### ISSUE TITLE
prevent fork exception

### ISSUE THREAD

**Issue by MurariKumar** [bitcoin-dot-org/bitcoin.org#1008]
Location: https://bitcoin.org/en/developer-guide#block-height-and-forking

how can i prevent fork exception in bitcoinj

**Comment by harding** [comment]
@MurariKumar that documentation is just a high-level overview of the system.  To deal with actual software problems in BitcoinJ, you'll need to ask BitcoinJ experts using the resources on their [community page](https://bitcoinj.github.io/#community).

I'm going to close this issue now.  If you did have a problem with the documentation that you linked to, let me know and I'll re-open.
