### ISSUE TITLE
Blockstack Summit 2015

### ISSUE THREAD

**Issue by john-light** [bitcoin-dot-org/bitcoin.org#1013]
- date: 2015-09-12  
    - title: Blockstack Summit 2015  
    - venue: D'Agostino Hall, New York University  
    - address: 108 W 3rd St  
    - city: New York, NY  
    - country: USA  
    - link: http://blockstack.org/summit

**Comment by carnesen** [comment]
@john-light What's the intended action on this open issue?

**Comment by john-light** [comment]
@carnesen https://bitcoin.org/en/events has a button that says "Submit an event" and when you press it, it automatically creates an issue in this format so I'm assuming this is how events are added to the calendar.

**Comment by harding** [comment]
What @john-light says is correct.  One of the site maintainers will take the information provided, do some quick checking, and add it to the [events file](https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/_events.yml).  We usually batch updates every few days.

More information can be found here: https://github.com/bitcoin-dot-org/bitcoin.org#events

**Comment by harding** [comment]
@john-light thanks for submitting your event.  It should appear on the website within the next 15 minutes.

**Comment by john-light** [comment]
Thanks @harding!
