### ISSUE TITLE
Build Bitcoin Core 0.11

### ISSUE THREAD

**Issue by Ryder95** [bitcoin-dot-org/bitcoin.org#1021]
Hello! Can I ask you about building Bitcoin Core 0.11 on Windows 7? I run ./configure in msys-shell and get the error: "configure: error: lib missing". Where I see list of libs, that I needed. Thank you for answer!

**Comment by harding** [comment]
@Ryder95 This issue tracker is only for issues related to the Bitcoin.org website, so I'm going to close it.  However, a quick web search found this article:

- http://bitcoin.stackexchange.com/questions/587/how-do-i-build-bitcoin-source-in-windows-7

In addition, I asked on IRC and one of the devs said that cross-compiling using Linux is much easier than trying to compile on Windows, although if you're new to cross compiling, that may not be the case.

If you need additional help, I suggest you try one of the places linked here: https://bitcoin.org/en/development#dev-communities

Good luck!
