### ISSUE TITLE
Document instructions for running Bitcoin Core as a daemon on Mac OS X

### ISSUE THREAD

**Issue by rnrkrft** [bitcoin-dot-org/bitcoin.org#1023]
Just tell me, what to do, to help a little.

rnr.krft@gmail.com

**Comment by carnesen** [comment]
Could you please elaborate on what you're trying to do and how far you got?

The installation instructions [on the main site README](https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/README.md) are pretty much the same for Mac and Linux. One difference is that where it says "Install binary libraries and tools", instead of running that apt-get command, you'll need to make sure you've installed the XCode command-line tools, or the full XCode, which is much much larger. There's known issues, however, at the "bundle install" step on Mac OS X. See here: https://github.com/bitcoin-dot-org/bitcoin.org/issues/1022

**Comment by rnrkrft** [comment]
I saw this:

"Bitcoin Core Daemon
If you can provide instructions and screenshots for running the latest version of Bitcoin Core daemon on OS X Yosemite, please open an issue and we’ll tell you what we need."

I would be able to do so, once the setup is through. And more than this I have a second partitition with El Capitan, on wich I could test.

**Comment by carnesen** [comment]
Thanks for elaborating. I see now what you mean. There's just a placeholder for the instructions for running Bitcoin Core as a daemon on Mac OS X. https://bitcoin.org/en/full-node#osx-daemon

AFAIK, the instructions are identical to Linux (https://bitcoin.org/en/full-node#ubuntu-daemon) with the following exceptions:

- The default data directory on Mac is "~/Library/Application Support/Bitcoin". On Linux it's "~/.bitcoin"
- I'm not sure whether or not the crontab suggestion in "Optional: Start Your Node At Boot" would work on Mac. It seems that the "crontab" command exists on Mac, but I've never used it.

I suggest changing the title of this issue to something like "Document instructions for running Bitcoin Core as a daemon on Mac OS X" and we can treat it as a TODO task. IMO the Mac instructions can just reference the Linux instructions and point out any salient differences as above, no need for separate screenshots etc.

**Comment by rnrkrft** [comment]
OK.

I have a look tomorrow.

Rainer
__
Dipl. Ök. Rainer Kraft
staatl. gep.  Wirtschaftsinformatiker
Informatiker VDP / Systemanalyse
Bäckerstr. 5
31812 Bad Pyrmont
sip 05281/9672625
mobil 0151/64732912
email rnr.krft@gmail.com

**Comment by rnrkrft** [comment]
Perhaps I need some advice too.

Running the app on my mac - bitcoin-QT that is - shows 400 to 500% CPU.
The bitcoin daemon uses 40 to 120% CPU.

Very strange.

**Comment by harding** [comment]
The GUI (-qt) is a CPU hog on my machine (Linux, PC) compared to the daemon as well, although not to the same degree as what you're reporting.  Once you finish catching up to the tip of the chain, the processor usage should even out on both programs.

**Comment by rnrkrft** [comment]
Sorry, that I am late. It is not as easy, as it looks on the first sight. I struggle with Bitcoin and Namecoin (that uses the same build instructions as Bitcoin). Just to go into the build process. Not necessary for Bitcoin.

The Bitcoin executables are working at of the box (both of the downloads). The default data directory is „~/Library/Application Support/Bitcoin/„. (in OS X there is no need for capitals). The crontab works on OS X, but OS X uses lauchctl to load and unload daemons/agents in launchd. Therefore you need to make a .plist config-file:
https://developer.apple.com/library/mac/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/CreatingLaunchdJobs.html <https://developer.apple.com/library/mac/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/CreatingLaunchdJobs.html>
I have not done this yet.

If you need to run bitcoind for any needs, it is hard to figure out, what is going on. As I ran bitcoin-qt for the first time, it asked for the data directory. I didn't found out, where it stores that information (I use a flash-boot-disk - no room for a gigantic blockchain). I have no need for a GUI, but for a server. Now I can create a config file for the launchctl. It will take a lot of try and error tasks.

If I run a bitcoin service, I will report again...
