### ISSUE TITLE
Use GitHub issues for TODOs instead of the wiki

### ISSUE THREAD

**Issue by carnesen** [bitcoin-dot-org/bitcoin.org#1024]
Currently there are TODOs for the site in two different places, [the site wiki](https://github.com/bitcoin-dot-org/bitcoin.org/wiki/Documentation-TODO) and [the repo's "issues" on GitHub](https://github.com/bitcoin-dot-org/bitcoin.org/issues). Shall we consolidate the former into the latter? The text TODO list lacks many useful features available like being able to have discussion in context and determine which commit(s) completed the task. I'd be happy to take this on if others think it's a good idea.

**Comment by kanzure** [comment]
Yep, I think it makes sense to have TODOs in github issues. For collaborative editing the wiki is a good idea when the TODOs require group collaboration on the text. TODOs are issues.

**Comment by saivann** [comment]
Thanks for the suggestion! A good part of the content on this TODO list seems to be proposals rather than real TODOs. I'm not sure if moving the later to GitHub issues would really be helpful, but I'm fine with the idea if someone thinks it is.

**Comment by harding** [comment]
I think turning some of the todos into issues would be a good idea.  However, I am a little concerned about scope creep for documentation issues---there are hundreds of facets of Bitcoin that I'd like to see documented, but I don't really want to have hundreds of open issues.

Previously, when we were first writing the docs, we only created an issue for a new major section when someone was about to begin writing it.  That way we knew it was in progress, nobody else started writing duplicate content, and we also had a chance to publicly discuss what should go into that documentation.

Building on this, my preference would to only open issues for documentation in three cases:

1. There's something wrong with the currently published documentation.  (True issue)

2. The documentation already covers a subject, but it's missing something important.  (Focused todo)

3. Somebody is (or soon will be) writing documentation about something.  (Claim/discussion todo)

Does that make sense?

**Comment by harding** [comment]
@carnesen you seem to be opening issues for documentation you plan to write in the near future, which is exactly how I'd like to see todo issues used.  With that being the case, do you think it's ok to close this issue?

**Comment by carnesen** [comment]
Was just a suggestion. Combo TODO list + issues as outlined above'll work too. Closing this one...
