### ISSUE TITLE
Accettable OP_RETURN usage

### ISSUE THREAD

**Issue by RCasatta** [bitcoin-dot-org/bitcoin.org#1029]
I am working with wallet developers to integrate a plugin that let's users to optionally write arbitrary data in OP_RETURN. It's a separate stand-alone function in a separate window than regular wallet operations. The purpose of that transaction is explicitly to write data on OP_RETURN, not to transfer bitcoin. The transaction is not sent to someone else so it cannot be used to spam users.
One developer is concerned about the use of OP_RETURN and the possible delisting of his wallet on the bitcoin.org web site because of its use. For this reason he don't want to integrate the plugin in his wallet.
Is it a legitimate worry?
If yes, is there some accettable OP_RETURN usage?

Taking the opportunity to compliments for the great work for the community.
Best

**Comment by luke-jr** [comment]
Acceptable OP_RETURN use is to commit to external data, or to encode necessary metadata with a transaction. Writing arbitrary messages that get included on the blockchain is *always* spam; regardless of the transaction's recipient, every node must still download it. The fact that you are not intending to transfer bitcoins at all just makes the entire "transaction" itself spam whether or not an OP_RETURN is included in it.

I would support delisting any wallet software explicitly supporting such spam (or any other kind of harm to Bitcoin).

**Comment by crwatkins** [comment]
@RCasatta If the purpose is not to transfer bitcoin, is the purpose to use the blockchain to record non-Bitcoin related information?

**Comment by RCasatta** [comment]
I personally don't know for sure... But if many found useful and valuable using the blockchain and his derived property for other purpose than transferring bitcoin and they are going to pay the fee for that why not? Colored coins and Timestamping services are doing the same.
The problem is that nodes aren't payed for their resource usage but anyway Bitcoin protocol cannot forbid this kind of interaction (banning op_return can only make thing worse as we saw) you can just discourage it by not including this kind of services on bitcoin.org but if people will find this useful the blockchain will be used also for this.
I cannot see that as a bad thing since fees are paying the miners and securing the network.
Even if I am agree that the main purpose of the blockchain is to transfer bitcoin, many times things aren't used for what they are thought for.

**Comment by dexX7** [comment]
Support for creating `OP_RETURN` raw transactions was merged into Bitcoin Core via https://github.com/bitcoin/bitcoin/pull/6346, which sets a precedence for these kinds of integration in my opinion.

**Comment by luke-jr** [comment]
@dexX7 Please do not read unnecessary things into actions, especially when they are explicitly false.

**Comment by fraggle222** [comment]
If OP_RETURN allows any data to be included and there are no rules in bitcoin to enforce what data is included (other than length), then by virtue of website policy we should not enforce some arbitrary rule here. If there are meant to be restrictions on OP_RETURN, then those restrictions should be built in to bitcoin (with appropriate BIP and/or pull request to bitcoin-core). Not enforced as a website policy.
