### ISSUE TITLE
Document that the RPC interface supports SSL, but its use is discouraged

### ISSUE THREAD

**Issue by carnesen** [bitcoin-dot-org/bitcoin.org#1036]
As I understand it, the RPC interface supports SSL, but its use is discouraged. We should add a few words to the developer documentation saying as much, something along the lines of [this answer on StackExchange](http://bitcoin.stackexchange.com/a/39118/7412):

"The RPC interface isn't designed to be used in any scenario which would require SSL, which would be access over the internet or other untrusted networks. It doesn't have the necessary denial of service protections or review to make it safe for use this way, and so letting potentially malicious clients connect to it would be incredibly unwise. If you need to talk to a remote bitcoind instance you are better off tunneling with SSH or stunnel which will provide a secure, authenticated path without exposing the socket any further than localhost."

**Comment by harding** [comment]
I just asked in #bitcoin-dev and @jonasschnelli pointed me to https://github.com/bitcoin/bitcoin/pull/5677 which will remove SSL support.  For details, see the comments starting here: https://github.com/bitcoin/bitcoin/pull/5677#issuecomment-71181146

If you want to add a quick note to the docs about SSL support, I'd be fine with that, but I'd suggest against spending any time on it that could be better used elsewhere.

**Comment by harding** [comment]
Oh, if you want to mention that using ssh or some other sort of tunneling if the best way to remotely access the RPC, that would be good all on its own.

**Comment by carnesen** [comment]
I'm glad to hear that support for SSL will be dropped. In light of that, like you say there's no sense documenting it. Thanks for investigating.
