### ISSUE TITLE
Wallet Guide feedback

### ISSUE THREAD

**Issue by jangorecki** [bitcoin-dot-org/bitcoin.org#1038]
On the following page: https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/_includes/guide_wallets.md#offline-wallets
There is following text

> The primary advantage of offline wallets is their possibility for greatly improved security over full-service wallets. As long as the offline wallet is not compromised (or flawed) and the user reviews all outgoing transactions before signing, the user's satoshis are safe even if the online wallet is compromised.

According the info on reddit [here](https://www.reddit.com/r/Bitcoin/comments/36qcpc/hierarchical_deterministic_bitcoin_wallets_that/) it looks like above info is not true because *child private keys* and *master public key* (all are stored in networked wallet) are sufficient to compromise offline wallet.

A minor suggestion I would also regarding point 1:

> Start the wallet software in offline mode to create the parent private and public keys.

This line could include the link to a page or manual describing how to start official client in offline mode.

**Comment by harding** [comment]
In an offline wallet setup, no private key should ever leave the offline part---so your statement that "child private keys and master public key [are] all are stored in networked wallet" is incorrect with regard to the child private keys.

I just read the linked doc and I don't see how you came to this conclusion, but if you can point out  the specific sentence that confused you, I'd be happy to clarify it.

> This line could include the link to a page or manual describing how to start official client in offline mode.

Starting Bitcoin Core in offline mode is as simple as starting it on a computer with no Internet connection; this is also true of all other offline wallets I've used (Electrum and Armory).  I would be happy to link to up-to-date documentation about this, but I don't know of any that mentions Bitcoin Core's new watch-only support.  (I hope to write some, but that's at least a month down my todo list.)

**Comment by jangorecki** [comment]
> Unfortunately, in all existing HD wallets—including BIP32 wallets—an attacker can easily recover the master private key given the master public key and any child private key.

Hm... I was thinking the child private key is stored in networked wallet. Thanks for clarification. Closing the issue.
