### ISSUE TITLE
Blockchain @ Birmingham

### ISSUE THREAD

**Issue by nihaodavid** [bitcoin-dot-org/bitcoin.org#1039]
- date: YYYY-MM-DD
      title: "Blockchain@Birmingham"
      venue: "Learning Center LG14@ University of Birmingham"
      address: "Edgbaston, Birmingham, WestMidlands, UK"
      city: "Birmingham"
      country: "United Kingdom"
      link: "https://blockchainbirmingham.wordpress.com"

**Comment by harding** [comment]
@nihaodavid thanks for submitting your event!  It should appear on the website within 15 minutes.
