### ISSUE TITLE
Remove Hive Wallet iOS

### ISSUE THREAD

**Issue by windsok** [bitcoin-dot-org/bitcoin.org#1040]
Hive wallet for iOS is currently completely non functional - the only way to recover funds in a hive wallet is by importing the private key into another wallet (which i've had to do).

I would recommend that Hive for iOS be removed from wallets page until these issues are resolved.

https://twitter.com/hivewallet/status/635577092772524032

**Comment by windsok** [comment]
Author of the wallet also recommends not to use it (for a different issue) here - https://github.com/hivewallet/hive-ios/issues/49

**Comment by harding** [comment]
Hive for Mac was removed in PR #987 and (I just checked) is not displayed on the site:

https://bitcoin.org/en/choose-your-wallet

**Comment by crwatkins** [comment]
@harding  #987 Removed Hive for Mac, not Hive for iOS.

**Comment by harding** [comment]
Oh, bugger.  I need to learn to read.  Sorry.

**Comment by harding** [comment]
@w-hive what is your opinion on delisting all of the Hive wallets from Bitcoin.org until you're able to address these issues?

**Comment by w-hive** [comment]
Yeah for sure, pull iOS -- and thanks for asking. Unfortunately we're out of funds and no real development is going on right now, although the Web version has been updated, and should be fine. We'll be putting up a message about this shortly and pulling our iOS app from the Store.

If we get our house refurnished we'll pop a note in here and ask to be restored.

**Comment by harding** [comment]
@w-hive thank you for your response and your candor.  I'll open a PR momentarily to remove the iOS wallet.

We look forward to the day we can re-list the client-side wallets.
