### ISSUE TITLE
bitcoin address

### ISSUE THREAD

**Issue by 111010** [bitcoin-dot-org/bitcoin.org#1043]
Bitlocker locked my address and had to format my F drive (it encrypted 25% and then not responding) is there any way of recovering my bitcoins with only my passphrase and address (i dont have my private key and my backup is deleted)

**Comment by carnesen** [comment]
@111010 Sorry to hear your computer got hit by Bitlocker. This GitHub repo holds the source code for the bitcoin.org web site, and issues filed here should be suggestions or bug reports for the site itself. For questions about key recovery, you'd be better off posting to one of the [Bitcoin community forums](https://bitcoin.org/en/community#forums).

**Comment by saivann** [comment]
@111010 Indeed, the forums are a better place to ask for support. Best of luck...

**Comment by 111010** [comment]
i am sorry (i am new here) i just wasn't sure where to ask about it and thanks :)

**Comment by wilbns** [comment]
@111010 - no worries. :)
