### ISSUE TITLE
IsStandard for P2SH

### ISSUE THREAD

**Issue by jonasschnelli** [bitcoin-dot-org/bitcoin.org#1052]
In the developers documentation there is a point where it says 

 > However, when you go to spend that output, peers and miners using the default settings will check the redeem script to see whether or not it’s a standard pubkey script. If it isn’t, they won’t process it further—so it will be impossible to spend that output until you find a miner who disables the default settings.

[https://bitcoin.org/en/developer-guide#non-standard-transactions]

I think the developers documentation should be updated an mention to merge of https://github.com/bitcoin/bitcoin/pull/4365

**Comment by harding** [comment]
Thanks!  I'll update this today.
