### ISSUE TITLE
Blockchain: Building information systems for social good

### ISSUE THREAD

**Issue by ProvenanceHQ** [bitcoin-dot-org/bitcoin.org#1062]
- date: 2015-09-27
      title: "Blockchain: Building information systems for social good"
      venue: "Victoria and Albert Museum"
      address: "Victoria and Albert Museum, Cromwell Rd, SW7 2RL"
      city: "London"
      country: "United Kingdom"
      link: "http://www.meetup.com/This-Happened-London/events/222502201/"

**Comment by harding** [comment]
Sorry we didn't get this on the events page in time; however, since it was on Meetup.com, it was probably listed anyway (we pull data about Bitcoin events from there).
