### ISSUE TITLE
Bitcoin Africa Conference 2016

### ISSUE THREAD

**Issue by bitcoinevents** [bitcoin-dot-org/bitcoin.org#1064]
- date: 2016-03-03
      title: "Bitcoin Africa Conference 2016"
      venue: "Sandton, Johannesburg"
      address: "Sandton, Johannesburg"
      city: "Johannesburg"
      country: "South Africa"
      link: "http://bitcoinconference.co.za/"

**Comment by wilbns** [comment]
@bitcoinevents Hello! Can you please find out the venue?

**Comment by bitcoinevents** [comment]
HI there

The venue will be the Focus Rooms in Johannesburg:

https://www.google.com/maps/dir/''/focus+rooms/data=!4m5!4m4!1m0!1m2!1m1!1s0x1e9573cd9cbbbfb3:0xabc0b6ab0f373626?sa=X&ved=0CHYQ9RcwDmoVChMI4fjDiJiZyAIVA7oUCh03DAan

Regards
Sonya

Sonya Kuhnel
Co-host of the Bitcoin Africa Conference
Bitcoin Events Pty Ltd
*Cell: *+ 27 83 3001170
*Twitter:* @BitcoinConf_ZA
*Website:* www.bitcoinconference.co.za

**Comment by harding** [comment]
Added in 7a7d7e0ff07fd1591f1933a293e4a971e43b1a9a, which should appear on the website within the next 15 minutes.  Thanks for submitting your event!
