### ISSUE TITLE
opcode or "op code"?

### ISSUE THREAD

**Issue by laanwj** [bitcoin-dot-org/bitcoin.org#1068]
In the developer reference we refer to "op codes" or "OP codes":

- https://bitcoin.org/en/developer-reference#serialized-blocks
- https://bitcoin.org/en/glossary/op-code

In what I've read before, e.g. assembly manuals, the word was always "opcodes".  Wikipedia seems to confirm this https://en.wikipedia.org/wiki/Opcode same for the bitcoin wiki: https://en.bitcoin.it/wiki/Script

Is there a specific reason to put it as two words?

**Comment by harding** [comment]
The reason that it's two words is that I didn't know it should be one word.  I'll open a PR to fix it as soon as a get a chance.  Thanks!

**Comment by laanwj** [comment]
If everyone agrees this is the way forward I'm willing to make the changes as well

**Comment by carnesen** [comment]
I did a lil Googling on the subject and "opcode" does seem to be more
standard than "op code".

**Comment by harding** [comment]
I think there are some images that need to be updated too, which might be easier for me to do (the images are all generated with GraphViz).  However, if someone wants to do a quick s/// on the _includes directory, we can get that merged quickly and clean up any edge cases later.

**Comment by harding** [comment]
#1107 makes this change.  Thanks for the suggestion!
