### ISSUE TITLE
Minimum requirements lists 50 GB, needs update

### ISSUE THREAD

**Issue by sgornick** [bitcoin-dot-org/bitcoin.org#1075]
Not sure what buffer should be included, or I'ld update it with some reasonable guesstimate myself.

"50 gigabytes of free disk space"

https://bitcoin.org/en/full-node#minimum-requirements

**Comment by harding** [comment]
Agreed.  When we added the recent Bitcoin Core pages, I added a variable to the site configuration that holds the current block chain size.  When I get a chance, I'm going to change every place where we currently statically list the block chain size to use that variable, which will allow us to easily update it every three months or so.  This will also allow us to close #749

**Comment by jonasschnelli** [comment]
Should we not mention pruning here?
You can run a full node with full validation with ~2GB of diskspace. You just lose the ability to query old transactions (`-txindex`) and you will considered as p2p leech because you don't serve historical blocks.

**Comment by harding** [comment]
@jonasschnelli absolutely.  I have that [variable in the config file](https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/_config.yml#L219) too, and I plan to rewrite the text to accommodate it.  (But thanks for reminding me!)

**Comment by saivann** [comment]
@harding Thanks!
