### ISSUE TITLE
DevCore: Developing the Developers [Date Correction]

### ISSUE THREAD

**Issue by BruceFenton** [bitcoin-dot-org/bitcoin.org#1079]
- date: "2015-10-16"  [Corrected from Oct 18]
      title: "DevCore Workshop: Developing the Developers"
      venue: "Draper University"
      address: "San Mateo"
      city: "CA"
      country: "USA"
      link: "bitcoinfoundation.org"

2015-10-18
DevCore Workshop: Developing the Developers
San Mateo, CA, USA

**Comment by harding** [comment]
Updated in 7a7d7e0ff07fd1591f1933a293e4a971e43b1a9a, which should appear on the website within the next 15 minutes.  Thanks for the update!
