### ISSUE TITLE
Bitcoin Conference Minsk*Gambling 2015

### ISSUE THREAD

**Issue by voffkas** [bitcoin-dot-org/bitcoin.org#1080]
- date: 2015-10-14
      title: "Bitcoin Conference Minsk*Gambling 2015"
      venue: "Renaissance Minsk Hotel"
      address: "Dzerzhinsky Avenue 1E"
      city: "Minsk"
      country: "Belorussia"
      link: "http://minsk.rgweek.ru/en"

**Comment by voffkas** [comment]
Pleazzz! :)

**Comment by harding** [comment]
I'm sorry that we didn't get your event listed in time.
