### ISSUE TITLE
EDIT for North American Bitcoin Conference

### ISSUE THREAD

**Issue by junior8k** [bitcoin-dot-org/bitcoin.org#1092]
- date: 2016-01-21
      title: "The North American Bitcoin Conference"
      venue: "James L Knight Center"
      address: "400 SE 2nd Ave"
      city: "Miami, Florida"
      country: "United States of America"
      link: "http://www.btcmiami.com"

**Comment by harding** [comment]
Thanks for submitting your update; it should appear on the website within about 15 minutes.
