### ISSUE TITLE
New glossary term suggestion: Premine

### ISSUE THREAD

**Issue by abderraouf-adjal** [bitcoin-dot-org/bitcoin.org#1093]

**Comment by harding** [comment]
Thanks for the suggestion!  I don't think I've ever heard that term in context of Bitcoin, only in the context of altcoins.  For that reason and because we don't use it anywhere in our documentation, I'm not sure it should be part of the Bitcoin.org glossary.

**Comment by luke-jr** [comment]
I agree it shouldn't be.

**Comment by saivann** [comment]
Closing the issue (agreed too), but thanks nevertheless for the suggestion!
