### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by wcbs2015** [bitcoin-dot-org/bitcoin.org#1094]
- date: 2016-11-30
      title: "West Coast Bitcoin Summit"
      venue: "JW Marriott Los Angeles L.A. LIVE"
      address: "900 West Olympic Boulevard"
      city: "Los Angeles"
      country: "United States"
      link: "https://wcbs2015.com"

**Comment by harding** [comment]
Thank you for submitting your event!  It should appear on the website within about 15 minutes.
