### ISSUE TITLE
Visual glitch of "Bitcoin Core" header on download page in Safari.

### ISSUE THREAD

**Issue by oliverdowling** [bitcoin-dot-org/bitcoin.org#1095]
I'm on Mac OS X 10.11 El Capitan.
Occurs in Safari 9.0.
Does not occur in Chrome (46.0.2490.71) or Firefox (41.0.2).

Happens when width is greater than about 1500px, and less than about 1900px. Appears to start happening again at about 2550px, but not sure past that.
Parts of "Bitcoin Core" are cut off. Which parts are cut off changes as window is resized.

Screenshots:
![screen shot 2015-10-21 at 12 30 58](https://cloud.githubusercontent.com/assets/431047/10625527/d97b8716-77ef-11e5-8890-242141c60a6c.png)
![screen shot 2015-10-21 at 12 32 21](https://cloud.githubusercontent.com/assets/431047/10625528/d9df5b56-77ef-11e5-8554-e008537ef12a.png)

**Comment by saivann** [comment]
Thanks for reporting this! This is likely Safari poor SVG support again..
