### ISSUE TITLE
No mention of new minrelaytxfee default

### ISSUE THREAD

**Issue by achow101** [bitcoin-dot-org/bitcoin.org#1096]
How come there is absolutely no mention that the minrelaytxfee default has changed? The commit and pull request are not mentioned at all and there is no heading that talks about the change. However, the [email](https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2015-October/011545.html) sent out to bitcoin-dev does include that. So why doesn't the website have it?

**Comment by achow101** [comment]
I added this and submitted a PR, 1097

**Comment by gmaxwell** [comment]
Please don't modify the release notes. The correct release notes are included with Bitcoin Core. The ones on the site are incorrect.
