### ISSUE TITLE
Vulnerability in UPnP library used by Bitcoin Core

### ISSUE THREAD

**Issue by hoangpnr** [bitcoin-dot-org/bitcoin.org#1098]
Source File: _alerts/2015-10-12-upnp-vulnerability.md

**Comment by harding** [comment]
I'm closing this as you haven't reported any issue; if that's a mistake, please provide additional information and I'll reopen the issue.  Thanks!

**Comment by hoangpnr** [comment]
I'm sorry about that I will report later
