### ISSUE TITLE
Release notes for 0.11.1 on the site are incorrect

### ISSUE THREAD

**Issue by gmaxwell** [bitcoin-dot-org/bitcoin.org#1099]
The release notes on the site do not match the ones distributed in 0.11.1.  It looks like they were not updated after the initial release candidate for the second release candidate or the release.

The correct release notes are in the package itself or at https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-0.11.1.md

This was reported to me by Hyena on Bitcoin talk.

**Comment by saivann** [comment]
@gmaxwell Thanks for reporting the issue. This is indeed what happened.

@harding Maybe we should always keep a todo list when preparing release PRs - With at least: Add and test magnet link, Add release date, Update release notes.
