### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by eleuteromaniaco** [bitcoin-dot-org/bitcoin.org#1104]
- date: 2015-12-04
      title: "laBITconf 2015: Latin American Bitcoin Conference"
      venue: "EBC Campus Dinamarca"
      address: "Dinamarca 32, Col. Juarez, Del. Cuauhtemoc"
      city: "Mexico D.F."
      country: "Mexico"
      link: "http://www.labitconf.com/"

**Comment by harding** [comment]
Thank you for submitting your event!  It should appear on the website within about 15 minutes.
