### ISSUE TITLE
Block version 4 will likely be BIP 65, not BIP 62

### ISSUE THREAD

**Issue by JustinDrake** [bitcoin-dot-org/bitcoin.org#1106]
See [here](https://twitter.com/petertoddbtc/status/657563877123735552).

Source File: _includes/devdoc/ref_block_chain.md

This paragraph is outdated:

```
Version 4 blocks will likely be introduced in the near-future as specified in draft BIP62. Possible changes include:
```

**Comment by harding** [comment]
Heh, I should've caught that when I updated the block version 3 text.  Thanks!  I'll update this shortly and see if I can work in a mention of the pending versionbits stuff for future upgrades.  (This is will be PR'd since it isn't a simple correction.)

**Comment by harding** [comment]
@JustinDrake when you have a moment, can you please review #1118 which should correct this?  Thanks again for reporting!
