### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by bitcoinsardegna** [bitcoin-dot-org/bitcoin.org#1111]
- date: 2015-10-29
      title: "Meeting Bitcoin Sardegna"
      venue: "Enò"
      address: "Vico Carlo Felice 10/12"
      city: "Cagliari"
      country: "Italy"
      link: "http://www.bitcoinsardegna.it/wp/?p=310"

**Comment by harding** [comment]
Thanks for submitting your event!  It should appear on the website within 15 minutes.
