### ISSUE TITLE
Blockchain University Demo Night

### ISSUE THREAD

**Issue by schwentker** [bitcoin-dot-org/bitcoin.org#1116]
- date: 2015-11-02
      title: Blockchain University Demo Night!
      venue: Orange SV
      address: Spear St
      city: San Francisco
      country: USA
      link: http://meetup.com/blockchainU/events/226155698

**Comment by harding** [comment]
@schwentker hi.  This is rather a lot of events you're submitting; is it possible to limit the number of submissions to one or two per month?  Also, any events on Meetup.com that include the word "Bitcoin"  will automatically appear on our map when we update the website.

**Comment by harding** [comment]
@schwentker thanks for submitting your event; it should appear on the website within 15 minutes.
