### ISSUE TITLE
Moneylab#2

### ISSUE THREAD

**Issue by maxdovey** [bitcoin-dot-org/bitcoin.org#1119]
- date: 2015-12-03
      title: "Moneylab#2 Economies of Dissent"
      venue: "Pakhuis De Zwijger"
      address: "Piet Heinkade 179 "
      city: "1019 HC Amsterdam"
      country: "The Netherlands"
      link: "http://networkcultures.org/moneylab/"

**Comment by harding** [comment]
Thanks for submitting your event!  It should appear on the website within about 15 minutes.
