### ISSUE TITLE
Dublin blockchain hackathon

### ISSUE THREAD

**Issue by Cryophoenix** [bitcoin-dot-org/bitcoin.org#1125]
- date: 2015-11-06
      title: "Dublin blockchain hackathon"
      venue: "DCU Innovation Campus"
      address: "old finglas road"
      city: "Dublin"
      country: "Ireland"
      link: "https://blockchain-hackathon.com"

**Comment by harding** [comment]
@Cryophoenix thanks for submitting your event; it should appear on the website within 15 minutes.
