### ISSUE TITLE
Santa Claus Bitcurex Bitcoin Event

### ISSUE THREAD

**Issue by maciejziolkowski** [bitcoin-dot-org/bitcoin.org#1127]
- date: 2015-12-08
      title: "Santa Claus Bitcurex Bitcoin Event"
      venue: "Centrum Golf"
      address: "Burakowska 15"
      city: "Warsaw"
      country: "Poland"
      link: "https://www.facebook.com/events/979552578733820/"

**Comment by harding** [comment]
Thanks for submitting your event!  It should appear on the website within 15 minutes.
