### ISSUE TITLE
practical workshop

### ISSUE THREAD

**Issue by gonxi** [bitcoin-dot-org/bitcoin.org#1130]
- date: 2015-11-20
      title: "practical workshop"
      venue: "Las Naves"
      address: "Joan Verdeguer 16"
      city: "Valencia"
      country: "Spain"
      link: "http://avalbit.org/actividades/taller-practico-bitcoin/"

**Comment by harding** [comment]
Thanks for submitting your event!  It should appear on the website within 15 minutes.
