### ISSUE TITLE
Many of the torrent trackers are broken

### ISSUE THREAD

**Issue by laanwj** [bitcoin-dot-org/bitcoin.org#1141]
I always seed the torrent. There have been some peers. But my torrent client tells me:
- udp://tracker.publicbt.com:80 Announce error: Connection failed - Today 06:13:12 AM
- udp://tracker.ccc.de:80 Announce error: Connection failed - Today 06:13:28 AM
- udp://open.demonii.com:1337 Announce error: Connection failed - Today 06:12:56 AM

udp://tracker.openbittorrent.com:80 and udp://tracker.coppersurfer.tk:6969 are working.

Don't know enough about bittorrent if this is a problem with the torrent file, or with my client, but I heard it from someone else on IRC too.

**Comment by saivann** [comment]
Thanks, agreed! If someone can come up with a good suggestion for better open trackers, I can take care of updating the configuration and scripts.

Having dead trackers does not make any harm though, that I know, but it seems clear that some of them have been down for way too long to be of any value.

**Comment by theymos** [comment]
torrentfreak.com recently [listed](https://torrentfreak.com/demonii-torrent-tracker-shuts-down-for-good-151116/?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+Torrentfreak+%28Torrentfreak%29) three alternative trackers after demonii.com shut down: 

*  udp://tracker.openbittorrent.com:80
* udp://tracker.coppersurfer.tk:6969
* udp://tracker.leechers-paradise.org:6969

Might be nice to add these for the next release.

**Comment by saivann** [comment]
@theymos Thanks, I replaced demonii by leechers-paradise for now, not sure if we should drop the other two ones (openbittorrent was down for a while but eventually recovered for example).

**Comment by wbnns** [comment]
Just wanted to follow up on this - is it still a concern? If not, will close. FWIW, I just downloaded Core using the tracker and it seemed like it worked well:

![image](https://cloud.githubusercontent.com/assets/1130872/22736481/ef8ff564-edc3-11e6-89e4-f493c0d4bb0d.png)

**Comment by laanwj** [comment]
No, this is no longer a concern, had forgot about this a bit.

**Comment by wbnns** [comment]
@laanwj Ok, great, thanks for the update.

**Comment by Sjors** [comment]
Some of these trackers are (still) dead, see #3087. However the remaining trackers are still good enough.
