### ISSUE TITLE
BIP001: Winter Edition

### ISSUE THREAD

**Issue by jrh11** [bitcoin-dot-org/bitcoin.org#1143]
- date: 2016-01-12
      title: "BIP001: Winter Edition"
      venue: "Leopolis"
      address: "Miskevycha Square, 9"
      city: "Lviv"
      country: "Ukraine"
      link: "http://bip001.com"

**Comment by harding** [comment]
@jrh11 hi, could you let us know when you have an address please?

**Comment by jrh11** [comment]
@harding hi, yes, sure

**Comment by TheFuzzStone** [comment]
Hi all ! ;-) and sorry for my English.

My name is Michael, I live in Lviv, Ukraine. I'm an enthusiast of bitcoin and wanna go to BIP001 but a ticket prices is too high for me. My salary is 180 USD, ticket price is 100 USD. 

Here you can buy a tickets http://bip001we.ticketforevent.com/en/

I would appreciate your help. If I can not collect necessary sum of a ticket --- I will return all donations to their owners.

This is my bitcoin-adress 17W4bZF8ugnuYkpG8sq5fbZQSN63qpX3yp

**Comment by harding** [comment]
Thanks for submitting your event.  It should appear on the website in about 15 minutes.
