### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by mollywaldron** [bitcoin-dot-org/bitcoin.org#1145]
- date: 2015-12-4-5
      title: "Latin American Bitcoin Conference" 
      venue: "Escuela Bancaria y Comercial (EBC) - Dinamarca campus"
      address: "Dinamarca No. 32, Col. Juárez, C.P. 06600"
      city: "Del. Cuauhtémoc, Ciudad de México"
      country: "Mexico"
      link: "http://labitconf.com/"

**Comment by harding** [comment]
@mollywaldron I just wanted to let you know that we already had your event listed on bitcoin.org/events .  Thanks for submitting it anyway!
