### ISSUE TITLE
More full node coverage

### ISSUE THREAD

**Issue by luke-jr** [bitcoin-dot-org/bitcoin.org#1148]
It would be nice if someone with web design skills could extend the Bitcoin Core page(s) or at least the wallet directory to cover more full nodes. At the very least, Bitcoin LJR is available for the end user market. @petertodd's RBF forks may also be popular. @btcdrak has an addrindex fork, but I'm not sure how useful that is to end users. Probably should consider if btcsuite has any end user friendly options (I don't know).

**Comment by harding** [comment]
I briefly spoke to @luke-jr about this on IRC, and I think this is an excellent idea, and it sounds very flexible---a couple hours work for a simple page listing the alternatives or many hours of work to provide something more comprehensive.

I'm tagging this as Help Needed, which is our flag that help from outside the regular site contributors would be especially appreciated here.  If anyone wants to volunteer, please comment here and we can help you figure out what will work well.

Relevant links:

- LJR: http://luke.dashjr.org/programs/bitcoin-ljr/
- RBF tree for 0.11.x: https://github.com/petertodd/bitcoin/tree/replace-by-fee-v0.11.0
- addrindex: https://github.com/btcdrak/bitcoin/tree/addrindex

**Comment by petertodd** [comment]
ACK, good idea!

My RBF release is pretty bare-bones, so it's probably better to present it as evidence that there are alternative views of policy, rather than necessarily something that an average end-user would ever want to mess with. Probably doesn't belong on the standard "choose-your-wallet" page, but may belong on some kind of advanced view of it.

**Comment by cjennyc28** [comment]
K

**Comment by brandonmonkey87** [comment]
malt-ego  has nodes to map the whole network :)

**Comment by crwatkins** [comment]
Since this issue was opened, Bitcoin Knots was listed #1150 and a new wallet listing UX was implemented #3017 with a full node feature category.  This probably satisfies most of the intent of this issue, so I'll close it for now.   If not, let's open a new issue focused on the new UX.
