### ISSUE TITLE
Blockchain Technology Conference (BTC) 2016

### ISSUE THREAD

**Issue by meltdem** [bitcoin-dot-org/bitcoin.org#1158]
- date: 2016-05-02
      title: "Blockchain Technology Conference (BTC) 2016"
      venue: "Marriott Marquis, Times Square, New York City"
      address: "1535 Broadway "
      city: "New York"
      country: "USA"
      link: "http://www.btc2016.co/"

**Comment by harding** [comment]
Thanks for submitting your event.  It is now listed on the site.  (Commit ID: 4505da13b0047ef71fdc2c0d3aed46dceb188c21 )
