### ISSUE TITLE
Setting for Bitcoin node

### ISSUE THREAD

**Issue by JiMail** [bitcoin-dot-org/bitcoin.org#1160]
Hello,
Can someone tell me if this is correct, becaurse it seems to do,.. nothing.
maxconnections=16
maxuploadtarget=2048 per day
upnp=0
(settings in bitcoin.conf)

**Comment by harding** [comment]
@JiMail can you clarify what you mean by "nothing"?

**Comment by JiMail** [comment]
it seems that the settings won’t work in de .conf
so it’s all the same... bitcoin works as usual.. (normal)

Van: David A. Harding 
Datum: maandag 14 december 2015 19:34
Aan: bitcoin-dot-org/bitcoin.org 
Cc: JiMail 
Onderwerp: Re: [bitcoin.org] Setting for Bitcoin node (#1160)

@JiMail can you clarify what you mean by "nothing"?

**Comment by franckuestein** [comment]
Hi @JiMail, can you please post more info about your problem?
I mean... what are you trying to do and a detailed explanation to enable us to help you.

Thanks!
