### ISSUE TITLE
Documentation clarification: Guide - Transactions

### ISSUE THREAD

**Issue by dirkmc** [bitcoin-dot-org/bitcoin.org#1161]
In https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/_includes/devdoc/guide_transactions.md it says:

This pubkey hash can also be reliably repeated later, so it also does not need to be stored. The hash shortens and obfuscates the public key, making manual transcription easier and providing security against unanticipated problems which might allow reconstruction of private keys from public key data at some later point.

Is the part about providing security against unanticipated problems really a reason for hashing the public key?

**Comment by harding** [comment]
I don't know whether that factored into Nakamoto's thinking when he created P2PKH transactions, however this is a real security benefit even though it doesn't come into play in all possible scenarios.

**Comment by dirkmc** [comment]
Further down in the explanation it says

Bob’s signature script will contain the following two pieces of data:

1. His full (unhashed) public key, so the pubkey script can check that it hashes to the same value as the pubkey hash provided by Alice.

...

So if the public key is exposed at this step then there would be no security-related reason for hashing it in the earlier step, no?

**Comment by harding** [comment]
@dirkmc assuming addresses aren't being reused, the key isn't revealed until a transaction spending the output is broadcast.  At that point. the hypothetical attacker with their ECDSA-breaking scheme is racing against the time it takes to confirm the transaction.
