### ISSUE TITLE
Digital Money Forum 2016

### ISSUE THREAD

**Issue by Erikazee** [bitcoin-dot-org/bitcoin.org#1162]
- date: 2016-01-08
      title: "THE DIGITAL MONEY FORUM 2016"
      venue: "Venetian, Level 4 Marcello 4404 "
      address: "Venetian Hotel & Casino 3355 Las Vegas Blvd S, Las Vegas, NV 89109 "
      city: "Las Vegas, NV"
      country: "USA"
      link: "http://thedigitalmoneyforum.com/"

![digitalmoneylogo](https://cloud.githubusercontent.com/assets/16297507/11798653/9faae330-a281-11e5-8f8e-8d650cc1f4af.png)

**Comment by harding** [comment]
Thanks for submitting your event.  It should appear on the website in about 15 minutes.

**Comment by Erikazee** [comment]
Thank you!
