### ISSUE TITLE
releases feed contains no content

### ISSUE THREAD

**Issue by Dreamsorcerer** [bitcoin-dot-org/bitcoin.org#1163]
The releases feed does not contain the contents of the posts, only the title, making the feed somewhat useless.

https://bitcoin.org/en/rss/releases.rss

Please put the content of posts into the feed so that we can read about new releases in a RSS feed reader.

**Comment by Mirobit** [comment]
Got fixed.

**Comment by wbnns** [comment]
@Mirobit I believe this is referring to the `description` element in the RSS specification that provides a short summary alongside each entry. 

For example:
```
<item>
<title>Bitcoin Core version 0.13.1 released</title>
<link>https://bitcoin.org/en/release/v0.13.1</link>
<guid>https://bitcoin.org/en/release/v0.13.1</guid>
<pubDate>Thu, 27 Oct 2016 00:00:00 GMT</pubDate>
</item>
```

To address this issue, additional information providing a summary of the entry would be included in the excerpt above using a description tag.

[More info for technical context can be found here](https://validator.w3.org/feed/docs/rss2.html#sampleFiles).

**Comment by wbnns** [comment]
[Bounty](https://github.com/bitcoin-dot-org/bitcoin.org#earn-bitcoin-for-contributing): **10,000 bits / ~$20 USD**
