### ISSUE TITLE
Add prominent warning to Bitcoin Core info.

### ISSUE THREAD

**Issue by dabura667** [bitcoin-dot-org/bitcoin.org#1166]
![default](https://cloud.githubusercontent.com/assets/6586275/11916651/4840c564-a723-11e5-939e-433ff7c583bc.png)
Just an example of what I am talking about adding.

A LOT of new people download bitcoin core, connect it for the few minutes before they shut down their computer, send bitcoin to it from Coinbase etc., see it not show up forever, not know why their data caps are being used up so quickly, etc. etc.

This behavior is a strain on the network, as they will likely never finish syncing, so their time on the network was only used to take data and leech off bandwidth which they didn't benefit from, and neither did the network.

Bitcoin.org needs to do a better job educating people on the requirements of Bitcoin Core instead of trying to trick them into supporting the network.

Or at least make the wallet automatically revert to SPV mode for the wallet while the full node syncs in the background, because the extremely frequent case of "omg I sent bitcoin from Coinbase and it is not showing up in my Bitcoin Core!!!" is causing a negative image of Bitcoin.

**Comment by dabura667** [comment]
Or perhaps disable showing receive addresses on the wallet before fully synced. But that's a suggestion for Core, not here.

**Comment by jrmithdobbs** [comment]
Please close. Unproductive.

**Comment by dabura667** [comment]
@jrmithdobbs This issue is extremely productive. Explain yourself.

**Comment by harding** [comment]
I don't think this is a useful addition for several reasons:

1. We already have a warning both in the description and on the download page.

2. Other wallets have their own weaknesses, which don't carry such conspicuous warnings.

3. The upcoming Bitcoin Core 0.12.0 uses libsecp256k1 for verification, which provides a significant speed up for initial blockchain sync on most platforms, making this less of a concern for people who aren't bandwidth limited.

4. The "leech" terminology common in BitTorrent doesn't really apply to Bitcoin.  People who protect their wallet with Bitcoin Core help uphold the rules of the system even if all they do is download data.

**Comment by jonasschnelli** [comment]
I agree that users should be better educated before or during first start(s) of Bitcoin-Core GUI (not necessary for bitcoind).

But a warning might be the wrong direction...

I would like to see a SPV mode during IBD, people can receive and spend coins (under a warning of using SPV). During IBD we could reduce bandwidth and CPU usage (stretch time).

**Comment by luke-jr** [comment]
Probably should mention data transfer usage in there at least. Otherwise agree with @jonasschnelli

**Comment by dabura667** [comment]
> We already have a warning both in the description and on the download page.

https://bitcoin.org/en/download does have a slight warning about bandwidth and space, but nothing about "your bitcoin will not show up in your balance nor be able to be spent until syncing is complete."

Not to mention the warning is not in the first view, and you must scroll down to view. Anyone who's made an app before knows that a small fraction of users scroll down when the link they want is on the first view. (in this case, the download link)

> Other wallets have their own weaknesses, which don't carry such conspicuous warnings.

imo, anything that a new person with no knowledge of bitcoin would expect from software (ie. "I can reset my password right?", "I can receive bitcoin immediately after setup, right?" etc) that isn't true should be in a conspicuous color so they can notice it. Not an inconspicuous info paragraph-o-text that is at the bottom of the download page. Yes, I mean that a large portion of wallets should have a red warning about no password resets, but this is a separate issue.

> upcoming Bitcoin Core 0.12.0 uses libsecp256k1

This is nice, but it still will only shave off a few hours. I don't think it's unreasonable for a user to expect opening a program, sending something to it and seeing it show up instantly (especially in today's age), so seeing absolutely 0 indication that their funds arrived for 10 hours as compared to 20, or 3 hours as compared to 6 still doesn't really solve the problem.

> People who protect their wallet with Bitcoin Core help uphold the rules of the system even if all they do is download data.

More often then not, they uphold validating the headers, then maybe 100,000 blocks or so, then give up thinking they got tricked and that Bitcoin is a scam. Little do they know that the bitcoin was sitting on the blockchain waiting to be unlocked with their private key, but Core did nothing to inform them of it, so they think "oh this must be what happened with Mt. Gox or something, Bitcoin is a scam!" and don't even bother to post a question or search online. (First rule of customer support: behind every one person complaining about something, there are at least 3 other people who gave up because of it.)

> I would like to see a SPV mode during IBD, people can receive and spend coins (under a warning of using SPV). During IBD we could reduce bandwidth and CPU usage (stretch time).

This is a perfect long term solution. However, I think we need to somehow increase awareness of fully validating software's unique properties in general. Whether or not it is a red colored warning is irrelevant to me.

The goal is to increase awareness for the least tech-savvy user.

**Comment by harding** [comment]
@dabura667 thank you for your reply.  I don't think it's a good use of time to talk so much about adding a minor warning, so I'm going to close this issue.  If you would like to submit a PR making the change you think is appropriate, we can discuss that specific proposal.
