### ISSUE TITLE
Censorship of statements

### ISSUE THREAD

**Issue by benjyz** [bitcoin-dot-org/bitcoin.org#1169]
from #1165 "Further comments will be deleted. If you have any questions, please feel free to contact me directly."

appropriate forums are censored, and bitcoin-org is now censoring as well. so the statement on bitcoin-org is meaningless since it only shows approvals, but not disprovals. It creates impression of  consensus, when in reality that might not be the case.

**Comment by seweso** [comment]
A list of developers (and some random people) is just that. It is still valuable to the people who think the ability to code translates into the ability to govern. 

I have seen the best coders get promoted countless of times within businesses, it rarely ends well. You lose a good coder, and you gain a bad leader/manager. 

So the issue is not about censorship. Its about a failure to properly govern. 

Which is ironic, because core gets a lot of power from the very miners they distrusted. So you have core dev's who really like soft forks, but they still want to keep a hard limit and not trust miners with just soft limits. 

Censorship is the least of our problems I would say.

**Comment by MillyBitcoin** [comment]
@benjyz  Bitcoin.org has always been censored.  It is run by Theymos and the people who actively manage it have a clique mentality.  Previously they had several wallets for security issues but the analysis was just done by random people, some of which had no experience whatsoever and they had no standards.  it is basically a bunch of teenagers/20-something with little or no experience trying to run a private little club.

As has already been pointed out in the comments some email with a few ideas is not a "roadmap."  A Roadmap is one of series of documents used in a systems engineering process.  You need things like standard definitions, risk analysis, etc. and you don't get a roadmap just by sending some email.  I have tried to explain the process to them several times (such as http://www.jakeman.com.au/media/whats-right-with-risk-matrices).  A few developers agree but most juts make some childish excuse, say it cannot be done, and accuse anyone who raises the issue of being "trolls."  The fact is the developers have little or no experience with anything outside of their specific technical areas.

**Comment by MillyBitcoin** [comment]
Looks like they are deleting comments here too!

**Comment by harding** [comment]
Please note that comments from MillyBitcoin have been deleted because that person was previously banned from this repository.

**Comment by btcdrak** [comment]
@benjyz I think you misunderstand #1165 is not a vote. Bitcoin Core already made a decision about the direction of development in the next year towards scaling. The PR offers the greater community the chance to add their signature to the document. As such, it is not a place to discuss or even dissent, and any such activity belongs elsewhere as explained [here](https://github.com/bitcoin-dot-org/bitcoin.org/pull/1165#issuecomment-166436947)

**Comment by MillyBitcoin** [comment]
@btcdrak He understand, he is saying that comments from a bunch of cheerleaders like yourself is meaningless at best and deceitful at worst.  Your unending biased comments are an example of why the current system is problematic.

**Comment by saivann** [comment]
Closing the issue, @benjyz I can understand your frustration but opening GitHub issues won't achieve anything, concretely speaking.

As for the implicit suggestion of displaying disapproval, I don't think it's warranted on a written statement like this one (just like the XT website does not list its detractors).

This said if anyone wants wants to make a website that tries documenting / summing up the research, arguments and positions of everyone on all proposals, and try be as neutral as possible, and get to do a good job at it, I'd be the first to applause. That'd be likely a lot of work though.
