### ISSUE TITLE
Formatting of Core Capacity Increases FAQ on iOS (Safari) is faulty

### ISSUE THREAD

**Issue by eragmus** [bitcoin-dot-org/bitcoin.org#1172]
Screenshots attached.

![img_2470](https://cloud.githubusercontent.com/assets/11140618/11969656/b8809570-a8ea-11e5-9668-03f10e400f74.png)
![img_2471](https://cloud.githubusercontent.com/assets/11140618/11969655/b880501a-a8ea-11e5-9221-51b931dfeb9e.png)
![img_2472](https://cloud.githubusercontent.com/assets/11140618/11969654/b879ffb2-a8ea-11e5-9728-1a5cae2b1e2c.png)

Thanks!

**Comment by saivann** [comment]
Thanks for submitting the issue!

I've been aware of that problem, when using code blocks or tables, it's still better to let them overflow than cutting them IMO. This being said, recent Android and iOs support having a scrollbar inside DOM elements, so we could probably avoid those issues completely.

**Comment by wbnns** [comment]
[Bounty](https://github.com/bitcoin-dot-org/bitcoin.org#earn-bitcoin-for-contributing): **10,000 bits / ~$20 USD**
