### ISSUE TITLE
Bitcoin Conference Russia 2016

### ISSUE THREAD

**Issue by voffkas** [bitcoin-dot-org/bitcoin.org#1182]
- date: 2015-04-08
      title: "Bitcoin Conference Russia 2016"
      venue: "Digital October"
      address: "Bersenevskaya naberezhnaya, 6, str. 3"
      city: "Moscow"
      country: "Russia"
      link: "http://bitcoinconf.moscow/en"

**Comment by harding** [comment]
Thanks for submitting your event.  It should appear on the website in about 15 minutes.

**Comment by voffkas** [comment]
Can you please check submittion? I can't  find it on Events section....
