### ISSUE TITLE
Why bitcoin.org promotes third party wallets?

### ISSUE THREAD

**Issue by jl2012** [bitcoin-dot-org/bitcoin.org#1185]
If you don't have exclusive right to move your bitcoin, you don't have any bitcoin. The balance shown in the wallet is only Bitcoin IOU, not Bitcoin.

With OP_CLTV, and the upcoming OP_CSV and segwit, users can retain exclusive right to move their bitcoin in a third party wallet (with time cost), with **_all**_ benefits of third party wallet, e.g. instant payment, instant exchange, green address. Third party wallets should be given a grace period to upgrade before they get delisted.

**Comment by crwatkins** [comment]
Current bitcoin.org listing criteria found at https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/README.md#wallets specify the conditions under which wallets (including custodial wallets) are listed.  I've started a discussion at #1109 soliciting input which will very likely lead to a proposal for separate category for such wallets and perhaps new listing criteria.

**Comment by ABISprotocol** [comment]
Thank you @crwatkins

**Comment by wbnns** [comment]
@jl2012 Hello, thanks for contributing and sharing your thoughts on this issue. This will be addressed alongside #1109.
