### ISSUE TITLE
Add Coinbase to web wallets

### ISSUE THREAD

**Issue by ferdynice** [bitcoin-dot-org/bitcoin.org#1189]
Hi,

I noticed that an excellent online wallet is not yet listed at web wallets. It is Coinbase.com, one of the more respected and reliable companies providing online wallets.

Thanks

**Comment by carnesen** [comment]
@ferdynice Thank you for your comment. Coinbase was recent removed from the wallet page (https://github.com/bitcoin-dot-org/bitcoin.org/pull/1178). There is already an open pull request (PR) to reinstate them (https://github.com/bitcoin-dot-org/bitcoin.org/pull/1180). My suggestion is to close this issue and instead voice your opinion on that open PR #1180 if you'd like.

**Comment by harding** [comment]
Closing as https://github.com/bitcoin-dot-org/bitcoin.org/pull/1180 was merged, re-adding Coinbase to the wallets page.
