### ISSUE TITLE
Bitcoin4Beginners Conference

### ISSUE THREAD

**Issue by Bitcoin4Beginners** [bitcoin-dot-org/bitcoin.org#1192]
- date: 2016-02-17
      title: "Bitcoin4Beginners Conference"
      venue: "Beurs van Berlage, former Amsterdam Stock Exchange"
      address: "Oudebrugsteeg 9, 1012 JN"
      city: "Amsterdam"
      country: "Netherlands"
      link: "http://bitcoinference.com/Bitcoin4Beginners/Amsterdam/Beurs-van-Berlage/2016/February/17/Wednesday.html"

**Comment by martijnw** [comment]
Kind of confusing. At the same time there is the http://www.d10e/#amsterdam event at the same location with speakers like Roger Ver, Brock Pierce, Steve Beauregard and many others. We are working hard to organize a world-class event here and can't accept our event being hijacked by a rogue listing.

**Comment by harding** [comment]
Thanks for submitting your event!  It should appear on the website within about 15 minutes.
