### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by martijnw** [bitcoin-dot-org/bitcoin.org#1196]
- date: 2016-02-17 until 2016-02-18
      title: "d10e - Exploring the future of decentralization"
      venue: "Beurs van Berlage"
      address: "Damrak 243, 1012 ZJ Amsterdam, Netherlands"
      city: "Amsterdam"
      country: "The Netherlands"
      link: "http://d10e.org/#amsterdam"

**Comment by harding** [comment]
Thanks for submitting your event!  It should appear on the website within about 15 minutes.
