### ISSUE TITLE
Repository and bitcoin.org website owned and operated by giant assholes

### ISSUE THREAD

**Issue by Azulan** [bitcoin-dot-org/bitcoin.org#1199]
Recommend better people for the job.

**Comment by jrmithdobbs** [comment]
Close and lock.

**Comment by Azulan** [comment]
@jrmithdobbs I don't know those two.

**Comment by jrmithdobbs** [comment]
I'm calling on @theymos / etc to close and lock this issue. Not making inane suggestions.

**Comment by Azulan** [comment]
@jrmithdobbs Oh yeah, he's one of the giant assholes who is the problem. I'm looking for other people with morals, ethics and intellectual honesty.
