### ISSUE TITLE
Bitcoin Developers Workshop 2016

### ISSUE THREAD

**Issue by Bitcoin-dev** [bitcoin-dot-org/bitcoin.org#1203]
- date: 2016-02-08
      title: "Bitcoin Developers Workshop 2016"
      venue: "Beurs van Berlage, former Amsterdam Stock Exchange"
      address: "Oudebrugsteeg 9, 1012 JN"
      city: "Amsterdam"
      country: "Netherlands"
      link: "http://www.bitcoinference.com/Bitcoin-Developers-Workshop/index.html"

**Comment by harding** [comment]
Thanks for submitting your event!  It should appear on the website within about 15 minutes.
