### ISSUE TITLE
Bitcoinference 2016

### ISSUE THREAD

**Issue by Bitcoinference** [bitcoin-dot-org/bitcoin.org#1204]
- date: 2016-02-11
      title: "Bitcoinference 2016"
      venue: "Beurs van Berlage, former Amsterdam Stock Exchange"
      address: "Oudebrugsteeg 9, 1012 JN"
      city: "Amsterdam"
      country: "Netherlands"
      link: "http://www.bitcoinference.com/"

**Comment by harding** [comment]
Thanks for submitting your event!  It should appear on the website within about 15 minutes.
