### ISSUE TITLE
d10e Amsterdam, Netherlands

### ISSUE THREAD

**Issue by amandahhendricks** [bitcoin-dot-org/bitcoin.org#1212]
- date: 2016-02-17-18
      title: d10e Amsterdam 2016
      venue: Beurs van Berlage
      address: Damrak 243, 1012 ZJ 
      city: Amsterdam
      country: Netherlands 
      link: http://www.d10e.org/#amsterdam

**Comment by harding** [comment]
Thanks for submitting your event!  It should appear on the website within about 15 minutes.

**Comment by amandahhendricks** [comment]
Thank you!
ᐧ

On Sun, Jan 24, 2016 at 4:05 AM, David A. Harding <notifications@github.com>
wrote:

> Thanks for submitting your event! It should appear on the website within
> about 15 minutes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitcoin-dot-org/bitcoin.org/issues/1212#issuecomment-174274939>
> .
>



-- 
​
-- 
Best,

d10e Team
Let's Tweet @d10e_con <http://www.twitter.com/d10e_con> / @TiffanyMadison
<http://www.twitter.com/tiffanymadison>
Let's Connect Facebook <http://www.facebook.com/tiffany.madison> - LinkedIn
<https://www.linkedin.com/in/tiffanymadison1> - Website
<http://www.tiffanymadison.com/> - Instagram
<http://instagram.com/tiffanymadison/> - Google+
<https://plus.google.com/+TiffanyMadison>

I'm located in Nashville, Tennessee USA (Central, US Time)
Sent from my iPhone. Please forgive Siri for typos.
