### ISSUE TITLE
HD wallet error

### ISSUE THREAD

**Issue by Dreamsorcerer** [bitcoin-dot-org/bitcoin.org#1215]
Location: https://bitcoin.org/en/developer-guide#hierarchical-deterministic-key-creation

> Whether creating child public keys or further-descended public keys, a predictable sequence of integer values would be no better than using a single public key for all transactions, as anyone who knew one child public key could find all of the other child public keys created from the same parent public key.

My understanding from reading the rest of this wiki and BIP 32 is that knowing a child public key will not allow you to find sibling keys. You would need the extended parent public key to achieve this.

In which case, using a single public key is much worse. As the wiki states earlier on, for increased security/privacy each key should be used only once. If a public child key allowed you to find other sibling keys, that would greatly decrease privacy and security in my mind, even with random integer values there are only ~2 billion possible keys, which doesn't sound infeasible to bruteforce.

Is this paragraph wrong, or am I misunderstanding something?

**Comment by harding** [comment]
That paragraph doesn't describe BIP32; it describes a reason for not using a simpler design that doesn't include the chain code.

**Comment by Dreamsorcerer** [comment]
Ah, I see now.
