### ISSUE TITLE
Bitcoind 'first run' steps are out of date for configuring RPC auth

### ISSUE THREAD

**Issue by seusher** [bitcoin-dot-org/bitcoin.org#1217]
The steps for setting up bitcoind (https://bitcoin.org/en/full-node#ubuntu-daemon) currently tell you to wait for the message giving you your rpcuser and rpcpassword parameters:

rpcuser=bitcoinrpc
rpcpassword=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

bitcoind no longer does this since it generates a local rpc authentication cookie. These steps should be updated to inform the user of the rcp auth cookie and let them know they aren’t required to set their own password anymore.

**Comment by laanwj** [comment]
https://github.com/bitcoin/bitcoin/blob/0.12/doc/release-notes.md#rpc-random-cookie-rpc-authentication

This is is only in 0.12+, which is not yet a released version. I agree cookie auth could be mentioned, but for people using older versions the old instructions are still useful.

**Comment by MarcoFalke** [comment]
(Noting that 0.12.0 was released: https://github.com/bitcoin/bitcoin/blob/v0.12.0/doc/release-notes.md#rpc-random-cookie-rpc-authentication)
