### ISSUE TITLE
Remove BlackBerry from the wallet categories.

### ISSUE THREAD

**Issue by GandalfBitcoin** [bitcoin-dot-org/bitcoin.org#1218]
It is useless and should be removed.

**Comment by schildbach** [comment]
Why? It's actively being used by tens of thousands of Bitcoin users.

**Comment by crwatkins** [comment]
@GandalfBitcoin Could you explain what you mean by "useless" or describe why you think it should be removed?

**Comment by GandalfBitcoin** [comment]
@schildbach @crwatkins could you tell me the difference between BlackBerry version and Android version?

**Comment by schildbach** [comment]
The main difference is: it runs on BlackBerry! That super important if you have a BlackBerry phone.

**Comment by laanwj** [comment]
Selection by platform is useful, even for niche ones.
This seems based on a misunderstanding, closing.
