### ISSUE TITLE
New event - Consensus 2016

### ISSUE THREAD

**Issue by bitkeef** [bitcoin-dot-org/bitcoin.org#1220]
- date: 2016-05-02
      title: "Consensus 2016"
      venue: "New York Marriott Marquis"
      address: "1535 Broadway, New York, NY 10036, United States"
      city: "New York City"
      country: "USA"
      link: "http://www.coindesk.com/events/consensus-2016/"

**Comment by harding** [comment]
@bitkeef Hi, I have what looks like a duplicate event for that day; please let me know how you'd like to have the event listed.   The current listing is, 

```
- date: 2016-05-02
  title: "Blockchain Technology Conference (BTC) 2016"
  venue: "Marriott Marquis, Times Square, New York City"
  address: "1535 Broadway "
  city: "New York"
  country: "USA"
  link: "http://www.btc2016.co/"
```

**Comment by bitkeef** [comment]
Hi David, 

Apologies if this was not clear, Consensus is the new name for BTC2016, and the URL has changed.

Thanks 

Keith

**Comment by harding** [comment]
Name and URL updated; they should appear on the website within 15 minutes.
