### ISSUE TITLE
Disruptive Innovation: Blockchain Applications & Challenges with a Game-Changing Technology

### ISSUE THREAD

**Issue by TheMankoffCompany** [bitcoin-dot-org/bitcoin.org#1227]
A Discussion for Institutions, Traders, Hedge Funds and Others in the Financial Technology Markets

February 24, 2016 • Instituto Cervantes • Chicago

After highly successful discussions in London and NYC, The Mankoff Company brings you an After the Bell event highlighting a topic of major interest in the Fintech community and beyond. Bringing together leading experts, investors, banks and others, we’re creating a panel discussion allowing for lively thought, creative insight and the opportunity to network and engage with leading lights and colleagues who are working with Blockchain and uncovering new opportunities and applications.

Wednesday, February 24, 2016 Event Schedule

5:30 pm: Registration

6:00 pm: Discussion Points
What can blockchain actually do?  An explanation of the underlying technology
Private vs. Public blockchains
How does Blockchain allow for better traceability and auditing?
How do you create a scaleable Blockchain?
Where do the regulators stand on this technology and how will that impact growth?
How start-ups in this space are leveraging the technology

Panelists:
John Karantonis, Co-Founder & CEO, Geopay.me, Inc.
Robert A. Musiala, Jr., Manager, PriceWaterhouseCoopers Advisory Services
Ryan Pierce, Co-Chair, FIX Digital Currency / Blockchain Working Group & Director and Technology Architect, Engineering & Execution, CME Group
Jennifer Rodrigues, Blockchain Innovation Lead, TD Bank
Mark Smith, CEO & Founder, Symbiont

Facilitator: Stacey Mankoff, Managing Principal, The Mankoff Company

7:00 pm:  Networking Reception: Following the conclusion of the Roundtable Panel Session, join us for a Networking Reception sponsored by Symbiont to further discuss the most top of mind issues of those involved and interested in Blockchain technology

To Register or For More Information: http://themankoffcompany.us/afterthebellblockchainchicago.html

**Comment by harding** [comment]
Thank you for submitting your event.  The Bitcoin.org events page is for promoting Bitcoin events, but neither your description above nor the linked page mentions "bitcoin" once, so I don't think it's a good fit for our events page.

**Comment by TheMankoffCompany** [comment]
Hi David,

Blockchain is the foundation technology of bitcoin so it is related.
Please re-post and thanks!



The Mankoff Company
www.themankoffcompany.com
347-463-9551
info@themankoffcompany.com
