### ISSUE TITLE
Remove alarming text from the 2015-07-04 soft fork alert page

### ISSUE THREAD

**Issue by ewiner** [bitcoin-dot-org/bitcoin.org#1229]
Source File: _alerts/2015-07-04-spv-mining.md

https://bitcoin.org/en/alert/2015-07-04-spv-mining has this scary warning at the top:

> **Note: this situation has not been fully resolved, and it does not appear that it will be fully resolved anytime soon. Users of the affected wallets listed below are still advised to wait additional confirmations or to switch to a safer wallet.**

My understanding is that, while dangerous SPV mining continues to occur, this particular issue of invalid blocks is not much of a cause for concern anymore (i.e. SPV wallet users shouldn't have to wait 30 confirmations).  If someone stumbles on this page, it might be unnecessarily alarming, as it apparently hasn't been updated since the middle of the incident in question.

I'm not confident enough on the details to make a PR for this, but I think at the very least an update is warranted.  A small review/postmortem of the incident on the page would be even better.

**Comment by luke-jr** [comment]
The concern is not gone, and may never be. Light clients (what you're calling "SPV wallets") continue to be very unsafe.

**Comment by laanwj** [comment]
SPV mining is still possible, and is still being done. Having miners not doing full verification does put SPV users at risk.

But the warning about this particular incident with the soft-fork could certainly be toned down.

**Comment by ABISprotocol** [comment]
There was another issue (or pull request) where people discussed this in detail, but I don't remember what it was, and I've searched around for it and couldn't find it.  I recall that I and others made some comments, I believe in my case I supported the use of Electrum and explained that people will continue to use it despite any warning to the contrary, for example, and I don't think it is helpful to steer people away from light clients / SPV wallets, but rather to address the issue of the SPV mining itself.  The current language ("it does not appear that it will be fully resolved anytime soon...switch to a safer wallet") should probably be changed or removed.  Additionally, the link provided from the Electrum note currently just goes to July 2015 forks in the Bitcoin wiki.  This is a useless link as someone then has to click again and they probably don't want to.  The link should actually be this one:
https://en.bitcoin.it/w/index.php?title=July_2015_chain_forks&redirect=no

**Comment by laanwj** [comment]
Electrum has a server based on a full node. AFAIK, as it receives spent/unspent status from a full node and doesn't process blocks It isn't in the class of wallets endangered by SPV mining.

**Comment by luke-jr** [comment]
All light clients get their data from full nodes, so Electrum isn't particularly special in this regard AFAIK...?

**Comment by laanwj** [comment]
Sure, it is a difference in degree not in kind. One difference would be that for electrum all it takes is to upgrade the node version of its servers (specifically the one you make it connect to) to one post-softfork. This is a more limited set than "all nodes".

**Comment by wbnns** [comment]
Since there haven't been any pull requests to revise the text since the issue was raised 10 months ago, I'm going to close this issue and leave the past alert from July 2015 as-is. If there is significant objection to this, I will reopen it. 👍
