### ISSUE TITLE
bitcoin/bitcoin.github.com repository

### ISSUE THREAD

**Issue by laanwj** [bitcoin-dot-org/bitcoin.org#1233]
Is the repository https://github.com/bitcoin/bitcoin.github.com still being used for anything, or can it be deleted now that the site moved to bitcoin-dot-org?

**Comment by harding** [comment]
@saivann can you confirm that this can be deleted?  I assume we haven't used this in two years since Bitcoin.org switched from GitHub pages to self-hosting.

**Comment by saivann** [comment]
@laanwj @harding Exactly, this can be deleted, thanks!

**Comment by laanwj** [comment]
Thanks for the quick response.

''Your repository "bitcoin/bitcoin.github.com" was successfully deleted.'
