### ISSUE TITLE
Developer guide: details for gettransaction and listtransactions are wrong

### ISSUE THREAD

**Issue by pinheadmz** [bitcoin-dot-org/bitcoin.org#1237]
See:

https://github.com/bitcoin/bitcoin/issues/7532

result field `blockindex` is NOT "The block height of the block on the local best block chain which includes this transaction" it IS "the position of the transaction in the block"

Applies to `gettransaction` and `listtransactions`, there may be others

**Comment by Mirobit** [comment]
Thanks, addressed in 9c9edae6f644e3822f18b39e6245415bef6ebe9d
