### ISSUE TITLE
Bitcoin4Beginners

### ISSUE THREAD

**Issue by Bitcoin4Beginners** [bitcoin-dot-org/bitcoin.org#1242]
- date: 2016-03-16
      title: "Bitcoin4Beginners"
      venue: "Beurs van Berlage, former Amsterdam Stock Exchange"
      address: "Oudebrugsteeg 9, 1012 JN"
      city: "Amsterdam"
      country: "The Netherlands"
      link: "http://www.bitcoinference.com/Bitcoin4Beginners/Amsterdam/Beurs-van-Berlage/2016/March/16/Wednesday.html"

**Comment by Cobra-Bitcoin** [comment]
Event has been added. Thanks.
