### ISSUE TITLE
CoinFest

### ISSUE THREAD

**Issue by Bitcoin4Beginners** [bitcoin-dot-org/bitcoin.org#1243]
- date: 2016-04-05
      title: "Bitcoin4Beginners: CoinFest!"
      venue: "Beurs van Berlage, former Amsterdam Stock Exchange"
      address: "Oudebrugsteeg 9, 1012 JN"
      city: "Amsterdam"
      country: "The Netherlands"
      link: "http://www.bitcoinference.com/Bitcoin4Beginners/Amsterdam/Beurs-van-Berlage/2016/April/5/Tuesday.html"

**Comment by Cobra-Bitcoin** [comment]
Event has been added. Thanks.
