### ISSUE TITLE
The London Bitcoin Forum

### ISSUE THREAD

**Issue by oliviaedwards** [bitcoin-dot-org/bitcoin.org#1244]
- date: 2016-03-23
      title: "The London Bitcoin Forum"
      venue: "QEII Centre"
      address: "Fleming & Whittle Broad Sanctuary"
      city: "London"
      country: "United Kingdom"
      link: "https://londonbitcoinforum.co.uk"

**Comment by Cobra-Bitcoin** [comment]
Event has been added. Thanks.

**Comment by harding** [comment]
I have also heard the reports about this possibly being a scam.  Their website says, "more than 60 expert speakers" but they don't list any names that I can see.  Perhaps one or two of those experts who are well known to the community could post here that they're attending.
