### ISSUE TITLE
Transaction Lost in Limbo

### ISSUE THREAD

**Issue by UnitekSystemsLtd** [bitcoin-dot-org/bitcoin.org#1247]
1.0BTC sent from a Hard Storage Machine which was running V9.1 has been lost in Limbo and remains unconfirmed.  From my investigation this is because the Fees are 0.0000
Can someone please help get this transaction confirmed:  otherwise there seems to be a hole in which BitCoin can go lost from Cold Storage Machines which are running core which have 0.0000 Mining Fees

https://www.blocktrail.com/BTC/tx/78bc8a497b8bd540909753e81cdfc9f3934b6e3a1a815a72aec841d251662a40
Transaction:  78bc8a497b8bd540909753e81cdfc9f3934b6e3a1a815a72aec841d251662a40 remains unconfirmed even though the Priority keeps increasing

Any help would be appriciated. Thanks

**Comment by cpmx** [comment]
Couldn't you just resend the transaction with a higher fee?

**Comment by UnitekSystemsLtd** [comment]
How?

The guy is running Core 9.1 and there is no options for the fee
His balance is 0BTC as his wallet on the core no longer shows it as a balance
And now the transaction for the 1BTC is in limbo
What can either of us do.   and according to CoinKite this transaction may never get processed

Btc coming from cold storage which are running a version of core which has no fees has the potential of the BTC being lost in mempool

Please help

**Comment by cpmx** [comment]
I'm not familiar with Core 9.1 but there should be a way to export the private keys and then create a transaction using [coninb.in](https://coinb.in/#newTransaction/)

**Comment by UnitekSystemsLtd** [comment]
my question is:  will this transaction be eventually be picked up by the Miners?

**Comment by UnitekSystemsLtd** [comment]
It finally got confirmed on 28 Feb in Block 400,388
That was a long time
