### ISSUE TITLE
Developer Glossary Definition: Double Spend

### ISSUE THREAD

**Issue by VincentPiper** [bitcoin-dot-org/bitcoin.org#1248]
Currently, Bitcoin.org's double-spend definition states: "A transaction that spends the same input as spent in another transaction.".

The original meaning before Bitcoin existed was something to the effect of: "a failure mode of digital cash schemes, when it is possible to spend a single digital token twice." (https://en.wikipedia.org/wiki/Double-spending) (In the Whitepaper, Satoshi refers in this meaning of double-spend). Ultimately, the creation of the blockchain made double-spending by this definition, impossible. Yet, the community still uses this term but in the new defined way.

The important term in both definitions is the word "spend" or "spent", but they are used in different meanings. In Bitcoin's Double-Spend Definition, it seems to refer to and in theory is interchangeable with just a "push" or a "broadcast" and does not seem to convey whether it is in a block or not. It actually seems to convey a state of limbo, like pending in the mempool.  But before Bitcoin, double-spend's definition seems to refer to an actual finalized pay out or disbursement and the doubling of that coin. (In addition, the terms are also used in the context of being recorded in the blockchain, like when a block explorer shows outputs that are "spent" or are "unspent".) There seems to be no single definition of "spend" or "spent", when it is to be used, and for what purpose. The reader is left to interpret the intended meaning.

I request that we change the name of the term of double-spend, to something else. I would propose something like a "double-push" or a "double-cast", so to differentiate from the original meaning. (I would prefer this option and would vote for "double-cast".)

But I also understand that it may not be possible since everyone is most likely set in their ways of Bitcoin terminology. (In addition, I believe I am filing this request in the proper venue, since Developers and Users would defer to the Bitcoin.org’s definitions as official or more official than others.) In that case, I request that the Developers Glossary Definition of Double Spend be made more specific so that it would say something as to the following:

**_Double Spend: "The transaction that used the same input as an already broadcasted transaction. This attempt of duplication_**[1]**_, deceit_**[2]**_, or conversion_**[3]**_, will be adjudicated when only one of the transactions is included in the blockchain."_**

[1] duplication, as in regards to double spend's original definition, as used in the Whitepaper.
[2] deceit, as in regards to a double spend against merchants or citizens.
[3] conversion, is my made up term for legitimate double spending, like in Opt-In-RBF cases.

Thank you for your consideration.

**Comment by MarcoFalke** [comment]
> But I also understand that it may not be possible since everyone is most likely set in their ways of Bitcoin terminology. (In addition, I believe I am filing this request in the proper venue, since Developers and Users would defer to the Bitcoin.org’s definitions as official or more official than others.) In that case, I request that the Developers Glossary Definition of Double Spend be made more specific so that it would say something as to the following:

Makes sense. I think it is easiest if you create a pull request.

**Comment by VincentPiper** [comment]
> Makes sense. I think it is easiest if you create a pull request.

Thank you for your comment and direction. 
I have created a pull request and revised the definition more. 
I am new to this, so hopefully I did it correctly.

**Comment by wbnns** [comment]
Closing this now that #1251 has been merged.
