### ISSUE TITLE
Please update info about Electrum

### ISSUE THREAD

**Issue by ecdsa** [bitcoin-dot-org/bitcoin.org#1249]
1. Electrum for Android is now available on Google Play: https://play.google.com/store/apps/details?id=org.electrum.electrum
2. Electrum for Desktop provides two-factor authentication, using multisig and TrustedCoin.
3. The logo is outdated. Please use https://raw.githubusercontent.com/spesmilo/electrum/master/icons/electrum.png

Let me know if you want me to write a pull request; I am not familar with the process here.

**Comment by crwatkins** [comment]
@ecdsa Yes, please submit a pull request; it would be most appreciated.  You may find some useful guidelines and hints here https://github.com/bitcoin-dot-org/bitcoin.org#adding-a-wallet .  Feel free to ask any questions here about the listings.

**Comment by Mirobit** [comment]
#1391, #1389 and #1439
Should be up to date now.

**Comment by wbnns** [comment]
Closing this now that #1439 has been merged. Thank you all!
