### ISSUE TITLE
Adding "fee management" infos in the wallets section

### ISSUE THREAD

**Issue by jlegoupil** [bitcoin-dot-org/bitcoin.org#1255]
Add “fee management” information in the bitcoin.org wallet section along with the standard infos : "control over your money", "validation", "transparency", "environment" and "privacy".

It would help users know how wallets manage fees so they can make the best choice and avoid having stuck transactions due to poor fee handling from wallets. Speaking for myself, "fee handling" was a decisive parameter when I chose my wallets. This is even more the case now.

We can also expect wallet innovation in the "fee management" space in the coming months due to the deployment of Opt-in RBF which makes it even more relevant, imo.

**Comment by theymos** [comment]
This is a good idea IMO.

**Comment by Cobra-Bitcoin** [comment]
Great idea!

**Comment by jlegoupil** [comment]
A proposal for "fee management" categories :

- _Vulnerable to delays_ (orange) : the fee is hard coded (also includes wallets that enable different hard-coded fees such as low/high priority).

- _Basic protection against delays_ (green) : user can manually set the fee or the wallet estimates a smart fee from the current mempool of unconfirmed transactions.

- _Full protection against delays_ (bold green) : user can increase the fee after broadcasting the transaction to the network (RBF enabled wallets)

**Comment by instagibbs** [comment]
@jlegoupil note that point #1 can also mean users are *regularly* over-paying in fees during slow times as well.

**Comment by crwatkins** [comment]
The https://github.com/bitcoin-dot-org/bitcoin.org/pull/1568 PR has been merged.  I'll close this issue for now.  Please feel free open a new issue for any updates to the current fee scoring.  Thanks to @jlegoupil for the proposal.
