### ISSUE TITLE
The Bitcoin conference 2016

### ISSUE THREAD

**Issue by vadimantas** [bitcoin-dot-org/bitcoin.org#1263]
- date: 2016-04-08
      title: "The Bitcoin conference 2016"
      venue: "ISM University of Management and Economics"
      address: "Arklių St. 18, LT-01129"
      city: "Vilnius"
      country: "Lithuania"
      link: "http://thebitcoinconference.com/"

**Comment by Cobra-Bitcoin** [comment]
This event is too small in scope and your account is too new. We don't want to risk promoting scam events on bitcoin.org, and so we have to be extra cautious. Sorry.

**Comment by vadimantas** [comment]
This event is organised on the large scale. Speakers will be participating from the government institutions, bitcoin startups and bank sector ([Participants list](http://thebitcoinconference.com/)). All the presentations and talks will be held in English, thus the global participants are welcome. The organisers of this event are enterpreneurs Ilja Laurs and Mindaugas Glodas from [Nextury Ventures](http://nextury.com/en/#section=we-are). If you have any doubts about this event, please contact them directly. The oncoming event was mentioned in the major Lithuanian press ([1](http://it.lrytas.lt/ismanyk/vilniuje-vyks-didziausia-baltijos-salyse-bitkoinu-konferencija.htm), [2](http://www.newsbtc.com/2015/12/06/nextury-ventures-and-lithuania-co-host-baltics-largest-bitcoin-and-blockchain-conference/), [3](http://en.delfi.lt/lithuania/economy/vilnius-to-host-largest-bitcoin-conference-in-baltics.d?id=69761760)) and is supported by [Vilnius municipality](http://www.vilnius.lt/index.php?4216633551).
I am new at git-hub community. Coding is not my bread. Though, I take some interest in bitcoins, thus I felt that to mention about this event here, was a right thing to do.
