### ISSUE TITLE
DEVCON 0 - The Genesis of a nation

### ISSUE THREAD

**Issue by martijnw** [bitcoin-dot-org/bitcoin.org#1265]
- date: 2016-03-25
      title: "DEVCON 0 - The Genesis of a nation."
      venue: "Meet Berlage / Bitcoin Embassy"
      address: "Oudebrugsteeg 9"
      city: "Amsterdam"
      country: "Netherlands"
      link: "https://bitcoinembassy.nl/event/bitnation-devcon-0-the-genesis-of-a-nation/"

**Comment by Cobra-Bitcoin** [comment]
This event is too soon. In future you should submit your events at least a few weeks before they are due to take place.
