### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by Abstrct** [bitcoin-dot-org/bitcoin.org#1266]
- date: 2016-06-20
      title: "Blockchain Training Conference"
      venue: "MaRS Discovery District"
      address: "101 College St, Toronto, ON M5G 1L7"
      city: "Toronto"
      country: "Canada"
      link: "https://blockchaintraining.org"

**Comment by Cobra-Bitcoin** [comment]
Added.

**Comment by Abstrct** [comment]
Thank you!
