### ISSUE TITLE
The transaction data to sign does not exclude public keys on scriptSig.

### ISSUE THREAD

**Issue by Kangmo** [bitcoin-dot-org/bitcoin.org#1273]
Source File: _includes/devdoc/guide_transactions.md

=> In essence, the entire transaction is signed except for any signature scripts, which hold the full public keys and secp256k1 signatures.

The full public keys in signature scripts are included for signature calculation. Here is the list of data excluded from the signature script.
1) signatures
2) OP_CODESEPARATOR 

Also, with OP_CODESEPARATOR, the one who creates a transaction can control the data to be included for calculating the signature.

**Comment by wbnns** [comment]
[Bounty](https://github.com/bitcoin-dot-org/bitcoin.org#earn-bitcoin-for-contributing): **5,000 bits / ~$10 USD**

**Comment by Kangmo** [comment]
thank you wbnns for the bounty. 
Here is my address. Is there any step that I need to follow? 

1LHesg4yPM1ksyi8ZpstGWTtaQm9pcYT2X

**Comment by wbnns** [comment]
@Kangmo Hello, yes, first you need to submit a pull request that gets merged, resolving this issue.

**Comment by achow101** [comment]
@Kangmo that is incorrect. The pubkeys are not included in the data that is signed. It is part of the scriptsig so it is not included in the data. The scriptsig is actually replaced with the scriptPubKey, which is (a misnomer) actually the output script which the transaction is spending from.

**Comment by wbnns** [comment]
@achow101 Thanks for the review; closing. @Kangmo Please feel free to clarify if anything has been misunderstood and this is in fact a valid issue.
