### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by wealthlink** [bitcoin-dot-org/bitcoin.org#1274]
- date: every day in 2016
      title: "" CRYPTOCURRENCY TRAINING
      venue: "WEALTHLINK OFFICE" 
      address: "108 ABA/OWERRI ROAD"
      city: "ABA"
      country: "NIGERIA"
      link: "https://bitcoin365club.com/?ref=WEALTHLINK"

**Comment by wealthlink** [comment]
CALL WEALTHLINK ON +2348036758278

**Comment by franckuestein** [comment]
ping @harding

Maybe you haven't seen it because user closed it immediately, but despite being a closed issue this is clear ponzi scheme spam.
