### ISSUE TITLE
20 vs 60 GB blockchain size

### ISSUE THREAD

**Issue by nponeccop** [bitcoin-dot-org/bitcoin.org#1281]
https://bitcoin.org/en/download says 20GB which is pretty outdated info:

> You should make sure that you have enough bandwidth and storage 
> for the full block chain size (over 20GB). 

However, https://bitcoin.org/en/full-node correctly lists the requirements as 60GB+.

**Comment by franckuestein** [comment]
@nponeccop already discussed on this pull request: https://github.com/bitcoin-dot-org/bitcoin.org/pull/1225
