### ISSUE TITLE
Update progress bar should show blocks instead of days

### ISSUE THREAD

**Issue by findftp** [bitcoin-dot-org/bitcoin.org#1286]
When I start bitcoin core, it starts downloading blocks from the network. The progress bar shows how many days/hours left to reach the latest block.
I would like to suggest to change this into showing how many blocks there are left to download because the wallet doesn't care about days, but it does about blocks!
Days are just something we humans find convenient to work with. Maybe it could be shown between parentheses behind the block height.

**Comment by jmacwhyte** [comment]
This is the repo for the bitcoin.org website, not the bitcoin core software (https://github.com/bitcoin/bitcoin). I suggest this issue be closed.

**Comment by findftp** [comment]
You are right. Wrong place. issue closed
