### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by junior8k** [bitcoin-dot-org/bitcoin.org#1290]
- date: 2016-05-30
      title: "Keynote 2016 - Blockchain Technology Conference"
      venue: "Burj Al Arab, Dubai"
      address: "3 Jumeira Rd"
      city: "Dubai"
      country: "United Arab Emirates"
      link: "http://www.keynote2016.com"

**Comment by Cobra-Bitcoin** [comment]
Event added.
