### ISSUE TITLE
Add Digitalbitbox to your wallet recomendations!

### ISSUE THREAD

**Issue by briannyeko** [bitcoin-dot-org/bitcoin.org#1306]
Add Digitalbitbox (HD wallet) to your wallet recomendations!

**Comment by crwatkins** [comment]
Hey @briannyeko thanks for bringing Digitalbitbox to our attention.  The method by which to add new content to bitcoin.org is explained [here] (https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/README.md) and adding  a wallet in particular is explained in detail [here](https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/README.md#adding-a-wallet).  We welcome you or anyone to submit a PR.

**Comment by laanwj** [comment]
About time! :)

**Comment by jonasschnelli** [comment]
The DigitalBitbox will leave beta phase soon. I'll create a PR soon.

**Comment by crwatkins** [comment]
PR #1417 has been opened to add this wallet to the listings.  Thank you for your suggestion @briannyeko.  Further input on this topic is welcome at PR #1417.
