### ISSUE TITLE
Satoshi client is wrong in the comment, should be /Satoshi:0.9.3/

### ISSUE THREAD

**Issue by Christewart** [bitcoin-dot-org/bitcoin.org#1307]
Source File: _includes/devdoc/ref_p2p_networking.md

**Comment by wbnns** [comment]
@Christewart Hello, thanks for contributing. Apologies, I'm not sure I understand the location you're referring to where this is incorrect. Could you please provide more details and reopen a new issue with the specific instance(s)?
