### ISSUE TITLE
Why if someone buys bitcoin on ebay does paypal AUTOMATICALLY not pay for it

### ISSUE THREAD

**Issue by SSNNAAKKEE** [bitcoin-dot-org/bitcoin.org#1311]
And will not even talk to ebay about notes sent back and forth between seller and buyer like buyer saying he will buy another when he receives first then buys it an hour later but this is not evidence to paypal ...   FREE BITCOIN FOR ALL ON EBAY JUST DONT PAY ON PAYPAL AND DONT COMPLAIN ON EBAY CUZ IF YOU COMPLAIN ON EBAY THEN THE EMAIL SAYING YOU RECEIVED THE FIRST WONT BE SEEN BY PAYPAL!

**Comment by SSNNAAKKEE** [comment]
And nobody cares about this?

**Comment by laanwj** [comment]
I'm sure somebody cares, but this is not a bitcoin.org site issue. I'm honestly not sure what brought you to complain here. Nowhere on the site does it recommend using ebay or paypal for trading bitcoin, and neither should it, as those companies prohibit cryptocurrency trading...
