### ISSUE TITLE
listaccounts is not working

### ISSUE THREAD

**Issue by amzamrutha** [bitcoin-dot-org/bitcoin.org#1313]
Source File: _includes/devdoc/bitcoin-core/rpcs/rpcs/listaccounts.md

listaccounts not returning any reponse.Page stucks there.
`<?php

  require_once 'jsonRPCClient.php';
 $confirmation=6;
  $bitcoin = new jsonRPCClient('http://user:password@127.0.0.1:port/');
$bitcoin->listaccounts($confirmation); ?>`

**Comment by Cobra-Bitcoin** [comment]
You're asking in the wrong place, this repository is for bitcoin.org issues.
