### ISSUE TITLE
Heads up about Bitcoin Core linux naming convention change in 0.13.0

### ISSUE THREAD

**Issue by laanwj** [bitcoin-dot-org/bitcoin.org#1315]
Due to introduction of ARM as a first-class platform, the tarballs will change name to include an architecture triplet instead of `linux32`/`linux64`:
```patch
-bitcoin-${VERSION}-linux32.tar.gz
-bitcoin-${VERSION}-linux64.tar.gz
+bitcoin-${VERSION}-aarch64-linux-gnu.tar.gz
+bitcoin-${VERSION}-arm-linux-gnueabihf.tar.gz
+bitcoin-${VERSION}-i686-pc-linux-gnu.tar.gz
+bitcoin-${VERSION}-x86_64-linux-gnu.tar.gz
```
Probably this will require a change to the download page logic.

**Comment by Cobra-Bitcoin** [comment]
Yeah, it's going to require some changes to the page logic. I'll work on that on the weekend.

**Comment by Cobra-Bitcoin** [comment]
I've made the changes to the download page logic. Just merge the "new-download-page" branch once the binaries go live.

**Comment by laanwj** [comment]
Thank you!
