### ISSUE TITLE
I sent -1.94075318 from my bitcoin core wallet 12 days ago to 1DkjqUfJGhJ3oxEuHkATexSrvcohC8PWdD and there are still no confirmations nor has the BTC been returned to my wallet.  How much longer will it take for an action to occur?

### ISSUE THREAD

**Issue by xy94087** [bitcoin-dot-org/bitcoin.org#1320]
Source File: _posts/2015-04-14-new-glossary.md

**Comment by harding** [comment]
I'm sorry, this issue tracker isn't for problems with Bitcoin software.  You can ask in many of the forums and chatrooms listed on the community page: https://bitcoin.org/en/community

**Comment by xy94087** [comment]
Ok, I will try asking there.  Thank you for commenting Mr. Harding.
