### ISSUE TITLE
Afterson.com Bitcoin services

### ISSUE THREAD

**Issue by bitcoin-afterson** [bitcoin-dot-org/bitcoin.org#1322]
What title can we give Afterson's Bitcoin services? Bitcoin wallet, we do not have a software that calculates Bitcoin or tally how many bitcoins remain. Bitcoin exchange, we do not convert Bitcoin to another currency directly. We use a Canadian Bitcoin exchange to convert to CAD. Bitcoin escrow, we do not act as an impartial third party between buyer and seller. Bitcoin has signature features, so escrow is not necessary. 
We offer Bitcoin owners to option to deposit a portion of Bitcoin. We purchase or pay for the item or service. We also can provide a prepaid visa credit card. Can Afterson still be considered a Bitcoin wallet?

**Comment by crwatkins** [comment]
All of the currently listed wallets are  apps (native, mobile, web, or browser extensions), so I don't believe that your service is what is listed here as a wallet.   I was going to suggest the referenced [list of exchanges](https://howtobuybitcoins.info) but you make a good point about not being an exchange.  Perhaps others have some suggestions.

**Comment by bitcoin-afterson** [comment]
Do you think that Afterson has a feasible idea, that such a Bitcoin service could be pragmatic. We though of BItcoin shopper as a title because we are "shop" or purchase for Bitcoin owners. However, we offer prepaid visa credit cards that can be funded through Bitcoin, we in turn convert Bitcoins to CAD then reload the credit card. Bitcoin owners would be able to purchase on their own. Can Afterson be listed in another category on Bitcoin.org?

**Comment by bitcoin-afterson** [comment]
We created a simple app downloadable on our main page of our website Afterson.com. We do not know if it is suitable.

**Comment by jmacwhyte** [comment]
As Afterson does not really fit into the current categories presented on bitcoin.org, I recommend it not be included at this time, and this issue be closed.

Perhaps the owners could instead try to get Afterson listed at http://usebitcoins.info/ as a place to spend bitcoin.

**Comment by Mirobit** [comment]
Should be closed. Doesn't fit to bitcoin.org and the App was removed anyway.
