### ISSUE TITLE
[BUG] Knotz has the same screenshot with Core

### ISSUE THREAD

**Issue by mcccs** [bitcoin-dot-org/bitcoin.org#1329]
![screen shot 2016-07-07 at 18 32 04](https://cloud.githubusercontent.com/assets/20167871/16659003/22e320aa-4471-11e6-9684-8e0d61c0c478.png)

**Comment by luke-jr** [comment]
Uh? Clearly shows a different icon in your screenshot...

**Comment by greenaddress** [comment]
@luke-jr I think he means the screenshot, it states "Bitcoin Core - Wallet" rather than "Bitcoin Knots - Wallet"

**Comment by mcccs** [comment]
> @luke-jr I think he means the screenshot, it states "Bitcoin Core - Wallet" rather than "Bitcoin Knots - Wallet"

Yes, this is what I meant.

**Comment by luke-jr** [comment]
Not sure why the titlebar matters so much...

**Comment by MarcoFalke** [comment]
@mcccs Please update the screenshots to the most recent versions by creating a pull request.

**Comment by mcccs** [comment]
I don't have Linux, can I take a screenshot on Mac or Windows ?

**Comment by MarcoFalke** [comment]
It should be easy to get Ubuntu running in a virtual machine.

**Comment by mcccs** [comment]
I did, and unzipped tar.gz
The problem is, I can't find the installer (or stand-alone)

There's a file called Bitcoin-QT but it  has no extensions and I can't launch it.

**Comment by MarcoFalke** [comment]
Press `CTRL + ALT + T` to open a terminal. Then something like

```
cd Downloads/bitcoin
./bin/bitcoin-qt &
```

to run the binary.
