### ISSUE TITLE
P2P protocol version message incorrectly defined.

### ISSUE THREAD

**Issue by evoskuil** [bitcoin-dot-org/bitcoin.org#1338]
The described `addr_recv services` and `addr_trans services` are not properly part of the [version message](https://bitcoin.org/en/developer-reference#version).

**Comment by harding** [comment]
@evoskuil could you provide more information about what you mean by "not properly part of"?  If I recall correctly, when I wrote that section, they appeared to be part of all the version messages I inspected on the network and they were part of the Bitcoin [Core] code since 2009.

**Comment by evoskuil** [comment]
I just meant that these do not show up on the wire for any version messages from any nodes on mainnet, nor will any node accept them.

**Comment by evoskuil** [comment]
Also notice they aren't documented here: https://en.bitcoin.it/wiki/Protocol_documentation#version

**Comment by laanwj** [comment]
This is the code in `net.cpp` that sends the version message:
https://github.com/bitcoin/bitcoin/blob/master/src/net.cpp#L504
```
    PushMessage(NetMsgType::VERSION, PROTOCOL_VERSION, (uint64_t)nLocalServices, nTime, addrYou, addrMe,
                nLocalHostNonce, strSubVersion, nBestHeight, ::fRelayTxes);
```
It does send two CAddress structures: `addrYou` and `addrMe` after the timestamp.
A CAddress is serialized as:
```
uint64_t services
uint8_t ip[16];
uint16_t port;
```
So from what I can see, the documentation is correct.

**Comment by evoskuil** [comment]
The address fields are correct but the services fields are not. I suspect there is conditional serialization of the address structures in the implementation.

**Comment by laanwj** [comment]
It doesn't *look* conditional, in `CAddress::SerializationOp`: https://github.com/bitcoin/bitcoin/blob/master/src/protocol.h#L301

**Comment by evoskuil** [comment]
Sorry, my mistake... *my* address deserialization is capturing the services fields which I didn't notice.
