### ISSUE TITLE
adding stuff!

### ISSUE THREAD

**Issue by briannyeko** [bitcoin-dot-org/bitcoin.org#1339]
When will you add(to your website):
Gemini(Exchange) and Bitsquare.io(Exchange) to the list of recomended exchanges?
Remove bitfinex from the list of recomended exchanges?

**Comment by harding** [comment]
Hi, @briannyeko.  What page are you referring to?  I don't believe Bitcoin.org has any pages that recommend specific exchanges, and `git grep -i finex` doesn't return any matches for me.
