### ISSUE TITLE
Incorrect protocol version documented for version.relay.

### ISSUE THREAD

**Issue by evoskuil** [bitcoin-dot-org/bitcoin.org#1341]
[Bounty](https://github.com/bitcoin-dot-org/bitcoin.org#earn-bitcoin-for-contributing): **25,000 bits / ~$250 USD**

According to other bitcoin.org [documentation](https://bitcoin.org/en/release/v0.9.0) and observation of the network, `version.relay` was not enabled in Bitcoin Core until protocol version 70002, but is [documented](https://bitcoin.org/en/developer-reference#version) as version 70001:

> Added in protocol version 70001 as described by BIP37.

**Comment by evoskuil** [comment]
Reviewing the sources shows that `version.relay` is read **but not written** in version 0.8.x (70001) and it is read **and** written in version 0.9.0 (70002).

**Comment by Mirobit** [comment]
Agreed it doesn't work with version 70001.

**Comment by evoskuil** [comment]
To be clear, it half-works, which can be a bit confusing.

**Comment by wbnns** [comment]
@evoskuil @Mirobit Thanks for bringing this up - what do you all propose to resolve this issue?

**Comment by evoskuil** [comment]
@wbnns There is proper Bitcoin Protocol behavior and there is the Bitcoin Core implementation. Assuming you are documenting the former I would document the proper behavior according to the BIP. Even so it might be worth a note on the bug since it needs to be worked around for useful operation against these older nodes. I've found a few of these types of issues in various clients because libbitcoin has configurable min and max protocol levels.

**Comment by wbnns** [comment]
[Bounty](https://github.com/bitcoin-dot-org/bitcoin.org#earn-bitcoin-for-contributing): **5,000 bits / ~$10 USD**

**Comment by achow101** [comment]
The field is optional. It does not need to be set even if the protocol version is 70001 or higher.

**Comment by evoskuil** [comment]
@achow101 Agree, it being optional makes it unimportant that Bitcoin Core reads it in 70001 but doesn't write it until 70002. I had been operating in consideration of BIP60, which makes it mandatory. Since BIP37 is "final" and BIP60 is "draft", your interpretation is correct.

**Comment by evoskuil** [comment]
Just for the record I would point out that the `version.relay` field is not valid at any protocol level prior to 70001. I mention this because I do encounter the occasional peer that sets it at these lower levels.

**Comment by evoskuil** [comment]
Ugh, I just [reminded myself](https://github.com/bitcoin/bips/wiki/Comments:BIP-0060) again why this sucks. The relay field is added to the version message. It is not possible for a pair of peers to know the each other's versions before sending the version message (the second one could). So the BIP37 specification is a bug, as it breaks the handshake with any earlier version peer that properly validates the version message. There's no good way to handle it apart from going back and patching those older versions and any new version that implements an older (and perfectly relevant) protocol version.

**Comment by harding** [comment]
@evoskuil I suggest you re-open the issue.  If this complication is making it hard for implementors to write software, it's something that should be documented IMO.  (That's what the documentation is for, after all, not just helping people fall asleep at their desks because it's so boring to read. :-)

@wbnns if he does re-open, maybe you can remove the bounty so that this issue can be addressed with care rather than with haste?  It's up to you whether @achow101 deserves the bounty for moving this issue forward (and then what does @evoskuil deserve for taking the time to report and carefully describe this issue?  I hate this whole bounty thing).

**Comment by wbnns** [comment]
@harding Hey, not sure if you saw, but this was opened on August 17, 2016 - I don't think there was anything hasty about adding a bounty the other day (a year and a half later) . :)

**Comment by harding** [comment]
@wbnns I agree comments about the bounty system should be left on #1606.  I apologize for my digression.

**Comment by wbnns** [comment]
@harding Ok, cool, no worries - thanks man.

**Comment by evoskuil** [comment]
@harding Okay, will do.

This issue is so persistently annoying to P2P protocol development that I feel like revising BIP60 to retroactively invalidate `version.relay` altogether in BIP37 (as opposed to requiring version changes to be fixed-size, which doesn't resolve the issue).

I finally realized that it is likely Core support for *sending* relay was released a (protocol) version after *reading* relay for the simple reason that sending it to size-validating peers would cause the new implementation to be dropped during handshake, at least in the cases where the peer received the version message first. By incrementally moving the feature out, once there was sufficient coverage of new nodes, the team would be intentionally isolating all size-validating pre-BIP37 nodes. This would force an upgrade to nodes which presumably have BIP37's bloom filtering enabled.

It's possible that the upgrade was just sloppy work, but it seems likely that the planned obsolescence was not seen as a negative. It's also possible that Core itself doesn't (or didn't) validate the size of the version message, in which case it would have been seen as benign. I've seen this same broken reasoning in the BIP151 proposal, which treats a totally invalid message type (i.e. prior to the handshake) as not breaking compatibility. This cases the same problem in that message-type-validating peers must drop the connection attempt before it can be downgraded.

Libbitcoin validates both message size and message type for all messages. If the protocol version does not support the message then the peer is dropped. It also supports configurable protocol version levels, able to emulate a peer of all versions back to 31402. This is done for historical/educational reasons, for easy development testing against older/specific peers, and as a matter of proper protocol implementation. All down-level peers should operate properly against any new peer. Protocol versions do not expire, and there are reasons to use lower level protocols even in new implementations.

So that's my rant :/. There's no good way to "fix" this since BIP37 itself is broken. Working around the bug means either never setting relay (and always getting tx flow) or making it impossible to connect to size-validating peers of protocol versions below 70001. Core requires a minimum peer protocol version of 31800 and Libbitcoin requires at least 31402. Allowing the extra byte, in violation of the original protocol, in modified down-level size-validating nodes, is the only option. Older implementations would need to be modified.

**Comment by cornelius** [comment]
#3063 adds a note about the potential incompatibility in the documentation. I would think that this is good enough from the documentation point of view. While there is this problem in the code which might affect clients implementing older versions, I think the documented protocol versions are correct from a documentation point of view now.

**Comment by wbnns** [comment]
Unless others object, this issue will be closed on Friday, August 16th.

**Comment by evoskuil** [comment]
BIP60 doesn't actually identify or explain the issue, so the reference to it may leave people guessing.

**Comment by cornelius** [comment]
The motivation section of BIP-60 refers to the compatibility issue and the comments linked in the BIP have more details. From my perspective this explains the issue quite well, at least it gave me a good understanding of the issue. Is there a better source as a reference?

**Comment by evoskuil** [comment]
The issue is not actually described by bip60. I wrote this up above *here*. The compat issue is that the additional byte (optional or otherwise) is not backward compatible with the previous protocol’s version message. The version message establishes the protocol version, so can’t change, but did.

**Comment by cornelius** [comment]
So maybe instead of the reference to BIP 60, we could add a note to the "version" message documentation with a brief explanation of the issue for implementors of older protocol versions:

"Note that protocol version 70001 introduced the optional `relay` field, adding an additional byte to the `version` message. This introduces an incompatibility with implementations of older protocol versions which do strict size checking of the `version` message according to their own protocol version. If you are implementing an older protocol version than 70001 you need to handle the case of a client implementing a newer protocol version sending the extra byte."

What do you think?

**Comment by evoskuil** [comment]
The size validation of the version message is presumed by older clients to be protocol version independent, since the version is inside the message. I would suggest something like: "Note that protocol version 70001 introduced the optional `relay` field, adding the possibility of an additional byte to the `version` message. This introduces an incompatibility with implementations of lower protocol versions which validate the version message size. When implementing support for protocol versions less than 70001 you may want to handle the case of a peer potentially sending an extra byte, treating it as invalid only in the case of a requested protocol version less than 70001."

**Comment by cornelius** [comment]
That sounds good. Thanks for the suggested changes. Makes it very clear from my point of view. I put up a pull request with an update to the note according to our discussion here: #3074.

**Comment by wbnns** [comment]
This has been rescheduled to be closed on Wednesday, August 21st.

**Comment by wbnns** [comment]
@cornelius 

Here's the [transaction ID](https://live.blockcypher.com/btc/tx/fde34ecb92e7c36938f9e53a3cdf749dc119b1f5c7e7204ccbef1440523e1b72/) for the bounties you took down (#1341, #2043).
