### ISSUE TITLE
include instructions for verifying 0.13.0

### ISSUE THREAD

**Issue by creationlayer** [bitcoin-dot-org/bitcoin.org#1342]
I noticed the warning message, and the keys. While it may seem quite simple to some higher in tech, I think it warrants just posting the command or method of verifying for users, otherwise they may just read it and think, so what do I do here.

**Comment by theymos** [comment]
I have a guide here which could maybe be used as a basis: https://www.reddit.com/r/Bitcoin/wiki/verifying_bitcoin_core

**Comment by creationlayer** [comment]
I did see this guide, very well done. I think it could be included either in short form, or as a "verification" additional page. Thank you for the guide.
