### ISSUE TITLE
Unknown contributors

### ISSUE THREAD

**Issue by ConcernedBitcoiner** [bitcoin-dot-org/bitcoin.org#1346]
I'm concerned about the influence of anonymous contributors such as cobra and btcdrak and theymos on the community...

Echoing Emin's concerns https://twitter.com/el33th4xor/status/767081106197843969, we can do better then unknow contributors being able to unilaterally make changes. bitcoin.org must be managed by established organizations if the bitcoin community wants to be respected and taken seriously by the financial community. banks wont use bitcoin and take it seriously if these anons hold so much influence and power...

theymos and cobra must hand over bitcoin.org to organizations or people trusted and respected by the community.

**Comment by JimHarperDC** [comment]
Most people, including people in banks, do rely on a fixed identity as assurance that a person is a reliable actor. But a fixed identity is a proxy for qualities that are possible to build around a pseudonym.

A more careful statement of this problem, if it is a problem, might be what organizational structure and qualities in leadership bitcoin.org needs to be reliable for the community and (especially) prospective members of the community. That could be compared to the roles that pseudonymous leaders/participants have. 

My two satoshis, contributed in hopes of discussion that is not personality-based or controversy-driven.

Jim Harper

**Comment by harding** [comment]
@ConcernedBitcoiner am I reading this correctly that you're using a pseudonymous identity to complain about people who use pseudonymous identities?

**Comment by luke-jr** [comment]
Hmm, so it's a problem to you that [some of] the owners of a private website about Bitcoin wish to remain pseudonymous, and therefore you want to put the website in control of other pseudonyms specifically designed to shield against liability (aka organisations)? How does this make sense?

P.S. theymos isn't even pseudonymous...

**Comment by Cobra-Bitcoin** [comment]
I think more people should use new identities and pseudonyms. Real world identities are simply too restricting. A pseudonym will give you more freedom. 

>banks wont use bitcoin and take it seriously if these anons hold so much influence and power...

Who cares what banks think? Do you think early automobile pioneers were begging for the approval and acceptance of existing horse and buggy manufacturers?

It's very unusual to argue against pseudonyms in Bitcoin, given that the entire system was designed and built by a pseudonymous person. I guess "Satoshi Nakamoto" sounds a lot less menacing than "Cøbra" though. That guy was always good at coming up with catchy names.

**Comment by jgarzik** [comment]
Strictly speaking, the main thing with regards to contributors to get right is IP/copyright assignment for the Bitcoin Core codebase (which is separate from bitcoin.org website).

You don't want a single individual to endanger use of Bitcoin Core as fully open source, because their contributions are IP-tainted (patented without being disclosed as such, etc.)

**Comment by shangzhou** [comment]
theymos did an AMA at reddit in 2013. Do your hoemwork before make such a controversial claim in the Bitcoin space.

**Comment by laanwj** [comment]
> bitcoin.org must be managed by established organizations

Serious question: does bitcoin have any "established organizations"? Wasn't that tried before, and that resulted in a lot of people concerned about centralization, and mismanagement within that organization?
Concern trolls have a short memory.

> Strictly speaking, the main thing with regards to contributors to get right is IP/copyright assignment for the Bitcoin Core codebase (which is separate from bitcoin.org website).

Yes, that's a danger for every open-source project. If anyone contributed code that is not licensed under the right license (either deliberate or by accident), that's problematic, and that code needs to be replaced. Whether we know someone's real name is not very relevant there though.
