### ISSUE TITLE
How to check the signatures of distributed Bitcoin Core binaries?

### ISSUE THREAD

**Issue by HamishMacEwan** [bitcoin-dot-org/bitcoin.org#1350]
Source File: _alerts/2016-08-17-binary-safety.md

Is there any way more information on how these hashes can be checked could be provided?

Exhortations to check without the guidance seem a bit cruel.  It's very frustrating.

**Comment by Cobra-Bitcoin** [comment]
https://bitcointalk.org/index.php?topic=1588906.0
