### ISSUE TITLE
Wanna be added as collaborator

### ISSUE THREAD

**Issue by santy2001** [bitcoin-dot-org/bitcoin.org#1353]
Hi, i just wanna be added as collaborator of the bitcoin.org , to participate actively and could merge pull request to the site , and also give us a hand in the process of makin easiest the bitcoin ,

my user is santy2001 , please add me as collaborator in the settings of the bitcoin.org.

I really apreciated

**Comment by Cobra-Bitcoin** [comment]
If you keep contributing commits, you'll have your username displayed here https://bitcoin.org/en/about-us under the "Contributors on GitHub" heading.
