### ISSUE TITLE
why i cant use full node 

### ISSUE THREAD

**Issue by almoharebh** [bitcoin-dot-org/bitcoin.org#1359]
i try to install bitcoin full node connection but I cant ?
 can any one help me .

**Comment by laanwj** [comment]
This is not a helpdesk for bitcoin core, but a ticket tracker for the bitcoin.org site.
You could try asking your question on the bitcoin stack exchange: https://bitcoin.stackexchange.com/
However you'll need to be much more specific in what you're doing.
