### ISSUE TITLE
transaction wont confirm and internal fatal error when I close client

### ISSUE THREAD

**Issue by bakd247** [bitcoin-dot-org/bitcoin.org#1375]
ok....maybe someone out there can save the day...I tried to send 10 dollars worth of btc to bitpay to get the prepaid visa card they offer. Here's what happened.  I generated the receive address on their site...then I sent the btc. All the sudden their address expires without ever receiving anything.  My client said it sent with no problem. So I email tech support about it....they dont know anything about it because they never got anything from me.  Now the transaction is pending in my wallet and is pending for a different amount than the amount I sent.   Then all the sudden and "internal fatal error" occurs every time I close the client.  So I update to version 13...everything is fine....the transaction goes into the mempool....then it happens again....I have $10 frozen in bitcoin and the client wont let me abandon the transaction at all...I'm at the point that if I cant find the answer on here I am going to ebay my hard drfive with password and all for 50 cents......please someone help me.  I have done nothing but mine and talk up bitcoin and now the client crashes on me...I'm not too happy right now to say the least about it...btw...I have all backups and they do nothing when putting in my appdata file...

**Comment by MarcoFalke** [comment]
Make sure to backup your wallet.dat file to an external storage device, then you can try zapping all wallet transactions: http://bitcoin.stackexchange.com/a/45997

**Comment by bakd247** [comment]
ok that got rid of the transaction but now the wallet work sync with the network and keeps getting hung up on the same block...shows all my coin as available but crashes before it syncs saying internal fatal error two times...tried putting my backup dat file in the appdata folder and that did nothing...I don't think these guys on youtube really know that much about this....anyway...anyone know how I can get in sync with the network? I have over 70usd in bitcoin that is inaccessible now in both version 12.1 and 13

**Comment by bakd247** [comment]
no matter what I do now when I open the wallet it says it is verifying the blocks on disk and it crashes when it reaches the same block every time at 5 hours remaining.....
