### ISSUE TITLE
wallet crashes at same sync time everyitme I open it...

### ISSUE THREAD

**Issue by bakd247** [bitcoin-dot-org/bitcoin.org#1376]
It says it is verifying the blocks on disk and then hangs up at the same block every time at "5 hours behind". I am getting peer connections but it wont sync with the network....I just zapped the wallet and it freed up a frozen transaction to not be pending anymore but it keeps crashing everytime...back up dats in the appdata folder does nothing for it....it keeps trying to verify blocks on the disk when I dont even have any blocks on the disk....PLEASE HELP!!!  I am over $75 invested in bitcoin and have been doing nothing but praising and talking about it nonstop and then this happens....

**Comment by bakd247** [comment]
btw i am using version 13 in windows 10 for what its worth

**Comment by cloudnthings** [comment]
Sent from the edgesa
On 24/09/2016 13:11, "bakd247" <notifications@github.com> wrote:
>
> It says it is verifying the blocks on disk and then hangs up at the same
block every time at "5 hours behind". I am getting peer connections but it
wont sync with the network....I just zapped the wallet and it freed up a
frozen transaction to not be pending anymore but it keeps crashing
everytime...back up dats in the appdata folder does nothing for it....it
keeps trying to verify blocks on the disk when I dont even have any blocks
on the disk....PLEASE HELP!!! I am over $75 invested in bitcoin and have
been doing nothing but praising and talking about it nonstop and then this
happens....

**Comment by bakd247** [comment]
Okay.....I don't see a response here...just what I wrote....????
