### ISSUE TITLE
So apparently if my computer crashes I lose my bitcoin even though I have a backup dat file on a separate hard disk and my own password?

### ISSUE THREAD

**Issue by bakd247** [bitcoin-dot-org/bitcoin.org#1377]
I have even tried re-downloading core and every single version locks up so apparently I just lost $75 worth of bitcoin because the damn thing doesn't work in windows....every other coin I use works just fine...litecoin, dash/darkcoin, cannabis coin and even my ethereum node works fine....bitcoin just doesn't work in windows 10 when you go to send coins it only receives them...So apparently if my computer crashes I lose my bitcoin even though I have a backup dat file on a separate hard disk and my own password?

**Comment by luke-jr** [comment]
This isn't a support forum. [Try IRC](http://webchat.freenode.net/?channels=%23bitcoin)

**Comment by bakd247** [comment]
I just did what bitcoin.org told me to by clicking on he "report a problem" button

**Comment by bakd247** [comment]
Btw I tried that and no one has a clue on there...i havnt been able to sync my qt wallet for 3 days and its really starting to piss me off...i really don't care where I post at this point because I have a lot of money on the line right now with this

**Comment by bakd247** [comment]
Finally figured out version 13 reindexing command....why are the commands for the new update not the same? Or at least put command line options in the appdata folder or something...but I syncing so I will let you all know.....this has been holding up my money for days so I hope my frustration is understood....the fact that it is so hard to find a way to fix a problem is the only reason everyone I know refuses to invest in bitcoin...that and the fact that there is no way to spend it on a debit card without a third party...

**Comment by bakd247** [comment]
That did not but loose all my coin....i am done with bitcoin......this stupid ass software just stole $75 from me and apparently no one knows how to fix it..

**Comment by MarcoFalke** [comment]
You very likely have a corrupt files in your data directory. If a reindex does not help, you can rename/backup your data dir such that it is gone from the default location: https://en.bitcoin.it/wiki/Data_directory#Windows

Afterward, place your `wallet.dat` (and only the wallet) in the data dir and let the client sync from the network.

**Comment by bakd247** [comment]
Tried that already.....nothing changed after I did that either....

**Comment by bakd247** [comment]
It keeps saying its checking the blocks on disk and hangs half way through...wont even attempt to sync to network

**Comment by bakd247** [comment]
I even uninstalled it and reinstalled then put my dat file in the appdata folder...transactions show on the right but it wont show any value anymore now...
