### ISSUE TITLE
Is it possible to update the bootstrap.dat file?

### ISSUE THREAD

**Issue by cryptid11** [bitcoin-dot-org/bitcoin.org#1380]
This one: https://bitcoin.org/bin/block-chain/
Or please remove it, seems like an abandoned project if nobody update it for almost 2 years... 
Thanks

**Comment by laanwj** [comment]
Didn't even know bitcoin.org was hosting that. Ever since bitcoin core has parallel block download, no one is maintaining the bootstrap torrent anymore, makes sense to remove it.

**Comment by harding** [comment]
About a year ago, I suggested removing in https://github.com/bitcoin-dot-org/bitcoin.org/issues/846 but @jgarzik asked that we keep hosting the historic torrent start file for research and other uses.  At that time, we moved the directory (to break any existing links to it "for faster download") and added a preface to the [README](https://bitcoin.org/bin/block-chain/README.txt) in the directory explaining the situation:

> As of Bitcoin Core version 0.10.0 and later, the block chain bootstrap
> torrent hosted here takes more time to download and import than it would
> to simply start Bitcoin Core and let it sync itself.

I'm slightly in favor of removing the directory, but don't think keeping it around would be an issue if people want that.

**Comment by laanwj** [comment]
Sure, it doesn't hurt to keep it there if it's clear that it is for historical research purposes and not "maintained" on purpose.

But supposedly that was not clear to the OP so maybe we need an even bigger warning.

**Comment by laanwj** [comment]
I think the readme is clear though. Nothing to be done here.
