### ISSUE TITLE
I'm not that tech savvy, how do I easily update my wallet?

### ISSUE THREAD

**Issue by jakussnakus64** [bitcoin-dot-org/bitcoin.org#1404]
Source File: _alerts/2016-11-01-alert-retirement.md

**Comment by MarcoFalke** [comment]
@jakussnakus64 You can check the version of the software when you start the program or in the "About"-menue. In case the version is no longer supported, please head over to https://bitcoin.org/en/download and follow the directions.

**Comment by jakussnakus64** [comment]
Nice, Thanks MarcoFalke
