### ISSUE TITLE
Outdated information on non-english bitcoin core download page?

### ISSUE THREAD

**Issue by sakamoto1255** [bitcoin-dot-org/bitcoin.org#1407]
Hi. I'm Korean Bitcoin core user.
I think information on the download page(https://bitcoin.org/ko/download) that translated to korean guides users 'In order to speed up sync blockchain data, bootstrap.dat (which is linked to torrent file attached in bitcoin.org) might help.'
I've heard that version 0.7.1 and later supports fast synchronization than using bootstrap.dat.
Therefore, In order to prevent Korean users not to struggle with outdated information, administer of the homepage should edit the page.

**Comment by Mirobit** [comment]
Thanks for the report. This issue has been fixed on Transifex. With the next update of the language files this should be fixed on bitcoin.org as well.
