### ISSUE TITLE
Typo in block version header data type?

### ISSUE THREAD

**Issue by axvm** [bitcoin-dot-org/bitcoin.org#1413]
Hello,

[Developer reference says](https://bitcoin.org/en/developer-reference#block-headers) version header data type is `uint32` but as @fanatid mention in bitcoinjs/bitcoinjs-lib#712 
[protocol documentation says](https://en.bitcoin.it/wiki/Protocol_documentation#Block_Headers) version header datatype is `signed int32`.

I'd like to know who is right. Thanks.

Source File: _includes/devdoc/ref_block_chain.md

**Comment by axvm** [comment]
There is definitely a typo in developer reference because [nVersion declared as `signed int32` in official client.](https://github.com/bitcoin/bitcoin/blob/master/src/primitives/block.h#L24)

**Comment by MarcoFalke** [comment]
@axvm Pull request welcome

**Comment by axvm** [comment]
@MarcoFalke done. Let me know if I need to change something in pr.

**Comment by axvm** [comment]
Made PR in correct repo.
