### ISSUE TITLE
New Design

### ISSUE THREAD

**Issue by SandroIeva** [bitcoin-dot-org/bitcoin.org#1415]
Hello,

iam a screen designer from hamburg germany and wanna work on a new 
bitcoin.org layout. What persons are involved in this project? 

regards Sandro

**Comment by wbnns** [comment]
@SandroIeva Hi, thanks for offering to potentially enhance the site and improve the layout with a new design. There are higher priorities at the moment, such as improving translation coverage, reviewing wallets and keeping other content up to date, so we'll be sticking with the current design for now.
