### ISSUE TITLE
New event in Arnhem Bitcoincity: A Bitcoin Brunch (and Christmas Bitcoin Shopping)

### ISSUE THREAD

**Issue by annetdeboer** [bitcoin-dot-org/bitcoin.org#1416]
- date: "2016-12-18"
      title: "A Bitcoin Brunch (and Christmas Bitcoin Shopping)"
      venue: "VANNU"
      address: "Jansplein 48"
      city: "Arnhem Bitcoincity"
      country: "The Netherlands"
      link: "https://www.meetup.com/Arnhem-Bitcoin-Users/events/235650407/"

**Comment by Cobra-Bitcoin** [comment]
It's been added.
