### ISSUE TITLE
Sounds like circle is discontinuing their Bitcoin offerings and should be removed.

### ISSUE THREAD

**Issue by gmaxwell** [bitcoin-dot-org/bitcoin.org#1426]
http://www.wsj.com/articles/bitcoin-powerhouse-will-pull-the-plug-on-bitcoin-1481104800

**Comment by jgarzik** [comment]
Removing the buy/sell ability does not mean they stopped being a wallet.

**Comment by MarcoFalke** [comment]
bitcoin.org currently reads: "It provides the ability to instantly
purchase and sell bitcoins using either a credit card or a U.S. bank
account."

So that sentence should be adjusted.

**Comment by crwatkins** [comment]
The article at https://support.circle.com/hc/en-us/articles/217972003 seems to claim that Circle will hold bitcoin for existing users in an insured account and allow them to send and receive bitcoin until that account is converted to local currency at which point the users can no longer return to bitcoin.

However, I can find no way to send or receive bitcoin with a new account.   Can anyone provide any information to the contrary?   

If there is no way to use bitcoin in new accounts, I will submit a PR in a few days to remove Circle from the wallet listings if no one else does first.

**Comment by Cobra-Bitcoin** [comment]
We should remove them! They've given up on bitcoin, so they don't deserve to be on bitcoin.org.

**Comment by achow101** [comment]
They should be removed. It appears that new accounts will not be able to use Bitcoin. They are only keeping Bitcoin for current users who use Bitcoin on their platform. Once those users switch to another currency, they cannot switch back to Bitcoin. New accounts can't set Bitcoin as the currency either.

**Comment by crwatkins** [comment]
PR #1427 has been submitted by @achow101.  Thanks Andrew.  Any addition comments on the topic can be made on PR #1427.
