### ISSUE TITLE
Soft Fork Definition

### ISSUE THREAD

**Issue by laudaa** [bitcoin-dot-org/bitcoin.org#1431]
The soft fork definition, as found [here](https://bitcoin.org/en/glossary/soft-fork):

> A temporary fork in the block chain which commonly occurs when miners using non-upgraded nodes violate a new consensus rule their nodes don’t know about.

Seems quite different from what we can find on the [Wiki](https://en.bitcoin.it/wiki/Softfork):

> A softfork is a change to the bitcoin protocol wherein only previously valid blocks/transactions are made invalid. Since old nodes will recognise the new blocks as valid, a softfork is backward-compatible. This kind of fork requires only a majority of the miners upgrading to enforce the new rules.

Should be a trivial change in this [file](https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/_data/glossary/en/soft-fork.yaml).

**Comment by theymos** [comment]
Yeah, that's totally wrong. The wiki text seems pretty perfect to me.

**Comment by Mirobit** [comment]
Addressed in #1436
