### ISSUE TITLE
Can any one know how to run Full node and fix this issue

### ISSUE THREAD

**Issue by almoharebh** [bitcoin-dot-org/bitcoin.org#1432]
Bitcoin node at 2.​88.​137.​143:8333 has stalled and does not appear to be downloading newer blocks from its peers.
If you are running this node, try restarting the Bitcoin client. If the issue persists, please report it to the software maintainer of the Bitcoin client.

2-Bitcoin node at 2.​88.​137.​143:8333 is currently unreachable.
If you are running this node, please ensure the Bitcoin client is running and accessible externally at port 8333.

**Comment by wbnns** [comment]
@almoharebh Hello, sorry you're experiencing an issue. For support setting up and running a full node, please try posting on [Bitcoin Stack Exchange](https://bitcoin.stackexchange.com/) instead. Also, these messages appear to be from Bitnodes, not from your machine. Please confirm that your node is running and also check your `debug.log` for any issues before reporting there.

**Comment by almoharebh** [comment]
yes i copy this messages from bitnode some time get up and some time get down .
