### ISSUE TITLE
Remove/Replace Bitcoin Foundation donation section

### ISSUE THREAD

**Issue by Mirobit** [bitcoin-dot-org/bitcoin.org#1433]
Currently the [Support Bitcoin](https://bitcoin.org/en/support-bitcoin) site links to the Bitcoin Foundation. With the [removal](https://github.com/bitcoin-dot-org/bitcoin.org/pull/1419) from the resources page with should also remove the donation link.

Is there any specific Organisation that deserves to be linked there? Bitcoin Core removed their donation page. The only Non-profit that supports Bitcoin I can think of if is [CoinCenter](http://www.coincenter.org/donate)

**Comment by luke-jr** [comment]
Bitcoin Core never had a donation page. The closest is the [sponsorship programme](https://bitcoincore.org/en/about/sponsorship/programme/) which is still active (although I don't think I've ever seen any use of it).

**Comment by wbnns** [comment]
@Mirobit Hi there! Thanks for noting the additional link. It has now been removed in #1419. A subsequent series of PRs will correct the remaining instances across different translations so as to keep everything in sync w/ Transifex (our translation management platform).
