### ISSUE TITLE
I suspect that the sender has paid too small an amount. because of this, the translation is stuck on one.

### ISSUE THREAD

**Issue by artemkri** [bitcoin-dot-org/bitcoin.org#1434]
Source File: _alerts/2016-11-01-alert-retirement.md

I suspect that the sender has paid too small an amount. because of this, the translation is stuck on one.
e066e195e4eca45049b89ce225ebfc806dc9c8a89f0b2283e3dac7e9aac4c969

**Comment by Mirobit** [comment]
I don't see the issue or connection between retirement of the alert system and stuck txs.

**Comment by wbnns** [comment]
@artemkri Hello, apologies, as @Mirobit mentioned it's not clear what the issue you're referring to is. I'm closing this for now, however, please feel free to follow back up if there's something we missed.
