### ISSUE TITLE
CES Digital Money Forum

### ISSUE THREAD

**Issue by Erikazee** [bitcoin-dot-org/bitcoin.org#1453]
- date: 2017-01-05
      title: "CES Digital Money Forum"
      venue: "Las Vegas Convention Center"
      address: "3150 Paradise Road"
      city: "Las Vegas, NV"
      country: "USA"
      link: "http://thedigitalmoneyforum.com/"

**Comment by Erikazee** [comment]
You don’t want to miss a minute of The Digital Money Forum at CES where we look at the role of everything from new payment systems to borderless eCommerce, to biometrics and authentication systems to virtual currencies, and the most disruptive of them all – the blockchain economy.

**Comment by wbnns** [comment]
@Erikazee Thanks - this is also part of #1463. 👍
