### ISSUE TITLE
The North American Bitcoin Conference

### ISSUE THREAD

**Issue by Erikazee** [bitcoin-dot-org/bitcoin.org#1454]
- date: 2017-01-17 & 18
      title: "The North American Bitcoin Conference"
      venue: "James L Knight Centre"
      address: "400 SE 2nd Ave"
      city: "Miami, FL"
      country: "USA"
      link: "http://btcmiami.com/"

**Comment by Erikazee** [comment]
The North American Bitcoin Conference is carefully curated to teach you about next-level, actionable innovation and technology you can utilize the very next day.

**Comment by wbnns** [comment]
@Erikazee Hi, thank you - this is pending to be added as part of PR #1463.
