### ISSUE TITLE
CoinAgenda Carribean

### ISSUE THREAD

**Issue by Erikazee** [bitcoin-dot-org/bitcoin.org#1455]
- date: 2017-03-3, 4 & 5
      title: "CoinAgenda Carribean"
      venue: ""
      address: ""
      city: "San Juan"
      country: "Puerto Rico"
      link: "http://coinagenda.com/"

**Comment by Erikazee** [comment]
CoinAgenda Caribbean is a new conference that combines the historic mission of CoinAgenda and BitAngels to connect and inform investors and entrepreneurs in the bitcoin, blockchain and cryptocurrency sectors with three first-of-a-kind, mini-conferences within the main event.

**Comment by wbnns** [comment]
@Erikazee Hello, thanks for submitting this. Could you please provide a venue and address?

**Comment by Erikazee** [comment]
Hi Will,

We actually are nailing down the venue early next month. Would it be ok if
I emailed it to you then?

Thanks,

Erika Zapanta
Account Executive
Transform Public Relations
Cell: 702-503-1239
Skype: Erika Zapanta

**Comment by wbnns** [comment]
@Erikazee Ok, thanks for the update. Once a venue is confirmed, please let us know.
