### ISSUE TITLE
"ListSinceBlock" docs wrong?

### ISSUE THREAD

**Issue by wyager** [bitcoin-dot-org/bitcoin.org#1457]
Source File: _includes/devdoc/bitcoin-core/rpcs/rpcs/listsinceblock.md

The doc field for "blockindex" says "Only returned for confirmed transactions. The block height of the block on the local best block chain which includes this transaction". I'm pretty sure this is wrong; from my end, it looks like "blockindex" is actually the index of the transaction within the block. I'm getting values below a couple thousand, whereas at least the block hash seems correct.

**Comment by Mirobit** [comment]
Same problem here: #1237.

I have a branch that fixes a few things in helpers/vars.md (including blockindex). Pull request will follow soon.

**Comment by Mirobit** [comment]
Thanks, addressed in 9c9edae6f644e3822f18b39e6245415bef6ebe9d

**Comment by wyager** [comment]
Cheers, closing.
