### ISSUE TITLE
65 GB blockchain size on download page is misleading

### ISSUE THREAD

**Issue by dabura667** [bitcoin-dot-org/bitcoin.org#1458]
#1225 was a hard coded fix for the growing blockchain size.

Since we want people to have a good estimate of how much disk space they need, I propose finally making it variable, OR performing a new one time hard coded fix to 100 GB.

**Comment by wbnns** [comment]
@dabura667 Hello, thanks for bringing this to attention. I have a working branch  to update the instructions for running a full node as of 0.13.1 that will resolve this issue. 👍
