### ISSUE TITLE
2017 Blockchain Fintech Summit of Silicon Valley

### ISSUE THREAD

**Issue by kevinmabitcoin** [bitcoin-dot-org/bitcoin.org#1460]
- date: 2017-01-07
      title: "2017 Blockchain Fintech Summit of Silicon Valley"
      venue: "Santa Clara Conventional Center, Great America Ballroom"
      address: "5001 Great America Pkwy"
      city: "Santa Clara"
      country: "USA"
      link: "https://www.eventbrite.com/e/the-blockchain-fintech-summit-of-silicon-valley-tickets-29506617086"

**Comment by kevinmabitcoin** [comment]
The conference will act as an open forum for issue-driven dialogues, strategies and collaboration among Blockchain trailblazers. We expect to discuss a range of specific real-world applications across markets and industries, such as finance, IoT, and philanthropy through keynotes, panels and shark tanks, followed by startup pitch demo. What makes the summit even more exciting is that government officials, influencers, regulators and compliance from China will join our discussion on how to achieve widespread Blockchain prosperity. All of these will contribute to building a clearer picture for the future of Blockchain.

**Comment by wbnns** [comment]
@kevinmabitcoin Hello, thank you for submitting this. It is pending to be added as part of PR #1463.
