### ISSUE TITLE
Over long

### ISSUE THREAD

**Issue by tinhueic** [bitcoin-dot-org/bitcoin.org#1466]
Source File: _alerts/2016-11-01-alert-retirement.md

https://blockchain.info/tx/2925a39c2ec6d7f8252e44fdcd9b121995296dde99eea9679ea51f422bd0ce9a
Please finish this txid

**Comment by wbnns** [comment]
@tinhueic Hello, apologies, I'm not sure what the issue you're referring to is. I'm closing this for now, however, please feel free to follow back up if there's something we missed.
