### ISSUE TITLE
How to uninstall BITCOIN core

### ISSUE THREAD

**Issue by MrGabe** [bitcoin-dot-org/bitcoin.org#1471]
I would like to know if you could help me, I downloaded the wallet of BITCOIN CORE and it occupied 25GB and filled my SSD i did not know that it takes more than 60GB, can you help me to uninstall the installed 25GB?
	
I could not install entire because my ssd only had 25GB available, so it took up space, it already deletes the wallet but the 25GB is still occupied ... my operating system is windows 7

gabrielmenegattireis@outlook.com
please

**Comment by MarcoFalke** [comment]
* Make sure you do not have any funds in your wallet!
* Then, delete your [datadir](https://en.bitcoin.it/wiki/Data_directory#Windows).

**Comment by MrGabe** [comment]
Thank u so much, easy =D

________________________________
De: MarcoFalke <notifications@github.com>
Enviado: quarta-feira, 4 de janeiro de 2017 09:48:13
Para: bitcoin-dot-org/bitcoin.org
Cc: MrGabe; Author
Assunto: Re: [bitcoin-dot-org/bitcoin.org] How to uninstall BITCOIN core (#1471)


  *   Make sure you do not have any funds in your wallet!
  *   Then, delete your datadir<https://en.bitcoin.it/wiki/Data_directory#Windows>.

-
