### ISSUE TITLE
Error in the page

### ISSUE THREAD

**Issue by hollyroody** [bitcoin-dot-org/bitcoin.org#1476]
Location: https://bitcoin.org/en/developer-reference#compactsize-unsigned-integers

In the paragraph "CompactSize Unsigned Integers" the last mentions an error. 
It says  : 
> For example, the number 515 is encoded as 0xfd0302.

It should say :
> For example, the number 515 is encoded as 0xfd0203.

**Comment by achow101** [comment]
No, the page is correct. It is supposed to be in little-endian order, which is the normal way (big endian) but byte swapped.
