### ISSUE TITLE
my bitcoin wasnt credited 

### ISSUE THREAD

**Issue by tpomps05** [bitcoin-dot-org/bitcoin.org#1482]
I generated an account through bitcoin core wallet since yesterday and 0.069629 BTC was transfered into the address generated for me and up till today . i have not yet been credited to my bitcon core wallet .
the other network gave me verification of the money being sent and i'm just confused  

i hope this got resolved as soon as possible 

Source File: _alerts/2016-11-01-alert-retirement.md

**Comment by tpomps05** [comment]
I generated an account through bitcoin core wallet since yesterday and 0.069629 BTC was transfered into the address generated for me and up till today . i have not yet been credited to my bitcon core wallet .
the other network gave me verification of the money being sent and i'm just confused

i hope this got resolved as soon as possible

this was the link of the verification that was provided by the sender  
I generated an account through bitcoin core wallet since yesterday and 0.069629 BTC was transfered into the address generated for me and up till today . i have not yet been credited to my bitcon core wallet .
the other network gave me verification of the money being sent and i'm just confused

https://btc.blockr.io/tx/info/a4a3b141288e4e9bb0e31f307d727d3b2fb43800d19a8bcf3e820734deca22b0

**Comment by wbnns** [comment]
@tpomps05 Hello, if you need technical support, please visit the [Help page](https://bitcoin.org/en/bitcoin-core/help) for Bitcoin Core.

**Comment by tpomps05** [comment]
Hello.
I founded my botcoin core wallet with $60 and I'm yet to be credited.
I have complained to the site that out to transfer the money and they sent
me a clarification that the money was transferred to the address provided
through your bitcoin core app.

Please help
