### ISSUE TITLE
New event in Arnhem Bitcoincity: 28th of January

### ISSUE THREAD

**Issue by annetdeboer** [bitcoin-dot-org/bitcoin.org#1486]
- date: 2017-01-28
      title: "Bitcoin Brunch @ International Day of Privacy"
      venue: "Urban Chef"
      address: "Koningstraat 50/51"
      city: "Arnhem Bitcoincity"
      country: "The Netherlands"
      link: "https://www.ArnhemBitcoinstad.nl"

**Comment by annetdeboer** [comment]
Does it help if I give the lat/long as well? Just in case, it's: 
"lat":"51.980132"
"lon":"5.910262"

**Comment by wbnns** [comment]
@annetdeboer Hello, thanks for submitting this. This is now scheduled to be merged and deployed and will be added soon.
