### ISSUE TITLE
Bitcoin wallet

### ISSUE THREAD

**Issue by BangLy** [bitcoin-dot-org/bitcoin.org#1487]
Source File: _alerts/2014-02-11-malleability.html

Why i can't send my bitcoin or sell it i don't have the api key for this address but i can not send i only want my wallet so easy and don't have the api key how can i  make it easy for my wallet blockchain

**Comment by wbnns** [comment]
@BangLy Hello, please [go here](http://www.reddit.com/r/bitcoinbeginners) for technical support.
