### ISSUE TITLE
CoinFestUK

### ISSUE THREAD

**Issue by CoinFestUK** [bitcoin-dot-org/bitcoin.org#1489]
- date: 2017-04-07
      title: "CoinFestUK"
      venue: "Manchester"
      address: "Manchester"
      city: "Manchester"
      country: "United Kingdom"
      link: "https://coinfestuk.org/"

**Comment by wbnns** [comment]
@CoinFestUK Hello, thanks for adding this. Could you please resubmit this once you all have selected a venue and have an address? We need that in order to be able to add the entry.
