### ISSUE TITLE
Future of Fintech

### ISSUE THREAD

**Issue by mfusher1** [bitcoin-dot-org/bitcoin.org#1492]
- date: 2017-06-27
      title: "Future of Fintech"
      venue: "Jazz at Lincoln Center"
      address: "10 Columbus Circle"
      city: "New York"
      country: "NY"
      link: "http://events.cbinsights.com/future-of-fintech"

**Comment by wbnns** [comment]
@mfusher1 Thank you for this event submission. #1502 adds it to the site.
