### ISSUE TITLE
Indonesia Flag 

### ISSUE THREAD

**Issue by linthum** [bitcoin-dot-org/bitcoin.org#1496]
Hi All,

On the page https://bitcoin.org/en/exchanges 
The flag of Indonesia is similar to an Indian flag. 

![image](https://cloud.githubusercontent.com/assets/8229589/22447720/10bb7e26-e74c-11e6-9814-2a667e93e145.png)

Kindly review

Best Regards,
Ratul Jindal

**Comment by wbnns** [comment]
Hi @linthum, thanks for mentioning this. I've just submitted PR #1498 to resolve the issue. 👍

**Comment by linthum** [comment]
@wbnns Thank will :+1:

**Comment by wbnns** [comment]
@linthum You're welcome!
