### ISSUE TITLE
Reject nonstandard tx message may not have hash.

### ISSUE THREAD

**Issue by evoskuil** [bitcoin-dot-org/bitcoin.org#1505]
Location: https://bitcoin.org/en/developer-reference#reject

> The transaction will not be mined or relayed because the rejecting node considers it non-standard—a transaction type or version unknown by the server. Extra data is the rejected transaction’s TXID.

This does not appear to be consistently applied by Satoshi nodes. We periodically see no bytes in the supposed place of the tx hash. For example, this message decodes as follows: 

```
/Satoshi:0.12.1/
message payload: 0x0274784016746f6f2d6c6f6e672d6d656d706f6f6c2d636861696e
tx : nonstandard : too-long-mempool-chain : <empty>
```
I haven't dug through their sources to see if/when this is the case, but it's not reliably seen on the wire.

**Comment by wbnns** [comment]
[Bounty](https://github.com/bitcoin-dot-org/bitcoin.org#earn-bitcoin-for-contributing): **5,000 bits / ~$10 USD**
