### ISSUE TITLE
Conflict in installguide

### ISSUE THREAD

**Issue by Pixdigit** [bitcoin-dot-org/bitcoin.org#1506]
The official download link leads to the ppa. However the ppa recommends to use official binaries.
 Which one should then be used and where downloaded from?

**Comment by harding** [comment]
Just to clarify the issue, on bitcoin.org/en/download , there's an "Ubuntu" link:

![2017-02-10-14_19_09_354991511](https://cloud.githubusercontent.com/assets/61096/22840559/f8aa5048-ef9b-11e6-8fee-ec47647dc43f.png)

Clicking that link takes you to a page that says,

![2017-02-10-14_20_08_192984721](https://cloud.githubusercontent.com/assets/61096/22840577/0f18371e-ef9c-11e6-8c31-554db01fd42c.png)

---

Maybe a simple solution for bitcoin.org/en/download is to rename "Ubuntu (PPA)" to "Unofficial PPA".  E.g.

![2017-02-10-14_29_04_834613600](https://cloud.githubusercontent.com/assets/61096/22840888/53fac846-ef9d-11e6-874e-fe0bc116ff72.png)

**Comment by wbnns** [comment]
@harding @Pixdigit Thanks. Just opened #1507 to resolve this. I added a note underneath the link so that people who don't recognize the Ubuntu logo will still know it's an Ubuntu PPA (and also that it's unofficial).

**Comment by wbnns** [comment]
I closed #1507 unmerged based on the discussion there. There didn't seem to be much weight one way or the other in the convo (and no additional comments) so let's just leave as-is.
