### ISSUE TITLE
BlockchainUA conference Kyiv

### ISSUE THREAD

**Issue by alexvechirko** [bitcoin-dot-org/bitcoin.org#1509]
- date: 2017-03-17
      title: "BlockchainUA conference Kyiv"
      venue: "Conference Hall “Oasis"
      address: "Vasylia Lypkivskoho St, 1А, 02000, Entertaining complex "Ultramarine, 3rd floor"
      city: "Kyiv"
      country: "Ukraine"
      link: "http://blockchainua.com/"

**Comment by wbnns** [comment]
@alexvechirko Thanks for submitting this.

Unless others object, this will be merged on Sunday, February 19th.

**Comment by alexvechirko** [comment]
@wbnns Hi, when will this issue be merged?
