### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by CoinFestUK** [bitcoin-dot-org/bitcoin.org#1511]
- date: 2017-04-07
      title: "CoinFestUK"
      venue: "Manchester Conference Centre"
      address: "Sackville Street, M1 3BB"
      city: "Manchester"
      country: "United Kingdom"
      link: "https://www.coinfestuk.org"

**Comment by wbnns** [comment]
@CoinFestUK Hello, this has been added to the Events page. Thanks for submitting it!
