### ISSUE TITLE
Blockchain Hackathon

### ISSUE THREAD

**Issue by alexvechirko** [bitcoin-dot-org/bitcoin.org#1517]
- date: 2017-03-18
      title: "THE SECOND ALL-UKRAINIAN BLOCKCHAIN HACKATHON"
      venue: "2th floor"
      address: "Verkhnii Val st, 10"
      city: "Kyiv"
      country: "Ukraine"
      link: "http://blockchainua-hackathon.com/en"

**Comment by wbnns** [comment]
@alexvechirko Thanks for suggesting this as well as your other event in Kyiv. Both have been added to the Events page. 👍
