### ISSUE TITLE
Blockchain Expo

### ISSUE THREAD

**Issue by BlockchainExpo** [bitcoin-dot-org/bitcoin.org#1518]
- date: 2017-06-01
      title: "Blockchain Expo Europe"
      venue: "Estrel"
      address: "Sonnenallee 225, 12057"
      city: "Berlin"
      country: "Germany"
      link: "www.blockchain-expo.com/europe"

**Comment by wbnns** [comment]
@BlockchainExpo Hello, thanks for suggesting this event. It has been added to the site.

**Comment by BlockchainExpo** [comment]
Hi Bill,

Many thanks for this.

All the best,
Beth

Beth Betts
Marketing Manager
TechForge Media | Blockchain Expo
P:   +44 (0) 117 980 9020
W:  www.techforge.pub<http://www.techforge.pub/> | www.blockchain-expo.com<http://www.blockchain-expo.com/>
E:    beth@techforge.pub<mailto:beth@techforge.pub> | LinkedIn<https://www.linkedin.com/in/beth-betts>
[Untitled design (35)]
