### ISSUE TITLE
Blockchain Tech Summit

### ISSUE THREAD

**Issue by abelotti** [bitcoin-dot-org/bitcoin.org#1519]
- date: 2017-08-26
      title: "Blockchain Technology Summit - Technical Blockchain Training for Devs"
      venue: "Online"
      address: "Online"
      city: "Online"
      country: "Online"
      link: "http://blockchaintechsummit.com"

**Comment by wbnns** [comment]
Hello, apologies, our event map doesn't currently support online events.
