### ISSUE TITLE
rescan an existing address

### ISSUE THREAD

**Issue by tal-beja** [bitcoin-dot-org/bitcoin.org#1520]
Source File: _includes/devdoc/bitcoin-core/rpcs/rpcs/importaddress.md

> Notes: if the address or pubkey script is already in the wallet, the block database will not be rescanned even if this parameter is set

This is not really true, if you try to import the same address twice with (or without) the rescan flag set to true, it rescan twice, and not only for the first time as this docs suggests.

**Comment by wbnns** [comment]
[Bounty](https://github.com/bitcoin-dot-org/bitcoin.org#earn-bitcoin-for-contributing): **5,000 bits / ~$10 USD**
