### ISSUE TITLE
Blockchain Expo North America

### ISSUE THREAD

**Issue by BlockchainExpo** [bitcoin-dot-org/bitcoin.org#1521]
- date: 2017-11-29
      title: "09.00"
      venue: "Santa Clara Convention Center"
      address: "5001 Great America Pkwy, Santa Clara, 95054"
      city: "CA"
      country: "USA"
      link: "http://blockchain-expo.com/northamerica/"

**Comment by wbnns** [comment]
@BlockchainExpo Hello, thanks for submitting this. Is the title correct? It's showing as `09.00` above, however, it seems the title should be `Blockchain Expo`.

**Comment by BlockchainExpo** [comment]
Hi,

Sorry about that, yes it should be Blockchain Expo North America. Not sure where the 09.00 came from!

Thanks,
Beth

Beth Betts
Marketing Manager
TechForge Media | Blockchain Expo
P:   +44 (0) 117 980 9020
W:  www.techforge.pub<http://www.techforge.pub/> | www.blockchain-expo.com<http://www.blockchain-expo.com/>
E:    beth@techforge.pub<mailto:beth@techforge.pub> | LinkedIn<https://www.linkedin.com/in/beth-betts>
[Untitled design (35)]

**Comment by wbnns** [comment]
@BlockchainExpo Ok, thanks for confirming. This is now scheduled to be added to the site.
