### ISSUE TITLE
Link to Gavin's example payment request generator is broken

### ISSUE THREAD

**Issue by rusticbison** [bitcoin-dot-org/bitcoin.org#1527]
Location: https://bitcoin.org/en/developer-examples#payment-processing

The link to Gavin's example payment request generator is broken: http://bitcoincore.org/~gavin/createpaymentrequest.php

**Comment by laanwj** [comment]
Should have moved to https://dev.bitcoincore.org/~gavin/createpaymentrequest.php
However that is not working either.

You can find the source code here, if you want to use it locally: https://github.com/gavinandresen/paymentrequest/blob/master/php/demo_website/createpaymentrequest.php

**Comment by wbnns** [comment]
@rusticbison @laanwj Thanks! Submitted #1538 to resolve this issue.
