### ISSUE TITLE
Oral Arguments 

### ISSUE THREAD

**Issue by theochino** [bitcoin-dot-org/bitcoin.org#1530]
- date: 2017-03-16
      title: "Oral Arguments on the Status of the Bitlicense in New York"
      venue: "New York State Supreme Court"
      address: "71 Thomas - Room 204 - Part 46"
      city: "New York"
      country: "USA"
      link: "https://www.meetup.com/Article-78-Against-NYDFS/events/238080585"

**Comment by wbnns** [comment]
@theochino Thanks. I've submitted a pull request to add this to the site. 👍
