### ISSUE TITLE
The Blockchain NZ - May 2017

### ISSUE THREAD

**Issue by salis** [bitcoin-dot-org/bitcoin.org#1535]
- date: 2017-05-08
      title: "The Blockchain NZ 2017"
      venue: "Viaduct Event Centre"
      address: "161 Halsey St"
      city: "Auckland"
      country: "New Zealand"
      link: "http://www.theblockchain.nz/"

**Comment by wbnns** [comment]
@salis Thank you for submitting this. This is scheduled to be added to the site, soon.
