### ISSUE TITLE
New glossary term suggestion: Node

### ISSUE THREAD

**Issue by forkwar** [bitcoin-dot-org/bitcoin.org#1539]
I'm surprised I don't see this on the list.  Only the lightweight/thin/SPV clients seem to be listed.

In addition to the general term "Node", more specific terms:

* Full node
* Archival node
* Pruned node

It may also be worth standardizing on either the word "client" or "node".

**Comment by wbnns** [comment]
[Bounty](https://github.com/bitcoin-dot-org/bitcoin.org#earn-bitcoin-for-contributing): **5,000 bits / ~$10 USD**
