### ISSUE TITLE
New glossary term suggestion: Proof of stake

### ISSUE THREAD

**Issue by forkwar** [bitcoin-dot-org/bitcoin.org#1540]
Also the synonym POW should be added.

**Comment by harding** [comment]
Proof of stake isn't a current or proposed Bitcoin feature, so I don't think it belongs in the developer glossary.  POW is already there (screenshot of [P](https://bitcoin.org/en/developer-glossary#p)):

![2017-05-14-06_30_50_360638090](https://cloud.githubusercontent.com/assets/61096/26033000/1afb5194-386f-11e7-9c6e-8b2e37d7ab99.png)

**Comment by forkwar** [comment]
Good point.  It can be used as a voting mechanism in bitcoin, but since it's not part of the Core protocol, it probably does not deserve a glossary entry.  (Also I meant to say "POS" as the synonym.  Oops.)
