### ISSUE TITLE
Number of fields for an input is wrong

### ISSUE THREAD

**Issue by Huntrr** [bitcoin-dot-org/bitcoin.org#1542]
Location: https://bitcoin.org/en/glossary/input

Inputs are defined as having four fields but only three fields are listed. I believe this sentence

> An input in a transaction which contains four fields: an outpoint, a signature script, and a sequence number

Should be

> An input in a transaction contains **three** fields: an outpoint, a signature script, and a sequence number

Either that or the fields listed are wrong.

**Comment by laanwj** [comment]
Huh. Maybe the writer was counting outpoint as two fields (hash,n). In any case it's worded wrongly.

**Comment by wbnns** [comment]
Thanks guys, I've submitted PR #1545 to resolve this. It will be live and fixed, shortly.
