### ISSUE TITLE
bitcoin.org Inaccessible from Iowa State University

### ISSUE THREAD

**Issue by joel0** [bitcoin-dot-org/bitcoin.org#1543]
I cannot find webmaster contact information for bitcoin.org, so I'm hoping somebody here can either help me or point me in the right direction.

From Iowa State University's campus I am unable to reach bitcoin.org.  All requests time out (HTTP[S] and ping).  This problem has existed for years.  I have contacted university IT and they "don't know why bitcoin.org is unreachable."  I have also contacted Black Lotus and now Level 3, but both refused to reply.  Can somebody check whether there is some sort of block on the server side for 65.110.224.0/19?

**Comment by wbnns** [comment]
@joel0 Hello, can you run a traceroute to bitcoin.org and see where it starts timing out?

**Comment by joel0** [comment]
Here it is.  I believe I ran `nmap` on 208.64.120.0/21 months ago and found that nothing is responding.  It seems to be either my university or Level 3 (Black Lotus) doing the blocking from what I've seen.

<pre>
Tracing route to bitcoin.org [208.64.123.130]
over a maximum of 30 hops:

  1     1 ms    <1 ms    <1 ms  routerb-65-110-241-128.tele.iastate.edu [65.110.241.253]
  2     1 ms    <1 ms    <1 ms  e63dmztest-vlan254.tele.iastate.edu [129.186.254.160]
  3     1 ms    <1 ms    <1 ms  rtr-b31isp1-be158.tele.iastate.edu [192.188.159.159]
  4     1 ms    <1 ms    <1 ms  rtr-e63isp1-be162.tele.iastate.edu [192.188.159.163]
  5     3 ms     3 ms     3 ms  rtr-border-bsb.net.uiowa.edu [198.49.182.173]
  6     4 ms     3 ms     3 ms  rtr-border-lc.net.uiowa.edu [198.49.182.13]
  7    13 ms    13 ms    13 ms  chi-b22-link.telia.net [62.115.50.53]
  8    13 ms    13 ms    13 ms  chi-b21-link.telia.net [62.115.141.177]
  9     *        *        *     Request timed out.
 10     *        *        *     Request timed out.
 11    55 ms    55 ms    55 ms  4.68.62.46
 12    82 ms    73 ms    55 ms  192.184.12.81
</pre>

Thanks.

**Comment by wbnns** [comment]
@joel0 Thanks for sending. I'm not showing any inaccessibility or downtime from Uptime Robot, which the site is currently being monitored with 24/7. Based on this, it would seem that there is some type of specific block that is taking place on that network. Can you open a ticket with the university support team, ask them to run a traceroute and get their feedback?

**Comment by joel0** [comment]
I'm always able to access the bitcoin.org from outside of campus, so I agree that there's some sort of block. 

The university IT said, "If you do a traceroute from campus, you'll see that it clears our network.  It would appear that bitcoin uses black lotus for ddos protection, and they are actually blocking us," and, "We suggest that you contact them and see if this is true."  So the university IT is quite convinced that the issue is outside their network (I'm not fully convinced though).

Would you be able to run `curl` or `wget` from an IP on Black Lotus's network to https://ipv4.hostname.jmay.us/ and http://www.iastate.edu/ ?  I would like to know if this is a bidirectional  unidirectional block.

**Comment by wbnns** [comment]
@joel0 Ok, I see. Thanks. We're actually in the process of switching off of Level 3, which should happen soon (hopefully). I think that will most likely resolve the issue for you. I'll keep this open until it happens, so you can check and confirm if so, afterward.

**Comment by wbnns** [comment]
@joel0 Hello, just wanted to follow back up on this. Can you please try again, now, and let us know if you're still encountering the issue?

**Comment by joel0** [comment]
It works now.  Thanks.

**Comment by wbnns** [comment]
@joel0 Ok, awesome, thanks for letting us know.
