### ISSUE TITLE
Spam site listed under Non-profit organizations > Romania

### ISSUE THREAD

**Issue by odv** [bitcoin-dot-org/bitcoin.org#1546]
Hello!

I was browsing bitcoin.org and noticed a spam link listed in the Community section, under Romania called Fundatia Bitcoin Romania. https://bitcoin.org/en/community#romania

If you go to that page, below the first post, there is a masked advertisement for a romanian webcam studio and two other posts about a particular person that got rich by selling flowers. I won't list his name here but he's quite a known scammer in the romanian internet space. If you check out his twitter handle he has a lot of retweets about romanian webcam studios which to me makes it pretty clear that he's behind this site too.

The Nov 17 and Nov 24 posts have a link to another site that has just one posts, again, about that same individual. If you query http://rotld.ro/engleza/index_en.html fundatiabitcoin.ro and the other 2 spam domains with just one post are owned by the same entity.

I personally think this site should be deleted. It brings absolutely no value to the Bitcoin Community, especially the Romanian one and could later be used to scam Romanian users.

Since I'm brand new here, I also want to thank everybody that contributed to this project.

**Comment by wbnns** [comment]
@odv Hello, thank you very much for bringing this to attention. I've just submitted PR #1547 which will resolve this issue and remove the site.
