### ISSUE TITLE
Ping nonce protocol version inconsistent.

### ISSUE THREAD

**Issue by evoskuil** [bitcoin-dot-org/bitcoin.org#1548]
Source File: _includes/devdoc/ref_p2p_networking.md

This selected text:

```
Added in protocol version 60000 as described by BIP31. 
```

... is inconsistent with the preceding text, [BIP31](https://github.com/bitcoin/bips/blob/master/bip-0031.mediawiki) and [this section](https://bitcoin.org/en/developer-reference#protocol-versions). Should read **60001**.

**Comment by wbnns** [comment]
@evoskuil Hello, thanks for catching this and bringing it to attention. Just submitted PR #1549 which will resolve the issue.
