### ISSUE TITLE
New event : Coinfest in Arnhem Bitcoincity

### ISSUE THREAD

**Issue by annetdeboer** [bitcoin-dot-org/bitcoin.org#1558]
- date: 2017-04-08
      title: "Coinfest"
      venue: "Barley's Biergarten"
      address: "Pauwstraat 4"
      city: "Arnhem Bitcoincity"
      country: "The Netherlands"
      link: "https://www.meetup.com/Arnhem-Bitcoin-Users/events/237435368/"

**Comment by wbnns** [comment]
@annetdeboer Hello, thank you for submitting this. I just wanted to confirm that this has been added to the site.
