### ISSUE TITLE
russian translation of how-it-works

### ISSUE THREAD

**Issue by ilia2s** [bitcoin-dot-org/bitcoin.org#1559]
I found an inaccuracy on "how-it-works" in "Balances - block chain" section. In russian version a word "ledger" in sentence "The block chain is a shared public ledger"  translated as "register" (регистр), but in this context we need to use translation of ledger as finance term. The more precise word will be (реестр, журнал, гросс бух) that denote a main accountant's book.

**Comment by wbnns** [comment]
@ilia2s Thanks for bringing this to attention. Would it be possible for you to join the Russian translation team on Transifex and fix this?

Here's a link: https://www.transifex.com/bitcoinorg/bitcoinorg/

**Comment by ilia2s** [comment]
Yes, I will do it.
