### ISSUE TITLE
UseBitcoins.info is full of outdated/broken links as well as links irrelevant to a majority of people...

### ISSUE THREAD

**Issue by JustAHappyKid** [bitcoin-dot-org/bitcoin.org#1560]
It's also full of annoying advertisements (but I guess they have to try to support the site somehow).

I just went through the first 10 listings for each of categories [General Goods](http://usebitcoins.info/index.php/goods/general-goods), [Hardware/Electronics](http://usebitcoins.info/index.php/goods/hardware), and [Clothing](http://usebitcoins.info/index.php/goods/clothing). I [found](https://github.com/bitcoin-dot-org/bitcoin.org/files/903826/usebitcoins.info.txt) _almost half_ (11 of 24) of the links were outright useless -- 404s, server-not-found's, "coming soon", etc.

For most of the other half of the listings I checked, they pointed to non-English websites (Dutch, Spanish, Greek, etc). _Nothing wrong with that_, but for any given person, that means a majority of the (working) listings are not going to be relevant, and I didn't see any way to target-in on listings for a particular country or region.

UseBitcoins.info is listed prominently on the [Getting Started page](https://bitcoin.org/en/getting-started) as well as less prominently on [several](https://bitcoin.org/en/support-bitcoin) [other](https://bitcoin.org/en/faq) [pages](https://bitcoin.org/en/press). This situation probably doesn't lend well to Bitcoin's "Spend" case.

I'd be happy to produce a patch to replace some/all of these links with link(s) to [another obvious contender](https://spendabit.co/), but I thought it might appear particularly self-serving to do so without discussion first (being a co-founder of said site). Perhaps a multi-pronged solution would be even better -- e.g., giving users an option for search, a business map, or a standard directory. (Though unfortunately I don't know of a standard directory-listing of BTC-accepting businesses that isn't full of outdated links.)

**Comment by wbnns** [comment]
@JustAHappyKid Hello, thanks for the heads up. Agreed, that's not good if people are getting directed to a place that is leading to 404s, etc. Please feel free to submit a pull request for this.

**Comment by JustAHappyKid** [comment]
@wbnns Cool. I will try to work on this next week.

**Comment by wbnns** [comment]
@JustAHappyKid Ok, great, thanks!

**Comment by Mirobit** [comment]
We could link to https://bitcoin.org/en/resources#directories
Spendabit.co is a slick site but I miss a browsing feature and it is not as extensive as usebitcoins or provides a local overview like coinmap.

**Comment by wbnns** [comment]
@Mirobit This alternative SGTM. Thanks.

**Comment by JustAHappyKid** [comment]
@wbnns @Mirobit What do you think about implementing a new "Spend" page to direct people to? ...That way, we could offer a bit more guidance -- "to find products online, do this; for local businesses, like cafes and bars, check here".

I'm envisioning something with three separate images/icons, one for online shopping (Spendabit), one for local businesses (Coinmap), and one for a general directory (useBitcoins.info or similar). And I'm offering to take a stab at it. :-)

**Comment by Mirobit** [comment]
@JustAHappyKid I like the idea. This way we treat all sites equally and provide more guidance.

**Comment by JustAHappyKid** [comment]
@Mirobit Great, well, if @wbnns isn't opposed then I'll start work on this soon.

**Comment by Cobra-Bitcoin** [comment]
We send ~1000 users to them each day, so any alternative is better at this point. Their site is definitely a horrible experience.

**Comment by JustAHappyKid** [comment]
I was hoping to start work on a new "Spend" page today, FYI. I can submit a pull-request with a simple URL swap, in the meantime / as a stop-gap measure, if it helps.

FWIW, we (Spendabit) are looking into starting a more traditional "directory" service (in the vain of UseBitcoins.info) to complement what we already have with the product search. It would probably be a couple months at least, however, before that'd be ready to replace one of the more established directories.

**Comment by JustAHappyKid** [comment]
@wbnns @Microbit @Cobra-Bitcoin Okay, what do you all think about [something like this](https://cloud.githubusercontent.com/assets/20557/25500536/e5fe0fec-2b7e-11e7-81e1-6d0180aed461.png)? If that does the trick, I can swap out all the existing links to UseBitcoins.info for a link to this new page, and then put together a pull-request.

BTW, what is the procedure for dealing with translations for new pages like this one? ...Do we simply put in place the English strings and then wait for others to come along and translate, or do we need to put some kind of placeholders in?

**Comment by Mirobit** [comment]
@JustAHappyKid Looks good.

**Comment by JustAHappyKid** [comment]
[Pull request](https://github.com/bitcoin-dot-org/bitcoin.org/pull/1584) submitted. :-)

**Comment by wbnns** [comment]
@JustAHappyKid Thanks!

**Comment by kitsuphat** [comment]
Get feeds into bitcoin wallet.

**Comment by JustAHappyKid** [comment]
Hey @wbnns and @Mirobit: Just wanted to make sure this one didn't fall off the radar, as it's been about 2 weeks since I updated [the pull-request](https://github.com/bitcoin-dot-org/bitcoin.org/pull/1584). I think we're good to go, but let me know if I missed anything.

**Comment by wbnns** [comment]
@JustAHappyKid Heya! Thanks for following up - I just replied the other day on the PR (#1584). We have one more set of revisions and then I think it's good to go. 👍

**Comment by JustAHappyKid** [comment]
@wbnns Going to try to take care of this today. :-)

**Comment by wbnns** [comment]
Closing this now that #1584 has been merged. Great work!
