### ISSUE TITLE
Core GUI OSX - Sync blocks very slowly

### ISSUE THREAD

**Issue by loonfilms** [bitcoin-dot-org/bitcoin.org#1563]
Hello, I have had a few different instances of the core software over the years and it normally takes a few days to sync up.. I find this time around it is much much slower. I have on a 100/100 mb/s connection so it should somewhat quick compared to slower connections. Not sure if this is something to do with this version.. I am running v0.14.0 (64-bit).

It has been almost 2 weeks and still only 54% synced up with the network. Anything I can do? Here is a screenshot.

<img width="925" alt="screen shot 2017-04-10 at 6 55 53 pm" src="https://cloud.githubusercontent.com/assets/19350866/24889632/ed04c504-1e1f-11e7-9e78-bb06d1febbf5.png">

Thanks in advance for any tips.

Best

Leo

**Comment by wbnns** [comment]
@loonfilms Hi there! Apologies, we don't provide direct support for Core software, here on the repository. Issues are reserved for things directly related to the Bitcoin.org website. You might have some success raising this issue in one of the following places:

- [Bitcoin Stack Exchange](http://bitcoin.stackexchange.com/)
- [BitcoinTalk Development & Technical Discussion](https://bitcointalk.org/index.php?board=6.0)

I hope this helps. Good luck!

**Comment by loonfilms** [comment]
Thanks for the help!
