### ISSUE TITLE
elipse --> ellipsis

### ISSUE THREAD

**Issue by wlbentley** [bitcoin-dot-org/bitcoin.org#1566]
In the wiki: [Documentation Style Guide](https://github.com/bitcoin-dot-org/bitcoin.org/wiki/Documentation-Style-Guide#code-formatting) under Code Formatting, "bracket-**elipse**-bracket" should read "bracket-**ellipsis**-bracket". An ellipse (with two 'l's) is a curve. Ellipsis is the punctuation mark. 

2 times: One instance in each of the two "**Shortening strings**" paragraphs.

Small tweak.

**Comment by harding** [comment]
@wbnns note the documentation style guide isn't part of the code base so the PR Welcome tag doesn't apply.  It's part of the GitHub wiki and apparently can only be edited by those with commit access to Bitcoin.org. (I didn't realize that when I created it.)

Options:

1. Get rid of it.  I don't think anyone uses it.  I can't even remember what it says; I just happen to follow it (maybe) on account of it's mostly a list of my personal preferences. :-)

2. Move it to the `docs` folder you created so it can be edited by PR.  It's written in Markdown, so it should transfer over cleanly.  (I can do that if you want.)

3. Make the minor change requested here and then hope everybody forgets about it again for another three years.  :-)

**Comment by wbnns** [comment]
@harding You're right, thanks Dave. Fixed as per Option #3, although I hope no one forgets like you mentioned. :) @wlbentley Thanks for mentioning this issue!
