### ISSUE TITLE
Rename Bitcoin Exchanges page to "Buy Bitcoin"?

### ISSUE THREAD

**Issue by Cobra-Bitcoin** [bitcoin-dot-org/bitcoin.org#1573]
Currently if you search for "bitcoin exchanges", our [bitcoin exchanges](https://bitcoin.org/en/exchanges) page shows up second. 

If you search for "buy bitcoin", a much more common search term, our bitcoin exchanges page is nowhere to be found (in fact our competitor bitcoin.**com** is the first result.) I think we should restructure our bitcoin exchanges page to be a better match for the search phrase "buy bitcoin", so we can knock out bitcoin.**com** from the top position.

We can do this by rewriting the URL from https://bitcoin.org/en/exchanges to https://bitcoin.org/en/buy-bitcoin and having the title of the page be "Buy Bitcoin". We can then link to that page with "Buy Bitcoin" as the anchor text throughout the site.

Once we do that, in a few months, we will probably be the top search result for that term. What do you guys think about this?

**Comment by Mirobit** [comment]
Agreed. "buy bitcoin" seems much more popular than "bitcoin exchange(s)"
https://trends.google.com/trends/explore?q=bitcoin%20exchange,buy%20bitcoin

**Comment by wbnns** [comment]
@Cobra-Bitcoin @Mirobit Hey, thanks for bringing this up. The reason I used `Bitcoin Exchanges` first when I set this up instead of `Buy Bitcoin` was because I was thinking that once we had the directory together (the current page), it might be a good opportunity to consider reaching out to one of the International exchanges to see if they want to sponsor a `Buy Bitcoin` page on the site where they would be the featured exchange. In this way, we would have a page that still generates lots of pageviews (the current Exchange page), in addition to a Buy Bitcoin page that would generate even more pageviews, but also revenue. I was thinking it would be it's own navigation link in the top nav ("Buy").

This would help the site support its costs and also allow us apportion money to compensate contributors.

Please let me know what you all think.

**Comment by Mirobit** [comment]
@wbnns That sounds well-thought-out.
While I am personally not to big on advertising on bitcoin.org I agree that cobra and major contributors like you and Craig deserve some compensation for time and costs. If no sponsorship is found advertising seems to be the only way.
But I think the page that will probably bring in the second most visitors (after the main page) should not link to only one exchange. Bitcoin.org should be more neutral and give the user a choice. Also in case of a bankruptcy/scam it could reflect negatively on bitcoin.org.
Depending on the visitor numbers maybe a small area on the exchanges page is attractive enough to bring some money in. 
I agree that we should have a seperate _Buy_ page (for seo reasons). Maybe similar to #1584. Informing users about the general options (exchange, local, atm, instant buy).

@Cobra-Bitcoin How is the current fiancial situation? I read a while ago that the servers were paid till March 2017 by the Bitcoin Foundation.

**Comment by JTuwiner** [comment]
@wbnns @Mirobit I think a page explaining the trade offers between exchanges, local trades, ATMs, credit card, etc would be a good addition! 

I was just at the Tokyo Bitcoin Meetup and these are the most common questions. I also realize MANY people try to invest their bitcoins in ponzi schemes or cloud mining after they buy. I try to explain that there is no easy money in Bitcoin, just like there is no easy money in real life! So I think a warning to avoid these schemes would be good. 

If wanted, I could write up something on the pros and cons of buying using different methods. (privacy, fees, speed, etc.) Let me know if this would help!

**Comment by Mirobit** [comment]
So we have 3 different ideas:

- Rename the page to "Buy Bitcoin"

- Create a "Buy Bitcoin" page that only lists one exchange (sponsor)

- Create a "Buy Bitcoin" page that informs the Users about the general options (local, ATM, exchange), risks and links to the current "Bitcoin Exchanges" page (similar to #1584).

I favour the third option for reasons stated above.

**Comment by JTuwiner** [comment]
@Mirobit Another option is to just rename the current exchange page to have a title like:

_Buy Bitcoin - Global Exchanges_

That knocks out two birds with one stone, and creates one strong page for both keywords on Google.

**Comment by wbnns** [comment]
@Mirobit Agreed, let's do Option #3.

**Comment by wbnns** [comment]
Just a quick update that I have a working branch - `wbnns-buy-bitcoin` - for getting a provisional page up that will allow us to start capturing search engine traffic for the key phrase "buy bitcoin".
