### ISSUE TITLE
https://blockchain.info/de/wallet/

### ISSUE THREAD

**Issue by Golddouble** [bitcoin-dot-org/bitcoin.org#1578]
On "https://bitcoin.org/de/waehlen-sie-ihre-wallet" there is a list with common web-Wallets.

Why is "https://blockchain.info/de/wallet/" not listed here? Is https://blockchain.info/de/wallet/ less common than the others?

(I wanted to compare "https://blockchain.info/de/wallet/" with other web-Wallets.)

**Comment by crwatkins** [comment]
Blockchain.info was removed from the wallet listings in late 2014 in PR https://github.com/bitcoin-dot-org/bitcoin.org/pull/663.  You can review the reasons in that PR, but be aware that information is over two years old and may or may not be still valid.

Wallets can be added to the listings by following the guidelines [here](https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/docs/managing-wallets.md).

**Comment by Golddouble** [comment]
Thank you for this interesting links.
