### ISSUE TITLE
How To Disrupt Everything - A Blockchain Event

### ISSUE THREAD

**Issue by AmandaHendricks** [bitcoin-dot-org/bitcoin.org#1579]
- date: 2017-07-10 & 11
      title: "How To Disrupt Everything - A Blockchain Event"
      venue: "Kromhouthal"
      address: "Gedempt Hamerkanaal 231, 1021 KP"
      city: "Amsterdam"
      country: "Netherlands"
      link: "http://amsterdam.keynote.ae/"

**Comment by wbnns** [comment]
@AmandaHendricks Thanks for submitting this. This is scheduled to be merged Sunday, May 14th (tomorrow).
