### ISSUE TITLE
Oral Arguments (Date change)

### ISSUE THREAD

**Issue by theochino** [bitcoin-dot-org/bitcoin.org#1580]
- date: 2017-06-08
  title: "Oral Arguments on the Status of the Bitlicense in New York"
  venue: "New York State Supreme Court"
  address: "71 Thomas - Room 204 - Part 46"
  city: "New York"
  country: "USA"
  link: "https://www.meetup.com/Article-78-Against-NYDFS/events/238080585"

**Comment by theochino** [comment]
Hello Will, the judge changed the date from 05/04 to 06/08.
I wish they would have done it on the day before consensus. Everyone is welcome.

**Comment by wbnns** [comment]
@theochino Hello, thanks for the update. It looks like the link pointing to the Meetup.com website is incorrect, referencing a Meetup that happened in March. If you could please revise and resubmit we can get this added.
