### ISSUE TITLE
CoinAgenda Europe

### ISSUE THREAD

**Issue by Erikazee** [bitcoin-dot-org/bitcoin.org#1581]
- date: 2017-07-16-18
      title: "CoinAgenda Europe"
      venue: "World Trade Center Barcelona"
      address: "Edif. Este, Moll de Barcelona, s/n
08039"
      city: "Barcelona"
      country: "Spain"
      link: "http://coinagenda.com/#about"

**Comment by Erikazee** [comment]
CoinAgenda Europe is a new conference that combines the historic mission of CoinAgenda and BitAngels to connect and inform investors and entrepreneurs in the bitcoin, blockchain and cryptocurrency sectors with three first-of-a-kind, mini-conferences within the main event

**Comment by wbnns** [comment]
@Erikazee Thanks Erika, this is scheduled to be merged Sunday, May 14th (tomorrow).
