### ISSUE TITLE
Error during parsing of >><<

### ISSUE THREAD

**Issue by vijaya21** [bitcoin-dot-org/bitcoin.org#1582]

**Comment by harding** [comment]
Where does this error occur?

**Comment by wbnns** [comment]
@vijaya21 Please let us know and we'll be happy to revisit this. Currently, there's not enough information to parse this issue.

**Comment by vijaya21** [comment]
I got this error in compiling getbalance.cpp program from minium/bitcoin-api-cpp in github.

**Comment by wbnns** [comment]
@vijaya21 Ok, thanks for clarifying. Apologies, we don't maintain that codebase, but I see their repository, here: https://github.com/minium/bitcoin-api-cpp

Maybe the maintainers can help you if you try opening your issue with them:
https://github.com/minium/bitcoin-api-cpp/issues/new

I hope this helps - good luck!
