### ISSUE TITLE
GSMA- M360, Tanzania

### ISSUE THREAD

**Issue by SarahBritten** [bitcoin-dot-org/bitcoin.org#1587]
- date: 2017/07/11-13
      title: M360 Tanzania (GSMA ran event) 
      venue: 
      address: ""
      city: ""
      country: ""
      link: ""

**Comment by wbnns** [comment]
@SarahBritten Hello, it looks like a lot of information is missing from this event. If you could please provide the additional details required above and resubmit, we can then look to add it to the website.
