### ISSUE TITLE
Blockchain Government Forum

### ISSUE THREAD

**Issue by mymarketinghaus** [bitcoin-dot-org/bitcoin.org#1589]
- date:2017-06-12/13
tle: "Blockchain Government Forum"
      venue: "Innovation Centre"
      address: "9 Bayview Avenue"
      city: "Ottawa"
      country: "Canada"
      link: "https://blockchainforum.ca/"

**Comment by wbnns** [comment]
@mymarketinghaus This is also scheduled to be merged Sunday, May 14th (tomorrow).
