### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by mymarketinghaus** [bitcoin-dot-org/bitcoin.org#1590]
- date:2017-09-12/13
tle: "The Advanced Digital Innovation Summit"
      venue: "McCarthy Tetrault"
      address: "745 Thurlow Street"
      city: "Toronto"
      country: "Canada"
      link: "http://www.adisummit.com/"

**Comment by wbnns** [comment]
@mymarketinghaus Thanks! This is scheduled to be merged Sunday, May 14th (tomorrow).
