### ISSUE TITLE
Moeda física Bitcoin lastro e garantia de recompra

### ISSUE THREAD

**Issue by mercadobitcoinreal** [bitcoin-dot-org/bitcoin.org#1599]
- date: 2017-17-05
      title: Moeda física Bitcoin
      venue: ""
      address: www.mercadobitcoinreal.net
      city: Rio de Janeiro
      country: RJ
      link: www.mercadobitcoinreal.net

**Comment by mercadobitcoinreal** [comment]
Participe do nosso evento Moeda física Bitcoin com lastro e garantia de recompra. www.mercadobitcoinreal.net

**Comment by wbnns** [comment]
@mercadobitcoinreal Olá, desculpas não fomos capazes de obter isto para o site no tempo. No futuro, se pudéssemos ter pelo menos uma semana de antecedência para obter o evento adicionado, que deve ser uma quantidade suficiente de tempo.
