### ISSUE TITLE
Headers message may be empty.

### ISSUE THREAD

**Issue by evoskuil** [bitcoin-dot-org/bitcoin.org#1604]
Source File: _includes/devdoc/ref_p2p_networking.md

This statement implies that empty headers messages are not sent, which is not the case:

> The headers message sends one or more block headers to a node which previously requested certain headers with a getheaders message.

It is typical for peers to send an empty headers message in response when the peers are in sync.

**Comment by wbnns** [comment]
[Bounty](https://github.com/bitcoin-dot-org/bitcoin.org#earn-bitcoin-for-contributing): **5,000 bits / ~$10 USD**

**Comment by evoskuil** [comment]
This issue may apply to the wording of the INV message as well, though I haven't verified the behavior.
