### ISSUE TITLE
New glossary term suggestion: MASF and UASF

### ISSUE THREAD

**Issue by forkwar** [bitcoin-dot-org/bitcoin.org#1605]
For MASF, the synonym Miner Activated Soft Fork might be useful to add.

For UASF, the synonym User Activated Soft Fork might be useful to add.

It may also be worth including links to [BIP8](https://github.com/bitcoin/bips/blob/master/bip-0008.mediawiki) and [BIP9](https://github.com/bitcoin/bips/blob/master/bip-0009.mediawiki).

**Comment by wbnns** [comment]
[Bounty](https://github.com/bitcoin-dot-org/bitcoin.org#earn-bitcoin-for-contributing): **5,000 bits / ~$10 USD**
