### ISSUE TITLE
Consider Including a Warning for Bitcoin's Merkle Tree

### ISSUE THREAD

**Issue by tommagnusson** [bitcoin-dot-org/bitcoin.org#1613]
Location: https://bitcoin.org/en/developer-guide#transaction-data

In the source code for bitcoin's merkle tree implementation there exists a large warning comment explaining a security vulnerability: https://github.com/bitcoin/bitcoin/blob/master/src/consensus/merkle.cpp#L22

Perhaps consider adding a similar warning in the documentation on the website, because it appears to be a naive way of constructing a merkle tree.

**Comment by harding** [comment]
@tommagnusson I think we already have a warning in that section:

![2017-05-31-13_25_07_844885508](https://cloud.githubusercontent.com/assets/61096/26644993/a282cbd6-4604-11e7-92ac-3a761a63642a.png)

I admit, that's a bit wordy and could be improved.
