### ISSUE TITLE
Events page no longer displays Bitcoin meetups

### ISSUE THREAD

**Issue by harding** [bitcoin-dot-org/bitcoin.org#1617]
I was tracing down another issue and I noticed the that Meetup API was failing for us.  It appears that they've changed to requiring an API key.  Here's the URL we currently use:

http://api.meetup.com/2/open_events?omit=description&status=upcoming&radius=25.0&topic=bitcoin&and_text=False&limited_events=False&desc=False&offset=0&format=json&page=500&time=0m%2C3m&sig_id=133622112&sig=cd874bc2c84f96d989f823880889bda2f5e4cdc5

And here's what it says when accessed:

    {"details":"API requests must be key-signed, oauth-signed, or accompanied by a key: https:\/\/www.meetup.com\/meetup_api\/docs\/#authentication","code":"not_authorized","problem":"You are not authorized to make that request"}

Fixing this would be kind of annoying because we wouldn't want to put the access key in the code itself (we'd probably use an environmental variable accessible on the server), but if we don't put the key in the code itself, we can't test with Travis CI or on any random contributor's machine.  Not that testing actually caught this bug whenever it started to fail.

I think the current [events page](https://bitcoin.org/en/events) is just fine without the meetups (and we do have a working link to Bitcoin meetups on the bottom of that page), so I suggest that we just drop that part of the [events plugin](https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/_plugins/events.rb).  (I suspect my other issue is in that part of the code also.)  I'm happy to make and test that change if there's agreement on that being a reasonable path forward.

**Comment by crwatkins** [comment]
ACK

**Comment by wbnns** [comment]
@harding Hey, nice catch! Thanks! Agreed and sounds good to me. 👍
