### ISSUE TITLE
Meetup: Kriptovaluták - befektetés & technológiai innováció egyben

### ISSUE THREAD

**Issue by coinbroker** [bitcoin-dot-org/bitcoin.org#1628]
- date: 2017-06-21
      title: "Kriptovaluták - befektetés & technológiai innováció egyben"
      venue: "https://www.google.com/maps/search/Petőfi+h%C3%ADd,+budai+h%C3%ADdfő,+Budapest,+hu/@47.4777615,19.0593342,17z/data=!3m1!4b1?hl=en"
      address: "Petőfi hír budai hídfő"
      city: "Budapest"
      country: "Hungary"
      link: "https://www.meetup.com/kriptovalutak/"

**Comment by coinbroker** [comment]
Különleges témához különleges helyszín dukál!

A38 Hajó vendégei lehetünk! A színpad mögötti VIP területen a backstage-ben tartjuk első Meetup-unkat. 
Mivel sokak számára ismeretlen területről van szó, így az alapoktól kezdjük körbejárni a kriptovaluták világát. 
Bemutatok pár kereskedési rendszert is, továbbá jó pár oldalt ahonnan információhoz juthatunk.

Meetup sorozatunk további részében lesz szó a bányászatról, sőt egy kis szerencsével élőben is láthatunk majd bányászgépeket.

**Comment by wbnns** [comment]
@coinbroker Üdvözöljük, sajnálja, hogy nem sikerült az eseményt időben hozzáadni a webhelyhez. Remélem jól sikerült.
