### ISSUE TITLE
BoChen Blockchain L0 Global Launch Event

### ISSUE THREAD

**Issue by wavelu** [bitcoin-dot-org/bitcoin.org#1629]
- date: 2017-06-16
      title: "BoChen Blockchain L0 Global Launch Event"
      venue: "Beijing Four Seasons"
      address: "48 Liang Ma Qiao Road Chaoyang District"
      city: "Beijing"
      country: "China"
      link: "http://www.bocheninc.com/index?lang=en-us"

**Comment by wbnns** [comment]
Hello, apologies that we weren't able to get this event added in time. I hope it went well.
