### ISSUE TITLE
Mention IBD

### ISSUE THREAD

**Issue by paveljanik** [bitcoin-dot-org/bitcoin.org#1633]
[Bounty](https://github.com/bitcoin-dot-org/bitcoin.org#earn-bitcoin-for-contributing): **13,500 bits / ~$110 USD**

The page https://bitcoin.org/en/full-node#what-is-a-full-node should mention IBD more extensively (https://github.com/bitcoin-core/bitcoincore.org/issues/349#issuecomment-285590983).

It would be handy to have a FAQ/IBD menu entry on the web so we can redirect people when asking why Bitcoin Core GUI is not doing anything on the first run, why it is consuming 100% CPU and IO at the first run etc.

**Comment by nickthetait** [comment]
Is this page sufficient? https://bitcoin.org/en/developer-guide#initial-block-download
If not, what information is missing? Or does it need to be simplified for someone new to Bitcoin?

**Comment by paveljanik** [comment]
The page is for developers. The description of the first run, high CPU, network traffic and storage is missing. Together with -prune description. For "joe" user.
