### ISSUE TITLE
Incorrect country for BitOasis exchange

### ISSUE THREAD

**Issue by Seccour** [bitcoin-dot-org/bitcoin.org#1636]
Hello,

So the exchange BitOasis is listed on /_templates/exchanges.html as a Saudi exchange while it's an exchange based in the United Arab Emirates which use only AED (The currency from the UAE). Wouldn't it be better to list it as a UAE exchange rather than a Saudi one ? Or directly add all other countries where BitOasis is available in addition to the UAE which are : Saudi Arabia, Kuwait, Bahrain and Oman.

**Comment by wbnns** [comment]
@Seccour Thanks for bringing this to attention. I'll submit a PR changing BitOasis to AED.
