### ISSUE TITLE
P2P Financial Systems International Workshop 2017

### ISSUE THREAD

**Issue by P2PFISY** [bitcoin-dot-org/bitcoin.org#1644]
- date: 2017-07-20/21
      title: "P2P Financial Systems International Workshop 2017"
      venue: "UCL Wilkins building"
      address: "Gower St, Bloomsbury, WC1E 6HJ"
      city: "London"
      country: "United Kingdom"
      link: "https://www.p2pfisy.com/
![p2pfisy_pic](https://user-images.githubusercontent.com/29679219/27510537-1e45fdb2-5913-11e7-8f53-286b3c6e3838.png)
"

**Comment by wbnns** [comment]
@P2PFISY Hello, thanks for submitting this. This looks very similar to #1641, so I'm going to close this to avoid confusion. #1641 will be added to the site, soon. 👍
