### ISSUE TITLE
Add International  bitcoin exchange   to exchanges list

### ISSUE THREAD

**Issue by NickBitsane** [bitcoin-dot-org/bitcoin.org#1645]
Hi Bitcoin community, 

We would like to take this opportunity to introduce our company. We are
Bitsane LP.  Officially registered company in Europe (Republic of Ireland ).  Bitsane provides
an online platform (Bitsane.com)  that allows users to freely trade
between a number of different virtual currencies. 

Your community is a leader in the new world .  It is in this respect that we would like to extend our interest in forming a partnership with your community. We believe that our services can well partner in further promotion of Bitcoin. 

Would like to ask you to put the Bitsane.com international exchange on the list 
https://bitcoin.org/en/exchanges  ?

Bitsane LP
Office 29, Clifton House, 
Fitzwilliam Street Lower Dublin 2, 
Republic of Ireland 

Thank you very much.

**Comment by Mirobit** [comment]
NACK. Many sites that use Advcash turn out to be scams. Also we already have 7 international exchanges listed. We don't want to list every exchange. Only the major ones.
