### ISSUE TITLE
CoinFestUK 2018

### ISSUE THREAD

**Issue by CoinFestUK** [bitcoin-dot-org/bitcoin.org#1655]
- date: 2018-04-05
      title: "CoinFestUK 2018"
      venue: "Manchester Conference Centre"
      address: "Sackville St, Manchester M1 3BB"
      city: "Manchester"
      country: "United Kingdom"
      link: "http://coinfestuk.org/"

**Comment by wbnns** [comment]
@CoinFestUK Hello, could you please resubmit this once it gets a little bit closer and the conference website has been updated with all of the 2018 info?
