### ISSUE TITLE
Translations need to be updated

### ISSUE THREAD

**Issue by wbnns** [bitcoin-dot-org/bitcoin.org#1657]
[Bounty](https://github.com/bitcoin-dot-org/bitcoin.org#earn-bitcoin-for-contributing): **120,000 bits / ~$300 USD**

Here's a high level overview of the process:

1. Use the [Transifex CLI client](https://docs.transifex.com/client/installing-the-client)* to download latest translations (including en.yml) from [Transifex](https://www.transifex.com/bitcoinorg/bitcoinorg/)
2. Diff bitcoin.org's en.yaml against the Transifex yaml to review changes
3. Identify English strings we don't want translators to re-translate from scratch (for example, very minute text changes - if in doubt, just ask)
4. Identify which translations had those strings reviewed (usually translations near 100% reviewed)
5. Manually update en.yml with the English strings we don't want re-translated
6. Review together here
7. Once reviewed, push to Transifex using the Transifex CLI client (this re-uploads en.yml, and all translations
8. Go to Transifex to manually set strings as reviewed that were identified in Step 4
9. Upload the latest en.yml from bitcoin.org manually (any additional changed strings will have to be retranslated)

Basically, we should work to reduce changes sent to Transifex, because translations don't scale well (but are obviously still very important to us because we have so many international users and non English speakers who use the site). Small stuff can escalate into large work, and small errors can turn out to be big. For example, there are currently 70+ languages in our Transifex translation project, so a single erroneous change could cause 70+ translators to do 70+ times the work. That would of course multiply by the number of changes that are made (this example is just assuming one).

TLDR: We don't want translators to have to start over on work they've already done.

*Transifex CLI commands can be found here: https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/docs/assisting-with-translations.md#update-english-strings

**Comment by NimaDgr** [comment]
Is there any chance you want to add Persian translation? I can do that.

**Comment by Pajulapoiss** [comment]
I could translate to Estonian.

**Comment by skae1l** [comment]
I can translate everything into German,.

**Comment by FajarHima** [comment]
I could translate to Indonesian

**Comment by ceanes** [comment]
I could translate to Portuguese

2017-07-07 8:35 GMT-03:00 FajarHima <notifications@github.com>:

**Comment by soyvzk** [comment]
I'm a professional english-spanish translator and I'd be glad to help with this project!

**Comment by 23kb** [comment]
I can translate to Urdu

**Comment by Bluewan** [comment]
I would like to translate to Turkish or German.

**Comment by mcccs** [comment]
> *Transifex CLI commands can be found here: https://github.com/bitcoin-dot-org/bitcoin.org#update-english-strings

This link is broken?

**Comment by wbnns** [comment]
@NimaDgr @Pajulapoiss @skae1l @ceanes @soyvzk @23kb @Bluewan Thank you all for the offers. This particular bounty is focused on updating the existing translations that volunteer translators have already made on Transifex as outlined in the process above.

If you're interested in joining one of the translation teams, though, you can do so, here - it would be great to have additional translation contributors: https://www.transifex.com/bitcoinorg/bitcoinorg/.

@mcccs Nice catch! Thanks for mentioning. I've [updated the link]( https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/docs/assisting-with-translations.md#update-english-strings) above. 👍

**Comment by fjdhgjaf** [comment]
Hello, I could translate to Hungarian.

**Comment by azeyrx** [comment]
I could translate to Polish and German

**Comment by boscoarinze** [comment]
i could translate to Igbo

**Comment by boscoarinze** [comment]
please i could translate to Igbo,one official local language in Nigeria

**Comment by mitchellcash** [comment]
@wbnns I can't seem to pull translations from Transifex. Do I have to be part of the team on Transifex to do so?

```
tx pull -a -s --skip

New translations found for the following languages:el, gu, ach, af, vi, ca, it, cs, cy, ar, ml, mk, eo, eu, et, gl, id, es, ru, nl, no, tr, si, ady, lv, lt, pa, sw, ro, pt_PT, pl, ta, be, fr, bg, ms, pt_BR, ast, hr, bn, zh_TW, da, fa, hi, bs, fi, hy, hu, fil, ja, is, he, ka, mr, uz, sr, sq, mn, ko, sv, km, ur, sk, ky, de, zh_CN, sn, uk, sl, ku, pl_PL, my, or
Pulling new translations for resource bitcoinorg.bitcoinorg (source: None)
 -> el: translations/bitcoinorg.bitcoinorg/el.yml
Exception
```

**Traceback**

```
tx --traceback pull -a -s --skip

New translations found for the following languages:el, gu, ach, af, vi, ca, it, cs, cy, ar, ml, mk, eo, eu, et, gl, id, es, ru, nl, no, tr, si, ady, lv, lt, pa, sw, ro, pt_PT, pl, ta, be, fr, bg, ms, pt_BR, ast, hr, bn, zh_TW, da, fa, hi, bs, fi, hy, hu, fil, ja, is, he, ka, mr, uz, sr, sq, mn, ko, sv, km, ur, sk, ky, de, zh_CN, sn, uk, sl, ku, pl_PL, my, or
Pulling new translations for resource bitcoinorg.bitcoinorg (source: None)
 -> el: translations/bitcoinorg.bitcoinorg/el.yml
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/txclib/cmdline.py", line 105, in main
    utils.exec_command(cmd, args[1:], path_to_tx)
  File "/usr/local/lib/python2.7/site-packages/txclib/utils.py", line 246, in exec_command
    cmd_fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/txclib/commands.py", line 383, in cmd_pull
    mode=options.mode, pseudo=pseudo, xliff=xliff
  File "/usr/local/lib/python2.7/site-packages/txclib/project.py", line 640, in pull
    params=params
  File "/usr/local/lib/python2.7/site-packages/txclib/project.py", line 954, in do_url_request
    skip_decode=skip_decode
  File "/usr/local/lib/python2.7/site-packages/txclib/utils.py", line 177, in make_request
    raise Exception(data)
Exception
```

**Comment by kuzzmi** [comment]
Here is the diff between the one from Github (on the left) and from Transifex (on the right):

https://www.diffchecker.com/gIYuArWK

Here is a list of keys, where the changes are either minor, or stylistical, or that just haven't been changed enough to be retranslated:

```
about-us:
    helptxt - minor updates

bitcoin-for-businesses:
    lowfee - minor updates

bitcoin-for-developers:
    owntext - minor updates
    anonymoustext - minor updates

bitcoin-for-individuals:
    lowfee - minor updates

community:
    walletmyceliumwallet - minor updates
    wallettrezor - minor updates
    checkgoodvalidationfullnodetxt - minor updates
    checkgoodvalidationfullnoderequiredtxt - minor updates
    checkfailenvironmentdesktoptxt - minor updates

development:
    morechoose - links updates
    notesync - minor updates with templates

faq:
    usedtxt1 - links updates
    acquireli2 - links updates
    advantagesli1 - formatting updates
    tenminutes - minor updates with templates
    tenminutestxt1 - minor updates with templates

getting-started:
    spendbut - minor update

index:
    list1 - lowering expectation updates
    list3 - lowering expectation updates

legal:
    informationtxt1 - links updates
    translationstxt1 - links updates

press:
    volunteernonprofit - links updates

privacy:
    title - minor updates
    pagetitle - minor updates

protect-your-privacy:
    traceabletxt - minor updates

support-bitcoin:
    miningtxt - minor updates and links updates
    donationtxt - links updates
    nonprofittxt - minor updates and links updates
    spreadtxt  - minor updates and links updates
    wikitxt - links updates

layout:
    menu-privacy - minor updates
```

**Comment by kuzzmi** [comment]
Another question here. Does it make sense to automate this process? I mean Transifex configuration can be included in the repo, for instance, and a few bash scripts could be written to make these diffs creation, so after resolving this issue, it won't take much time to have up-to-date translations.

Also, as a suggestion, why do we really need to maintain two versions of the translations? Why can't we just pull the translations from Transifex during the build/preview stage? This would simplify things a lot.

**Comment by mitchellcash** [comment]
@kuzzmi my thoughts exactly. I ended up just joining the Arabic Translation Team on Transifex and went through the same process as you.

My thoughts are:
1. Add .tx/config to repo

```
[main]
host = https://www.transifex.com

[bitcoinorg.bitcoinorg]
file_filter = _translations/<lang>.yml
source_file = _translations/en.yml
source_lang = en
```

2. Set up Transifex to auto update the English resource using this URL `https://raw.githubusercontent.com/bitcoin-dot-org/bitcoin.org/master/_translations/en.yml`:

<img width="690" alt="auto update resources" src="https://user-images.githubusercontent.com/8009243/28389818-01f73812-6d1b-11e7-80ae-9d61a1826f08.png">

3. As part of the `make deployment` process your could automate the `tx pull -a -s --skip` step

**Considerations**
* All English string updates happen on GitHub, otherwise they will be overridden
* This does mean that you can't selectively choose which strings had minor changes and skip translating them again (without going through a lot of effort)

Overall I think this is the best way to handle translations, but @wbnns what do you think?

Some of the steps outlined above need to be actioned by an Admin on Transifex so let me know if you need a hand.

**Comment by kuzzmi** [comment]
@mitchellcash after giving it some thought, I guess this is a bit too aggressive approach as this will eliminate the convenience of cherry-picking strings, as @wbnns mentioned in the issue description.

Another suggestion:
What we can do though is to use what is already presented here in `_translations` directory as a base and have a tool/script that will generate diffs automatically. In this case it will be much easier to grasp when and what needs to be pulled to Transifex for a full translation and what can be cherry-picked. The process will be semi-automated, so in the end the flexibility is preserved and all routine tasks are automated.

Overall this falls out of this issue discussion and it's probably better to handle it in a separate ticket.

**Comment by wbnns** [comment]
@mitchellcash Thanks for the feedback!

@kuzzmi 

> What we can do though is to use what is already presented here in _translations directory as a base and have a tool/script that will generate diffs automatically. In this case it will be much easier to grasp when and what needs to be pulled to Transifex for a full translation and what can be cherry-picked. The process will be semi-automated, so in the end the flexibility is preserved and all routine tasks are automated.

This sounds great and could be a significant improvement over the current workflow.

Regarding the diffs, as per our conversation on Telegram, the following will need to be retranslated:
```
+ 19c22
+ 29,30c36,46
+ 52c73,79
+ 71,72c119,128
+ 143a207
+ 159c223
+ 161c225
+ 251c326
+ 280c362
+ 283c365
+ 290,291c372,391
+ 362,363c462,481
+ 416c555
+ 448c587
+ 450c589
+ 485c634
+ 487c636
+ 514c663
+ 529c695
+ 608c782
+ 612c786
+ 614c788
+ 616c790
+ 618c792
```
If you have any questions, please let me know.

**Comment by kuzzmi** [comment]
Here is a list of changes that I'm about to force-push to Transifex:

```diff
74c74
< anonymoustext: "With Bitcoin, there is no credit card number that some malicious actor can collect in order to impersonate you. In fact, it is even possible to send a payment without revealing your identity, almost like with physical money. You should however take note that some effort can be required to <a href="#protect-your-privacy#">protect your privacy</a>."
---
> anonymoustext: "With Bitcoin, there is no credit card number that some malicious actor can collect in order to impersonate you. In fact, it is even possible to send a payment without revealing your identity, almost just like with physical money. You should however take note that some effort can be required to <a href="#protect-your-privacy#">protect your privacy</a>."
126c126
< walletmyceliumwallet: "Mycelium Bitcoin Wallet for Android is designed for security, speed, and ease of use. It has unique features to manage your keys and for cold storage and offers compatibility with Trezor and others."
---
> walletmyceliumwallet: "Mycelium Bitcoin Wallet for Android is designed for security, speed, and ease of use. It has unique features to manage your keys and for cold storage and offers compatibilty with Trezor and others."
133c133
< wallettrezor: "Trezor is a hardware wallet providing a high level of security without sacrificing convenience. Unlike cold storage, Trezor is able to sign transactions while connected to an online device. That means spending bitcoins is secure even when using a compromised computer."
---
> wallettrezor: "TREZOR is a hardware wallet providing a high level of security without sacrificing convenience. Unlike cold storage, TREZOR is able to sign transactions while connected to an online device. That means spending bitcoins is secure even when using a compromised computer."
193c193
< checkfailenvironmentdesktoptxt: "This wallet can be loaded on computers which are vulnerable to malware. Securing your computer, using a strong passphrase, moving most of your funds to cold storage, or enabling two-factor authentication can make it harder to steal your bitcoins."
---
> checkfailenvironmentdesktoptxt: "This wallet can be loaded on computers which are vulnerable to malware. Securing your computer, using a strong passphrase, moving most of your funds to cold storage or enabling two-factor authentication can make it harder to steal on your bitcoins."
231c231
< morechoose: "You can choose a project to contribute to by answering a few <a href="http://whatcanidoforbitcoin.xyz/">questions about your skills</a>."
---
> morechoose: "You can choose a project to contribute to by answering a few <a href="http://whatcanidoforbitcoin.org/">questions about your skills</a>."
518,519c518,519
< title: "Privacy Policy - Bitcoin"
< pagetitle: "Privacy Policy"
---
> title: "Privacy - Bitcoin"
> pagetitle: "Privacy"
692c692
< menu-privacy: "Privacy Policy"
---
> menu-privacy: "Privacy"
```

**Comment by crwatkins** [comment]
I believe that the above reintroduces a spelling error in the `walletmyceliumwallet` line for "compatibility".

**Comment by kuzzmi** [comment]
My bad, I misplaced the files for diffing. Updated the diff in my previous comment.

**Comment by wbnns** [comment]
@kuzzmi Thanks! Looks good to me - please do it when you're ready.

**Comment by kuzzmi** [comment]
I think this issue can be considered as resolved.

I've done the following:

- [x] Identify English strings we don't want translators to re-translate
- [x] Identify which translations have those strings reviewed
- [x] Manually update en.yml with the English strings we don't want re-translated
- [x] Push changes to Transifex
- [x] Manually set strings as reviewed that were identified before
- [x] Upload the latest en.yml from github.com/bitcoin-dot-org/bitcoin.org manually

If nobody has any concerns, this address can be used for the bounty payout:
14kafbQ3WBmvMhAA3y6gwohUuYQ4zLZrLq

**Comment by wbnns** [comment]
Unless others object, this will be closed on Sunday, July 30th.

**Comment by mitchellcash** [comment]
Nice work @kuzzmi

**Comment by wbnns** [comment]
@kuzzmi Great work. Here's the [transaction confirmation](https://live.blockcypher.com/btc/tx/a376f60f77ba2c76945bc8194b03502b8117d248a8d4800901881c65002a0a81/) for the bounty.
