### ISSUE TITLE
Need to update instructions for Running a Full Node for Windows 10

### ISSUE THREAD

**Issue by wbnns** [bitcoin-dot-org/bitcoin.org#1659]
[Bounty](https://github.com/bitcoin-dot-org/bitcoin.org#earn-bitcoin-for-contributing): **30,000 bits / ~$75 USD**

Windows 10 has been out for a while and instructions for how to run a full node on it need to be added to the [Running a Full Node](https://bitcoin.org/en/full-node#windows-instructions). The instructions for the other versions of Windows are a good template to follow to get started.

![image](https://user-images.githubusercontent.com/1130872/27772444-19486c92-5f20-11e7-961d-134a8da33b22.png)

**Comment by camendt** [comment]
i can create win10 instructions

**Comment by mcccs** [comment]
@camendt Someone already did #1666
