### ISSUE TITLE
Removal of BTC.com wallet?

### ISSUE THREAD

**Issue by Mirobit** [bitcoin-dot-org/bitcoin.org#1660]
BTC.com was one of the _The Future of Bitcoin Conference 2017_ [sponsors](https://www.thefutureofbitcoin.com/#sponsors).  At the conference well known fraudster and patent troll Craig Wright [attacked](https://www.youtube.com/watch?v=v1_gxvx_QGo) bitcoin users and core devs.

While I don't have a problem with supporting a conference that gives different opinions (e.g BU) a platform, I draw the line when they give a dangerous egomaniac a platform for his FUD and hate.

While this is not against the bitcoin.org wallet inclusion rules, it shows at best poor judgement and at worst the desire to harm bitcoin.

Maybe I am totally out of line here but I would like to hear from BTC.com (@bitkevin) if they knew that Craig was one of the speakers and if they support his views on Bitcoin.

**Comment by Cobra-Bitcoin** [comment]
They're associated with that monster Jihan Wu, so I don't mind if they get removed because of this, they're terrible people. I definitely feel like a line has been crossed here.

**Comment by bitkevin** [comment]
It's a shame that have Craig Wright on the stage.

**Comment by crwatkins** [comment]
I would like to comment on the process and procedure here.  I agree with @Mirobit that I do not believe that sponsoring a conference, regardless of the subject matter is against our wallet criteria.  I fully believe that if we think that such actions  (or lack there of) are valid criteria, we should work to express those criteria.

**Comment by AlejandroDeLaTorre** [comment]
BTC.com was not aware that Craig Wright would be on stage. John Matonis was scheduled to speak and surprised us, and everyone else when he gave the stage to Craig Wright.

**Comment by jlopp** [comment]
All I see here is a "guilt by association" witch hunt. Proposals to remove a wallet's listing should be based upon technical reasoning, not ad hominems.

**Comment by FrancisPouliot** [comment]
This has nothing to do with wallet recommendations. I suggest this thread be closed. This is no reason this should be under review. 

The sponsors were clearly not aware CW would be there, and even if they were or had even personally invited him on stage it wouldn't make a difference.

Wallets are to be recommended on their technical merits, and should only be delisted if they can be demonstrated to harm or put users at risk.

**Comment by Mirobit** [comment]
@jlopp @FrancisPouliot Judging a wallet only on its technical merits can be short-sighted. An malicious developer can push an update to the app store at any time to steal the users funds or harm the network or bitcoin's image. So I think the trustworthiness of the developer should also be a criteria. No one would recommend a wallet developed by Bernard Madoff even if it would be technically fine. 
This is an extreme example and _BTC.com_ hasn't shown any signs of being an malicious developer. But I think it should be at least discussion if the trustworthiness/'moral character' of the developer should be considered for wallet inclusion. Currently the only requirement is that the identity of the devs/CEO is known.

Anyway I am closing the issue since I agree with @crwatkins and the r/btc crowd is rolling in.

**Comment by jli225** [comment]
No wonder so many people see the the administrators of the bitcoin.org website as "notorious, unashamed, effrontery".

**Comment by jonasschnelli** [comment]
Please use scientific/technical-measurements to list/de-list wallets. Otherwise this gets a big mess and we will have endless discussions.

**Comment by jli225** [comment]
@jonasschnelli I don't think the administrators of bitcoin.org have any intention to judge with scientific/technical-measurements. Actually, you asked them for too much.

As many people said, they are stupid yet arrogant. They are only fortunate for being accidentally in charge of this famous site. They did not "earn" this position gradually so it's not surprising that they are lack of some basic requirement for managing an important website. Actually, they see bitcoin.org as their private property, and practically bitcoin.org becomes a personal website nowaday.

**Comment by jonasschnelli** [comment]
Domains are owned by individuals or cooperations. Not sure if I like this, but it's how it is. Would it be better if the site is owned by the Bitcoin Foundation? Or via GitHub and changed get merged based on reddit votes... I smell a clear "No!" here.

Bitcoin.org did a good job so far, not perfect but much better then any other so-called "official" bitcoin sites.
@jli225: feel free to try better.

**Comment by jli225** [comment]
@jonasschnelli
absolute power corrupts absolutely. Its corruption is inevitable.
This is the root cause of the horrible corruption happened in Reddit/Bitcoin, Github/Bitcoin and so many places.

That's why Satoshi passed the torch to Gavin, that's why Gavin passed the torch to Vladimir

And that's why Vladimir refused to pass the torch or return to Gavin.

That's why such horrible censorship can last for years on an expected censorship-resistant internet of money.

**Comment by FrancisPouliot** [comment]
Stop trolling. This is an open-source educational project by volunteers.

Regarding Coinbase, look at past discussion or open a relevant issue for review. AFAIK they specifically asked the community to remove them from educational material that considers them a "wallet" with this blog post: https://blog.coinbase.com/coinbase-is-not-a-wallet-b5b9293ca0e7

I understand you want to leave your opinions for the world to see, but this is nothing short of digital graffiti and I would ask you refrain from using this repo as your soapbox.

**Comment by molecular** [comment]
Shouldn't listing of wallet software be based purely on the properties of that wallet? Why would you even look at properties of the producer of the wallet?

The proposed action gives the impression of punishing the producer of the wallet for something that has nothing whatsoever to do with the wallet itself.

**Comment by Mirobit** [comment]
@molecular Not looking at the properties of the producer would be reckless. Bitcoin.org is a place where newcomers look for information. Many of them simply rely on the fact that a wallet is listed on Bitcoin.org and don't do further research on the developer. So we need to make sure that the developer is at least somewhat trustworthy and doesn't have a history of scam/fraud.

The current rules would not prevent Mark Kaperkles or Bernard Madoff from adding their wallets to Bitcoin.org if they are technically fine. 

This is not about BTC.com anymore.

The are currently no such wallets listed or under consideration but we need to think long-term. We should not have this discussion when the first scammer tries to add his wallet. Better be prepared.

**Comment by seandotau** [comment]
As a newbie, bitcoin.org is a definitely a starting place when looking for information. 

Judging a wallet based on technical merits is a given. Judging the developer/author of the wallet should be left to the individual but information about the developer/author is important and should be presented in a non-biased manner. This is similar to company register holding information about directors. 

It's not about "punishing the producer of the wallet" but making information available so individuals can make their own decisions.

**Comment by FrancisPouliot** [comment]
There shouldn't be any liability for contributors of this project.

Recommendations based on objective, verifiable, peer-reviewed analysys.

I'm unfollowing this thread.
