### ISSUE TITLE
Removal of "Bitcoin Core" wallet? 

### ISSUE THREAD

**Issue by jli225** [bitcoin-dot-org/bitcoin.org#1662]
[The new Bitcoin reference version supported by Bitcoin community majority](https://github.com/btc1/bitcoin/issues)   https://github.com/btc1/bitcoin/issues
----
As administrator "Cobra-Bitcoin“ and "Mirobit" said,

> Judging a wallet only on its technical merits can be short-sighted. A malicious developer can push an update to the app store at any time to steal the users funds or harm the network or bitcoin's image. 

No longer "purely technical"? Suddenly "political" is better when it fits their narrative? Suddenly "technical" becomes short-sighted?

According to such standard, they shall remove "Bitcoin Core" from their site.

Anyway, bitcoin.org is a personal website, although they pretend to be "official" site. So double standard and propaganda are expected.

I am sure they won't remove "Bitcoin Core" from their site even though it's visibly malicious, because  administrator "Mirobit" spat that words only in order to try to slander btc.com by implying it's malicious.

Behold, they still spam the lies and propaganda such as ASICBoost, even though only brainwashed idiots believe it.

**Comment by keeking** [comment]
Concept ACK

**Comment by Mirobit** [comment]
Wow, basically every sentence is factually wrong or twists my words..

> As administrator "Cobra-Bitcoin“ and "Mirobit" said,
I am a normal user and don't have any admin permissions.

> No longer "purely technical", suddenly "political" is better when it fits their narrative? Suddenly "technical" becomes short-sighted?
I said **only** looking on the tech is short-sighted.

> I am sure they won't remove "Bitcoin Core" from that site even though it's visibly malicious, because administrator "Mirobit" spat that words only in order to try to slander btc.com by implying it's malicious.
I clearly state that BTC.com is not an malicious actor. I was concerned about their connection to CSW. BTC.com stated that there is no connection. This solved the issue with BTC.com for me.
That the wallet requirements should be updated is an issue unrelated to BTC.com.

**Comment by kek-coin** [comment]
Just to point out for anyone stumbling across this madness in the future; @jli225 responded with :+1:, 😄 and ❤️ to his own post.

**Comment by RawlzSec** [comment]
Oh god. Looks like r/btc learned how to use github.

**Comment by jli225** [comment]
The administrators closed this issue without any explanation. That's how they deal with issues they dislike. This github is only for appearances.

As @benjyz said,

> the statement on bitcoin-org is meaningless ...... It creates impression of consensus, when in reality that might not be the case.
