### ISSUE TITLE
Mycelium has an iOS version now

### ISSUE THREAD

**Issue by harding** [bitcoin-dot-org/bitcoin.org#1664]
I'm not sure, but I believe they were Android only when we first listed them, however they now seem to have an iOS version:

- https://wallet.mycelium.com/contact.html (I know the URL says "contact" but it's also their download page)
- https://itunes.apple.com/en/app/mycelium-bitcoin-wallet/id943912290

Unless the Mycelium developers are against it, I suggest the iOS version be reviewed and considered for inclusion under Bitcoin.org's usual criteria.

**Comment by wbnns** [comment]
@harding Nice catch, thanks for mentioning this.

**Comment by harding** [comment]
Whoops, I meant to mention that it was reported by a user on Twitter today; all thanks go to them: https://twitter.com/BTC4USD/status/882333498790563840

**Comment by crwatkins** [comment]
The codebase and the IU is totally different from the Android version. If the developer (or any interested party) believes that the iOS wallet meets our listing criteria, and they are interested in having it listed, they should submit a PR with screenshots and proposed scoring.

**Comment by harding** [comment]
@crwatkins that sounds quite reasonable.  Thank you for investigating.
