### ISSUE TITLE
2017-07-12-potential-split typos

### ISSUE THREAD

**Issue by mmortal03** [bitcoin-dot-org/bitcoin.org#1684]
@harding  A couple of grammatical mistakes in the "Potential network disruption" announcement:

"in the later case, you will need to take extra steps in order to begin safely receiving bitcoins again."

the *latter* case

"If they accept transactions during the event, they could lose money and will likely spread those loses across all their users. "

spread those *losses*

**Comment by harding** [comment]
@mmortal03 thank you for notifying us about those; they're currently scheduled to be fixed in the next update.
