### ISSUE TITLE
Potential Warning For Slow Transaction Confirmation and Fee Spikes as we approach Aug 1.

### ISSUE THREAD

**Issue by krispii** [bitcoin-dot-org/bitcoin.org#1689]
Source File: _alerts/2017-07-12-potential-split.md

It may benefit users to be warned to move their bitcoin in advance of the 12-24 hour deadline as there may also be a surge in transactions, possible network spam and fee spikes. If bitcoin can be moved earlier it may benefit some users to do so. 

Just thought it might be worth mentioning. Great work on the post.

**Comment by wbnns** [comment]
@krispii Thanks for thinking to mention this. Closing since the alert has ended.
