### ISSUE TITLE
Incremental redesign and accessibility improvements

### ISSUE THREAD

**Issue by kuzzmi** [bitcoin-dot-org/bitcoin.org#1693]
Despite the fact that Bitcoin is the future, the website design is currently seems to be outdated.

I've seen #1078, but it didn't make it to the master branch, so I though it makes sense to do this incrementally.

To achieve this, in my opinion, the following steps are needed:
- [ ] current css and scss files must be refactored to provide more maintainable styling
- [ ] icons and illustration must be redrawn in order to match the current trend
- [ ] store only svg images (when applicable) in the repository and generating required png's during the build to enforce easier changes in the future
- [ ] include browser rendering via external service to make sure the website looks as expected on different devices
- [ ] ensure website is accessible to people with disabilities.
[Current report](http://wave.webaim.org/report#/https://bitcoin.org/en/)
- [ ] enhance website responsiveness

All the steps can be done via separate ticket and pull requests, and this will also allow to mark important things with bounty label.

I've drafted icons in the following style, for example, in addition to lifting up the Bitcoin.org orange color is used to make them look more related:

![image](https://user-images.githubusercontent.com/1727140/28343315-0414e116-6c1d-11e7-962f-e6c554291c5a.png)

I'm keen to hear your thought on this.

**Comment by wbnns** [comment]
@kuzzmi Thanks for raising these points. Agreed, there is definitely room for improvement in several places. If you're interested in pursuing this type of work, I would recommend breaking these down into as many minute issues as possible first (before any PRs) so that we can minimize subjectivity and discuss/work through them together in a granular fashion.

**Comment by wbnns** [comment]
Let's consider the following as QA items in conjunction with the [ongoing redesign](https://github.com/bitcoin-dot-org/bitcoin.org/projects/1):

<img width="669" alt="image" src="https://user-images.githubusercontent.com/1130872/38501088-6493b96e-3bc9-11e8-98e7-12633614d516.png">
