### ISSUE TITLE
The Bitcoin, Ethereum, And Blockchain Super Conference

### ISSUE THREAD

**Issue by mmi2good** [bitcoin-dot-org/bitcoin.org#1694]
- date: 2018-02-16-18
      title: The Bitcoin, Ethereum, And Blockchain Super Conference
      venue: Dallas/Fort Worth
      address: Dallas/Fort Worth Airport Marriott 8440 Freeport Pkwy Irving, TX 75063
      city: Dallas/Fort Worth
      country: United States
      link: https://www.bitcoinsuperconference.com/

**Comment by duynam1992** [comment]
- date: 2018-02-16-18
  title: The Bitcoin, Ethereum, And Blockchain Super Conference
  venue: Dallas/Fort Worth
  address: Dallas/Fort Worth Airport Marriott 8440 Freeport Pkwy Irving, TX 75063
  city: Dallas/Fort Worth
  country: United States

**Comment by mmi2good** [comment]
Can I assign this to someone? I'd like this to be labeled as Event.
