### ISSUE TITLE
Gibraltar International FinTech Conference 2017

### ISSUE THREAD

**Issue by gibfin1** [bitcoin-dot-org/bitcoin.org#1701]
18th - 19th October 2017
      Gibraltar International FinTech Conference 2017
      Sunborn Yacht Hotel, Gibraltar
      Ocean Village, Gibraltar
      www.gibfin.com
      Email: Marketing@gibfin.com

**Comment by wbnns** [comment]
@gibfin1 Hello, I couldn't find a specific agenda or any speaker info on the website, and the [Twitter account](https://twitter.com/gibfin) that the website links to has no information about the event - it's just tweeting "make money online" spam.

**Comment by gibfin1** [comment]
Hi Will,

Apologies as our twitter has now been updated to @gibfin2017 and our list of speakers will be announced shortly. This had gone into my spam hence the delayed response


Kind regards


Nick Hughes

Gibraltar IFC
1st Floor, World Trade Center
Bayside Road, Gibraltar GX11 1AA
Tel: +350 2000 8041
Mob: +350 5405 9200
Email: marketing@gibfin.com
www.gibfin.com


________________________________
