### ISSUE TITLE
Blockchain Solution Forum

### ISSUE THREAD

**Issue by nils617** [bitcoin-dot-org/bitcoin.org#1703]
- date: 2017-10-03
      title: "Blockchain Solutions Forum"
      venue: "Fira Barcelona Grand Via"
      address: "Av. Joan Carles I, 64"
      city: "Barcelona"
      country: "Spain"
      link: "http://www.blockchainsolutionsforum.com"

**Comment by wbnns** [comment]
@nils617 This event has a similar issue - there is no program/agenda and there is only booth/exhibit space available for sale. Please resubmit once there is more information available about the event.
