### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by nils617** [bitcoin-dot-org/bitcoin.org#1704]
-date: 2017-10-03
      title: "Crypto-Economy & ICO 2017"
      venue: "Fira Barcelona Grand Via"
      address: "Av. Joan Carles I, 64"
      city: "Barcelona"
      country: "Spain"
      link: "http://www.theCryptoEconomy.com"

**Comment by wbnns** [comment]
@nils617 Hi, thanks for submitting this. On the website, it looks like there aren't yet any speific speakers or startups mentioned for the event in the program and I only saw booth/exhibit space for sale. Could you please resubmit once this data is available?
