### ISSUE TITLE
BitCoin is sent to space with your photo :)

### ISSUE THREAD

**Issue by xGooDx** [bitcoin-dot-org/bitcoin.org#1710]
- date: 2017-11-01
      title: "BitCoin is sent to space with your photo :)"
      venue: "UKRAINE KIEV"
      address: "UL. SHELKOVICHNAJA 11 "
      city: "Kiev"
      country: "UKRAINE"
      link: "l2rx.com"

**Comment by xGooDx** [comment]
Company "Life 2 Relax Project" After 3 months BitCoin will be sent to space with your photo. Wonderfully came up with: http://l2rx.com

;)

**Comment by wbnns** [comment]
@xGooDx Hi, thanks for submitting this. It looks like the venue is missing and there are also some broken links on the website that the event links to. Could you please resubmit this once both issues have been resolved?
