### ISSUE TITLE
Blockchain & Cryptocurrency Con 2018

### ISSUE THREAD

**Issue by finid** [bitcoin-dot-org/bitcoin.org#1717]
- date: 2018-02-23
      title: "Blockchain & Cryptocurrency Con 2018"
      venue: "TBD"
      address: "TBD"
      city: "Dallas"
      country: "USA"
      link: "https://blockchain-conf.com"

**Comment by wbnns** [comment]
@finid Hi there! Could you please resubmit this once you have a venue and address?

**Comment by finid** [comment]
@wbnns venue and address has been added.
