### ISSUE TITLE
Improve grammar in English translation

### ISSUE THREAD

**Issue by gene1wood** [bitcoin-dot-org/bitcoin.org#1721]
@wbnns Suggested a few changes in #1630 which have been implemented. Please re-open the PR to see the [changes](https://github.com/gene1wood/bitcoin.org/commit/01d243c64c3f94e3d37eeb503515ed023b393ada) and let me know anything else that needs to be done.

**Comment by wbnns** [comment]
@gene1wood Hello, thanks. I reopened your PR - it looks like there may still be some merge conflicts when you have time to take a look.

**Comment by gene1wood** [comment]
@wbnns No prob, merge conflicts resolved.
