### ISSUE TITLE
Enable translations for the developer documentation

### ISSUE THREAD

**Issue by wbnns** [bitcoin-dot-org/bitcoin.org#1723]
[Bounty](https://github.com/bitcoin-dot-org/bitcoin.org#earn-bitcoin-for-contributing): **400,000 bits / ~$3200 USD**

The developer documentation is an awesome part of Bitcoin.org, however, unlike many of the other pages, it's only available in English. So far in 2017, over six million website visits have originated from places where people do not speak English as their first language.

It's important that we provide a way to help a potential new generation of Bitcoin developers in non English-speaking countries learn more about Bitcoin on a technical level, to help foster the development of new products and services, all around the world, built on top of the tech.

The developer documentation needs to be refactored so that it can be exported and translated by our team on [Transifex](https://www.transifex.com/bitcoinorg/bitcoinorg/), to be rendered just like the other translated web pages on the site.

**Comment by kuzzmi** [comment]
I've started working on this and here's a brief status update from me:

![image](https://user-images.githubusercontent.com/1727140/28990436-be58c43a-797d-11e7-92eb-8052e55c8560.png)

**Comment by wbnns** [comment]
@kuzzmi This is great - awesome job. 👍 👍

**Comment by wbnns** [comment]
The bounty has been increased on this issue.

**Comment by Mirobit** [comment]
@kuzzmi Does your work affect the files in ´\_includes\devdoc\bitcoin-core´ folder? Because I don't want the 0.15 API update  to interfere with your refactoring.

**Comment by kuzzmi** [comment]
@Mirobit, yes, it includes the whole `_includes\devdoc` folder, but feel free to make needed updates, I'll have to make quite a big merge after I'm done, so this shouldn't result in a big overhead.

**Comment by kuzzmi** [comment]
Current state is as on the screenshot:

![image](https://user-images.githubusercontent.com/1727140/32365778-f2281b56-c083-11e7-9010-e00715e917e2.png)

I added some Ukrainian translation strings to ensure that all works as expected. There will be a few changes to the instructions regarding how to contribute to translation.

**Comment by wbnns** [comment]
@kuzzmi Thanks for the update, looking forward to getting this up on the site!

**Comment by kuzzmi** [comment]
![image](https://user-images.githubusercontent.com/1727140/32721862-9684584c-c870-11e7-9623-eb5f03df5bdf.png)

I added a warning and enabled translation of a few other tiny things.

Current text is:
> BETA: This version of the documentation may contain English (original) parts, if you wish to contribute to translating this document to your language, please use the appropriate links under the headings, or visit [this link](#)

The link in the disclaimer will point to the instructions.

**Comment by wbnns** [comment]
@kuzzmi That disclaimer looks wonderful, and is a great call to action for inviting people to help contribute - thanks a bunch.
