### ISSUE TITLE
Deactivate network warning

### ISSUE THREAD

**Issue by Mirobit** [bitcoin-dot-org/bitcoin.org#1726]
I think it is time to deactivate the network warning:

- BIP91, BIP148 and BCash deadlines haven been passed without any unexpected events.
- Only people using BCash clients need to worry about possible blockchain reorgs and this is not the responsibility of Bitcoin.org
  - Thanks to the BCash replay protection and different difficulty rules, Bitcoin SPV users don't need to worry about receiving BCash transactions and confirmation uncertainty.

We could link to the [Claim your BCash guide](https://github.com/yellowblood/sell-bcash).

**Comment by Cobra-Bitcoin** [comment]
Agreed it's a good time to deactivate. Not sure about linking to that guide though, most bitcoin.org visitors are completely new to Bitcoin, so there's no need to confuse them by exposing them to BCash nonsense when they likely don't own any BTC.

**Comment by wbnns** [comment]
I've opened PR #1729 to deactivate. 👍
