### ISSUE TITLE
Remove support for weak cipher suite

### ISSUE THREAD

**Issue by reddr** [bitcoin-dot-org/bitcoin.org#1733]
Also SSL certificate/configuration for bitcoin.org is already quite good there is one thing that should be improved: 
The  **TLS_RSA_WITH_3DES_EDE_CBC_SHA** cipher-suite is known to be weak for years.
It only provides an effective 112 bit security and opens the door for meet-in-the-middle attacks.
Bitcoin.org currently supports this suite for TLS 1.0, 1.1 and 1.2.

Proposed fix:  This suite should be removed from the set of supported cipher-suites.

**Comment by Cobra-Bitcoin** [comment]
Done. Thanks for bringing this to our attention!
