### ISSUE TITLE
BlockchainUA

### ISSUE THREAD

**Issue by katininona** [bitcoin-dot-org/bitcoin.org#1739]
- date: 2017-09-22
      title: "BlockchainUA conference"
      venue: "Conference Hall “Oasis”"
      address: "Vasylia Lypkivskoho St, 1А, Kyiv, 02000, 3rd floor"
      city: "Kyiv"
      country: "Ukraine"
      link: "https://blockchainua.com"

**Comment by cjennyc28** [comment]
K

**Comment by cjennyc28** [comment]
?

**Comment by wbnns** [comment]
@katininona Thanks for submitting this! We'll get this added alongside #1736.
