### ISSUE TITLE
Missing Translation for Donation Banner

### ISSUE THREAD

**Issue by reddr** [bitcoin-dot-org/bitcoin.org#1741]
[Bounty](https://github.com/bitcoin-dot-org/bitcoin.org#earn-bitcoin-for-contributing): **13,500 bits / ~$110 USD**

Bitcoin.org is a great community effort and donations are important to steadily improve this project.

However, the donation banner is only available in English, which might discourage potential donators that are not confident with the English language, from contributing. Therefore the banner and donation popup (see screenshots below) should be translated urgently.

![bit2](https://user-images.githubusercontent.com/28353286/29210587-8f837012-7e94-11e7-93d6-0438d62a5368.png)

![bit1](https://user-images.githubusercontent.com/28353286/29210593-9371606c-7e94-11e7-9ced-362bbc9ee9a6.png)

**Comment by kuzzmi** [comment]
I agree. When developed, I included 2 more languages, but I'm not that confident in neither German, nor other languages enough to take a responsibility to translate such crucial part.

We need to update our strings on Transifex with the current version, so we can translate them ASAP.

**Comment by RafaelMostert** [comment]
How can I help? I should be able to at least add the Dutch translation.

I branched the github project and joined Transifex as a translator.
I see which strings in en.yml are responsible for the donation text, I also see that these strings are not present in the Dutch language file nl.yml, and also not available for translation in Transifex.
What is the way to add these strings to Transifex? Or can I just directly add the appropriate text to nl.yml and make a pull request for that file?

**Comment by rafaelescrich** [comment]
Hi, I'm a software developer from Brazil and want to help the project. I can translate to brazilian portuguese.

**Comment by wbnns** [comment]
This is no longer an issue. It will display correctly if:

1. The banner is turned on (it is currently off), and
2. The language is fully translated. Several of them have already translated this string.
