### ISSUE TITLE
BTC.com wallet also support PC (Windows, OSX, Linux)

### ISSUE THREAD

**Issue by Splarv** [bitcoin-dot-org/bitcoin.org#1742]
BTC.com Bitcoin Wallet also support PC (Windows, OSX, Linux). But on your site it exists only as a mobile wallet.
https://www.bitcoin.com/choose-your-wallet/bitcoin-com-wallet

**Comment by kuzzmi** [comment]
It seems quite fresh and they essentially use Copay wallet as a base with a few changes: https://github.com/bitcoin-com/wallet.

**Comment by Francisc** [comment]
It's basically Copay with different CSS.
I'd remove it altogether and leave Copay.

**Comment by crwatkins** [comment]
@Splarv as far as I know, the BTC.com wallet which is listed here does not support desktop ("PC") clients.  You provided a link to the Bitcoin.com wallet which is a different wallet from a different developer (which has not yet requested to be listed).  I don't believe this is a valid issue.
