### ISSUE TITLE
Web wallets are displayed when Mobile is selected

### ISSUE THREAD

**Issue by crwatkins** [bitcoin-dot-org/bitcoin.org#1743]
[Bounty](https://github.com/bitcoin-dot-org/bitcoin.org#earn-bitcoin-for-contributing): **20,000 bits / ~$90 USD**

@kuzzmi 

On desktop Chrome browser

1. Go to https://bitcoin.org/en/choose-your-wallet
2. Click on `Web`:  See Web selected, and see listing of wallets
3. Click on `Mobile` (but do not select any of the platforms):  See Mobile menu selected

Expected:  The listing would show Mobile wallets, or the menu selection would remain on Web
Observed:  The listing still shows Web wallets, but Mobile menu is selected.

Same occurs when clicking on `Desktop` but not selecting any of the platforms.

**Comment by kuzzmi** [comment]
I'm actually in doubt whether it even makes sense to show "all mobile" wallets. If I'm interested in the mobile wallet, I already know OS I'm looking a wallet for. 

This is definitely a bug, but a way to fix it I see is a bit different. I think it makes more sense to disable clicking a top-level menu item if there are sub-items already.
This is a general issue with menus (I clicked on "Resources"):

![image](https://user-images.githubusercontent.com/1727140/29243296-bbd756a8-7f9b-11e7-8f9e-c9c8f8f1305d.png)

**Comment by crwatkins** [comment]
@kuzzmi I agree.
