### ISSUE TITLE
Events should show Segwit activation parties

### ISSUE THREAD

**Issue by luke-jr** [bitcoin-dot-org/bitcoin.org#1746]
Multiple venues are planning Segwit activation parties next week.

**Comment by wbnns** [comment]
@luke-jr Do you have a link with a list of them?

**Comment by Kixunil** [comment]
@wbnns [I do.](http://segwit.party)

**Comment by wbnns** [comment]
@Kixunil Thanks for the link! Just a quick heads up that the link to Progressbar in Slovakia, is broken on your website, it should go to: https://www.progressbar.sk/calendar/segwit-activation-party-workshop

**Comment by Kixunil** [comment]
@wbnns Yeah, the event was changed. I didn't organize it and the organizer probably missed it.
