### ISSUE TITLE
Blockchain Cruise Asia 2018

### ISSUE THREAD

**Issue by coinsbank** [bitcoin-dot-org/bitcoin.org#1754]
- date: 2018-01-15
      title: "Blockchain Cruise Asia 2018"
      venue: "Mariner of the Seas cruise ship"
      address: ""
      city: "Singapore"
      country: "Singapore"
      link: "https://coinsbank.com/cruise-asia"

**Comment by wbnns** [comment]
@coinsbank Hello, thanks for submitting this. Could you please provide an address for this? For example, the address of the departure terminal? Once we have this we can add the event.

**Comment by coinsbank** [comment]
@wbnns 
- date: 2018-01-15
  title: "Blockchain Cruise Asia 2018"
  venue: "Mariner of the Seas cruise ship"
  address: "Marina Bay Cruise Centre Singapore"
  city: "Singapore"
  country: "Singapore"
  link: "https://coinsbank.com/cruise-asia"

**Comment by wbnns** [comment]
@coinsbank Thanks!
