### ISSUE TITLE
Blockchain and Cryptocurrency Con 2018

### ISSUE THREAD

**Issue by finid** [bitcoin-dot-org/bitcoin.org#1768]
- date: 2018-02-23
      title: "Blockchain and Cryptocurrency Con 2018"
      venue: "Dr. Pepper StarCenter"
      address: "12700 N Stemmons Frwy"
      city: "Farmers Branch"
      country: "USA"
      link: "https://blockchain-conf.com"

**Comment by wbnns** [comment]
@finid Hello, thank you for submitting this. It appears this website is unfinished / has some broken links:

Example:
![image](https://user-images.githubusercontent.com/1130872/29667140-8dcc0ac8-8898-11e7-949b-0a232d377f08.png)

Example:
![image](https://user-images.githubusercontent.com/1130872/29667112-6539099e-8898-11e7-9fb3-b100d67e0ad9.png)

It also doesn't appear that there are any speakers listed, despite there being sponsorship / media partner packages for sale.

Could you please resubmit once these items are resolved?

**Comment by finid** [comment]
@wbnns the first batch of speakers have been added, and the training partners have also been listed. 
And those are not broken links, just a way of making it difficult for email harvesters to get at the email.
