### ISSUE TITLE
Bitcoin Core wallet not syncing 

### ISSUE THREAD

**Issue by asmodyus** [bitcoin-dot-org/bitcoin.org#1770]
So it showing 8 active connections. Stuck at 97.5% Progress bar is been stuck on calculating.

**Comment by wbnns** [comment]
@asmodyus Hi there! Apologies, this repository is for issues directly related to the Bitcoin.org website. Here's a link where you can connect with others who may be able to give you technical support regarding your node: https://bitcoin.org/en/bitcoin-core/help#forums
