### ISSUE TITLE
Add fastbuybitcoin.com to Resources->Learning

### ISSUE THREAD

**Issue by peakstwin** [bitcoin-dot-org/bitcoin.org#1778]
Add www.fastbuybitcoin.com to **resources page ->learning list** and **directories->merchants**. 

This website is very helpful and has great info/guides for beginners and bitcoin community. 
Also has crypto market capitalization's data and bitcoin related news.

**Comment by wbnns** [comment]
@peakstwin Hello, thanks for mentioning. Let's hold off on adding this for now until the site becomes more well-established. This seems to be more of an affiliate site aimed at monetizing off of the key phrase "buy bitcoin online". The "helpful" information is buried in the site and the home page is mainly just referral tracking links that reside above the fold, pointing people to bitcoin exchanges.
