### ISSUE TITLE
Add the Bitcoin Foundation petition to the home page

### ISSUE THREAD

**Issue by theochino** [bitcoin-dot-org/bitcoin.org#1780]
Hello,

Add the Bitcoin Foundation to the home page.
https://www.change.org/p/members-of-the-united-states-senate-don%CA%BCt-criminalize-bitcoin-and-other-cryptocurrencies

This is finally getting endorsed: https://twitter.com/charlieshrem/status/903662301353566209

Theo Chino
AbolishTheBitlicense.com

**Comment by wbnns** [comment]
@theochino Hello, thanks for mentioning. Let's hold off on this for now as the home page may not be the best place for this.

We have hundreds of thousands of international visitors that this wouldn't pertain to.
