### ISSUE TITLE
Add bticoin release 0.15.0 to /bin/

### ISSUE THREAD

**Issue by victorperin** [bitcoin-dot-org/bitcoin.org#1795]
[Bitcoin v0.15.0 has released](https://github.com/bitcoin/bitcoin/releases/tag/v0.15.0) we should update the website bin folder to match the binaries.

Add binaries files to https://bitcoin.org/bin/bitcoin-core-0.15.0/

**Comment by harding** [comment]
Bitcoin Core 0.15.0 has been tagged but not yet released as of this message.  The tagging always occurs before the binaries are built, as Bitcoin Core requires at least three well-known community members to each independently generate identical binaries for each platform before distributing those binaries on Bitcoin.org and BitcoinCore.org.

In short: don't worry, the binaries will be uploaded as soon as they're ready.

**Comment by victorperin** [comment]
Thank you, I didn't know about this process. :)
