### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by fintechworldforum** [bitcoin-dot-org/bitcoin.org#1798]
- date: 2017-11-21
      title: "FinTech World Forum 2017"
      venue: "The Great Hall, Kensington Conference and Events Centre"
      address: "Hornton St, Kensington, London W8 7NX"
      city: "London"
      country: "UK"
      link: "http://fintechconferences.com"

**Comment by fintechworldforum** [comment]
Event Submision

**Comment by wbnns** [comment]
Closing, duplicate of #1797
