### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by coinsbank** [bitcoin-dot-org/bitcoin.org#1799]
- date: 2018-01-17
      title: "Thai Blockchain Conference"
      venue: "Phuket Paradise Beach"
      address: "109 Muean-Ngern Rd., Patong, Kathu, Phuket, 83150 Thailand"
      city: "Patong"
      country: "Phuket, Thailand"
      link: "https://thai.coinsbank.com"

**Comment by wbnns** [comment]
@coinsbank Hello, thanks for submitting this. Could you please let us know when more information has been added regarding speakers? At the moment, it seems there is only information about sponsors, along with tickets for sale. Also, the Contact and social media links appear to be broken.
