### ISSUE TITLE
Fintechsummit

### ISSUE THREAD

**Issue by Matejicko** [bitcoin-dot-org/bitcoin.org#1810]
- date: 2017-11-16
      title: "Fin.Techsummit"
      venue: "Crowne Plaza"
      address: "Hodžovo námestie 568/2"
      city: "Bratislava"
      country: "Slovakia"
      link: "http://fintechsummit.sk/en/"

**Comment by Matejicko** [comment]
Hello, 
I see that you probably have a lot of work. 
I would like to ask you, if you had time to look into this conference, so it can be added. 
Thanks.

**Comment by wbnns** [comment]
@Matejicko Hi there! Absolutely, this will be added via `99af791`.
