### ISSUE TITLE
Blockchain & Bitcoin Conference Malta

### ISSUE THREAD

**Issue by ElenSh** [bitcoin-dot-org/bitcoin.org#1823]
On December 7, Malta will become the epicenter of the fintech industry in Europe as it will host the Blockchain & Bitcoin Conference.

Blockchain & Bitcoin Conference is a series of international events that take place in Moscow, St. Petersburg, Kyiv, Stockholm, Tallinn, Prague, and now also in Malta. Organizer of the conferences is the international company Smile-Expo, which became a pioneer of the exhibition business in the field of advanced technologies.

The conference will cover such topical issues as ICO holding, trends of the blockchain industry, development of cryptocurrencies and challenges of legislative regulation of the fintech sector.

The conference participants are representatives of largest financial organizations in Europe, IT specialists, business angels, investors and government officials.

Official language of the conference is English.

Source: https://malta.blockchainconf.world/en © Blockchain & Bitcoin Conference Malta

**Comment by wbnns** [comment]
@ElenSh Thanks for submitting this; closing in favor of #1812. We'll have this added soon!
