### ISSUE TITLE
اولین همایش بیت‌کوین  و ارزهای دیجیتال

### ISSUE THREAD

**Issue by syasserahmadi** [bitcoin-dot-org/bitcoin.org#1829]
- date: 2017-10-17
      title: "اولین همایش بیت‌کوین 
و ارزهای دیجیتال"
      venue: "سالن همایش های کتابخانه ملی"
      address: "تهران، بزرگراه شهید حقانی، بعد از ایستگاه مترو حقانی، خروجی كتابخانه ملی"
      city: "تهران"
      country: "ایران"
      link: "https://btcday.ir/"

**Comment by Roy19833** [comment]
Verzonden vanuit Outlook
________________________________
Van: syasserahmadi <notifications@github.com>
Verzonden: dinsdag 3 oktober 2017 01:22:14
Aan: bitcoin-dot-org/bitcoin.org
CC: Subscribed
Onderwerp: [bitcoin-dot-org/bitcoin.org] اولین همایش بیت‌کوین و ارزهای دیجیتال (#1829)


- date: 2017-10-17 title: "اولین همایش بیت‌کوین

و ارزهای دیجیتال"
venue: "سالن همایش های کتابخانه ملی"
address: "تهران، بزرگراه شهید حقانی، بعد از ایستگاه مترو حقانی، خروجی كتابخانه ملی"
city: "تهران"
country: "ایران"
link: "https://btcday.ir/"

**Comment by syasserahmadi** [comment]
if there's any question , i'd be happy to answer
