### ISSUE TITLE
Bitcoin & CryptoCurrency Event

### ISSUE THREAD

**Issue by javidjava** [bitcoin-dot-org/bitcoin.org#1839]
- date: 2017-10-17
      title: "Bitcoin & CryptoCurrency Event"
      venue: "Iran national library"
      address: "Haqqani Highway, after the Haqqani Subway Station, National Library Outlet."
      city: "Tehran"
      country: "Iran"
      link: "https://btcday.ir"
[![logo btc](https://user-images.githubusercontent.com/20674316/31296676-18a956d6-aaf0-11e7-8945-9c3db6dffc82.jpg)](http://btcday.ir)

**Comment by wbnns** [comment]
Closing, duplicate of #1829. This will be on the website, soon - thanks!
