### ISSUE TITLE
Add More Indian Exchanges

### ISSUE THREAD

**Issue by 77gabru** [bitcoin-dot-org/bitcoin.org#1843]
Three top INR exchanges were listed under Indian section and out of which 'Unocoin' recently got removed due to : #1836 

lots of new exchanges came out in last few months ( some are not worthy to be listed just yet) but i think its safe enough to add [PocketsBits](https://pocketbits.co.in/AboutUs), [Koinex](https://koinex.in/about_us) and [Coinome](https://www.coinome.com/pages/about-coinome)

Let me know if any more information is required, i can get official statements from all.

Thanks

**Comment by Mirobit** [comment]
What is there position on the upcoming Segwit2X hard fork? Which coin will they call Bitcoin?

**Comment by 77gabru** [comment]
PocketBits : The legacy chain will be listed as BTC, The forked chain will be listed as S2X or BTG

Koinex : Whichever is the longer and has more community support

Coinome : we understand that the chain split possibility and hard fork is all stemming out of the developer efforts put on BitcoinCore, and hence, we'd like to continue to call BitcoinCore as Bitcoin/BTC. However, since our business would survive only with our customers and our fundamental loyalty is to our customers, we'd like to take heed of their demands if a bad situation arises, and hence we might have to take a change in our stand in the future.

**Comment by sreekanthgs** [comment]
+1. I represent Coinome.com.

**Comment by sreekanthgs** [comment]
Our stand on the Bitcoin name and BTC ticker symbol along with our decision on upcoming forks: https://blog.coinome.com/bitcoin-cash-and-other-new-hard-forks-ae3dadbc0d

**Comment by wbnns** [comment]
@77gabru Hello, thanks for letting us know. An Indian exchange, Coindelta, was recently added. Coinome was deferred for now since it is in beta. If there are others that people are using in India that you think should be on the page, please feel free to submit a pull request.

**Comment by sreekanthgs** [comment]
@wbnns Coinome is now out of Beta. Can you folks please reconsider this? Thank you.
