### ISSUE TITLE
Adding warning about risk of 51% attacks after Segwit2x attack

### ISSUE THREAD

**Issue by billkle1n** [bitcoin-dot-org/bitcoin.org#1847]
Since the vast majority of the hash rate will stop mining after the Segwit2x hard fork, it will become feasible for some of the big miners to perform double spend attacks on Bitcoin, rewrite the transaction history or indefinitely stall the confirmation of new transactions. Maybe it would make sense to add a warning about that?

**Comment by Cobra-Bitcoin** [comment]
Why warn about 51% attacks? A 51% attack has always been possible. It's not a new risk. If miners dare to attack the Bitcoin block chain, they will be fired through a change of POW.

**Comment by billkle1n** [comment]
It's always been a *theoretical* risk but has never been a real danger since no single miner has ever controlled over 51% of the hash rate. The danger will become very real after the hard fork since a lot of miners will suddenly possess over 51% of the Bitcoin chain's hash rate (and a lot more than that in the case of large miners).

There is a real risk that people will lose money and I feel like it would be responsible to explain the attack and why the sudden loss of hash rate will make Bitcoin less secure for a while (possibly, permanently).

**Comment by kbenzle** [comment]
It would be a larger enough of a concern for users running full Core nodes. What would happen if a Core node sent coins to an address and the TX was picked up by the 2X network?
