### ISSUE TITLE
Could you please add the landmark for the Blockchain & Bitcoin Conference Moscow?

### ISSUE THREAD

**Issue by Nbesedin** [bitcoin-dot-org/bitcoin.org#1853]
Question in topic. 
Thank you in advanec.

**Comment by wbnns** [comment]
@Nbesedin Sure, if you have the info, we can add it for you. Here's what we need:
https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/docs/adding-events-release-notes-and-alerts.md#events
