### ISSUE TITLE
Altana Wallet requirements for Choose your wallet page

### ISSUE THREAD

**Issue by the9ull** [bitcoin-dot-org/bitcoin.org#1860]
[Altana](https://play.google.com/store/apps/details?id=it.inbitcoin.altana) is an Android Wallet, it is a fork of GreenBits.
Differently from GreenBits it does not remind the user to enable 2FA. We disabled it because we consider it a feature for advanced users, we think that the beginner user could get damaged if s/he uses 2FA without knowing what s/he is doing.
Do we have to modify this feature before submit Altana to Change your wallet page?
Thank you

**Comment by crwatkins** [comment]
@the9ull thanks for reviewing the [basic requirements](https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/docs/managing-wallets.md) for wallets before submitting a PR.  As you probably noticed, we currently have the following requirements for multi-sig wallets:

* Provides 2FA authentication feature
* Reminds the user to enable 2FA by email or in the main UI of the wallet

which are currently required for wallet listings.  You could certainly meet the requirement by re-enabling that feature before submitting Altana for listing.  Another option would be to open an issue for discussion to remove that requirement, or actually submit a PR to remove that requirement with justifications for discussion by the community.  Our requirements are constantly evolving.

Personally, I'm currently slightly learning toward keeping the requirement as I believe it is very useful and there is no requirement for the user to enable it.   That said, however, I think one might be able to argue that any multi-sig wallet (with or with 2FA) is as safe or safer than a wallet without multi-sig.

Please feel free to submit any other questions here or in a separate issue.
