### ISSUE TITLE
Blockchain Development Program at York University

### ISSUE THREAD

**Issue by theblockchainhub** [bitcoin-dot-org/bitcoin.org#1861]
- date: 2017-10-27
      title: Certified Ethereum Developer Program
      venue: Bergeron Centre, York University
      address: ""
      city: Toronto
      country: Canada
      link: www.theblockchainhub.com/ced
<img width="979" alt="screen shot 2017-05-08 at 4 17 20 pm" src="https://user-images.githubusercontent.com/32369278/31647571-13e79ed4-b2d7-11e7-9e76-44c2a7bdd99c.png">

**Comment by wbnns** [comment]
@theblockchainhub Hello, this seems to be for an Ethereum Developer Program (there aren't any mentions of Bitcoin). If I missed something, please let me know.

**Comment by theblockchainhub** [comment]
Hi! We would love to incorporate bitcoin in our blockchain development curriculum, but we need your help for it!
