### ISSUE TITLE
Blockchain&Bitcoin Conference Moscow

### ISSUE THREAD

**Issue by Nbesedin** [bitcoin-dot-org/bitcoin.org#1862]
- date: 2017-11-15
      title: "Blockchain& Bitcoin Conference Moscow"
      venue: "ECC "Sokolniki", pavilion 4.1 5-iy Luchevoy prosek 7/1
      address: "ECC "Sokolniki", pavilion 4.1 5-iy Luchevoy prosek 7/1"
      city: "Moscow"
      country: "Russia"
      link: "https://moscow.blockchainconf.world/en"

**Comment by wbnns** [comment]
Hello, thank you for submitting this - it has already been added.

**Comment by Nbesedin** [comment]
I asked previously to add this on the map(since it is on the website but not on the interactive map) and you responded I should remake an issue with full event info
