### ISSUE TITLE
erro leer la base de dato,cerrando

### ISSUE THREAD

**Issue by shimonlaloush** [bitcoin-dot-org/bitcoin.org#1863]
the application bitcoin-qt.exe has requested the Runtime to terminate it in an unusual way
help

**Comment by wbnns** [comment]
@shimonlaloush Hello, apologies, this repository is for issues directly related to the code base of Bitcoin.org. For technical support specifically related to Bitcoin Core, we recommend visiting one the communities located here: https://bitcoin.org/en/development#dev-communities

Good luck! :)
