### ISSUE TITLE
Blockchain & Bitcoin Conference Slovenia 

### ISSUE THREAD

**Issue by antipova** [bitcoin-dot-org/bitcoin.org#1865]
- date: 2017-12-12
      title: "Blockchain & Bitcoin Conference Slovenia" 
      venue: "Dunajska cesta 18, 100,"  Ljubljana Exhibition and Convention Centre."   
      address: "Dunajska cesta 18, 100,"  Ljubljana Exhibition and Convention Centre."  
      city: "Ljubljana" 
      country: "Slovenia" 
      link: https://goo.gl/JjjjHE 
![22050970_1730887337216339_1178604760392358225_o8iy7u9](https://user-images.githubusercontent.com/32902868/31721538-43951e08-b422-11e7-9f63-fe2cb5331ee0.jpg)

**Comment by Artic2017** [comment]
у
