### ISSUE TITLE
Curso Bitcoin Colombia MasterTrader y otras criptomonedas presencial.

### ISSUE THREAD

**Issue by maribelplazav** [bitcoin-dot-org/bitcoin.org#1870]
2017-10-23
 Curso Bitcoin Colombia MasterTrader y otras criptomonedas presencial.
Te invito a participar en nuestros cursos Bitcoin Colombia MasterTrader y otras criptomonedas presencial.
Conoce todo sobre Bitcoin y otras criptomonedas. Aprende a detectar oportunidades de compraventa , invierte por tu cuenta y gana dinero haciendo trading en plataformas globales como Kraken, Poloniex, Bittrex.

Lugar y fecha: Bogotá, desde el 23 de Octubre 2017
Hora: 6:30pm a 9:30pm 
Costo: $300.000
Duración: 16 horas
Info: (+57) 316 435 8391
Prestamos el servicio de Compra y Venta de Bitcoin y otras criptomonedas
Te invito a visitar nuestra pagina web  
www.bitcoin-colombia.com

**Comment by wbnns** [comment]
@maribelplazav Hola, podría volver a enviar este evento en el siguiente formato?
https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/docs/adding-events-release-notes-and-alerts.md#events

Si tiene alguna pregunta o problema, hágamelo saber.
