### ISSUE TITLE
wrong info, the fee cannot reach near zero or tx delay tend to NaN of time

### ISSUE THREAD

**Issue by camenlx** [bitcoin-dot-org/bitcoin.org#1879]
At https://bitcoin.org/en/faq#how-much-will-the-transaction-fee-be
is wrong info for new commers to bitcoin for current date 2017.
The term 'low' fee is relative how much you pay for 1 bread in your wealth environment.
In my humble opinion, current 'dynamic' fees by app's are really very higth.

The site should state tx 'fees' are mandatory or else you lose your money in the void of unconfirmed transaction.
Please someone inform me what is the email distribution to propose a BIP?
I want to propose that any tx unconfirmed should have a timeout destructor at 24h long.
If bitcoin states that fiat tx are slow then this is must have feature, either miners assure all tx processed in 24h period or these old 24h waiting unconfirmed tx should be released (destroied).
Thanks for reading.

**Comment by wbnns** [comment]
@camenlx Hello, here's a link to where you can learn more about how to submit a BIP, including the standard procedure: https://github.com/bitcoin/bips/blob/master/README.mediawiki
