### ISSUE TITLE
Change homepage from "new kind of money" to "intangible commodity"

### ISSUE THREAD

**Issue by theochino** [bitcoin-dot-org/bitcoin.org#1887]
The guy that has come up with this definition is in jail so he cannot send this himself.

To make money, you need a commodity (metal, silver, gold, ....) and someone to transform that commodity. Bitcoin is the root and it's virtual, so it's an "intangible commodity."

![32062249-f6c935ca-ba41-11e7-8d7d-d1ba195a3dc1](https://user-images.githubusercontent.com/5959961/32128518-584fa2e2-bb4c-11e7-8651-0d95c4fcfd68.png)

![32062261-fd1c98fe-ba41-11e7-986d-347026d2f9bf](https://user-images.githubusercontent.com/5959961/32128520-5c78bd86-bb4c-11e7-824e-49e4ad0c4ba0.png)

Theo Chino
https://twitter.com/TheoBitcoin/status/923609548975493121

**PS:** This has been the most contentious two words to describe bitcoin and the use of "Money" is what makes every law maker want to kill it and send everyone in jail. - This need to be changed. Morpheus _(the guy in jail in Arizona - https://www.facebook.com/groups/FreeMorpheusTitania)_ and I _(the guy suing up the NYDFS - http://AbolishTheBitlicense.com)_ came up with the best description to explain Bitcoin in less than 5 minutes.

**Comment by wbnns** [comment]
@theochino Hello, thanks for suggesting this change. Closing this for now since there doesn't seem to be much support in pressing for this.
