### ISSUE TITLE
P2SH documentation implies non-existent policy.

### ISSUE THREAD

**Issue by evoskuil** [bitcoin-dot-org/bitcoin.org#1894]
[Bounty](https://github.com/bitcoin-dot-org/bitcoin.org#earn-bitcoin-for-contributing): **22,000 bits / ~$175 USD**

Source File: _includes/devdoc/guide_transactions.md

> **Pay To Script Hash (P2SH)**
P2SH is used to send a transaction to a script hash. Each of the standard pubkey scripts can be used as a P2SH redeem script, but in practice only the multisig pubkey script makes sense until more transaction types are made standard.

This implies that redeem scripts must at least be standard for their tx to be standard, which is not the case and conflicts with this statement in [another section](https://bitcoin.org/en/developer-guide#non-standard-transactions):

> This allows payment to non-standard scripts, and as of Bitcoin Core 0.11, almost all valid redeem scripts can be spent.

Clarification would be helpful I think.

**Comment by looterz** [comment]
@wbnns Can you confirm if the bounty was paid out for this to `3HvapZ9bNe5itSXPpB1TR7XYYCKRz5qSEY`? I was unable to find the transaction.

**Comment by wbnns** [comment]
@looterz 

Apologies, we missed this on our side because we manually closed the issue instead of doing it via the PR - but you're all set now. This has been included with #1947. Thanks for the help!
