### ISSUE TITLE
Blocktrain 1.0

### ISSUE THREAD

**Issue by Mirash1810** [bitcoin-dot-org/bitcoin.org#1898]
- date: 2017-11-24
      title: "" Blocktrain 1.0
      venue: "" Centro de Alta Tecnología
      address: "" Cra. 15 #77-05
![d7fa72_03f077172f5141bfbe29905645977168-mv2](https://user-images.githubusercontent.com/33358680/32392883-6a3d14a4-c0a5-11e7-9fe5-469e53f527d3.png)

      city: ""Bogota 
      country: "" Colombia 
      link: ""https://www.blocktrainedu.info/

**Comment by Mirash1810** [comment]
Hello there, could you explain me what does close means for this request?
Thanks

**Comment by wbnns** [comment]
@Mirash1810 Hello, sure - this closed because the event has been added: https://github.com/bitcoin-dot-org/bitcoin.org/commit/4cbc4c6ee4e4ec934f58cca34e884a1bf02f4369

If you have any other questions, please let me know - happy to help.
