### ISSUE TITLE
importaddress (watch-only wallet) does not show any balance

### ISSUE THREAD

**Issue by MasterII** [bitcoin-dot-org/bitcoin.org#1901]
Hello,
I have add my blockchain wallet address (via importaddress), rescan 100%, but even after 3 days, bitcoincore client 0.15.0.1 dows not show actual balance. It stays on 0.00000000.

Also I have not found how to remove watch-only wallet to monitor other.

**Comment by wbnns** [comment]
@MasterII Hello, apologies, this repository is for issues directly related to Bitcoin.org. For Bitcoin Core support, here's are some forums where you can connect with others who may be able to help you: https://bitcoin.org/en/bitcoin-core/help#forums
