### ISSUE TITLE
Ubuntu 16.10 not supported

### ISSUE THREAD

**Issue by matbalez** [bitcoin-dot-org/bitcoin.org#1913]
The instructions provided for Ubuntu 16.10 fail b/c the binaries for bitcoin-qt and bitcoind are not available for this distro. 

I was however able to get these instructions to work for 16.04, so perhaps as simple as just relabeling the version number?

**Comment by wbnns** [comment]
@matbalez Hello, thanks for the heads up - which instructions on what page are you referring to?

**Comment by matbalez** [comment]
https://bitcoin.org/en/full-node

<img width="1059" alt="screen shot 2017-11-19 at 9 32 33 pm" src="https://user-images.githubusercontent.com/1079348/32999633-4446da90-cd71-11e7-8483-d7ce507baf58.png">
