### ISSUE TITLE
The North American Bitcoin Conference

### ISSUE THREAD

**Issue by AmandaHendricks** [bitcoin-dot-org/bitcoin.org#1915]
- date: 2018-01-18 & 19
      title: "The North American Bitcoin Conference"
      venue: "James L Knight Center"
      address: "400 SE 2nd Ave, Miami, FL 33131"
      city: "Miami"
      country: "U.S.A."
      link: https://btcmiami.com
![tnabc_miami2018_600x315](https://user-images.githubusercontent.com/28020576/32728639-4c342d1c-c83e-11e7-86ce-c63406c64b44.jpg)

"

**Comment by duynam1992** [comment]
33131

**Comment by Vishesh-Gupta** [comment]
I would to attend this conference. Is there any official website for this?

**Comment by AmandaHendricks** [comment]
@Vishesh-Gupta https://btcmiami.com
