### ISSUE TITLE
Testing Connections is no worhing!

### ISSUE THREAD

**Issue by Torrent76** [bitcoin-dot-org/bitcoin.org#1917]
Testing Connections on:       https://bitcoin.org/en/full-node#what-is-a-full-node

"The BitNodes project provides an online tool to let you test whether your node accepts inbound connections. 

On my wallet I can see 12/8 inbound/outbound number of conections. I try with Testing Connections and is no working. Why? What i did wrong?

Thank
Frank R.

**Comment by wbnns** [comment]
@Torrent76 Hello, apologies, this repository is for issues directly related to the code base of Bitcoin.org. For technical support specifically related to Bitcoin Core, we recommend visiting one the communities located here: https://bitcoin.org/en/development#dev-communities

Good luck! :)
