### ISSUE TITLE
Request for greater clarity in the Standard Transactions section

### ISSUE THREAD

**Issue by sidheart** [bitcoin-dot-org/bitcoin.org#1924]
[Bounty](https://github.com/bitcoin-dot-org/bitcoin.org#earn-bitcoin-for-contributing): **7,000 bits / ~$50 USD**

Source File: _includes/devdoc/guide_transactions.md

Pubkey script: OP_HASH160 <Hash160(redeemScript)> OP_EQUAL
Signature script: <sig> [sig] [sig...] <redeemScript>

The above is presented as the standard P2SH. However, it is confusing for first time readers. Using the information presented in the guide so far, a reader will conclude that this script indeed verifies that the redeemScript hashes to the proper value. However, the importance of the signatures is not evident. In addition, it is not clear how the redeemScript is processed after it has been verified.

**Comment by Vishesh-Gupta** [comment]
I am not sure how to add it to the .md file but redeemScript is similar in function Pubkey Script and I think this article can clearly justify your answer https://github.com/bitcoin/bips/blob/master/bip-0016.mediawiki

**Comment by Merkerk44** [comment]
Habe auf die wallet Code 3FkenCiXpSLqD8L79intRNXUgjRoH9sjXa  Block 495418
BTC eingezahlt. Wo kann ich meine BTC finden
