### ISSUE TITLE
Contributing and Web Based General Issues

### ISSUE THREAD

**Issue by Vishesh-Gupta** [bitcoin-dot-org/bitcoin.org#1925]
I am interested in solving website based issues and would love to be assigned a few of the website based issues. I have experience in working with the web.

Also for contributing more to this repository, I want to know what kind of skills do people expect one to have. I know a lot of people have been asking me the same question recently from where I am but have no clue and are scared to ask. This can also help other people I suppose.

I would also like to know what skills can help solve the bounty tag based problems as they look fun.

**Comment by wbnns** [comment]
@Vishesh-Gupta Hi there! Awesome, thanks for getting in touch. If you have a development background, all you need to do is resolve the open issue by submitting a pull request addressing the problem. If the issue has a bounty attached to it, include your bitcoin address in the pull request and get paid that amount if the pull request gets approved and merged.

If you don't have a development background, don't worry, some new opportunities are on the horizon that non-technical people can still partake in and get paid for contributing. If you're fluent in more than one language, one you can already get started on is our [Translation project](https://www.transifex.com/bitcoinorg/bitcoinorg/) - helping people learn about Bitcoin in languages other than English.
