### ISSUE TITLE
The transaction example is missing the pubkey in the scriptSig-field

### ISSUE THREAD

**Issue by Sword-Smith** [bitcoin-dot-org/bitcoin.org#1926]
[Bounty](https://github.com/bitcoin-dot-org/bitcoin.org#earn-bitcoin-for-contributing): **7,000 bits / ~$50 USD**

Source File: _includes/devdoc/ref_transactions.md

**Comment by Kexkey** [comment]
It is not an error in the documentation.

The example spends a pay-to-pubkey output.  The scriptPubKey of a p2pk output is:

\<pubKey\> OP_CHECKSIG

...and hence only the signature is expected in the spending scriptSig.

Reference: https://en.bitcoin.it/wiki/Script#Obsolete_pay-to-pubkey_transaction

**Comment by RandyMcMillan** [comment]
close?

**Comment by Sword-Smith** [comment]
Yes, close.
