### ISSUE TITLE
Wallet order

### ISSUE THREAD

**Issue by runn1ng** [bitcoin-dot-org/bitcoin.org#1928]
In what order are the wallets listed on the bitcoin.org website?

I was surprised today that Bitcoin Knots is in front of Bitcoin Core on the listing - https://bitcoin.org/en/wallets/desktop/linux

I cannot find where the order is taken from in this repo. Is it random?

**Comment by kuzzmi** [comment]
The order is not purely random, but depends on a date. Date is used to make daily rotation and to ensure that wallets are listed in the same order every day.

You can take a look here:
https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/js/main.js#L357
