### ISSUE TITLE
dumpprevkey return unknown error (code-4)

### ISSUE THREAD

**Issue by webwakko** [bitcoin-dot-org/bitcoin.org#1930]
Location: https://bitcoin.org/en/developer-reference#dumpprivkey
I have a version from the QT-wallet (in fact a few for different coins) which have a strange error in it.
When trying to dump a private key for the original address in the wallet, in returns an error that the private key is unknown for that address.
Weird part is: when creating a new address within this same wallet, the dump works fine.
Due to the unknow private key, it's impossible to send out coins from this wallet that were received on that address. In other words, all the received coins are stuck in the wallet.

**Comment by webwakko** [comment]
Hi wbnns, 

thanks for labeling it for me.. I hope this issue has a positive solution..

**Comment by wbnns** [comment]
@webwakko Hello, here's a link to forums where you can connect with others who may be able to offer technical support regarding your issue: https://bitcoin.org/en/bitcoin-core/help#forums

**Comment by webwakko** [comment]
Thanks
