### ISSUE TITLE
Need assistance ASAP

### ISSUE THREAD

**Issue by Hubpretv** [bitcoin-dot-org/bitcoin.org#1937]
Hi,

Need assistance ASAP with transaction sent from node to bitcoinpay address. It is sent from node and never happened to me that get transaction ID and when paste in explorer getting message that could not be find transactions matching this hash. Here is transaction ID 6d452c5a1b745a50c4e5a074b9266e2f5bb24ccb013a0ac31647a31fc50aa454
and here is  address where it is sent 
 1FUEFJhJZg5b2zZdiGakyWg4z5pu2DpcHg
Not know was me click in fast something twice or not but that never happened to me and all transaction go fast from node and now not know what is best way to do, could you tell me best way to get that transaction visible ?

![image](https://user-images.githubusercontent.com/33935037/33179446-bf1e1a8a-d069-11e7-8767-468009b6068c.png)

Best regards!

**Comment by Hubpretv** [comment]
Is it problem bitcoinpay wallet or transaction fee????

**Comment by wbnns** [comment]
@Hubpretv Hello, apologies, this repository is for issues related directly to Bitcoin.org. For node/wallet-related support, here are some links to forums where you can connect with others who may be able to help you: https://bitcoin.org/en/bitcoin-core/help#forums
