### ISSUE TITLE
Should Bitcoin.org sponsor Kyle Torpey?

### ISSUE THREAD

**Issue by wbnns** [bitcoin-dot-org/bitcoin.org#1945]
[Kyle Torpey](https://twitter.com/kyletorpey) has a [Daily Bitcoin Newsletter](https://www.getrevue.co/profile/kyletorpey/) that he sends out every day to a loyal following of a bunch of people (myself included), which he is turning into a Podcast and YouTube stream, where he goes over the news.

He's been doing it on his own time, consistently, since April.

I was thinking considering how much money those bent on fracturing our community throw into spreading FUD, fake news and misinformation, on their own Bitcoin-related websites. This is an opportunity to support someone who is on our community's side.

Sponsoring Kyle would be $5K for the month of December (we could optionally renew, but we don't have to - we have just over $100K in our reserves).

Sponsoring him would make us part of his daily bitcoin recap, which would include:
+ A mention in his [tweets](https://twitter.com/kyletorpey/status/933538520232284160) when he sends out the newsletter each day.
+ A link to Bitcoin.org below his bio at the beginning of every newsletter.
+ A 5-10 second mention at the beginning of every podcast / YouTube show.

This could be helpful in bringing new users, contributors and contributions to Bitcoin.org, and also push back against efforts of others who are working and spending money each day to try and direct people away from us.

We can also look at our Analytics to see how much traffic we're getting from this towards the end of the month.

The sponsorship would start on December 1 and end on December 31, unless we want to renew.

Thoughts?

**Comment by wbnns** [comment]
Apologies, forgot to add my opinion as the website maintainer - I think we should.

**Comment by kuzzmi** [comment]
I think sponsoring Kyle is a good idea. Everybody will agree that it's quite difficult to find good concise unaffiliated news summaries, that do not spread FUD, but stick to facts. I haven't been following Kyle, but did check some of his former tweets and newsletters and it's pretty clear that he's "on our community's side". 

In addition I have a few thoughts:

1. It would be also nice to see a link to Bitcoin.org on his website as well, perhaps in a separate section, if that's fine with Kyle of course, so those who ever get to the website also can easily get to bitcoin.org

2. Not sure how feasible that would be, but it would also be neat to have a transparent picture of how this sponsorship works. May be something like a bi-weekly report. I know for sure that a link in the email can be tweaked to have some kind of an anchor, so it's visible in Google Analytics, not sure about Twitter tho. This way the numbers will tell about how this sponsorship works.

**Comment by kyletorpey** [comment]
@kuzzmi Adding a link to bitcoin.org to my personal site seems like a good idea whether this sponsorship goes through or not. I can add it to the section about some of my favorite projects. I'll go ahead and do that now.

I'm not sure how to setup a tracking link, but I'd be open to that. To be honest, I think the value of this sponsorship from Bitcoin.org's perspective would be more of supporting a single news source to promote that this community trusts. Other than that, I imagine bringing in new contributors and donations would be the key metrics to track, and hopefully I'd be able to help out there. From what I can tell, you guys don't need much help in the general traffic department.

**Comment by wbnns** [comment]
@kuzzmi @kyletorpey 

Thanks guys - the link is easy to set up, it's no problem (https://bitcoin.org/?utm_source=kyletorpey).

**Comment by wbnns** [comment]
Let's give this a couple more days - if there continues to be an absence of objection and/or critical feedback from multiple people that this shouldn't be done, we can plan to start this on Friday, December 1, for one month.

**Comment by Cobra-Bitcoin** [comment]
Sounds like a good idea!

**Comment by wbnns** [comment]
@kyletorpey 

We just sent you a payment for the first week of this, that just finished. We'll continue to do so each week, until the end of the month. Thanks!
