### ISSUE TITLE
Undocumented inv/data message types

### ISSUE THREAD

**Issue by eklitzke** [bitcoin-dot-org/bitcoin.org#1947]
[Bounty](https://github.com/bitcoin-dot-org/bitcoin.org#earn-bitcoin-for-contributing): **25,000 bits / ~$200 USD**

The current docs define `MSG_TX`, `MSG_BLOCK` and `MSG_FILTERED_BLOCK`. There are actually more defined now. From `protocol.h`:

```c
/** getdata / inv message types.
 * These numbers are defined by the protocol. When adding a new value, be sure
 * to mention it in the respective BIP.
 */
enum GetDataMsg
{
    UNDEFINED = 0,
    MSG_TX = 1,
    MSG_BLOCK = 2,
    // The following can only occur in getdata. Invs always use TX or BLOCK.
    MSG_FILTERED_BLOCK = 3,  //!< Defined in BIP37
    MSG_CMPCT_BLOCK = 4,     //!< Defined in BIP152
    MSG_WITNESS_BLOCK = MSG_BLOCK | MSG_WITNESS_FLAG, //!< Defined in BIP144
    MSG_WITNESS_TX = MSG_TX | MSG_WITNESS_FLAG,       //!< Defined in BIP144
    MSG_FILTERED_WITNESS_BLOCK = MSG_FILTERED_BLOCK | MSG_WITNESS_FLAG,
};
```

I will probably send a PR adding documentation for these at some point, but if someone else wants to jump in feel free.

**Comment by Tusharchoudhary** [comment]
how can i help?

**Comment by cornelius** [comment]
It looks like this is done in pull request #2092. Is there anything else to do or can this issue be closed?

**Comment by wbnns** [comment]
@cornelius No, it appears you're right. Thanks for mentioning!

@looterz Would you like to provide an updated bitcoin address for collecting the bounty?

**Comment by looterz** [comment]
@wbnns Hi my current address is `3HvapZ9bNe5itSXPpB1TR7XYYCKRz5qSEY`. Appreciate it!

**Comment by wbnns** [comment]
@looterz 

Great, thanks! Here's the [transaction ID](https://live.blockcypher.com/btc/tx/36e3bd4fa0ea5b9ee016f7505457362e655c82e29e82756dcaa02db8feeab879/) for the bounties you took down.
