### ISSUE TITLE
Итоговая конференция BlockchainMania

### ISSUE THREAD

**Issue by sergiietsmaksym** [bitcoin-dot-org/bitcoin.org#1952]
- date: 2017-12-16
      title: "Итоговая конференция BlockchainMania"
      venue: "МОСКВА БЕРСЕНЕВСКАЯ НАБ, , Д. 6, СТР"
      address: "БЕРСЕНЕВСКАЯ НАБ, , Д. 6, СТР"
      city: "МОСКВА "
      country: "РОССИЯ"
      link: "http://blockchainmania.ru"
“Цыплят по осени считают” или итоговая конференция BlockchainMania

Фейерверк искрометных докладов, секретные рецепты успеха, аналитика уходящего крипто-года и прогноз крипто-погоды на 2018 - все это в предновогодней, заключительной конференции БЛОКЧЕЙНМАНИЯ!
Итоговая конференция объединит в себе главные тенденции и актуальные резюме по различным направлениям этой отрасли. Важно присутствовать как новичкам, так и бывалым представителям сообщества. Будут инвесторы, трейдеры, аналитики, стартаперы.
Что будут обсуждать?
Тренды ближайшего года и дальше. Чего точно следует ожидать. 
Какие есть и как избежать юридических рисков при ICO в России и мире. Как провести полностью законное ICO?
Деятельность Экспертного совета по цифровой экономике и блокчейн технологиям при Госдуме РФ.
Перспективы использования блокчейна в предпринимательстве.
Как проекту выстроить коммуникацию со СМИ.
IR для ICO проектов. 
Опыт "HOQU": как 500 человек привлекли 3000 инвесторов и это не стоило ни копейки.
Живая дискуссия криптоинвесторов. 
Презентации проектов для инвесторов. 
Для кого конференция?
Для всех, кто хочет идти в ногу с развитием цивилизации: инвесторам (микро и макро), трейдерам (крипто и фиат), аналитикам, разработчикам. 
Почему нужно посетить эту конференцию?
В крипто-мире события развиваются со скоростью ракеты. Ваш успех, личный или корпоративный, во многом определяется возможностью держать руку на пульсе: причем желательно «прощупывать пульс» у ведущих игроков на рынке. Квинтэссенция полученного в 2017 году опыта станет стартом для прыжка в 2018, который обещает быть еще более насыщенным и интригующим. Подведение итогов. Впитать рецепты лучших. Схватить инсайд государственных движений. Услышать основные тренды следующего года. Объединить всю эту информацию, и стать супер успешным - в 2018 году!

Кто расскажет?
Соучредитель крипто-фонда; 
Член экспертного совета рабочей группы по цифровой экономике при Госдуме РФ;
Новостной продюсер BitNovosti - первого в России новостного портала о блокчейн; 
Директор HOQU;
Представитель ICOBOX;
CEO of IP Center SKOLKOVO в Фонд "СКОЛКОВО". 
Где?

МОСКВА, Берсеневская набережная, д. 6, строение 3.
Предусмотрена он-лайн трансляция. 
Когда?
16 декабря 2017 , с 10:30 и пока у вас хватит сил. 
Как попасть?
Заказывайте билеты здесь. 
Вопросы задавайте сюда info@blockchainmania.ru, 8 (495) 266-60-85.
Плюшки
Во время конференции предусмотрены кофе-брейк и обед. 
После официальной части можно продолжить общение на afterparty. Внимательно выбирай билет! 

NB! Успей купить по обычной цене до 1 декабря.

**Comment by wbnns** [comment]
@sergiietsmaksym Hello, it looks like the website for this event hasn't been set up yet:

![image](https://user-images.githubusercontent.com/1130872/33643711-86fd8b6c-da06-11e7-9622-8a0c912a00da.png)

Please let us know once it has and we can reconsider adding the event.
