### ISSUE TITLE
Redesign-related Meta

### ISSUE THREAD

**Issue by Cobra-Bitcoin** [bitcoin-dot-org/bitcoin.org#1953]
We picked a proposal from Ethworks (https://dribbble.com/ethworks) to redesign bitcoin.org, the project is split into three phases, with the first phase being the creation of **_three_** concept redesigns of our landing page, the second phase is a redesign of 10 of the most important subpages + tablet/mobile responsive design of the selected landing page, and the final phase being actual HTML + CSS implementation into the current codebase of the site.

This is a discussion to justify the expenditure for the cost of phase 1 (**$4000**). By going through with phase 1, we aren't committing ourselves to phase 2 or 3, but if the community is impressed with the work (the concepts will be presented publicly and critiqued on Reddit/Twitter/Github), we can discuss proceeding further with the project. The current site looks dated and the community hasn't ever been presented with a competent, modern and fresh alternative.

We currently have over $100k collected in donations for use to improve the site, the cost for phase 1 represents a very small portion of our money, and the discussion sparked by having the community see and critique three new professional designed landing pages and the possibility of further redesign work is well worth the cost.

Thoughts?

**Comment by thejohnha** [comment]
It would be nice to know what competing alternatives exist for the organization. In other words, are there other initiatives that could be higher priority than a redesign of the landing page? Are the other sections of the site feature complete?

If there were a list of competing projects, ideally aligned with an overall strategy document, it would be easier to choose and prioritize the allocation of capital.

Another question could be, what should the annual expenditure budget be? Even though there is no interest on the balance, there are price appreciation and perhaps future bitcoin forks to consider. In that light, should there be any thought given to limiting spending now to allow for greater spending power in the future? Is a 4% expenditure on a landing page re-design the best use of capital, or should we look for other metrics to help us budget appropriately? What do other endowments consider prudent in terms of annual spending?

Also, is there a balance of bitcoin cash or bitcoin gold in conjunction with the bitcoin balance? If so, should that spending power be considered?

Just a few things that came to mind. Thanks for starting the conversation!

**Comment by kuzzmi** [comment]
Generally, I'm all in for redesign, but that "we picked a proposal" just doesn't feels okay for me for some reason. Were there any other companies/designers/developers who made proposals that were declined afterwards?

**Comment by Cobra-Bitcoin** [comment]
@kuzzmi I had a whole bunch of companies that showed interest on this Tweet: https://twitter.com/CobraBitcoin/status/931507531784048640. I talked to a lot of them and looked through their work, but Ethworks looked the most promising so I chose to focus on working with them based on their portfolio.

@thejohnha Expenditure is very limited, and any future expenditure would have to be discussed on Github and justified, and at the time of writing, there's only this expenditure, a $5000 sponsorship for Kyle Torpey, and some open bounties that are planned/discussed for the near future.

**Comment by kuzzmi** [comment]
OK, now it feels right. The only concern I still have is the final cost if the first phase only is 4k, apart from that, I think it should be a good investment.

As a side note, I have some spare time, so will also do a few concepts for practicing. I'm definitely not on par with that studio, but it would be nice to have more options in the end.

**Comment by Aristaa** [comment]
All,

Thank you for your interest and support.  It is important that I
also review all proposals before any and all final decisions are made. This
is critcal to our missions continued success. At times it is best to grow
slowly and organically. This allows for contemplation and reflection which
are critical for future and continued growth.  Perhaps a more sound
investment in the first phase will pay dividends in the long run. Rest well
and "Do Less". Then let's review some concepts.

**Comment by wbnns** [comment]
Here's a [link to the proposal](https://www.dropbox.com/s/b2efr2ywd8gtb7w/Bitcoin.org-Estimation.pdf?dl=0) in case anyone would like to review.

I agree with @Cobra-Bitcoin that the site looks dated (others have mentioned this as well) and think that there is room for improvement. Also, that we have sufficient funds at the moment that we could put towards updating the design of the site.

My main initial concern with this particular proposal is that we would essentially be paying ~$4000 for 3 designs of one web page, [the home page](https://bitcoin.org/). There are many other pages on Bitcoin.org, and since they won't match this new proposed design, this creates a bit of a price commitment to move forward into paying for designs of the other pages as well (in other words, I suspect this would end up being much more than $4000, before we're done).

That said, if people would like to pursue this proposal, I am happy to set up regular meetings to manage the effort with ETHworks, and report back here (others are welcome to join the meetings as well) so that we can strive to reach the best possible outcome.

**Comment by achow101** [comment]
I'm not sure whether we really need a redesign. I think the site is fine as it is, maybe a few things could be rearranged.

> others are welcome to join the meetings as well

Where will these meetings be held and how can one join them?

**Comment by Vishesh-Gupta** [comment]
Hey everyone, I actually like the @cobra-bitcoins proposal of a new website design. I do feel like there are many new technologies out there which can help us redesign the website and make it more user friendly and add more functionality to it. I would like to join and help for redesigning and development. Also i would suggest that since @wbnns was saying on three designs for one home page why don't we rather make one website but after doing a poll with the community for whichever design they like if we have a set design. For the development part, their are i think better ways of doing it and cheaper ways too. Like creating a bounty for small tasks and keeping it open source can help a lot and make it cheaper i guess. It will also give exposure to developers in community for web and our work of redesigning a website will also be completed. It might take a few weeks but the outcome might be nicer and cheaper.

**Comment by Cobra-Bitcoin** [comment]
The three redesigns are sort of just to get the ball rolling on the redesign process. It'll spark discussion and we can get lots of feedback from the community on which one they like and why and incorporate the good feedback into further redesigns of other pages.

It would be a little weird for us to collect all this money and not at least attempt to make the site look more modern. We aren't compelled to actually implement the redesign, maybe it turns out the 3 concept designs produced aren't liked by anyone, but it's worth trying because nobody has ever seen a professional redesigned homepage before. The site really looks like it's stuck in 2013. You can compare our landing page to modern ones and you'll see that we're really falling behind: https://dribbble.com/search?q=landing+page.

How about we just spend the $4000, see how the 3 new concept redesigns of our homepage turn out, and then decide if it's worth going ahead with phase 2 and 3? It would be really nice to just see the site in a different light for once.

**Comment by Vishesh-Gupta** [comment]
@Cobra-Bitcoin  I totally agree with it.

**Comment by wbnns** [comment]
I'm OK with giving this a shot to see what can be accomplished in the first phase.

@achow101 There haven't been any additional meetings scheduled, yet, but I imagine they would most likely be Google Hangouts.

**Comment by Cobra-Bitcoin** [comment]
OK, lets give this until Sunday the 10th for more discussion. The general consensus seems to be to start phase 1 and see what can get accomplished. 

Unless other contributors come into the discussion and are significantly against it, we can start next week on talking to Ethworks more about phase 1 and trying to get the ball rolling.

**Comment by htmelvis** [comment]
Are they going to provide any documentation about the overall scope of what they are going to do? Make sure that the proper care is taken to preserve existing urls, etc. to be sure that when it is redesigned they don't throw the current search rankings out the window, especially when there is a bitcoin.com that is just waiting to out perform this site on certain key phrases in search.

**Comment by wbnns** [comment]
@htmelvis 

Hello, yes and agreed. We've already mentioned this to them because it's a top priority.

**Comment by wbnns** [comment]
I've emailed Natalia from ETHworks to set up a kick off meeting to discuss getting started on Phase 1. I'll post the time here as soon as I have it, for those who would like to attend.

Also, I've set up a [project board](https://github.com/bitcoin-dot-org/bitcoin.org/projects/1) that we can use, once we have the meeting, where we can keep track of everything related to Phase 1 and collaborate together.

**Comment by wbnns** [comment]
A meeting with ETHworks has been scheduled for tomorrow (Friday, December 15th) at 15:00 UTC.

We'll be meeting here, for those who would like to join:
https://appear.in/bitcoin.org

**Comment by kuzzmi** [comment]
@wbnns, great stuff! I'd love to participate, though AFAIK, there are limitations on appear.in for the amount of concurrent connections, being 4 on a free tier. Hopefully I'll make it through.

**Comment by wbnns** [comment]
@kuzzmi Heya! It's not on the free tier; more people can join. 👍

**Comment by wbnns** [comment]
For those interested, remaining / specific todos relating to the redesign are available [here](https://github.com/bitcoin-dot-org/bitcoin.org/projects/1).
