### ISSUE TITLE
INVITATION ONLY CRYPTO CURRENCY CONFERENCE

### ISSUE THREAD

**Issue by ARMANDROUSSO1** [bitcoin-dot-org/bitcoin.org#1957]
INVITATIONS POUR UN COCKTAIL - RÉCEPTION - CONFÉRENCE SUR LES BITCOINS, CRYPTO-MONNAIES, MONNAIES VIRTUELLES... 
LE MERCREDI 13 DÉCEMBRE 2017 DE 19H À 22H AUX SALONS HOCHE.
IL NE RESTE PLUS QUE 100 PLACES OUVERTES ! 
INSCRIVEZ-VOUS VITE À  
L'E-MAIL INDIQUÉ: HocheCryptoConference2017@gmail.com

**Comment by wbnns** [comment]
@ARMANDROUSSO1 Hello, apologies, we'd need a website URL before we can consider adding this.
