### ISSUE TITLE
World Blockchain Summit Nairobi

### ISSUE THREAD

**Issue by arifaraj** [bitcoin-dot-org/bitcoin.org#1961]
- date: 2018-03-22
      title: "World Blockchain Summit Nairobi"
      venue: ""
      address: ""
      city: "Nairobi"
      country: "Kenya"
      link: "https://www.nairobi.worldblockchainsummit.com/"

**Comment by wbnns** [comment]
@arifaraj Hello, could you please resubmit this once a venue and address is available? Both are needed in order to add the event.
