### ISSUE TITLE
Adding BTC.com back 

### ISSUE THREAD

**Issue by AlejandroDeLaTorre** [bitcoin-dot-org/bitcoin.org#1964]
Hi all,

The team and I would very much like to be re-added to bitcoin.org. We are proud to announce that we recently added support for SegWit across our wallet and API platform, ahead of many other wallets.

We will continue to strive to provide the best multi-platform wallet technology for Bitcoin.
Please let us know which steps we need to take to get re-added to bitcoin.org.

- BTC.com

**Comment by crwatkins** [comment]
I recommend submitting a PR to create the listing.  Please note that your logo and screen shot is still in the repository, so you can use those unless you want to update them.  I would support that PR.

**Comment by Nelsonyaru** [comment]
No, because BTC.COM is NOT one minion of Blockstream.
