### ISSUE TITLE
Bitcoin & Blockchain Meetup

### ISSUE THREAD

**Issue by flywithakin** [bitcoin-dot-org/bitcoin.org#1972]
- date: 2018-01-21
      title: Cryptocurrency & Blockchain
      venue: IBETO HOTEL
      address: Along Gudu District Apo
      city: Abuja, NG
      country: Nigeria
      link: http://eventbrite.com/bitcoin

**Comment by wbnns** [comment]
@flywithakin 

Hello, the link provided for this event is broken. Could you please resubmit with a corrected link?
