### ISSUE TITLE
BitcoinFest.io - Pre ICO 30 Jan

### ISSUE THREAD

**Issue by bitcoinfest** [bitcoin-dot-org/bitcoin.org#1984]
- date: 2018-01-30
      title: "Bitcoin Festival - Pre ICO 30 Jan"
      venue: "World"
      address: "Buenos Aires,New York,Barcelona"
      city: "Buenos Aires"
      country: "Argentina"
      link: "BitcoinFest.io"

**Comment by luke-jr** [comment]
Looks like a scam?

**Comment by bitcoinfest** [comment]
Hello how are you ? not at all, all the projects nowadays are technological, we thought of raising funds for this event. regards

**Comment by htmelvis** [comment]
Def. spam, no specific information and a 404 on the "whitepaper"

**Comment by bitcoinfest** [comment]
Hello how are you?

http://bitcoinfest.io/whitepaperEN.pdf
http://bitcoinfest.io/whitepaperES.pdf
