### ISSUE TITLE
Suggested content for ETHworks home page redesign

### ISSUE THREAD

**Issue by wbnns** [bitcoin-dot-org/bitcoin.org#1990]
@marekkirejczyk @natiwa

I've created this issue where we can discuss content for the home page. I suggest we use a data-driven approach to determine ideally what should be on the page.

In the last six months, there have been over 56,000,000 visits to Bitcoin.org. Here are the pages, ranked by traffic that people have visited:
https://www.dropbox.com/s/98w4908cqf91thg/bitcoindotorg-top-page-last-six-months.pdf?dl=0

Some observations:
+ The homepage is the most visited page.
+ There are many international users who come to Bitcoin.org, as indicated by the page titles that aren't in English (the site displays natively in their own language).
+ After the homepage, the Getting Started, Choose Your Wallet, Buy, Exchanges, and Download pages are the most visited pages by English speakers
+ For non-English speakers, the Getting Started and Choose Your Wallet pages are visited by many Korean and Russian users
+ It would be helpful to show the real-time bitcoin price on the Bitcoin.org homepage, creatively, perhaps in the header - open to your suggestions

Important: We don't want to lose search engine rankings, so it's important that we don't drop any of the pages that are currently linked to in the header and footer from the existing [homepage](https://bitcoin.org) on Bitcoin.org. This is not to say that the header and footer navigation can't be refreshed though.

**Comment by achow101** [comment]
I think the home page should include the "Choose your wallet" page. That is one of the most frequently visited pages and often times people are referred there when asking about what wallet to use. IMO it is one of Bitcoin.org's most important pages. However it is currently not easily accessible from the home page, and for a redesign, I think it would be good to have it easily accessible from the home page.

**Comment by crwatkins** [comment]
@achow101 I can agree with that (but I probably didn't have to point it out).

**Comment by wbnns** [comment]
Agreed. We talked about this in the meeting on Friday - that the homepage should help people more efficiently connect with the current top pages that people are already visiting (the "Choose your wallet" page was one of them).

**Comment by wbnns** [comment]
@marekkirejczyk @natiwa

Do you all need anything else from us or is the above sufficient for getting started next week?

**Comment by natiwa** [comment]
@wbnns Is that all form the suggested content? If yes, then I think we're fine.

**Comment by wbnns** [comment]
@natiwa Yes, thanks - specifically we want to look to your expertise of paying attention to what are currently the most visited pages after the home page ([as mentioned in this comment](https://github.com/bitcoin-dot-org/bitcoin.org/issues/1990#issue-282438354)) and how the new home page can be used to help visitors connect with the info on the site that is being viewed the most, with better efficiency.

**Comment by natiwa** [comment]
Hi, The link to the dropbox is no longer available. https://www.dropbox.com/s/98w4908cqf91thg/bitcoindotorg-top-page-last-six-months.pdf?dl=0

**Comment by wbnns** [comment]
@natiwa 

Hello, [here's an updated link](https://www.dropbox.com/s/dfcdkx2soyvqkzr/bitcoindotorg-top-page-last-six-months.pdf?dl=0).
