### ISSUE TITLE
Draft and execute agreement w/ ETHworks detailing terms for redesign project

### ISSUE THREAD

**Issue by wbnns** [bitcoin-dot-org/bitcoin.org#1993]
@marekkirejczyk @natiwa

Can you please draft an agreement with payment terms? 

Also, we want to make sure that it is agreed that as part of the project, all interest and ownership in intellectual property belongs to Bitcoin.org - could you please make sure there is a clause for that, too, that we can review?

Thanks!

**Comment by wbnns** [comment]
@marekkirejczyk @natiwa

Also, an additional note - let's make sure as part of the agreement that the work you all do, upon each payment, inherits/adopts the following Creative Commons license: https://creativecommons.org/publicdomain/zero/1.0/

**Comment by natiwa** [comment]
Hi,

@wbnns  Thank you for our last conversation. It was nice to meet you.

Please take a look at our contract. https://docs.google.com/document/d/1qbxh26qhL_nYo-xlkPiNyWE74lI8hoXcYLbXXr3nKJ0/edit?usp=sharing

You are free to leave your comments there. 

Thanks!

**Comment by Roy19833** [comment]
Hello! I wanna know more. Do you want contact
Verzonden vanuit Outlook
________________________________
Van: Natalie Kirejczyk <notifications@github.com>
Verzonden: maandag 18 december 2017 03:45:50
Aan: bitcoin-dot-org/bitcoin.org
CC: Subscribed
Onderwerp: Re: [bitcoin-dot-org/bitcoin.org] Draft and execute agreement w/ ETHworks detailing terms for redesign project (#1993)


Hi,

@wbnns<https://github.com/wbnns> Thank you for our last conversation. It was nice to meet you.

Please take a look at our contract. https://docs.google.com/document/d/1qbxh26qhL_nYo-xlkPiNyWE74lI8hoXcYLbXXr3nKJ0/edit?usp=sharing

You are free to leave your comments there.

Thanks!

**Comment by wbnns** [comment]
@natiwa 

This looks great, thanks for putting this together. I added some comments to the document (as well as the information you requested).

Could you also please add a clause that you all will maintain the [work log](https://docs.google.com/spreadsheets/d/1JzAzh0qAJv2S068GokAS2KSfhz5XDhx78wd3jsxUXoI/edit?usp=sharing) for any time that is being logged, and that you all will be paid on a weekly basis?

Once that's done - let's get this executed within the next week so that you all can start the first week in January, as we discussed (once the holidays are over and you all have finished with previous work you're completing).

**Comment by natiwa** [comment]
@wbnns 

Thanks. I'll take care of this tomorrow. 

Talk to you soon.

**Comment by natiwa** [comment]
The contract has been improved. Please take a look at it and let me know if you have any additional comments.

Have a great and peaceful Christmass.

**Comment by wbnns** [comment]
@natiwa 

Thanks! I saw the updates and emailed you the signed document. Could you all please execute and return it? Once you do I'll move this to complete.

Looking forward to getting started next week.

**Comment by wbnns** [comment]
Closing this issue - [received fully executed agreement](https://www.dropbox.com/s/0c1nj9q0qie6yoi/Signed-Ethworks-Bitcoin.pdf?dl=0).
