### ISSUE TITLE
Need logo in SVG or EPS format

### ISSUE THREAD

**Issue by wbnns** [bitcoin-dot-org/bitcoin.org#1994]
@marekkirejczyk @natiwa

I will get this for you so you have a copy.

**Comment by natiwa** [comment]
Please, keep me updated.

**Comment by harding** [comment]
FYI: there's an SVG version of the logo with some extra text here: https://github.com/harding/meta.bitcoin.org/blob/master/logos/bitcoin.org-logo.svg

**Comment by natiwa** [comment]
Thank you!

**Comment by wbnns** [comment]
@harding Thanks!
