### ISSUE TITLE
Global Blockchain Summit

### ISSUE THREAD

**Issue by Crafty-Gurl** [bitcoin-dot-org/bitcoin.org#1997]
- date: 2018-04-19/20
      title: "Global Blockchain Summit"
      venue: ""
      address: ""
      city: "Denver, CO"
      country: "USA"
      link: "https://globalblockchainsummit.com/pr"

**Comment by wbnns** [comment]
@Crafty-Gurl 

Hello, could you please resubmit this once a venue and address are available? Both are needed in order to add the event.
