### ISSUE TITLE
Blockchain & Bitcoin Conference India

### ISSUE THREAD

**Issue by ElenSh** [bitcoin-dot-org/bitcoin.org#2000]
- date: 2018/02/22
      title: "Blockchain & Bitcoin Conference India"
      venue: "Bengaluru, India"
      city: "Bengaluru"
      country: "India"
      link: "https://goo.gl/JZDKKL"

**Comment by wbnns** [comment]
@ElenSh 

Hello, we need a venue and address before we can add this. Please let us know once you have it and we can add this event to the site.
