### ISSUE TITLE
BitGo wallet links breaking

### ISSUE THREAD

**Issue by Cobra-Bitcoin** [bitcoin-dot-org/bitcoin.org#2018]
All the installation links on the BitGo wallet are broken: https://bitcoin.org/en/wallets/desktop/windows/bitgo/.

@jlopp Are there any new links we can use instead? Or do you think it's better if we just remove the wallet?

**Comment by jlopp** [comment]
Looks like the Windows / Mac / Linux links are all for the BitGo Chrome App for which we have discontinued support; I'd just remove those options and leave the web wallet.

**Comment by crwatkins** [comment]
Thanks @jlopp, Could you or @bpdavenport (who submitted the Chrome app PR) submit a PR to correct the listing?  Thanks!

**Comment by wbnns** [comment]
@Cobra-Bitcoin 

Thanks for catching this. Fixed with #2024.
