### ISSUE TITLE
Blockchain Economic Forum

### ISSUE THREAD

**Issue by roma-latoken** [bitcoin-dot-org/bitcoin.org#2023]
- date: Feb 4-6, 2018
      title: "Blockchain Economic Forum"
      venue: "TBD"
      address: "TBD"
      city: "Singapore"
      country: "Singapore"
      link: "https://bef.latoken.com"

**Comment by wbnns** [comment]
@roma-latoken 

Hello, please resubmit this once a venue and address are available. Both are needed in order to add this event to the site.
