### ISSUE TITLE
CreateNewBlock: TestBlockValidity failed: bad-fork-prior-to-checkpoint (code 67)

### ISSUE THREAD

**Issue by yashmoda** [bitcoin-dot-org/bitcoin.org#2032]
I uninstalled bitcoin core and removed all the data of my previous wallet and the .bitcoin folder. On reinstalling bitcoin core and generating blocks, I get the above error.

**Comment by wbnns** [comment]
@yashmoda 

Hello, apologies, this repository is for issues related directly to Bitcoin.org. For Bitcoin Core-related support, here are some links to forums where you can connect with others who may be able to help you: https://bitcoin.org/en/bitcoin-core/help#forums
