### ISSUE TITLE
Confusion regarding the last image in the Transaction section of the docs.

### ISSUE THREAD

**Issue by joaojoyce** [bitcoin-dot-org/bitcoin.org#2039]
Source File: _data/devdocs/en/guides/transactions.md

In this section (https://bitcoin.org/en/developer-guide#transactions) I always have a hard time understanding the last image (caption: "Some of the data signed by default"). 

There are four types of arrows and lines:
1) Arrows that cross the "Signed Data" block mean that the data is signed and inserted in the next transaction.
2) Arrow that start in the "Signed Data" block and end in the transaction represent that all the signed data is inserted in the new transaction.
3) The pointer that goes from the "Pubkey Script" of Tx1 and ends in the "Signed Data" block means that the Pubkey is signed but not inserted in the new transaction.
4) There is also the dashed line meaning that the private key is used to sign the data.

I was wondering if this image causes confusion for anyone else and if it could be improved.

I really love the guides. Thanks!

**Comment by wbnns** [comment]
Hello, thanks for the feedback. Closing this for now since it's been several months, without further comment.
