### ISSUE TITLE
Blockchain Economic Forum 2018

### ISSUE THREAD

**Issue by roma-latoken** [bitcoin-dot-org/bitcoin.org#2040]
- date: 2018-02-04
      title: "Blockchain Economic Forum 2018"
      venue: "Suntec Singapore International Convention and Exhibition Centre"
      address: "1 Raffles Boulevard, Suntec City"
      city: "Singapore"
      country: "Singapore"
      link: "https://bef.latoken.com/"

**Comment by wbnns** [comment]
Duplicate of #2040
