### ISSUE TITLE
Bitcoin and Cryptocurrencies Workshop

### ISSUE THREAD

**Issue by shr-esmaeilzadeh** [bitcoin-dot-org/bitcoin.org#2042]
- date: 04-01-2018
  title: "Bitcoin and Cryptocurrencies Workshop"
  venue: "Industrial Management Institute of Iran "
  city: "Tabriz"
  country: "Iran"
  link: "http://www.imiazar.ir/news-and-announcements/418-registering-a-specialized-workshop-on-digitization-and-bitcoin-for-new-investments"

**Comment by wbnns** [comment]
@shr-esmaeilzadeh Hello, it looks like the date for this event was in December (not in January), therefore, it has already passed. Thanks anyway, though, for the contribution!
