### ISSUE TITLE
Protocol version needs to be updated

### ISSUE THREAD

**Issue by okeygo** [bitcoin-dot-org/bitcoin.org#2043]
[Bounty](https://github.com/bitcoin-dot-org/bitcoin.org#earn-bitcoin-for-contributing): **25,000 bits / ~$200 USD**

Table shows incorrect data in this link: [developer-reference#protocol-versions](https://bitcoin.org/en/developer-reference#protocol-versions)

Submitting issue as requested in the same paragraph.

**Comment by wbnns** [comment]
@okeygo Thanks, yes, this needs to be updated with the release of new versions, where applicable.

**Comment by cornelius** [comment]
With #3063 the version should now be up to date and reflect the one in the latest Bitcoin Core implementation.

I think it's good to mention the version for which it has been checked explicitly to avoid the false impression that something hasn't changed in a later version if it's only the documentation not being  updated.

**Comment by wbnns** [comment]
Unless others object, this issue will be closed on Friday, August 16th.

**Comment by wbnns** [comment]
@cornelius 

Would you like the bounty sent to the bitcoin address on your Keybase? If not, just let us know an alternative destination. Thanks for the help.

**Comment by cornelius** [comment]
> Would you like the bounty sent to the bitcoin address on your Keybase? If not, just let us know an alternative destination. Thanks for the help.

Yes, the keybase address is fine. Thanks.
