### ISSUE TITLE
Update exchanges list

### ISSUE THREAD

**Issue by Pannuba** [bitcoin-dot-org/bitcoin.org#2047]
Postebit (https://posteb.it) and Bitsewa (https://bitsewa.com), both listed in the [Exchanges](https://bitcoin.org/en/exchanges) page, seem to be down.

Also, is there any reason why Coinbase and/or GDAX are not listed?

EDIT: Coinmama (https://coinmama.com), an international exchange, could be added as well.

**Comment by Cobra-Bitcoin** [comment]
Coinbase got removed because of their support for 2X.
