### ISSUE TITLE
Global Blockchain Conference 2018

### ISSUE THREAD

**Issue by abrarbaba** [bitcoin-dot-org/bitcoin.org#2052]
- date: 2018-05-07
      title: "Global Blockchain Conference 2018"
      venue: "THE RITZ CARLTON"
      address: "DUBAI"
      city: "DUBAI"
      country: "UAE"
      link: "https://www.fb-research.com/events/details/global-blockchain-conference-2018"

**Comment by wbnns** [comment]
@abrarbaba Hello, this links to a login page with no information about the event; we wouldn't be able to add this as-is.
