### ISSUE TITLE
Blockchain Innovation Showcase 

### ISSUE THREAD

**Issue by challengeadvisory** [bitcoin-dot-org/bitcoin.org#2053]
- date: 2018-01-30
      title: "Blockchain Innovation Showcase"
      venue: "Pullman Hotel"
      address: "Euston Road, Kings Cross"
      city: "London"
      country: "United Kingdom"
      link: "https://www.challenge.org/events/"

**Comment by wbnns** [comment]
@challengeadvisory Hi - do you have a web page with information about this event, instead of a PDF file? If so, please let us know the link so we can review it in order to potentially add this.
