### ISSUE TITLE
LIVE Bitcoin Seminar

### ISSUE THREAD

**Issue by meckjohnson** [bitcoin-dot-org/bitcoin.org#2054]
March 3, 2018
   LIVE Bitcoin Seminar
   Atlanta Marriott Marquis
   265 Peachtree Center Avenue
   Atlanta, GA 30303
   United States
   http://atlbitcoin2018.eventbrite.com

**Comment by wbnns** [comment]
@meckjohnson Hello, thanks for submitting this, however, it looks like there are no more spaces available for people to be able to attend this event. We wouldn't be able to add it to the website.

**Comment by meckjohnson** [comment]
Hi Will,

Registration is still available. I hope you can still have our event
added to your calendar. The final sales date had been entered
incorrectly. It should have been March 2nd instead of February 2nd.
Please feel free to contact me directly at the number listed below.
Thanks in advance for your assistance!

Warm Regards,

---
Meck Johnson, Event Manager
Design Media, Inc.
404.857.0028
meck@designmediainc.com 

On 2018-02-03 07:24, Will Binns wrote:

> @meckjohnson [1] Hello, thanks for submitting this, however, it looks like there are no more spaces available for people to be able to attend this event. We wouldn't be able to add it to the website. 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].
 

Links:
------
[1] https://github.com/meckjohnson
[2]
https://github.com/bitcoin-dot-org/bitcoin.org/issues/2054#issuecomment-362802402
[3]
