### ISSUE TITLE
Fix link pull requests

### ISSUE THREAD

**Issue by Tusharchoudhary** [bitcoin-dot-org/bitcoin.org#2057]
https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/docs/contributing-to-developer-documentation.md
the hyperlink on 'pull request' redirects to the same page.

I feel it should direct here - https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/docs/working-with-github.md

**Comment by wbnns** [comment]
@Tusharchoudhary Thanks for reporting this.
