### ISSUE TITLE
比特幣週聚｜Bitcoin Happy Hour

### ISSUE THREAD

**Issue by EthereumD** [bitcoin-dot-org/bitcoin.org#2062]
- date: 2018-1-10
      title: "比特幣週聚｜Bitcoin Happy Hour"
      venue: "LE BLE D'OR , 金色三麥"
      address: "忠孝東路七段299號 115台北市南港區 "
      city: "Taipei,台北市"
      country: "Taiwan"
      link: "https://www.meetup.com/Taipei-Bitcoin-Meetup-Group/events/246547295/"

**Comment by Roy19833** [comment]
Verzonden vanuit Outlook
________________________________
Van: EthereumD <notifications@github.com>
Verzonden: maandag 8 januari 2018 06:06:03
Aan: bitcoin-dot-org/bitcoin.org
CC: Subscribed
Onderwerp: [bitcoin-dot-org/bitcoin.org] 比特幣週聚｜Bitcoin Happy Hour (#2062)


- date: 2018-1-10
  title: "比特幣週聚｜Bitcoin Happy Hour"
  venue: "LE BLE D'OR , 金色三麥"
  address: "忠孝東路七段299號 115台北市南港區 "
  city: "Taipei,台北市"
  country: "Taiwan"
  link: "https://www.meetup.com/Taipei-Bitcoin-Meetup-Group/events/246547295/"
