### ISSUE TITLE
World Blockchain Summit

### ISSUE THREAD

**Issue by arifaraj** [bitcoin-dot-org/bitcoin.org#2063]
- date: 2018-03-22
      title: "World Blockchain Summit"
      venue: ""
      address: ""
      city: "Nairobi"
      country: "Kenya"
      link: "https://www.nairobi.worldblockchainsummit.com/"

**Comment by wbnns** [comment]
@arifaraj Hello, the website for this event doesn't appear to be working, and the submission is missing an address and venue. We'd need these three issues to be resolved before we can consider adding this to the site.
