### ISSUE TITLE
Hand this domain over to the real Bitcoin community.

### ISSUE THREAD

**Issue by Nelsonyaru** [bitcoin-dot-org/bitcoin.org#2064]
Sad to see this domain is used/hacked by some bad actors to pump Bitcoin Segwit Coin, instead of the real Bitcoin. 

Worse, the webmaster of bitcoin.org intentionally uses the description of Bitcoin, and the name of Bitcoin, to tout its Bitcoin Segwit Coin by misleading newbies out of bad will.

I have responsibility to warn the admin of bitcoin.org that impersonation is immoral. Yes I know it's too high a standard for him/her. So I was forced to report this abuse to ICANN.

Time to hand this domain over to the real Bitcoin community.

Bitcoin is Bitcoin, Bitcoin Segwit Coin is Bitcoin Segwit Coin. HUGE difference..

**Comment by Nelsonyaru** [comment]
Wow? This issue was closed before any talk was involved.

So the webmaster of bitcoin.org decides to continue misleading newbies. It's evil.

**Comment by robgraeber** [comment]
Bitcoin cash is the forked blockchain, trying to hijack the name of the project BCH forked is :rofl:

**Comment by kinsi55** [comment]
Sorry for being so direct, but are you retarded?
