### ISSUE TITLE
How to run bitcoin core daemon?

### ISSUE THREAD

**Issue by Kazu0den** [bitcoin-dot-org/bitcoin.org#2073]
Hi All,

I am new to Bitcoin and tried to install and run bitcoin core daemon but it seems that i got stuck when getting to the cmd?
Anyone can help?

![bitcoin daemon cmd error](https://user-images.githubusercontent.com/35217872/34906917-15a68a10-f8a9-11e7-8743-05ef1b5e9d05.jpg)

**Comment by wbnns** [comment]
@Kazu0den Hello, here's a link to forums where you can connect with others who may be able to offer technical support regarding your issue: https://bitcoin.org/en/bitcoin-core/help#forums
