### ISSUE TITLE
Blockchain & Cryptocurrency Con 2018

### ISSUE THREAD

**Issue by finid** [bitcoin-dot-org/bitcoin.org#2074]
- date: 2018-02-22
      title: "Blockchain & Cryptocurrency Con 2018"
      venue: "Addison Conference & Theatre Centre"
      address: "15650 Addison Rd."
      city: "Addison"
      country: "USA"
      link: "https://blockchain-conf.com"

**Comment by Bang631** [comment]
2018-01-14 12:48 GMT+07:00, finid <notifications@github.com>:
>     - date: 2018-02-22
>       title: "Blockchain & Cryptocurrency Con 2018"
>       venue: "Addison Conference & Theatre Centre"
>       address: "15650 Addison Rd."
>       city: "Addison"
>       country: "USA"
>       link: "https://blockchain-conf.com"
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/bitcoin-dot-org/bitcoin.org/issues/2074


-- 





SocTrang2016SocTrang
