### ISSUE TITLE
Full nodes vs Miners. What is the difference? 

### ISSUE THREAD

**Issue by vlgk** [bitcoin-dot-org/bitcoin.org#2079]
Guys, could you please specify the difference between full node and miner in your article "Running a full node"  https://bitcoin.org/en/full-node. There are a lot of discussions and opinions in internet, but it seems logical to have official description in your article in the first part.  
Thank you in advance.     
PS The most questionable points are whether miners are full nodes too or not, if yes why there is the need in full nodes too.

**Comment by NotCobra** [comment]
There are three kind of full nodes; Mining nodes (MN), nodes run by merchants, nodes run by normal users as wallet (NU).

For the network, only mining full nodes matter. Miners are incentivized by the Bitcoin network to run full nodes, and they are responsible for verifying transactions for the network.

Full nodes are useful for some big merchants. One use case is to accept zero confirmation safely. Such nodes contribute nothing to the network.

Running full nodes are very dangerous for normal users and contributes nothing to the network. For example, hackers can easily know your IP and find your computer on the internet. By running nodes or some other ways, normal users can verify transactions for himself, yet the Bitcoin network doesn't care.

Normal users had not been expected to run full nodes until Blockstream was founded. After the formation of that cartel, this propaganda that everyone should run full nodes suddenly was spread under censorship. Yes it's illogical and ridiculous, and with common sense will you see through such stupid lies easily. However, the censorship was so effective.

**Comment by NotCobra** [comment]
@vlgk That's not "opposite opinion". Actually, it's an echo of the propaganda.

Like any other propaganda existed in the history of human beings, you can **easily** find the logical fallacy no matter how hard they twist the facts.

Let's take the link you provided as an example.

Beyond long and tedious nonsense, this is what that guy actually made as a premise.

> This (the nodes running by end users) is what keeps the network honest.

This is a blatant lie. So that guy proved that propaganda with this lie.

**Comment by vlgk** [comment]
@NotCobra  anyway, once again the only solution to stop such discussions or propaganda - write clear answer on bitcoin.org

**Comment by NotCobra** [comment]
@vlgk The only solution is to stick with truth, math, and logic. Frankly speaking, what the owner of bitcoin.org has done in past three years contradicts to everything Bitcoin stands for. Sorry for my frankness, but the harm has been done.

Not only must Justice be done; it must also be seen to be done.
