### ISSUE TITLE
SHA256 checksums for macOS doesn't mach signatures

### ISSUE THREAD

**Issue by yaakovgamliel** [bitcoin-dot-org/bitcoin.org#2087]
The current bitcoin-0.15.1-osx64.tar in the website has a sha256 of 037d7bdb787e18b4694c7eeb36422be6ef78b17240092b63483dda94b3af0a21, which does not match the signature b6771c5d67fb6b9c4882cc351e579470a008211d76407155e544b28b00fcd711 from the release signature file.

**Comment by wbnns** [comment]
@yaakovgamliel Hello, I checked the latest distribution and the signature matched:

![image](https://user-images.githubusercontent.com/1130872/39932818-6a6d8358-54fe-11e8-9bec-1dd6db20b43f.png)

**Comment by yaakovgamliel** [comment]
Great!, thanks for double checking
