### ISSUE TITLE
BLOCKCHAIN & CRYPTOCURRENCY IN EU. Prague

### ISSUE THREAD

**Issue by pkrugloff** [bitcoin-dot-org/bitcoin.org#2096]
- date: 2018-02-22
      title: "BLOCKCHAIN & CRYPTOCURRENCY IN EU."
      venue: ""
      address: ""
      city: "Prague"
      country: "Czech Republic"
      link: "http://lp.bcfgroup.eu/blockchain/"

**Comment by wbnns** [comment]
@pkrugloff Hello, thanks for adding this. We need a venue and address before we can potentially include this event on the site. If you have one, please let us know.
