### ISSUE TITLE
ppa repo unsecure on apt-get update

### ISSUE THREAD

**Issue by antekotarac** [bitcoin-dot-org/bitcoin.org#2097]
After executing:

sudo apt-add-repository ppa:bitcoin/bitcoin
sudo apt-get update

I get:

Updating from such a repository can't be done securely, and is therefore disabled by default.

**Comment by wbnns** [comment]
@antekotarac Hello, please reopen this on the [Bitcoin Core repository](https://github.com/bitcoin/bitcoin) so that they're aware and can take a closer look.
