### ISSUE TITLE
New Event

### ISSUE THREAD

**Issue by mykoolio** [bitcoin-dot-org/bitcoin.org#2101]
- date: 2018-05-08
      title: "BLOCFEST - Blockchain Festival & Conference "
      venue: "Shangri-la, Kuala Lumpur"
      address: "Kuala Lumpur, Malaysia"
      city: "Kuala Lumpur"
      country: "Malaysia"
      link: "www.blocfest.asia"

**Comment by wbnns** [comment]
@mykoolio 

Hello, this event page is a bit misleading. The homepage touts 20 speakers and has quotes from different people in the space with a call to action to buy tickets, however, on the speakers page, none of the people who are quoted on the homepage seem to be attending as speakers.
