### ISSUE TITLE
Select New Homepage Design

### ISSUE THREAD

**Issue by wbnns** [bitcoin-dot-org/bitcoin.org#2105]
Related Issues:

+ #1992
+ #2070
+ #2081
+ #2104

Once we've tallied up the community votes, we need to let @natiwa know which one we'd like to move forward implementing across the subpages.

**Comment by harding** [comment]
I haven't been following this project, so I'm sorry if this is on the wrong issue (I'm happy to move it).  On Reddit, @maaku made what I think was an insightful [comment](https://www.reddit.com/r/Bitcoin/comments/7ttlrx/vote_and_help_choose_bitcoinorgs_new_design/dtfvdgm/):

> All three [proposed designs] have a bitcoin price widget added. Don't do that. It (1) betrays the purpose of bitcoin development as an experimental peer to peer currency, and (2) potentially commercializes what should be a not-for-profit entity.
>
> Of all places, bitcoin.org should be the one website that isn't about the price, and you should be especially careful not to run afoul of major regulatory restrictions since those might impact developers associated with the project.

I thought this should be recorded (and, ideally, addressed) somewhere less ephemeral than Reddit.

**Comment by Cobra-Bitcoin** [comment]
Looks like version 3 is the winner: http://archive.is/gNaSi. Though the poll kept changing suddenly between version 1 and 3 the entire time.

**Comment by wbnns** [comment]
@harding Ok, thanks.
