### ISSUE TITLE
Lighthouse link is dead

### ISSUE THREAD

**Issue by rimas-kudelis** [bitcoin-dot-org/bitcoin.org#2107]
The [innovation page](https://bitcoin.org/en/innovation) has a link to the app called Lighthouse,but it seems dead. The server does not respond, and looking at [archive.org](https://web.archive.org/web/20170624063519/http://vinumeris.com:80/), it seems the page itself has been down since at least July 2017.

**Comment by wbnns** [comment]
@rimas-kudelis 

Nice catch, we'll fix this.

**Comment by Alhssan** [comment]
https://github.com/bitcoin/bitcoin/commit/3cf991756cf357b651c6415e3d950e5aa9d355ab#diff-87d0269770372470db215457bf5cdec7
