### ISSUE TITLE
DC Finance Family Office Conference: Investments into Cryptocurrencies

### ISSUE THREAD

**Issue by DCFinance** [bitcoin-dot-org/bitcoin.org#2109]
- date: 2018-04-25
      title: "DC Finance Family Office Conference: Investments into Cryptocurrencies"
      venue: "Reed Smith LLP, NYC"
      address: "599 Lexington Ave, New York, NY 10022"
      city: "New York"
      country: "United States"
      link: "http://thenycmeetings.com/"

**Comment by wbnns** [comment]
Duplicate of #2083
