### ISSUE TITLE
Block size

### ISSUE THREAD

**Issue by JulietDeltaSmirnoff** [bitcoin-dot-org/bitcoin.org#2110]
I believe BTC will perform better and be faster, if the block sizes are increased. I understand that the blocks were limited to 1MB in order to prevent multiple instances of a single action, when the network was still between a few hundred and a few thousand users. Currently it is a few million, and the backlog has put traders off using BTC as payment option. Which makes sense, because no-one wants to buy now and get paid later, nor pay now, pick up the burger and chips in three days' time.

Bitcoin started good currently it is losing its credibility as a payment system. Please, keep us from forcibly returning to the fiat currencies merely for the speed of payment.

Even lightning is considered not enough to heal the BTC network's woes.

**Comment by wbnns** [comment]
Thanks for sharing your feedback.
