### ISSUE TITLE
Banned

### ISSUE THREAD

**Issue by JessAnd** [bitcoin-dot-org/bitcoin.org#2111]
Hi guys,
I just tried to log in to see this response but system says I was banned. Apologies if I wrote something wrong/inappropriate, but I do believe this was either my honest mistake, or it was done in error. In any case could you please unblock my account?

Thank you very much, and wishing you the best.

Jessica
(JessAnd - screen name; forums@mizproservices.com - my email)

**Comment by wbnns** [comment]
@JessAnd Hello, we don't have a log in system that would ban accounts. Maybe try reaching out to the support team of the platform that displayed that message?
