### ISSUE TITLE
1st Global Crypto Online Summit

### ISSUE THREAD

**Issue by floriankandler** [bitcoin-dot-org/bitcoin.org#2117]
- date: 2018-02-10 to 2018-02-16
      title: "1st Global Crypto Online Summit"
      venue: "100% online at www.cryptario.com"
      address: "www.cryptario.com"
      city: "Online / worldwide"
      country: "Online / worldwide"
      link: "https://cryptario.com"

**Comment by wbnns** [comment]
@floriankandler 

Hello, apologies, the events page isn't set up to handle online-only events at the moment. It requires a physical location that can be referenced on the event map.
