### ISSUE TITLE
Trying to set up Bitcoin Core Having issues

### ISSUE THREAD

**Issue by Tyrant40** [bitcoin-dot-org/bitcoin.org#2127]
Hey, can I use a VPN or TOR to set up Bitcoin Core? I don't have access to the router or cable modem when I travel is there a way to still do the full node without the ability to open port 8333?

**Comment by wbnns** [comment]
@Tyrant40 Hello, here's a link to forums where you can connect with others who may be able to offer technical support regarding your issue: https://bitcoin.org/en/bitcoin-core/help#forums
