### ISSUE TITLE
Blockchain Innovation Showcase 

### ISSUE THREAD

**Issue by challengeadvisory** [bitcoin-dot-org/bitcoin.org#2134]
At Challenge Advisory, we believe that it is pivotal to provide our start-up clients with a platform on which they can deliver their value proposition to a captive audience of potential investors who can help take their ideas to the next level. Challenge Advisory Group will be hosting an innovation showcase in London on April 26, focused on the most exciting technological revolution since the Internet – Blockchain.

Our Blockchain Showcase will be an exclusive one-day event featuring the 10 most innovative start-ups we are currently collaborating with in this space. We will be providing this elite group of start-ups a unique platform to pitch their business to a specially curated group of VentureCaptial Investors from our network.

About Challenge Advisory

Challenge Advisory is a global strategic consultancy focused on working with people and organisations at the forefront of disruptive technological innovations across major industries. Our aim is to provide our clients with help to achieve measureable and sustainable results, moulding them into innovators and future leaders.

Find out more
https://www.challenge.org/events/

**Comment by wbnns** [comment]
@challengeadvisory 

Hello, please let us know when you have a direct link to a web page about this event and we can consider adding it to the site.
