### ISSUE TITLE
Implement Version 3 Across Subpages

### ISSUE THREAD

**Issue by wbnns** [bitcoin-dot-org/bitcoin.org#2139]
Related:

#2138
#2081

@natiwa

Let's use this issue to post the InVision comps as we work through each of the subpages (#2138). If there are any potential site-wide changes to the design that would be affecting all pages, let's discuss those in (#2081).

**Comment by natiwa** [comment]
Getting started wireframe 1: https://invis.io/2KFTP10TZ93#/279029567_Bitcoin-org__-_getting_Started
Getting started wireframe 2: https://invis.io/68FTP1H5ZVS#/279029566_Bitcoin-org__-_getting_Started_Ver_2

**Comment by Cobra-Bitcoin** [comment]
The second wireframe looks great, a lot more easier to follow.

**Comment by wbnns** [comment]
@natiwa 

I agree w/ @Cobra-Bitcoin - version 2 looks great. Can you please go ahead and transform the wireframe into the actual design? Let's see it on desktop, tablet and mobile. 

(Side note to @Cobra-Bitcoin - agreed, we don't need to do tablet and mobile compositions on every subpage, and only mobile ones in some cases - but we should do all of them on the first few to start - the most visited pages - so we have examples to reference/emulate when it comes time for development. It will save time and money by reducing room for error and/or revision due to subjective interpretation).

**Comment by natiwa** [comment]
Please take a look at this:

[Desktop](https://invis.io/SEFTVO5NQYV#/279074494_Bitcoin-org_-_Getting_Started_-Desktop), [Tablet](https://invis.io/26FTVNJC5AT#/279074493_Bitcoin-org_-Getting_Started_Tablet_768px), [Mobile](https://invis.io/PQFTVN15AG9#/279074492_Bitcoin-org_-Getting_Started_Mobile_320px)

**Comment by wbnns** [comment]
@natiwa 

Nice work, thanks. I left a few comments regarding the navbar and the jagged-edge effect.

**Comment by natiwa** [comment]
Links have been updated.

**Comment by natiwa** [comment]
[Choose your Bictoin wallet - wireframe](https://invis.io/QUFUHAD7KBS#/279267914_Bitcoin-org__-_Choose_Your_Bitcoin_Wallet)
[Wallet preview - wireframe ver 1](https://invis.io/FCFUHAZQP4V#/279267899_Bitcoin-org__-_Wallet_Preview_Ver_1)
[Wallet preview - wireframe ver 2](https://invis.io/TDFUHBEU5YS#/279267900_Bitcoin-org__-_Wallet_Preview_Ver_2)

**Comment by natiwa** [comment]
[How to buy Bitcoin](https://invis.io/MNFUJBDA5FE#/279286247_Bitcoin-org__-_How_To_Buy_Bitcoin)

**Comment by natiwa** [comment]
[Bitcoin exchange](https://invis.io/APFURLODGCF#/279356371_Bitcoin-org__-_Bitcoin_Exchanges)

**Comment by Cobra-Bitcoin** [comment]
Those wireframes look good, I prefer the first version of the wallet preview, looks a lot more interactive and cool.

Let's get these implemented and quickly knock them out. In the "Choose your wallet" page could we have each wallet listing in their own box with a white or subtle drop shadow effect and a little spacing between the boxes? Similar to how the wallets were listed on the homepage in version 2, it looked really nice.

**Comment by crwatkins** [comment]
I slightly prefer the flow down over the flow up (i.e. ver 1 over ver 2).

At this stage, is a new "choosing tool" open for consideration?  I'm thinking of something that might show scoring (perhaps only the color) for the subset of wallets you have selected.  Right now I fear we make new users look at every wallet in isolation and then try to come up with a choice.

**Comment by wbnns** [comment]
@natiwa 

Please go ahead and continue with the other wireframes from the spreadsheet and post them here. Let's review what's been done so far during our progress meeting tomorrow (hopefully you're feeling better by then! 🙂).

**Comment by natiwa** [comment]
Hi all,

@wbnns I have a big favor to you. Can we please move our weekly meeting to Monday (the same time). I'm afraid I caught the flu or something like that and I don't feel well enough for a call. I have a plan to work whole Sunday to catch up with work. 

Best,
N

**Comment by wbnns** [comment]
@natiwa No problem, I hope you feel better! Have a nice weekend and talk to you on Monday.

**Comment by natiwa** [comment]
@Cobra-Bitcoin Yes, we can do a drop shadow for those boxes, but Balsamiq not allows me to do that so I will add it in Sketch directly. 

**How to buy Bitcoin - new versions:**
[ver 2.](https://invis.io/BWFWTB78C5E#/279998410_Bitcoin-org__-_How_To_Buy_Bitcoin_Ver2) 
-> In my opinion, it looks nice and works for [Spending Bitcoin](https://bitcoin.org/en/spend-bitcoin), but can't be used as a template for other similar layouts like [Some things you need to know](https://bitcoin.org/en/you-need-to-know)... We should have another layout for that. 

[ver 3.](https://invis.io/A7FWTF1MVX5#/279999846_Bitcoin-org__-_How_To_Buy_Bitcoin_Ver3) 
-> ...Otherwise, we should keep it simple and do it as a template for other screens. I'm afraid there is no way to make this screen fancy and useable at once. 
Let me know your thoughts. 

**For Individuals, For Business, For Developers**
We can proceed with two the same layouts as I prepared for "How to buy Bitcoin" subpage, but on the "Bitcoin for Businesses" subpage, the number of elements is odd and we will have the same problem as in version 1 of [How to buy Bitcoin](https://invis.io/MNFUJBDA5FE#/279286247_Bitcoin-org__-_How_To_Buy_Bitcoin). Let me know your thoughts. 

[**How does Bitcoin work?**](https://invis.io/VSFWTWEUN8Y#/280006550_Bitcoin-org__-_How_Does_Bitcoin_Work_)

[**FAQ**](https://invis.io/ARFWU38EBPG#/280008619_Bitcoin-org__-_Frequently_Asked_Questions)

[**Secure Your Wallet**](https://invis.io/P6FWU6L3B72#/280009554_Bitcoin-org__-_Securing_Your_Wallet) 

I'll continue tomorrow :)

**Comment by wbnns** [comment]
@natiwa 

I hope you're feeling better! Thanks for continuing to work through this. Please keep going and let's review everything during our progress meeting tomorrow.

**Comment by natiwa** [comment]
[**Running A Full Node**](https://invis.io/F8FX1DRVP3D#/280077229_Bitcoin-org__-_Running_A_Full_Node)

[**Bitcoin Core**](https://invis.io/BZFX27RM78F#/280084848_Bitcoin-org__-_Bitcoin_Core)

[**Blog**](https://invis.io/V4FX33JRKUX#/280092710_Bitcoin-org__-_Bitcoin-org_Site_Blog)

[**Bitcoin Paper**](https://invis.io/GUFX3B1ZDSP#/280094169_Bitcoin-org__-_Bitcoin_Paper)

[**Network status and alerts** ](https://invis.io/2FFX64W9D7J#/280120260_Bitcoin-org__-_Network_Status_And_Alerts) After I came with the idea for a layout for Alerts subpage, I came to the conclusion that we could youse the same layout for Blog as well. 

[**Bitcoin Resources**](https://invis.io/PXFX6MWMJ5A#/280124502_Bitcoin-org__-_Bitcoin_Resources)

[**About bitcoin.org** ](https://invis.io/VQFX7NC8NXE#/280132934_Bitcoin-org__-_About_Bitcoin-org)

**Comment by wbnns** [comment]
👏 👏 👏

**Comment by natiwa** [comment]
Please remember that some of the layouts will be the same or at least very similar. 

[Spreadsheet with templates ](https://docs.google.com/spreadsheets/d/17ncFqPXjiFlyA3i2rk3mq-kHuxpl_DqafhqjZPjHDY8/edit?usp=sharing)

**Comment by natiwa** [comment]
@wbnns I don't see your comments here [
Bitcoin.org Subpages Outline for Redesign](https://docs.google.com/spreadsheets/d/1wrmYP5dePSOaatbTD2TIk9MKcIkJWHlU3j9K_6RzRFU/edit?usp=sharing)

**Comment by natiwa** [comment]
[Innovation](https://bitcoin.org/en/innovation) I think we can use layout [This ](https://invis.io/BWFWTB78C5E#/279998410_Bitcoin-org__-_How_To_Buy_Bitcoin_Ver2) or [This](https://invis.io/A7FWTF1MVX5#/279999846_Bitcoin-org__-_How_To_Buy_Bitcoin_Ver3) for that subpage. 

[Developer Reference](https://bitcoin.org/en/developer-reference#block-chain) very similar to [Link](https://invis.io/F8FX1DRVP3D#/280077229_Bitcoin-org__-_Running_A_Full_Node)

[Support Bitcoin](https://bitcoin.org/en/support-bitcoin) I think we can use layout [This ](https://invis.io/BWFWTB78C5E#/279998410_Bitcoin-org__-_How_To_Buy_Bitcoin_Ver2) or [This](https://invis.io/A7FWTF1MVX5#/279999846_Bitcoin-org__-_How_To_Buy_Bitcoin_Ver3) for that subpage. 

[Development](https://bitcoin.org/en/development) I think we can also use that template [Link](https://invis.io/F8FX1DRVP3D#/280077229_Bitcoin-org__-_Running_A_Full_Node)

 [Developer Examples](https://bitcoin.org/en/developer-examples#testing-applications) and [Legal](https://bitcoin.org/en/legal) again we can use that template [Link](https://invis.io/F8FX1DRVP3D#/280077229_Bitcoin-org__-_Running_A_Full_Node)

[Protect Your Privacy](https://bitcoin.org/en/protect-your-privacy) I would suggest using that [layout](https://invis.io/VSFWTWEUN8Y#/280006550_Bitcoin-org__-_How_Does_Bitcoin_Work_)

[**Events** ](https://invis.io/4WFXW1SJX86#/280342701_Bitcoin-org__-_Events)

[**Developer Glossary**](https://invis.io/S5FXXYKJBAE#/280357293_Bitcoin-org__-_Developer_Glossary) 

[**Glossary subpage**](https://invis.io/PCFXYD564EK#/280360907_Bitcoin-org__-_Glossary_Subpage)

[**Download Bitcoin Core**](https://invis.io/YFFY1QADVRB#/280387786_Bitcoin-org__-_Download_Bitcoin_Core)  and I've changed a bit the layout for [Bitcoin Core ](https://invis.io/BZFX27RM78F#/280084848_Bitcoin-org__-_Bitcoin_Core)

[Press](https://bitcoin.org/en/press) I would use layout from [FAQ](https://invis.io/ARFWU38EBPG#/280008619_Bitcoin-org__-_Frequently_Asked_Questions)

**Comment by natiwa** [comment]
I've tried to improve the [spreadsheet](https://docs.google.com/spreadsheets/d/17ncFqPXjiFlyA3i2rk3mq-kHuxpl_DqafhqjZPjHDY8/edit?usp=sharing). I added the new columns to put the preview links there: 

- Wireframe Desktop
- Wireframe Mobile
- Design Desktop
- Design Tablet 
- Design Mobile
-

**Comment by Cobra-Bitcoin** [comment]
Great work!

With the download page though (https://invis.io/YFFY1QADVRB#/280387786_Bitcoin-org__-_Download_Bitcoin_Core), I think it would look much nicer if we kept the download buttons in the center so they're the main focus, instead of pushing them to the left and having the text be noticed first.

**Comment by natiwa** [comment]
I agree with small but... :) 
If we move button to the center the layout won't be consistent with the "Bitcoin Core" subpage. That could be confusing for the users.

**Comment by natiwa** [comment]
Choose Your Wallet on Mobile. Two versions:

[Version 1](https://invis.io/VJFYSY15AWP#/280619259_Bitcoin-org__-_Mobile_-_Choose_Your_Bitcoin_Wallet__ver_1) (3 previews)  and [Version 2](https://invis.io/HWFYT2I82US#/280619261_Bitcoin-org__-_Mobile_-_Choose_Your_Bitcoin_Wallet_Ver_2) (5 previews)

**Comment by Cobra-Bitcoin** [comment]
Personally, I'm much more keen on version 2. Has a very smooth and interactive feeling which makes it simple to use.

I think in the next few days we should get started on the actual designs for more pages. We've only seen the getting started page, but now it looks like the wallet pages at least are ready to proceed to design. The quicker we start knocking out the designs, the better.

**Comment by natiwa** [comment]
For all similar to [Secure Your Wallet](https://invis.io/P6FWU6L3B72#/280009554_Bitcoin-org__-_Securing_Your_Wallet) I have prepared the: [**Mobile version**](https://invis.io/PVFYU07JGTY#/280628942_Bitcoin-org__-_Mobile_-Securing_Your_Wallet). I was thinking about solution like this: [Link](https://codepen.io/Chenyu/pen/dPeaME) or [Link](http://output.jsbin.com/AviNUxA/2) or [Link](https://tympanus.net/Tutorials/FullscreenBookBlock/)

[**Bitcoin Core Mobile**](https://invis.io/VNFYUGQXMTF#/280632978_Bitcoin-org__-_Mobile-_Bitcoin_Core_)

**Comment by natiwa** [comment]
@Cobra-Bitcoin Yes, of course. I prefer version 2 as well. I think I will finish all important mobile wireframes today, and I will be able to start designing form tomorrow.

**Comment by natiwa** [comment]
Last screens:

[**Alerts**](https://invis.io/F5FYWC62R6P#/280647139_Bitcoin-org__-_Mobile-_Network_Status_And_Alerts_) 

[**Developer Documentation**](https://invis.io/8UFYWUKYMPG#/280651372_Bitcoin-org__-_Mobile-_Developer_Documentation)

**Comment by wbnns** [comment]
@natiwa 

Awesome work. Thanks for doing the taking the mobile considerations into mind that we discussed the other day. This is all great stuff. I also like Version 2 that @Cobra-Bitcoin mentioned.

I appreciate you working hard to wrap up the rest of the wireframes like we discussed. Please go for it and be aggressive on knocking out the designs that correspond to them, now that they're finished. Will look forward to connecting again for our next progress review session on Friday!

**Comment by natiwa** [comment]
Designs:
[**How to buy Bitcoin**](https://invis.io/Q6FZREZBMP4#/280918337_Bitcoin-org_Buy_Bitcoin-_Desktop)

[**Choose your wallet Desktop**](https://invis.io/98FZRHO2SVU#/280919158_Bitcoin-org_-_Choose_Your_Wallet_-Desktop)
[**Choose your wallet Table**](https://invis.io/XQFZRJPHKEU#/280919157_Bitcoin-org_-Choose_Your_Wallet-__Tablet_768px)t 
[**Choose your wallet - mobile - step 1**](https://invis.io/2VFZRKHUJ3Y#/280919156_Bitcoin-org_-Choose_Your_Wallet-_Step1_Mobile_320px)
[**Choose your wallet - mobile - step 2**](https://invis.io/KGFZRLMPYMT#/280919155_Bitcoin-org_-Choose_Your_Wallet-_Step2_Mobile_320px)
[**Choose your wallet - mobile - step 3**](https://invis.io/M6FZRWXVET5#/280923146_Bitcoin-org_-Choose_Your_Wallet-_Step3_Mobile_320px)

**Comment by crwatkins** [comment]
Do we want to show scoring (perhaps only the color) for the subset of wallets you have selected? Right now I fear we make new users look at every wallet in isolation and then try to come up with a choice.

**Comment by wbnns** [comment]
@natiwa 

You're welcome. Regarding our meeting tomorrow at 15:00 UTC, I have something that has come up and need to reschedule. I can meet later tomorrow, or if OK with you all, let's do Monday at 15:00 UTC like we did this week.

Please keep going with the additional designs, I'll post comments on the InVision comps as you go!

**Comment by natiwa** [comment]
[**Choose your wallet - mobile - step 4**](https://invis.io/U3G0JT2SW29#/281164924_Bitcoin-org_-Choose_Your_Wallet-_Step4_Mobile_320px)

[**Bitcoin Exchanges**](https://invis.io/PJG0JK7YH2G#/281162103_22-01-18_Bitcoin-org_Bitcoin_Exchanges_Desktop_1200px__)

[**Secure Your Wallet**](https://invis.io/GKG0JMX8NDZ#/281162065_22-01-18_Bitcoin-org_Secure_Your_Wallet_Desktop_1200px__)

[**Buy Bitcoin**](https://invis.io/Q7G0JNLA4KE#/281162117_22-01-18_Bitcoin-org_Buy_Bitcoin_Desktop_1200px__)

Template for: [**For Individuals, For Business, For Developers**](https://invis.io/QUG0JOYCVZS#/281162329_22-01-18_Bitcoin-org_Bitcoin_For_Individuals_Desktop_1200px__)

**Comment by natiwa** [comment]
Let's do our call on Monday. :)

**Comment by wbnns** [comment]
@natiwa Great work. I've gone through and left comments on what you've done so far. Let's keep pushing to finish these. I think we can start looking to begin implementing these designs, soon, perhaps later this week. Talk to you tomorrow at our progress meeting.

**Comment by natiwa** [comment]
@wbnns Thanks. I have also left my replies. 

Please check the new solution for the Wallet page.
[**Wallet page new solution** ](https://invis.io/E7G1FI4CJD3#/281472179_Bitcoin-org_-_Wallet_Page-Desktop_Ver_2)
[**Wallet page new solution - navigation**](https://invis.io/X5G1FJH9SN4#/281472178_Bitcoin-org_-_Wallet_Page-Desktop_Ver_2_Nav)

Improved [**Choose your wallet - mobile - step 4**](https://invis.io/U3G0JT2SW29#/281164924_Bitcoin-org_-Choose_Your_Wallet-_Step4_Mobile_320px)

**Comment by Cobra-Bitcoin** [comment]
@natiwa The top navigation looks really clean and great, nice work. Absolutely love it.

What will happen to this page then https://projects.invisionapp.com/share/98FZRHO2SVU#/screens/280919158_Bitcoin-org_-_Choose_Your_Wallet_-Desktop? Will it include the new navigation (though obviously with  operating system/wallet sections greyed out), or do you think it's better if the navigation only appears when inside a wallet? I like the idea of it always being there, just so the user can better visualize the step-by-step "flow".

**Comment by natiwa** [comment]
@Cobra-Bitcoin I was thinking to do that navigation only inside the wallet page. But I'm open to any suggestions. 

https://projects.invisionapp.com/share/98FZRHO2SVU#/screens/280919158_Bitcoin-org_-_Choose_Your_Wallet_-Desktop That page looks clear as a first screen of selecting wallet. The purpose of the new navigation is only to help navigate between wallets without the necessity of going back.

**Comment by Cobra-Bitcoin** [comment]
I'm OK with it only appearing when inside the wallet page.

Could you update this [spreadsheet](https://docs.google.com/spreadsheets/d/17ncFqPXjiFlyA3i2rk3mq-kHuxpl_DqafhqjZPjHDY8/edit#gid=0) more often? Makes it easy for me to keep track of progress with one glance. Agreed with @wbnns that we should start looking to implement soon.

**Comment by natiwa** [comment]
Yes, sorry. I will do it now.

**Comment by natiwa** [comment]
[**Resources**](https://invis.io/AWG1ID7NZ9E#/281497500_22-01-18_Bitcoin-org_Bitcoin_Resources_Desktop_1200px) 

[**Developer Examples**](https://invis.io/T8G1IICZMRG#/281498555_22-01-18-Bitcoin-org_Developer_Examples_desktop_1200px)

**Comment by natiwa** [comment]
[**Bitcoin Core**](https://invis.io/XKG1N23TPD9#/281537810_Bitcoin-org_-_Bitcoin_Core_-Desktop)

**Comment by natiwa** [comment]
[**Bitcoin Core - Mobile** ](https://invis.io/BFG2AY635UR#/281756489_Bitcoin-org_-Bitcoin_Core_Mobile_320px)

[**Download Bitcoin Core**](https://invis.io/DAG2CED4F2Z#/281768505_Bitcoin-org_-_Download_Bitcoin_Core_-Desktop)

[**Events**](https://invis.io/TBG2DW7GFKR#/281781815_Bitcoin-org_-_Event_-Desktop_1200px) 

[**Bitcoin Paper**](https://invis.io/W8G2EPV3BCN#/281789853_Bitcoin-org-Bitcoin_Paper_Desktop_1200px)

[**Secure your wallet Mobile View 1**](https://invis.io/PWG2HTDYFXR#/281815384_Bitcoin-org_-Securing_Your_Wallet-_view1_Mobile_320px)
[**Secure your wallet Mobile View 2**](https://invis.io/TMG2HUYD5ZR#/281815383_Bitcoin-org_-Securing_Your_Wallet-_view2_Mobile_320px)
[**Secure your wallet Mobile View 3**](https://invis.io/4DG2HUFWN6V#/281815382_Bitcoin-org_-Securing_Your_Wallet-_view3_Mobile_320px)

[**Developer glossary**](https://invis.io/V2G2JQ6MGHB#/281817581_Developer_Glossary)

[**Glossary Subpage**](https://invis.io/TWG2K8Q4872#/281837918_Glossary_Subpage) 

[**Developer Documentation**](https://invis.io/SKG2KFY4EM2#/281839206_22-01-18_Bitcoin-org_Developer_Documentation-Desktop_1200px)
[**Developer Documentation Mobile**](https://invis.io/KXG2KED9QNB#/281839205_Bitcoin-org_-Developer_Documentation-_Mobile_320px)


**Improvements:**

[Bitcoin Exchanges ](https://invis.io/PJG0JK7YH2G#/281162103_22-01-18_Bitcoin-org_Bitcoin_Exchanges_Desktop_1200px__)
[Alerts](https://invis.io/5VG0NACZ9EP#/281192625_Bitcoin-org_-_Network_Status_And_Alerts_-Desktop_1200px)
[Developer Examples](https://invis.io/T8G1IICZMRG#/281498555_22-01-18-Bitcoin-org_Developer_Examples_desktop_1200px)

**Comment by natiwa** [comment]
Hey all,

@wbnns We still working on some screens. I'll send you a sketch file a little bit later today. 
Which spreadsheet? Do you mean time reports or the "Bitcoin.org Subpages by layout types" ?

Before my vacations we won't finish:
- all of the icons (some of the screens would have empty space for icons)
- all of the illustrations for subpages: Protect your privacy, How it works, Things You Need to Know

Our second designer will work on them during my absence.

**Comment by wbnns** [comment]
@natiwa Ok, thanks for the update and also for sending the files. Could you please update both spreadsheets (time reports and layout types) before you go?

**Comment by natiwa** [comment]
Of course.

**Comment by natiwa** [comment]
Last screens: 
[**Things you need to know**](https://invis.io/DUG391DT4WC#/282060032_22-01-18_Bitcoin-org_Things_You_Need_To_Know-Desktop_1200px)
[**How does Bitcoin work**](https://invis.io/V6G39255AH9#/282060851_22-01-18_Bitcoin-org_How_Does_Bitcoin_Work-Desktop_1200px)
[**Protect your privacy**](https://invis.io/E5G392T2SU4#/282059494_22-01-18_Bitcoin-org_Protect_Your_Privacy-Desktop_1200px)
[**Press Centre** ](https://invis.io/T8G394FX3FQ#/282058818_22-01-18_Bitcoin-org_press_Centre_Desktop_1200px)
[**Blog/Alert subpage**](https://invis.io/2TG39F8VRP8#/282064039_22-01-18_Bitcoin-org_Alert_Subpage-Desktop_1200px)
[**Innovation**](https://invis.io/XZG396ZYE3K#/282062508_22-01-18_Bitcoin-org_Innovation_Desktop_1200px)
[**Blog**](https://invis.io/MFG39JUWS9D#/282065641_Bitcoin-org_-Blog-Desktop_1200px)
[**About us**](https://invis.io/AMG3CSYGDW4#/282093596_22-01-18_Bitcoin-org_About_Us_Desktop_1200px)

**I have updated the spreadsheets:**
[Worklog](https://docs.google.com/spreadsheets/d/1JzAzh0qAJv2S068GokAS2KSfhz5XDhx78wd3jsxUXoI/edit?usp=sharing)
[Subpages by layout types](https://docs.google.com/spreadsheets/d/17ncFqPXjiFlyA3i2rk3mq-kHuxpl_DqafhqjZPjHDY8/edit?usp=sharing)

Here is the [Link to the Sketch source file](https://drive.google.com/file/d/1Wg1_87WuPw7_-APxEEyvzExx0ULaiTUM/view?usp=sharing).

**Comment by natiwa** [comment]
Please take a look at the all icons and the illustrations we've made. 

You can leave your comments directly in Invision.

https://invis.io/SHG8BA6U7ZX#/283752725_22-01-18_Bitcoin-org_How_Does_Bitcoin_Work-Desktop_1200px
https://invis.io/T7G8BAEWBQ8#/283752808_22-01-18_Bitcoin-org_Things_You_Need_To_Know-Desktop_1200px
https://invis.io/A6G8BANDBQK#/283752884_22-01-18_Bitcoin-org_Innovation_Desktop_1200px
https://invis.io/D7G8BASJ5GB#/283752939_22-01-18_Bitcoin-org_Support_Bitcoin_Desktop_1200px
https://invis.io/7GG8BB24A5N#/283753044_22-01-18_Bitcoin-org_Spending_Bitcoin_Desktop_1200px
https://invis.io/WTG8BBA3VXM#/283753123_22-01-18_Bitcoin-org_Bitcoin_Communities_Desktop_1200px

**Comment by natiwa** [comment]
@wbnns Please take a look at the Homepage with social icons on the right and in the footer.
[LINK](https://invis.io/6VFF8CB9CJA#/274446152_19-01-18_Bitcoin-org_Ver3_Desktop_1200px)

The idea behind this is to have that fixed during the scrolling. Let me know your thoughts. 

Also, I forgot to ask on the call.Have you had a chance to take a look at the illustrations and icons from the previous post? 

Natalia.

**Comment by natiwa** [comment]
I have updated the spreadsheet by all Mobile and tablet previews we've done.  
[Link to "Bitcoin.org Subpages by layout types" ](https://docs.google.com/spreadsheets/d/17ncFqPXjiFlyA3i2rk3mq-kHuxpl_DqafhqjZPjHDY8/edit?usp=sharing)

Only two left:
-Wallet page - Tablet version
- Events- mobile version

**Comment by natiwa** [comment]
Last screens:
[Wallet page - Tablet version](https://invis.io/9WGI1S4G7K2#/287012782_Bitcoin-org_-wallet_Page_Nav-__Tablet_768px)
and [Events- Tablet version](https://invis.io/26FTVNJC5AT#/279074493_Bitcoin-org_-Getting_Started_Tablet_768px) [Events- mobile version (https://invis.io/8NGHA27SUZW#/286763426_Bitcoin-org_-Blog-_Mobile_320px)
