### ISSUE TITLE
State of Digital Money 2018

### ISSUE THREAD

**Issue by alanlungtse** [bitcoin-dot-org/bitcoin.org#2141]
- date: 2018-05-05
      title: "State of Digital Money 2018"
      venue: "Cross Campus Downtown LA"
      address: "800 Wilshire Blvd - Suite 200, Los Angeles, CA 90017"
      city: "Los Angeles, CA"
      country: "USA"
      link: "stateofdigitalmoney.com"

**Comment by wbnns** [comment]
Duplicate of #2048
