### ISSUE TITLE
Broken link for Breadwallet (Android)

### ISSUE THREAD

**Issue by schildbach** [bitcoin-dot-org/bitcoin.org#2151]
On the [Breadwallet "choose your wallet" page](https://bitcoin.org/en/wallets/mobile/android/breadwallet/), clicking "install" leads to a [404-like error page](https://play.google.com/store/apps/details?id=com.breadwallet).

Seems like Breadwallet has been pulled from Google Play.

**Comment by crwatkins** [comment]
@schildbach thanks for the report.  From the URL you provided above, I assume it is happening for you on the Android "tab"?  I ask because it is working for me on Mac Chrome and landing me on https://play.google.com/store/apps/details?id=com.breadwallet . Can you provide more information about your environment so we can track it down?  Thanks.

**Comment by schildbach** [comment]
It's happening on Firefox/Ubuntu. Have you actually tried the link? It's a "not found" page.

**Comment by crwatkins** [comment]
Yes.  It works fine for me.  Takes me to the play store and shows me the wallet.    Perhaps it is a US vs Deutsch store issue?

**Comment by schildbach** [comment]
Hmmm, maybe. Hard to tell.

**Comment by wbnns** [comment]
I'm also able to load it without issue. 

![Breadwallet](https://i.imgur.com/NSpCFyv.png)

**Comment by wbnns** [comment]
Firefox on MacOS:

![image](https://user-images.githubusercontent.com/1130872/36236365-5b3b3d16-11bb-11e8-88e8-b50f6cafc39a.png)

**Comment by Cobra-Bitcoin** [comment]
I tested with Tor just now, it doesn't seem to work when connecting from a European IP address (at least the ones I was connecting from).

Not sure what's going on...

**Comment by wbnns** [comment]
I've tested this again, using Tor with an IP address in Germany and it seems to be loading fine, now.
