### ISSUE TITLE
request for staging repo on FILIPINO LOCALIZATION

### ISSUE THREAD

**Issue by cordeta** [bitcoin-dot-org/bitcoin.org#2159]
I would like to request a staging repo for Tagalog localization

**Comment by wbnns** [comment]
@cordeta Hello, do you mean you'd like to add Tagalog to Transifex? If so, you can [request the language](https://www.transifex.com/projects/p/bitcoinorg/) on Bitcoin.org's Transifex page.

If I misunderstood you or if you have any other questions, please let me know.
