### ISSUE TITLE
Mempool RPCs Parameter mismatch

### ISSUE THREAD

**Issue by thephez** [bitcoin-dot-org/bitcoin.org#2160]
[Bounty](https://github.com/bitcoin-dot-org/bitcoin.org#earn-bitcoin-for-contributing): **25,000 bits / ~$125 USD**

Parameter 1 is a TXID, but the Name and Description are for an address in (at least) the following:
- Source File: _data/devdocs/en/bitcoin-core/rpcs/rpcs/getmempoolancestors.md
- Source File: _data/devdocs/en/bitcoin-core/rpcs/rpcs/getmempooldescendants.md
- Source File: _data/devdocs/en/bitcoin-core/rpcs/rpcs/getmempoolentry.md

https://bitcoin.org/en/developer-reference#getmempoolancestors
https://bitcoin.org/en/developer-reference#getmempooldescendants
https://bitcoin.org/en/developer-reference#getmempoolentry

**Comment by 0xB10C** [comment]
The files you noted seem to be fixed:

getmompoolancestors with e29d1e5a7ae85e50f4c552ee76978da357237dd8
getmompooldescendants with 3d3baa7df5fafa29285f0f203094a6ccab968270
getmempoolentry with 4c36b5d3df063142e868066f7417ea34261196f5

**Comment by wbnns** [comment]
@0xB10C 

Thank you.
