### ISSUE TITLE
Adding Bitcoin Vietnam and VBTC exchange

### ISSUE THREAD

**Issue by marcusvanesveld** [bitcoin-dot-org/bitcoin.org#2166]
Dear Bitcoin.org

Vietnam is missing in the exchanges list, so here are two Vietnamese bitcoin exchanges to add to the list:

- bitcoin.vn (https://bitcoin.vn)
- VBTC (https://vbtc.exchange)

Thank you,

Marcus van Esveld | Communications | bitcoin.vn

**Comment by marcusvanesveld** [comment]
Hi, 

Thank you for looking at my request - actually bitcoin.vn was out for a while due to a domain shutdown from the Vietnamese gov. Luckily all is fixed now and we're up again with a new domain: 

https://bitcoinvn.io/

Here is our api if needed: https://api.bitcoinvn.io/

VBTC has had no issues. It's still running smoothly: https://vbtc.exchange

Api: https://blinktrade.com/docs/

Thank you!

**Comment by wbnns** [comment]
@marcusvanesveld Hello, thanks for the info. Are BitcoinVN and VBTC the same company?

**Comment by wbnns** [comment]
@marcusvanesveld When you have time, please let us know and we can proceed with considering the addition of the exchange(s).

**Comment by marcusvanesveld** [comment]
Hi! I was out of town for a week so couldn't reply swiftly. Thanks for waiting. 
VBTC and bitcoinvn.io are different companies. VBTC is a P2P exchange, and bitcoinvn.io is officially a brokerage. Thank you!
