### ISSUE TITLE
Blockchain & Bitcoin Conference Germany

### ISSUE THREAD

**Issue by ElenSh** [bitcoin-dot-org/bitcoin.org#2171]
- 2018/04/04
      title: "Blockchain & Bitcoin Conference Germany"
      venue: "InterContinental Berlin"
      address: "Budapester Str. 2"
      city: "Berlin"
      country: "Germany"
      link: "https://goo.gl/zReyXe"

**Comment by ElenSh** [comment]
Trends and regulation of the crypto industry discussed at Blockchain & Bitcoin Conference Germany on April 4  

On April 4, Berlin will host Blockchain & Bitcoin Conference Germany, an event of Smile-Expo company that created a network of blockchain events in 20 countries throughout the world.  International experts will gather to discuss trends of the modern crypto industry. 

Blockchain & Bitcoin Conference Germany is one of the largest European platforms, where members of the global crypto community will be able to find business partners, present their products, and exchange accumulated experience. The event will feature major global investors searching for promising projects. 

Conference 

Speakers will focus on keynote topics such as implementation of blockchain in business, state regulation of crypto assets, and launch of ICOs. The audience will obtain practical knowledge as to how to integrate modern technologies in business, how to prepare and run a token sale, and how not to break the law when running a crypto business. 

Conference headliners: 

•	Peter Mitchell and Christopher Murrer are experts in tax law from the worldwide famous law firm Baker & McKenzie Zurich. As experienced lawyers, they will tell what awaits the European business with the arrival of laws that regulate data protection. 
•	Meinhard Benn is one of the 50 most influential people in the sphere of blockchain in Berlin, founder of cryptocurrency micropayments service SatoshiPay. His presentation will be dedicated to cryptocurrency wallets.    

Exhibition area 
Apart from the conference, guests of Blockchain & Bitcoin Conference Germany will have access to exhibition area, featuring companies that represent the blockchain industry. They will present their products such as software and hardware solutions for cryptocurrency mining, blockchain developments, as well as trading, financial, and marketing services. 

Date: April 4
Venue: the event will take place at InterContinental Berlin hotel, located not far from Berlin Zoological Garden in Großer Tiergarten. Address: Budapester Str. 2, 10787 Berlin.

Follow the event news and program updates on the official website of Blockchain & Bitcoin Conference Germany.

**Comment by ElenSh** [comment]
How soon will you be able to publish the event?

**Comment by wbnns** [comment]
@ElenSh Hello, apologies that we weren't able to add this in time.
