### ISSUE TITLE
Chainges

### ISSUE THREAD

**Issue by AgataMa** [bitcoin-dot-org/bitcoin.org#2186]
Chainges is the **first world-class blockchain&cryptocurrency conference** shaped by the community, based in **Amsterdam, May 4-5**. The conference is for anyone with a vested interest in blockchain technology and cryptocurrencies. The event caters for a range of demographics that are looking to hone their skills, meet new connections, source new technology, gain inspiration and celebrate this ever-emerging corner of distributed ledger technology as it takes flight. 

website: http://chainges.co
Facebook: https://www.facebook.com/Chainges.co/ 
Twitter: https://twitter.com/_chainges

**Comment by wbnns** [comment]
@AgataMa Hello, thanks for submitting this, however, the website seems to be broken:

<img width="1274" alt="image" src="https://user-images.githubusercontent.com/1130872/38432843-0d153478-3986-11e8-953b-426cd5aa2fea.png">
