### ISSUE TITLE
Serbian language

### ISSUE THREAD

**Issue by nedvedp** [bitcoin-dot-org/bitcoin.org#2193]
I have been translating bitcoin.org into Serbian on transifex. It appears that the project for this language is abandoned, since some of the changes were 4 years ago.

Is there a way that someone can verify my changes and that we can speed this up? Is there a coordinator of the project?

I would gladly take over if there is nobody to handle this.

**Comment by wbnns** [comment]
@nedvedp Hello, thanks for your interest in taking over the Serbian translation. What's your transifex username?

**Comment by nedvedp** [comment]
@wbnns The translation on Serbian of the strings in bitcoin.org are 83.47% translated. I probably need few more days to edit it out if necessary and apply changes, so it would be very helpful if either you can ping the coordinator to review them or give me the permission to do so if the team is inactive, which pretty much seems so as only 20ish percent was translated when I started, most of which were generic strings. Some of those also require modification imho.

**Comment by wbnns** [comment]
@nedvedp I just added you as a coordinator for Serbian. You should have the correct permissions to take care of it now. Thanks for your help!
