### ISSUE TITLE
Remove Coinkite from the list of wallets as it is discontinued for over a year

### ISSUE THREAD

**Issue by nedvedp** [bitcoin-dot-org/bitcoin.org#2194]
Coinkite wallet should be removed from the wallets list as it has been closed down for over a year now. 
[Source 1](https://coinkite.com/wallet)
[Source 2](http://blog.coinkite.com/post/141836920461/time-to-be-your-own-bank)

**Comment by crwatkins** [comment]
@nedvedp Coinkite was removed from the wallets list in 2016 when they announced that they were shutting down in PR #1269.  There may still be some vestigial references in translations (that will not appear on the site).  Could you let us know where you are seeing these references?
