### ISSUE TITLE
Fix the 404 in CONTRIBUTING.md

### ISSUE THREAD

**Issue by nedvedp** [bitcoin-dot-org/bitcoin.org#2195]
There's a 404 dead link in the  https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/docs/working-with-github.md

> GitHub allows you to make changes to a project using git, and later submit them in a "pull request" so they can be reviewed and discussed. Many online how-tos exist so you can learn git, **`[here's a good one](https://www.atlassian.com/git/tutorial/git-basics - this link is 404)`.**

**Comment by wbnns** [comment]
@nedvedp Thanks for mentioning this. Opened #2375 to fix.
