### ISSUE TITLE
Handling outdated English translation strings on Transifex

### ISSUE THREAD

**Issue by nedvedp** [bitcoin-dot-org/bitcoin.org#2198]
Hello,

I assume that most of the strings are up to  date, but there are some outdated on Transifex.

How should we handle those when translating? Is there anything a translator can do to update them?

Example 

> Bitcoins can also be exchanged in physical form such as the Denarium coins, but paying with a mobile phone usually remains more convenient [source](https://bitcoin.org/en/faq)

On Transifex 

>  Bitcoins can also be exchanged in physical form such as the Casascius coins, but paying with a mobile phone usually remains more convenient. 

Off-topic but I would add Opendime when mentioning physical coins.

Thanks.

**Comment by wbnns** [comment]
@nedvedp Thanks. When the English strings are updated in the repository, they will get updated in Transifex.
