### ISSUE TITLE
Update Frontend to Incorporate New Design

### ISSUE THREAD

**Issue by wbnns** [bitcoin-dot-org/bitcoin.org#2200]
@marekkirejczyk @natiwa

Let's use this issue to keep track of our work updating / rewriting HTML/CSS/JS etc. as we implement the new design across the site.

**Comment by wbnns** [comment]
@alexcherman @marekkirejczyk

Attached is a report of the most-used browsers that have visited Bitcoin.org over the past six months, to keep in mind. We want to ensure full cross-browser compatibility amongst various devices. 

[most-used-browsers.pdf](https://github.com/bitcoin-dot-org/bitcoin.org/files/1801441/most-used-browsers.pdf)
[firefox-versions.pdf](https://github.com/bitcoin-dot-org/bitcoin.org/files/1801447/firefox-versions.pdf)
[safari-versions.pdf](https://github.com/bitcoin-dot-org/bitcoin.org/files/1801448/safari-versions.pdf)
[chrome-versions.pdf](https://github.com/bitcoin-dot-org/bitcoin.org/files/1801449/chrome-versions.pdf)
[internet-explorer-versions.pdf](https://github.com/bitcoin-dot-org/bitcoin.org/files/1801450/internet-explorer-versions.pdf)

**Comment by Cobra-Bitcoin** [comment]
@alexcherman @marekkirejczyk Can we get a preview of the site up somewhere as soon as possible? I know some code has already been written, so would like to play around with things and see how it actually looks.

**Comment by wbnns** [comment]
@Cobra-Bitcoin Here's a preview: https://adoring-johnson-a68598.netlify.com/

**Comment by wbnns** [comment]
@alexcherman @marekkirejczyk

Just FYI, added a few more items to the [Redesign QA spreadsheet](https://docs.google.com/spreadsheets/d/1uvfM-KpxD57IQS02hK__5nvZyYJeVUWpWR-IbyaGglE/edit?usp=sharing).

Please let me know if you have any questions.
