### ISSUE TITLE
World Satoshi Summit

### ISSUE THREAD

**Issue by wss1729** [bitcoin-dot-org/bitcoin.org#2210]
12th-13th May 2018    
   
      venue: "JW Marriott"
      address: "Aerocity,New Delhi,India "
      city: "Delhi"
      country: "India"
      link: "https://worldsatoshisummit.com/
![700x700 2](https://user-images.githubusercontent.com/36760780/37337968-00035556-26dc-11e8-9d00-d7b47af8b6cc.jpg)
"

**Comment by wbnns** [comment]
Duplicate of #2170
