### ISSUE TITLE
Query in a passage:

### ISSUE THREAD

**Issue by somanyquestions** [bitcoin-dot-org/bitcoin.org#2214]
Source File: _data/devdocs/en/guides/block_chain.md

Should this say the opposite? "Chaining blocks together makes it impossible to modify transactions included in any block without modifying all following blocks."

Should it not say "Chaining blocks together makes it impossible to modify transactions included in any block without modifying all previous blocks."

Curious!

**Comment by wbnns** [comment]
@somanyquestions Nice catch, thanks for reporting. Opened #2374 to correct this.
