### ISSUE TITLE
Black Sea Blockchain Summit

### ISSUE THREAD

**Issue by Mulcaheys** [bitcoin-dot-org/bitcoin.org#2218]
- date: 2018-04-24
      title: "Black Sea Blockchain Summit"
      venue: "Rooms Hotel"
      address: "14 Merab Kostava Street"
      city: "Tbilisi"
      country: "Georgia"
      link: "www.bsbsummit.com"

**Comment by wbnns** [comment]
@Mulcaheys Hello, thanks for submitting this event, however, the website doesn't appear to be functioning:

<img width="1278" alt="image" src="https://user-images.githubusercontent.com/1130872/38440731-94a35c30-399f-11e8-9bf0-45b6afa05554.png">
