### ISSUE TITLE
DC Finance's Dallas Family Office & High Net Worth Blockchain Conference

### ISSUE THREAD

**Issue by DC-Finance** [bitcoin-dot-org/bitcoin.org#2230]
- date: 2018-09-04
      title: "The Dallas Family Office & High Net Worth Blockchain Conference"
      venue: "Haynes and Boone, LLP"
      address: "2323 Victory Avenue, Suite 700, Dallas, TX 75219"
      city: "Dallas"
      country: "USA"
      link: ""

**Comment by beyourseff** [comment]
Hello there, 
I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:
**Q: Is this a Bitcoin event?**
A: No

**Q: Is there a talk focused exclusively on a Bitcoin topic?**
A: No

**Q: Will there be talks regarding ICO's and/or altcoins? If so, how much time will be dedicated to them in total?**
A: Yes, this seems to be an ICO-centric event.

Result: **In my opinion this event should/should NOT be listed on Bitcoin.org based on the above.**

**Comment by DC-Finance** [comment]
Hi there,

 

Of course it is a bitcoin event – we are the organizer of three events that are solely dedicated to bitcoin, cryptocurrency and blockchain, this is one of them. It is a conference, so the entire day is built up of different lectures about the topics mentioned above. The days are normally divided into three sessions: blockchain, cryptocurrency and ICO. Please let me know would you reconsider. 

 

Thanks,

 

Linda Sandström

Production Manager

 

DC Finance

Family Office Global Network 

* US Toll Free  1-855-513-1113

* UK Toll Free: 0800-098-8444

Israel tel: +972-3677-7701 ext. 8-4

Fax: +972-3677-9232

Email:  <mailto:jocelyn@nyc-wealth.com> linda@dc-finance.com 

Web: www.dc-finance.com  

English web: www.nyc-wealth.com
