### ISSUE TITLE
Blockchain & Decentralized Tech SuperSummit

### ISSUE THREAD

**Issue by finid** [bitcoin-dot-org/bitcoin.org#2231]
- date: 2018-10-10
      title: "Blockchain & Decentralized Tech SuperSummit"
      venue: "Embassy Suites Dallas-Frisco Convention Center & Spa"
      address: "7600 John Q. Hammons Drive"
      city: "Frisco"
      country: "Texas"
      link: "https://blockchainsupersummit.net"

**Comment by beyourseff** [comment]
Hello there, 
I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:
**Q: Is this a Bitcoin event?**
A: No

**Q: Is there a talk focused exclusively on a Bitcoin topic?**
A: No

**Q: Will there be talks regarding ICO's and/or altcoins? If so, how much time will be dedicated to them in total?**
A: Possible

**Other notes:** lots of buzzwords (IoT, AI, VR etc) but no actual talks are listed, so it was hard to assess this.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**

**Comment by wbnns** [comment]
@finid Hello, could you please resubmit this for review once the agenda becomes available?

**Comment by finid** [comment]
@wbnns, I'll resubmit it, and have to anyway, because the date has changed.

But to your questions, @beyourseff, your reasons for not wanting the event listed don't make sense. For one, the conference is not exclusively a Bitcoin event, but a blockchain and cryptocurreny event, of which Bitcoin is a part of. All the events already listed at https://bitcoin.org/en/events share the same scope - blockchain technology and cryptocurrencies.

Also, no actual talks are listed, because the schedule is not available yet. And for an event that won't take place until late-October 2018, that is not unusual. Conferences don't list their agendas until about 3 months out. Even then, the agenda typically are not final until just weeks before the conference starts.

One more point, IoT, AI, VR etc, are not just buzzwords, but technology segments that are seeing the influence of blockchain technology.

For the record, seven (7) classes/workshops that will be conducted at the conference have been listed on the agenda. They are not exclusively about Bitcoin, but about blockchain technology and ICOs and cryptocurrencies.
