### ISSUE TITLE
Blockchain Economic Forum

### ISSUE THREAD

**Issue by annakovaleva1** [bitcoin-dot-org/bitcoin.org#2233]
- date: 2018-06-16 - 2018-06-19
      title: "Blockchain Economic Forum"
      venue: "San Francisco"
      address: ""
      city: "SF"
      country: "USA"
      link: "https://bef.latoken.com/"

**Comment by annakovaleva1** [comment]
Blockchain Economic Forum comes back to facilitate the discussions of the most important topics of the crypto economy and its growing influence on the global economy.

**Comment by syaifudin857** [comment]
Join
