### ISSUE TITLE
BitCoin Investors Expo

### ISSUE THREAD

**Issue by BitCoinExpo18** [bitcoin-dot-org/bitcoin.org#2234]
- date: 2018-11-05
      title: "" BitCoin Investors Expo
      venue: "" New Orleans,LA
      address: ""
      city: ""New Orleans
      country: ""United States
      link: ""https://theticketbrite.myshopify.com/products/bitcoin-expo-attendee-registration

**Comment by beyourseff** [comment]
The URL doesn't work so I couldn't assess whether or not this event could/couldn't be listed on Bitcoin.org.
