### ISSUE TITLE
UNCHAIN CONVENTION

### ISSUE THREAD

**Issue by doglette111** [bitcoin-dot-org/bitcoin.org#2235]
- date: 2018-31-05
      title: "UNCHAIN CONVENTION"
      venue: "Theater Kehrwieder"
      address: "Kehrwieder 6"
      city: "Hamburg"
      country: "Germany"
      link: "https://unchain.hamburg/"

**Comment by beyourseff** [comment]
Hello there, 
I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:
**Q: Is this a Bitcoin event?**
A: Not really, more crypto-companies focused.

**Q: Is there a talk focused exclusively on a Bitcoin topic?**
A: It does seem so.

**Q: Will there be talks regarding ICO's and/or altcoins? If so, how much time will be dedicated to them in total?**
A: Doesn't seem so.

Result: **In my opinion this event could be listed on Bitcoin.org based on the above.**
