### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by Carmiah** [bitcoin-dot-org/bitcoin.org#2236]
date: 13 June 2018
      title: "CryptoCompare & MJAC London Blockchain Summit"
      venue: "Old Billingsgate"
      address: "Old Billingsgate Walk, EC3R 6DX"
      city: "London"
      country: "United Kingdom"
      link: "https://mjac.io/"

**Comment by beyourseff** [comment]
Hello there, 
I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:
**Q: Is this a Bitcoin event?**
A: Doesn't seem so, more focused on 'crypto-assets' as a whole

**Q: Is there a talk focused exclusively on a Bitcoin topic?**
A: I couldn't find any.

**Q: Will there be talks regarding ICO's and/or altcoins? If so, how much time will be dedicated to them in total?**
A: I couldn't find any.

Result: **In my opinion this event could be listed on Bitcoin.org based on the above.**

**Comment by twolmarans** [comment]
Hey,

having looked at the event's site:

Q: Is this a Bitcoin event?
A: No

Q: Is there a talk focused exclusively on a Bitcoin topic?
A: There is no listed Bitcoin-specific talk, but there is mention of Bitcoin

Q: Will there be talks regarding ICO's and/or altcoins? If so, how much time will be dedicated to them in total?
A: Yes, there will be a fair amount of time spent on altcoins, investing and how to list a new coin.

Result: I don't think that this is a relevant event for bitcoin.org.
