### ISSUE TITLE
World Satoshi Summit

### ISSUE THREAD

**Issue by rattle99** [bitcoin-dot-org/bitcoin.org#2237]
- date: 2018-05-12/13
      title: "World Satoshi Summit"
      venue: "JW Marriott Hotel"
      address: "Asset Area 4, Hospitality District, Aerocity"
      city: "New Delhi"
      country: "India"
      link: "https://worldsatoshisummit.com/"

**Comment by twolmarans** [comment]
Hey,

having looked at the event's site:

Q: Is this a Bitcoin event?
A: No

Q: Is there a talk focused exclusively on a Bitcoin topic?
A: There is no listed Bitcoin-specific talk

Q: Will there be talks regarding ICO's and/or altcoins? If so, how much time will be dedicated to them in total?
A: No topics listed, pitching ideas, trading and networking seems to be the focus

Result: I don't think that this is a relevant event.

**Comment by rattle99** [comment]
You missed checking the [Agenda](https://worldsatoshisummit.com/agenda)
