### ISSUE TITLE
BTA Bitcoin Turkey Education Camp

### ISSUE THREAD

**Issue by koriagency** [bitcoin-dot-org/bitcoin.org#2238]
date: 2018-04-06
title: "BTA Bitcoin Türkiye Eğitim Kampı"
venue: "Antalya Adalya Elite Lara Hotel"
address: "Kemerağzı Mah. Tesisler Cad. No:416 07112 Kundu/Aksu/Antalya"
city: "Antalya"
country: "Turkey"
link: "https://www.bitcointradeacademy.com"

**Comment by twolmarans** [comment]
Hey,

having looked at the event's site:

Q: Is this a Bitcoin event?
A: Yes

Q: Is there a talk focused exclusively on a Bitcoin topic?
A: Yes

Q: Will there be talks regarding ICO's and/or altcoins? If so, how much time will be dedicated to them in total?
A: Yes, There is a section regarding altcoin mining. 

Result: This seems to fit the guidelines for a Bitcoin event and could be listed

**Comment by wbnns** [comment]
@koriagency Thanks for submitting the event, and thanks to @twolmarans for the review.

**Comment by koriagency** [comment]
thanks. event will continue till 9 april by the way :)
