### ISSUE TITLE
CoinGeek.com Conference 

### ISSUE THREAD

**Issue by Petterayre** [bitcoin-dot-org/bitcoin.org#2239]
- date: 2018-05-18
      title: "COINGEEK CONFERENCE "
      venue: "Four Seasons Hong Kong"
      address: "8 Finance St, Central, Hong Kong"
      city: "Hong Kong Central"
      country: "Hong Kong"
      link: "https://coingeek.com/conference/registration/"

**Comment by beyourseff** [comment]
This is a clear example of why #2184 should be implemented. Why should a BCash event be listed on Bitcoin.org?

**Comment by wbnns** [comment]
@beyourseff Hello, it's not listed. Anyone can open an issue to submit an event for potential inclusion, and anyone can comment on the issue as to why they think it should or shouldn't be included.
