### ISSUE TITLE
World Blockchain Forum

### ISSUE THREAD

**Issue by AmandaHendricks** [bitcoin-dot-org/bitcoin.org#2240]
- date: 2018-04- 16 & 17
      title: "World Blockchain Forum - Investments & ICOs"
      venue: "Madinat Jumeirah"
      address: "6 King Salman Bin Abdulaziz Al Saud St
      city: "Dubai"
      country: "United Arab Emirates"
      link: "https://dubai.keynote.ae"

**Comment by AmandaHendricks** [comment]
Thank you for your help @wbnns do you know when this will show up on the calendar?

**Comment by beyourseff** [comment]
Hello there, 
I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:
**Q: Is this a Bitcoin event?**
A: No

**Q: Is there a talk focused exclusively on a Bitcoin topic?**
A: No

**Q: Will there be talks regarding ICO's and/or altcoins? If so, how much time will be dedicated to them in total?**
A: Yes. There's multiple ICO pitch slots throughout the event. In addition, many speakers are those who talk about their ICO.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**

**Comment by AmandaHendricks** [comment]
@beyourseff thank you for your reply. I appreciate the time you took to analyze my event submission(s). Can you please point me to event guidelines of bitcoin.org that stipulate what events are suitable? I’m not seeing where events must be strictly bitcoin focused.

**Comment by beyourseff** [comment]
Hi Amanda,

I'm not speaking on behalf of Bitcoin.org, and there currently aren't any Bitcoin.org guidelines. I have simply assessed the event based on the information presented on the website. Ultimately it is @wbnns who'll decide whether or not the event is suitable for submission.

I hope that answers your question :)

**Comment by wbnns** [comment]
@AmandaHendricks Hello, thanks for submitting this event and thanks @beyourseff for reviewing it. 

We have pretty loose requirements, however, generally we look to see that there is a clear agenda and that the event relates to bitcoin in some way (e.g. it being used as a currency, harnessing its technology, speakers from bitcoin-related companies, etc.).
