### ISSUE TITLE
The African Blockchain Conference 2018

### ISSUE THREAD

**Issue by Nagimesi** [bitcoin-dot-org/bitcoin.org#2242]
- date: 2018-05-23
      title: "The African Blockchain Conference 2018"
      venue: "The Kampala Serena Hotel"
      address: "Kintu Road"
      city: "Kampala"
      country: "Uganda"
      link: "https://africanblockchain.org/"

**Comment by beyourseff** [comment]
Hello there, 
I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:
**Q: Is this a Bitcoin event?**
A: Not really, more blockchain-centric it seems.

**Q: Is there a talk focused exclusively on a Bitcoin topic?**
A: It seems there is.

**Q: Will there be talks regarding ICO's and/or altcoins? If so, how much time will be dedicated to them in total?**
A: On day 1, in breakout hall 2 there's an ICO fundraising talk.

Result: **In my opinion this event could be listed on Bitcoin.org based on the above.**

**Comment by Nagimesi** [comment]
Hello,
Thank you for taking the time to respond to our issue. We opted for the wider blockchain-centric model to encompass the variety of interests involved. We are trying to get continental policy makers/regulators in the same environment with industry players and hope that some sort of legislation covering cryptocurrencies emerges with our short term goal being regulation for cryptocurrency transactions (p2p or exchanges) and ICOs.


Sent from Mail for Windows 10
