### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by c4tri** [bitcoin-dot-org/bitcoin.org#2243]
- date: 2018-04-05 - 2018-04-06
      title: "C³ Crypto Conference - MEET THE INTERNATIONAL CRYPTO COMMUNITY IN THE HEART..."
      venue: "Station Berlin"
      address: "Luckenwalder Str. 4–6 10963 Berlin"
      city: "Berlin"
      country: "Germany"
      link: "https://www.eventbrite.de/e/c3-crypto-conference-meet-the-international-crypto-community-in-the-heart-of-europe-in-berlin-tickets-42271198292?discount=C3TEAM"

**Comment by beyourseff** [comment]
Hello there, 
I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:
**Q: Is this a Bitcoin event?**
A: No.

**Q: Is there a talk focused exclusively on a Bitcoin topic?**
A: No.

**Q: Will there be talks regarding ICO's and/or altcoins? If so, how much time will be dedicated to them in total?**
A: Yes, exclusively it seems.

Result: **In my opinion this event should/should NOT be listed on Bitcoin.org based on the above.**
