### ISSUE TITLE
2018 US China Blockchain and Digital Currency Conference

### ISSUE THREAD

**Issue by blockchainchinaconnect** [bitcoin-dot-org/bitcoin.org#2245]
- date: 08-22-2018
      title: "2018 US China Blockchain and Digital Currency Conference"
      venue: ""
      address: ""
      city: "Los Angeles"
      country: ""
      link: "https://www.blockchainchinaconnect.com/"

**Comment by beyourseff** [comment]
Hello there, 
I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:
**Q: Is this a Bitcoin event?**
A: No

**Q: Is there a talk focused exclusively on a Bitcoin topic?**
A: It doesn't seem so.

**Q: Will there be talks regarding ICO's and/or altcoins? If so, how much time will be dedicated to them in total?**
A: Yes.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**
