### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by Hsbas** [bitcoin-dot-org/bitcoin.org#2246]
- date: 2018-06-06
      title: "Crypto Coin Turkey"
      venue: "Istanbul, Turkey"
      address: "İstanbul Üniversitesi Fen Fakültesi Vezneciler Mh. 
İstanbul Üniversitesi Prof. Cemil Bilsel Konferans Salonu"
      city: "Istanbul"
      country: "Turkey"
      link: "https://cryptocointurkey.org/"

**Comment by beyourseff** [comment]
Hello there, 
I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:
**Q: Is this a Bitcoin event?**
A: Doesn't seem so.

**Q: Is there a talk focused exclusively on a Bitcoin topic?**
A: Doesn't seem so.

**Q: Will there be talks regarding ICO's and/or altcoins? If so, how much time will be dedicated to them in total?**
A: Yes, there seem to be multiple talks with regards to ICO's and ICO regulation.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**

**Comment by wbnns** [comment]
@Hsbas Thanks for submitting this event.

@beyourseff Thanks for reviewing it. In the afternoon, there's a Bitcoin section in the program.
