### ISSUE TITLE
Blockchain Life 2018

### ISSUE THREAD

**Issue by Straus1994** [bitcoin-dot-org/bitcoin.org#2247]
- date: 2018-11-7-8
      title: "Blockchain Life 2018"
      venue: "ExpoForum"
      address: "Петербургское ш., 64к1 лит. А, Санкт-Петербург, 196140"
      city: "Saint-Petersburg"
      country: "Russia"
      link: "https://blockchain-life.com/ru/"

**Comment by beyourseff** [comment]
Hello there, 
I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:
**Q: Is this a Bitcoin event?**
A: No

**Q: Is there a talk focused exclusively on a Bitcoin topic?**
A: No

**Q: Will there be talks regarding ICO's and/or altcoins? If so, how much time will be dedicated to them in total?**
A: Exclusively so it seems.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**

**Comment by wbnns** [comment]
@Straus1994 Hello, could you please resubmit this for review once an agenda becomes available?
