### ISSUE TITLE
Blockchain Career Fair 

### ISSUE THREAD

**Issue by rkdekrypt** [bitcoin-dot-org/bitcoin.org#2248]
- date: 2018-04-12
      title: "Blockchain Career Fair"
      venue: "International House"
      address: "2299 Piedmont Ave"
      city: "Berkeley"
      country: "California USA"
      link: "http://blockchaincareerfair.io/"

**Comment by beyourseff** [comment]
Hello there, 
I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:
**Q: Is this a Bitcoin event?**
A: It focuses on 'distributed ledger technology'

**Q: Is there a talk focused exclusively on a Bitcoin topic?**
A: No, but it's not focused on talks.

**Q: Will there be talks regarding ICO's and/or altcoins? If so, how much time will be dedicated to them in total?**
A: Doesn't seem so

Result: **In my opinion this event could be listed on Bitcoin.org based on the above.**
