### ISSUE TITLE
New Event - CryptoEconomics Security Conference 2018

### ISSUE THREAD

**Issue by rkdekrypt** [bitcoin-dot-org/bitcoin.org#2249]
- date: 2018-10-15
      title: "CryptoEconomics Security Conference 2018"
      venue: "Pauly Ballroom"
      address: "2475 Bancroft Way"
      city: "Berkeley"
      country: "USA"
      link: "https://cesc.io"

**Comment by beyourseff** [comment]
Hello there, 
I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:
**Q: Is this a Bitcoin event?**
A: Yes, it's exclusively focused on Bitcoin-related elements.

**Q: Is there a talk focused exclusively on a Bitcoin topic?**
A: Yes, multiple.

**Q: Will there be talks regarding ICO's and/or altcoins? If so, how much time will be dedicated to them in total?**
A: No, it doesn't seem so.

Result: **In my opinion this event should be listed on Bitcoin.org based on the above.**

**Comment by rkdekrypt** [comment]
Thank you. This is a technical academic event as you can see our 2017. We
strictly limiting our presenters to meaningful talk that push the industry
forward.
