### ISSUE TITLE
New event - World Crypto Conference

### ISSUE THREAD

**Issue by WorldCryptoConference** [bitcoin-dot-org/bitcoin.org#2252]
- date: 2018-10-31
      title: "World Crypto Conference"
      venue: "Aria Resort"
      address: "3730 S Las Vegas Blvd"
      city: "Las Vegas"
      country: "United States"
      link: http://worldcryptocon.com/

**Comment by twolmarans** [comment]
Hey,

having looked at the event's site:

Q: Is this a Bitcoin event?
A: No

Q: Is there a talk focused exclusively on a Bitcoin topic?
A: There is no listed Bitcoin-specific talk

Q: Will there be talks regarding ICO's and/or altcoins? If so, how much time will be dedicated to them in total?
A: Yes, the majority of the conference seems to be ICO/Altcoin related with a few educational talks

Result: I don't think that this is a relevant event.

**Comment by WorldCryptoConference** [comment]
@twolmarans Hey there,

Yes this will primarily be a bitcoin event. The majority of the conference will be focused on education, with very little to do with ICO's and Altcoins.

The intended name for this conference was World Bitcoin Conference but the name was taken, hence a change to the name World Crypto Conference.

The spotlight of talks will be centered around bitcoin. In fact there will be a panel around the bitcoin vs bitcoin cash debate. Please reconsider your decision, as this is absolutely a bitcoin focused event

**Comment by twolmarans** [comment]
Hi There, thanks for your input

I don’t speak on behalf of Bitcoin.com, I just assessed the event from Information on the site. @wbnns is able to make the final call.

I didn’t see mention of Bitcoin and saw (iirc) 5+ Talks/presentations dedicated to ICO’s/altcoins. Only one coin was mentioned by name in the schedule, which was not Bitcoin.

I’m sure your comment above will be noted by the team and taken into consideration.
