### ISSUE TITLE
Blockchain brunch with Ripple & CoinTelegraph

### ISSUE THREAD

**Issue by EliciaT** [bitcoin-dot-org/bitcoin.org#2257]
- date: 2018-04-18
      title: "Blockchain brunchwork w/ Ripple & CoinTelegraph"
      venue: "WeWork"
      address: "600 California St"
      city: "San Francisco"
      country: "US"
      link: "https://brunchwork.com/next-event/?eb_event_id=43694934726" 
      promo code: "GITHUB for 20% off"

**Comment by twolmarans** [comment]
Hey, 

As we want to standardize this;
 
Q: Is this a Bitcoin event?
A: No

Q: Is there a talk focused exclusively on a Bitcoin topic?
A: No

Q: Will there be talks regarding ICO's and/or altcoins? If so, how much time will be dedicated to them in total?
A: It looks like the event is more focused on Ripple.

Result: I don't think that this is a relevant event.
