### ISSUE TITLE
World Blockchain Forum: Security Tokens

### ISSUE THREAD

**Issue by AmandaHendricks** [bitcoin-dot-org/bitcoin.org#2259]
- date: 2018-06-12&13
      title: "World Blockchain Forum: Security Tokens"
      venue: "Metropolitan West"
      address: "639 W 46th St, New York, NY 10036"
      city: "New York"
      country: "United States"
      link: "http://newyork.keynote.ae"

**Comment by AmandaHendricks** [comment]
@wbnns

**Comment by beyourseff** [comment]
Hello there, 
I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:
**Q: Is this a Bitcoin event?**
A: It doesn't appear to be one.

**Q: Is there a talk focused exclusively on a Bitcoin topic?**
A: I could not find the talks.

**Q: Will there be talks regarding ICO's and/or altcoins? If so, how much time will be dedicated to them in total?**
A: It seems that's what the majority of talks will be about.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**

**Comment by AmandaHendricks** [comment]
@beyourseff thank you for your reply. I appreciate the time you took to analyze my event submission(s). Can you please point me to event guidelines of bitcoin.org that stipulate what events are suitable? I’m not seeing where events must be strictly bitcoin focused.
While the event may not be entirely on bitcoin the attending  companies contribute to and rely on the overall success and recognition of bitcoin
