### ISSUE TITLE
ETHworks Progress Meeting (Week of Apr. 1st)

### ISSUE THREAD

**Issue by wbnns** [bitcoin-dot-org/bitcoin.org#2260]
This issue will contain notes from the upcoming Progress Meeting on Friday, April 6th at 15:00 UTC with ETHworks about redesigning Bitcoin.org.

People confirmed to be attending the meeting:

@wbnns (myself)
@marekkirejczyk

**Comment by marekkirejczyk** [comment]
@wbnns Confirmed.

**Comment by wbnns** [comment]
Here's a summary of the latest progress:
https://paper.dropbox.com/doc/ETHworks-Progress-Meeting-yjWoOJiyi43Fyh22CTM4o?_tk=share_copylink

**Comment by wbnns** [comment]
Updated comment with correct link.
