### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by html5zebra** [bitcoin-dot-org/bitcoin.org#2263]
- date: 2018-06-16
      title: "Blockchain Economic Forum"
      venue: "San Francisco Marriott Marquis"
      address: "780 Mission St, San Francisco, CA 94103"
      city: "San Francisco"
      country: "USA"
      link: "bef.latoken.com"

**Comment by beyourseff** [comment]
Hello there, 
I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:
**Q: Is this a Bitcoin event?**
A: Yes (but more 'digital assets' as a whole)

**Q: Is there a talk focused exclusively on a Bitcoin topic?**
A: Yes, there are several talks regarding Bitcoin and/or its underlying technology.

**Q: Will there be talks regarding ICO's and/or altcoins? If so, how much time will be dedicated to them in total?**
A: Yes, there are several.

**Notes:** None

Result: **In my opinion this event should be listed on Bitcoin.org based on the above.**
