### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by FHSG-Blockchain** [bitcoin-dot-org/bitcoin.org#2264]
- date: 2018-11-22
      title: "Forum Blockchain for Business (B4B)"
      venue: "Stadtsaal, Restaurant Lagerhaus - by FHS St. Gallen"
      address: "Davidstrasse 44"
      city: "St. Gallen"
      country: "Schweiz"
      link: "https://www.blockchain4business.ch/"

**Comment by beyourseff** [comment]
Hello there, 
I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:
**Q: Is this a Bitcoin event?**
A: Not quite

**Q: Is there a talk focused exclusively on a Bitcoin topic?**
A: Not that I can see. It's more so focused on applying 'blockchain technology' to existing business.

**Q: Will there be talks regarding ICO's and/or altcoins? If so, how much time will be dedicated to them in total?**
A: Yes. It seems what is meant by 'blockchain technology' is actually ICO-related

**Notes:** I was unable to conclude whether this could be added. The event description is a little vague but from what I read it's more ICO focused than actual Bitcoin technology.

Result: **In my opinion this event should not be listed on Bitcoin.org based on the above.**

**Comment by FHSG-Blockchain** [comment]
Hi there, many thanks for the assessment. The programme has indeed still some space for adjustment as it is still early and the objective is to be able to present an up to date content in November.

Bitcoin itself will be discussed in the morning session as part of an intro to blockchain. 

While checking out some other event listings on bitcoin.org I concluded that it is not a hard requirement to have a bitcoin focus. However if that's the case then the event at hand indeed does not fit.

Cheers

**Comment by FHSG-Blockchain** [comment]
Adding to that in the morning session as well as in the panel at the end of the day ICOs will be discussed in detail. There will be at least two speakers having done an ICO recently. On top of that there will be a regulatory specialist discussing the legal aspects of an ICO. Thus in total there will be at least 3 x 45 min about ICOs.

**Comment by wbnns** [comment]
@FHSG-Blockchain Hello, thanks for submitting this event, however, it seems more focused on launching ICOs, rather than Bitcoin.
