### ISSUE TITLE
There is a mistake in the image

### ISSUE THREAD

**Issue by blockcn** [bitcoin-dot-org/bitcoin.org#2265]
[Bounty](https://github.com/bitcoin-dot-org/bitcoin.org#earn-bitcoin-for-contributing): **7,000 bits / ~$50 USD**

Source File: _data/devdocs/en/references/block_chain.md

There are 30 '0' after 'Threshold 0x1bc330' in the image below:
![20180406210300](https://user-images.githubusercontent.com/37364384/38422574-d8f1f5b6-39dd-11e8-9db6-f53ca61379a7.png)

I think that it's a mistake. And it should be 42 '0' after '0x1bc330'. Just like：
**`Threshold 0x1bc330000000000000000000000000000000000000000000`**
Because of: ( 0x18 -3 ) * 2 = 21 * 2 = 42

**Comment by harding** [comment]
@blockcn good catch!  I agree with your assessment; it's my fault for not doubling the zeros to produce correct hex.
