### ISSUE TITLE
Futurama Blockchain Innovators Summit 2018 Dubai

### ISSUE THREAD

**Issue by coinsbank** [bitcoin-dot-org/bitcoin.org#2267]
- date: 2018-05-03
      title: "Futurama Blockchain Innovators Summit 2018"
      venue: "Meydan Hotel Dubai"
      address: "Meydan Racecourse, Al Meydan Road, Nad Al Sheba"
      city: "Dubai"
      country: "United Arab Emirates"
      link: "https://coinsbank.com/dubai/"

**Comment by beyourseff** [comment]
Hello there, 
I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this a Bitcoin event?**
A: No

**Q: Is there a talk focused exclusively on a Bitcoin topic?**
A: No 

**Q: Will there be talks regarding ICO's and/or altcoins? If so, how much time will be dedicated to them in total?**
A: Yes, this seems to be an event solely focused on ICO's.

**Notes:**Site is broken.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**
