### ISSUE TITLE
New event - Next Block Conference

### ISSUE THREAD

**Issue by NickBesedin** [bitcoin-dot-org/bitcoin.org#2269]
- date: 2018-05-18
      title: "Next Block Conference"
      venue: "Hilton Hotel Kyiv"
      address: "Tarasa Shevchenko Blvd, 30, Kyiv, Ukraine, 01030"
      city: "Kyiv"
      country: "Ukraine"
      link: "http://next-block.org/"

**Comment by beyourseff** [comment]
Hello there, 
I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this a Bitcoin event?**
A: No

**Q: Is there a talk focused exclusively on a Bitcoin topic?**
A: No 

**Q: Will there be talks regarding ICO's and/or altcoins? If so, how much time will be dedicated to them in total?**
A: Yes, this seems to be an event solely focused on ICO's.

**Notes:** Site is broken.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**

**Comment by NickBesedin** [comment]
Thank you for the response, but one of our keynote speakers, Bobby Lee, will speak exclusively about bitcoin. Other speakers will also touch bitcoin eventually. Our speakers do not promote altcoins on the conference. Event is not dedicated solely for ICOs, since there will be parts about cryptocurrency  legislation, in Ukraine and in the world and other blockchain-related topics as well.  Maybe that can change your mind. 

The website seems to work properly, http://next-block.org/ 

Looking forward to your response.
