### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by CarolineMIB** [bitcoin-dot-org/bitcoin.org#2275]
- date: 2018-05-16
      title: "Monaco International Blockchain"
      venue: "Grimaldi Forum"
      address: "10 avenue Princesse Grace"
      city: "Monte-Carlo"
      country: "Principality of Monaco"
      link: "http://monaco-international-blockchain.io/"

**Comment by beyourseff** [comment]
There's precisely 0 information on the topics being discussed at this event so I can't assess whether or not it's suitable for inclusion on the Bitcoin.org events page.

**Comment by CarolineMIB** [comment]
Hi, 

Actually it's all on line on our web site, including the speakers, the topics etc : 

Speakers : http://monaco-international-blockchain.io/speaker/
Day 1 : http://monaco-international-blockchain.io/day-1/
Day 2 : http://monaco-international-blockchain.io/day-2/

Topics : 
Legislation : Regulation as an empowerment to legal industry
Finance : Bank, Finance & Blockchain : ferocious battle or necessary collaboration
Society : Tokenise our world, how can blockchain and tokens enhance your everyday life
Environment : Green your blockchain ; Blockchain as a main tool to as sustainable growth
Hardware : Blockcahin 3.0 how Blockchain changes the web
Urbanization : smart cities will be the blockchain cities
Economy : blockchain the power of decentralization, a new kind of business
Finance : Forecast of the Crypto Market 2018/2019

I hope it helps and that you can reconsider to include Monaco International Blockchain as proper event, 

Thank you, 

Caroline

**Comment by wbnns** [comment]
@CarolineMIB Hello, thanks for the info, however, the website doesn't appear to be loading in some cases (e.g. the speakers page), or is very very slow. Please let us know once this is fixed and we'll review it again.
