### ISSUE TITLE
Remove rpcs from documentation that have been deprecated or removed

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin-dot-org/bitcoin.org#2277]
[Bounty](https://github.com/bitcoin-dot-org/bitcoin.org#earn-bitcoin-for-contributing): **25,000 bits / ~$125 USD**

Many rpcs, such as `getinfo` or account related rpc have been deprecated or already removed from the most recent released version of Bitcoin Core. I'd suggest to remove them as well from the developer documentation.

E.g. "getinfo" https://github.com/bitcoin/bitcoin/blob/0.16/src/rpc/misc.cpp#L448-L458

or all the "account" related calls, which you can find with:
```
git grep account _templates/ _data/ _config.yml _autocrossref.yaml .tx/

**Comment by rudygodoy** [comment]
I believe this has been already addressed by #2980

**Comment by wbnns** [comment]
@rudygodoy 

Hello, yes, thank you for noticing and mentioning.

Cc: @cornelius

**Comment by wbnns** [comment]
@cornelius 

Here's the [transaction ID](https://live.blockcypher.com/btc/tx/07f826ab5227219dc062bbb79343274b07897202185a551b1d2c71bac118f87d/) for the bounty you took down.
