### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by zsoro2** [bitcoin-dot-org/bitcoin.org#2279]
- date: 2018-06-15
      title: "Dmfx financials mini conference"
      venue: " London, United Kingdom"
      address: "BMA House, Tavistock Square"
      city: "London"
      country: "United Kingdom"
      link: "http://dmfx-financials.com/"

**Comment by beyourseff** [comment]
Hello there, 
I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:
**Q: Is this a Bitcoin event?**
A: No, this event/workshop seems to be focused on trading and investing in ICO's/altcoins

**Q: Is there a talk focused exclusively on a Bitcoin topic?**
A: There seems to be one.

**Q: Will there be talks regarding ICO's and/or altcoins? If so, how much time will be dedicated to them in total?**
A: Yes. This event will most likely exclusively focus on teaching attendees invest in altcoins and ICO's.

**Notes:**Has a Forbes logo as a 'Media Partner' but there's no link. All other 'Media Partners' seem to be recently launched 'news' sites which heavily focus on ICO news.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**

**Comment by zsoro2** [comment]
We will be in forbes from 2 weeks now, but we already have a video about the interview.
You can check out here: https://dmfx-financials.com/event
