### ISSUE TITLE
ABC Summit

### ISSUE THREAD

**Issue by ABCSummit18** [bitcoin-dot-org/bitcoin.org#2284]
- date: YYYY-MM-DD
      title: "ABC Summit"
      venue: "Casino Estoril (Lisbon)"
      address: "Av. Dr. Stlanley Ho"
      city: "Estoril"
      country: "Portugal"
      link: "www.abcsummit.com
![facebook_novo_01](https://user-images.githubusercontent.com/38351665/38733550-3784a7ae-3f1a-11e8-9a90-57f4f56b2349.png)
"

**Comment by beyourseff** [comment]
Hello there, 
I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:
**Q: Is this a Bitcoin event?**
A: It seems this event is about the underlying technology 'blockchain'

**Q: Is there a talk focused exclusively on a Bitcoin topic?**
A: Not that I can see, but there are a few talks regarding scalability etc

**Q: Will there be talks regarding ICO's and/or altcoins? If so, how much time will be dedicated to them in total?**
A: I can see one.

**Notes:**It's a little unclear but for now I'm leaning towards having this added to Bitcoin.org

Result: **In my opinion this event could be listed on Bitcoin.org based on the above.**

**Comment by ABCSummit18** [comment]
hi,

thank you for you detailed answer.
So, its already listed?
regards,

Romain


Le 2018-04-17 09:55, beyourseff a écrit :
