### ISSUE TITLE
New event - BTCM2018 @BlockchainHotel

### ISSUE THREAD

**Issue by blockchainhotel** [bitcoin-dot-org/bitcoin.org#2285]
- date: 2018-05-25
      title: "BTCM2018 @BlockchainHotel"
      venue: "BlockchainHotel"
      address: "Friedrich-Ebert-Straße 18"
      city: "Essen"
      country: "Germany"
      link: "https://www.blockchainhotel.de/en/conference/"

**Comment by beyourseff** [comment]
Hello there, 
I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:
**Q: Is this a Bitcoin event?**
A: I'm leaning towards saying yes.

**Q: Is there a talk focused exclusively on a Bitcoin topic?**
A: Yes, a few it seems

**Q: Will there be talks regarding ICO's and/or altcoins? If so, how much time will be dedicated to them in total?**
A: Yes, a few talks will be focused on ICO's.

**Notes:**None

Result: **In my opinion this event could be listed on Bitcoin.org based on the above.**

**Comment by limxdev** [comment]
I think that is a nice meetup.

Kind Regards Christian
