### ISSUE TITLE
Crypto Invest Summit West

### ISSUE THREAD

**Issue by tonywinders** [bitcoin-dot-org/bitcoin.org#2286]
- date: 2018-05-01 to 2018-05-02
      title: "Crypto Invest Summit West"
      venue: "LA Convention Center"
      address: "1201 S Figueroa St, West Hall"
      city: " Los Angeles, CA 90015"
      country: "USA"
      link: "https://cryptoinvestsummit.io/"

![https_ 2f 2fcdn evbuc com 2fimages 2f41443173 2f171387157509 2f1 2foriginal](https://user-images.githubusercontent.com/38301955/38759223-a7c9b496-3f29-11e8-9b4c-16518daba36d.jpg)

Crypto Invest Summit brings to you the who’s who in the cryptocurrency and blockchain space on two stages. Join us for two days of presentations, pitches, educational panels and insightful fireside chats with industry leaders and early bitcoin investors. Speakers include Tim Draper (DFJ), Brock Pierce (Block One & Chairman of the Bitcoin Foundation), Crystal Rose (Sensay) and Matt Sorum (Artbit and Guns ‘N Roses drummer), along with many more. Panels cover social good, legal consideration and regulatory practices, women in blockchain, gaming, crypto marketing, crypto payments, plus many other topics. There will also be an ICO pitch stage and expo.

Dates & Times:
April 30 (pre-registration) at 6 pm
May 1–2 from 7:30 am – 6 pm

Location:
Los Angeles Convention Center, West Hall
1201 South Figueroa St. Los Angeles, CA 90015

Ticket prices:
Single ticket = $499
Team rate (minimum 3) = $249
After April 15 = $999

**Comment by beyourseff** [comment]
Hello there, 
I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:
**Q: Is this a Bitcoin event?**
A: Not really. The focus is more on ICO's based on the agenda.

**Q: Is there a talk focused exclusively on a Bitcoin topic?**
A: Not that I can see.

**Q: Will there be talks regarding ICO's and/or altcoins? If so, how much time will be dedicated to them in total?**
A: Yes, there will be quite a few talks with regards to ICO's, investing in ICO's and the like.

**Notes:**None

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**
