### ISSUE TITLE
iCoin Summit

### ISSUE THREAD

**Issue by 7marketz** [bitcoin-dot-org/bitcoin.org#2291]
- date: 2018-05-09 - 2018-05-10 
      title: "iCoin Summit"
      venue: "Atlantica Oasis Hotel"
      address: "Potamos Yermasoyias 52001"
      city: "Limassol"
      country: "Cyprus"
      link: "https://icoinsummit.com/

![icoin summit banner](https://user-images.githubusercontent.com/38256520/38864324-0a0046a4-4243-11e8-9694-f31a17d54d6e.png)

"

**Comment by beyourseff** [comment]
Hello there, 
I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this a Bitcoin event?**
A: Not in the slightest

**Q: Is there a talk focused exclusively on a Bitcoin topic?**
A: None.

**Q: Will there be talks regarding ICO's and/or altcoins? If so, how much time will be dedicated to them in total?**
A: Yes, fully centered around ICO's.

**Notes:** "world’s first ICO battle, where 16 ICOs will compete for up to $250,000 grand prize"

Result: **In my opinion this event should DEFINITELY NOT be listed on Bitcoin.org based on the above.**
