### ISSUE TITLE
New event - Polish Bitcoin Congress

### ISSUE THREAD

**Issue by Felipeoo** [bitcoin-dot-org/bitcoin.org#2293]
- date: 2018-05-11
      title: "Polish Bitcoin Congress"
      venue: "Sheraton Warsaw Hotel"
      address: "B. Prusa 2, 00-493"
      city: "Warsaw"
      country: "Poland"
      link: "http://congressbitcoin.com/"

**Comment by beyourseff** [comment]
Hello there, 
I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this a Bitcoin event?**
A: Yes, it certainly is

**Q: Is there a talk focused exclusively on a Bitcoin topic?**
A: Yes, the event is fully centered around Bitcoin and/or its underlying technology.

**Q: Will there be talks regarding ICO's and/or altcoins? If so, how much time will be dedicated to them in total?**
A: It seems there aren't any

**Notes:** None

Result: **In my opinion this event should certainly be listed on Bitcoin.org based on the above.**

**Comment by Felipeoo** [comment]
Thank You, we make this event most pro Bitcoin we can, so when it will be add? we waiting 15 days now, and event is in 9 days only

**Comment by beyourseff** [comment]
Unfortunately I cannot add it myself, when @wbnns gets the time to do so, he'll do it.
