### ISSUE TITLE
Blockchain Super Conference

### ISSUE THREAD

**Issue by nplusnetworks** [bitcoin-dot-org/bitcoin.org#2295]
- date: 2018-07-13
      title: "Blockchain Super Conference"
      venue: "Kitchener - Waterloo"
      address: "32 Weber Street West"
      city: "Kitchener - Waterloo"
      country: "Canada"
      link: "https://blockchainsuperconference.com/"

**Comment by beyourseff** [comment]
Duplicate #2303
