### ISSUE TITLE
Decrypted Forum

### ISSUE THREAD

**Issue by vladstan** [bitcoin-dot-org/bitcoin.org#2297]
- date: 2018-11-22/23
      title: "Decrypted Forum"
      venue: "Convention Centre of Palma"
      address: "Carrer de Felicià Fuster, 2, 07006 Palma, Illes Balears"
      city: "Palma de Mallorca"
      country: "Spain"
      link: "https://decryptedforum.com"

**Comment by beyourseff** [comment]
Hello there, 
I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this a Bitcoin event?**
A: It seems to indeed be the case

**Q: Is there a talk focused exclusively on a Bitcoin topic?**
A: There are several talks which focus on a Bitcoin topic.

**Q: Will there be talks regarding ICO's and/or altcoins? If so, how much time will be dedicated to them in total?**
A: I found two (day 1 at 16:00 ? and day 2 at 14:00)

**Notes:** Although there's 2 talks about ICO's it seems the overwhelming majority of talks are Bitcoin-centric. As such, I'm leaning towards having this approved.

Result: **In my opinion this event could be listed on Bitcoin.org based on the above.**
