### ISSUE TITLE
Futurama Blockchain Innovators Summit

### ISSUE THREAD

**Issue by FuturamaDubai** [bitcoin-dot-org/bitcoin.org#2299]
- date: 2018-05-03
    title: "Futurama Blockchain Innovators Summit"
    venue: "Meydan Dubai Hotel"
    address: "Meydan Racecourse Al Meydan Road, Nad Al Sheba"
    city: "Dubai"
    country: "UAE"
    link: "goo.gl/7pCNAz"

**Comment by beyourseff** [comment]
Duplicate #2298 AND #2267. It's still a no from me.

PS: Spamming the event doesn't help guys :/
