### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by maseox** [bitcoin-dot-org/bitcoin.org#2300]
- date: 2018-07-24
      title: "Le bitcoin et les altcoins"
      venue: "Salle Donald Nixon"
      address: "247 avenue de la liberté"
      city: "Paris"
      country: "France"
      link: "https://achat-bitcoin.fr/"

**Comment by beyourseff** [comment]
Hi @maseox, could you point me to the event's agenda and details so I can assess whether or not it's suitable for inclusion on Bitcoin.org?
