### ISSUE TITLE
Future of Digital Assets and Virtual Currency Regulation in the US in 2018: webinar

### ISSUE THREAD

**Issue by AnnaCrypto** [bitcoin-dot-org/bitcoin.org#2302]
- date: 2018-04-25
      title: "Future of Digital Assets and Virtual Currency Regulation in the US in 2018"
      venue: "Online"
      address: "Online"
      city: "Online"
      country: "US"
      link: "http://bit.ly/2JjJ8zh"

**Comment by beyourseff** [comment]
This has already been added (see #2263) and should therefore be closed.
