### ISSUE TITLE
2018 Global Token Galaxy Expo

### ISSUE THREAD

**Issue by chenbaozhu** [bitcoin-dot-org/bitcoin.org#2304]
- date: 2018-5-25-27
      title: 2018 Global Token Galaxy Expo
      venue: 8407 Central Avenue Newark, CA 94560
      address: 8407 Central Avenue Newark, CA 94560
      city: Newark, CA
      country: United States
      link: http://bit.ly/2H8UE42

**Comment by beyourseff** [comment]
Hello there, 
I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this a Bitcoin event?**
A: Nope. All I'm seeing is talks about tokens, ICO's and 'invest in blockchain'

**Q: Is there a talk focused exclusively on a Bitcoin topic?**
A: No

**Q: Will there be talks regarding ICO's and/or altcoins? If so, how much time will be dedicated to them in total?**
A: Yes

**Notes:** N/A

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**
