### ISSUE TITLE
Run with the Unicorns Crypto Conference May 2-3New event

### ISSUE THREAD

**Issue by ritzpdc** [bitcoin-dot-org/bitcoin.org#2305]
Hi!

Here's the event details for the upcoming blockchain conference that coincides with The Kentucky Derby for world class fun and amazing networking and media opportunities. 

http://www.runfortheunicorns.com

Use this discount code to save 10% off all tickets: RUN10

Run With The Unicorns Conference May 2-3 is assembling the top innovators in fintech, ICOs, and blockchain technology in Louisville KY during Derby Week, one of the top world class festivals of the year. Featuring the hottest startups to the Fortune 500 companies showcasing the best digital experiences in all aspects of life and work: from entertainment and brand engagement, to enterprise and industrial, urban and architecture, education and training, government, and commerce. 

We'll have activities planned from April 30 - May 6th so you can enjoy the Kentucky Derby and get networked with all the attendees and the influencers that come to the Derby.

The RUN 2018 Program includes mind-blowing keynotes by industry luminaries, classes and tutorials, products and startup demos, industry use cases, The ICO Competition, Art Gala and reception, talks by 100 industry leaders covering business, technology and design, and exhibits. Do not miss the opportunity to position your company in this world-changing industry, and create awareness among Fortune 500 companies, potential buyers, partners, investors, and the media.

The Kentucky Derby and the Derby Festival is the back drop for Run With the Unicorns, a Blockchain and Fin Tech Conference. It is the oldest and one of the most prestigious events in the world. Over 1.5B people bet on the KY Derby last year. Louisville Kentucky attracts many of the wealthiest people from all over the world Derby Week to celebrate the Kentucky Derby on The First Saturday in May. 

RUN for the Unicorns is the place where baby Unicorns can network and tell their story to investors. RUN 2018 is designed to provide many networking opportunities so you really get to know each other, to form the bond it requires to truly help each other. We are adding top speakers, new Unicorns and investors daily.

Come join us at the Hyatt Regency in the heart of downtown Louisville Derby Week!

RUN for the Unicorns 2018    http://www.runfortheunicorns.com

**Comment by beyourseff** [comment]
This event has already started, but nevertheless: I don't think it should be added to Bitcoin.org due to its focus on ICO's (it's got a whole ICO competition etc).
