### ISSUE TITLE
DAPPHack

### ISSUE THREAD

**Issue by 67tallchris** [bitcoin-dot-org/bitcoin.org#2309]
- date: 2018-06-01
      title: "DAPPHack"
      venue: "Space at Grant Park"
      address: "318 Cherokee Ave, Suite 108 GA"
      city: "Atlanta"
      country: "United States"
      link: "https://www.ticketbase.com/events/dapphack"

**Comment by beyourseff** [comment]
Hello there, 
I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

**Notes:** This is a hackaton focused on building DAPPs on Ethereum, not Bitcoin and/or its underlying technology. 

Result: **In my opinion this event should/should NOT be listed on Bitcoin.org based on the above.**
