### ISSUE TITLE
BCI Summit

### ISSUE THREAD

**Issue by bflynn4141** [bitcoin-dot-org/bitcoin.org#2310]
- date: June-12-2018 - June-13-2018
      title: "BCI Summit"
      venue: "The Metropolitan"
      address: "123 West 18th St."
      city: "New York"
      country: "United States"
      link: "bcisummit.com"

**Comment by beyourseff** [comment]
Hello there, 
I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this a Bitcoin event?**
A: No. This is moreso a 'Crypto Diversification/trading' event.

**Q: Is there a talk focused exclusively on a Bitcoin topic?**
A: Not that I can tell

**Q: Will there be talks regarding ICO's and/or altcoins? If so, how much time will be dedicated to them in total?**
A: Yes, the overwhelming majority of talks will be about diversifying into altcoins - including ICO's

**Notes:** N/A

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**

**Comment by rollinglow19** [comment]
#TlME
