### ISSUE TITLE
Policy on adding new resources?

### ISSUE THREAD

**Issue by soundasleep** [bitcoin-dot-org/bitcoin.org#2312]
Is there a policy for adding new resources and services to your [list of Bitcoin resources](https://bitcoin.org/en/resources)? I'd love to add [CryptFolio](https://cryptfolio.com) as a portfolio management service, but understand if you'd like to keep the list short and curated. Thanks!

**Comment by wbnns** [comment]
@soundasleep Hello, yes, we need at least a few other resources that fit in the section before adding the new category.
