### ISSUE TITLE
CoinAgenda Asia

### ISSUE THREAD

**Issue by Erikazee** [bitcoin-dot-org/bitcoin.org#2313]
- date: 2018-06-21 to 2018-06-23
      title: "CoinAgenda Asia"
      venue: "Shangri-La Hotel"
      address: "22 Orange Grove Road, 258350, Singapore"
      city: "N/A"
      country: "Singapore"
      link: "http://coinagenda.com/"

**Comment by beyourseff** [comment]
No agenda yet so I can't assess whether or not it's suitable for inclusion on Bitcoin.org

**Comment by Erikazee** [comment]
Hi there, thanks for the reply! We have posted a rough agenda here: http://coinagenda.com/agenda.html Our past speakers are listed on the site as well and we are some of the best in the industry.

**Comment by wbnns** [comment]
@Erikazee Hello, thanks - we also would need a venue and address before we could complete the review. Please let us know once those are available as well.

**Comment by Erikazee** [comment]
Hi there! We posted the venue at the bottom of the site, also accessible if you click venue at the top. It will be at the Shangri-La Hotel - 22 Orange Grove Road, 258350, Singapore

**Comment by Erikazee** [comment]
Hello, checking in here to see if you need anything else for us to be listed?
