### ISSUE TITLE
The New Era of FinTech Powered by Blockchain

### ISSUE THREAD

**Issue by EPNex** [bitcoin-dot-org/bitcoin.org#2315]
- date: 2018-05-09
      title: "The New Era of FinTech Powered by Blockchain"
      venue: "University of Amsterdam"
      address: "New Achtergracht 170, 1018WV"
      city: "Amsterdam"
      country: "The Netherlands"
      link: "https://www.blockchainevent.info/"
![english2](https://user-images.githubusercontent.com/37392298/39352233-b18fb0c6-4a36-11e8-883a-f0ec844131bd.jpg)
![01](https://user-images.githubusercontent.com/37392298/39352240-b7338070-4a36-11e8-8caa-ef5e950ee352.jpg)
![02](https://user-images.githubusercontent.com/37392298/39352241-b78bd9c8-4a36-11e8-9cfd-d35e36f8edf2.jpg)
![03](https://user-images.githubusercontent.com/37392298/39352242-b7e1bab4-4a36-11e8-87ca-58b152714284.jpg)
![693415897282200098](https://user-images.githubusercontent.com/37392298/39352246-b8376554-4a36-11e8-83be-d8ce87582e9d.jpg)
![05](https://user-images.githubusercontent.com/37392298/39352248-b93b3ba6-4a36-11e8-8f22-f35e8188b825.jpg)
![dean](https://user-images.githubusercontent.com/37392298/39352249-b992dabe-4a36-11e8-8c72-e752c5a0960a.jpg)
![rodger](https://user-images.githubusercontent.com/37392298/39352250-b9e534d0-4a36-11e8-82d4-504fa73a3f09.jpg)

**Comment by beyourseff** [comment]
Hello there, 
I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this a Bitcoin event?**
A: No

**Q: Is there a talk focused exclusively on a Bitcoin topic?**
A: No

**Q: Will there be talks regarding ICO's and/or altcoins? If so, how much time will be dedicated to them in total?**
A: Yes, seems to be focused on epnex.io which is powered by NEO.

**Notes:** Focuses on acquiring people who'll trade on epnex.io, not really informative or useful.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**
