### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by yuliasophie** [bitcoin-dot-org/bitcoin.org#2316]
- date: 2018-05-03
      title: "Стартапам – быстрые деньги, инвесторам – качественные стартапы. Вебинар о новом проекте Ника Евдокимова Token Roadshow"
      venue: ""
      address: ""
      city: "Moscow"
      country: "Russia"
      link: "https://www.youtube.com/channel/UCzvjUJbJsJxI6vCpSyvRBIA "

**Comment by beyourseff** [comment]
"Token Roadshow", no agenda or website.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**
