### ISSUE TITLE
Vinnytsia CryptoCoin Conference 2018

### ISSUE THREAD

**Issue by MaximusPro** [bitcoin-dot-org/bitcoin.org#2319]
- date: 2018-05-26
      title: "Vinnytsia CryptoCoin Conference 2018 is a conference for supporters of crypto industry development. One of the major conferences in the city, which will bring together experts and associates of this area to tell about the new technologies that are currently being used in decentralized systems in the market."
      venue: "Hotel Optima"
      address: "str. Kievskaya 50A"
      city: "Vinnytsia"
      country: "Ukraine"
      link: "http://cryptoevents.vn.ua/"

**Comment by beyourseff** [comment]
Focuses on ICO's and trading, not related to Bitcoin and/or its underlying technology.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**
