### ISSUE TITLE
Bitcoin & Cryptocurrencies - Workshop

### ISSUE THREAD

**Issue by EurekaF** [bitcoin-dot-org/bitcoin.org#2320]
2018-06-28
Bitcoin & Cryptocurrencies Training Course 
Venue: TBA
Address: Central London
City: London
Country: UK
http://www.eurekafinancial.com/courses/278.html

**Comment by beyourseff** [comment]
Focuses on trading and investing in ICO's. Not a Bitcoin and/or underlying technology event.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**

**Comment by EurekaF** [comment]
Hi, 

Did you have a chance to look at my comments below? Can you please reconsider listing our event on your website? As mentioned it does cover blockchain and other cryptocurrencies. Once again here is the link to the detailed programme:  http://www.eurekafinancial.com/courses/278.html#outline <http://www.eurekafinancial.com/courses/278.html#outline>

And here the details for the listing: 

Bitcoin & Cryptocurrencies
28 Jun 2018, London 
http://www.eurekafinancial.com/courses/278.html#details <http://www.eurekafinancial.com/courses/278.html#details>

I look forward to hearing from you soon. 

Kind regards, 

Aldona Puchalska
Eureka Financial
+44 207 993 8597
http://www.eurekafinancial.com
