### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by acantinellipaiva** [bitcoin-dot-org/bitcoin.org#2328]
- date: 2018-05-05
      title: "Conferência Brasileira Sobre Bitcoin e Criptomoedas"
      venue: "World Trade Center"
      address: "Av. das Nações Unidas, 12551 - Cidade Monções"
      city: "São Paulo"
      country: "Brasil"
      link: "http://www.bitconf.com.br/2018SP/"

**Comment by wbnns** [comment]
Duplicate of #2282
