### ISSUE TITLE
Embedded Video black bars (Redesign)

### ISSUE THREAD

**Issue by squawk77** [bitcoin-dot-org/bitcoin.org#2335]
- The Video on the homepage plays with small black bars at the top and bottom.

BTW:
I am a german native speaker and I saw some a little bit strange sounding german translations and I would like to help. How can I make directly suggestions (edit text) for translation improvements?
(Sorry I am new to github)

**Comment by wbnns** [comment]
@squawk77 Thanks for reporting this issue! It should now be fixed. Regarding translations, [here's how you can get involved](https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/docs/assisting-with-translations.md).

If you have any questions, please let us know.
