### ISSUE TITLE
New Event

### ISSUE THREAD

**Issue by Yacine-krk** [bitcoin-dot-org/bitcoin.org#2340]
- date: 2018-12-01
      title: "Achat Bitcoin et régulation en France"
      venue: ""
      address: ""
      city: "Paris"
      country: "France"
      link: "http://acheterbitcoin.pro"

**Comment by wbnns** [comment]
@Yacine-krk Please let us know when a venue and address are available for this event so that we can finish reviewing it for potential inclusion on the website.

**Comment by Yacine-krk** [comment]
Hello @wbnns 

Please find below the information :

Address : 66 Avenue des Champs Elysées, 75008, Paris
Venue : Still to be defined. But there will be a hostess to indicate the conference room.

Thanks !
