### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by MaximusPro** [bitcoin-dot-org/bitcoin.org#2345]
- date: 2018-05-26
      title: "Vinnytsia CryptoCoin Conference 2018"
      venue: "Hotel Optima"
      address: "str. Kievskaya 50"
      city: "Vinnytsia"
      country: "Ukraine"
      link: "http://cryptoevents.vn.ua/"

**Comment by wbnns** [comment]
@MaximusPro This event seems more focused on ICOs and cryptotrading, rather than Bitcoin.
