### ISSUE TITLE
BlockChainConf.Tech

### ISSUE THREAD

**Issue by vincentmayers** [bitcoin-dot-org/bitcoin.org#2348]
- date: 2018-09-06
      title: "BlockChainConf.Tech"
      venue: "Cobb Galleria Centre"
      address: "2 Galleria Pkwy SE"
      city: " Atlanta"
      country: "USA"
      link: "http://blockchainconf.tech/"

**Comment by wbnns** [comment]
@vincentmayers Please let us know once an agenda becomes available, so that we can finish reviewing the event for potential inclusion.

**Comment by vincentmayers** [comment]
Thanks will do. 


Cheers
Vincent 

@vincentmayers
