### ISSUE TITLE
Distributed 2018

### ISSUE THREAD

**Issue by Briters21** [bitcoin-dot-org/bitcoin.org#2349]
- date: 2018-07-19 & 2018-07-20
      title: Distributed 2018
      venue: Westin St. Francis 
      address:  335 Powell St, San Francisco, CA 94102
      city: San Fransisco
      country: United States
      link: http://2018.distributed.com/

**Comment by wbnns** [comment]
@Briters21 This event seems more focused on DLT and tokenization rather than Bitcoin.

**Comment by Briters21** [comment]
This is a blockchain event, and we at BTC media put out Ybitcoin magazine.  Our two tracks at this event are: 

- Foundations of Distributed Business and the New Global Enterprise.
- Groundbreaking protocols & potential tokenization.
