### ISSUE TITLE
Some redesign bugs

### ISSUE THREAD

**Issue by Cobra-Bitcoin** [bitcoin-dot-org/bitcoin.org#2352]
These should be quick fixes, they're just issues I've noticed or had people report to me:

- The "Donate Community:" text and "Donate" button at the footer should be hidden on mobile/tablet, because clicking it launches the donation modal, which isn't optimized for mobile devices.
- There is an overlap on tablet of the language selection menu with the navigation menu: https://i.imgur.com/2wT1n2G.png.
- People think there is too much space taken up by the top portion of the site, and I think that's true, we need to shrink this space more so we can fit more content on screen at first glance: https://i.imgur.com/BxHJqCr.png.
- Notice on the current site, on a page where the side menu is present, when you scroll all the way to the bottom, it doesn't disappear (https://bitcoin.org/en/full-node). However on the redesign, scrolling all the way to the bottom of a page makes the side menu suddenly disappear awkwardly: https://i.imgur.com/oJZc4K8.png.

We're getting pretty close to going live, so let's keep up the great work and get these last few bugs fixed. 👍

**Comment by Cobra-Bitcoin** [comment]
- Make the entire box clickable, not just the small area around the wallet icon: https://i.imgur.com/8bvnOEm.png.
- Overlap issue on mobile on the about page: https://i.imgur.com/pdjl2GJ.png.

**Comment by Cobra-Bitcoin** [comment]
- https://twitter.com/janeygak/status/991927379302932485

**Comment by wbnns** [comment]
@Cobra-Bitcoin Thanks. Relabeling these for reference:

> 1. The "Donate Community:" text and "Donate" button at the footer should be hidden on mobile/tablet, because clicking it launches the donation modal, which isn't optimized for mobile devices.
> 2. There is an overlap on tablet of the language selection menu with the navigation menu: https://i.imgur.com/2wT1n2G.png.
> 3. People think there is too much space taken up by the top portion of the site, and I think that's true, we need to shrink this space more so we can fit more content on screen at first glance: https://i.imgur.com/BxHJqCr.png.
> 4. Notice on the current site, on a page where the side menu is present, when you scroll all the way to the bottom, it doesn't disappear (https://bitcoin.org/en/full-node). However on the redesign, scrolling all the way to the bottom of a page makes the side menu suddenly disappear awkwardly: https://i.imgur.com/oJZc4K8.png.
> 5. Make the entire box clickable, not just the small area around the wallet icon: https://i.imgur.com/8bvnOEm.png.
> 6. Overlap issue on mobile on the about page: https://i.imgur.com/pdjl2GJ.png.
> 7. https://twitter.com/janeygak/status/991927379302932485

For:

1. The donation button has been removed. The text is still there, it fits (side note: We are going to change this text to "Support Bitcoin.org" instead of "Donate Community").
2. What device was this on? I'm not seeing the issue on an iPad or iPad Pro (https://cl.ly/rUY0)
3. I've decreased the size by 20%, please LMK what you think (before: https://cl.ly/rUE2 after: https://cl.ly/rVC4)
4. I'm unable to replicate this issue (https://cl.ly/rV2o), what OS, browser and version are you using?
5. @alexcherman, please fix. cc: @marekkirejczyk
6. What mobile device and browser are you using? I was unable to replicate the problem on an iPhone or Pixel 2.
7. This is related to there not being Farsi strings, it's an issue with translation coverage (not the redesign).

**Comment by Cobra-Bitcoin** [comment]
I tested on Firefox, with the Tor browser and resized the window to simulate mobile, tablet and desktop experiences (as well as using the built-in simulator of specific devices). Has there been a thorough check of the design across Chrome, IE, Safari and Firefox (on Linux, Windows, macOS, Android & iOS) yet? I know it's a lot of effort to check across every different OS / browser combination, but there could be stuff we haven't spotted yet. Mostly seems to work well though, these are just minor issues more or less.

The decreased size looks much better by the way. 👍

**Comment by wbnns** [comment]
@Cobra-Bitcoin Ok, thanks. Yes, we're testing with [Browser Stack](https://www.browserstack.com/start).

**Comment by wbnns** [comment]
@Cobra-Bitcoin Hey, just following up on this. All of these items are resolved with the exception of number 5, which is currently being discussed in the following thread:
https://github.com/bitcoin-dot-org/bitcoin.org/issues/2347#issuecomment-390206856
