### ISSUE TITLE
Adding the https://www.abolishthebitlicense.org to the Learning Ressources

### ISSUE THREAD

**Issue by theochino** [bitcoin-dot-org/bitcoin.org#2360]
As Bitcoin is being attacked, this resources is about pushing back with knowledge and facts.

I have included all the videos that show the technology without using a computer (to show that it is not required to have a computer to mine, create a private key, send a transaction.)

I also including all the trial documents that exist and all the legislative hearing I can find on video and it's also a resource for those going to see their legislators to explain bitcoin and lawyers to understand bitcoin and to figure out whether or not it is relevant to their case.

The website is https://www.abolishthebitlicense.org

You closed #2146 without contacting me. 

Theo

**Comment by wbnns** [comment]
@theochino Hello, I replied to you in #2146 - we can reopen it if others think it should still be added to the resources section (or another part of the site).
