### ISSUE TITLE
Blockchain Connect Conference 

### ISSUE THREAD

**Issue by masondusvinsight** [bitcoin-dot-org/bitcoin.org#2361]
Date: Jun 26-27 2018
Title: Blockchain Connect Conference 
Venue: San Joes Convention Center
Address: 150 W San Carlos St,
City: San Joes
State: California
Country: United State
Link: http://goblockchainconnect.com/

**Comment by wbnns** [comment]
@masondusvinsight This event doesn't seem to be very focused on Bitcoin:

![image](https://user-images.githubusercontent.com/1130872/40174991-00aa0b36-5994-11e8-9160-ca25e463f1bb.png)
