### ISSUE TITLE
The Crypo Summit Mallorca

### ISSUE THREAD

**Issue by frankelo** [bitcoin-dot-org/bitcoin.org#2363]
- date: 2018-05-23 - 2018-05-25
      title: The Crypto Summit Mallorca
      venue: Palma deMallorca
      address: Av. d'Amèrica, 2, 07600 Palma, Illes Balears, Spanien
      city: 07600 Palma
      country: Illes Balears, Spain
      link: https://www.thecryptosummit.com/
![cathedrale_2](https://user-images.githubusercontent.com/39257463/39982855-fc84796e-5755-11e8-9ef4-d91b8f499a2a.jpg)

**Comment by wbnns** [comment]
@frankelo There's no mention of Bitcoin on the event website, and the agenda seems focused on ICOs and high-level cryptocurrency speculation.
