### ISSUE TITLE
tokenomics

### ISSUE THREAD

**Issue by moonwalker322** [bitcoin-dot-org/bitcoin.org#2365]
- date: 2018-05-23
      title: "TOKENOMICS — is a unique conference fully devoted to token-based economy."
      venue: "Tallinn University 
of Technology"
      address: "Ehitajate tee 5, 12616 Tallinn"
      city: "Tallinn"
      country: "Estonia"
      link: "http://iskander.events"

**Comment by wbnns** [comment]
@moonwalker322 This event doesn't appear to be directly related to Bitcoin, and is focused mainly on tokens.
