### ISSUE TITLE
Blockchain Conference

### ISSUE THREAD

**Issue by canblockchainhub** [bitcoin-dot-org/bitcoin.org#2367]
- date: 2018-07-13 - 2018-07-15
      title: Blockchain Conference
      venue: Kitchener-Waterloo Innovation Centre
      address: 283 Duke Street West 
      city: Kitchener
      country: Canada
      link: https://blockchainsuperconference.com

**Comment by wbnns** [comment]
@canblockchainhub This event is already listed on the website.
