### ISSUE TITLE
LivesOne World Conference

### ISSUE THREAD

**Issue by Maxthon2018** [bitcoin-dot-org/bitcoin.org#2373]
- date: 2018-06-14
      title: "LivesOne World Conference"
      venue: "Singapore Suntec Exhibition Centre"
      address: "Raffles Boulevard Suntec City Singapore 039593 Singapore"
      city: "Singapore"
      country: "Singapore"
      link: "https://www.facebook.com/events/168768363808935/"

**Comment by wbnns** [comment]
@Maxthon2018 This event doesn't appear to have any relation to Bitcoin.
