### ISSUE TITLE
Bitcoin meetup Gent 72 Sint Paulus

### ISSUE THREAD

**Issue by exbu** [bitcoin-dot-org/bitcoin.org#2382]
- date: 2018-05-24
      title: "Bitcoin meetup Gent 72 Sint Paulus"
      venue: "Parochiehuis Sint-Paulus"
      address: "Patijntjestraat 27"
      city: "Gent"
      country: "Belgium"
      link: "https://cryptospot.be/2018/05/15/gent-bitcoin-meetup-72/"

**Comment by dlqls33** [comment]
m
