### ISSUE TITLE
Nothing happens when I execute bitcoind

### ISSUE THREAD

**Issue by ronsonntag54** [bitcoin-dot-org/bitcoin.org#2389]
Installation went smoothly. Blockchain data downloaded in 1.5 days. GUI client runs without any issues. But, when I go to command prompt, navigate to d:\program files\bitcoin\daemon and execute bitcoind.exe, nothing happens. I get no feedback and the command window cursor just sits below the execution line. I have tried with both -datadir=[data path] and without.

**Comment by achow101** [comment]
This is intended behavior. bitcoind does not output anything to the terminal. You can check if it is running by opening another command prompt and using bitcoin-cli to send it commands.

**Comment by ronsonntag54** [comment]
That is not what the documentation says. It stated that I should have received a message upon startup.

**Comment by achow101** [comment]
Where does it say that so we can fix it?

**Comment by ronsonntag54** [comment]
https://en.bitcoin.it/wiki/Running_Bitcoin#Windows indicates has out of date configuration screens for the GUI-Settings, and doesn't mention anything about having to open up a second command window after executing bitcoind.exe.

https://bitcoin.org/en/full-node#windows-10, in the Bitcoin Core Daemon section, states: "If you installed Bitcoin Core into the default directory, type the following at the command prompt: c:\Program files\Bitcoin\daemon\bitcoind

Bitcoin Core daemon should start and print a message that Bitcoin Core is starting."

This is followed by a section on bitcoin-cli without any mention that a second command prompt window must first be opened.

**Comment by wbnns** [comment]
@ronsonntag54 Understood, thanks for the clarification. Opened #2390 to remove the statement regarding the confirmation message

We do not maintain the wiki, however, if you'd potentially be interested in updating that documentation, [here's a link where you can get register](https://en.bitcoin.it/w/index.php?title=Special:CreateAccount&returnto=Main+Page).
