### ISSUE TITLE
To reopen #2146

### ISSUE THREAD

**Issue by theochino** [bitcoin-dot-org/bitcoin.org#2398]
https://AbolishTheBitlicense.org is an integral part of the echosystem and it is a primer ressource for lawyers in term of defending clients.

When they go to bitcoin.org they get lost. AbolishTheBitlicense.org is a ressources for the whole United States and also explain the legalese to those outside the United States.

https://www.abolishthebitlicense.org/lawsuits/

This should be make prominent .... 

By the way, the NY thing is http://article78againstNydFs.com

**Comment by wbnns** [comment]
@theochino Hello, thanks for following up. As mentioned on #2146, if others would like to reopen the issue, we can do that - but let's keep the conversation focused there so that there's a common thread everyone can follow.
