### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by jjyano** [bitcoin-dot-org/bitcoin.org#2399]
- date: 2018-06-28
      title: "Capital Raising & Investing in the Age of Blockchain"
      venue: "Studio450"
      address: "450 West 31st Street, New York, NY 10001"
      city: "New York"
      country: "United States"
      link: "https://www.eventbrite.com/e/capital-raising-investing-in-the-age-of-blockchain-tickets-46366920708?aff=bitcoinorg"

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: Not the case.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: Not that I can tell.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: The talks will be focused on blockchain and cryptocurrencies in general.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**

**Comment by jjyano** [comment]
Hi there,

Thanks for getting back to me.

The two fireside chats and the panel will all focus on Bitcoin and the
entire event focuses on institutional investments in digital currencies.
Additionally, the events listed on Bitcoin.org do not all specifically
relate to Bitcoin specifically. Rather, they discuss a wide array of
topics.

https://bitcoin.org/en/events

Thanks,
Jason

--
Jason Yanowitz
The BlockWorks Group <http://blockworksgroup.io/>
c. (415) 497-9715
Schedule a Meeting <http://calendly.com/jasonyanowitz>

**Comment by wbnns** [comment]
@jjyano Hello, if there's a particular event listed that doesn't seem related to bitcoin, please let us know so we can take a second look. With regard to this one, there's no mention of bitcoin or fireside chats on the Eventbrite page.
