### ISSUE TITLE
Blockchain Life 2018

### ISSUE THREAD

**Issue by BlockchainLife2018** [bitcoin-dot-org/bitcoin.org#2405]
- date: 2018-November-7-8
      title: "Blockchain Life 2018"
      venue: "ExpoForum"
      address: "Peterburgskoye road , 64 lit. А, St-Petersburg, 196140"
      city: "St-Petersburg"
      country: "Russia"
      link: "https://blockchain-life.com/ru/"

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: Not the case.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: No.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: The majority of talks will be focused on blockchain, ICO and ICE.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**

**Comment by BlockchainLife2018** [comment]
Hello!

Sorry, there are a lot of conversations about Bitcoin, for an example one of the discussions will be "The future of Bitcoin: will some coin substitute it or not?" and we have a round table about bitcoin and his forks 

And, eventually, it would be the biggest event in Europe on bitcoin and cryptocurrency
Please, add us

**Comment by wbnns** [comment]
@BlockchainLife2018 Thanks for following up. On the website, it doesn't seem clear that there are a lot of conversations about bitcoin. There was only the one mention you noted above relating to what bitcoin may/may not be replaced by, next. This, coupled with the large amount of ICO-related hype and content is the issue.
