### ISSUE TITLE
Blockchain Futurist Conference

### ISSUE THREAD

**Issue by untraceableevents** [bitcoin-dot-org/bitcoin.org#2406]
Date: August 14 - 16 2018 
Title: Blockchain Futurist Conference
Venue: Rebel Entertainment Complex
Address: 11 Polson St, Toronto, ON M5A 1A4
City: Toronto
Country: Canada
Website: https://futuristconference.com/
![futurist-logo-website](https://user-images.githubusercontent.com/39775767/40738304-34a60d04-6411-11e8-8a49-3072c9624efe.jpg)

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: No.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: Not that I can tell.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: It's a blockchain-centric event.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**
