### ISSUE TITLE
Blockchain Leadership Summit

### ISSUE THREAD

**Issue by julykoshevaya** [bitcoin-dot-org/bitcoin.org#2409]
- date: 2018-11-23
      title: "Blockchain Leadership Summit"
      venue: Congress Center
      address: Messepl. 21, 4058
      city: Basel
      country: Switzerland
      link: https://swissblockchainsummit.com/
![logopr 1](https://user-images.githubusercontent.com/39798433/40780824-6f61c182-64e2-11e8-83e8-4849f820d761.png)
"

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: Not the case.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: Not that I can tell.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: The majority of talks are focused on Blockchain.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**
