### ISSUE TITLE
31st Materials Science and Engineering Conference: Advancement & Innovations

### ISSUE THREAD

**Issue by dave123456666** [bitcoin-dot-org/bitcoin.org#2410]
- date: 2018-10-15
      title: "31st Materials Science and Engineering Conference: Advancement & Innovations"
      venue: "Radisson Blu Seaside Hotel, Helsinki"
      address: "Ruoholahdenranta, 3 00180 - Helsinki Finland "
      city: "Helsinki "
      country: "Finland "
      link: "https://materialscience.materialsconferences.com"

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: No.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: No.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: This event is about 'sustainable new materials and recycling technology'.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**
