### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by fiestoon** [bitcoin-dot-org/bitcoin.org#2413]
- date: 2018-10-29
      title: "ExpoBlockchain"
      venue: "EXPOBLOCKCHAIN.CO 2018, in this version The Blockchain Virtual Fair, the world’s first specialized virtual fair, will take place from October 29 to November 3. 2018. This innovative social business experience, based on current interconnectivity systems, provides both exhibitors and visitors, through the AVATAR 3D technology experience, the opportunity to promote and learn about new products, trends and services related to Blockchain technology and interact and generate business contacts in real time, from a smartphone, a computer or a tablet."
      address: "Virtual event"
      city: "Bogotá"
      country: "Colombia"
      link: "https://expoblockchain.co/site/"

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: Not the case.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: No.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: The majority of talks will be focused on blockchain.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**
