### ISSUE TITLE
Add  "₿" utf-8 symbol in german glossar 

### ISSUE THREAD

**Issue by halferemite** [bitcoin-dot-org/bitcoin.org#2414]
"Die Abkürzung BTC wird häufig als Einheit für Bitcoin (**B⃦**). verwendet (1 BTC = 1 Bitcoin)."

add  ₿ utf-8

https://bitcoin.org/de/glossar#btc

**Comment by TheRec** [comment]
Submitted a PR which fixes other translations too.

I've also noticed that not all translations use the symbol, so they are not all consistent, it might be a good idea to update them in another issue maybe... especially the English version which does not mention it at all.
