### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by manekenen** [bitcoin-dot-org/bitcoin.org#2417]
- date: 2018-10-11
      title: "Top10 Hall of Fame"
      venue: "Casa Llotja de Mar"
      address: "Passeig d'Isabel II, 1, 08003"
      city: "Barcelona"
      country: "Spain"
      link: "http://top10.bzntm.com/"

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: Not that I can tell.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: Not the case.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: The event appears to revolve around blockchain.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**
