### ISSUE TITLE
BLOCKCHAIN VISIONNAIRE SUMMIT

### ISSUE THREAD

**Issue by PolinaRay07** [bitcoin-dot-org/bitcoin.org#2425]
2018-07-23
      BLOCKCHAIN VISIONNAIRE SUMMIT
      Kalkscheune
      Johannisstr. 2
      Berlin
      Germany
      http://blockchainvis.co
![blockchainvis](https://user-images.githubusercontent.com/40062708/41158335-3a6de942-6b31-11e8-8e53-82ad7ab5e302.jpg)

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: Not the case.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: No.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: The majority of talks will be centered on blockchain.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**
