### ISSUE TITLE
Redesign Feedback - Bug

### ISSUE THREAD

**Issue by jdabs** [bitcoin-dot-org/bitcoin.org#2429]
Bug happens on this page:

https://bitcoin.org/en/faq#more-help

At the very bottom, the link for "Wiki FAQ" sends a weird MIME type and shows a popup to download. I'm using Firefox v. 60.0.1 on Windows 7 x64. See attached.
![bitcoin-org-wiki](https://user-images.githubusercontent.com/6774432/41168743-e3c7f892-6b14-11e8-8fc3-96c5f99c9f66.jpg)

**Comment by wbnns** [comment]
@jdabs 

Hello, thanks for reporting this issue. It looks like the page that the link pointed to has changed (the wiki is prompting the dialog; it's not coming from bitcoin.org). We've updated the link to point to the correct page (#2430).
