### ISSUE TITLE
The 2018 CoinsBank Mediterranean Blockchain cruise

### ISSUE THREAD

**Issue by dmvishnyak** [bitcoin-dot-org/bitcoin.org#2432]
date: 2018-09-07
    title: "The 2018 CoinsBank Mediterranean Blockchain cruise"
    venue: "Barcelona (Spain), Monaco (Monte Carlo), Ibiza"
    country: "Spain, Monte Carlo, Ibiza"
    link: "https://coinsbank.com/cruise-europe"

![cruise6](https://user-images.githubusercontent.com/40112670/41190744-15b9b18c-6bed-11e8-85fc-bbfc62591ae6.png)

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: Not that I can tell.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: Not the case.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: The event is centered on blockchain.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**
