### ISSUE TITLE
Change version number on windows download page 

### ISSUE THREAD

**Issue by dsparks06** [bitcoin-dot-org/bitcoin.org#2434]
Change version number on windows download page on bitcoin.org

Windows Instructions
Windows 10
*Instructions for Bitcoin Core 0.14.2 on Windows 10
https://bitcoin.org/en/full-node#windows-instructions

**Comment by wbnns** [comment]
@dsparks06 Hello, I've added a clarification (#2709) that it is for 0.14.2 and higher.
