### ISSUE TITLE
Outdated translation

### ISSUE THREAD

**Issue by Komodorpudel** [bitcoin-dot-org/bitcoin.org#2442]
Hey guys,

I currently have a lot of time and thought about getting started with the German translation of the developer documentation.
Unfortunately, I am wondering if there is any reason to do it all. Almost 8 months ago, I translated the last big chunk of new strings for bitcoin.org, but as of today they are still not present on the website. Not even talking about changes before that… Pretty sure this is also the case for translations into other languages.

(@wbnns  : We talked about this last year via email if I recall correctly)

I don’t really mind if there are a more important topics open (such as the redesign), causing the translations not to be up-to-date. But are there any plans to update the translations in the (near) future? Otherwise it feels like wasted time to translate the documentation at the moment.

Best regards,

Simon

**Comment by wbnns** [comment]
@Komodorpudel Hello, you're absolutely right - the translations need to be updated and have fallen behind. For my part, I apologize, I have not had the time available to catch them up. That said, now that the new design has gone live I'll be focusing on this (imminently), among other things.
