### ISSUE TITLE
Blockchain Day Online 2018

### ISSUE THREAD

**Issue by Blockchainday** [bitcoin-dot-org/bitcoin.org#2443]
- date: "2018-06-22 - 2018-06-24" 

THE CONFERENCE "BLOCKCHAIN DAY ONLINE" 
WILL BE HELD ON JUNE 22-24, 2018 AT 16:00 - 22:00 (GMT + 3)"

    -  link: "http://blockchainday.org/"
    -  venue: "Kyiv"
    -  country: "Ukraine"

THE CONFERENCE THAT WILL REVERT YOUR REPRESENTATIVE OF THE WORLD OF BLOCKCHAIN. 
IN THE PROGRAM THE BEST SPEAKERS - EXPERTS WITH INTERNATIONAL NAME. 
WILL BE DIFFICULT, BUT - INTERESTING. 
ONLY PRACTICE, ONLY HARDWORK. 

ARE YOU READY?

![_ - 1new_angl](https://user-images.githubusercontent.com/32510756/41229357-5b42e0a0-6d84-11e8-9e2b-e76c05b52cb1.jpg)

**Comment by wbnns** [comment]
@Blockchainday Hello, thanks for the submission. At this time the Events page doesn't incorporate online-only events. A physical location with an address is needed in order to potentially add an event.
