### ISSUE TITLE
Blockchain Nation Las Vegas

### ISSUE THREAD

**Issue by bcnation** [bitcoin-dot-org/bitcoin.org#2444]
- date: 2018-10-09
      title: "Blockchain Nation Las Vegas"
      venue: "Paris Hotel and Casino"
      address: "3655 S Las Vegas Blvd, Las Vegas, NV 89109"
      city: "Las Vegas"
      country: "USA"
      link: "[https://www.bcnation.com](https://www.bcnation.com)"
![lasvegasbanner](https://user-images.githubusercontent.com/37531920/41383791-78e79c82-6f40-11e8-8391-8611a844665a.jpg)

**Comment by wbnns** [comment]
@bcnation 

Hello, there doesn't seem to be any specific mention of Bitcoin in the agenda, and the event seems more broadly focused on the use of blockchain technology for ICOs/tokenization.

**Comment by bcnation** [comment]
sorry for not responding sooner. Your email somehow ended up in spam.  The substantial amount of conference is dedicated to Bitcoin in general. As you can see John McAfee, and Vinny Lingham are confirmed speakers at the event.  We are also in talks with Andreas Antonopoulos. More bitcoin-centric speakers are being added.
