### ISSUE TITLE
Блокчейн и криптовалюты: новые возможности для бизнеса

### ISSUE THREAD

**Issue by Lypovskyi** [bitcoin-dot-org/bitcoin.org#2446]
- date: 2018-06-22
      title: "Блокчейн и криптовалюты: новые возможности для бизнеса"
      venue: "22 Июня 2018 года, 
в рамках 5го Восточноевропейского бизнес форума "Украина 2018. Вызовы и возможности" (ХАРЬКОВ) будет выделена и проведена секция "Блокчейн и криптовалюты: новые возможности для бизнеса".

Среди участников будет ряд профессиональных спикеров, представителей украинских и международных крипто-фондов, а также будут представлен ряд украинских старт-апов и ICO проектов.

Это профессиональное событие с массой полезного контента о рынке криптовалют, блокчейна, майнинга и применения всего этого для развития бизнеса.

События будет мега полезным для инвесторов, трейдеров, представителей бизнеса... и всех тех, кто пока только просто интересуется темой, и хотел бы за короткий период времени разобраться в сути рынка, а также, как на нем реально можно зарабатывать (а не про-факапить свои деньги)!

Возможность лично пообщаться и задать свои вопросы любому из спикеров и участников Форума.

Все это (и даже больше) уже 22 ИЮНЯ 2018 года в ХАРЬКОВЕ на "5м Восточноевропейском бизнес форуме "Украина 2018. Вызовы и возможности"."
      address: "Стадион Металлист"
      city: "Харьков"
      country: "Украина"
      link: "http://eebf.biz/"

![default](https://user-images.githubusercontent.com/40261892/41400188-1b84a6f4-6fc5-11e8-92f7-14d290850cf0.jpg)

**Comment by Roy19833** [comment]
Verzonden vanuit Outlook
________________________________
Van: Lypovskyi <notifications@github.com>
Verzonden: woensdag 13 juni 2018 20:23:03
Aan: bitcoin-dot-org/bitcoin.org
CC: Subscribed
Onderwerp: [bitcoin-dot-org/bitcoin.org] Блокчейн и криптовалюты: новые возможности для бизнеса (#2446)


- date: 2018-06-22
  title: "Блокчейн и криптовалюты: новые возможности для бизнеса"
  venue: "22 Июня 2018 года,


в рамках 5го Восточноевропейского бизнес форума "Украина 2018. Вызовы и возможности" (ХАРЬКОВ) будет выделена и проведена секция "Блокчейн и криптовалюты: новые возможности для бизнеса".

Среди участников будет ряд профессиональных спикеров, представителей украинских и международных крипто-фондов, а также будут представлен ряд украинских старт-апов и ICO проектов.

Это профессиональное событие с массой полезного контента о рынке криптовалют, блокчейна, майнинга и применения всего этого для развития бизнеса.

События будет мега полезным для инвесторов, трейдеров, представителей бизнеса... и всех тех, кто пока только просто интересуется темой, и хотел бы за короткий период времени разобраться в сути рынка, а также, как на нем реально можно зарабатывать (а не про-факапить свои деньги)!

Возможность лично пообщаться и задать свои вопросы любому из спикеров и участников Форума.

Все это (и даже больше) уже 22 ИЮНЯ 2018 года в ХАРЬКОВЕ на "5м Восточноевропейском бизнес форуме "Украина 2018. Вызовы и возможности"."
address: "Стадион Металлист"
city: "Харьков"
country: "Украина"
link: "http://eebf.biz/"

[default]<https://user-images.githubusercontent.com/40261892/41400188-1b84a6f4-6fc5-11e8-92f7-14d290850cf0.jpg>

**Comment by wbnns** [comment]
@Lypovskyi 

Hi, this event doesn't seem to be specifically focused on Bitcoin.
