### ISSUE TITLE
Blockchain & Bitcoin Conference Baku

### ISSUE THREAD

**Issue by SmileEvent** [bitcoin-dot-org/bitcoin.org#2447]
- date: 2018-09-27
  title: "Blockchain & Bitcoin Conference Baku"
  venue: "Hilton Baku"
  address: "1B Azadlig Avenue, Baku, AZ1000, Azerbaijan"
  city: "Baku"
  country: "Azerbaijan"
  link: "https://azerbaijan.bc.events/en"

**Comment by SmileEvent** [comment]
On September 27, the first large-scale Blockchain & Bitcoin Conference Baku, dedicated to blockchain, cryptocurrencies, and ICOs will start in Azerbaijan. Its participants will include well-known specialists and gurus of the cryptocurrency market, developers, entrepreneurs, representatives of payment systems, foreign experts.  
The conference will bring together Azerbaijanian and foreign experts. In their presentations, they will focus on the efficient conduct of token sales, cryptocurrency trading, use of blockchain in business, and investment opportunities of innovative technologies. 
As part of the discussion panel, speakers will discuss one of the key topics – regulation of blockchain and cryptocurrencies in Azerbaijan and across the globe. 
Furthermore, guests of Blockchain & Bitcoin Conference Baku will have access to the exhibition area. Here companies will present mining hardware, component parts for mining farms, software, blockchain platforms, and consultancy services for ICO projects. 
In addition, there will be a pitch session for exhibitors. Companies will tell about their activities and products presented at their booths. 
Follow the news of the event on the official website of Blockchain & Bitcoin Conference Baku.

**Comment by wbnns** [comment]
@SmileEvent Hello, while this event does have the word "Bitcoin" in the title, the agenda seems to be focused solely on the topic of ICOs and the use of blockchain technology outside of the context of Bitcoin. If we missed something, please let us know and we'll re-review.

**Comment by SmileEvent** [comment]
Hello! Yes, only 3 speakers have been announced on the site yet, and their speeches are devoted to the blockade and ISO, and not directly to bitcoin. However, as a cult cryptocurrency, bitcoin has always been a cross-cutting theme of all our conferences. Since the program is not yet closed, I can not say whether a separate report will be devoted to it, however, the history and actual state of bitcoin will be mentioned by at least half of the speakers.
