### ISSUE TITLE
Add "Art of the Problem's" Bitcoin video to Learning resources

### ISSUE THREAD

**Issue by britcruise9** [bitcoin-dot-org/bitcoin.org#2450]
I've had multiple requests to get this added to Bitcoin.org as it's a fantastic intro for people fresh to Bitcoin and doesn't skip the key technical insights:

https://www.youtube.com/watch?v=ZKwqNgG-Sv4

**Comment by wbnns** [comment]
Please go ahead and open a pull request if you would still like to see this added and we'll review.
