### ISSUE TITLE
BlockchainConf.Tech A Blockchain Conference for Software Engineers

### ISSUE THREAD

**Issue by vincentmayers** [bitcoin-dot-org/bitcoin.org#2453]
- date: 2018-09-06
      title: "BlockchainConf.Tech"
      venue: "Cobb Galleria Centre"
      address: "! Galleria Parkway"
      city: "Atlanta"
      country: "USA"
      link: "http://blockchainconf.tech"
![hackernoon hero](https://user-images.githubusercontent.com/5480295/41515543-5b4f1728-727d-11e8-8e0f-932919b4d25a.png)

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: Not the case.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: No.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: The majority of talks will be focused on blockchain.

Result: I**n my opinion this event should NOT be listed on Bitcoin.org based on the above.**
