### ISSUE TITLE
World Blockchain Roadshow Asia Part 1 (Kuala Lumpur)

### ISSUE THREAD

**Issue by danabsalyamov** [bitcoin-dot-org/bitcoin.org#2454]
- date: 2018-06-28
      title: "World Blockchain Roadshow Asia Part 1 (Kuala Lumpur)"
      venue: "Renaissance Kuala Lumpur Hotel"
      city: "Kuala Lumpur"
      country: "Malaysia"
      link: "http://wbrshow.idacb.com/"

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: Not the case.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: Not that I can tell.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: The majority of talks will be focused on blockchain and ICO start-ups.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**
