### ISSUE TITLE
Creating a PDF version for German translation

### ISSUE THREAD

**Issue by 99coins** [bitcoin-dot-org/bitcoin.org#2455]
@wbnns 
I would like to add the German translation to this page. The merged version [can be found here](https://github.com/wbnns/bitcoinwhitepaper/blob/master/bitcoin_de.odt).

Can a maintainer please create a PDF for this file so I can run it through VirusTotal?

Thanks

**Comment by wbnns** [comment]
@99coins Thanks. It looks like there's a small issue in that the formatting needs to match the other translated papers. We can take care of that on the other repository. Once you do that, we can convert it to a PDF so you can scan it (and also so we can add it to the site).
