### ISSUE TITLE
HoshoCon - Blockchain Security Conference

### ISSUE THREAD

**Issue by gabeshep** [bitcoin-dot-org/bitcoin.org#2456]
- date: 2018-10-09
      title: "HoshoCon - Blockchain Security Conference"
      venue: "The Hard Rock Hotel & Casino"
      address: "4455 Paradise , Las Vegas, NV 89169"."
      city: "Las Vegas"
      country: "USA"
      link: "http://www.hoshocon.com"

**Comment by gabeshep** [comment]
Hi there,

Thanks for your response. 

Sorry, I didn't see these requirements on the event page anywhere. However, there is programming we intend to add to HoshoCon that is related to Bitcoin, and am hopeful we will have multiple speaker submissions exclusively for Bitcoin topics. 

However - I do see multiple events already listed that don't meet some or all of this criteria.

Thanks

**Comment by wbnns** [comment]
@gabeshep Hello, please let us know if the additional content becomes available on the website so we can re-review.
