### ISSUE TITLE
New Language timeframe 

### ISSUE THREAD

**Issue by nedvedp** [bitcoin-dot-org/bitcoin.org#2458]
Hi,

I've translated the majority of the Bitcoin.org YML section.

I have around 190 strings left, so I believe I'll reach the 100% soon.

I wanted to ask when is a new language added on the site? Is it when the YML is 100% or are there other sections I should translate.

![screen shot 2018-06-19 at 13 49 02](https://user-images.githubusercontent.com/37040516/41596454-b7b8972a-73ca-11e8-98d5-de86e96c95d1.png)

By the way @wbnns thanks for giving me the coordinator access, it tremendously made things smoother and faster.

**Comment by wbnns** [comment]
@nedvedp Hi there! You're welcome, thanks for your help. When it's 100% translated and reviewed, we can put it on the site.
