### ISSUE TITLE
Redesign Feedback

### ISSUE THREAD

**Issue by aki** [bitcoin-dot-org/bitcoin.org#2464]
https://bitcoin.org/zh_CN/download
bootstrap.dat link invalid,I found one, I didn't know if it was
https://bitcoin.org/bin/blockc-hain/bootstrap.dat.torrent

![screenshot from 2018-06-21 19-37-13](https://user-images.githubusercontent.com/39704453/41716914-8df87fec-758a-11e8-8896-08ec7c5e5ddb.png)

**Comment by wbnns** [comment]
@carbonatite Thanks for letting us know; we're updating the translation strings to resolve the issue.

**Comment by harding** [comment]
I'm not sure why this is tagged 'dev docs' since it refers to the download page and translations.

**Comment by wbnns** [comment]
@harding It was inadvertent and has been updated.

**Comment by carbonatite** [comment]
Sorry, I sent the wrong link. It should be 
https://bitcoin.org/bin/block-chain/bootstrap.dat.torrent
