### ISSUE TITLE
Texas Bitcoin Conference 2018

### ISSUE THREAD

**Issue by tiffanyaliano** [bitcoin-dot-org/bitcoin.org#2466]
![htxcfflt_400x400-300x300](https://user-images.githubusercontent.com/6087589/41887088-dafeb404-78c4-11e8-992d-45e97acedeab.jpg)

Texas Bitcoin Conference 2018
October 27-28, 2018 (9am - 5pm)
AT&T Executive Education & Conference Center
1900 University Ave, Austin Tx 78705
United States
support@texasbitcoinconference.com
https://texasbitcoinconference.com

 Now in its fourth year, the Texas Bitcoin Conference is one of the most attended conferences in Texas for the bitcoin, blockchain and currency industries. People attending range from expert to novice, looking for information on the value of projects involved in ICO’s, blockchain technologies, regulations in place and more. Following the success of past years conferences, we are expecting hundreds to join us for another exciting conference in our State’s Capital City.

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: Yes.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: Yes. Based on the 2017 schedule of events, Bitcoin was part of the talks on day 2.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: This appears to be more Bitcoin-centric.

Result: **In my opinion this event could be listed on Bitcoin.org based on the above.**
