### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by terrypeirui** [bitcoin-dot-org/bitcoin.org#2467]
- date: 2018-09-18
      title: "Blockchain Practitioner Conference China 2018"
      venue: "Pullman Hotel Shanghai South"
      address: "1 Pubei Road"
      city: "Shanghai"
      country: "China"
      link: "http://www.bpc-events.com"

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: Not the case.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: No.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: The majority of talks will be focused on blockchain.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**
