### ISSUE TITLE
Add Serbian Language to the website

### ISSUE THREAD

**Issue by nedvedp** [bitcoin-dot-org/bitcoin.org#2468]
Hi,

After 2 months, I've finally translated the entire 100% YML part for Serbian Latin.

Serbian has two official letters (characters) Latin and Cyrillic. 

Please add it to the website.

I began translating in Cyrillic and can continue if you guys want to add that version as well. [Differences between lat and cyr here](https://en.wikipedia.org/wiki/Romanization_of_Serbian).

I translated Latin so that users from other similar countries like Bosnia and Herzegovina, Croatia, Montenegro can read, modify and adjust Serbian version to their own language if someone wants to do it.

**Comment by Komodorpudel** [comment]
@wbnns Already discussed with @nedvedp that Serbian Cyrillic is not needed.

So the only thing needed is to get the new Serbian Latin translations into the repository.

**Comment by wbnns** [comment]
@Komodorpudel Ok, thanks. @nedvedp Great work on this! 👏👏👏

We'll open the PR to get everything updated. 👍

**Comment by wbnns** [comment]
@nedvedp Hey, thanks again for your work. There are some URLs that have characters in them, which need to be updated (e.g. blokčejn should be blokcejn). We're taking care of it on Transifex and then everything should be ready to go.
