### ISSUE TITLE
New event Baltic Honeybadger 2018

### ISSUE THREAD

**Issue by bjarnemagnussen** [bitcoin-dot-org/bitcoin.org#2471]
- date: 2018-09-22 until 2018-09-23
      title: "Baltic Honeybadger 2018"
      venue: "RISEBA Arhitektūras un mediju centrs H20 6"
      address: "Durbes iela 4"
      city: "Rīga"
      country: "Latvia"
      link: "https://bh2018.hodlhodl.com/"

About the conference from their webpage:
The Baltic Honeybadger conference is the first major event in Latvia dedicated to Bitcoin and the technologies built around it. Our goal is to create an educational and community-driven event with high-profile speakers from all around the world and with different backgrounds — from technical engineers and cybersecurity professionals to business owners and bestselling authors.

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: Yes.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: The event is dedicated to Bitcoin.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: The event appears to be solely focused on Bitcoin.

Result: **In my opinion this event could be listed on Bitcoin.org based on the above.**
