### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by hakaroodi** [bitcoin-dot-org/bitcoin.org#2474]
date: 2018-07-25
      title: "Crypto Funding Summit: Security Tokens and ICOs"
      venue: "NYU Kimmel Center"
      address: "60 Washington Square S"
      city: "New York, NY"
      country: "United States"
      link: "https://www.cryptofundingsummit.com/"

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: Not the case.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: No.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: The majority of talks will be focused on blockchain and ICOs.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**
