### ISSUE TITLE
Bitconf Summer Edition - Fortaleza 2018

### ISSUE THREAD

**Issue by AndersonSilva47** [bitcoin-dot-org/bitcoin.org#2475]
- date: 2018-11-16 and 2018-11-17
      title: "Bitconf Summer Edition - Fortaleza 2018"
      venue: "Fábrica de negócios"
      address: "Av. Monsenhor Tabosa, 740"
      city: "Fortaleza"
      country: "Brasil"
      link: "http://www.bitconf.com.br/2018CE/"

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: Yes.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: Bitcoin looks like the major topic of this event.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: There will be talks about blockchain and other cryptocoins.

Result: **In my opinion this event could be listed on Bitcoin.org based on the above.**
