### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by bcnation** [bitcoin-dot-org/bitcoin.org#2488]
- date: 2018-10-09
      title: "Blockchain Nation Las Vegas"
      venue: "Paris Hotel"
      address: "3655 S Las Vegas Blvd, Las Vegas, NV 89109"
      city: "Las Vegas
      country: "US"
      link: "https://www.bcnation.com
![banner linkedin speakers2](https://user-images.githubusercontent.com/37531920/42130217-258ff984-7cac-11e8-90e0-84026374a1ee.png)
"

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: Not the case.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: Not that I can tell.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: The event seems to be focused on blockchain.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**
