### ISSUE TITLE
Future is now. Blockchain summit.

### ISSUE THREAD

**Issue by thechainers** [bitcoin-dot-org/bitcoin.org#2490]
**Event pt.: Future is now. Blockchain summit.**

Pięciu mówców, pięć inspirujących wykładów!

5 lipca (czwartek) w siedzibie Inkubatora Przedsiębiorczości Chainers Group (Elbląg, ul. Św. Ducha 16-18) odbędzie się wydarzenie, jakiego do tej pory jeszcze nie było! ,,Future is now. Blockchain Summit.''- ten event skierowany jest do tych, którzy interesują się technologią blockchain oraz jej zastosowaniem oraz wpływem na naszą przyszłość. To również wydarzenie idealne dla lokalnych przedsiębiorców, którzy szukają optymalizacji kosztów swoich przedsiębiorstw oraz wprowadzenia w struktury swoich działalności nowych rozwiązań.

Najbardziej znane nazwiska ze środowiska blockchain'a w jednym miejscu! Sonia Targosz, Rafał Leszek oraz Patryk Kempiński i inni, równie ciekawi prelegenci!

Harmonogram wydarzenia:

14:00 rozpoczęcie, przywitanie gości

14:10 wykład I Michał Stryjewski (Chainers Group, Unlimited Miners)- Optymalizacja kosztów przedsiębiorstw.

14:35 wykład II Sonia Targosz (WCM, prezes Fiat Based Token)- Przyszłość inteligentnych kontraktów.

15:00 przerwa kawowa

15:20 wykład III Przemysław Targosz (WCM, President Fiat Based Token)- Transakcje- płatności przyszłości, jak smart kontrakty zrewolucjonizują nasze życie?

15:45 wykład IV Rafał Leszek- Podstawy ekonomii blockchain, dlaczego czeka nas rewolucja?

16:10 wykład V Patryk Kempiński- Perspektywy rozwoju technologii rozproszonych rejestrów i problemy do rozwiązania.

16:35 przerwa kawowa

17:00 wykład VI Bartłomiej Sitek (Chainers Group)- Implementacja nowych technologii.

17:30 zakończenie, podziękowania

Bilety do nabycia na stronie: http://chainers.net/

Dla pierwszych 30 zarejestrowanych osób bilet darmowy!

Każda kolejna osoba: 199 zł

Zapraszamy!

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: Not the case.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: Not that I can tell.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: The event is focused on blockchain.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**
