### ISSUE TITLE
NEXT BLOCK Conference Sofia

### ISSUE THREAD

**Issue by Skorobreshchuk** [bitcoin-dot-org/bitcoin.org#2491]
- date: 2018-09-14
      title: "Evolution Of Money"
      venue: "NDK Sofia"
      address: "Boulevard "Bulgaria", 1463 Ndk, Sofia, Bulgaria"
      city: "Sofia"
      country: "Bulgaria"
      link: "https://next-block.org/"

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: Not the case.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: No.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: The majority of talks will be focused on blockchain and ICO pitches.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**

**Comment by Skorobreshchuk** [comment]
Hello there!

@applesolbrilla @wbnns I would like to inform you that the event is related to both blockchain and crypto and specifically Bitcoin itself.

Our keynote speaker is Communications Ambassador at bitcoin.com and his keynote speech' topic is "Evolution of money" which is also the umbrella topic of the Conference. There he will speak directly about how the last stage of money evolution for now is Bitcoin and other cryptocurrencies with bitcoin being the most usable and widespread.

Secondly, almost all panel discussions include Bitcoin as a topic. At every panel, Bitcoin, ICOs and other digital currencies will be discussed within the framework of different approaches to them.

The topics for the panel discussions are the following:

Digital Assets vs Physical Assets (direct talk about Bitcoin and other digital currencies)
Banking the Unbanked (how Bitcoin and other digital currencies should be free to use between the users or banked)
Challenges of a Crypto Economy (how using digital currencies may be challenging with the modern economy crisis etc)
Finding the Balance Between Financial Freedom and Regulatory Oversight (whether Bitcoin and other digital currencies should be regulated by the countries government or not and how to achieve it)

Thus, I think the event is related to the content of the website and I am kindly asking you to take my arguments into consideration and list the event.

Thank you for your time!
