### ISSUE TITLE
New event - Top10 Point of Trust

### ISSUE THREAD

**Issue by NickBesedin** [bitcoin-dot-org/bitcoin.org#2494]
- date: 2018-10-11
      title: "Top10 Point of Trust"
      venue: "Casa Llotja de Mar"
      address: " Passeig d'Isabel II, 1, 08003"
      city: "Barcelona"
      country: "Spain"
      link: "https://top10.bzntm.com/"

**Comment by wbnns** [comment]
@NickBesedin Thanks for the info. Please let us know when a more detailed agenda and/or list of speakers become available.
