### ISSUE TITLE
Blockchain in Healthcare Symposium Dubai 2018

### ISSUE THREAD

**Issue by jimlakjuma** [bitcoin-dot-org/bitcoin.org#2504]
- date: 2018-09-20
      title: "Blockchain in Healthcare Symposium Dubai"
      venue: "Raffles Dubai"
      city: "Dubai"
      country: "United Arab Emirates"
      link: "http://blockchaininhealthcare.co"

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: Not the case.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: No.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: The majority of talks will be focused on blockchain.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**
