### ISSUE TITLE
#BLOCKCHAIN&TOURISM 2018

### ISSUE THREAD

**Issue by jtrixbusiness** [bitcoin-dot-org/bitcoin.org#2506]
- date: 2018-09-22
      title: "Блокчейн и туризм"
      venue: "БОГДО"
      address: "ул. Таганская, дом 7"
      city: "Москва"
      country: "Россия"
      link: "http://jtrixbusiness.ru/"

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: Not the case.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: Not that I can tell.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: The majority of talks will be focused on blockchain and ICO start-ups.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**

**Comment by jtrixbusiness** [comment]
The majority of talks will be on blockchain in the travel industry.
