### ISSUE TITLE
Docs issue report

### ISSUE THREAD

**Issue by xbis** [bitcoin-dot-org/bitcoin.org#2508]
Source File: _data/devdocs/en/bitcoin-core/rpcs/rpcs/getrawtransaction.md
The description of "getrawtransaction" does not describe fields: "txid", "hash", "version", "size", "vsize", "locktime", "vin", "vout" returned in verbose mode

**Comment by wbnns** [comment]
@xbis Apologies if I'm misunderstanding your issue - do you not see what you're looking for, [here](https://bitcoin.org/en/developer-reference#getrawtransaction)?
