### ISSUE TITLE
Crypto Investor Show - Manchester (9th & 10th November 2018)

### ISSUE THREAD

**Issue by cristinaduta** [bitcoin-dot-org/bitcoin.org#2509]
Following on from the hugely successful and inaugural [Crypto Investor Show](https://www.cryptoinvestor.show/) in London on Saturday 10th March 2018, the show moves north to Manchester which is taking place over the 9th & 10th November 2018.

We aim to put on well rounded, innovative and exciting events that reflect the buzz of the industry, whilst giving investors the chance to fully understand the key elements driving blockchain technology forward, how and why the industry has got to where it is now, and what could be in store for 2018 and beyond.

_Why attend?_

Attendees can gain insight into the array of investment opportunities provided by Cryptocurrencies and Blockchain Technology. You can discover how to mine, buy, and trade digital currency, the latest blockchain innovations and how to navigate the ICO market.

Website: https://www.cryptoinvestor.show/

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: Not that I can tell.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: Not that I can tell.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: The majority of talks will be focused on blockchain and cryptocurrencies.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**

**Comment by wbnns** [comment]
@cristinaduta 

Hello, we have new criteria that events are assessed on (what Apple mentioned above).

Hope this helps clarify.
