### ISSUE TITLE
Crypto Investor Show - London (1st & 2nd March 2019)

### ISSUE THREAD

**Issue by cristinaduta** [bitcoin-dot-org/bitcoin.org#2510]
The second edition of the [Crypto Investor Show](https://www.cryptoinvestor.show/) in London will continue to bring investors together with the crypto and blockchain communities to inspire innovation and collaboration. This second edition will take place over two days and will have new and exciting elements which will be announced very soon. 

We aim to put on well rounded, innovative and exciting events that reflect the buzz of the industry, whilst giving investors the chance to fully understand the key elements driving blockchain technology forward, how and why the industry has got to where it is now, and what could be in store for 2018 and beyond.

_Why attend?_
Attendees can gain insight into the array of investment opportunities provided by Cryptocurrencies and Blockchain Technology and will discover how to mine, buy, and trade digital currency, the latest blockchain innovations and how to navigate the ICO market.

Find out more on on website: https://www.cryptoinvestor.show/

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: Not that I can tell.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: Not that I can tell.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: The majority of talks will be focused on blockchain and cryptocurrencies.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**
