### ISSUE TITLE
Robonomics 2018. Blockchain for Smart Cities

### ISSUE THREAD

**Issue by BessonovaNatali** [bitcoin-dot-org/bitcoin.org#2518]
- date: 2018-08-24
      title: "Robonomics 2018. Blockchain for Smart Cities"
      address: " ul. Burlatskaya, 33"
      city: "Tolyatti"
      country: "Russia"
      link: "https://airalabrus.timepad.ru/event/761803/"

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: Not the case.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: Not that I can tell.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: The majority of talks will be focused on blockchain.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**
