### ISSUE TITLE
International Blockchain and Cryptocurrency BCconf 2018

### ISSUE THREAD

**Issue by smallgiant2005** [bitcoin-dot-org/bitcoin.org#2520]
- date: 2018-11-13
      title: "International Blockchain and Cryptocurrency BCconf 2018"
      venue: "Sheraton Hotel"
      address: "Jalan Sultan Ismail, Chow Kit, 50250 
      city: "Kuala Lumpur"
      country: "Malaysia"
      link: "http://bcconf.com
![bcconf_720_480](https://user-images.githubusercontent.com/17356577/42733215-b8c41df2-882d-11e8-8513-78ff6deb50d1.jpg)
![logo bc conference 600px](https://user-images.githubusercontent.com/17356577/42733217-bf09c932-882d-11e8-8b6e-b508f6466744.jpg)
[press release bcconf2018.pdf](https://github.com/bitcoin-dot-org/bitcoin.org/files/2195654/press.release.bcconf2018.pdf)

"

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: Not the case.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: Not that I can tell.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: The majority of talks will be focused on blockchain and ICO start-ups.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**
