### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by cristpereirag** [bitcoin-dot-org/bitcoin.org#2522]
- date: 2018-10-17
      title: "Blockchain Summit Latam - Colombia 2018"
      venue: "Casa Dann Carlton Hotel"
      address: "Cl. 93b #18-99"
      city: "Bogotá"
      country: "Colombia"
      link: "www.blockchainsummit.la"

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: Not the case.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: Not that I can tell.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: The majority of talks will be focused on blockchain.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**

**Comment by cristpereirag** [comment]
Hi! thanks for the reply. About the questions:

*Q: Is this event specifically related to Bitcoin?*
A: Not the case.

*Q: Is there a talk focused exclusively on Bitcoin?*
A: Yes, we will have talk focus con Bitcoin Core (Technical) and The rise
of Bitcoin and Cryptoassets era.

*Q: Are the majority of talks focused on ICOs and/or other digital
currencies?*
A: We will have different talks about different blockchain projects, such
us Bitcoin, Ethereum, NEO, Ripple, NEM.


Please let me know if this answer help.

Thanks!



Cristóbal Pereira G.
co-founder & CEO

mifutu.ro


2018-07-16 3:08 GMT-04:00 Apple Joy Solbrilla <notifications@github.com>:

**Comment by wbnns** [comment]
@cristpereirag Hello, thanks for following up - please let us know once the agenda is updated and speakers become listed on the website with information pertaining to this.

**Comment by cristpereirag** [comment]
Perfect, I'll do!

Best.

Cristóbal Pereira G.
co-founder & CEO

mifutu.ro


2018-07-25 18:09 GMT-04:00 Will Binns <notifications@github.com>:
