### ISSUE TITLE
About-us page: Same text is displayed twice

### ISSUE THREAD

**Issue by Komodorpudel** [bitcoin-dot-org/bitcoin.org#2541]
Hey,

on the about us page (https://bitcoin.org/en/about-us), a string is displayed twice for some reason. See attached picture.

Best regards,

Simon

![bitcoin org about us](https://user-images.githubusercontent.com/29728442/43099284-faed54c4-8ec1-11e8-854f-33cc3c31bf16.JPG)

**Comment by wbnns** [comment]
@Komodorpudel Thanks Simon. Resolved with #2542.
