### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by lindsaylaverty** [bitcoin-dot-org/bitcoin.org#2550]
- date: 2018-09-19
      title: World Ethical Data Forum
      venue: World Trade Center Barcelona
      address: 1ª planta, Edif. Este, Moll de Barcelona, s/n, 08039 Barcelona
      city: Barcelona
      country: Spain
      link: www.worlddataforum.com

Good morning, 

I have been reviewing your list of top blockchain conferences in 2018 and wish that you add the inaugural World Ethical Data Forum. 

On the 19th and 20th of September this year we are hosting the inaugural World Ethical Data Forum, to be held at the World Trade Centre in Barcelona. The forum will bring together experts and enthusiasts from all over the globe to present and discuss several critical questions, such as the meaning of ethical data exchange, the moral implications and responsibilities that arise from the wealth of new decentralized technologies and systems, and whether a responsible moral climate of exchange and data commodification can be encouraged by design, but which does not compromise the advantages of distributed architectures. The event will also explore potential technical solutions to the questions raised.

Especially in light of the recent Facebook/Cambridge Analytica scandal, and of the new regulations being introduced the world over,* we are determined to make this inaugural World Ethical Data forum a place where all parties, irrespective of creed or ideology, are able to discuss perhaps the most difficult commodity of all to know how to manage, monetize and transfer — data.

Some of our headline speakers include;

- Andrew Padilla (Senior Software Architect at Watson Health Imaging analytics - IBM) 
- Dr Fenglian Xu (Master inventor of the Hyper ledger Blockchain - IBM) 
- Alex Lightman (CEO of Token Communities Plc & author) 
- Dr David Brin (Internationally best-selling novelist of The Postman, turned into a film starring Kevin Costner & Futurist) 
- Simon Thompson (Head of Practice for Big Data & Customer Experience for BT) 

There are several Speaker / Sponsorship opportunities available for the event. If you would like to discuss them further, please let us know.  Please see our Media Kit (https://drive.google.com/open?id=1dk5tb6uqNCqg2XFHbX8x7vrFN4rKALFy)which contains everything you may need to work with us as a media partner. 

Please contact lindsay@blockdigital.io for more information.

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: Not the case.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: Not that I can tell.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: The majority of talks will be focused on blockchain and ICO.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**
