### ISSUE TITLE
CoinsBank Blockchain Cruise

### ISSUE THREAD

**Issue by coinsbank** [bitcoin-dot-org/bitcoin.org#2555]
- date: 2018-09-07
      title: "CoinsBank Blockchain Cruise"
      venue: "Vision of the Seas cruise ship"
      address: "Barcelona Cruise Terminal B, c. Moll Adossat"
      city: "Barcelona"
      country: "Spain"
      link: "https://coinsbank.com/cruise-europe"

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: Somewhat related.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: BTC is in the conference topics.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: The conference is focused primarily on blockchain and cryptocurrencies.

Result: **In my opinion this event could be listed on Bitcoin.org based on the above.**

**Comment by coinsbank** [comment]
Any updates on this?

**Comment by wbnns** [comment]
@coinsbank Hello, yes, this will be added, soon.
