### ISSUE TITLE
Ukrainian Blockchain Day 

### ISSUE THREAD

**Issue by UaForza** [bitcoin-dot-org/bitcoin.org#2556]
- date: 2018-10-15
      title: "Ukrainian Blockchain Day "
      venue: "NSC Olimpiyskiy"
      address: "Velyka Vasylkivska str. 55."
      city: "Kyiv"
      country: "Ukraine"
      link: "http://blockchainday.org/en/ukraine"

**[Ukrainian Blockchain Day](http://blockchainday.org/en/ukraine)**

**Blockchain day** is a global and cross-sector platform for collaboration, networking, explaining and advancing Blockchain methodologies and solutions. 

The goal is to accelerate the growth of a sustainable ecosystem that drives the application and implementation of Blockchain in all private and public sectors.

![_kiev_1](https://user-images.githubusercontent.com/40323795/43326032-6a1ed132-91c0-11e8-96a4-6d34e3435540.jpg)

**Blockchain Day as a platform in 2018 includes:**

- Flagman event – **[Ukrainian Blockchain Day](http://blockchainday.org/en/ukraine)** – audience 1500+ 
- Large Forums in the centers of the development and usage of the technology – audience 500 +
- Meetups during the event
- Live conference – **[Blockchain Day Online](http://blockchainday.org/en/online)** – audience 20 000+
- Master classes – from 15 till 50 people
- International close dinners and breakfasts with the speakers and investors

_Type of Large forums, that Blockchain Day includes
Classic forum – the conference with the speeches – [**Kyiv**](http://blockchainday.org/en/ukraine), **[Amsterdam](http://blockchainday.org/en/netherlands)**, **[Dubai](http://blockchainday.org/en/uae)**, **[Tbilisi](http://blockchainday.org/en/georgia)**
Forum –networking – with active engagement of the audience – **[Kyiv](http://blockchainday.org/en/ukraine)**, **[Dubai](http://blockchainday.org/en/uae)**
Forum – party – classic forum in non-formal atmosphere with food and drinks - **[Moscow](http://blockchainday.org/en/russia)**_

[**CONTACTS**](http://blockchainday.org/en/ukraine)

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: Not the case.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: Not that I can tell.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: The majority of talks will be focused on blockchain and ICO projects.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**
