### ISSUE TITLE
Quebex.com Canadian bitcoin exchange

### ISSUE THREAD

**Issue by davidquebex** [bitcoin-dot-org/bitcoin.org#2559]
Hi, would you be kind enough to add quebex.com Canadian bitcoin exchange? Last time you tested you were flagged by our anti-fraud feature and that’s why your account was under review. We have over 5,000 verified users.

**Comment by davidquebex** [comment]
We tried calling you but the number provided was not working.

**Comment by davidquebex** [comment]
Hi, I just texted you. Cheers
  
  
  
  
David Bruno   
  
  
President | Quebex Fintech Inc.
  
  www.Quebex.com (http://www.quebex.com/)
  
Skype:   david@Quebex.com (mailto:david@Quebex.com)
  
  
  
  
  

  
  
>

**Comment by davidquebex** [comment]
I don’t understand why you don’t want to list Quebex.com. We are trying to promote safe environment for P2P bitcoin trading and take time to verify all users to prevent e transfer fraud. Your account was under review because it was flagged by our automated system. This is why you did not have access to the feaures. We have 5,000+ verified Canadian users, we are licensed to operate in Quebec and have been in operation for almost 2 years now. You would be benefiting safe bitcoin trading in Canada but for some reason are not listing our exchange. Please advise.
  
  
  
  
David
  
Quebex.com
  
  

  
  
  
  
  

  
  
>

**Comment by wbnns** [comment]
@davidquebex Hello, thanks for the info. We've reviewed the site again.

It seems the empty box issues are resolved that we mentioned in #2421, however, it seems new accounts are flagged by default. We received the same message that we needed to call a phone number. The verification link in the "My Quebex" dropdown in the navigation bar seems broken and loads the "Dashboard" page (a different link that's already in the navigation bar). We were unable to find any information or step-by-step process on what a user needs to do to be able to use the site, other than calling a phone number. The phone number is a recording that asks for a name (screening the call), but doesn't say anything about what to do for the above situation (if nobody picks up, after a hold, it goes to voicemail).

When we navigated to the "Post Ad" link, it said that our verification documents hadn't been approved, but there do not seem to be any resources or links detailing where those documents can be uploaded.

**Comment by davidquebex** [comment]
Users are NOT flagged by default. If you are a real person located in Canada you will get automatically approved. We have a very sophisticated system for detecting suspicious accounts. We are a p2p exchange so protecting our users is the most important thing for us. Most uses get their bank accounts shit down on Localbitcoins due to e transfer fraud. We don’t want fraudsters and criminals on the platform. We can’t publicly disclose how our system works but if your available for a call we can explain a bit. If your trying to HIDE behind virtual devices or proxies you WILL be flagged for manual review.   We will fix the issues below and get back to you.
  
  

  
  
  
  
  

  
  
>
