### ISSUE TITLE
CryptoBlockCon - New York City

### ISSUE THREAD

**Issue by gcsmithv** [bitcoin-dot-org/bitcoin.org#2564]
- date: 2018-08-14
      title: "CryptoBlockCon - New York City"
      venue: "NYIT Auditorium On Broadway"
      address: "1871 Broadway, New York, NY 10023"
      city: "New York City"
      country: "United States"
      link: "http://www.cryptoblockcon.com/new-york-august-2018/
![feathr landing page header image](https://user-images.githubusercontent.com/32965496/43433809-f9b3225c-9446-11e8-83c6-9969883a58db.jpg)
"

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: Not the case.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: Not that I can tell.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: The majority of talks will be focused on blockchain and ICOs.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**
