### ISSUE TITLE
Add Lightning Hackday #3

### ISSUE THREAD

**Issue by svanstaa** [bitcoin-dot-org/bitcoin.org#2571]
- date: 2018-09-01
      title: "Lightning Hackday #3"
      venue: "Ahoy Berlin"
      address: "Wattstrasse 11"
      city: "Berlin"
      country: "Germany"
      link: "https://lightninghackday.fulmo.org"

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: Yes.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: It appears that there's a schedule specific for Bitcoin.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: The talks appear to be purely around Bitcoin and Lightning Network.

Result: **In my opinion this event could be listed on Bitcoin.org based on the above.**
