### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by gutomartino** [bitcoin-dot-org/bitcoin.org#2572]
- date: 2018-09-06
      title: "Dezentral Berlin"
      venue: "Kosmos"
      address: "Karl-Marx-Allee 131A, 10243 Berlin"
      city: "Berlin"
      country: "Germany"
      link: "www.dezentral.io"

**Comment by gutomartino** [comment]
Hi, Everyone
not sure if I did it right, but we have this conference on the 6th of September in Berlin
Please reach out to me on guto@dezentral.io if I did it wrong.

**Comment by gutomartino** [comment]
My first time using github

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: Not the case.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: Not that I can tell.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: The majority of talks will be focused on blockchain.

Result: I**n my opinion this event should NOT be listed on Bitcoin.org based on the above.**
