### ISSUE TITLE
Receiving `error: {“code”:-26,“message”:“16:”}` on sendrawtransaction

### ISSUE THREAD

**Issue by neetu-goyal** [bitcoin-dot-org/bitcoin.org#2573]
***** Request *****
{"method":"sendrawtransaction","params":["010000000181e65f66c08f51195c65fd907a90b369f7a5862f67702eabb46d31c7010411d701000000b500473044022058dd0f37cca4f4626d383d445ca9ce532b5f55a0d96aacfc6098dbe0246a2fa402207ca77de5d418f808288437209bd89d86701e413e8911fdfc072a00dbd291f1a701004c6952210254bd45c08ad752e8a86db3d3cc4edb03c0cf3b0c75397c6a87b37918696e01c2210307442b5998b30591118f90466d0c06df9930fd21fcd4035eb3b3494601b663212103b2ac13f537d6fe296675a4927eae4413179c013217a2fd7d78eb328f7ccba87053aeffffffff01c0d40100000000001976a914e3fe845bf3048ed4a83a69f2fdbfb4b7bb78029f88ac00000000"],"id":1}
***** End Of request *****

***** Server response *****
{"result":null,"error":{"code":-26,"message":"16: mandatory-script-verify-flag-failed (Signature must be zero for failed CHECK(MULTI)SIG operation)"},"id":1}
***** End of server response *****

Kindly check and help me ASAP.

**Comment by wbnns** [comment]
@neetu-goyal Hello, here's a link to forums where you can connect with others who may be able to offer technical support regarding your issue: https://bitcoin.org/en/bitcoin-core/help#forums
