### ISSUE TITLE
Add the Litecoin Summit to Bitcoin Events Page

### ISSUE THREAD

**Issue by TheBiomancer** [bitcoin-dot-org/bitcoin.org#2574]
- date: 2018-09-14
      title: "Litecoin Summit"
      venue: "South San Francisco Conference Center"
      address: "255 S Airport Blvd, South San Francisco, CA 94080"
      city: "South San Francisco"
      country: "USA"
      link: "https://litecoinsummit.org/"

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: Not the case.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: Not that I can tell.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: The majority of talks will be focused on Litecoin and blockchain.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**
