### ISSUE TITLE
CESC

### ISSUE THREAD

**Issue by SFBlockchainwk** [bitcoin-dot-org/bitcoin.org#2578]
Hello- Our event for CESC is showing the wrong dates. We need it changed to October 10-11.   

 - date: 2018-10-10
      title: Cryptoeconomics Security Conference
      venue: Hilton at Union Square
      address: 333 O'Farrell Street
      city: San Francisco, CA 94102
      country: United States of America
      link: https://cesc.io/

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: Not the case.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: Not that I can tell.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: The majority of talks will be focused on blockchain and cryptoeconomics.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**
