### ISSUE TITLE
New event - Blockchain Fair Asia 2018 (PH edition)

### ISSUE THREAD

**Issue by NaomiLopez** [bitcoin-dot-org/bitcoin.org#2579]
- date: 2018-10-11
      title: "Blockchain Fair Asia 2018 (PH edition)"
      venue: "SMX Aura, Taguig, Philippines"
      address: "8 McKinley Pkwy, Taguig, Metro Manila"
      city: "Taguig"
      country: "Philippines"
      link: "https://blockchainfairasia.com"

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: Not the case.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: Not that I can tell.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: The majority of talks will be focused on blockchain and cryptomarket.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**
