### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by cryptocameron** [bitcoin-dot-org/bitcoin.org#2581]
- date: 2018-12-14
      title: USA Blockchain Conference
      venue: Chateau Luxe
      address: 1175 E Lone Cactus Dr Phoenix, AZ 85024
      city: Phoenix
      country: United States of America
      link: 
![blockchain banner](https://user-images.githubusercontent.com/42304598/43995918-10d8a658-9d6d-11e8-9854-e83da2a8f704.png)
usablockchainconference.com

**Comment by wbnns** [comment]
@odarboe Yes, thanks.

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: Not that I can tell.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: No.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: There is currently no program available.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**
