### ISSUE TITLE
New event - Blockchain Venture Summit London

### ISSUE THREAD

**Issue by burakozkirdeniz** [bitcoin-dot-org/bitcoin.org#2582]
- date: 2018-11-21
      title: "Blockchain Venture Summit"
      venue: "8 Northumberland Avenue, London UK"
      address: "8 Northumberland Avenue, LONDON - WC2N 5BY"
      city: "London"
      country: "United Kingdom"
      link: "https://blockchainventuresummit.com/"

![bvs](https://user-images.githubusercontent.com/5032199/44001677-ea1145c0-9e3e-11e8-9e07-946f223787f4.jpg)

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: Not the case.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: Not that I can tell.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: The majority of talks will be focused on blockchain and cryptocurrency start-ups.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**
