### ISSUE TITLE
Futurama Blockchain Innovators Summit

### ISSUE THREAD

**Issue by BountyManOdessa** [bitcoin-dot-org/bitcoin.org#2587]
- date: 2018-09-10
      title: "Futurama Blockchain Innovators Summit"
      city: "Ibiza"
      country: "Spain"
      link: "https://futuramasummit.com/"
      description: "Second Futurama Blockchain Innovators Summit aims to gather the builders of the future under the hot rays of the Spanish sun on the magical island of Ibiza.
The aim of Futurama Blockchain Innovators Summit is to bring together some of the leading thinkers and doers in the world of the blockchain, to accelerate each other and prepare for the next phase of socio-economic growth in the industry.

What’s unique about Futurama Blockchain Innovators Summit is that their organizers managed to realize something that no other had been able to do before – to bring in the representatives of key exchanges, state officials, and regulators, even with their super busy schedules, to provide guests with an exclusive three-day opportunity of priceless networking.

Futurama Blockchain Innovators Summit expects top exchanges, regulators, funds and of course the innovators of blockchain to participate in this Balearic experience across a compound of several exclusive villas on the island of Ibiza, to mix together and find ways to accelerate the community. Because at the end of the day it's all about community.  Brock Pierce, Miko Matsumura, Roger Ver, Crystal Rose and 20+ crypto whales will be there.

Representatives of Coinsbank, Bithumb exchange, Binance, Bitlinka, Exmo, Golix, DNA fund, Blockchain capital, Evercoin, Huawei, Securrency, Cryptocapital, SENSE, Cointopia will meet at one place for creating future."

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: Not the case.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: Not that I can tell.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: The majority of talks will be focused on blockchain and ICO projects.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**
