### ISSUE TITLE
Blockchain Day Netherlands

### ISSUE THREAD

**Issue by tsybulskayalena** [bitcoin-dot-org/bitcoin.org#2590]
- date: 2018-09-29
      title: "Blockchain Day Netherlands"
      venue: "Amsterdam, Netherlands"
      address: "Amsterdam, Netherlands"
      city: "Amsterdam"
      country: "Netherlands"
      link: "http://blockchainday.org/netherlands/"
![bd_950_400_5_2](https://user-images.githubusercontent.com/14363344/44217472-3876dd80-a180-11e8-8239-a6334cc5c207.jpg)

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: Not the case.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: No.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: The majority of talks will be focused on blockchain.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**
