### ISSUE TITLE
Dubai Blockchain Expo

### ISSUE THREAD

**Issue by pauldbe** [bitcoin-dot-org/bitcoin.org#2591]
- date: 2018-10-15
  title: "Dubai Blockchain Expo"
  venue: "Atlantis Hotel"
  address: "The Palm Jumeira"
  city: "Dubai"
  country: "UAE"
  link: "https://dbe.ae/?r=bitcoin"

![dbe](https://user-images.githubusercontent.com/42443323/44215181-f26f4900-a182-11e8-9c77-4884c65dc9d5.jpg)

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: Not the case.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: No.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: The majority of talks will be focused on blockchain and ICO start-ups.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**
