### ISSUE TITLE
Update outdated translation strings in footer

### ISSUE THREAD

**Issue by nedvedp** [bitcoin-dot-org/bitcoin.org#2599]
Hello,

I've noticed two outdated strings which don't appear in Transifex, both located in the footer.

![2018-08-20_00-26-50](https://user-images.githubusercontent.com/37040516/44313860-109da900-a410-11e8-9c35-5fee5c14f562.png)

**Comment by wbnns** [comment]
@nedvedp Opened #2711 to resolve this. Thanks again for mentioning.
