### ISSUE TITLE
Move RPC reference to bitcoincore.org

### ISSUE THREAD

**Issue by karel-3d** [bitcoin-dot-org/bitcoin.org#2600]
There should be an effort to move RPC docs from

https://bitcoin.org/en/developer-reference

to bitcoincore.org website, at least the parts that are more relevant to bitcoin core client then bitcoin in general.

I have recently added auto-generated RPC docs to bitcoincore.org, which are already more up-to-date than what is on this developer reference website.

cc @harding

**Comment by wbnns** [comment]
Would recommend to update them, rather than remove them.

**Comment by karel-3d** [comment]
bitcoin.org is intended to be about bitcoin protocol in general and not about different implementations, while bitcoincore.org is for Bitcoin Core? So it makes more sense to me to leave it at a website of Bitcoin Core since it is Core API, other implementations might change it
