### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by cnjsstong** [bitcoin-dot-org/bitcoin.org#2605]
- date: 2018-08-30
      title: "Blockchain Without Borders Token Expo 2018"
      venue: "Crowne Plaza Times Square Manhattan"
      address: "1605 Broadway, New York, NY 10019"
      city: "New York"
      country: "United States"
      link: "https://www.eventbrite.com/e/blockchain-without-borders-token-expo-2018-tickets-48621047863"

**Comment by cnjsstong** [comment]
Thank you so much!

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: Not the case.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: Not that I can tell.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: The majority of talks will be focused on blockchain.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**
