### ISSUE TITLE
Blockchain Economy Istanbul Summit

### ISSUE THREAD

**Issue by GTashli** [bitcoin-dot-org/bitcoin.org#2616]
- date: 2018-02-20
      title: "Blockchain Economy Istanbul Summit"
      venue: ""
      address: "Maslak mah. Taşyoncası sk. T4 blok. No:1  U/B246
                      Sariyer/Istanbul/Turkey"
     
      city: "Istanbul"
      country: "Turkey"
      link: "http://blockchaineconomy.istanbul"

**Comment by GTashli** [comment]
THE LARGEST INTERNATIONAL BLOCKCHAIN ECONOMY CONFERENCE OF THE REGION

As known, Netherlands-based banking giant ING published a customer report recently where it was declared that Turkey is the leading cryptocurrencies owner among all European countries. The fact that the people in Turkey are heading to more technological innovations and current economic circumstances serve as an increasing factor for it. Investors and engineers, mostly from the Middle East and Central Asian countries as well as from Turkey, who are interested in blockchain and who deal with cryptocurrencies will be participating in this conference. You will better understand Blockchain, the greatest technological and financial revolution of the 21st century, with the expression of expert speakers in the sphere. Thus, "Blockchain Economy Istanbul Summit" rolls out the distinction of being the largest-scale event of the region, ever held in this field.

More than 5,000 attendees from 20 countries will attend the conference and more than 10,000 people will be watching live. We are associating investors, entrepreneurs and professionals for discussing current cryptocurrency market and future of blockchain technology.

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: This event is related to Bitcoin.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: The list of subjects in this event suggests this is the case.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: There will be talks on blockchain and cryptocurrencies.

Result: **In my opinion this event could be listed on Bitcoin.org based on the above.**

**Comment by GTashli** [comment]
http://blockchaineconomy.istanbul
