### ISSUE TITLE
NEXT BLOCK Conference “Evolution of Property”

### ISSUE THREAD

**Issue by Kokarieva** [bitcoin-dot-org/bitcoin.org#2618]
- date: 2018-11-09
      title: "NEXT BLOCK Conference “Evolution of Property”
      venue: ""
      address: ""
      city: "Lisbon"
      country: "Portugal"
      link: "https://kryptonevents.com/lisbon"

**Comment by Kokarieva** [comment]
Our conference dedicated to blockchain. All our speakers, partners and attendees are experts in the blockchain field.
We would appreciate if you could add us to the list of the events on your website. From our side, you'd be placed as our official media/info partner on our website.
Thanks a lot!

**Comment by odarboe** [comment]
@Kokarieva open the issue for it to be reviewed.
