### ISSUE TITLE
Dotted path not appearing properly in Chrome

### ISSUE THREAD

**Issue by Cobra-Bitcoin** [bitcoin-dot-org/bitcoin.org#2619]
The dotted path shown in the get started page doesn't display properly in Chrome browser.

Example in Chrome:
<img width="300" alt="chrome" src="https://user-images.githubusercontent.com/12899428/44786179-3737ae80-ab8b-11e8-9193-3c64d6fb0b5f.png">

Example in Firefox:
<img width="250" alt="firefox" src="https://user-images.githubusercontent.com/12899428/44786194-428ada00-ab8b-11e8-8eb8-2fc943470f48.png">

**Comment by wbnns** [comment]
@Cobra-Bitcoin Thanks for mentioning - could you please let me know what version of Chrome and what operating system you're using? I'm not able to replicate this in 68.0.3440.106 (the latest version) on OS 10.13.6.

**Comment by wbnns** [comment]
@Cobra-Bitcoin ICYMI

**Comment by Cobra-Bitcoin** [comment]
I tested on the latest version of Chrome on Windows 10.
