### ISSUE TITLE
CRYPTO-ROCKSTARS BLOCKCHAIN CONFERENCE

### ISSUE THREAD

**Issue by EddiM** [bitcoin-dot-org/bitcoin.org#2624]
**JOIN THE BITCOIN REVOLUTION - LEARN EVERYTHING THAT YOU NEED TO KNOW ABOUT THE LATEST BLOCKCHAIN TRENDS AND TRADING CRYPTOCURRENCY.**

**3 DAYS + 30 SPEAKERS // 26.-28.NOVEMBER 2018**

**ONLINE CONFERENCE / VIRTUAL SUMMIT + NETWORKING LOCATION IN COLOGNE, GERMANY.**

**FEATURING SPEAKERS** from renown brands like: 
* BINANCE
* SAP
* Accenture
* BTC-Echo
* DASH
* Qarnot
* Motionwerks
* Crown
* DEZOS
* BountyGuru
* CoinTraffic
* Blockchain Solutions
* TEAL AI AG
* Tatiana Moroz from Crypto Media Hub
* Katalytics
* Startplatz 
* IBM
* KI-Dezentralized
* Spike Crypto ICO Marketing
* and the mother of the Silk Road creator Ross Ulbricht
* plus more...

**TOPICS INCLUDE:**
* Introduction to Blockchain and Bitcoin for beginners
* Why the collapse of the banking system is imminent
* Community driven and self-sustainable blockchain ecosystems 
* The language of Blockchain - Tech without talk
* The first crypto heating unit that can mine while heating your home
* Free the art - how and why cryptocurrencies, communities and creators can unite
* The Binance Story - How the exchange became No.1 in just 12 months
* Monero - The fungible cryptocurrency
* ICO Marketing for Startups
* The first blockchain based emobility product
* The consequences of the Silk Road trial for digital privacy lawmaking
* Doing your homework on ICOs
* Different Blockchains, Different Use Cases – Strengths and weaknesses of private and public blockchains
* Artificial Intelligence and Blockchain
* eCommerce Solutions for Blockchain 
* How we collected 16.666 ETH in just 15 minutes
* Secure Identity Protocols (Business Case)
* Bounties - how to get thousands of people promoting your project
* Cryptoland - The crypto regulation process on Malta 
* A guide to the DASH Privacy Coin 
* Supply Chain Management on the Blockchain 
* How to report your crypto taxes
* Trading crypto with leverage
* How to do your own Chart Analytics
* Startup Accelerator powered by ICO funding 
* plus more...

Get more detailed information about speakers and topics on our website:
http://crypto-rockstars.com

**FREQUENTLY ASKED QUESTIONS:**

**WHAT IS THIS CONFERENCE ABOUT?**
This event has a strong focus on some of the best Blockchain Startups, Technology Use-Cases and ICO Marketing Know-How.

**WHAT IS A MIXED ONLINE + OFFLINE EVENT?**
Originally, this event was planned as a pure VIRTUAL SUMMIT / ONLINE CONFERENCE, but we had so many requests for a live networking location, that we partnered up with the famous STARTPLATZ in COLOGNE. All videos are pre-recorded and streamed live on our online webinar platform. So you can watch it from anywhere in the world OR you can come to Cologne to meet some speakers in person and network with our huge local community of blockchain experts and enthusiasts. 

**CAN I WATCH THIS ONLINE EVENT AT MY HOME / OFFICE?**
YES, ABSOLUTELY! GET ONLINE ACCESS AND WATCH ALL 30 EXCLUSIVE VIDEO INTERVIEWS OF THIS 3-DAY EVENT FROM ANYWHERE IN THE WORLD. 

IMPORTANT: Access to this free resource is limited to only 500 seats and on a first come first served basis! That means, when you miss a live session, then it´s gone! If the webinar rooms are fully packed, then you can´t get access anymore! That means, you might want to buy a ticket to get 12 month online VIP-Access to all interview videos OR come to our live networking event in Cologne Germany to meet up with most speakers in person.

[You can register for a free webinar ticket here (Limited to only 500 seats!)](https://events.genndi.com/register/169105139238454986/e0ba7aa574) 

**WHAT IS THE BENEFIT OF COMING TO COLOGNE?**
The live location in Cologne features free access to a huge networking area, some trade show promotions, a bonus magazine, an exclusive red carpet interview setup for the press, an interactive social wall, meet some of our speakers in person, take part in open Q&A sessions and experience a selection of the finest street food. 

**WHY ARE THERE 2 DIFFERENT TICKETS?**
Because of technological issues, there are 2 DIFFERENT Tickets available. 

The Online Ticket gets you 12-months access to our online membership portal where you can watch a replay of the interview recordings from your home. 

[Buy your Online Ticket here:](https://edwina.krtra.com/t/g6b028jFt4rK) 

The Cologne Ticket gets you entry to the live networking event in Cologne. This ticket is powered by Eventbrite and has no connection to our online membership portal, BUT you can buy your VIP-Online-Access as an additional extra for a special price at the box office in Cologne. 

[Buy your Cologne Ticket here / powered by Eventbrite](https://www.eventbrite.com.au/e/crypto-rockstars-blockchain-conference-3-days-in-cologne-tickets-46319826849?aff=CryptoRockstars&afu=270101617343)

**CAN I SIGN UP AS AN AFFILIATE TO HELP PROMOTE THIS BLOCKCHAIN EVENT?**
Yes, we pay out between 25-50% of the ticket price as a sales commission.

You can register as an affiliate here:

[Affiliate Program > Online Ticket (50% payout)](https://edwina.krtra.com/t/rqUSFojWLfYf)

[Affiliate Program > Cologne Ticket (25% payout) / powered by Eventbrite](https://www.eventbrite.de/affiliate-register?eid=46319826849&affid=215542758)

IMPORTANT: Ticket prices are increasing as the event date approaches.
![cr logo neu 4](https://user-images.githubusercontent.com/42961873/45020937-8caf0800-b030-11e8-8617-e575c01fb745.png)
![visitenkarte event jpeg](https://user-images.githubusercontent.com/42961873/45020952-95074300-b030-11e8-82a1-c4b907b9905e.jpg)

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: Not the case.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: Only in the introduction.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: The majority of talks will be focused on blockchain and ICO start-ups.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**
