### ISSUE TITLE
How the blockchain will revolutionise the B2B business

### ISSUE THREAD

**Issue by TrynC** [bitcoin-dot-org/bitcoin.org#2625]
- date: 2018-11-13
      title: "How the blockchain will revolutionise the B2B business"
      venue: "Swiss Chamber"
      address: "via Palestro, 2"
      city: "Milan"
      country: "Italy"
      link: "https://www.casaleggio.it/en/b2b/"

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: Not the case.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: No.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: The majority of talks will be focused on blockchain.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**
