### ISSUE TITLE
CRYPTONEED VENTURE FEST 2018

### ISSUE THREAD

**Issue by ashangin** [bitcoin-dot-org/bitcoin.org#2627]
- date: 2018-11-20
      title: ""
      venue: "Tesla.Place"
      address: "Shosse Entuziastov, 5c2"
      city: "Moscow"
      country: "Russia"
      link: "www.cnvf.ru"

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: Not the case.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: No.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: The majority of talks will be focused on blockchain and ICO start-ups.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**

**Comment by ashangin** [comment]
Hello!

Actually, part of events on your website are not focused on Bitcoin. CNVF is includes questions on Bitcoin and another cryptocurrency.

Additionally, we can discuss with you the participation of your representative as a speaker at the festival. For contact e-mail speakers@cnvf.ru, WhatsApp/Telegram +79637388907.
