### ISSUE TITLE
Blockchain Unbound Tokyo

### ISSUE THREAD

**Issue by arencc** [bitcoin-dot-org/bitcoin.org#2628]
- date: 2018-10-14 -> 2018-10-16
      title: Blockchain Unbound Tokyo
      venue: ANA Intercontinental Tokyo
      address: 1-12-33 AKASAKA MINATO-KU TOKYO, 107-0052 JAPAN
      city: Tokyo
      country: Japan
      link: https://blockchainunboundtokyo.com/

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: Not the case.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: No.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: The majority of talks will be focused on blockchain and ICO start-ups.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**
