### ISSUE TITLE
USA Blockchain Conference

### ISSUE THREAD

**Issue by cryptocameron** [bitcoin-dot-org/bitcoin.org#2632]
- date: 2000-12-14/15
      title: "USA Blockchain Conference"
      venue: "Chateau Luxe"
      address: "1175 E Lone Cactus Dr, Phoenix, AZ 85024"
      city: "Phoenix"
      country: "United States of America"
      link: "https://www.usablockchainconference.com/
![blockchain banner](https://user-images.githubusercontent.com/42304598/45127438-1b08b400-b12d-11e8-9137-0f9ec8325dd5.jpg)
"

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: Not the case.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: No.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: The majority of talks will be focused on blockchain and cryptocurrency.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**

**Comment by cryptocameron** [comment]
Sterlin Lujan, the Communications Ambassador for Bitcoin.com,has committed
to speak.
