### ISSUE TITLE
ESOCKETTIMEDOUT

### ISSUE THREAD

**Issue by alishaagupta** [bitcoin-dot-org/bitcoin.org#2635]
Source File: _data/devdocs/en/bitcoin-core/rpcs/rpcs/importaddress.md

Whenever the method is used, address is imported but an error is thrown showing ESOCKETTIMEDOUT.

**Comment by jdabs** [comment]
@alishaagupta are you using any of the additional parameters for that method?

**Comment by alishaagupta** [comment]
No , i just used the command -
bitcoin-cli importaddress "address"

**Comment by wbnns** [comment]
@alishaagupta Hello, if you're still experiencing this issue, please consider visiting [Bitcoin Stack Exchange](https://bitcoin.stackexchange.com/) for more in-depth technical assistance.
