### ISSUE TITLE
Blockchain Day

### ISSUE THREAD

**Issue by AudreyLeadmedia** [bitcoin-dot-org/bitcoin.org#2640]
- date: 2018-10-10
      title: "The Blockchain Day"
      venue: "Palais Brongniart"
      address: "16 Place de la Bourse, 75002 Paris"
      city: "Paris"
      country: "France"
      link: "https://theblockchainday.com/"

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: Not the case.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: No.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: The majority of talks will be focused on blockchain and ICO start-ups.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**
