### ISSUE TITLE
New event: TOKEN2049

### ISSUE THREAD

**Issue by AlexFiskum** [bitcoin-dot-org/bitcoin.org#2650]
- date: 2019-03-13
      title: "TOKEN2049"
      venue: "Kerry Hotel"
      address: "38 Hung Luen Road, Hong Kong"
      city: "Hong Kong"
      country: "Hong Kong"
      link: "https://www.token2049.com/"

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: Not that I can tell.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: Not indicated.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: Detailed schedule is currently not available but this may be the case.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**
