### ISSUE TITLE
crontab command for automatic bitcoind startup on Debian 9

### ISSUE THREAD

**Issue by baltakatei** [bitcoin-dot-org/bitcoin.org#2657]
I noticed that the following line that the instructions say to append to the text file opened by the `crontab -e` command doesn't work as-is on a fresh install of Debian 9:

`@reboot bitcoind -daemon`

However, the line does work if I include the path to `bitcoind`, like so:

`@reboot /usr/local/bin/bitcoind -daemon`

I have not checked whether this was an issue only with Debian 9 or other GNU/Linux distributions. I did check to make sure that there was a newline character at the end of `@reboot bitcoind -daemon`.

**Comment by wbnns** [comment]
@baltakatei You may need to ensure that `/usr/local/bin` is in your `$PATH`.

**Comment by member7me** [comment]
Hello. I have the same issue. Could you say, where I can check $PATH ?
