### ISSUE TITLE
Add www.thebigcoin.io to "Spending Bitcoin" page and "Resources" page directories->merchants.

### ISSUE THREAD

**Issue by tomasm91** [bitcoin-dot-org/bitcoin.org#2661]
Majority of the online retailers do not accept Bitcoin and make difficulties for the crypto community to use it. I have found quite interesting online shopping platform for spending Bitcoin. These guys seem to be operating for a year now. 

At first, I was sceptical but did some research and found many positive feedbacks at Trustpilot, Bitcointalk and Reddit so I decided to give it a try. I placed a small test order to make sure I don’t get scammed. However, the item was delivered as promised, so now I'm using them quite often.

You can choose any item (even flight tickets) from any site worldwide. You just copy the product link and paste it to their website, the system catch the product, then you simply enter the shipping details (for physical products) and finally you pay the required amount of BTC, thats it, just sit back and wait for the delivery!

I believe Bitcoin community should know that such services exist.

**Comment by wbnns** [comment]
Thanks for the info. It seems like an interesting idea, but we were unable to find any specific reviews beyond TrustPilot. It still seems a bit new

**Comment by tomasm91** [comment]
@wbnns I have come up with this service that has been around for over a year.
I have made my research before using this service. Here is what I have found:

Thebigcoin was listed on official sites like GetMonero.org, Dash.org.

There also are some reviews here:
 - Bitcointalk forum: https://bitcointalk.org/index.php?topic=2152963
 - Trustpilot: https://www.trustpilot.com/review/thebigcoin
 - Reddit: https://www.reddit.com/r/TheBigCoin/

I've read an article about these guys a few days ago: https://www.ccn.com/leading-cryptocurrency-shopping-platform-thebigcoin-hits-300000-in-total-orders/

The last thing I came up with was their partnership with MakerDAO: https://www.reddit.com/r/MakerDAO/comments/9n3l46/thebigcoinio_accepts_dai_stablecoin/

I personally have placed 6 orders through them and every single one was delivered as expected.
I'm sure these guys are not some kind of a shady service and they have already earned trust among the cryptocurrency community.
