### ISSUE TITLE
Stableconf

### ISSUE THREAD

**Issue by ecsaron** [bitcoin-dot-org/bitcoin.org#2669]
- date: 2018-10-25 / 26
      title: "Stableconf"
      venue: "Kings Place, London, UK"
      address: "90 York Way"
      city: "London"
      country: "UK"
      link: "http://stableconf.com"

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: Not the case.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: No.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: The majority of talks will be focused on blockchain and stablecoins.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**
