### ISSUE TITLE
I want to translate this documentation into chinese?

### ISSUE THREAD

**Issue by renlulu** [bitcoin-dot-org/bitcoin.org#2671]
Location: https://bitcoin.org/en/developer-guide#consensus-rule-changes

**Comment by odarboe** [comment]
@renlulu  Checkout https://www.transifex.com/bitcoin/bitcoin/ to help in the translation. It might be good to verify that this document is up to date before going forward.

**Comment by wbnns** [comment]
@renlulu Hello, please read [this blog post](https://bitcoin.org/en/posts/how-to-help-translate) for more information on how to get started. If you have any other questions, please let us know. Thanks for your help!

**Comment by renlulu** [comment]
> @renlulu Hello, please read [this blog post](https://bitcoin.org/en/posts/how-to-help-translate) for more information on how to get started. If you have any other questions, please let us know. Thanks for your help!

Thanks, But I cannot open it.Is the website https://bitcoin.org down?

**Comment by renlulu** [comment]
> @renlulu Checkout https://www.transifex.com/bitcoin/bitcoin/ to help in the translation. It might be good to verify that this document is up to date before going forward.

Thanks
