### ISSUE TITLE
NEW EVENT - CRYPTO SUMMIT

### ISSUE THREAD

**Issue by mateusnds** [bitcoin-dot-org/bitcoin.org#2672]
- date: 2018-10-02
      title: "CRYPTO SUMMIT"
      venue: "Hub Minas Digital"
      address: "Avenida Bias Fortes, 50, Lourdes - Belo Horizonte, MG"
      city: "Belo Horizonte"
      country: "Brazil"
      link: "https://www.sympla.com.br/crypto-summit__361567"

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: Not the case.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: Not that I can tell.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: The majority of talks will be focused on blockchain and cryptocoins.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**

**Comment by mateusnds** [comment]
Hello @applesolbrilla , Thank you for check the event.

You 'are Right! Is not Exclusively on Bitcoin, they will talk about Blockchain.

Thank you.
