### ISSUE TITLE
New Event LightningHackdayNYC

### ISSUE THREAD

**Issue by svanstaa** [bitcoin-dot-org/bitcoin.org#2673]
date: 2018-10-27/28 title: "Lightning HackdayNYC" venue: "Flatiron school" address: "11 Broadway #260" city: "New York" country: "USA" link: "https://lightninghackday.fulmo.org"

**Comment by odarboe** [comment]
@svanstaa for clarity and consistency with the norm, can you put each property in one line.

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: Yes.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: The event itself is exclusively about Bitcoin.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: The talks appear to be purely around Bitcoin and Lightning.

Result: **In my opinion this event could be listed on Bitcoin.org based on the above.**
