### ISSUE TITLE
CoinAgenda Global

### ISSUE THREAD

**Issue by Erikazee** [bitcoin-dot-org/bitcoin.org#2676]
- date: 2018-10-23
      title: "CoinAgenda Global"
      venue: "Mandalay Bay Resort"
      address: "3950 S Las Vegas Blvd"
      city: "Las Vegas"
      country: "USA"
      link: "https://global.coinagenda.com/"

**Comment by Erikazee** [comment]
My previous attempts to have CoinAgenda listed on your site have always been turned down due to not being enough focus on bitcoin or speakers listed.

The conference is focused on blockchain and all crypto investing, including bitcoin. We have panels covering exchanges and regulation all related to the industry in its entirety. An agenda can be found here: https://global.coinagenda.com/agenda

**Comment by wbnns** [comment]
@Erikazee 

Hello, thanks for your message. The issue is that there is nothing specifically mentioned about Bitcoin on the agenda - it seems more broadly focused on exchanges, blockchain technology and ICOs (which are specifically mentioned).
