### ISSUE TITLE
Washington Elite AI & Blockchain Summit

### ISSUE THREAD

**Issue by GlobalBoost** [bitcoin-dot-org/bitcoin.org#2680]
- date: 2018-11-30  and 2018-12-1
      title: "Washington Elite AI & Blockchain Summit"
      venue: "DC Convention Center"
      address: "801 Mt Vernon Pl NW"
      city: "Washington, DC"
      country: "USA"
      link: "[Washington Elite AI & Blockchain Summit website](http://WashingtonElite.com)"

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: Not the case.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: No.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: The majority of talks will be focused on blockchain and ICO start-ups.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**
