### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by virtuapete** [bitcoin-dot-org/bitcoin.org#2681]
- date: 2018-12-07
      title: "Crypto Pro Miami Art Week"
      venue: "Fontainebleau Miami Beach"
      address: "4441 Collins Ave"
      city: "Miami Beach, FL"
      country: "USA"
      link: "https://cryptoproexpo.com/miami-art-week-2018/"

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: Not the case.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: Not that I can tell.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: The majority of talks will be focused on blockchain and cryptocurrencies.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**
