### ISSUE TITLE
Add Samourai Wallet to recommended Android Wallets

### ISSUE THREAD

**Issue by FrancisPouliot** [bitcoin-dot-org/bitcoin.org#2688]
I have been using Samourai Wallet since their alpha testers' group (I think 2015?).

I have been closely monitoring development, and I personally use it as my hot wallet. 

It is the wallet that our services Bylls.com and BitcoinOutlet.com recommend to its users.

I think it's time we add it to the suggested Android wallets. They have a lot of very good privacy features and security features. They let users connect to their own nodes for validation. They have lots of best practices embedded. They are compatible with open dime. As far as mobile wallets go, they are a great choice and I fully recommend it. 

Control over your money: yes 

Simplified validation: no. by default it queries samourai APIs

Full-node validation: yes, you can use your own full node to validate transactions. But Samourai API is still required to fetch utxos to create transactions.

Basic transparency: you can run it as an APK on android, and the source code is open.

Secure environment: unsure

Basic privacy: there are many benefits, I think samourai devs should probably fill this part.

Full control over fees: yes

@samouraidev should probably have a look at this issue and comment.

**Comment by crwatkins** [comment]
@FrancisPouliot Thanks for the recommendation! Wallets are added to the listings on bitcoin.org by contributors (like you) or the wallet developers themselves by submitting a PR as described [here](https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/docs/managing-wallets.md). Following this is a review process based on the criteria listed. Reviews can be performed by anyone, but are usually done by the current bitcoin.org wallet maintainer who offers an opinion on the compliance to each criteria listed. Approval for listing is based on community consensus of complying with the criteria.

The review criteria are fairly detailed and it usually takes some involvement of the wallet team to accurately determine compliance (and to perhaps resolve any outstanding issues). That said, there has been at least one wallet listing PR that was recently submitted by other than the wallet developer. You may want to coordinate with the Samurai team to submit a PR.

Note that this was recently recommended in #2329, but no PR has been submitted yet.

**Comment by Cobra-Bitcoin** [comment]
This might be relevant https://www.reddit.com/r/Bitcoin/comments/9tm92r/greg_maxwell_i_have_seen_far_too_much_outright/.

**Comment by wbnns** [comment]
Closing for now since it has been a couple of months and there hasn't been any activity on this thread.

@FrancisPouliot @SamouraiDev If either of you (or others) are interested in pursuing this addition, please feel free to open a PR. Here's a [reference](https://github.com/bitcoin-dot-org/bitcoin.org/pull/2788) for the process.

**Comment by SamouraiDev** [comment]
Not interested.

**Comment by joaovarelas** [comment]
Samourai Wallet has known unpatched vulnerabilites that were disclosed to the public:

References:

- [https://vrls.ws/posts/2021/08/samourai-wallet-bitcoin-pin-authentication-bypass-crypto/](url) 
- [https://twitter.com/ob_hodl/status/1297867841727868929](url)
