### ISSUE TITLE
Dropping the 'News' section from the Resources Page

### ISSUE THREAD

**Issue by wbnns** [bitcoin-dot-org/bitcoin.org#2697]
Link: https://bitcoin.org/en/resources

We recently had a pull request to add a language-specific news resource to the News section of the Resources page (so that it would only appeared when the page is viewed in that language), and I noted that the majority of the news was more tailored to cryptocurrencies and blockchain-related topics in general, rather than a specific focus on Bitcoin. The current news sites that appear on the resources page also somewhat reflect this trend. 

There's no shortage of news about Bitcoin these days, so wondering if there should even be a section with a handful of links we try to maintain at this point. Especially since the ones we have aren't that super-focused about Bitcoin anymore - there's a lot of other coverage intermixed.

What's the sentiment on potentially dropping this section from the Resources page?

**Comment by jdabs** [comment]
I think this is wise. Considering thar the project holds strict standards for events and wallets, the content on the news sites veers far from these. Not that the sites' content is bad, but most of it doesn't align with the requirements for the other resource galleries.

**Comment by jdabs** [comment]
Or as an alternate, make the link go to the "bitcoin" category for the news site. That way, it would only go to articles that have been tagged as bitcoin related.

**Comment by Cobra-Bitcoin** [comment]
Agreed, I think it should be removed. The state of cryptocurrency and Bitcoin news is pretty poor anyways. No need to point users to these sites anymore, they can just keep up with the latest news on Reddit or Twitter.

**Comment by mateusnds** [comment]
Hello, @Cobra-Bitcoin  and @wbnns 

As a Journalist I just want to share my vision.

We are always trying to bring the latest news to people. We realize that not everyone uses reddit or Twitter, we are always following these channels to pass the information to readers.

I think the older people on the market do not give much more importance to news sites like that. But, the newbies people are always on the lookout for news and learning.

Most news sites actually cover the whole market, Bitcoin, crypto-coins and blockchain. But hey? Bitcoin is still the main focus, and it is possible to filter this.

What do you think?

**Comment by wbnns** [comment]
Opened #2715.

@mateusnds Hello, thanks for sharing your perspective. Yes, you're right, not everyone uses social media to read the news. Even outside of social media, though, every day Bitcoin is in newspapers, television shows, radio programs/podcasts and trending news results on search engines.
