### ISSUE TITLE
[Nit] Update required storage amount

### ISSUE THREAD

**Issue by GrumpyKiitty** [bitcoin-dot-org/bitcoin.org#2699]
An update is needed on the following page given the discrepancy between its storage requirement statement ("over 145GB") and the current requirement (~200 GB): https://bitcoin.org/en/download.

**Comment by merland** [comment]
Seems like the value `site.text.bitcoin_datadir_gb` in [_config.yml](https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/_config.yml) needs to be updated. Is there a process/routine for updating these ever-growing "constants"...?

**Comment by wbnns** [comment]
Opened #2716.

@merland Hi, yes, that's where it needs to be updated. Regarding your question, no, not at the moment.
