### ISSUE TITLE
Mallorca Blockchain Days 

### ISSUE THREAD

**Issue by MallorcaBCDays** [bitcoin-dot-org/bitcoin.org#2704]
- date: 2019-03-23
      title: "Mallorca Blockchain Days"
      venue: "Palma de Mallorca Pueblo Español,"
      address: "Pueblo Español, 55"
      city: "Palma de Mallorca"
      country: "Spain"
      link: "https://mallorcablockchaindays.com"

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: Not the case.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: Not that I can tell.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: The majority of talks will be focused on blockchain and cryptocurrencies.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**

**Comment by wbnns** [comment]
@MallorcaBCDays

Hello, thanks for your message. I'm reopening this and we'll rereview the event website.

**Comment by wbnns** [comment]
@MallorcaBCDays 

We reviewed your event website again and agree with @applesolbrilla 's conclusion that it's not clear that this event is specifically related to Bitcoin. Also, we could not find any specific agenda on the website that provided more details about the talks that you mentioned there would be about Bitcoin.

Also, adding this event could be confusing to new users if they discover the event via bitcoin.org - at least two of the speakers are from a company called BitCore, which has its own coin called BTX that bears an almost identical logo to bitcoin, albeit in a different color, in addition to a somewhat similar ticker symbol.

**Comment by MallorcaBCDays** [comment]
In the end I have to accept your judgement it just leaves a very bad taste, especially as you list conferences as the "Malta Blockchain Summit" where the main focus clearly is not bitcoin but ICOs.
When we publish our agenda you will realize how absurd your argumentation is.

A few of our speakers are true bitcoin OGs (Travis, Michael, Eric, Rodolfo, Chris, Andrii...) others are organizing many bitcoin community events (Blockchainhotel Bitcoin Meetup, Mallorca Bitcoin Meetup, ...) Rodolfo is the director of Bitcoin Argentina and the main organizer of the Latin America Bincoin conference...

Anyway: https://miltonfriedman.hoover.org/objects/57796/volume-2-the-tyranny-of-control
