### ISSUE TITLE
How can i build a block server?

### ISSUE THREAD

**Issue by Cheng-Lun** [bitcoin-dot-org/bitcoin.org#2708]
Location: https://bitcoin.org/en/developer-guide#stratum
i'm so unclear when i read the document https://bitcoin.org/en/developer-guide#stratum.That make me sad,it's unfriendly to us who the first time contact it.How can i use it, and read the about api document?

**Comment by wbnns** [comment]
@Cheng-Lun This section only provides a high-level overview to introduce terms. You may want to consider visiting the link to [this page](https://slushpool.com/help/manual/stratum-protocol) for more specific technical information.
