### ISSUE TITLE
2nd Annual CHAINERS Blockchain Week

### ISSUE THREAD

**Issue by Raemao** [bitcoin-dot-org/bitcoin.org#2718]
- date: 2019-01-14 to 2019-01-18
      title: "2nd Annual CHAINERS Blockchain Week"
      venue: "Conrad Hotel"
      address: "10 Gukjegeumyung-ro, Yeoeuido-dong, Yeongdeungpo-gu, Seoul, Korea"
      city: "Seoul"
      country: "Korea"
      link: "http://www.blockkarneval.com/"

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: Not the case.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: Not that I can tell.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: The majority of talks will be focused on blockchain and ICO investments.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**
