### ISSUE TITLE
November Meetup in Arnhem Bitcoin City

### ISSUE THREAD

**Issue by annetdeboer** [bitcoin-dot-org/bitcoin.org#2719]
- date: 2018-11-17
      title: "November Meetup"
      venue: "Oranje Koffiehuis"
      address: "Arke Noachstraat 7"
      city: "Arnhem Bitcoin City"
      country: "The Netherlands"
      link: "https://www.meetup.com/ArnhemBitcoinCity/events/255578567/"

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: Yes.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: The event itself is exclusively about Bitcoin.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: The talks appear to be purely around Bitcoin.

Result: **In my opinion this event could be listed on Bitcoin.org based on the above.**
