### ISSUE TITLE
Blockchain Conference Moscow

### ISSUE THREAD

**Issue by Viktoria-M** [bitcoin-dot-org/bitcoin.org#2724]
On November 20, Blockchain Conference Moscow will be held for the eighth time. The conference is intended for developers, entrepreneurs, investors, startup founders, as well as financiers, economists, lawyers, and marketers that work with blockchain and cryptocurrencies. It will fall into two sessions to provide every participant with a possibility to focus on information. 

Main topics of Blockchain Conference Moscow:
1. Fintech Hall:
•	cryptocurrencies and traditional assets;
•	blockchain regulation;
•	blockchain security;
•	blockchain and innovation;
•	industrial application of the technology. 
2. Blockchain Hall:
•	tokenization of the economy and other areas of social life;  
•	decentralization of the Internet;  
•	ICOs – cryptocurrency crowdsales, present and future; 
•	successful trading strategies;
•	EOS constitution as the first social contract on blockchain. 

Registration to the conference is available on the website of the [Blockchain Conference Moscow](https://moscow.bc.events/en?utm_source=pr_LY&utm_medium=pr&utm_campaign=github-bitcoin.org).

**Comment by Viktoria-M** [comment]
![blokcheyn_moskva_foto_vesna_2018_15245587673655_image](https://user-images.githubusercontent.com/40798045/47348736-cc9e7d00-d6ba-11e8-9343-45141b08a2f8.jpg)
![blokcheyn_moskva_foto_vesna_2018_15245624350708_image](https://user-images.githubusercontent.com/40798045/47348737-cc9e7d00-d6ba-11e8-994a-174ec446124f.jpg)
![blokcheyn_moskva_foto_vesna_2018_15245624970188_image](https://user-images.githubusercontent.com/40798045/47348738-cd371380-d6ba-11e8-96ff-5d4ab9aa8e32.jpg)

**Comment by Viktoria-M** [comment]
Here we have [a great video](https://www.youtube.com/watch?v=IxjFpMVife4&index=2&list=PLJ3fZcmf7xIPGd8ObeBSoAGOtDI1mkAEs) of Blockchain Conference Moscow 2018, please have a look!

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: Not the case.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: Not that I can tell.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: The majority of talks will be focused on blockchain and ICOs.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**
