### ISSUE TITLE
LABITCONF 2018

### ISSUE THREAD

**Issue by Camilolwi** [bitcoin-dot-org/bitcoin.org#2728]
- date: 2018-12-05
      title: "LABITCONF 2018 : Latin American Bitcoin & Blockchain conferences"
      venue: "Centro cultural Corpartes."
      address: "Rosario Norte 660, Las Condes."
      city: "Santiago de chile"
      country: "Chile"
      link: "https://www.labitconf.com/"

**Comment by applesolbrilla** [comment]
Hello there,

I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this event specifically related to Bitcoin?**
A: Yes.

**Q: Is there a talk focused exclusively on Bitcoin?**
A: The list of topics in this event suggests this may be be the case.

**Q: Are the majority of talks focused on ICOs and/or other digital currencies?**
A: The event has listed a few talks on ICOs and other digital currencies.

Result: **In my opinion this event could be listed on Bitcoin.org based on the above.**
