### ISSUE TITLE
error code: -28 after upgrading from 0.16.3 to 0.17.0.1

### ISSUE THREAD

**Issue by stefanomarty** [bitcoin-dot-org/bitcoin.org#2734]
I'm running a full node on Debian jessie.

After upgrading from 0.16.3 to 0.17.0.1 I keep getting this error whenever I try to get any info from the daemon:
```
$ bitcoin-cli getblockchaininfo
error code: -28
error message:
Verifying blocks...
```

I'm not an expert, so I presume the bitcoind daemon is performing some kind of indexing, as I can see from the changing timestamps in .bitcoin/blocks/index

If the above assumption is correct, and there are no real issues with my install, I'd suggest to complete the message with something like this:
```
error code: -28
error message:
Verifying blocks...
Checking block N of M
Please wait until the verification is complete.
```

so that you can check the progress and see there are no real errors in your node. Just my 2 cents.

**Comment by wbnns** [comment]
@stefanomarty Hi, thanks for the feedback, however, this isn't the right repository for this issue. You should open it, [here](https://github.com/bitcoin/bitcoin/issues/new), instead.

**Comment by stefanomarty** [comment]
Sorry, I was following the wrong GitHub link! :-)

Thanks for pointing me to the right place, I opened a new issue there.
Ciao.

**Comment by wbnns** [comment]
You're welcome and no problem, good luck.
