### ISSUE TITLE
Cripto Latin Fest 2019 Blockchain

### ISSUE THREAD

**Issue by santiago08** [bitcoin-dot-org/bitcoin.org#2738]
- date: 2019-05-18-19
      title: "Cripto Latin Fest 2019"
      venue: "Bogota_Colombia"
      address: "Bogota"
      city: "Bogota"
      country: "Colombia"
      link: "www.criptolatinfest.com"

**Comment by wbnns** [comment]
@santiago08 Hello, we would need a valid venue to associate with the event before this could potentially be added.

**Comment by santiago08** [comment]
date: 2019-05-18-19
  title: "Cripto Latin Fest 2019"
  venue: "Hacienda_san_Rafael_Bogota_Colombia"
  address: "carrera 57 N° 133 – 00"
  city: "Bogota"
  country: "Colombia"
  link: "www.criptolatinfest.com"

**Comment by santiago08** [comment]
![copia de black](https://user-images.githubusercontent.com/37759649/52908819-43075200-324b-11e9-9d78-68bf2ee97f48.png)
