### ISSUE TITLE
ubuntu 18.10 bitcoin-qt fail to launch

### ISSUE THREAD

**Issue by santhoshpkumar** [bitcoin-dot-org/bitcoin.org#2746]
ubuntu 18.10 bitcoin-qt fail to launch

**Comment by wbnns** [comment]
Hello, this repository is for issues specifically related to bitcoin.org. Please consider checking out [Bitcoin Stack Exchange](https://bitcoin.stackexchange.com.) for general bitcoin questions and/or support requests related to issues like this one.

Hope that helps and good luck! :)
