### ISSUE TITLE
typo in SendCmpct section of developer reference

### ISSUE THREAD

**Issue by rsa4096** [bitcoin-dot-org/bitcoin.org#2747]
Source File: _data/devdocs/en/references/p2p_networking.md

https://bitcoin.org/en/developer-reference#cmpctblock
in current document, sendcmpct message's "announce" field data type is "block_header" , 
should it be "uint8_t" or "boolean"?

**Comment by cornelius** [comment]
This is fixed in #3063.

**Comment by wbnns** [comment]
@cornelius Thank you.
