### ISSUE TITLE
Linking to Bitwage on the exchanges page

### ISSUE THREAD

**Issue by Cobra-Bitcoin** [bitcoin-dot-org/bitcoin.org#2750]
We link to [Bitwage](https://bitwage.com/) on the exchanges page, but this doesn't seem to operate as a proper exchange anymore (if it ever did?), it's more of a payroll service that supports Bitcoin. The link to Bitwage is very prominent at the top of the list of exchanges, right after Bitstamp.

I think it's better to have it linked somewhere else, or remove the link entirely since it's confusing for users looking for an actual exchange. This link seems to have been added when the exchanges page was still being built out, and a new part of the site. Now that we have more exchanges and content on the page it seems unnecessary and out of place to link to Bitwage like this.

**Comment by wbnns** [comment]
@Cobra-Bitcoin Yes, thanks - maybe better suited for an "earn" bitcoin page or something along those lines.
