### ISSUE TITLE
WIRESUMMIT 2018 (Investor Edition)

### ISSUE THREAD

**Issue by DavidQuirk** [bitcoin-dot-org/bitcoin.org#2751]
- date: 2018-12-02
      title: "WIRESUMMIT 2018 (Investor Edition)"
      venue: "New Delhi"
      country: "India"
      link: "www.wiresummit.org"
![wiresummit_featured_image](https://user-images.githubusercontent.com/45026722/48462479-52b36c80-e7fe-11e8-9a1b-178a18fb3f5a.jpg)
![logo 6](https://user-images.githubusercontent.com/45026722/48462489-5e069800-e7fe-11e8-9e45-f5efe56c4e58.png)

**Comment by wbnns** [comment]
@DavidQuirk 

Hello, this conference website doesn't appear to have any direct material or mentions pertaining to Bitcoin.
