### ISSUE TITLE
Crypto Bootcamp with Peter Kent & Matt Millen

### ISSUE THREAD

**Issue by neyeric** [bitcoin-dot-org/bitcoin.org#2754]
- date: 2018-11-28
      title: "Crypto Bootcamp with Peter Kent & Matt Millen [Free]"
      venue: "Live Streaming Event"
      address: ""
      city: ""
      country: ""
      link: "https://www.facebook.com/bestcryptotraining/posts/252619695419383"

**Comment by wbnns** [comment]
@neyeric Hello, thank you, however, the events page isn't designed for online-only events at the moment. It has traditionally been used for physical, on-location events - this is why an address, city and country information are required.
