### ISSUE TITLE
Criptolandia

### ISSUE THREAD

**Issue by AleFernandez** [bitcoin-dot-org/bitcoin.org#2761]
- date: 2018-12-15
      title: "Criptolandia"
      venue: "Chía"
      address: "Av. Pradilla #3-47"
      city: "Bogotá"
      country: "Colombia"
      link: "https://www.weacceptbitcoin.world/listing/criptolandia/
![001-01](https://user-images.githubusercontent.com/20295418/48963106-cd485e80-ef59-11e8-9fe4-bfa643f488dd.png)
![001-02](https://user-images.githubusercontent.com/20295418/48963107-cd485e80-ef59-11e8-8958-2149c0623fb4.png)
![001-03](https://user-images.githubusercontent.com/20295418/48963108-cde0f500-ef59-11e8-9a3e-95e71d8eabc7.png)
![001-04](https://user-images.githubusercontent.com/20295418/48963109-cde0f500-ef59-11e8-9d65-ec167796936e.png)
![001-05](https://user-images.githubusercontent.com/20295418/48963110-cde0f500-ef59-11e8-9f29-344ba64c7cb1.png)
![001-07](https://user-images.githubusercontent.com/20295418/48963111-cde0f500-ef59-11e8-9775-4cef03678a51.png)
![001-10](https://user-images.githubusercontent.com/20295418/48963112-cde0f500-ef59-11e8-88ac-eb3c61a6e407.png)
![001-11](https://user-images.githubusercontent.com/20295418/48963113-cde0f500-ef59-11e8-817b-9c08839debf1.png)

"

**Comment by khendraw** [comment]
Cannot open the event link, but find it on the Facebook page https://www.facebook.com/CriptoLandiaOK/
- This event is not specifically related to Bitcoin, more like about blockchain re-evolution.
- Not sure the talk will be specifically about Bitcoin, but one of the speaker will talk about Bitcoin and the wold of cryptocurrencies.
- There is no information if there will be talk focused on ICOs and other digital currencies.
- I believe this event can be added to Bitcoin.org

![image](https://user-images.githubusercontent.com/26235601/49557889-baf7f880-f93b-11e8-9259-601c84b25568.png)
