### ISSUE TITLE
Blockchain Conference Philippines December 6

### ISSUE THREAD

**Issue by Viktoria-M** [bitcoin-dot-org/Bitcoin.org#2762]
- date: 2018-12-06
      title: "Blockchain Conference Philippines"
      venue: "HOLIDAY INN & SUITES MAKATI 
Palm Drive"
      address: "Ayala Centre, Makati 1224"
      city: "Manila"
      country: "Philippines"
      link: "https://philippines.bc.events
![300x200](https://user-images.githubusercontent.com/40798045/49016753-b8551080-f18f-11e8-9c80-b3e5ff1a2c40.png)

**Comment by khendraw** [comment]
- This event is not specifically related to Bitcoin, more like blockchain and cryptocurrency in general.
- I don't think there will be a talk focused exclusively on Bitcoin on this event.
- After checking out the speakers, I think most of the talks will be focused on ICOs and other digital currencies.
- I think this event is not suitable to be added on Bitcoin.org
