### ISSUE TITLE
Wallet selection, mSignal/ciphrex is dead. Missing Wasabi wallet.

### ISSUE THREAD

**Issue by Transisto** [bitcoin-dot-org/bitcoin.org#2765]
Add https://wasabiwallet.io/

Remove https://ciphrex.com/team/

They haven't tweeted anything since 2017 and their linked website is down.

**Comment by wbnns** [comment]
@Transisto 

Hello, thank you for bringing this to attention. Opened #2767 to drop mSIGNA.

With regard to Wasabi wallet, here is a link to our [wallet listing requirements](https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/docs/managing-wallets.md#wallets) in case you'd like to share the link with them and they'd like to be a part of the site.
