### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by jenniferpeng1215** [bitcoin-dot-org/bitcoin.org#2783]
- date: 2018-12-31
      title: "New Years Eve 2019 - The Genesis Block: Bitcoin's 10 Year Anniversary"
      venue: "Mykonos Blue Rooftop"
      address: "127 West 28th Street"
      city: "New York City"
      country: "U.S."
      link: "https://www.eventbrite.com/e/new-years-eve-2019-the-genesis-block-bitcoins-10-year-anniversary-tickets-53468591998"

**Comment by khendraw** [comment]
This event is specifically related to Bitcoin.
There is no talk focused on Bitcoin or ICOs and/or other digital currencies, it is just a celebrating the 10-year anniversary of Bitcoin’s Genesis Block on the new year's eve.
This event can be added to the Bitcoin.org
