### ISSUE TITLE
Coin.Space wallet non-functional

### ISSUE THREAD

**Issue by crwatkins** [bitcoin-dot-org/bitcoin.org#2784]
A listed wallet appears to be non-functional. 

@jspeigner @nikashitsa The Coin.Space wallet currently does not seem to be functional. Correct PIN entries return “en*undefined is not a valid address”.   Can you comment?  Does this affect all wallets?

**Comment by nikashitsa** [comment]
Yes, all BTC users can't login now.
We are working on it https://twitter.com/CoinAppWallet/status/1072332434719600641
XRP, XLM and LTC are alive now. ETH will be next, BTC and BCH after.

Sorry for the inconvenience.

**Comment by crwatkins** [comment]
@nikashitsa Thanks for the update.  When things are working again and you get a chance, let us know if you think this can be avoided in future (did it also happen a few months ago?).  Also, a better error message than “en*undefined is not a valid address” would help a lot.

**Comment by nikashitsa** [comment]
@crwatkins Done. Coin.Space wallet is alive now.

**Comment by crwatkins** [comment]
Thanks.
