### ISSUE TITLE
New event: Bitcoin 10 years ~ 2009 - 2019

### ISSUE THREAD

**Issue by annetdeboer** [bitcoin-dot-org/bitcoin.org#2793]
- date: 2019-01-20
      title: "Bitcoin 10 years ~ 2009 - 2019"
      venue: "Barley's Oriental Garden"
      address: "Pauwstraat 4"
      city: "Arnhem Bitcoin City"
      country: "The Netherlands"
      link: "https://www.arnhembitcoinstad.nl"

**Comment by khendraw** [comment]
Is this event specifically related to Bitcoin? Yes
Is there a talk focused exclusively on Bitcoin? Yes
Are the majority of talks focused on ICOs and/or other digital currencies? No
Yes, I think this event should be added to Bitcoin.org
