### ISSUE TITLE
my bitcoin node keep disconnecting

### ISSUE THREAD

**Issue by amcitaly** [bitcoin-dot-org/bitcoin.org#2805]
Hello dears, I have start few days ago my bitcoin node, it works but each 20/30 minutes keep disconnecting and connecting again. The ports are open, the firewall is down (win+router) the sleeping mode of pc is off. I can't understand what is, can someone help me ? Thank you, Alex

**Comment by wbnns** [comment]
@amcitaly 

Hello, here's a link to forums where you can connect with others who may be able to help you with your issue: https://bitcoin.org/en/bitcoin-core/help#forums

**Comment by amcitaly** [comment]
thank you !
