### ISSUE TITLE
Blockchain Strefa Elbląg #1

### ISSUE THREAD

**Issue by thechainers** [bitcoin-dot-org/bitcoin.org#2812]
Blockchain Strefa Elbląg #1 ⚡

➡️ Interesuje Cię temat technologii blockchain?
➡️ Chcesz dowiedzieć więcej o kryptowalutach?
➡️ Szukasz innowacyjnego rozwiązania dla Twojego biznesu?
➡️ A może zależy Tobie na nawiązaniu nowych kontaktów biznesowych?

💥 Jeśli tak to przyjdź na nasze spotkanie! Jego celem jest networking, budowanie lokalnej społeczności, ale również wymiana doświadczeń oraz wiedzy związanej z technologią blockchain oraz kryptowalutami. Nie będzie prelekcji, wystąpień- to luźne spotkanie przy kawie i ciastkach. 🍻

💥 Dowiedz się jak wdrożyć nowe technologie w swojej firmie oraz jak pozyskać finansowanie na innowacyjne projekty.

💥 Przyjdź i poznaj grupę miłośników krypto oraz tych, którzy chcą zacząć swoją przygodę z walutami cyfrowymi.

📣 Udostępnij nasze wydarzenie, niech trafi do jak największego grona odbiorców! 

Nasze spotkanie inspirowane jest sukcesem poznańskich spotkań Bitcoin Tej, którzy są również współorganizatorem pierwszego spotkania z serii #BlockchainStrefaElblag. 

➡️ Kiedy? 31.01.2019, godz. 18:00
➡️ Gdzie? Elbląski Park Technologiczny, ul. Stanisława Sulimy 1/109 (82-300 Elbląg)
💸 Wejście na spotkanie jest całkowicie darmowe!
Natomiast rejestracja jest OBOWIĄZKOWA!

Obserwuj nas na naszych SM!
⚫ Facebook: Chainers Group 
🔴 Instagram: TheChainers
🔵 Twitter: TheChainers

Dołącz do nas! 😎

**Comment by khendraw** [comment]
Is this event specifically related to Bitcoin? No
Is there a talk focused exclusively on Bitcoin? No
Are the majority of talks focused on ICOs and/or other digital currencies? No, it is all about blockchain technology & cryptocurrencies in general.
In my opinion this event is not to be added to Bitcoin.org
