### ISSUE TITLE
German introduction: "buy" & "sell" links to english content

### ISSUE THREAD

**Issue by Stadicus** [bitcoin-dot-org/bitcoin.org#2816]
On the german "Erste Schritte" (first steps) page, the button that link for "buy" and "spend" bitcoin link to the english pages:

* Bitcoin kaufen
  * links to https://bitcoin.org/en/buy
  * instead of https://bitcoin.org/de/kaufen

* Händler und Produkte finden
  * links to https://bitcoin.org/en/spend-bitcoin
  * instead of https://bitcoin.org/de/bitcoins-ausgeben

I checked the YAML translation, the `url` section correctly references `buy: kaufen` and `spend-bitcoin: bitcoins-ausgeben`.

Unrelated: while browsing the translation, I found several other hard-coded links to english pages (`/en/...`). I can create a pull-request for that, but I think the main issue are the buttons (not sure how to fix that).

**Comment by wbnns** [comment]
@Stadicus 

Hello, thanks for reporting this. I've opened #2823 to resolve this issue for the 'Exchange', 'Buy' and 'Spend' pages. For other pages you see, please let us know and we'll update those as well. We need to do a site-wide comb-through to look for hard-coded links that aren't correctly pointing to translated versions of pages that have been added over the years.
