### ISSUE TITLE
Malta AI & Blockchain Summit

### ISSUE THREAD

**Issue by Surya-Maneesh** [bitcoin-dot-org/bitcoin.org#2821]
- date: 2019-05-22
      title: "Malta AI & Blockchain Summit"
      venue: "TBA, Malta"
      address: "TBA, Malta"
      city: "Malta"
      country: "Malta"
      link: "https://maltablockchainsummit.com/"

**Comment by khendraw** [comment]
Is this event specifically related to Bitcoin? No
Is there a talk focused exclusively on Bitcoin? No
Are the majority of talks focused on ICOs and/or other digital currencies? Yes
This event is not to be added to Bitcoin.org
