### ISSUE TITLE
CoinFestUK 2019

### ISSUE THREAD

**Issue by CoinFestUK** [bitcoin-dot-org/bitcoin.org#2822]
date: 2019-04-04
title: "CoinFestUK2019"
venue: "Manchester Conference Centre"
address: "Sackville Street"
city: ", Manchester M1 3BB"
country: "UK"
link: "http://coinfestuk.org/"

**Comment by CosmicHemorroid** [comment]
They should be called. ShitCoinFestUK. They supported Bitcoin Classic, S2X and Bitcoin Cash over Bitcoin. 

Nack
