### ISSUE TITLE
New event "Bitcoin TechDays"

### ISSUE THREAD

**Issue by DanielSanW** [bitcoin-dot-org/bitcoin.org#2825]
- date: 2019-02-12
      title: "Bitcoin TechDays 2019"
      venue: "JetBrains Event Space"
      address: "Elsenheimerstraße 47A"
      city: "Munich"
      country: "Germany"
      link: "https://bitcoin-techdays.org/"

**Comment by khendraw** [comment]
Is this event specifically related to Bitcoin? Yes
Is there a talk focused exclusively on Bitcoin? Yes
Are the majority of talks focused on ICOs and/or other digital currencies? No
Yes, this event should be added to the Bitcoin.org
