### ISSUE TITLE
FRAUD in Bitcoin

### ISSUE THREAD

**Issue by Vilaggio** [bitcoin-dot-org/bitcoin.org#2826]
I have received my 3rd email threatening me if I don't pay money through a bitcoin account. While I DO NOT feel threatened personally, these criminals are using your platform to scam people. I actually thought it was funny as it doesn't describe me at all. I tracked their IP to Portugal. The body of the email is below. It contains the bitcoin account info.

Thanks!

As you may have noticed, I sent you an email from your account.
This means that I have full access to your account.

I've been watching you for a few months now.
The fact is that you were infected with malware through an adult site that you visited.

If you are not familiar with this, I will explain.
Trojan Virus gives me full access and control over a computer or other device.
This means that I can see everything on your screen, turn on the camera and microphone, but you do not know about it.

I also have access to all your contacts and all your correspondence.

Why your antivirus did not detect malware?
Answer: My malware uses the driver, I update its signatures every 4 hours so that your antivirus is silent.

I made a video showing how you satisfy yourself in the left half of the screen, and in the right half you see the video that you watched.
With one click of the mouse, I can send this video to all your emails and contacts on social networks.
I can also post access to all your e-mail correspondence and messengers that you use.

If you want to prevent this,
transfer the amount of $630 to my bitcoin address (if you do not know how to do this, write to Google: "Buy Bitcoin").

My bitcoin address (BTC Wallet) is: **1Jh1miFmhTmGQvn6Zejaqg85viD4k1vVjG**

After receiving the payment, I will delete the video and you will never hear me again.
I give you 48 hours to pay.
I have a notice reading this letter, and the timer will work when you see this letter.

Filing a complaint somewhere does not make sense because this email cannot be tracked like my bitcoin address.
I do not make any mistakes.

If I find that you have shared this message with someone else, the video will be immediately distributed.

Best wishes!

**Comment by wbnns** [comment]
@Vilaggio 

Hello, thanks for the report. Yes, this is a [common type of scam](https://bitcoin.org/en/scams#blackmail). This isn't specifically related to bitcoin.org, however. With Bitcoin, there isn't a central authority that controls who and/or what kinds of transactions can take place on the network. Here's more information on [how it works](https://bitcoin.org/en/how-it-works).

**Comment by Vilaggio** [comment]
I wasn’t really worried about the email. 

 

Thank you,

 

Michael Schlotthauer

919-424-6040

 <http://www.vilaggio.net/>
