### ISSUE TITLE
BitBlockBoom!

### ISSUE THREAD

**Issue by GaryLeland** [bitcoin-dot-org/bitcoin.org#2832]
- date: 2019-08-17
      title: "BitBlockBoom"
      venue: "Renaissance Dallas Addison Hotel"
      address: "15201 Dallas Parkway"
      city: "Addison, TX 75001"
      country: "US"
      link: "https://bitblockboom.com/
![bitcoinconference 2](https://user-images.githubusercontent.com/46818359/51870110-3f517100-2318-11e9-850e-cfac72400f1b.png)
"

**Comment by khendraw** [comment]
1. Is this event specifically related to Bitcoin? Yes
2. Is there a talk focused exclusively on Bitcoin? Yes
3. Are the majority of talks focused on ICOs and/or other digital currencies? No
In my opinion this event should be added to Bitcoin.org

**Comment by GaryLeland** [comment]
Yes, this is a Bitcoin-only event.

Thank you.



GaryLeland.com        CryptoCousins.com        4MinuteCrypto.com

CryptoCrybaby.com   ArlingtonCrypto.com        BitBlockBoom.com

**Comment by annetdeboer** [comment]
@GaryLeland You have a typo in your meetup title; to prevent it from being copy/pasted in the site I suggest you take a quick look :)

**Comment by GaryLeland** [comment]
Thanks very much. I think it is now fixed.
