### ISSUE TITLE
KeepKey reportedly has reproducible builds now

### ISSUE THREAD

**Issue by JeremyRand** [bitcoin-dot-org/bitcoin.org#2836]
KeepKey is listed on Bitcoin.org as "Basic transparency", indicating that it doesn't have reproducible builds.  However, the KeepKey website [indicates](https://www.keepkey.com/keepkey/faq/security/) that KeepKey does have reproducible builds now.  If the KeepKey website's claim is accurate (I haven't tried to reproduce the build myself), then presumably Bitcoin.org should be updated accordingly.

**Comment by crwatkins** [comment]
@keepkeyjon Do you believe that third parties can currently perform deterministic builds of your released code?

If so, would you like to submit a PR to update your listing on bitcoin.org or would you like to request that we do it?

**Comment by keepkeyjon** [comment]
Our builds should be deterministic as of a little less than a year ago. If they're not, definitely call us out on it, and we'll work on fixing it. Instructions here: https://github.com/keepkey/keepkey-firmware#verifying-published-binaries

I'm happy to submit a PR.

**Comment by crwatkins** [comment]
@JeremyRand Thanks for the update.
