### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by 4tochka** [bitcoin-dot-org/bitcoin.org#2842]
- date: 2019-06-08
      title: "Breaking Bitcoin"
      venue: "THE Bitcoin security event"
      address: ""
      city: "Amsterdam"
      country: "The Netherlands"
      link: "https://breaking-bitcoin.com"

**Comment by khendraw** [comment]
- Is this event specifically related to Bitcoin? Yes
- Is there a talk focused exclusively on Bitcoin? Yes
- Are the majority of talks focused on ICOs and/or other digital currencies? No
- In my opinion this event should be added to Bitcoin.org
