### ISSUE TITLE
Not possible to navigate to a wallet's other platforms

### ISSUE THREAD

**Issue by crwatkins** [bitcoin-dot-org/bitcoin.org#2844]
Once a platform (e.g. iOS) is chosen for a particular wallet, we have no way for the user to navigate to another platform for that same wallet (e.g. Android).

1. Select "Choose your wallet"
2. Select the iOS option for wallet BRD  (and see the iOS entry with iOS download links)
3. Select Android from the chooser below BRD

Results:  Selection of wallets change, but BRD is not displayed in the choices and thus there is no way to switch the display (scoring and links) to the Android version of BRD.

Note that we don't ever display the selected wallet in the choices below which leads to this problem.  I believe the selected wallet should always appear in the choices.

**Comment by wbnns** [comment]
@crwatkins

Thanks for reporting. What OS and browser are you experiencing this behavior in?

**Comment by crwatkins** [comment]
Sorry:  Desktop browsers
