### ISSUE TITLE
Replace Airbitz with Edge

### ISSUE THREAD

**Issue by crwatkins** [bitcoin-dot-org/bitcoin.org#2853]
@paullinator @i3inary It seems that Airbitz is receiving no new updates and immediately directs users to Edge.  Is it [now time](https://github.com/bitcoin-dot-org/bitcoin.org/pull/2368#issuecomment-389787061) to remove Airbitz?

**Comment by crwatkins** [comment]
(pinging @paullinator @i3inary in case the edit to the last comment didn't cause a ping)

**Comment by paullinator** [comment]
Yes we’re fine removing Airbitz now. Thanks for the patience.
