### ISSUE TITLE
Metahash (MHC) KuCoin Exchange Listing with Promotion

### ISSUE THREAD

**Issue by DonnaFRogers** [bitcoin-dot-org/bitcoin.org#2854]
- date: 2019-02-13
      title: "Metahash (MHC) KuCoin Exchange Listing with Promotion"
      venue: "online"
      address: "online"
      city: "online"
      country: "online"
      link: "https://blog.kucoin.com/metahash-mhc-gets-listed-on-kucoin-further-information-and-promotion-details/"

**Comment by khendraw** [comment]
- Is this event specifically related to Bitcoin? No
- Is there a talk focused exclusively on Bitcoin? No
- Are the majority of talks focused on ICOs and/or other digital currencies? Yes
I believe this event should not be added to Bitcoin.org
