### ISSUE TITLE
Cripto Latin Fest 2019 Blockchain

### ISSUE THREAD

**Issue by santiago08** [bitcoin-dot-org/bitcoin.org#2860]
- date: 2019-05-18-19
  title: "Cripto Latin Fest 2019"
  venue: "Hacienda_San_Rafael_Bogota_Colombia"
  address: "carrera 57 N° 133 – 00"
  city: "Bogota"
  country: "Colombia"
  link: "www.criptolatinfest.com"
![clf2019](https://user-images.githubusercontent.com/37759649/52908911-c8d7cd00-324c-11e9-8dee-c7a58205c5a0.png)

**Comment by khendraw** [comment]
- Is this event specifically related to Bitcoin? No
- Is there a talk focused exclusively on Bitcoin? No
- Are the majority of talks focused on ICOs and/or other digital currencies? Yes
- In your opinion, should this event be added to Bitcoin.org? No

**Comment by santiago08** [comment]
> * ¿Este evento está específicamente relacionado con Bitcoin? No
> * ¿Hay una charla centrada exclusivamente en Bitcoin? No
> * ¿La mayoría de las conversaciones se centran en los ICO y / u otras monedas digitales? Sí
> * En su opinión, ¿debería agregarse este evento a Bitcoin.org? No

En el evento pasado si fuimos agregados a Bitcoin.org  
No entiendo por que esta vez dices que NO
SI hablamos del bitcoin
No hablamos de solo icos y otras cripto, Tambien hablamos de blockchain y mas tecnologia

**Comment by wbnns** [comment]
@santiago08 

Hola, el problema es que no hay menciones específicas de Bitcoin en el contenido o en los temas en el sitio web para el evento, solo términos muy genéricos como tokens y tecnología de blockchain.

**Comment by santiago08** [comment]
> @santiago08
> 
> Hola, el problema es que no hay menciones específicas de Bitcoin en el contenido o en los temas en el sitio web para el evento, solo términos muy genéricos como tokens y tecnología de blockchain.

Que debo enviar para mostrar que si se habla del bitcoin, es mas es el tema principal para los que no conocen del bitcoin

**Comment by wbnns** [comment]
@santiago08 
> es mas es el tema principal para los que no conocen del bitcoin

La página de eventos es para aquellos en los que el tema principal es sobre Bitcoin, que no parece ser el caso al revisar la página de inicio del evento. Es por esto que no podríamos agregarlo a la página de eventos.

Si otros colaboradores de bitcoin.org quisieran revisar su sitio web y no estén de acuerdo con la conclusión de @khendraw y yo, estaremos feliz de reconsiderarlo.

**Comment by santiago08** [comment]
> @santiago08
> 
> > es mas es el tema principal para los que no conocen del bitcoin
> 
> La página de eventos es para aquellos en los que el tema principal es sobre Bitcoin, que no parece ser el caso al revisar la página de inicio del evento. Es por esto que no podríamos agregarlo a la página de eventos.
> 
> Si otros colaboradores de bitcoin.org quisieran revisar su sitio web y no estén de acuerdo con la conclusión de @khendraw y yo, estaremos feliz de reconsiderarlo.

No entiendo, este evento es el mismo del año pasado y ese si me lo aceptaron en bitcoin.org

**Comment by wbnns** [comment]
@santiago08 

> No entiendo, este evento es el mismo del año pasado y ese si me lo aceptaron en bitcoin.org

Este es un nuevo requisito que adoptamos durante el año pasado. Anteriormente, éramos mucho más liberales con respecto a los eventos que se agregarían, pero muchos de los eventos que los organizadores/promotores querían agregar comenzaron a centrarse menos en Bitcoin y más en ICOs, altcoins y un tema genérico sobre la tecnología blockchain.

**Comment by santiago08** [comment]
bueno amigo igualmente gracias.
a pesar que el evento lo mas principal es el bitcoin, ya ustedes no creen, y en temas como ico y cripto enseñamos a no caer en estafas  y aprendizajes. 
no contamos con su apoyo igual muchas gracias
