### ISSUE TITLE
Free Trading On KuCoin For Platform 2.0 Launch

### ISSUE THREAD

**Issue by KaraCryptonite** [bitcoin-dot-org/bitcoin.org#2862]
Free Trading On KuCoin For Platform 2.0 Launch

In celebration of this special moment  for #KuCoinV2 Launch,  You can enjoy zero trading fees for all trading pairs, expiring at 23:59:59 Feb 21, 2019 (UTC+8).

See the event here: https://www.kucoin.com/activity/46

**Comment by wbnns** [comment]
Closing, duplicate of #2854.
