### ISSUE TITLE
CoinsBank Blockchain Cruise 2019

### ISSUE THREAD

**Issue by hpehoc13** [bitcoin-dot-org/bitcoin.org#2868]
- date: 2019-06-09
      title: "CoinsBank Blockchain Cruise 2019"
      venue: "Barcelona,Palma de Mallorca, Marseille, La Spezia, Rome"
      address: "Barselona"
      city: "Barselona"
      country: "Spain"
      link: "http://bit.ly/coinsbank-cruises"
![1](https://user-images.githubusercontent.com/47857701/53173714-46a72a00-35f9-11e9-9ad9-013cd37d618b.png)

**Comment by khendraw** [comment]
- Is this event specifically related to Bitcoin? Not specifically
- Is there a talk focused exclusively on Bitcoin? No
- Are the majority of talks focused on ICOs and/or other digital currencies? No
- In your opinion, should this event be added to Bitcoin.org? No
