### ISSUE TITLE
TEAMZ Blockchain Summit

### ISSUE THREAD

**Issue by 8967876** [bitcoin-dot-org/bitcoin.org#2870]
- date: 2019-04-06
      title: "TEAMZ Blockchain Summit"
      venue: "Toranomon Hills"
      address: "1-23-3 Toranomon, Minato-ku,"
      city: "Tokyo"
      country: "Japan"
      link: "https://summit.teamz.co.jp
![d31083-13-403476-5](https://user-images.githubusercontent.com/47884552/53231485-61969e80-36cc-11e9-80fe-4de3351be37a.jpg)
"

**Comment by khendraw** [comment]
- Is this event specifically related to Bitcoin? No
- Is there a talk focused exclusively on Bitcoin? No
- Are the majority of talks focused on ICOs and/or other digital currencies?  Yes
- In your opinion, should this event be added to Bitcoin.org? No
