### ISSUE TITLE
Events map uses http:// to load background layer

### ISSUE THREAD

**Issue by annetdeboer** [bitcoin-dot-org/bitcoin.org#2879]
There is a Leaflet map on the Events page which loads the OSM background map through http:// instead of https:// 

This leads to browser messages "Connection is not secure" / Loading mixed (insecure) display content 

https://bitcoin.org/en/events

**Comment by wbnns** [comment]
@annetdeboer Thanks for bringing this to attention. Opened #2890 to resolve the issue.
