### ISSUE TITLE
CoinsBank Blockchain Cruise 2019

### ISSUE THREAD

**Issue by hpehoc13** [bitcoin-dot-org/bitcoin.org#2880]
- date: 2019-06-09
      title: "CoinsBank Blockchain Cruise 2019"
      venue: "Barcelona"
      address: "port Barcelona"
      city: "Barcelona"
      country: "Spain"
     http://bit.ly/coinsbank-cruises
![7](https://user-images.githubusercontent.com/47857701/53756560-77754200-3eca-11e9-8c02-5001bc62d849.png)

**Comment by annetdeboer** [comment]
This event was already submitted in issue #2868
