### ISSUE TITLE
New event: Coinfest 2019 in Arnhem Bitcoincity

### ISSUE THREAD

**Issue by annetdeboer** [bitcoin-dot-org/bitcoin.org#2881]
- date: 2019-04-01
      title: "Coinfest 2019"
      venue: "MeeM"
      address: "Coehoornstraat 8"
      city: "Arnhem Bitcoin City"
      country: "The Netherlands"
      link: "https://www.arnhembitcoinstad.nl"

**Comment by khendraw** [comment]
- Is this event specifically related to Bitcoin? Yes
- Is there a talk focused exclusively on Bitcoin? Yes
- Are the majority of talks focused on ICOs and/or other digital currencies? No
- In your opinion, should this event be added to Bitcoin.org? Yes
