### ISSUE TITLE
bitFlyer US link (North America section) is directing to Japanese site

### ISSUE THREAD

**Issue by ryanortega** [bitcoin-dot-org/bitcoin.org#2882]
bitFlyer US Link (North America section) is directing to Japanese site:  https://bitcoin.org/en/exchanges#north-america

Link is going here:  https://bitflyer.com/ja-jp/

Instead of the US link here: https://bitflyer.com/en-us (which is at the top of the jp page). Should this be linked directly to the US part of the website?

**Comment by wbnns** [comment]
@ryanortega 

>Should this be linked directly to the US part of the website?

Yes, it should. Thank you for mentioning. We'll fix it.
