### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by MiningDisrupt** [bitcoin-dot-org/bitcoin.org#2893]
- date: 2019-07-24
      title: "Mining Disrupt 2019"
      venue: "DoubleTree Hilton MAAC"
      address: "711 NW 72nd Ave"
      city: "Miami"
      country: "USA"
      link: "www.miningdisrupt.com"

**Comment by khendraw** [comment]
- Is this event specifically related to Bitcoin? No
- Is there a talk focused exclusively on Bitcoin? No
- Are the majority of talks focused on ICOs and/or other digital currencies? No, this event is all about cryptomining.

In my opinion this event is not to be added to Bitcoin.org

**Comment by MiningDisrupt** [comment]
Hello Khendraw,
 
Thank you for the swift response. I don't see where you are deriving your opinions from. But we do have cryptocurrency and Bitcoin topics at the event, if you scroll down and see the schedule, it has topics such as "Introduction to Bitcoin", "Rise of Cryptocurrency by Cypherpunks", and "Need for Bitcoin Alternatives", etc.
 
https://www.eventbrite.com/e/mdc-disrupt-conference-miami-2019-tickets-57880812067
 
Thank you for your time.
 
Best regards,
Robin Lam
--------- Original Message --------- Subject: Re: [bitcoin-dot-org/bitcoin.org] New event (#2893)

**Comment by khendraw** [comment]
Hello,

Thank you for your response.

My opinions are derived from the facts if the event is specifically related to Bitcoin - whics is unfortunately not **specifically related**, since the event is more on the cryptomining and blockchain in general. And since I cannot see any talk focused on Bitcoin on the link you've provided earlier https://miningdisrupt.com/, I decide that there is no talk focused exclusively on Bitcoin until I see it in the page you are referring later https://www.eventbrite.com/e/mdc-disrupt-conference-miami-2019-tickets-57880812067. 
So here I go again -
+ Is this event specifically related to Bitcoin? No
+ Is there a talk focused exclusively on Bitcoin? Yes, 20 minutes - Introduction to Bitcoin talk.
+ Are the majority of talks focused on ICOs and/or other digital currencies? No.
Yet, still since I cannot see if this event is specifically related on Bitcoin - even there is a talk about The Need for Bitcoin Alternatives so I believe this event is not to be added to Bitcoin.org

Regards,
KHendraw

**Comment by MiningDisrupt** [comment]
Hello KHendraw,
 
I appreciate your quick response and the fact that you took the time to respond. I wanted to clear up any misconceptions on the below.
 
This conference is not solely based around Bitcoin, it is about emerging blockchain/crypto companies and mining.  We plan to have open discussions about the current crypto ecosystem and the future.  These discussions will not be limited to, but will include the discussion of Bitcoin.  In addition to the discussion of Bitcoin, we plan to also dive deep on PoW on the mining side which is an integral component of Bitcoin.  Although the conference is not Bitcoin specific, it will have a rich Bitcoin presence.  Right now the talks are general discussion topics that we do plan to edit.  We are open to having a discussion specific to Bitcoin and a few of our current speakers have engaged us to have a Bitcoin specific discussion.  
 
I understand you do not think it is in the best interest of Bitcoin.org to participate, if there is any other organization or group that you believe may receive value from attending this event, feel free to let us know.  We are also open to a potential referral partnership.  
 
 
 
 
Thanks,
 
Fernando L. Rivero, MSF
 
--------- Original Message --------- Subject: Re: [bitcoin-dot-org/bitcoin.org] New event (#2893)

**Comment by wbnns** [comment]
@khendraw Thank you. 

@MiningDisrupt Apologies that the event wouldn't be a fit for the website, but thank you for taking the time to clarify and make the submission.

**Comment by MiningDisrupt** [comment]
THE NIGHT TO ENJOY, LEARN, AND SHARE
The silent revolution is happening in Atlanta. Underneath the sunny skies, a technological hurricane is sweeping across the world. Hear from the best and brilliant minds of Georgia. From beginners to experts, all levels of expertise are welcomed to join us this Atlanta Blockchain Week.



Celebrate the bull market with early adopters, investors, and entrepreneurs. Engage with industry titans, executives, and leaders of this fast growing industry. Become a part of history in the making as xDisrupt debuts products and services that never been disclosed to the public before.


SCHEDULE*
4:00pm - Check-In and Registration
4:30pm - Opening Remarks / Door Closes
4:45pm - Panel: Blockchain Security and CryptoHacking
5:15pm - Panel: Effects of Tokenization on Loyalty Programs
5:45pm - Panel: Rewards, Incentives, and Payment Systems
6:00pm - Panel: CryptoMining Enterprise Solutions
6:30pm - Closing Remarks / Post-Networking
8:30pm - Official Networking Afterparty
*Subject to change



Frequently Asked Questions (FAQs)
Are there ID or minimum age requirements to enter the event? Attendees must be at least 21+ years old with valid ID to drink alcoholic beverages. Underage attendees will be given a bracelet indicating they are underage, therefore cannot drink the alcoholic beverages. All attendees must bring (1) a valid government ID with name matching their ticket and (2) a print out of their ticket or a copy on their mobile device.
Is it okay if the name on my ticket or registration doesn't match the person who attends? No. All attendees must have a valid ID that matches their name on the purchased ticket(s). Failure to do so may result in denied entry into the event.
My ticket was purchased under someone else's name / I am apart of a group ticket, what do I do? Please still bring your valid ID but all members purchased under one name must be present at the door with the original ticket owner. Failure to do so may result in denied entry into the event.
Is there parking available? Yes, there is street parking and nearby public parking garages.
Disclaimer: This is not financial advice or legal advice or medical advice. Please conduct your own self-research with due diligence. All sales are final. No refunds. Not transferable.



Tags

------------------------------
Event Summary:
------------------------------

Event: BlokTech xDisrupt: Atlanta | Bitcoin, Blockchain, and Cryptocurrency
Date: Saturday, September 28, 2019 from 4:00 PM to 6:30 PM (EDT)
Location: &lt;b&gt;West Side Midtown Studio&lt;/b&gt;&lt;br /&gt;1425 Ellsworth Industrial Blvd&lt;br /&gt;Suite 9&lt;br /&gt;Atlanta, GA 30318

------------------------------
Event Details:
------------------------------

xDisrupt 2019: Atlanta Edition | Premier Blockchain, Security, and Enterprise Solutions

------------------------------
Hosted By:
------------------------------
MDC


------------------------------
Register Online:
------------------------------

More information and online registration are available here:
https://www.eventbrite.com/e/bloktech-xdisrupt-atlanta-bitcoin-blockchain-and-cryptocurrency-tickets-72332204571?ref=enivtefor001&invite=MTc1OTEyNzkvcmVwbHkrMDJlNDE2YTllNTYyYjM2OTcyMTFkZGViNGI1N2Y4NDQyOGQ1YjhmMTJh%0AMzRiZGY0OTJjZjAwMDAwMDAxMThhMzhlMjQ5MmExNjljZTE5MGQyOTZhQHJlcGx5LmdpdGh1Yi5j%0Ab20vMA%3D%3D%0A

----------------------------------------------------------------------

Collect event fees online with Eventbrite
http://www.eventbrite.com

**Comment by MiningDisrupt** [comment]
THE NIGHT TO ENJOY, LEARN, AND SHARE
The silent revolution is happening in Atlanta. Underneath the sunny skies, a technological hurricane is sweeping across the world. Hear from the best and brilliant minds of Georgia. From beginners to experts, all levels of expertise are welcomed to join us this Atlanta Blockchain Week.



Celebrate the bull market with early adopters, investors, and entrepreneurs. Engage with industry titans, executives, and leaders of this fast growing industry. Become a part of history in the making as xDisrupt debuts products and services that never been disclosed to the public before.


SCHEDULE*
4:00pm - Check-In and Registration
4:30pm - Opening Remarks / Door Closes
4:45pm - Panel: Blockchain Security and CryptoHacking
5:15pm - Panel: Effects of Tokenization on Loyalty Programs
5:45pm - Panel: Rewards, Incentives, and Payment Systems
6:00pm - Panel: CryptoMining Enterprise Solutions
6:30pm - Closing Remarks / Post-Networking
8:30pm - Official Networking Afterparty
*Subject to change



Frequently Asked Questions (FAQs)
Are there ID or minimum age requirements to enter the event? Attendees must be at least 21+ years old with valid ID to drink alcoholic beverages. Underage attendees will be given a bracelet indicating they are underage, therefore cannot drink the alcoholic beverages. All attendees must bring (1) a valid government ID with name matching their ticket and (2) a print out of their ticket or a copy on their mobile device.
Is it okay if the name on my ticket or registration doesn't match the person who attends? No. All attendees must have a valid ID that matches their name on the purchased ticket(s). Failure to do so may result in denied entry into the event.
My ticket was purchased under someone else's name / I am apart of a group ticket, what do I do? Please still bring your valid ID but all members purchased under one name must be present at the door with the original ticket owner. Failure to do so may result in denied entry into the event.
Is there parking available? Yes, there is street parking and nearby public parking garages.
Disclaimer: This is not financial advice or legal advice or medical advice. Please conduct your own self-research with due diligence. All sales are final. No refunds. Not transferable.



Tags

------------------------------
Event Summary:
------------------------------

Event: BlokTech xDisrupt: Atlanta | Bitcoin, Blockchain, and Cryptocurrency
Date: Saturday, September 28, 2019 from 4:00 PM to 6:30 PM (EDT)
Location: &lt;b&gt;West Side Midtown Studio&lt;/b&gt;&lt;br /&gt;1425 Ellsworth Industrial Blvd&lt;br /&gt;Suite 9&lt;br /&gt;Atlanta, GA 30318

------------------------------
Event Details:
------------------------------

xDisrupt 2019: Atlanta Edition | Premier Blockchain, Security, and Enterprise Solutions

------------------------------
Hosted By:
------------------------------
MDC


------------------------------
Register Online:
------------------------------

More information and online registration are available here:
https://www.eventbrite.com/e/bloktech-xdisrupt-atlanta-bitcoin-blockchain-and-cryptocurrency-tickets-72332204571?ref=enivtefor001&invite=MTc1OTEyNzkvcmVwbHkrMDJlNDE2YTkxYTk4MWZkNjY3NTAzODVjYmIzMTlhNjFhZmZmZDc2Y2Ex%0AZDUzMjJjOTJjZjAwMDAwMDAxMThhMzY2MDI5MmExNjljZTE5MGQyOTZhQHJlcGx5LmdpdGh1Yi5j%0Ab20vMA%3D%3D%0A

----------------------------------------------------------------------

Collect event fees online with Eventbrite
http://www.eventbrite.com

**Comment by MiningDisrupt** [comment]
Mining Disrupt Conference (MDC) organizes the premier digital asset event in the Northern Hemisphere on 21-23 July, 2019 in Miami, Florida, where we explore the mining and blockchain enterprise solutions in-depth. We are shining a light on the global development of this new asset class, while taking a unique and widening perspective on the mining and token industry along with its opportunities.
Join the discussion before the conference www.t.me/MiningDisrupt

 

 

 

Never before ever in history has there been an event to host all of the major mining equipment manufacturers and distributors in one place at the same time... until Mining Disrupt.
Experience firsthand the power of cryptocurrency mining. Envision the future of blockchain technology. Engage with industry titans, leaders, and entrepreneurs of this fast growing industry. Become a part of history in the making as Mining Disrupt debuts products and services that have never been disclosed to the public before.

 

 

 

------------------------------
Event Summary:
------------------------------

Event: Mining Disrupt Conference 2020 | Bitcoin Blockchain Cryptocurrency Mining
Date: Wednesday, July 22, 2020 at 8:00 AM <span class="pipe">-</span> Thursday, July 23, 2020 at 11:00 PM (EDT)
Location: &lt;b&gt;DoubleTree by Hilton Hotel Miami Airport &amp; Convention Center&lt;/b&gt;&lt;br /&gt;711 Northwest 72nd Avenue&lt;br /&gt;Miami, FL 33126

------------------------------
Event Details:
------------------------------

The Bitcoin Blockchain and Mining Conference

------------------------------
Hosted By:
------------------------------
MDC


------------------------------
Register Online:
------------------------------

More information and online registration are available here:
https://www.eventbrite.com/e/mining-disrupt-conference-2020-bitcoin-blockchain-cryptocurrency-mining-tickets-67883333879?ref=enivtefor001&invite=MTc2OTk3MTEvcmVwbHkrMDJlNDE2YTllNTYyYjM2OTcyMTFkZGViNGI1N2Y4NDQyOGQ1YjhmMTJh%0AMzRiZGY0OTJjZjAwMDAwMDAxMThhMzhlMjQ5MmExNjljZTE5MGQyOTZhQHJlcGx5LmdpdGh1Yi5j%0Ab20vMA%3D%3D%0A

----------------------------------------------------------------------

Collect event fees online with Eventbrite
http://www.eventbrite.com

**Comment by MiningDisrupt** [comment]
Mining Disrupt Conference (MDC) organizes the premier digital asset event in the Northern Hemisphere on 21-23 July, 2019 in Miami, Florida, where we explore the mining and blockchain enterprise solutions in-depth. We are shining a light on the global development of this new asset class, while taking a unique and widening perspective on the mining and token industry along with its opportunities.
Join the discussion before the conference www.t.me/MiningDisrupt

 

 

 

Never before ever in history has there been an event to host all of the major mining equipment manufacturers and distributors in one place at the same time... until Mining Disrupt.
Experience firsthand the power of cryptocurrency mining. Envision the future of blockchain technology. Engage with industry titans, leaders, and entrepreneurs of this fast growing industry. Become a part of history in the making as Mining Disrupt debuts products and services that have never been disclosed to the public before.

 

 

 

------------------------------
Event Summary:
------------------------------

Event: Mining Disrupt Conference 2020 | Bitcoin Blockchain Cryptocurrency Mining
Date: Wednesday, July 22, 2020 at 8:00 AM <span class="pipe">-</span> Thursday, July 23, 2020 at 11:00 PM (EDT)
Location: &lt;b&gt;DoubleTree by Hilton Hotel Miami Airport &amp; Convention Center&lt;/b&gt;&lt;br /&gt;711 Northwest 72nd Avenue&lt;br /&gt;Miami, FL 33126

------------------------------
Event Details:
------------------------------

The Bitcoin Blockchain and Mining Conference

------------------------------
Hosted By:
------------------------------
MDC


------------------------------
Register Online:
------------------------------

More information and online registration are available here:
https://www.eventbrite.com/e/mining-disrupt-conference-2020-bitcoin-blockchain-cryptocurrency-mining-tickets-67883333879?ref=enivtefor001&invite=MTc2OTk3MTEvcmVwbHkrMDJlNDE2YTkxYTk4MWZkNjY3NTAzODVjYmIzMTlhNjFhZmZmZDc2Y2Ex%0AZDUzMjJjOTJjZjAwMDAwMDAxMThhMzY2MDI5MmExNjljZTE5MGQyOTZhQHJlcGx5LmdpdGh1Yi5j%0Ab20vMA%3D%3D%0A

----------------------------------------------------------------------

Collect event fees online with Eventbrite
http://www.eventbrite.com

**Comment by MiningDisrupt** [comment]
Hello Everyone!
 
HAPPY THANKSGIVING! Use the code "BLACKFRIDAY" to get 20% OFF on tickets starting today on Thanksgiving (November 28, 2019) until Cyber Monday (December 2, 2019). Even exhibition booths are 20% OFF, for exhibition booths please contact conference@miningdisrupt.com ; This offer expires at 5:00pm EST on December 2, 2019. Join the discussion before the conference at www.t.me/MiningDisrupt
 
-Mining Disrupt Team

------------------------------
Event Summary:
------------------------------

Event: Mining Disrupt Conference 2020 | Bitcoin Blockchain Cryptocurrency Mining
Date: Wednesday, July 22, 2020 at 8:00 AM <span class="pipe">-</span> Thursday, July 23, 2020 at 11:00 PM (EDT)
Location: &lt;b&gt;DoubleTree by Hilton Hotel Miami Airport &amp; Convention Center&lt;/b&gt;&lt;br /&gt;711 Northwest 72nd Avenue&lt;br /&gt;Miami, FL 33126

------------------------------
Event Details:
------------------------------

The Bitcoin Blockchain and Mining Conference

------------------------------
Hosted By:
------------------------------
MDC


------------------------------
Register Online:
------------------------------

More information and online registration are available here:
https://www.eventbrite.com/e/mining-disrupt-conference-2020-bitcoin-blockchain-cryptocurrency-mining-tickets-67883333879?ref=enivtefor001&invite=MTg0ODk2OTUvcmVwbHkrMDJlNDE2YTkxYTk4MWZkNjY3NTAzODVjYmIzMTlhNjFhZmZmZDc2Y2Ex%0AZDUzMjJjOTJjZjAwMDAwMDAxMThhMzY2MDI5MmExNjljZTE5MGQyOTZhQHJlcGx5LmdpdGh1Yi5j%0Ab20vMA%3D%3D%0A

----------------------------------------------------------------------

Collect event fees online with Eventbrite
http://www.eventbrite.com

**Comment by MiningDisrupt** [comment]
Hello Everyone!
 
HAPPY THANKSGIVING! Use the code "BLACKFRIDAY" to get 20% OFF on tickets starting today on Thanksgiving (November 28, 2019) until Cyber Monday (December 2, 2019). Even exhibition booths are 20% OFF, for exhibition booths please contact conference@miningdisrupt.com ; This offer expires at 5:00pm EST on December 2, 2019. Join the discussion before the conference at www.t.me/MiningDisrupt
 
-Mining Disrupt Team

------------------------------
Event Summary:
------------------------------

Event: Mining Disrupt Conference 2020 | Bitcoin Blockchain Cryptocurrency Mining
Date: Wednesday, July 22, 2020 at 8:00 AM <span class="pipe">-</span> Thursday, July 23, 2020 at 11:00 PM (EDT)
Location: &lt;b&gt;DoubleTree by Hilton Hotel Miami Airport &amp; Convention Center&lt;/b&gt;&lt;br /&gt;711 Northwest 72nd Avenue&lt;br /&gt;Miami, FL 33126

------------------------------
Event Details:
------------------------------

The Bitcoin Blockchain and Mining Conference

------------------------------
Hosted By:
------------------------------
MDC


------------------------------
Register Online:
------------------------------

More information and online registration are available here:
https://www.eventbrite.com/e/mining-disrupt-conference-2020-bitcoin-blockchain-cryptocurrency-mining-tickets-67883333879?ref=enivtefor001&invite=MTg0ODk2OTUvcmVwbHkrMDJlNDE2YTllNTYyYjM2OTcyMTFkZGViNGI1N2Y4NDQyOGQ1YjhmMTJh%0AMzRiZGY0OTJjZjAwMDAwMDAxMThhMzhlMjQ5MmExNjljZTE5MGQyOTZhQHJlcGx5LmdpdGh1Yi5j%0Ab20vMA%3D%3D%0A

----------------------------------------------------------------------

Collect event fees online with Eventbrite
http://www.eventbrite.com

**Comment by MiningDisrupt** [comment]
------------------------------
Event Summary:
------------------------------

Event: Mining Disrupt Conference 2020 | Bitcoin Blockchain Cryptocurrency Mining
Date: Wednesday, July 22, 2020 at 8:00 AM <span class="pipe">-</span> Thursday, July 23, 2020 at 11:00 PM (EDT)
Location: &lt;b&gt;DoubleTree by Hilton Hotel Miami Airport &amp; Convention Center&lt;/b&gt;&lt;br /&gt;711 Northwest 72nd Avenue&lt;br /&gt;Miami, FL 33126

------------------------------
Event Details:
------------------------------

The Bitcoin Blockchain and Mining Conference

------------------------------
Hosted By:
------------------------------
MDC


------------------------------
Register Online:
------------------------------

More information and online registration are available here:
https://www.eventbrite.com/e/mining-disrupt-conference-2020-bitcoin-blockchain-cryptocurrency-mining-tickets-67883333879?ref=enivtefor001&invite=MTkwMzg5NjUvcmVwbHkrMDJlNDE2YTkxYTk4MWZkNjY3NTAzODVjYmIzMTlhNjFhZmZmZDc2Y2Ex%0AZDUzMjJjOTJjZjAwMDAwMDAxMThhMzY2MDI5MmExNjljZTE5MGQyOTZhQHJlcGx5LmdpdGh1Yi5j%0Ab20vMA%3D%3D%0A

----------------------------------------------------------------------

Collect event fees online with Eventbrite
http://www.eventbrite.com

**Comment by MiningDisrupt** [comment]
------------------------------
Event Summary:
------------------------------

Event: Mining Disrupt Conference 2020 | Bitcoin Blockchain Cryptocurrency Mining
Date: Wednesday, July 22, 2020 at 8:00 AM <span class="pipe">-</span> Thursday, July 23, 2020 at 11:00 PM (EDT)
Location: &lt;b&gt;DoubleTree by Hilton Hotel Miami Airport &amp; Convention Center&lt;/b&gt;&lt;br /&gt;711 Northwest 72nd Avenue&lt;br /&gt;Miami, FL 33126

------------------------------
Event Details:
------------------------------

The Bitcoin Blockchain and Mining Conference

------------------------------
Hosted By:
------------------------------
MDC


------------------------------
Register Online:
------------------------------

More information and online registration are available here:
https://www.eventbrite.com/e/mining-disrupt-conference-2020-bitcoin-blockchain-cryptocurrency-mining-tickets-67883333879?ref=enivtefor001&invite=MTkwMzg5NjUvcmVwbHkrMDJlNDE2YTllNTYyYjM2OTcyMTFkZGViNGI1N2Y4NDQyOGQ1YjhmMTJh%0AMzRiZGY0OTJjZjAwMDAwMDAxMThhMzhlMjQ5MmExNjljZTE5MGQyOTZhQHJlcGx5LmdpdGh1Yi5j%0Ab20vMA%3D%3D%0A

----------------------------------------------------------------------

Collect event fees online with Eventbrite
http://www.eventbrite.com
