### ISSUE TITLE
bitcoin-cli -conf=/chain/btc/main/bitcoin.conf  getaccount 366suDTHfmrpuf9XCCV6vCPg615KrsHRZY

### ISSUE THREAD

**Issue by younggundog** [bitcoin-dot-org/bitcoin.org#2897]
Location: https://bitcoin.org/zh_CN/developer-reference#block-headers

error code: -32601
error message:
Method not found

**Comment by wbnns** [comment]
@younggundog 

Hello, here's a link to forums where you can connect with others who may be able to help you with your issue: https://bitcoin.org/en/bitcoin-core/help#forums
