### ISSUE TITLE
Could not connect to the server 127.0.0.1:8332 (error code 1 - "EOF reach ed")

### ISSUE THREAD

**Issue by H-Moradof** [bitcoin-dot-org/bitcoin.org#2902]
Hi,
I want to run a local node.
I downloaded , installed and run bitcoin core software on my server.
according to the link below, I try to run command "`bitcoin-cli getblockchaininfo`" 
But I got this error:
**Could not connect to the server 127.0.0.1:8332 (error code 1 - "EOF reach
ed")**
link: https://bitcoin.org/en/full-node#windows-10

the operation of my server in **Windows Server 2012**

Whould you tell me what is wrong ?
thanks

**Comment by wbnns** [comment]
@H-Moradof 

Hello, here's a link to forums where you can connect with others who may be able to help you with your issue: https://bitcoin.org/en/bitcoin-core/help#forums
