### ISSUE TITLE
NYC BlockAsia 2

### ISSUE THREAD

**Issue by pprabhu007** [bitcoin-dot-org/bitcoin.org#2904]
- date: 2019-05-16
      title: "NYC BlockAsia 2"
      venue: "Metropolitan West, New York"
      address: "639 West 46th Street, New York, NY, 10036"
      city: "New York City"
      country: "USA"
      link: "https://www.eventbrite.com/e/nyc-blockasia-2-tickets-58978077016"

**Comment by khendraw** [comment]
- Is this event specifically related to Bitcoin? No, it is generally a blockchain conference in general.
- Is there a talk focused exclusively on Bitcoin? No, it is not mentioned.
- Are the majority of talks focused on ICOs and/or other digital currencies? No, it is not mentioned also.

In my opinion this event is not to be added to Bitcoin.org
