### ISSUE TITLE
CryptoCompare Digital Asset Summit

### ISSUE THREAD

**Issue by Carmiah** [bitcoin-dot-org/bitcoin.org#2906]
- date: 2019-06-12
      title: "CryptoCompare Digital Asset Summit"
      venue: "Old Billingsgate"
      address: "1 Old Billingsgate Walk, London EC3R 6DX"
      city: "London"
      country: "United Kingdom"
      link: "https://summit.cryptocompare.com/"

**Comment by khendraw** [comment]
Is this event specifically related to Bitcoin? No
Is there a talk focused exclusively on Bitcoin? No
Are the majority of talks focused on ICOs and/or other digital currencies? No

In my opinion this event is not to be added to bitcoin.org
