### ISSUE TITLE
Improve structure of documentation for RPC interface

### ISSUE THREAD

**Issue by GSPP** [bitcoin-dot-org/bitcoin.org#2910]
(I have moved this issue to here.)

When I Google for "bitcoin core rpc" I find a bunch of pages that are a bit confusing. What I am looking for is https://bitcoin.org/en/developer-reference#bitcoin-core-apis. But there are multiple others confusing matches and I suggest a few improvements for them:

1. The top result is https://bitcoincore.org/en/doc/. This has fairly little information and is, IMO, a distraction.
2. The second result is https://en.bitcoin.it/wiki/API_reference_(JSON-RPC). This is not about RPC commands at all. Rather, it is a (partial?) list of language clients. The page should be renamed. Also, it might help to place a link to the RPC calls documentation at the top of this page.
3. The third result is https://en.bitcoin.it/wiki/Original_Bitcoin_client/API_calls_list which is entirely obsolete I think. Can this be deleted?
4. The fourth result is https://bitcoin.org/en/developer-reference which is the page I want but the wrong anchor. Not sure what can be done about this.
5. The next result is https://en.bitcoinwiki.org/wiki/Bitcoind which seems reasonable but has a lot of obsolete stuff on it as well.

I might be wrong about these points but I wanted to express my confusion as a normal developer just trying to find the documentation of all available commands. I hope this helps.

**Comment by GSPP** [comment]
Maybe the page can link to https://masonicboom.github.io/btcrpcapi/ which seems very useful. I had not encountered this resource before. Linking to it would help discoverability.

It could be considered inappropriate to link to unofficial pages from the official RPC page. This could be solved by creating an official page plus a less formal unofficial page that simply links to helpful resource. The unofficial page could be created by re-doing the API_reference_(JSON-RPC) wiki page. So delete all API calls from API_reference_(JSON-RPC) and simply list a bunch of helpful resources.

**Comment by wbnns** [comment]
@GSPP 

Hello, apologies for the confusion, however, we don't have ultimate control over the order of the results that Google displays for specific keywords, nor bitcoincore.org, bitcoin.it and bitcoinwiki.org, which you mentioned had content that didn't seem related to your query.

**Comment by GSPP** [comment]
You could:

1. Reach out and notify the owners. Maybe a quick email is enough to set some change into motion.
2. Check the SEO for the documentation page. It is strange that all this garbage ranks before the "canonical" result. An easy attempt at a fix would be to link to `https://bitcoin.org/en/developer-reference` from the footer of the bitcoin.org homepage (or from the main menu). This is a very strong SEO signal that this page is important.
