### ISSUE TITLE
New event - Value of Bitcoin Conference

### ISSUE THREAD

**Issue by DanielSanW** [bitcoin-dot-org/bitcoin.org#2913]
- date: 2019-06-03
      title: "Value of Bitcoin Conference"
      venue: "Bavarian State Bank - BayernLB"
      address: "Brienner Straße 18"
      city: "80333 Munich"
      country: "Germany"
      link: "http://vob-conference.com"

**Comment by khendraw** [comment]
Is this event specifically related to Bitcoin? Yes
Is there a talk focused exclusively on Bitcoin? Yes
Are the majority of talks focused on ICOs and/or other digital currencies? No
In my opinion this event should be added to Bitcoin.org

**Comment by DanielSanW** [comment]
It's purely focused on the economics of Bitcoin.
ALL talks are exclusively focused on Bitcoin.
