### ISSUE TITLE
New event - Magical Crypto Conference

### ISSUE THREAD

**Issue by WhalePanda** [bitcoin-dot-org/bitcoin.org#2915]
- date: 2019-05-11
      title: "Magical Crypto Conference"
      venue: "Metropolitan Pavilion"
      address: "125 West 18th Street"
      city: "New York"
      country: "United States"
      link: "https://www.magicalcryptoconference.com/"

**Comment by khendraw** [comment]
- Is this event specifically related to Bitcoin? No
- Is there a talk focused exclusively on Bitcoin? Yes
- Are the majority of talks focused on ICOs and/or other digital currencies? Yes
In my opinion, this event should be added to Bitcoin.org
