### ISSUE TITLE
Please add ChainNode.com to the "Bitcoin community" page

### ISSUE THREAD

**Issue by In-Bitcoin-We-Trust** [bitcoin-dot-org/bitcoin.org#2917]
ChainNode.com (which was known as 8btc forum) is the largest blockchain forum in China.

Please add this link (https://www.chainnode.com/forum/2, which talks about bitcoin only) to https://bitcoin.org/zh_CN/community

Thank you.

**Comment by In-Bitcoin-We-Trust** [comment]
If possible, you may want to use these following descriptions as the anchor text:

English: ChainNode's Bitcoin Community
&
Chinese: ChainNode 链节点上的比特币社区

**Comment by wbnns** [comment]
@In-Bitcoin-We-Trust 

Thank you - #2940 is scheduled to be merged which will make the inclusion.

**Comment by In-Bitcoin-We-Trust** [comment]
great to know that! thank you.
