### ISSUE TITLE
Request to list all standard transactions after introductory paragraph

### ISSUE THREAD

**Issue by dergigi** [bitcoin-dot-org/bitcoin.org#2918]
Location: https://bitcoin.org/en/developer-guide#standard-transactions

I would expect the following sentence to be followed by a list of standard transactions:

> As of Bitcoin Core 0.9, the standard pubkey script types are:

Instead, what follows are subsections for each standard transaction type. This might be intended, but it was quite confusing for me.

I would expect to see a list of all transaction types at once, followed by a more detailed explanation for each in the sections below. As of now, the list does not exist.

Proposed change:

> As of Bitcoin Core 0.9, the standard pubkey script types are:
> * Pay To Public Key Hash (P2PKH)
> * Pay To Script Hash (P2SH)
> * Multisig
> * Pubkey
> * Null Data

I hope this makes sense. Since this is my first issue, please let me know if this is intended, a non-issue or if there are any guidelines I missed.

**Comment by wbnns** [comment]
Closing; resolved by #2919.
