### ISSUE TITLE
Blockchain Workshop Geared for Women #nycblockchainweek

### ISSUE THREAD

**Issue by schwentker** [bitcoin-dot-org/bitcoin.org#2921]
- date: 2019-05-16 to 2019-05-17 
      title: "Blockchain Workshop Geared for Women"
      venue: "Shearman & Sterling"
      address: "599 Lexington Avenue"
      city: "New York City"
      country: "US"
      link: "https://blockchain-workshop-geared-for-women.eventbrite.com"

**Comment by khendraw** [comment]
1. Is this event specifically related to Bitcoin? No
2. Is there a talk focused exclusively on Bitcoin? No
3. Are the majority of talks focused on ICOs and/or other digital currencies? No

I don't think this event should be added to Bitcoin.org
