### ISSUE TITLE
SPOT Conference 2019

### ISSUE THREAD

**Issue by Liongrass** [bitcoin-dot-org/bitcoin.org#2926]
- date: 2019-07-29
      title: "SPOT Conference"
      venue: "Hong Kong Stock Exchange"
      address: "1/F, Exchange Square"
      city: "Central"
      country: "Hong Kong"
      link: "https://www.spotconf.com/"

**Comment by khendraw** [comment]
This event is not having a clear information about the talks yet but it is an initiative from by the Bitcoin Association of Hong Kong.

**Comment by Liongrass** [comment]
Indeed the first round of speakers hasn't been publicized. You can view [speakers](https://www.spotconf.com/2018/#speakers) and [agenda](https://www.spotconf.com/2018/agenda) from 2018 on the site.

**Comment by wbnns** [comment]
@Liongrass Thank you. Please let us know when the speakers and agenda are available for this year's conference and we'll review the event.

**Comment by Liongrass** [comment]
Hi!
You can now find a list of [speakers here](https://www.spotconf.com/#speakers), as well as an [agenda here](https://www.spotconf.com/2019/agenda). Looking forward to seeing this re-opened!
Leo

**Comment by khendraw** [comment]
Hello, thank you for updating the event information. After reviewing, I believe this event is focused on cryptocurrencies in general and not primarily focused on bitcoin.
