### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by monada89** [bitcoin-dot-org/bitcoin.org#2927]
- date: 2019-06-14
      title: "UNCHAIN Bitcoin & Blockchain Convention"
      venue: "Säälchen"
      address: "Holzmarktstrasse 25"
      city: "Berlin"
      country: "Germany"
      link: "https://www.unchain-convention.com/"

**Comment by khendraw** [comment]
- Is this event specifically related to Bitcoin? Yes
- Is there a talk focused exclusively on Bitcoin? Yes
- Are the majority of talks focused on ICOs and/or other digital currencies? No
In my opinion this event can be added to Bitcoin.org
