### ISSUE TITLE
Layer-2 Meetup: Blockchain Week NY edition

### ISSUE THREAD

**Issue by Geoprotocol** [bitcoin-dot-org/bitcoin.org#2929]
- date: 2019-05-15
      title: "Layer-2 Meetup: Blockchain Week NY edition"
      venue: "15 мая 2019 года в Нью-Йорке во время одного из самых крупных и ожидаемых ежегодных событий в блокчейн-сообществе – Consensus 2019 состоится Layer-2 Meetup.

Технологические лидеры Layer-2-решений соберутся, чтобы обсудить общие проблемы и выгоды при разработке решений второго уровня. Обсуждать будем все, от масштабируемости до совместимости и многое другое!

Если говорить более конкретно, то вот список тем, которые будут обсуждаться во время встречи:

Мультиэквивалентный Layer 2: плюсы и минусы
Стейт-ченнелы
Как построить эффективную Layer-2 сеть 
Проблемы реализации эффективной и быстрой маршрутизации в пиринговых сетях
Вызовы, связанные с принятием Layer-2
"
      address: "Centre for Social Innovation, 601 West 26th Street, Suite 325"
      city: "New York"
      country: "USA"
      link: "http://tiny.cc/spt34y"

**Comment by khendraw** [comment]
Using Google Translate :

Technology leaders of Layer-2 solutions will gather to discuss common problems and benefits when developing second-level solutions. We will discuss everything from scalability to compatibility and much more! More specifically, here’s a list of topics to be discussed during the meeting: Multi-equivalent Layer 2: Pros and Cons of State Channels How to Build an Efficient Layer-2 Network Problems of Implementing Efficient and Fast Routing in Peer-to-Peer Networks 2 "

Not sure if this event should be added Bitcoin.org

**Comment by wbnns** [comment]
@khendraw Thanks. The link just goes directly to a Google Form - there's no website with more information. This would be confusing to people who click the link on bitcoin.org looking for more info. We can close the issue.

@Geoprotocol If there's a website with more information about the event that we can review, please let us know.
