### ISSUE TITLE
2nd Annual ADI Crypto Mining Conference  

### ISSUE THREAD

**Issue by EmmaTodd** [bitcoin-dot-org/bitcoin.org#2943]
- date: 2019-05-13
      title: "2nd Annual ADI Crypto Mining Conference"
      venue: "Citco Gateway New York"
      address: "350 Park Avenue, 13th Floor"
      city: "New York, NY, "
      country: "USA"
      link: [http://adisummit.com/newyorkmining2019/
![ADI Summit](https://user-images.githubusercontent.com/50117928/56919243-1f078e80-6a8e-11e9-91cd-339b3105b7b4.png)
]("http://adisummit.com/newyorkmining2019/")

**Comment by khendraw** [comment]
- Is this event specifically related to Bitcoin? No
- Is there a talk focused exclusively on Bitcoin? No
- Are the majority of talks focused on ICOs and/or other digital currencies? The event is about Cryptocurrency mining.

In my opinion, this event is not to be added to Bitcoin.org.
