### ISSUE TITLE
About bitcoin atm

### ISSUE THREAD

**Issue by Nightreaper84** [bitcoin-dot-org/bitcoin.org#2944]
I just want to let you know you should put bitcoin atm's in Sedalia Missouri or cole camp Missouri too

**Comment by wbnns** [comment]
@Nightreaper84 

Hello, thank you for the suggestion, however, bitcoin.org doesn't own or install ATMs.

**Comment by Nightreaper84** [comment]
who does so i can ask them to or can you tell them for me

**Comment by wbnns** [comment]
@Nightreaper84 

Hello, there are multiple companies. Maybe consider checking out [Coin ATM Radar](https://coinatmradar.com/) to find an ATM near you. A merchant at the location could possibly refer you to whoever placed it there.
