### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by monada89** [bitcoin-dot-org/bitcoin.org#2962]
- date: 2019-06-01
      title: "#LightningHackdayMUC"
      city: "Munich"
      country: "Germany"
      link: "https://lightninghackday.fulmo.org/"

**Comment by khendraw** [comment]
Is this event specifically related to Bitcoin? No, but it is about lightning network which are specifically on Bitcoin.
Is there a talk focused exclusively on Bitcoin? No
Are the majority of talks focused on ICOs and/or other digital currencies? No
In my opininon this event should be added to bitcoin.org
