### ISSUE TITLE
New event: Bitcoin Pizza Day in Arnhem Bitcoin City

### ISSUE THREAD

**Issue by annetdeboer** [bitcoin-dot-org/bitcoin.org#2963]
- date: 2019-05-22
      title: "Bitcoin Pizza Day"
      venue: "De Pizzabakkers"
      address: "Broerenstraat 35"
      city: "Arnhem Bitcoin City"
      country: "The Netherlands"
      link: "https://www.arnhembitcoinstad.nl"

**Comment by khendraw** [comment]
Is this event specifically related to Bitcoin? Yes
Is there a talk focused exclusively on Bitcoin? No talks just event.
Are the majority of talks focused on ICOs and/or other digital currencies? No
In my opinion this event should be added to Bitcoin.org
