### ISSUE TITLE
New event: Breaking Arnhem

### ISSUE THREAD

**Issue by annetdeboer** [bitcoin-dot-org/bitcoin.org#2964]
- date: 2019-06-06
      title: "Breaking Arnhem"
      venue: "Barley's Oriental Garden"
      address: "Pauwstraat 4"
      city: "Arnhem Bitcoin City"
      country: "The Netherlands"
      link: "https://www.arnhembitcoinstad.nl"

**Comment by khendraw** [comment]
Is this event specifically related to Bitcoin? Yes
Is there a talk focused exclusively on Bitcoin? No, just Bitcoin enthusiasts meetup event
Are the majority of talks focused on ICOs and/or other digital currencies? No
I believe this event is to be added to Bitcoin.org
