### ISSUE TITLE
Add Quebex.com Canadian Bitcoin Exchange 

### ISSUE THREAD

**Issue by davidquebex** [bitcoin-dot-org/bitcoin.org#2966]
Hi Will,

Thanks for reviewing Quebex.com.

Please see below answer to your questions;

Hi Will,

I’ve added code to suppress the popup for 7 days once closed, stored in the session cookie.

I’ve also fixed the styling issue for the select element dropdown arrow that appears in responsive view in Firefox. On mobile devices, there would have been an issue where the right most 10% of the black section would not have been clickable which I have now resolved.

I’ve installed Firefox on my iPhone and tested the quick links select element, and it now works fine. I’ve also tested it on a Samsung tablet which worked as expected; unfortunately I don’t have an android phone handy at the moment to test with.

When I tested on Firefox 60 running on windows 10 I noticed that there were a few quirks I can’t reproduce on mobile devices.

Can I ask what device you’re testing on? Your user agent suggests it’s a windows 7 device; are you using a PC or mobile device?

I have been unable to reproduce the issue you had with the province select element on any device; I wonder if it would perhaps be a Firefox responsive mode issue? It’s a regular select element with nothing special happening.

The href for the initiate chat link has been replaced with “javascript:void(0)” which works well with Firefox, so you should now be able to click it to trigger popping up the chat window. As for receiving the prompt after completing the KYC, that is expected behaviour when a user fails the Equifax KYC or when any of our fraud mitigation strategies flag an account for manual review. 

We have thousands of users who have successfully passed the Equifax KYC and thousands more who were approved without doing one who would not have been prompted to initiate a chat with staff. As we cater to the Canadian market, we admit that it is exceptionally hard for non-Canadians to successfully sign up with Quebex.

Please continue your review, and let me know if you spot any other ways we can improve our user experience.

Thanks,

- Aaron

**Comment by wbnns** [comment]
@davidquebex 

Hello, thank you. We saw the update to #2960 and will respond there.

**Comment by davidquebex** [comment]
Ok thanks Will! Is it normal that it says the issue is closed?
