### ISSUE TITLE
Quebex.com P2P exchange eliminates e-transfer fraud

### ISSUE THREAD

**Issue by davidquebex** [bitcoin-dot-org/bitcoin.org#2967]
Dear Bitcoin community,

Quebex.com is working really hard to create a safe P2P environment for both sellers and buyers.

Many P2P exchange like localbitcoins have huge issues with e-transfer fraud resulting in sellers loosing bitcoins and their bank account.

Just google “localbitcoin e-transfer fraud”

Quebex.com has made it very hard for fraudsters to signup and get their accounts approved.

Since 2016, we have had over $1,194,000 CAD in P2P trades on Quebex without one single instance of Fraud.

So now traders can focus on selling bitcoins instead of wasting time and worrying about asking buyers to provide selfies and photo IDs. This is most of the time useless as these fraudsters hide behind burner phones and proxy’s and provide falsified ID.

The proof that we have a good system in place is that Will Binns has tried to signup many times with burner phones and proxy services but can’t get access to the site features.

This is because it’s typical behaviour of fraudsters.

If he tries to signup and provide real info the system will automatically approve him and he can start trading in less than 5 minutes, without even uploading any IDs.

I hope the bitcoin community will find a P2P exchange that cares about its sellers useful and hopefully bitcoin.org will also agree.

Will Binns, please try to create a real account and not hide as you will never have access to site feature and will always encounter issues.

Best,

David

**Comment by wbnns** [comment]
@davidquebex Hello, sorry, but we disagree.

In case any other contributors would like to review your exchange and potentially recommend it for listing, here are links to other related issues:

+ #2421 
+ #2559
+ #2960

In addition to the above, we noted we weren't the only ones who have [experienced issues](https://www.reddit.com/r/BitcoinCA/comments/7k2w8x/has_anyone_here_used_quebex_to_buy_or_sell_crypto/) trying to use the platform.

**Comment by davidquebex** [comment]
Hi Will,

Thank you for your quick reply!

I respect that you disagree, but you must understand that as long as you try to hide when signing up you will experience issues.

Please understand that protecting the traders on Quebex.com is our number one priority.

Quebex has over $1M traded since 2016, without e-transfer fraud and think that the bitcoin community would really appreciate a service that can provide a safe P2P trading environment.

As per reddit post, these are very old posts. Since all issues have been resolved. We don’t use webcam verification anymore, there’s no ID required to get verified and support has been greatly improved.

Nevertheless, as a courtesy, we would like to offer reddit user swearb0x, traderp2, yannic69 $25 in BTC. It’s just our way of saying we are sorry and will do better.

Will, please try to signup with real information, without using burner phone and proxy so you can properly test the platform.

Best,

David

**Comment by davidquebex** [comment]
In case any other contributors would like to review localbitcoins and potentially remove it from bitcoin.org listing, (or at minimum add a scam alert next to listing to keep bitcoin community safe) here are links to other related issues:

https://www.reddit.com/r/Bitcoin/comments/7ohp1a/beware_localbitcoinscom_scammers/

https://www.reddit.com/r/Bitcoin/comments/9enq17/localbitcoinscom_scam_alert/

https://www.reddit.com/r/localbitcoins/comments/8tksnw/fraud_account_on_localbitcoins/

https://www.reddit.com/r/localbitcoins/comments/8jbjjs/frauds/

https://www.reddit.com/r/localbitcoins/comments/7wkxox/bitcoin_fraud_need_urgent_help/

https://www.reddit.com/r/Bitcoin/comments/9jgaps/beware_of_localbitcoins_antifraud_policy_your/

https://www.reddit.com/r/localbitcoins/comments/8g45oc/sellers_beware_scam_alert/

https://www.reddit.com/r/localbitcoins/comments/6lt2rv/cash_deposit_scam_warning/

https://www.reddit.com/r/localbitcoins/comments/74qwo7/just_got_scammed_out_of_2400_on_localbitcoins/

More can be found here:

localbitcoin fraud site:www.reddit.com

**Comment by davidquebex** [comment]
Quebex.com is like localbitcoins but without the scammers. We really work hard to weed out anybody trying to create fake accounts by hiding behind burner phones and proxies and providing fake or falsified IDs. So far we’ve had amazing success, with over 1.2M trade and no fraud!

**Comment by davidquebex** [comment]
Will, let’s work together to keep the bitcoin community safe!

**Comment by achow101** [comment]
Bitcoin.org's issues are not the place to advertise your service.

**Comment by davidquebex** [comment]
Hi Andrew,

Thank you for your comment.

As mentioned in the issue you are referring, we respect that you disagree, but you must understand that as long as the reviewer hiding when when signing up you will experience issues.
Please understand that protecting the traders on Quebex.com is our number one priority.

Best regards
