### ISSUE TITLE
Remove bitbuy for signup issues?

### ISSUE THREAD

**Issue by aaronkuchma** [bitcoin-dot-org/bitcoin.org#2976]
As per the bitbuy.ca website, Trading is "[restricted] to Canadian clients only with Canadian IPs," (source: https://bitbuy.ca/en/compliance ).

This makes it difficult for me to review it with a non-Canadian IP as the site will not allow non-Canadians to transact.

As such, I don't think it is a good fit for bitcoin.org.

**Comment by achow101** [comment]
NACK. It's in the Canadian section for a reason..
