### ISSUE TITLE
Bitcoin Pizza Day BH

### ISSUE THREAD

**Issue by mateusnds** [bitcoin-dot-org/bitcoin.org#2981]
date: 2019-05-22
      title: "Bitcoin Pizza Day Belo Horizonte"
      venue: "La Pizzeria"
      address: "Rua Felipe dos Santos - Lourdes, MG 30180-160"
      city: "Belo Horizonte - MG"
      country: "Brazil"
      link: "https://livecoins.com.br/eventos-cripto/bitcoin-pizza-day/"

**Comment by khendraw** [comment]
Is this event specifically related to Bitcoin? Yes
Is there a talk focused exclusively on Bitcoin? No
Are the majority of talks focused on ICOs and/or other digital currencies? No
In my opinion this event can be added to Bitcoin.org

**Comment by wbnns** [comment]
@mateusnds 

Hello, apologies we weren't able to get this added in time. In the future, if you could give us a bit more notice (more than one week; ideally at least one month), we'll do our best to have your event reviewed and potentially added beforehand.

**Comment by mateusnds** [comment]
Hello, @wbnns 

Thank you for the message. No problem, I Really took too long to include the event. So, My bad.

Take a look:  https://www.facebook.com/rafaelfelicio/posts/2467637956582613

**Comment by wbnns** [comment]
@mateusnds Looks like you all had a good time. 👍
