### ISSUE TITLE
Bitcoin core page says "no voting." What about soft forks?

### ISSUE THREAD

**Issue by SohaibJKhan** [bitcoin-dot-org/bitcoin.org#2994]
" There's no voting or other corruptible process involved: there's just individual software following identical rules—"math"—to evaluate identical blocks and coming to identical conclusions about which block chain is valid. " - https://bitcoin.org/en/bitcoin-core/

I feel like this is misleading. Maybe I misunderstand forks haha,

**Comment by wbnns** [comment]
Hello, here's a link to places where you can connect with others to discuss this in more detail: https://bitcoin.org/en/bitcoin-core/help#forums

**Comment by SohaibJKhan** [comment]
@wbnns Sorry if the issue was out of line, just felt it wasn't 100% right based off of the whole segwit change. I felt that it would be relevant to the site.  

"There's no voting or other corruptible process involved" - it definitely seems like this isn't true .

**Comment by wbnns** [comment]
@SohaibJKhan It's ok, no need to apologize. :)
