### ISSUE TITLE
Show only peer to peer or crypto to crypto exchanges on bitcoin.org

### ISSUE THREAD

**Issue by maxwellmons** [bitcoin-dot-org/bitcoin.org#3001]
The fiat to crypto methods for entering and exiting bitcoin are under threat of mirroring the central banking system that the technology seeks to escape. In the fiat central banking system, there are central banks, large international banks, smaller regional banks, and local banks. Large international banks follow the rules of the central banks. The regional banks follow the rules of the international banks, as do the local banks. 

Local and regional banks rely on the larger banks to process their international transactions. International fiat wire transfers sent from a small or regional bank will pass through a large international bank. The international bank will process, reject, or hold the transfer depending on how it conforms to their internal policies or procedures in cooperation with governments and central banks. There are blacklists of countries, organizations, and people that money can't be sent to. Control is absolute. If anyone doesn't follow the rules, they are kicked out of the system and their account is closed. If they continue to disobey the rules they will go to jail. Countries who don't follow the rules will find worse outcomes.

This chain of command and control is propogating at this moment through bitcoin exchanges. There are a small number of international bitcoin exchanges that have stable banking relationships. They work closely with international banks, central banks, and governments and only allow certain types of clients who fit in the mold of their reporting and control capabilities. This is why it is very easy to buy and sell bitcoin if you are in the United States and simultaneously very difficult if you are in the Democratic Republic of the Congo.

A heavily regulated international exchange that is based in the United States or in the United Kingdom will submit to the requirements of the international bank that they are partnered with. A regional exchange will follow the rules of the regional bank that they are partnered with, which in turn follows the orders of the international bank. Exchanges that do not follow these rules or that are not closely connected to the fiat banking system will not have stable banking relationships. This is why exchanges have problems processing withdraws and deposits. Their corporate fiat banking relationships are under threat of termination or have already been terminated. When they have been terminated, they must set up a new banking relationship which can be very difficult. If they cannot, it is the end of the exchange.

Regional and local exchanges are at the mercy of the larger international exchanges. International exchanges have the most liquidity and the smaller exchanges utilize their OTC departments as well as their online exchange capabilities to help clear their transactions. If the international exchanges mandate a set of rules, the smaller exchanges must comply. Those who don't will find themselves without stable banking relationships and without an exchange partner who will process their operations from crypto back into fiat via international transfer.

In the future, if a small group of international exchanges decide in concert that they will split BTC to support other forks of Bitcoin, most of the other exchanges beneath them will ultimately comply. Many people do not realize that this is even more centralized than mining concerns and that it could happen at any time.

Bitcoin is peer to peer technology. This is crippled if the doors to the system are centralized exchanges forcing the massive numbers of people entering the system to succumb to the rules of fiat banking that Bitcoin sought to disrupt and supplant.

Only peer to peer and crypto to crypto exchanges should be shown on bitcoin.org to prevent this.

**Comment by wbnns** [comment]
Closing; discussion to be continued in #3033.
