### ISSUE TITLE
como recuperar contraseña en Bitcoin Core

### ISSUE THREAD

**Issue by yudisnel** [bitcoin-dot-org/bitcoin.org#3005]
Hola como se puede recuperar la contraseña o clave en Bitcoin Core yo hice un deposito BTC y me pide contraseña para retirar el monto abonado a la billetera y no he podido recuperarlo pues no recuerdo que contraseña fue

**Comment by wbnns** [comment]
Perdón, pero si no tiene la contraseña, será muy difícil o imposible recuperar los fondos. Le recomendamos que vuelva sobre sus esfuerzos de crear la billetera para, con suerte, determinar la contraseña.
