### ISSUE TITLE
Ownbit list on bitcoin.org

### ISSUE THREAD

**Issue by jtomtan** [bitcoin-dot-org/bitcoin.org#3027]
Hi guys,

We want to apply for listing on bitcoin.org as one of the recommend Bitcoin Wallets. Ownbit has a long history back to 2013 which contributes a lot for Bitcoin growing up, especially in China.

And now Ownbit is one the most featured Bitcoin Wallets, which supports SegWit, MultiSig, Customize UTXO, Offline Cold Wallet and etc. It has a very good reputation as the BEST Bitcoin Wallet in the community(If you try it , you will see).

And also Ownbit has been trusted by many other popular projects, and has been listed as their recommended 3rd wallets, like Litecoin, DASH and so on. And also Stellar will list Ownbit in their new website soon. All these can be checked and they are true.

So, Ownbit as one of the modern Bitcoin Wallets apply for listing, and it deserves to be accessed by more Bitcoin users. Wish to get feedback from you soon.

Ownbit website: https://ownbit.io
Apps can be downloaded at Appsotre/Google Play searching: Ownbit.

**Comment by crwatkins** [comment]
@jtomtan Thanks for letting us know about Ownbit.  

Please take a look at the wallet listing criteria [here](https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/docs/managing-wallets.md) and confirm that Ownbit meets these criteria. In particular, review the open source requirement.

The next step is to submit a PR here as described in the above referenced document.  If you have any questions at all, be sure to ask here.

**Comment by jtomtan** [comment]
> here

Thanks for the reply. I will check for the listing and feedback later.

I strongly recommend you download and have a try on Ownbit, and we believe it's outstanding in features among all Bitcoin Wallets.

For open source requirement, we are not opening yet for preventing copy & paste from competitors. But we can add one of you into our github to review our codes and we can keep this account there permanently to make sure all our versions conforms to some basic security rules.

Thanks very much. We hope this proposal can work.

**Comment by crwatkins** [comment]
Regretfully, we have not been listing closed source wallets.   The [community is fairly adamant ](https://github.com/bitcoin-dot-org/bitcoin.org/issues/1622)that this should remain a requirement.

**Comment by jtomtan** [comment]
> Regretfully, we have not been listing closed source wallets. The [community is fairly adamant ](https://github.com/bitcoin-dot-org/bitcoin.org/issues/1622)that this should remain a requirement.

Understood. We'd like to make Ownbit fully open resource to be listed on bitcoin.org. 

And I checked the criteria you mentioned above. I believe we meet them all. And for some items we do in settings. Users can the decide the behavior. For example, whether generating new address every time a new transaction for the last address is received. Some users may hate see too many addresses.

So, to continue, just submit a new PR describing in the document, right?

**Comment by crwatkins** [comment]
> Understood. We'd like to make Ownbit fully open resource to be listed on bitcoin.org.

Note that listing can only occur after the code has been open for at least three months.

> And I checked the criteria you mentioned above. I believe we meet them all. 

Great.  If you do have any concerns or need any clarifications, be sure to ask as failures can delay listings.

> And for some items we do in settings. Users can the decide the behavior. For example, whether generating new address every time a new transaction for the last address is received. Some users may hate see too many addresses.

Please note that address reuse [abuses the privacy and security](https://en.bitcoin.it/wiki/Address_reuse) of not only your users, but of those they transact with and of the entire community.  The only possible way I would recommend a wallet for listing that has such a setting is if that setting by default was not to reuse addresses (which I do not believe is your default) and if there were serious warnings on the setting explaining the implications of enabling it.  It would be best not to have such a dangerous setting.

> So, to continue, just submit a new PR describing in the document, right?

Correct.  I would suggest fixing your address reuse issue and providing open source code in maintained source code control first.  I'll close this issue in anticipation of the listing PR, but feel free to re-open this or ask more questions here if you have any.

**Comment by jtomtan** [comment]
It's very easy for us to turn on the "use new address" by default. But if you listen to the users, most of them actually don't want too many addresses, specially for new users of Bitcoin. It's not about they didn't notice the privacy, but it's just they want simplicity. Different people may have different opinion about this. Anyway, if this is a mandatory requirement, we could change that. 

And one more question, have you ever tried Ownbit? We believe the listing on bitcoin.org should include more new & powerful Bitcoin Wallets. Some outstanding features of Ownbit for Bitcoin includes:
1. Full segwit support
2. Flexible address policy (we think user should control more)
3. MultiSig support (up to 9 people)
4. Export/Import private keys, Export Xpub, Watch Wallet
5. Offline usage, offline creation, import, offline signing, invented Cold Wallet feature by software only
6. Customize UTXO (user can select which UTXOs to use)
7. More smarter fees (Invented a fee algorithm according to recent blocks and current mempool)
8. RBF alert (alert if the bitcoin TX is a replace-by-fee)

So, could you please have a pre-check on Ownbit, for listing on bitcoin.org, the thing now we do is to make our github repositories public, and change our address policy default to "use new address". Anything more? 

Or what's your comments about Ownbit listing on bitcoin.org?

**Comment by jtomtan** [comment]
> > Understood. We'd like to make Ownbit fully open resource to be listed on bitcoin.org.
> 
> Note that listing can only occur after the code has been open for at least three months.
> 
> > And I checked the criteria you mentioned above. I believe we meet them all.
> 
> Great. If you do have any concerns or need any clarifications, be sure to ask as failures can delay listings.
> 
> > And for some items we do in settings. Users can the decide the behavior. For example, whether generating new address every time a new transaction for the last address is received. Some users may hate see too many addresses.
> 
> Please note that address reuse [abuses the privacy and security](https://en.bitcoin.it/wiki/Address_reuse) of not only your users, but of those they transact with and of the entire community. The only possible way I would recommend a wallet for listing that has such a setting is if that setting by default was not to reuse addresses (which I do not believe is your default) and if there were serious warnings on the setting explaining the implications of enabling it. It would be best not to have such a dangerous setting.
> 
> > So, to continue, just submit a new PR describing in the document, right?
> 
> Correct. I would suggest fixing your address reuse issue and providing open source code in maintained source code control first. I'll close this issue in anticipation of the listing PR, but feel free to re-open this or ask more questions here if you have any.

Seems I have no privilege to re-open the case, please check my comments above.

**Comment by crwatkins** [comment]
@jtomtan The wallet review process takes weeks for a new wallet, so it is hard to provide any comments in advance, other than to carefully review the requirements and ask questions about any that might be confusing.  It might also be helpful to look at closed PRs with completed reviews.
