### ISSUE TITLE
2019 Block Plus Summit SERIES III - Future of FinTech

### ISSUE THREAD

**Issue by mz2725** [bitcoin-dot-org/bitcoin.org#3029]
- date: 2019-09-09
      title: "2019 Block Plus Summit SERIES III - Future of FinTech"
      venue: "Gem Center"
      address: "8 Nguyễn Bỉnh Khiêm
                     Hồ Chí Minh 800010
                     Viet Nam"
      city: "Hồ Chí Minh"
      country: "Viet Nam"
      link: "https://www.eventbrite.com/e/2019-block-plus-summit-series-iii-future-of-fintech-tickets-63530214582"
     **Detail**: The combination of finance and technology stimulates a surgeof many application such as peer-to-peer network, mobile payment system, decentralized economy, and Robo-advising. So far, technology is still evolving and changing our cognition of traditional finance.
Hosted by BitMart l abs, the 2019 Block Plus Summit Ill gathers the elites in the industry of Fintech from regulators, international leading companies, financial institutions, blockchain companies, advisory firms, and law firms to discuss the current development of Fintech and share the valuable insights toward the interesting topics such like the decentralized applications, decentrialized finance, global regulations about Fintech."
![image](https://user-images.githubusercontent.com/52208966/60106890-f3beba00-9733-11e9-903e-38ed95a0c4d5.png)
![image](https://user-images.githubusercontent.com/52208966/60106904-f91c0480-9733-11e9-959c-9a7c95eb3b51.png)
![image](https://user-images.githubusercontent.com/52208966/60106930-ff11e580-9733-11e9-9d27-ac67951e6aa4.png)
![image](https://user-images.githubusercontent.com/52208966/60106934-033e0300-9734-11e9-9493-065f886fd9a2.png)
![image](https://user-images.githubusercontent.com/52208966/60106949-06d18a00-9734-11e9-8d11-10476fc613df.png)
![image](https://user-images.githubusercontent.com/52208966/60106959-0a651100-9734-11e9-94ca-df005ca6dc22.png)
![image](https://user-images.githubusercontent.com/52208966/60106970-0f29c500-9734-11e9-9191-b31a1d09844c.png)
![image](https://user-images.githubusercontent.com/52208966/60106973-1224b580-9734-11e9-84c7-5e6b41953916.png)
![image](https://user-images.githubusercontent.com/52208966/60106984-1650d300-9734-11e9-81ec-a228beb2b47f.png)

**Comment by mz2725** [comment]
Above is the event which will be hosted by BitMart Lab, and we would like to post it on your website. Please Approve

**Comment by khendraw** [comment]
Is this event specifically related to Bitcoin? No.
Is there a talk focused exclusively on Bitcoin? No.
Are the majority of talks focused on ICOs and/or other digital currencies? No, it is mainly on the blockchain technology in general.

In my opinion this event is not to be added to Bitcoin.org
