### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by Aysuneks** [bitcoin-dot-org/bitcoin.org#3030]
Date: February 20-21, 2020
Organization: Blockchain Economy
City: Istanbul, Turkey
Venue: WOW İstanbul Hotel
Web: https://www.blockchaineconomy.istanbul/EN/

**Comment by khendraw** [comment]
Is this event specifically related to Bitcoin? No
Is there a talk focused exclusively on Bitcoin? No
Are the majority of talks focused on ICOs and/or other digital currencies? No
In your opinion, should this event be added to Bitcoin.org? No
