### ISSUE TITLE
BTC transmission not Confirming

### ISSUE THREAD

**Issue by Micah68** [bitcoin-dot-org/bitcoin.org#3038]
https://www.blockchain.com/btc/tx/6647f579d29e1c32cabf8e4f191e084906626404c85af498fcf82c1788702136

This balance of BTC was sent from a wallet to an exchange over 12 hours ago and it has seen no confirmations as of yet. See above BTC explorer for details.

Thank you,
Micah68

**Comment by wbnns** [comment]
@Micah68 This is confirmed, now.
