### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by rileysilbert** [bitcoin-dot-org/bitcoin.org#3040]
- date: 2019-09-26
      title: "CoinAlts Fund Symposium"
      venue: "The Art Institute of Chicago"
      address: "111 S. Michigan Ave"
      city: "Chicago"
      country: "United States"
      link: "https://blockworksgroup.io/coinalts2019"
      graphic: "https://imgur.com/a/WVEod32?"

**Comment by khendraw** [comment]
Is this event specifically related to Bitcoin? No
Is there a talk focused exclusively on Bitcoin? No
Are the majority of talks focused on ICOs and/or other digital currencies? Yes
I think this event is not to be added to Bitcoin.org
