### ISSUE TITLE
Bither wallet is listed as reusing addresses, but apparently uses an HD wallet by default

### ISSUE THREAD

**Issue by shesek** [bitcoin-dot-org/bitcoin.org#3043]
This is the wallet creation screen, with HD selected by default:

![](https://i.imgur.com/x8tiXCj.jpg)

I'm not affiliated with Bither. I bumped into this while researching the state of address reuse in bitcoin wallets. Bither appears to be the only wallet listed with `privacyaddressreuse` set to `checkfailprivacyaddressrotation`.

**Comment by crwatkins** [comment]
@shesek Thanks for noticing this!  When Bither was [originally reviewed](https://github.com/bitcoin-dot-org/bitcoin.org/pull/724#issuecomment-98295136) HD mode was not the default, and thus default wallets reused addresses.    Would you like to submit a PR to change this?  Or would you like me to?

**Comment by shesek** [comment]
I'll do it, one moment...

**Comment by shesek** [comment]
Closing in favor of #3044.
