### ISSUE TITLE
Blockchain Life 2019 Europe

### ISSUE THREAD

**Issue by blockchainlife2019** [bitcoin-dot-org/bitcoin.org#3055]
- date: 2019-10-16 2019-10-16
      title: "Blockchain Life 2019"
      venue: "Expocentre"
      address: ""
      city: "Moscow"
      country: "Russia"
      link: "https://blockchain-life.com/europe/"

**Comment by blockchainlife2019** [comment]
The forum Blockchain Life 2019 - is one of the biggest international events in Russia and Eastern Europe in the fields of blockchain, cryptocurrencies and mining. Annually, 5000 people from 70+ countries attend Blockchain Life forums. This year we are expecting more than 6000 participants at our European Blockchain Life 2019. 

Among the participants are the leading industry companies, international cryptotraders, world funds and private investors, government representatives, the best startups, blockchain developers and everyone who is interested in the most prospective field.

Blockchain Life 2019 is a hub for blockchain and crypto development in Russia and all over the world. The forum connects the international crypto-community and government representatives and best industry projects with the funds.

**Comment by khendraw** [comment]
Is this event specifically related to Bitcoin? No
Is there a talk focused exclusively on Bitcoin? No
Are the majority of talks focused on ICOs and/or other digital currencies? No, it is on blockchain techology, cryptocurrencies and mining in general.
In my opinion this event is not to be added to Bitcoin.org
