### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by Karhrman** [bitcoin-dot-org/bitcoin.org#3059]
- date: 2019-09-09
      title: "Cryptocurrency Investigator [ Foundation Course ]"
      venue: "Tomoko Discovery"
      address: "501 1st Ave N."
      city: "St. Petersburg"
      country: "USA"
      link: "https://www.tomokodiscovery.com/events/cryptocurrency-investigator"

**Comment by khendraw** [comment]
Is this event specifically related to Bitcoin? No
Is there a talk focused exclusively on Bitcoin? No
Are the majority of talks focused on ICOs and/or other digital currencies? No, it is on Cryptocurrency Investigator
In your opinion, should this event be added to Bitcoin.org? No
