### ISSUE TITLE
Update Trezor branding

### ISSUE THREAD

**Issue by crwatkins** [bitcoin-dot-org/bitcoin.org#3060]
@prusnak In your wallet listing, the branding for Trezor may be out of date.  Should it be "Trezor One"?  If so, would you like to submit a PR to update that or would you like us to make that change?

**Comment by prusnak** [comment]
Do we want to have a separate listing for all (existing and upcoming) Trezor models?

**Comment by crwatkins** [comment]
That's an excellent question.  What do you think?  I would lean toward "yes" for a few reasons (none of which is because "it would be easier")

1. We have precedence.   I've [made the case](https://github.com/bitcoin-dot-org/bitcoin.org/pull/1337#issuecomment-241895424) for two Ledger Nanos being listed in the past (one of which is no longer listed).
2.  There is a possibility that one model might meet listing criteria while another model doesn't. We've had a submission where one model was open source and a second model was not open source (neither currently listed).
3.  In the near future, we hope to have a [wallet selection wizard ](https://github.com/bitcoin-dot-org/bitcoin.org/pull/3017) with feature filters such that different models may have different feature sets listed.

**Comment by crwatkins** [comment]
As we consider this, we also have a submission to [add Corazon wallet](https://github.com/bitcoin-dot-org/bitcoin.org/pull/3042) from @DarrenSG which I understand (please correct me if I'm wrong) is a very nice case for a Trezor Model T.  If we don't have separate listings for different Trezor models, would we have different listings for different cases (since they look different)?

Input and discussion is welcome!

**Comment by prusnak** [comment]
I agree it makes sense to add a listing for Trezor Model T because the user experience is substantially different. For the same reason, I think it does not make sense to list Corazon separately as the user experience is the same. However, we might mention Corazon in the Model T listing. How does that sound?

**Comment by crwatkins** [comment]
@prusnak Will you be able to coordinate with @DarrenSG for a PR for the Trezor Model T?

Would you like to rebrand the Trezor One in that PR (or a separate PR) or would you prefer that we do a simple search and replace?

**Comment by prusnak** [comment]
Updated Trezor branding in https://github.com/bitcoin-dot-org/bitcoin.org/pull/3091

Let's merge this change and then let Darren work on the suggestion for the edit we could discuss later.

**Comment by wbnns** [comment]
@crwatkins 

> I therefore still believe when there are different models from the same vendor which have distinguishing differences that users might choose between, we owe it to our users to list both models if requested by the vendor (and of course only if they meet our criteria). The Trezor Model T has not yet been listed because it was never submitted for listing (and quite honestly because of our work load, we don't tend to submit many listings ourselves).
>
> Taking this to the next step, there are different versions of certain models. Some may differ based on physical appearance such as the color of the case. I don't think we should list both the white and black versions of the Trezor One, so I would not recommend listing versions that are not functionally unique.

Ok, thanks.

@prusnak 

> Updated Trezor branding in #3091
>
> Honestly, there is very limited space in the listing (only 320 characters), so I change my opinion and I think that Corazon should be listed separately. There is simply not enough space to explain what is Model T, how it differs from Trezor One and how does Corazon differ from Model T.

Thanks for your help with the PR. With regard to the to Corazon, since it isn't functionally unique in the context we're discussing here, would lean to recommend that the wallet page isn't the ideal location for it.
