### ISSUE TITLE
New event: Baltic Honeybadger 2019

### ISSUE THREAD

**Issue by mgpnd** [bitcoin-dot-org/bitcoin.org#3064]
- date: 2019-09-14
      title: "Baltic Honeybadger 2019"
      venue: "RISEBA Arhitektūras un mediju centrs H20 6"
      address: "Durbes iela 4"
      city: "Riga"
      country: "Latvia"
      link: "https://bh2019.hodlhodl.com/"

**Comment by khendraw** [comment]
- Is this event specifically related to Bitcoin?  Yes
- Is there a talk focused exclusively on Bitcoin? Yes
- Are the majority of talks focused on ICOs and/or other digital currencies? No
**In my opinion this event should be added to Bitcoin.org**
