### ISSUE TITLE
New Event: Provenance Summit Tokyo 2019

### ISSUE THREAD

**Issue by manhuichi** [bitcoin-dot-org/bitcoin.org#3065]
- date: 2019-10-14
      title: "Provenance Summit Tokyo"
      venue: "Happo En"
      address: "1 Chome-1-1 Shirokanedai, Minato City, Tokyo 108-0071, Japan"
      city: "Tokyo"
      country: "Japan"
      link: "www.provenance.events"

**Comment by khendraw** [comment]
Is this event specifically related to Bitcoin? No
Is there a talk focused exclusively on Bitcoin? No
Are the majority of talks focused on ICOs and/or other digital currencies? No, it is about blockchain technology in general.
In my opinion this event is not to be added to Bitcoin.org
