### ISSUE TITLE
Trustology TrustVault - wallet listing exception

### ISSUE THREAD

**Issue by mrhornsby** [bitcoin-dot-org/bitcoin.org#3071]
Hi,

I'm the CTO of [Trustology](https://www.trustology.io) and we'd like you to consider listing our multi-asset iOS wallet, [TrustVault](https://apps.apple.com/gb/app/trustvault/id1455959680). 

There are two of the basic criteria that we don't satisfy:

1. Uses deterministic ECDSA nonces (RFC 6979)
   * We use a FIPS compliant HSM to store customers seeds and to enforce access controls, thus we can't control the generation of the ECDSA nonce values

1. User has access to private keys
   * To ensure the security of our solution and provide guarantees to our clients we don't allow a user access to the private keys or the seed for their wallet

Please let me know if you'd be willing to make an exception in our case, I'm happy to provide more details as needed.

Many thanks

Mark

**Comment by crwatkins** [comment]
Thanks for the questions Mark, and in particular, thanks for your careful review of the criteria.   I don't think there would be a problem on the RFC6967 criteria as long as the HSM used either another deterministic algorithm for the nonce, or a FIPS compliant random number.  However, as I read your web page, I understand that you are providing a custodial solutions (I couldn't download your app from the app store because I'm not running the UK app store) but we currently don't list custodial wallets.  If you have a multisig wallet where the user is in ultimate control of the their funds without your help, let us know.

**Comment by mrhornsby** [comment]
Thanks for the quick response Craig.

Our app will be available globally in a couple of weeks. If it helps I could arrange for you to have test access in the interim.

The way our solution works is to custody a customers seed phrase and generate keys and transactions on their behalf. We use the Secure Enclave of the iOS device to store a delegate key - this key is used to programatically unlock the wallet in our HSM. This functionality is custom code embedded in the HSM firmware. This prevents Trustology from having access to a users keys. The only time we would get involved is where a customer has lost their device (the delegate key cannot be extracted from the secure enclave) and so we would run through a recovery process with them to migrate their custodied wallet to a new device and Secure Enclave key.

Every users funds are secured at their own addresses generated from their custodied wallet and there is no co-mingling of funds (which I think makes us different to most other custodial solutions).

Let me know if you can consider listing us under these conditions. (On the nonce front we are using a FIPS compliant random number generator).

Many thanks

Mark

**Comment by crwatkins** [comment]
Mark, thanks for your explanation.

A good litmus test is "If your company and infrastructure immediately ceased operating today for any reason, would there be any way for a user to retrieve their funds without your assistance?"    If yes, the wallet potentially can be listed.  If not, you might want to look at other areas of the site, including the Resources section to see if you qualify for listing in any of those areas.

**Comment by mrhornsby** [comment]
Hi Craig,

If we ceased trading we would need the company administrators to run the infrastructure for people to extract funds.

Appreciate your help, I'll look at the other areas as you suggest.

Thanks

Mark
