### ISSUE TITLE
GCC Crypto & FXshow Dubai 2019

### ISSUE THREAD

**Issue by JLFevents** [bitcoin-dot-org/bitcoin.org#3072]
date:2019 Oct 30-31
      title: GCC Crypto & FX Show 
      venue: DUBAI
      address: DUBAI
      city: DUBAI
      country:UAE
      link: www.gcccryptoshow.com

**Comment by khendraw** [comment]
1. Is this event specifically related to Bitcoin? No
2. Is there a talk focused exclusively on Bitcoin? No
3. Are the majority of talks focused on ICOs and/or other digital currencies? Yes
In my opinion this event is not to be added to bitcoin.org
