### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by criptoblock** [bitcoin-dot-org/bitcoin.org#3073]
- date: 2019-10-19
      title: "CriptoBlock - Blockchain, adoção e usabilidade de criptomoedas"
      venue: "Investe SP"
      address: "Avenida escola Politécnica, 82 - Jaguaré"
      city: "São Paulo"
      country: "Brasil"
      link: "https://criptoblock.com.br/"

**Comment by khendraw** [comment]
1. Is this event specifically related to Bitcoin? No
2. Is there a talk focused exclusively on Bitcoin? No
3. Are the majority of talks focused on ICOs and/or other digital currencies? No, only blockchain adoption and cryptocurrency usaage in general.

In my opinion, this event is not to be added to bitcoin.org

**Comment by criptoblock** [comment]
@khendraw hello

Are you Brazilian? Not
Do you follow or have participated in any Criptoblock event? Not
Have you ever held an event with content about Bitcoin, Blockchain and Cryptocurrency?
So if you do not know the content of our event is my invitation to accompany in São Paulo on 19-10-19 from 09:00.

I'm sure your criticism of saying that the event has no Bitcoin content will change.

In my view, the event should be included yes.

Please, before criticizing just ask questions.

**Comment by wbnns** [comment]
@criptoblock 

Hello, we also went through your website and agree with @khendraw's conclusion. It is unclear that this event has anything to do with bitcoin, other than being able to use it to buy tickets.
