### ISSUE TITLE
AI & BLOCKCHAIN SUMMIT

### ISSUE THREAD

**Issue by iionova** [bitcoin-dot-org/bitcoin.org#3078]
- date: 2019-11-19 - 2019-11-21
      title: "AI & BLOCKCHAIN SUMMIT - THE BIGGEST CONFERENCE VENUE OF 2019 AS A PART OF SMART CITY WORLD CONGRESS IN BARCELONA"
      venue: "Gran Via Venue"
      address: "Av. Joan Carles I, 64"
      city: "Barcelona"
      country: "Spain"
      link: "http://smartcitybls.com/
![AI   Blockchain Summit for announce](https://user-images.githubusercontent.com/39768098/63379709-8929a380-c39d-11e9-9193-c8c87e1db216.png)
"

**Comment by khendraw** [comment]
Is this event specifically related to Bitcoin? No
Is there a talk focused exclusively on Bitcoin? No
Are the majority of talks focused on ICOs and/or other digital currencies? No, it is about blockchain technology in general.
In my opinion this event is not to be added to bitcoin.org
