### ISSUE TITLE
Edge Wallet Listing / Open Source Code Requirement

### ISSUE THREAD

**Issue by wbnns** [bitcoin-dot-org/bitcoin.org#3080]
As part of #3032 and #3017, we noted that the source code for the **Edge Wallet** listings for both [Android](https://bitcoin.org/en/wallets/mobile/android/edgewallet/) and [iOS](https://bitcoin.org/en/wallets/mobile/ios/edgewallet/) are missing, which are requirements in order to be listed.

The source code links point to a [GitHub profile page for Airbitz](https://github.com/Airbitz) with no repositories, along with a link to the [GitHub profile for Edge](github.com/EdgeApp). It's not immediately clear if Edge wallet for Android or iOS are open source wallets. We'd like to propose using this issue to track updating the source code links on bitcoin.org, or remove the wallet if it's no longer open source.

Since thousands of people visit the wallet pages each week, and ensuring that wallets meet listing criteria is a top priority, we'd like to set a goal to reach an outcome and close this issue no later than September 9th if possible.

Cc: @crwatkins @paullinator @i3inary

**Comment by paullinator** [comment]
Edge is open source and the link to the primary application code is at https://github.com/EdgeApp/edge-react-gui. Thanks for the notice.

**Comment by wbnns** [comment]
@paullinator 

Hello, thank you. It seems the [repository](https://github.com/EdgeApp/edge-react-gui) may not be the wallet, but rather, an open source react-based GUI for interacting with it serverside. We didn't review all of the repository code, though - would that be an incorrect assertion? Also, the repository docs instructed us to download the deprecated Airbitz app and visit [developer.airbitz.co](https://developer.airbitz.co/login) to get an API key:

![image](https://user-images.githubusercontent.com/1130872/64292496-0fc3b080-cf5a-11e9-8137-9c541e1b934e.png)

The [link](https://airbitz.co/app), however, redirects to the Edge app, which doesn't seem to support API key registration. We were able to find the Airbitz app in the [Play store](https://play.google.com/store/apps/details?id=com.airbitz&hl=en_US), though, and downloaded it so that we could follow the instructions to get an API key - but it doesn't seem that this is possible when following the subsequent instructions. We noted [a few of the open issues in the repository](https://github.com/EdgeApp/edge-react-gui/issues) were from people who also seemed to have encountered this problem.

Could you please elaborate on the relationship between the repository and the API, and what is open source and/or closed source? Also, is there a corresponding open source repository for the API-related code?

**Comment by wbnns** [comment]
Hello. We've waited an additional two weeks past September 9th, the requested date to try and reach a resolution to this issue. Since we've been unable to do so, we've opened #3117.
