### ISSUE TITLE
New Event: The Lightning Conference

### ISSUE THREAD

**Issue by svanstaa** [bitcoin-dot-org/bitcoin.org#3088]
- date: 2019-10-19
      title: "The Lightning Conference"
      venue: "Magazin in der Heeresbaeckerei"
      address: "Koepenicker Str. 16"
      city: "10997 Berlin"
      country: "Germany"
      link: "thelightningconference.com"

**Comment by bjarnemagnussen** [comment]
I just take the liberty to review this event.

There is not yet a full schedule available, however from the invited speakers and self-description of the event it is clearly geared towards the Lightning network on Bitcoin.

- Is this event specifically related to Bitcoin? Yes, with focus on the Lightning network
- Is there a talk focused exclusively on Bitcoin? Yes, with focus on the Lightning network
- Are the majority of talks focused on ICOs and/or other digital currencies? No
 
In my opinion this event should be added to Bitcoin.org

**Comment by khendraw** [comment]
Thank you @bjarnemagnussen for the review. I fully aggree with you.
