### ISSUE TITLE
Bug when switching between "New" and "Experienced" on wizard

### ISSUE THREAD

**Issue by Cobra-Bitcoin** [bitcoin-dot-org/bitcoin.org#3092]
This seems to only be an issue on iOS devices using Safari. Steps to reproduce:

- Visit https://bitcoin.org/en/choose-your-wallet?step=2&platform=ios on an iOS device running Safari (iPhone)
- Toggle between the "New" and "Experienced" by clicking on the boxes but focus your click more on the middle of the box where the text New/Experienced is displayed
- You should find that sometimes rather than the box being selected, the link inside it is selected instead, and the box doesn't get the highlight around it to indicate that it's the current selection

Basically it's possible for a user to click the link **_inside_** the box, without activating the box itself, the following code is the problem:

```
<h4 id="wizardNewTitle" class="helper-user-radio-title anchorAf">
<a href="#wizardNewTitle"></a>New
</h4>
```
Somehow the user is able to click the link inside that box without activating the box. It seems some piece of Javascript is dynamically inserting that link into the DOM too, but I can't seem to track down where that's happening. Feel free to test on an iPhone and you'll quickly see the same issue. Best way I've found to trigger it is to aim my finger on clicking on the text (New/Experienced), and randomly jumping between both boxes until I trigger it.

**Comment by wbnns** [comment]
@Cobra-Bitcoin 

Nice catch, thanks. Looks like this is a precendence-related issue as a result of the [addAnchorLinks](https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/js/base.js#L190) function in `js/base.js`.

The first "touch" when toggling between the two boxes in Safari on iOS activates the anchor link, and the second "touch" will activate the box. In other words, if you touch in the middle of the box, as you mentioned, you should see the anchor link icon appear. If you touch again, the box itself will illuminate, successfully switching between options, as intended.

Cc: @alexcherman
