### ISSUE TITLE
BitBrum 2019

### ISSUE THREAD

**Issue by inspiringcoltd** [bitcoin-dot-org/bitcoin.org#3097]
- date: 2019-11-03
      title: "BitBrum 2019"
      venue: "The Studio"
      address: "7 Cannon St"
      city: "Birmingham"
      country: "United Kingdom"
      link: "http://www.bitbrum.org"

**Comment by inspiringcoltd** [comment]
BitBrum is a not for profit, community inspired, grass-roots organised event. The sole aim of which is inform people about the technological, economic and societal impact of this bitcoin and to equip people with the knowledge to avoid the scams and the tools and confidence to innovate. 

In short we want everyone to benefit from Bitcoin. Not just the tech savvy or those that are already wealthy. Our region has a fine industrial & commercial heritage and together we thrive and prosper on diversity. But take a walk around the streets or travel around the region and you'll see there are many problems to solve. We believe that bitcoin that offers; egalitarian friction-less commerce, decentralised security and permission-less innovation can be part of the solution.

**Comment by khendraw** [comment]
- Is this event specifically related to Bitcoin? Yes
- Is there a talk focused exclusively on Bitcoin? Yes
- Are the majority of talks focused on ICOs and/or other digital currencies? No
In my opinion,  this event should be added to Bitcoin.org.
