### ISSUE TITLE
Tomorrow’s Future

### ISSUE THREAD

**Issue by iionova** [bitcoin-dot-org/bitcoin.org#3098]
- date: 2019-10-03
      title: "Tomorrow’s Future"
      venue: "Sihlhof, Zürich"
      address: "Sihlhof, HWZ Hochschule für Wirtschaft Zürich Lagerstrasse 5, 8004 Zürich "
      city: "Zurich"
      country: "Switzerland"
      link: "http://bit.ly/2zbRBS1"
![#tomorrowsfuture 1x1](https://user-images.githubusercontent.com/39768098/64316820-9d38ec00-cfbe-11e9-8830-7ba87983ce73.png)
"

**Comment by khendraw** [comment]
- Is this event specifically related to Bitcoin? No
- Is there a talk focused exclusively on Bitcoin? No
- Are the majority of talks focused on ICOs and/or other digital currencies? No, it is about emerging technologies in general.

In your opinion, should this event be added to Bitcoin.org? No
