### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by leonjohnson** [bitcoin-dot-org/bitcoin.org#3099]
- date: 2020-02-06
      title: "Advancing Bitcoin Developer Conference"
      venue: "Code Node"
      address: "10 South Pl, London EC2M 7EB"
      city: "London"
      country: "UK"
      link: "https://www.advancingbitcoin.com "

**Comment by khendraw** [comment]
- Is this event specifically related to Bitcoin? Yes
- Is there a talk focused exclusively on Bitcoin? Yes
- Are the majority of talks focused on ICOs and/or other digital currencies? No
In my opinion, this event should be added to Bitcoin.org
