### ISSUE TITLE
MoneyLab#7: Outside of Finance

### ISSUE THREAD

**Issue by DigitalPublishingToolkit** [bitcoin-dot-org/bitcoin.org#3105]
- date: 2019-11-14&15
      title: "MoneyLab#7: Outside of Finance"
      venue: "Tolhuistuin"
      address: ""
      city: "Amsterdam"
      country: "Nederland"
![600*300](https://user-images.githubusercontent.com/4921370/64793724-c4258e00-d57b-11e9-8e1f-b6b575fb23ed.jpg)

      link: "http://networkcultures.org/moneylab7"

**Comment by khendraw** [comment]
1. Is this event specifically related to Bitcoin? No
2. Is there a talk focused exclusively on Bitcoin? No
3. Are the majority of talks focused on ICOs and/or other digital currencies? No, it is more on the financial and economics in general.

In my opinion this event is not to be added to Bitcoin.org
