### ISSUE TITLE
TC Conf

### ISSUE THREAD

**Issue by nicosey** [bitcoin-dot-org/bitcoin.org#3110]
- date: 2019-10-10
      title: "Transylvania Crypto Conference"
      venue: "Cluj-Napoca"
      address: "22-26 Regele Ferdinand Street, Central Commercial Center, 3rd Floor, 400110"
      city: "Cluj- Hub"
      country: "Romania"
      link: "https://tcconf.ro/"

**Comment by khendraw** [comment]
- Is this event specifically related to Bitcoin? No, it is on cryptocurrency in general, including Bitcoin.
- Is there a talk focused exclusively on Bitcoin? Yes (the event are having some bitcoin activists as speakers - and there's "Bitcoin the next 10 years Panel" on the Day 3 schedule.
- Are the majority of talks focused on ICOs and/or other digital currencies? No.

In my opinion this event is to be added to Bitcoin.org
