### ISSUE TITLE
Bitcoin 2020

### ISSUE THREAD

**Issue by branbrandg** [bitcoin-dot-org/bitcoin.org#3113]
- date: 2020-03-27
      title: "Bitcoin 2020"
      city: "San Francisco"
      country: "USA"
      link: "https://www.bitcoin2020conference.com/"

**Comment by khendraw** [comment]
- Is this event specifically related to Bitcoin? Yes
- Is there a talk focused exclusively on Bitcoin? Yes
- Are the majority of talks focused on ICOs and/or other digital currencies? No

In my opinion this event is to be added to Bitcoin.org

**Comment by wbnns** [comment]
@branbrandg 

Hello, we would need a venue and address in order to add this. Please let us know once the information is available.
