### ISSUE TITLE
Donation Address should not be reused

### ISSUE THREAD

**Issue by alexk111** [bitcoin-dot-org/bitcoin.org#3115]
Address reuse abuses the privacy and security of transaction participants. Since it's done on bitcoin.org it also serves as a bad example for others. Consider setting up a [One-Time Address](https://github.com/alexk111/One-Time-Address) instance and replace the hardcoded Bitcoin address with a link to it.

**Comment by wbnns** [comment]
Thanks for the suggestion, however, we maintain a publicly accessible spreadsheet with a [record of receipts and expenditures](https://docs.google.com/spreadsheets/d/1QxDq_9mOvammyfpRyQ8CvUUDsnlyLhx_kTYOBDERM30/edit?usp=sharing) for additional transparency, that anyone in the community can review (transactions to one-time addresses would still be publicly available).
