### ISSUE TITLE
Add Bull Bitcoin as Canadian exchange

### ISSUE THREAD

**Issue by btcsessions** [bitcoin-dot-org/bitcoin.org#3124]
It would be great to have bullbitcoin.com as a Canadian exchange option to buy/spend Bitcoin. It is owned by Francis Pouliot and has been combined with Bylls - a platform that allows Canadians to pay any of their bills with BTC.

**Comment by wbnns** [comment]
@btcsessions 

Thanks. A pull request (#3119) has been opened to make the addition. We'll review.
