### ISSUE TITLE
Bitcoin Pubquiz in Café van Ouds

### ISSUE THREAD

**Issue by exbu** [bitcoin-dot-org/bitcoin.org#3134]
- date: 2019-10-10
      title: "Bitcoin Pubquiz in Café van Ouds"
      venue: "Café van Ouds"
      address: "Augustijnenstraat 33"
      city: "Nijmegen"
      country: "The Netherlands"
      link: "https://www.meetup.com/nl-NL/wearebloxnl/events/265278861/"

**Comment by khendraw** [comment]
- Is this event specifically related to Bitcoin? Yes
- Is there a talk focused exclusively on Bitcoin? No
- Are the majority of talks focused on ICOs and/or other digital currencies? No

In my opinion,  this event is to be added to Bitcoin.org.

**Comment by wbnns** [comment]
@exbu 

Apologies we weren't able to get this added in time. In the future, if you could give us a bit more notice in advance of the event, it shouldn't be an issue.
