### ISSUE TITLE
Unclear which device the Bitbox wallet listing is referencing

### ISSUE THREAD

**Issue by wbnns** [bitcoin-dot-org/bitcoin.org#3135]
For the [Bitbox wallet listing](https://bitcoin.org/en/wallets/hardware/bitbox/?step=5&platform=hardware), the "Visit Website" link points to [Shift Crypto's homepage](https://shiftcrypto.ch/). The "Source Code" link points to the firmware for the Bitbox02.

We should clarify if it is the Bitbox01 or Bitbox02 that is listed, and update the links and references accordingly.

Cc: @crwatkins

**Comment by crwatkins** [comment]
@TheCharlatan @jonasschnelli Would you like to update the branding on your listing?  Just FYI, your source code link was (probably incorrectly) changed during some cleanup.

**Comment by TheCharlatan** [comment]
The current listing refers the BitBox01, so it looks like the firmware Repo was indeed changed incorrectly. The firmware for it is at https://github.com/digitalbitbox/mcu. We will update the listing soon for the BitBox02.

**Comment by crwatkins** [comment]
@TheCharlatan Thanks!

You currently list BitBox01 (under the old branding).  Would you like to continue listing that device or is it obsoleted by BitBox02?   Will you be submitting BitBox02 for listing?  These questions are based on my understanding that the 02 is a significantly different device than the 01.

**Comment by TheCharlatan** [comment]
BitBox01 is not obsoleted, we'll be submitting the listing for BitBox02 soon.

**Comment by crwatkins** [comment]
@TheCharlatan Excellent.  Looking forward to both listings.

**Comment by fresheneesz** [comment]
If BitBox01 gets a separate entry from BitBox02, it should probably be noted with at least some of the caveats mentioned here:

https://saleemrashid.com/2018/11/26/breaking-into-bitbox/

Its unclear to me which issues were fixed in BitBox01, and which issues were only fixed in BitBox02.

**Comment by crwatkins** [comment]
@fresheneesz PR #3142 replaces the BitBox01 entry.

**Comment by TheCharlatan** [comment]
@fresheneesz a replacement listing for the BitBox01 has been submitted. The BitBox02 is a new design both in hardware and software, sharing few commonalities with the BitBox01. The vulnerabilities listed in that post were all fixed, safe for the "secure chip" issues, which cannot be patched easily.

**Comment by fresheneesz** [comment]
@TheCharlatan Thanks for the info!

**Comment by wbnns** [comment]
Closing; resolved by #3142 .
