### ISSUE TITLE
Bitcoin 2020

### ISSUE THREAD

**Issue by branbrandg** [bitcoin-dot-org/bitcoin.org#3137]
- date: 2020-03-27
      title: "Bitcoin 2020"
      venue: "SVN West"
      address: "10 S Van Ness Ave"
      city: "San Francisco"
      country: "USA"
      link: "https://www.bitcoin2020conference.com/"

**Comment by khendraw** [comment]
- Is this event specifically related to Bitcoin? Yes
- Is there a talk focused exclusively on Bitcoin?  Yes
- Are the majority of talks focused on ICOs and/or other digital currencies? No
In my opinion, this event should be added to Bitcoin.org.

**Comment by branbrandg** [comment]
Hi-

Can there be any progress made on this?

Thanks,
Brandon

**Comment by annetdeboer** [comment]
This event is postponed to Q3 2020, due to Corona / COVID19 virus; see: https://bitcoinmagazine.com/articles/postponed-bitcoin-2020-is-moving-to-q3-2020

Exact dates not published yet. @branbrandg any idea when the new dates get published?

**Comment by branbrandg** [comment]
Hi Annet,

We are working on all of the new details right now. Lots of moving pieces,
so I can't give you an answer right now, but as soon as we have info, we
will share it with you.

Thanks,
Brandon

**Comment by wbnns** [comment]
@annetdeboer @branbrandg Thank you.
