### ISSUE TITLE
Adding a list of features to individual wallet pages

### ISSUE THREAD

**Issue by wbnns** [bitcoin-dot-org/bitcoin.org#3143]
This was previously mentioned by @crwatkins during the wallet redesign.

While it's currently possible to see what wallets are available based on selected features in the new wizard, it's not possible to see all of the features that are available once one has navigated to an individual wallet page. On individual wallet pages, we should show what features are available for the wallet that is being viewed.

Cc: @crwatkins @natiwa @alexcherman

**Comment by wbnns** [comment]
Prior to the holidays, we began experimenting with this idea. Below is a draft of what it could potentially look like, adding a "Features" section to the top of each individual wallet page, along with a tooltip for more info:

![image](https://user-images.githubusercontent.com/1130872/71666296-8f268c80-2d60-11ea-8a76-d2f94fa45e39.png)

**Comment by wbnns** [comment]
Just an update -- we're putting together a mobile version of this.

**Comment by crwatkins** [comment]
I assume the tooltip descriptions will be our existing feature descriptions verbatim from the wizard.  If not (for example if they are too verbose) let me know and I will work on that.

**Comment by wbnns** [comment]
@crwatkins 

> I assume the tooltip descriptions will be our existing feature descriptions verbatim from the wizard. If not (for example if they are too verbose) let me know and I will work on that.

Exactly, that's what we were thinking (using the existing descriptions) - thanks.

**Comment by wbnns** [comment]
**Mobile / Handheld:**

![Screen Shot 2020-01-31 at 16 19 40](https://user-images.githubusercontent.com/1130872/73550791-243ea300-443d-11ea-99d6-2b7817ef4b4b.png)

**Tablet:**

![Screen Shot 2020-01-31 at 16 16 01](https://user-images.githubusercontent.com/1130872/73550550-b4301d00-443c-11ea-88f2-236cbadd3562.png)

**Comment by crwatkins** [comment]
Closed by #3270
