### ISSUE TITLE
Adding a dark mode feature

### ISSUE THREAD

**Issue by Cobra-Bitcoin** [bitcoin-dot-org/Bitcoin.org#3151]
It might be good to have a dark mode feature for the site that can be enabled by default for users whose [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) is set to dark, and by a toggle for others.

Our default theme is already quite dark so I don't think it'll take too much effort to have a dark mode since there's only a few areas of brightness on the site. Obviously it should still look quite good though. It's not a necessity but would be a nice touch especially for users running system wide dark modes on their operating systems like the latest macOS.

**Comment by jdabs** [comment]
Is anyone already working on this? I could work on the dark mode stye sheet if not. I have a possible good pallete to work with. Example:
![black-theme](https://user-images.githubusercontent.com/6774432/69817264-35163280-11c8-11ea-9a06-0a8aca71a68f.png)

**Comment by Cobra-Bitcoin** [comment]
@jdabs That palette looks really good, and yeah, go for it, I don't think anybody else is working on it.

**Comment by jdabs** [comment]
Ok, I will see what  I can crank out over my holiday time off and put what I have on a github static site.
It looks easier to load a separate dark stylesheet in case the media query is set to dark, based on the mdn spec. I just don't want to get ugly with !important tags for overwriting the default/light style sheet.

**Comment by wbnns** [comment]
@jdabs 

Hi, yes, as @Cobra-Bitcoin mentioned, no one has given any notice that they're working on this as of yet. Also, yes, let's please adhere to the spec and use a media query.

Thanks for your help. :)

**Comment by jdabs** [comment]
Found an interesting limitation of the spec and the theme color meta tag. You cannot change a metatag value with purely a media query. 
https://html.spec.whatwg.org/multipage/semantics.html#meta-theme-color

However, it looks like chrome for Android only supports this meta tag, but it adds a very nice touch when the phone is set to dark mode.
https://caniuse.com/#feat=meta-theme-color

However chrome on Android is 36% traffic share :)

**Comment by Dorson** [comment]
I coded a flexible and working solution for the Dark Mode.

Try demo in here:
https://dorson.github.io/CSS-Dark-Mode-and-color-switch/

Works with basic CSS variables + short JavaScript.

Can be used inside existing CSS style file. Can be used to define multiple color themes in one CSS file,  or any other possible dynamic CSS style setting options like text size, etc... No user logins or profiles or tracking required.

Let's save our eyesight at night :-)

**Have fun using my code !**

**Comment by angeloko23** [comment]
> It might be good to have a dark mode feature for the site that can be enabled by default for users whose [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) is set to dark, and by a toggle for others.
> 
> Our default theme is already quite dark so I don't think it'll take too much effort to have a dark mode since there's only a few areas of brightness on the site. Obviously it should still look quite good though. It's not a necessity but would be a nice touch especially for users running system wide dark modes on their operating systems like the latest macOS.

**Comment by Cobra-Bitcoin** [comment]
Going to go ahead and close this. We have dark mode in the codebase, but we only need to fix how the dark mode looks on some pages (wallets, etc) now, so we have a good base to work with.
