### ISSUE TITLE
Add ZEBITEX to Europe exchange page

### ISSUE THREAD

**Issue by Chrisss31** [bitcoin-dot-org/bitcoin.org#3152]
Hello,
We are DIGITAL SERVICE, we own ZEBITEX and we provide others services like DIGYCODE ( the crypto voucher available on more 10k point of sale in Fance and more, and ZeBitcoin a crypto broker.
ZEBITEX is the first multi crypto exchange in France  launch on november 2018, we tens of active pairs against 4 standard market EUR for fiat and BTC - ETH and USDT for crypto.  we are interested in listing in site bitcoin.org as one of the Europe bitcoin exchanges. Could you give us more detail about the process of listing and related conditions？
Best Regards

**Comment by wbnns** [comment]
@Chrisss31 

Hello, please review our [documentation](https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/docs/adding-exchanges.md) for exchanges and let us know how you'd like to proceed.
