### ISSUE TITLE
Bizar Bitcoin Bazar

### ISSUE THREAD

**Issue by annetdeboer** [bitcoin-dot-org/bitcoin.org#3155]
- date: 2019-11-20
      title: "Bizar Bitcoin Bazar"
      venue: "Bizar-Bazar"
      address: "Ing. J.P. van Muijlwijkstraat 19-a"
      city: "Arnhem Bitcoin City"
      country: "the Netherlands"
      link: "https://www.arnhembitcoinstad.nl"

**Comment by khendraw** [comment]
- Is this event specifically related to Bitcoin? Yes
- Is there a talk focused exclusively on Bitcoin? Yes
- Are the majority of talks focused on ICOs and/or other digital currencies? No

In my opinion, this event should be added to Bitcoin.org.
