### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by bolaigeafe** [bitcoin-dot-org/bitcoin.org#3158]
- date: 2019-11-23
      title: "Crypto Revolution and it's Economic Advantage"
      venue: "Conference Hall, University of Ibadan, Nigeria"
      address: "University of Ibadan Campus, UI, Ibadan"
      city: "Ibadan"
      country: "Nigeria"
      link: "https://www.meetup.com/CryptoNigeria/members/265640430/"

**Comment by khendraw** [comment]
Hello @bolaigeafe , could you please kindly provide url of the "Crypto Revolution and it's Economic Advantage" event since I cannot find the event information on the URL provided.
Thanks.

**Comment by bolaigeafe** [comment]
https://www.eventbrite.com/e/crypto-revolution-and-its-economic-advantage-tickets-80939392903

**Comment by khendraw** [comment]
- Is this event specifically related to Bitcoin? Yes
- Is there a talk focused exclusively on Bitcoin? Yes
- Are the majority of talks focused on ICOs and/or other digital currencies? No
In my opinion, this event should be added to Bitcoin.org.

**Comment by bolaigeafe** [comment]
Okay.
So, please what can I do next?
The scheduled date is fast approaching already

**Comment by khendraw** [comment]
Thank you for your reply @bolaigeafe, I have address this to the web team so the event should be appear on the https://bitcoin.org/en/events in time.

cc: @wbnns

**Comment by wbnns** [comment]
@bolaigeafe 

Thank you for submitting your event.

#3180 has been opened to add it to the website and will be merged shortly.

**Comment by bolaigeafe** [comment]
Thank you for your support.
Please, is there any possibility of getting Bitcoin merchandise and materials for the publicity and marketing during event?

**Comment by wbnns** [comment]
@bolaigeafe 

You're welcome. For bitcoin merchandise and materials, you may want to consider reaching out to some local bitcoin companies in your area, since the event is only a few days away.
