### ISSUE TITLE
Mining Disrupt 2020

### ISSUE THREAD

**Issue by robinlam2017** [bitcoin-dot-org/bitcoin.org#3167]
- date: 2020-07-22
      title: "Mining Disrupt 2020"
      venue: "DoubleTree Hilton MACC"
      address: "711 NW 72nd Ave”
      city: "Miami"
      country: "USA"
      link: "www.miningdisrupt.com"

**Comment by khendraw** [comment]
- Is this event specifically related to Bitcoin? No
- Is there a talk focused exclusively on Bitcoin? Yes
- Are the majority of talks focused on ICOs and/or other digital currencies? No
In my opinion, this event should be added to Bitcoin.org
