### ISSUE TITLE
Listing custodial Lightning wallets

### ISSUE THREAD

**Issue by crwatkins** [bitcoin-dot-org/bitcoin.org#3173]
For years now, we [have required](https://github.com/bitcoin-dot-org/bitcoin.org/pull/1706) user access to private keys for wallet listings and the community has been very adamant on the subject.  In early discussions when there were few Lightning Network wallets available, [I have argued](https://github.com/bitcoin-dot-org/bitcoin.org/pull/3000#issuecomment-499097115) both pro and con positions for listing custodial Lightning wallets.  As many more wallets have been released and since we recently [added a new selection filter](https://github.com/bitcoin-dot-org/bitcoin.org/pull/3017) that allows users to specifically select wallets listed with Lightning capability, it is probably time to revisit the topic.

1. The community has been very adamant on the custodial topic for on-chain wallets
1. There are two non-custodial LN wallets listed
2. Users can now come to bitcoin.org to specifically request LN wallets
2. There have been custodial [issues](https://github.com/BlueWallet/LndHub/issues/8) confirmed with LN wallets that are not expected with wallets based on consensus
2. Many, if not all, released LN wallets provide Lightning functionality as an obvious major feature of the application, not a hidden optional function

There have been discussions that by making LN wallets custodial, on-boarding and general user experience can be easily improved.  I think the same can be said for on-chain wallets, and those arguments have been previously rejected.   The point could also be made for using PayPal instead.

For these reasons, I'm leaning toward applying the "access to private key" criterion to major off-chain features (including LN) of wallets as well as on-chain features.  This seems quite consistent with what we do today with the concept of exchange features and whether the custodial exchange is a major feature of the wallet or not.

Thoughts and discussion are very welcome.

**Comment by wbnns** [comment]
@crwatkins 

Thanks for raising this issue. Yes, am also thinking that we should apply the private key criterion.

**Comment by ncoelho** [comment]
The concept of private key, hosting and custody is something that should be applied on lightning in a different way compared to Layer 1. For instance, "Does the user has the possibility to have full custody?" - I think that's the right question to ask.

Let me try explain why. 

Lightning being a payments network technology has different trade off concepts compared to Layer 1.
- Liquidity is needed upfront;
- Wallets and channels are not the same;
- Channel states can be broadcasted by any party.

These different constrains/properties of the network design, makes many different use cases for custody or non-custody completely legitimate and needed. Let's take a look on them:

- Having a custodial wallet serving has a liquidity provider to receive with ability to withdraw;
- Having a non-custodial wallet with a custodial channel with ability to receive and withdraw;
- Having ability to 3rd-party custody the "watching service" of the channel states;
And probably others we can think of...

My point being that the concept of private key ownership is not related with the concept of custody of funds on Lightning. Probably the tech will get there and I do hope so, but that's not the case in the near future.

**Comment by crwatkins** [comment]
Hey @ncoelho thanks for commenting!  It's been a bit too quiet here.

I think I understand your points about the advantages of providing a custodial solution, however

> My point being that the concept of private key ownership is not related with the concept of custody of funds on Lightning.

While that's an intriguing thought to consider, I don't think I quite understand.   It seems to me that private key ownership is directly tied to the custody of the funds.  Can you explain?

**Comment by ncoelho** [comment]
Let me see if I can explain that sentence better.

You can have a lightning node hot wallet (you own your private key), and at the same time use:
- custodial channels;
- use a 3rd party "watch tower" service;

In both cases you will own your private keys but that won't guarantee a trust-less/self-sovereign/censorship-resistent setup, or custody of your funds which I assume is what we are discussing here. 

We are assuming the same properties of a consensus based network like bitcoin, which is not the case on Lightning. In Lightning which is spec based, any implementation can have their own trade-offs as long as they respect the BOLT specs. 

We are already seeing examples of what I'm referring above appearing in the wild. Thus, the right question imho at the moment will be "Does the user has the possibility to have full custody?" if so allow the wallet and not "only allow full non-custodial services".

**Comment by wbnns** [comment]
#3186 has been merged, but leaving this open since there continues to be a discussion regarding semantics on how this could potentially be improved further.

**Comment by crwatkins** [comment]
I'll start by reporting on the history/precedence as best as I know.  Most of our wallet framework was established before my time and my first inclination is always to look for precedence to draw on.  

We have a precedent of evaluating wallets (against requirements and for scoring) based on the default behavior of the wallet.  For example, we classify Armory and mSIGNA as having full node validation capabilities, but not Electrum nor Wasabi because, even though they can utilize your own full node, that's not the default.  

Looking for precedence related to custodial wallets:  In the past, we have [decided against](https://github.com/bitcoin-dot-org/bitcoin.org/pull/1706) listing wallets such as Coinbase even though the app has a non-custodial wallet component. 

@ncoelho wrote 
> Thus, the right question imho at the moment will be "Does the user has the possibility to have full custody?" if so allow the wallet and not "only allow full non-custodial services".

If we are to subscribe to that criterion that would mean that we could re-list exchange apps such as Coinbase again.  In the [past](https://github.com/bitcoin-dot-org/bitcoin.org/issues/1109) there has been little support for doing that.

Next I'll provide some personal thoughts on the Lightning Network; I'm no longer attempting to report on past precedence.

> We are assuming the same properties of a consensus based network like bitcoin, which is not the case on Lightning. In Lightning which is spec based, any implementation can have their own trade-offs as long as they respect the BOLT specs.

I think I can agree with that to a certain point, but for me, that does not include "custodial" holdings nor trusted third parties.

All the mentions of the word "custodial" in the [Lightning Network whitepaper](http://lightning.network/lightning-network-paper.pdf) are preceded by the word "without" except for one "does not require."  I'm not one to pick apart whitepapers looking for divine guidance that was never intended (yes, I'm referring to the Bitcoin whitepaper), but it is completely obvious that the Lightning Network was designed to be non-custodial and not rely on trusted third parties.  I'm currently of the opinion that bolting (pun intended) a custodial component on to the Lightning Network certainly could be considered easy and convenient, just like PayPal and Venmo, but also eliminates the need for about 58 of the 59 pages in the whitepaper.

**Comment by ncoelho** [comment]
I agree with all your thinking and everything you wrote. I'm also not trying to discuss custodial vs non-custodial.

> For these reasons, I'm leaning toward applying the "access to private key" criterion to major off-chain features (including LN) of wallets as well as on-chain features

I was just trying to contribute to your OP by adding that "access to private key" on Lightning doesn't necessarily mean having custody of your funds. Same applies for Liquid sidechain for instance, not sure how to explain this better if I'm not being myself clear.

**Comment by crwatkins** [comment]
OK @ncoelho I think I understand.  Thanks.

**Comment by crwatkins** [comment]
Thanks to all for the input.  At this point, I'm happy with the direction and wording committed in #3186 particularly considering that according to DropBit in the [iOS App Store](https://apps.apple.com/us/app/dropbit-bitcoin-wallet/id1347304050) their custodial lightning funds were [seized ](https://blockstream.info/tx/4c628ffdacdeaf17da2b0c10bf95eb88abdd2ff65b0dbe322324b29dc11835d5) and now are currently unavailable to their users.  This seems like something we should avoid.

**Comment by wbnns** [comment]
@crwatkins Thanks.
