### ISSUE TITLE
[RFC] Review Fee for Exchanges

### ISSUE THREAD

**Issue by wbnns** [bitcoin-dot-org/bitcoin.org#3174]
The [Exchanges page](https://bitcoin.org/en/exchanges) is a popular page on the site, and receives millions of visits from people who are looking for options to choose from to exchange their bitcoin. As Bitcoin continues to grow in popularity, we're seeing a proliferation of exchanges [requesting to be added to the Exchanges page](https://github.com/bitcoin-dot-org/bitcoin.org/pulls?q=is%3Apr+label%3AExchanges). Being on the page is beneficial to exchanges because it helps them get new customers and also improves their rankings across search engines from being linked to from bitcoin.org (bitcoin.org ranks very high for "buy bitcoin" and "bitcoin exchanges").

Exchanges are reviewed before being added to the site. Each month there are requests that are denied due to issues that arise during reviews (which are technical, thorough and unbiased). In an effort to provide continuous and stable/regular funding to the site, and to remain ad-free and neutral (as opposed to a sponsorship model which has been experimented with in the past that singles out one or more select organizations), we wanted to solicit community feedback about the possibility of requiring an annual non-refundable review fee to all exchanges requesting to be part of the page.

The idea is that the review fee would be non-refundable and would basically cover each exchange being reviewed upon request for potential inclusion along with regular re-reviews on an ongoing basis - these things we already do. So basically, there would be no change to the current workflow, with the exception of the fee.

Cc: @Cobra-Bitcoin

**Comment by crwatkins** [comment]
@wbnns This is an interesting idea.  Thanks much for floating it.

What is the goal?  Or maybe I should ask, what is your main goal in proposing this?  Goals I could imagine:

1. Reduce workload by charging a fee to weed out less "serious" submissions
1. Reduce workload by charging a fee to encourage more self-review and higher quality submissions
2. Fund (subsidize) the site by charging a fee
3. Encourage extra volunteers by charging a fee to pay bounties to perform reviews

Something else?

**Comment by wbnns** [comment]
@crwatkins 

Thanks. The main goal is to provide continuous and stable/regular funding to the site (as opposed to using sponsorship models that have been experimented with in the past, that single out one or more entities).

This would yield more opportunities for volunteers to earn bitcoin for their contributions across the site, not just the Exchanges page ([example](https://bitcoin.org/en/posts/recognizing-recent-efforts-of-volunteer-translators)).

**Comment by Cobra-Bitcoin** [comment]
Really good idea.

A lot of effort goes into verifying and checking that these exchanges are legitimate and operate properly, so some fee to handle the whole listing process makes sense. It also filters out the less serious submissions. If they aren't prepared to pay a fee to get their exchange reviewed it doesn't really bode well for their legitimacy. Many of these exchanges won't even last that long, so not only is reviewing them for addition required, but somebody has to regularly keep track of every exchange we currently list and look at if they're still even around with significant volume and _actually_ serving the customers under the country in which they're listed on the exchange page. The review fee should start with new exchanges wanting to be listed and then gradually expand to all exchanges. 

With respect to the exchanges page in general, I think a good long term goal would be to make the exchanges page much smarter, have some sort of wizard as we do with the wallets page, and maybe automatically recommend certain exchanges based on the location of the user. That makes it even more important though to have a list of exchanges that we can mostly assume are operating legitimately, and having regular and consistent review.

**Comment by crwatkins** [comment]
One of our missions is

* Remain a neutral informative resource about Bitcoin

and I'm a bit concerned about a plan that results in "If you don't pay us, you don't get listed."  I think that's OK for an organization selling advertising space, but not for a neutral source of information.  I understand that the payment would be for the review, but in the end according to the proposed plan if you don't pay, you don't get listed.

One option (which I haven't decided whether is a good idea or not, but thought I would mention it) is something similar to Guinness World Records which I believe allows for expedited review for a fee.  In our case, we could encourage donations or sponsorships (perhaps with various levels which are acknowledged for both appreciation and transparency reasons on the listings) which could influence the priority of reviews, but not preclude a listing.

**Comment by wbnns** [comment]
@crwatkins 

Disagree. Charging a fee for something like this is pretty common and well-established practice, and it would be a concerning thing if an exchange didn't have enough liquidity to pay for a formal review, or if they objected to having one conducted by a third party.

As an addendum, would recommend that we allow exchanges to provide a recent third party report with acceptable criteria as a substitute.

Don't think we should let exchanges pay for expedited reviews, as you mentioned, though.
