### ISSUE TITLE
Genesis Block 2020

### ISSUE THREAD

**Issue by dualist-inquiry** [bitcoin-dot-org/bitcoin.org#3179]
- date: 2020-01-09
      title: "Genesis Block 2020"
      venue: "Cowrks,  Residency Road"
      address: " Purva Premiere, Residency Rd, Shanthala Nagar, Ashok Nagar, Karnataka- 560025"
      city: "Bengaluru"
      country: "India"
      link: "www.genesisblock2020.com"

**Comment by khendraw** [comment]
- Is this event specifically related to Bitcoin? Yes
- Is there a talk focused exclusively on Bitcoin? Yes
- Are the majority of talks focused on ICOs and/or other digital currencies? No

In your opinion, this event should be added to Bitcoin.org.
