### ISSUE TITLE
adding new exchange 

### ISSUE THREAD

**Issue by monika-dotcom** [bitcoin-dot-org/bitcoin.org#3196]
hi bitcoin.org 

i am working at the crytpo exchange etoro.com and would like to add . 
let me know what you need in order to add eToro and how the process is .
as we have to pay the fee of 2500$ is it possible to add etoro.com tracking link so we can see
how many traders are coming to eToro through bitoin.org ?

many thanks
Monika

**Comment by wbnns** [comment]
@monika-dotcom 

Hello, we are closing this issue as it is a duplicate. #3166 has already been opened for the potential inclusion of eToro.

Regarding link tracking, we generally do not encourage their use and recommend direct links.

**Comment by monika-dotcom** [comment]
> @monika-dotcom
> 
> Hello, we are closing this issue as it is a duplicate. #3166 has already been opened for the potential inclusion of eToro.
> 
> Regarding link tracking, we generally do not encourage their use and recommend direct links.

hi , the ticket is about etoroX ,  but i asked for etoro.com , can you please reconsider

**Comment by wbnns** [comment]
@monika-dotcom 

Apologies if the requests were misunderstood. To clarify, since eToro owns eToroX, are the requests to add two different websites?

**Comment by monika-dotcom** [comment]
no worries, etoro.com and etoroX are two companies , we operate totally independent of each other . on conferences you will see also 2 booths,  each for one company .

**Comment by wbnns** [comment]
@monika-dotcom 

> no worries, etoro.com and etoroX are two companies , we operate totally independent of each other .

Hello, it seems that the eToro customer support employees are the same ones that provide support for eToroX. As a result, we're closing this for now, pending the outcome of #3166.
