### ISSUE TITLE
"2" address unexpectedly changed to "m" address in Testnet

### ISSUE THREAD

**Issue by wilsonpc** [bitcoin-dot-org/bitcoin.org#3199]
Using Bitcoin Core 0.18

[Testnet found blocks](https://tbtc.bitaps.com/mtAeMSyVpsdX3BrVdNMaKwA1G8G4GMWHpF) (other transactions shown are test transactions with faucet coins)

**bitcoin-cli getnewaddress** gave me an address that I used as the pools address (2N5tv3gJzBD1zZ2hri2ffYbHsm1AEhpNQFz); began mining; 6 blocks were found; but heights  found, instead of by my "2" address, were found by the random address in the link above beginning with an "m". 

I have no idea where this "m" address came from or how it "changed"; it doesn't belong to my Bitcoin Core wallet and I have no access to the funds (not an issue but it would be nice to return faucet coins).  Concern is whether something like this can occur on Mainnet.

**Comment by wbnns** [comment]
@wilsonpc 

Hello, please open this issue on the [GitHub repository](https://github.com/bitcoin/bitcoin/issues) for Bitcoin Core.

**Comment by wilsonpc** [comment]
Thanks.  Done.  

I used the link on this page [Bitcoin Developer Examples](https://bitcoin.org/en/developer-examples#testing-applications) under Testing Applications - Testnet - Report Issue.

Maybe that Report Issue link should be changed.

**Comment by wbnns** [comment]
@wilsonpc 

Thanks for letting us know, apologies that wasn't clear.
