### ISSUE TITLE
Unconfiscatable Bitcoin Not Blockchain Conference

### ISSUE THREAD

**Issue by themuzzman** [bitcoin-dot-org/bitcoin.org#3202]
- date: 2020-02-22
      title: "Unconfiscatable Bitcoin Not Blockchain Conference"
      venue: "The D Hotel & Casino"
      address: "301 Fremont St."
      city: "Las Vegas, NV 89101"
      country: "USA"
      link: "https://www.unconfiscatable.com"

**Comment by khendraw** [comment]
- Is this event specifically related to Bitcoin? Yes 
- Is there a talk focused exclusively on Bitcoin? Yes
- Are the majority of talks focused on ICOs and/or other digital currencies? No

In my opinion, this event should be added to Bitcoin.org.
