### ISSUE TITLE
Add AgoraDesk to P2P Exchanges

### ISSUE THREAD

**Issue by LocalMonero** [bitcoin-dot-org/bitcoin.org#3203]
Hello!

[AgoraDesk](https://agoradesk.com) is a P2P OTC exchange recently created by us, the team behind [LocalMonero](https://localmonero.co). We've been running Monero's equivalent of LocalBitcoins for over 2 years and have earned the trust of the extremely skeptical Monero community.

AgoraDesk is our expansion into Bitcoin. We offer the same fast and easy trading experience that LocalBitcoins used to offer before they started implementing mandatory KYC/AML. [Here's a bigger article comparing us to LocalBitcoins in case you need more information](https://agoradesk.com/localbitcoins-alternative).

In addition, we are the first and only exchange platform in the entire industry that offers P2P OTC bitcoin options. It's similar to how option trades work on the #bitcoin-otc IRC channel, except we have an improved put option flow and we've made it all nice and simple just like a normal trade on LocalBitcoins.

We hope that this is enough to be added to the bitcoin.org P2P exchanges list.

Thanks!

**Comment by wbnns** [comment]
Related: 3210
