### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by DanielSanW** [bitcoin-dot-org/bitcoin.org#3208]
- date: 2020-06-30
      title: "Value of Bitcoin Conference 2020"
      venue: "Alte Kongresshalle"
      address: "Am Bavariapark 14"
      city: "Munich"
      country: "Germany"
      link: "https://vob-conference.com/"

**Comment by khendraw** [comment]
- Is this event specifically related to Bitcoin? Yes
- Is there a talk focused exclusively on Bitcoin? Yes
- Are the majority of talks focused on ICOs and/or other digital currencies? No
In my opinion this event should be added to Bitcoin.org
