### ISSUE TITLE
bitcoin-qt -> transactions window: dates are incorrect for older transactions

### ISSUE THREAD

**Issue by ximonn** [bitcoin-dot-org/bitcoin.org#3211]
Bitcoin core version v0.19.1 (64 bit linux precompiled). Qt version 5.9.8.

When adding a watch only address the blockchain is parsed to find transactions for this address. The recent transactions list shows the last transactions.
The problem is that the dates are incorrect. 
For a transaction done in 2017 a date in 2019 is given (e.g. 28-06-19 is given instead of the correct date which is 2017-12-03) . 
The same wrong dates are shown in the transaction view. 
The totals in btc are correct.

To reproduce: add a watch only address via the console:
> importaddress xxxxxxx

**Comment by jdabs** [comment]
Thanks @ximonn . Since this sounds like a bug with QT, would it be better to submit this on Bitcoin core repo? https://github.com/bitcoin/bitcoin/issues

**Comment by wbnns** [comment]
@ximonn Thank you. As @jdabs mentioned (thanks jdabs), we recommend opening the issue on the Core repository.
