### ISSUE TITLE
Add Artis Turba to Exchanges

### ISSUE THREAD

**Issue by ArtisTurba** [bitcoin-dot-org/bitcoin.org#3214]
[Artis Turba](https://artisturba.com) is an intuitive cryptocurrency exchange built for individuals, traders and investors. Located in South Africa, Artis Turba enables buying and selling of Bitcoin against the South African Rand (ZAR) and also serves the Namibian, Botswana and Eswatini (Swaziland) markets.

**Comment by wbnns** [comment]
We contacted this exchange's support team but did not receive any acknowledgement or reply in a timely manner (> 1 month).

We recommend that a review be deferred for at least six months.
