### ISSUE TITLE
Financial Cryptography and Data Security 2020

### ISSUE THREAD

**Issue by schwentker** [bitcoin-dot-org/bitcoin.org#3215]
- date: 2020-02-11
      title: "Financial Cryptography and Data Security 2020"
      venue: "Shangri-La Tanjung Aru Resort & Spa"
      address: "No. 20 Jalan Aru"
      city: "Sabah"
      country: "Malaysia"
      link: "https://fc20.ifca.ai/"

**Comment by khendraw** [comment]
- Is this event specifically related to Bitcoin? No
- Is there a talk focused exclusively on Bitcoin? No
- Are the majority of talks focused on ICOs and/or other digital currencies? No
In my opinion, this event is not suitable to be added to Bitcoin.org
