### ISSUE TITLE
Bitcoin Full Node Run Error - Mac OS Mojave

### ISSUE THREAD

**Issue by charliedepucho** [bitcoin-dot-org/bitcoin.org#3219]
To whom it may concern - taking the critical step to download and run a full node. 

I run Mac OS Mojave 10.14.5. After downloading the application from the bitcoin.org website, when I attempt to run the software, I receive the following error message: 

<img width="637" alt="Screen Shot 2019-12-14 at 5 30 30 PM" src="https://user-images.githubusercontent.com/58893674/70855875-b1cb3100-1e97-11ea-8734-a4e1d3e1f20d.png">

Am I missing something or does the software need to fixed?

Thanks,

**Comment by wbnns** [comment]
@charliedepucho 

Hello, here's a link to forums where you can connect with others who may be able to help you with your issue: https://bitcoin.org/en/bitcoin-core/help#forums
