### ISSUE TITLE
Considering adding BTCPayServer as a wallet suggestion

### ISSUE THREAD

**Issue by NicolasDorier** [bitcoin-dot-org/bitcoin.org#3222]
I would like to know what you think about it:

BTCPayServer has historically been a payment processor for merchants. 

It turns out that as the time passed, it became a very good wallet as well.
Especially now, it is possible, with the help of the "BTCPayServer Vault" (a desktop app allowing web applications to access your hardware wallet) to use BTCPayServer with any hardware wallet you want.

On top of it, we will soon allow the creation of hot wallets.

Of course, BTCPayServer is special in the sense that it is not a wallet app you can just install on your machine. So I was wondering if it has its place in bitcon.org wallet suggestion list or not.

What do you think?

**Comment by laanwj** [comment]
I definitely think it deserves mention, though I'm not sure it fits in any of the current wallet categories (mobile/desktop/web/hardware). It's more like a category in itself of *server* wallet.

**Comment by crwatkins** [comment]
I agree with @laanwj; I think it would be great to mention it somewhere, but I think we would do a disservice listing it as a wallet as I suspect someone looking for a payment processor would not be looking in the wallet listings (nor would most people looking for just a wallet be well served downloading a payment server).

**Comment by NicolasDorier** [comment]
@crwatkins I want people who search for a wallet, to find btcpayserver. (not someone searching payment processor)
Because this is one of the best way to use your hardware wallet without doxxing yourself to anonymous servers like electrum.

While btcpayserver is well known as a payment processor, it is actually a full fledged self hosted wallet which can interop with any hardware wallet.

**Comment by ncoelho** [comment]
I would suggest a new section for payment processors, billing, point-of-sale. Another section for APIs, SDKs and developer tools, for instance.

Different user types, require different tooling.

**Comment by NicolasDorier** [comment]
I am closing this. I understand why it is not clear to appear on the Wallets section.

I think another section would be very useful. After all, Bitcoin have a huge list of projects which are not advertised on bitcoin.org. I don't have time to polish another section though, will open new issue if I work on that.

**Comment by wbnns** [comment]
Added a stub (#3245) based on the conversation, above.
