### ISSUE TITLE
Portland Bitcoin Conference

### ISSUE THREAD

**Issue by ascisco** [bitcoin-dot-org/bitcoin.org#3234]
2020-05-03
Portland Bitcoin Conference
Oregon Convention Center
777 NE Martin Luther King Jr Blvd
Portland, Oregon
United States
https://portlandbitcoinconference.com/

**Comment by khendraw** [comment]
- Is this event specifically related to Bitcoin? Yes
- Is there a talk focused exclusively on Bitcoin? Yes
- Are the majority of talks focused on ICOs and/or other digital currencies? No

**In my opinion this event should  be added to Bitcoin.org**

**Comment by ascisco** [comment]
This even has been postponed until October 25th, 2020

Please update bitcoin.org

Thank you.

**Comment by wbnns** [comment]
@ascisco 

Thank you, opened #3300 to change the date.
