### ISSUE TITLE
Mallorca Blockchain Days

### ISSUE THREAD

**Issue by fridgee76** [bitcoin-dot-org/bitcoin.org#3236]
- date: 2020-03-20
      title: "Mallorca Blockchain Days 2020"
      venue: "Hotel Valparaiso"
      address: "Carrer de Francesc Vidal I Sureda, 23"
      city: "Palma de Mallorca"
      country: "Spain"
      link: "www.mallorcablockchaindays.com"

**Comment by fridgee76** [comment]
Mallorca Blockchain Days, a conference for cryptocurrencies and Blockchain technologies, is pleased to announce its upcoming conference happening on Friday, March 20 to Sunday, March 22, 2020. Organized by Mallorca Blockchain, it will be held in Palma de Mallorca (Spain), at the Hotel Valparaiso, one of the most emplematic hotels in Palma de Mallorca. 
The ground-breaking Blockchain conference is set on March 21st, 2020, in Mallorca, and the event itself will last for a day. However, there will be a day before and after intended for networking and having fun along with Bitcoin experts, as well as Blockchain developers and ventures investors.
“We bring those at the forefront of Blockchain technologies together,” commented Christian Luecke from Mallorca Blockchain Days. “Our guiding philosophy statement is 'Nothing is true, everything is permitted', something which allows us to push the limits to which speakers we present and the lack of fear we have in delivering truly cutting-edge ideas.”
Focusing on the possibility of Bitcoin to push personal liberty, a variety of international Blockchain specialists will present their speeches at the conference. Some of the names include Rodolfo Andragnes (Bitcoin Argentina), Christoph Heuermann (Staatenlos), Rahim Taghizadegan (Economist), Jason King (Academy), and many more.
Tickets are now available at the official website of Mallorca Blockchain Days https://mallorcablockchaindays.com/tickets.html and are available in two different packages. The Conference Pass is available for €140, while the VIP package for €680. The organizers of the event promise to make a memorable event in Palma de Mallorca.

**Comment by khendraw** [comment]
- Is this event specifically related to Bitcoin? No
- Is there a talk focused exclusively on Bitcoin? Yes
- Are the majority of talks focused on ICOs and/or other digital currencies? No

In my opinion, this event can be added to Bitcoin.org
