### ISSUE TITLE
FINTECH WORLD FORUM 2020

### ISSUE THREAD

**Issue by fintechworld** [bitcoin-dot-org/bitcoin.org#3248]
- date: 2020-05-21
      title: "FINTECH WORLD FORUM 2020"
      venue: "Kensington Conference and Events Centre"
      address: "Hornton St, Kensington, W8 7NX"
      city: "London"
      country: "United Kingdom"
      link: "https://fintechconferences.com/"

**Comment by khendraw** [comment]
- Is this event specifically related to Bitcoin? No
- Is there a talk focused exclusively on Bitcoin? No
- Are the majority of talks focused on ICOs and/or other digital currencies? No
In my opinion, this event is not to be added to Bitcoin.org
