### ISSUE TITLE
BLOCKCHAIN WORLD CONGRESS 2020

### ISSUE THREAD

**Issue by fintechworld** [bitcoin-dot-org/bitcoin.org#3249]
- date: 2020-05-21
      title: "BLOCKCHAIN WORLD CONGRESS 2020"
      venue: "Kensington Conference and Events Centre"
      address: "Hornton St, Kensington, W8 7NX"
      city: "London"
      country: "United Kingdom"
      link: "https://blockchainconferences.org"

**Comment by khendraw** [comment]
- Is this event specifically related to Bitcoin? No
- Is there a talk focused exclusively on Bitcoin? Yes - just one on day 2
- Are the majority of talks focused on ICOs and/or other digital currencies? No
In my opinion,  this event is not relevant enough to be added to Bitcoin.org
