### ISSUE TITLE
BitBlockBoom Bitcoin Conference

### ISSUE THREAD

**Issue by GaryLeland** [bitcoin-dot-org/bitcoin.org#3258]
- date: 2020-08-29
      title: "BitBlockBoom"
      venue: "Renaissance Hotel"
      address: "15201 Dallas Parkway"
      city: "Dallas"
      country: "USA"
      link: "https://BitBlockBoom.com"

**Comment by khendraw** [comment]
- Is this event specifically related to Bitcoin? Yes
- Is there a talk focused exclusively on Bitcoin? Yes
- Are the majority of talks focused on ICOs and/or other digital currencies? No
**In my opinion, this event should be added to Bitcoin.org**
