### ISSUE TITLE
The Bitcoin Reformation

### ISSUE THREAD

**Issue by Jeans5** [bitcoin-dot-org/bitcoin.org#3264]
- date: 2020-04-25/26
      title: The Bitcoin Reformation
      venue: Conference: A Debate On The Decade's Best Performing Asset
      address: Zuiderkroon
      city: Antwerp
      country: Belgium
      link: http://bit.ly/2Oz6G8k

**Comment by khendraw** [comment]
- Is this event specifically related to Bitcoin? Yes
- Is there a talk focused exclusively on Bitcoin? Yes
- Are the majority of talks focused on ICOs and/or other digital currencies? No
In my opinion, this event should  be added to Bitcoin.org

**Comment by Jeans5** [comment]
Hi @wbnns  , 

Can you provide any information about why you each time close this issue? It's a genuine event with relevant speakers who all confirmed speaking. We host this event for the first time in Belgium and would appreciate it if Bitcoin.org could help to promote it by publishing it on the events page. Let us know if there would be any changes we would need to do.

Thanks.

**Comment by wbnns** [comment]
@Jeans5 

Hi, sure:

+ #3263 was closed because it was submitted incomplete/blank, with no information about the event.
+ #3264 (this issue) is open and was [reviewed yesterday](https://github.com/bitcoin-dot-org/bitcoin.org/issues/3264#issuecomment-583460617). The event will be added soon.
+ #3265 was closed because it had the same name, date, url, etc. as the previously mentioned issue.

If you have any other questions please let us know.

**Comment by Jeans5** [comment]
Hi @wbnns , thanks for adding the conference to the events page. Any idea when this would happen?

**Comment by wbnns** [comment]
@Jeans5 

It should be on the site later today.

**Comment by Jeans5** [comment]
Hi @wbnns , due to a high demand we changed the dates of the event to 24 and 25th of April. Would it be possibe to change this on the website? Thanks!

**Comment by wbnns** [comment]
@Jeans5 

Hello, ok, we'll update it.

**Comment by annetdeboer** [comment]
This conference is postponed to Q4 2020, due to Corona / COVID19 virus, see: https://thebitcoinreformation.com/
Exact dates not published yet. @Jeans5 (hi :) any idea when the new date becomes public?

**Comment by Jeans5** [comment]
Hi,

That's correct, the conference is postponed to Q4 this year. As soon as we have decided on a new date for the conference, I'll let you know! Would it be possible to already update the date of the event to "Q4 - exact date to be confirmed".

Thanks!

**Comment by wbnns** [comment]
@annetdeboer Thank you.

@Jeans5 Apologies, we'd need a date and location in order for the event to be on the website.
