### ISSUE TITLE
Add Monero Konferenco 2020

### ISSUE THREAD

**Issue by ajs-xmr** [bitcoin-dot-org/bitcoin.org#3269]
- date: 2020-06-13
      title: "Monero Konferenco"
      venue: "MotionLab.Berlin"
      address: "Bouchéstr. 12 | Hall 20 12435 Berlin"
      city: "Berlin"
      country: "Germany"
      link: "https://monerokon.com"

**Comment by khendraw** [comment]
- Is this event specifically related to Bitcoin? No
- Is there a talk focused exclusively on Bitcoin? No
- Are the majority of talks focused on ICOs and/or other digital currencies? Yes
In my opinion this event is not to be added to Bitcoin.org

**Comment by ajs-xmr** [comment]
> Is this event specifically related to Bitcoin? No

There are other events currently listed that are not specifically related to Bitcoin (e.g. Magical Crypto Conference, Mining Disrupt 2020).

> Is there a talk focused exclusively on Bitcoin? No

Any technology-focused talk, including ones exclusively related to Bitcoin, are welcomed. CFP is still open.

> Are the majority of talks focused on ICOs and/or other digital currencies? Yes

No. The focus of the conference is on presenting state-of-the-art research. Privacy-preserving cryptographic methods, such as [Confidential Transactions](https://people.xiph.org/~greg/confidential_values.txt), are relevant to Bitcoin.

**Comment by wbnns** [comment]
@ajs-xmr 

Thank you for following up. If other contributors disagree and think this should be added, we can reconsider.
