### ISSUE TITLE
Removing mixing/shuffling filter from wallet selector

### ISSUE THREAD

**Issue by wbnns** [bitcoin-dot-org/bitcoin.org#3276]
While this continues to be researched to improve fungibility, I don't think that it should specifically be filter criteria in the wallet selector. Although bitcoin.org is a global site, the application of how mixing and shuffling can/should be applied is becoming more of a legal gray area.

Therefore, would recommend that it be removed until there is more clarity on the matter.

Cc: @crwatkins

**Comment by crwatkins** [comment]
If a user comes to bitcoin.org looking for a wallet that can perform mixing/shuffling, I think we should provide a feature selection to help them find it.  I think I see (what perhaps is) @wbnns point in that our description describes it in a way in which it might be perceived as universally desirable when it may or may not be.   Perhaps a small change in the description might be sufficient to help educate users?

**Comment by wbnns** [comment]
@crwatkins 

Thanks for the feedback. I think it should be removed.

In addition to what I said I can see that site analytics thus far in 2020 show it has only been used 235 times as an option to filter wallets, registering 235 pageviews (each time it is selected it registers a pageview), when by comparison, the site has had 2,558,706 pageviews.

So ~0% of traffic is utilizing it.
