### ISSUE TITLE
Bitcoin Lightning Network Hackday Barcelona

### ISSUE THREAD

**Issue by animalmother1988** [bitcoin-dot-org/bitcoin.org#3278]
- date: 2020-04-04
      title: "Lightning Hackday Barcelona"
      venue: "Polis Parallela"
      address: "Carrer de Jaume Puigvert, 13"
      city: "Barcelona"
      country: "Spain"
      link: "https://lightninghackday.fulmo.org/"

**Comment by khendraw** [comment]
- Is this event specifically related to Bitcoin? Yes
- Is there a talk focused exclusively on Bitcoin? Yes
- Are the majority of talks focused on ICOs and/or other digital currencies? No
In my opinion, this event should be added to Bitcoin.org

**Comment by animalmother1988** [comment]
ALL talks are focused exclusively on Bitcoin/LN!

**Comment by martinbehrens** [comment]
Supporting @khendraw 's motion, should be added.
