### ISSUE TITLE
Startup Bootcamp 2020

### ISSUE THREAD

**Issue by iionova** [bitcoin-dot-org/bitcoin.org#3279]
- date: 2020-09-18
      title: "Startup Bootcamp 2020"
      venue: "Catalonia, Spain"
      address: ""
      city: "Batcelona"
      country: "SPain"
      link: "http://expert.innmind.com/bootcamp
![STARTUP  BOOTCAMP  2020 (8)](https://user-images.githubusercontent.com/39768098/74962076-db648380-5417-11ea-9427-3a39d9500a81.png)
"

**Comment by khendraw** [comment]
- Is this event specifically related to Bitcoin? **No**
- Is there a talk focused exclusively on Bitcoin? **No**
- Are the majority of talks focused on ICOs and/or other digital currencies? **No**

In my opinion,  this event should not be added to Bitcoin.org
