### ISSUE TITLE
New event - TOKEN2049

### ISSUE THREAD

**Issue by AlexFiskum** [bitcoin-dot-org/bitcoin.org#3281]
- date: 2020-10-07
      title: "TOKEN2049"
      venue: "Kerry Hotel"
      address: "38 Hung Luen Rd, Hung Hom, Hong Kong"
      city: "Hong Kong"
      country: "Hong Kong"
      link: "https://www.token2049.com/"

**Comment by wbnns** [comment]
We took a closer look at this event and felt it was too broadly focused for the purposes of placement on the bitcoin.org events page.

If other contributors disagree, we can reconsider.

Cc: @khendraw
