### ISSUE TITLE
Should also Include web safety things are not always free

### ISSUE THREAD

**Issue by clickgetcrypto** [bitcoin-dot-org/bitcoin.org#3288]
I my self find difficult to attain coin, have been phished, hacked, and been through gambit. I was still am a work in progress and I consider myself mildly tech savvy. Need to have more Actionable Encouragement and Knowledge Base to help individuals like myself retain coin and not targets. What this does help build more trust, better user community as well

**Comment by wbnns** [comment]
@clickgetcrypto 

Hello, thanks for the feedback and sorry to hear about your issues. On bitcoin.org, there's a page with tips on how to [avoid scams](https://bitcoin.org/en/scams).

It's linked to in the footer of every page and is also one of the first results on search engines when using search query phrases like "avoiding bitcoin scams" and "bitcoin scams".

Is this what you had in mind?

**Comment by wbnns** [comment]
Since it has been a couple of weeks and we haven't heard back, closing this issue for now.
