### ISSUE TITLE
Review events for accuracy

### ISSUE THREAD

**Issue by jdabs** [bitcoin-dot-org/bitcoin.org#3290]
Considering that events are shifting their schedules worldwide, we need to ensure that all event dates are accurate, cancelled, postponed, or switched to a teleconference style.

Ideally, event submitters need to keep the listing accurate.

**Comment by wbnns** [comment]
@jdabs 

Thanks. We checked all of the existing ones, removed two, and will continue to recheck the others in case of any additional cancellations or postponements.
