### ISSUE TITLE
[Help] Get default wallet's address

### ISSUE THREAD

**Issue by GTP95** [bitcoin-dot-org/bitcoin.org#3294]
Hello everyone.
I'm running bitcoin core v0.17.1 (I need this exact version because I'll use it to deploy a calendar server: https://github.com/opentimestamps/opentimestamps-server) and I'm trying to get the address of the default wallet, so I can put some funds on it. By calling getwalletinfo or listwallets from the CLI I get only one wallet with an empty name: "". By a quick googling seems that this is the default wallet. The first strange (to me) thing is that if I call listlabels I get an empty response:
```
$ bitcoin-cli listlabels
[ 
]
```
when I'm expecting to see the same empty label. Anyway the real problem is that I need the wallet's address but running getaddressbylabel returns an error:
```
$ getaddressesbylabel ""                                                                                        
error code: -11                                                                                                                                                         
error message:                                                                                                                                                          
No addresses with label
```
Should I call getnewaddress first? 
Sorry for the trivial question but I wasn't able to find documentation about this issue.

**Comment by wbnns** [comment]
@GTP95 

> Should I call getnewaddress first?

Hello, yes, that will give you a new address for the wallet. Also, in case helpful:
```
getnewaddress ( "label" "address_type" )

Returns a new Bitcoin address for receiving payments.
If 'label' is specified, it is added to the address book 
so payments received with the address will be associated with 'label'.

Arguments:
1. label           (string, optional, default="") The label name for the address to be linked to. It can also be set to the empty string "" to represent the default label. The label does not need to exist, it will be created if there is no label by the given name.
2. address_type    (string, optional, default=set by -addresstype) The address type to use. Options are "legacy", "p2sh-segwit", and "bech32".

Result:
"address"    (string) The new bitcoin address

Examples:
> bitcoin-cli getnewaddress 
> curl --user myusername --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "getnewaddress", "params": [] }' -H 'content-type: text/plain;' http://127.0.0.1:8332/
```

An optional label argument can be used when getting the new address, which should then appear when using the other commands that you mentioned.

Hope that helps.
