### ISSUE TITLE
[Help] wallet not showing right amount

### ISSUE THREAD

**Issue by GTP95** [bitcoin-dot-org/bitcoin.org#3299]
Hello,
I'm running a public full node using bitcoin core v0.17.1 with the options deprecatedrpc=signrawtransaction deprecatedrpc=accounts addresstype=bech32 (I need this exact version and those options enabled because I will use it for timestamps: https://github.com/opentimestamps/opentimestamps-server) and a wallet with the following addresses:
```
$bitcoin-cli getaddressesbylabel ""
{
  "bc1q0yw68tg43q2cum34uwp895yxt5vpemy3dea8sl": {
    "purpose": "receive"
  },
  "bc1qsag68a2jdjug06atafhu937mfal64jq0se3leh": {
    "purpose": "receive"
  }
}
```
About five hours ago I've sent a fraction of bitcoin from coinbase to the first address and I know that the transaction is confirmed because I've checked on blockchain explorer and there the wallet has the right amount of bitcoin: https://www.blockchain.com/it/btc/address/bc1q0yw68tg43q2cum34uwp895yxt5vpemy3dea8sl.
But if I check on my server the wallet appears to be empty and even without unconfirmed balance:
```
$bitcoin-cli getwalletinfo
{
  "walletname": "",
  "walletversion": 169900,
  "balance": 0.00000000,
  "unconfirmed_balance": 0.00000000,
  "immature_balance": 0.00000000,
  "txcount": 0,
[other fields omitted]
}
```
My questions are:
1) It's possible that the node missed the transaction even if the server never went offline or this indicates a configuration error?
2) What should I do to let the wallet know the right balance? (I'm using the cli)
3) If I have to stop the node and restart it using the rescan option, is there a way to know from bitcoin-cli when it has finished scanning the blockchain?

Thanks for your help and sorry if the question is trivial, but it's my first time using bitcoin and I want to get it right.

**Comment by wbnns** [comment]
@GTP95 

Hello, taking a cursory look at what you've described, would recommend that you run `getblockchaininfo` to confirm that your node is all caught up.

If that doesn't work, please consider joining one of the following [developer communities](https://bitcoin.org/en/development#dev-communities) where someone may be able to coordinate with you more closely and provide assistance. We tend to reserve this particular repository for issues specifically related to the operation of the website.

Hope this helps.

**Comment by GTP95** [comment]
Thanks, I will try to ask on bitcoin stack exchange.

**Comment by GTP95** [comment]
Turned out to be opentimestamp server that somehow prevented the wallet to see the transaction: after stopping and restarting it the wallet had the right amount. I'm opening an issue on opentimestamps' repo, thanks for your help

**Comment by wbnns** [comment]
@GTP95 

Thanks for the update, glad you were able to pinpoint the issue. Nice job figuring it out. 👍
