### ISSUE TITLE
Donate modal doesn't load BTC/USD rates

### ISSUE THREAD

**Issue by Cobra-Bitcoin** [bitcoin-dot-org/bitcoin.org#3303]
The donation modal isn't loading the BTC/USD rates. Looks like there's something wrong with the API we're using to get the rates.

**Comment by wbnns** [comment]
Looks like the issue is that the API (BitcoinAverage) is no longer providing free, public access:

```
curl https://apiv2.bitcoinaverage.com/indices/global/ticker/short\?crypto\=BTC\&fiat\=USD`

Unauthenticated requests are not allowed. Take out a new plan or start a free trial at https://pro.bitcoinaverage.com
```
