### ISSUE TITLE
Whitepaper in Hindi Language

### ISSUE THREAD

**Issue by BlockBitMedia** [bitcoin-dot-org/bitcoin.org#3312]
Hello, 

I have translated bitcoin whitepaper in hindi and uploaded in https://github.com/wbnns/bitcoinwhitepaper

But I can't see that updated in main website, please note that the translation I did is not google translation. 

Thank you.

**Comment by wbnns** [comment]
@BlockBitMedia 

Hello, thank you for the translation - it's currently being reviewed. Once that is complete, assuming there are no issues, we'll add it to the site.

**Comment by wbnns** [comment]
Opened #3339 to add the translation.

@BlockBitMedia Thanks again.
