### ISSUE TITLE
Please remove bitstamp

### ISSUE THREAD

**Issue by kokole** [bitcoin-dot-org/bitcoin.org#3328]
They asked for a lot of information which I gave to them. They checked and said that the KYC procedure is done.
When trying to withdraw, they locked it and started asking even more questions about things that shouldn't even be of importance to them, like asking for parts of the conversation where I talk with my client (???)

I'm not the only one with such an experience, there are lots of others.

**Comment by wbnns** [comment]
@kokole 

Thank you for letting us know. We'll record your feedback alongside our reviews of the exchange.
