### ISSUE TITLE
My involvement with Bitcoin.org

### ISSUE THREAD

**Issue by Cobra-Bitcoin** [bitcoin-dot-org/Bitcoin.org#3332]
First of all, happy halving to everyone!

I just want to inform that I will gradually be reducing my involvement in Bitcoin.org this year, it won't happen instantly but hopefully by the end of the year, I won't be around anymore. Over the years, I'm glad to have helped contribute to a project that has let so many millions of people learn about Bitcoin. It's really a massive honour. The domain name will be left in trusted hands, I have a few people in mind already. Alternatively, if anyone knows of any individuals or organisations that would be good, feel free to suggest (either here, or privately -- just DM me on Twitter). Ultimately, trust is very hard to measure, but I plan to be thorough and meticulous here and find the right people.

I guess for a lot of people, this will probably be some sort of relief. I can't say I've gotten along well with everyone, and some people have questioned my judgement. Hopefully whoever comes after me doesn't get sucked into drama as easily as I sometimes did (though that's also largely a product of being around in pretty dramatic times). Bitcoin.org really is an amazing resource, and we need to continue working on it and keep improving it. With Bitcoin being as complicated as it is for new people to understand, sites like Bitcoin.org are key to getting more mainstream adoption. Especially in avoiding getting Bitcoin labelled as some get rich quick scheme.

If we've had any collaboration over the years; I appreciate your contributions, and have learned a lot from many of you. I wish everyone good luck and success. Thank you. No doubt Bitcoin will keep succeeding and reaching new milestones with such a great community behind it.

**Comment by mateusnds** [comment]
Hey Cobra, I hope everything is fine with you.
I wish you success wherever you go.

**Comment by jmcorgan** [comment]
I suggest Bitcoin Optech (bitcoinops.org).

"The Bitcoin Operations Technology Group (Optech) works to bring the best open source technologies and techniques to Bitcoin-using businesses in order to lower costs and improve customer experiences."

**Comment by Cobra-Bitcoin** [comment]
@jmcorgan Unfortunately, the people behind Bitcoin Optech have smeared Bitcoin.org in the past, and some work on an alternative competing site, so it wouldn't be wise to involve them.

**Comment by harding** [comment]
Happy halving!

What about giving the domain to its primary contributors over the years?  E.g., by commit count, three people made almost 60% of all non-merge commits:

    $ git log --no-merges | grep ^commit | wc -l
    4389

    $ git shortlog -n --no-merges --summary --author=Binns --author=saivann --author=Harding
      1134  Will Binns
      1045  Saivann
       387  David A. Harding

I suspect you'd also find the same three people (perhaps in a different order) at the top of the list when looking at various other metrics, such as most lines added or most hours contributed to the site.

Even if you don't think I should count---despite almost [10 years](https://bitcointalk.org/index.php?action=profile;u=1652) of participation in Bitcoin, over [six years](https://github.com/bitcoin-dot-org/bitcoin.org/pull/393) of [consistent contribution](https://dtrt.org/pubs/) to Bitcoin documentation (including extensive contributions to Bitcoin.org), and no history in all that time of scamming people or other unethical behavior---I think you owe it Saivann and Will to give them a chance to control the site which they've each spent countless hours maintaining on behalf of all Bitcoin users.

(There are several other contributors too who could also be included if you wanted a broad base of domain owners.  For example, I excluded wallet maintainer Craig Watkins from the above list because he only has a few commits, but I know he's contributed significant amounts of time to evaluating wallets and corresponding with their authors---effort that has benefited many novice Bitcoin users.)

**Comment by Cobra-Bitcoin** [comment]
@harding Current active contributors like Will Binns and Craig Watkins are already among the people I had in mind.

Unless some past questionable behaviour is unearthed, it makes the most sense to go with them, but one of the reasons why I created the issue was to get alternatives to the "obvious" choices.

**Comment by AudiobookLinks** [comment]
If ANYTHING you say is true and you no longer agree with the direction Blockstream is taking the Bitcoin Core protocol why not revert Bitcoin.org to promoting actual bitcoin (called Bitcoin Cash now). 

It is a relief you are leaving because you are a liar. You try and play both sides of the debate and end up looking like a liar and idiot.

**Comment by georgedonnelly** [comment]
Let's build a project around mass adoption and mass education, multi-lingual and focused on the developing world / informal economy. It can have a program to guide people towards starting crypto-related businesses that are aimed at adoption and education. me@georgedonnelly.com

**Comment by jlopp** [comment]
Thank you for your efforts over the years, @Cobra-Bitcoin!

**Comment by JavierGonzalez** [comment]
Hello, Cobra!

As I'm sure you know, power corrupts.
And absolute power corrupts absolutely.

And this applies universally to all humans of all races.
You and I included.

Satoshi knew this problem and solved it masterfully.
Byzantine Generals problem addresses this key point.
A decision-making well coordinated in a blockchain, without a central command.

Then, Bitcoin -the solution- is the most secure public consensus mechanism ever built, through hash voting.

From my understanding, I have tried to extend the logic of the Whitepaper by building a confortable web system , where each participant can speak and vote with hash power, totally decentralized and 100% verifiable. Adding BTC+BCH+BSV hashpower, in a truly neutral space. The BMP.

Nobody has used it yet, but it is opensource and production-ready:
https://github.com/JavierGonzalez/BMP

I reused an old domain name to save costs. 
It would be an honor to host it in bitcoin.org as well.

Greetings!

**Comment by ShadowOfHarbringer** [comment]
You should transfer the domain to me.

I cannot be corrupted by either power of money and I always do what I believe in.

Just saying.

**Comment by FieserKiller** [comment]
iirc @gmaxwell wrote recently somewhere that he'd like to run bitcoin.org

**Comment by Cobra-Bitcoin** [comment]
@FieserKiller I doubt anyone would disagree with Greg Maxwell being involved, despite my disagreements with him, he's always been principled. I haven't seen any evidence of your claim though, and I suspect it isn't true and put here just to troll.

**Comment by FieserKiller** [comment]
@Cobra-Bitcoin hey unkind stranger. you literally made me leave my bed (its ~ midsnight here) and scroll through 2 weeks of gmaxwells reddit history to clear my name.
So here is the post i was referring to: https://www.reddit.com/r/btc/comments/gcivdm/btc_is_by_definition_an_altcoin_segwit_is_the/fpcdpcg/?context=3

**Comment by beyourseff** [comment]
@Cobra-Bitcoin Sorry to see you leave, you've been a great member of the community and I wish you all the best in your future endeavors.

I remember the times you'd sporadically drop in the Bitcoin Core #UASF Slack channel and argue with us all about some thing or the other. Good times :)

As for a candidate: I don't have anyone specific in mind who hasn't been mentioned here yet, though I'd urge you to set it up in a way where there'd be multiple parties who'd all have to mutually agree for certain domain actions to be taken.

Though difficult, I trust that your decision will be a good one.

**Comment by Cobra-Bitcoin** [comment]
@FieserKiller Fair enough. Sorry for the accusation, the thread was getting filled with trolls and I interpreted your comment as sarcasm for some reason.

@beyourseff Wish you the best too. Multiple parties is a good idea, I'm not an expert on how that could be set up safely though and in a legally binding way.

**Comment by Megawatt7** [comment]
Hello, you have my utmost respect for providing a proper Bitcoin website over the years.
Please, don't pass it on to Roger Ver.
-Thank you for everything

**Comment by yoa-cl** [comment]
Happy Having! Thanks for all the years you put in. Pass the torch to someone that will make you and the community proud.

**Comment by solsticesolutions** [comment]
I'd like to volunteer to turn the site into a 100% ethereum shill destination.

**Comment by gazhayes** [comment]
Simply redirect it here: https://github.com/bitcoin/bitcoin and the community will sort it out.

**Comment by vcorem** [comment]
@Cobra-Bitcoin thank you for what you did for Bitcoin and for all the effort all those years. Good luck in your future endeavors.

**Comment by Codepadre** [comment]
>  if anyone knows of any individuals or organisations that would be good, feel free to suggest

@Cobra-Bitcoin, please consider Gavin Andresen.

Satoshi Nakamoto left Gavin Andresen as lead developer of Bitcoin when Satoshi departed and Gavin was Satoshi’s right-hand man.

**Comment by FreeTrade** [comment]
@Cobra-Bitcoin , you cite "getting more mainstream adoption" as a primary concern. 

I observed a newbie trying to start using Bitcoin recently. He first visited bitcoin.org - impressed I think by the authority of the '.org' - he clicked on 'select a wallet' and 'new user', only to be baffled to point of helplessness by the criteria and features questions - they offered options such as 'Validation', 'Bech32' and 'Lightning'. I cringed while newbie left the site to pick another option from Google. 

You're making the right decision to hand the site over to someone who'll be able to orient the site more towards mainstream adoption.

I suggest Roger Ver. Even his detractors would admit that he has worked tirelessly and unwaveringly for Bitcoin adoption. He is ideologically committed to it and least corruptable person in the Bitcoin space.

**Comment by lukechilds** [comment]
I'm really glad you're doing this @Cobra-Bitcoin. While I've not always agreed with your views, I've always respected the fact that you never abused your control over the domain to push your own agenda.

I think the fact that you're now handing it over shows great character. The ability to put the greater good of a project over one's own ego is not a quality that everyone possesses.

Could I suggest maybe transferring control of the domain over to a trusted organisation who have an interest in seeing Bitcoin succeed but aren't directly involved with the politics. Ideally with the condition that for them to make any DNS changes, they should have agreement from m-of-n people. The n people could be selected by you or the community as a whole.

I think @EFForg or @linuxfoundation could be good candidates for this.

**Comment by CoxxA** [comment]
Hey Cobra, I wish you all the best in the future

**Comment by jdabs** [comment]
@Cobra-Bitcoin Thank you for your work and guidance through so many years. You have a kind of patience that I could only aspire to.

**Comment by TheBlueMatt** [comment]
First of all, thanks @Cobra-Bitcoin for all the work that's gone into the site. I know we've disagreed a time or two, but in spite of all the drama, the site has always remained a robust place for people to learn about Bitcoin and get started.

A few notes on succession:

> I think @EFForg or @linuxfoundation could be good candidates for this.

Sadly, linux foundation is a super political organization, which doesn't seem like a great home for something like this. EFF may be better, but adjudicating nuanced political debates about super-deep Bitcoin topics seems, like, way out of their wheelhouse. Ultimately, with most orgs I think we'll see either a) external orgs that are out of their depth trying to manage a Bitcoin educational resource or b) Bitcoin industry orgs that tend to have some kind of adgenda, or at least are perceived as such.

I think an individual (or very small group of individuals) ultimately makes the most sense, especially with the setup that it has had where its an open source project that anyone can contribute to, but where disputes are ultimately decided by someone who's character is respected, even if there are disagreements about the decision makes the most sense. Who that is I don't know, but regular contributors seems like a reasonable metric.

**Comment by panicfomo** [comment]
Thank you for your service, Cobra!

**Comment by MrHash** [comment]
Thank you for holding that domain name away from people with bad intentions over the years. I request that in the transfer of the domain ownership that the donations wallet finally be converted to a multisig as well.

**Comment by AudioBookReviews** [comment]
> Thank you for holding that domain name away from people with bad intentions over the years. 

In what way has Cobra's intentions not been 100% negative for Bitcoin? He has helped dismantle the original Bitcoin experiment (peer-to-peer digital cash) and replace it with a banking friendly "settlement" layer. My guess is the account is controlled by @gmaxwell or Luke Jr. No matter what the person controlling the .org has been a net negative for Bitcoin.

**Comment by gazhayes** [comment]
> He has helped dismantle the original Bitcoin experiment (peer-to-peer digital cash) and replace it with a banking friendly "settlement" layer. 

Arguments like this fail to consider Bitcoin's security model - the State is the adversary. There is only one metric that matters when it comes to the sustainability of Bitcoin forks: which one is most resilient to State attack. For example, *when* they criminalise mining, the larger your mining operation the easier you are to find and the earlier you go to jail. Mining naturally migrates to the edges when the network comes under attack, distributing the risk the same way the Bittorrent protocol does.

**Comment by BitcoinArbitor** [comment]
> 
> 
> > Thank you for holding that domain name away from people with bad intentions over the years.
> 
> In what way has Cobra's intentions not been 100% negative for Bitcoin? He has helped dismantle the original Bitcoin experiment (peer-to-peer digital cash) and replace it with a banking friendly "settlement" layer. My guess is the account is controlled by @gmaxwell or Luke Jr. No matter what the person controlling the .org has been a net negative for Bitcoin.

bcash trolls should remember their place is on twitter and reddit. enjoy your path to irrelevance along with Craig Wright, Gavin Anderson and Mike Hearn.

**Comment by nelruk** [comment]
Thank you for all the hard work you put @Cobra-Bitcoin all these years
Only hope the best for you!

**Comment by Cobra-Bitcoin** [comment]
Really appreciate the positive comments, thanks guys :)

**Comment by echallenge** [comment]
Looking for something completely different,, here is a idea..  Will donate some other great .org assets like Connectivity.org, Interoperability.org, Training.org, Entrepreneurs.org into a trust that is created to build and execution a plan put together by its members to form an accountable impact program using the URL's as the central point of action and value.  Using the CONTRIB (.com) model/tools to transparently set, create and distribute the value of the asset across is members while turning the URL into a Bitcoin DAO.   Serving the Bitcoin community first with a focus on impact programs impacting the world through blockchain and Bitcoin utility.  Just a wild idea wanted to put that is executable and different in thinking..  THE URL should be its own self running smart entity, we can help..... peace..chad   chad@ecorp.com

**Comment by mateusnds** [comment]
ok
