### ISSUE TITLE
Choosing optimal Hebrew translation of Bitcoin paper

### ISSUE THREAD

**Issue by wbnns** [bitcoin-dot-org/bitcoin.org#3336]
Context: #3185 

It seems the sentiment in #3185 was that @MeniRosenfeld 's translation should be the default. @ZeevBB initially translated the paper, which we added to the site (prior to the suggested change). There was some discussion that perhaps both versions could be made available to users.

After drafting this (rough draft screen shot to follow), we feel it would be ideal to have one Hebrew translation:

<img width="788" alt="image" src="https://user-images.githubusercontent.com/1130872/82044824-58696700-96ae-11ea-919f-57aa0a160df6.png">

Otherwise, it's plausible that in the future a 3rd or 4th translator will want to add their version, which would be a potentially confusing UX for new users wishing to read the paper in Hebrew - "Which one should I read?", "Which one is the most accurate?" - these are already questions when there are two.

This issue is to determine which Hebrew translation should be used (currently, Meni or Zeev's). An additional idea, in case helpful, might be to combine both translations to create a distilled Hebrew translation of the paper, in case anyone is interested in pursuing that. Otherwise, let's confirm here what the preference is.

Cc: @MeniRosenfeld, @ZeevBB, @sha-265, @shesek

**Comment by ZeevBB** [comment]
Any decision that works best for bitcoin.org is fine with me.

**Comment by sha-265** [comment]
As I mentioned before, I would go with Meni's version.

**Comment by wbnns** [comment]
Ok, let's go with Meni's, then. That said, Ze'ev has been a great help on the overall translation of the site into Hebrew (in addition to his version of the Bitcoin paper) as well as helping us maintain quality assurance with regard to the display of the site in RTL. Cheers.
