### ISSUE TITLE
Ensure RTL languages display properly across site

### ISSUE THREAD

**Issue by wbnns** [bitcoin-dot-org/Bitcoin.org#3337]
There are currently some inconsistencies on the site where-in languages that read from right to left (RTL), are not displaying properly. This issue is for tracking various problems that have been identified, to ensure that they are resolved.

## Examples

![image](https://user-images.githubusercontent.com/1130872/82046217-c9aa1980-96b0-11ea-8fd2-413a66c49dca.png)

![image](https://user-images.githubusercontent.com/1130872/82046256-d9296280-96b0-11ea-882e-104bfe0dcd2c.png)

![image](https://user-images.githubusercontent.com/1130872/82046285-e6dee800-96b0-11ea-902f-1505bd48be91.png)

![image](https://user-images.githubusercontent.com/1130872/82046360-037b2000-96b1-11ea-844b-9a0fd0640d76.png)

![image](https://user-images.githubusercontent.com/1130872/82046402-17268680-96b1-11ea-8646-ba1d530e780d.png)

Cc: @alexcherman, @ZeevBB

**Comment by wbnns** [comment]
Related: #3375

**Comment by Daniel-Leedan** [comment]
It seems that all the RTL issues have been fixed. Is there anything open that needs help?

**Comment by ZeevBB** [comment]
It looks good

**Comment by Komodorpudel** [comment]
@Cobra-Bitcoin You can close this.
