### ISSUE TITLE
Adding a crypto-to-crypto only category to the Exchanges page

### ISSUE THREAD

**Issue by wbnns** [bitcoin-dot-org/bitcoin.org#3357]
There are a growing number of crypto-to-crypto (C2C) only exchanges that do not serve as fiat-to-crypto gateways. We should consider whether or not we should add a category to the Exchanges page for these types of platforms.

**Comment by rzel** [comment]
Please, please do this! I have a crypto-to-crypto exchange (although in the future it may also have fiat-to-crypto) and would very much like to be listed.

A huge number of people are mining the newer coins and swapping into Bitcoin, and sometimes swapping Bitcoin into the newer coins. 

The bitcoin.org page, as it is, only caters to fiat-to-crypto, which is fairly limited.

I highly recommend this proposal, as there is huge interest in crypto-to-crypto exchanges.

**Comment by Cobra-Bitcoin** [comment]
@rzel We should only really be concerned with fiat to Bitcoin onboarding. By virtue of being on the site, it's reasonable to assume the user is only interested about learning and acquiring Bitcoin, not other crypto, so having crypto-to-crypto exchanges appearing on the list of exchanges wouldn't serve the interests of the majority of the visitors IMO. I think the people mining newer coins and swapping into Bitcoin can figure out the relevant exchanges themselves.
