### ISSUE TITLE
Bitcoin Core issue to join the network

### ISSUE THREAD

**Issue by yaz94** [bitcoin-dot-org/bitcoin.org#3363]
I am running a full-node on my pc. I synchronized the full blockchain with the client, in order to see all the transactions fired by nodes. but, I still have a problem to join the network through https://bitnodes.io, after allowing the inbound and outbound on my firewall, adding the internal and external port (8333) to the option Port Forwarding on my Router and chose the device which runs the Bitcoin client with the same IP address through the option DHCP on my router too. 
But, It still not joining the network using bitnodes????

**Comment by odarboe** [comment]
@yaz94 Have you checked [Test connection page](https://bitcoin.org/en/full-node#testing-connections). 
Search for

**Comment by yaz94** [comment]
Yeah, it is unreachable !!

**Comment by odarboe** [comment]
Checkout this thread  https://www.reddit.com/r/Bitcoin/comments/83ncbn/why_my_node_is_not_showing_on_bitcoin_nodes_live/

**Comment by yaz94** [comment]
@odarboe 
the link sent by you mentioned that ((If you configure something (like port forwarding or possibly UPnP) on the router, then it knows what computer and port to forward it to (e.g. your IP address of your computer on your LAN and port 8333).))

and I already did it, by adding the port 8333 and my IP address (my PC local IP) to the router in order to only sent the inbound to my PC!!

**Comment by odarboe** [comment]
@yaz94  Run these commands to check your connection peers and get the latest info on the node status and post it here.
> bitcoin-cli getconnectioncount
> bitcoin-cli getblockchaininfo
> bitcoin-cli getnetworkinfo

**Comment by yaz94** [comment]
23:11:14
￼
getconnectioncount


23:11:14
￼
10


23:11:30
￼
getblockchaininfo


23:11:30
￼
{
  "chain": "main",
  "blocks": 632378,
  "headers": 632378,
  "bestblockhash": "00000000000000000008018cbb35dc7c3059369af618bcec7235a0c1ae7de6ee",
  "difficulty": 15138043247082.88,
  "mediantime": 1590873020,
  "verificationprogress": 0.9999911070138023,
  "initialblockdownload": false,
  "chainwork": "00000000000000000000000000000000000000000fe55d7b3c36a79af2d17324",
  "size_on_disk": 317847635518,
  "pruned": false,
  "softforks": {
    "bip34": {
      "type": "buried",
      "active": true,
      "height": 227931
    },
    "bip66": {
      "type": "buried",
      "active": true,
      "height": 363725
    },
    "bip65": {
      "type": "buried",
      "active": true,
      "height": 388381
    },
    "csv": {
      "type": "buried",
      "active": true,
      "height": 419328
    },
    "segwit": {
      "type": "buried",
      "active": true,
      "height": 481824
    }
  },
  "warnings": ""
}


23:11:48
￼
getnetworkinfo


23:11:48
￼
{
  "version": 190100,
  "subversion": "/Satoshi:0.19.1/",
  "protocolversion": 70015,
  "localservices": "0000000000000409",
  "localservicesnames": [
    "NETWORK",
    "WITNESS",
    "NETWORK_LIMITED"
  ],
  "localrelay": true,
  "timeoffset": 0,
  "networkactive": true,
  "connections": 10,
  "networks": [
    {
      "name": "ipv4",
      "limited": false,
      "reachable": true,
      "proxy": "",
      "proxy_randomize_credentials": false
    },
    {
      "name": "ipv6",
      "limited": false,
      "reachable": true,
      "proxy": "",
      "proxy_randomize_credentials": false
    },
    {
      "name": "onion",
      "limited": true,
      "reachable": false,
      "proxy": "",
      "proxy_randomize_credentials": false
    }
  ],
  "relayfee": 0.00001000,
  "incrementalfee": 0.00001000,
  "localaddresses": [
    {
      "address": "92.14.132.134",
      "port": 8333,
      "score": 3
    }
  ],
  "warnings": ""
}

**Comment by odarboe** [comment]
@yaz94 we can observe that you are connected to the network with 10 peers. To confirm if the port 8333 is properly configured run this command and check the status response.
> curl -H "Accept: application/json; indent=4" https://bitnodes.io/api/v1/nodes/<ADDRESS>-<PORT>/

**Comment by yaz94** [comment]
@odarboe 
I am sorry my friend, I tried several times but it stills unreachable!!
the 10 that your are talking about are the outbound when the inbound is equal to 0, which must be greater than 0, in order to be reachable

**Comment by odarboe** [comment]
@yaz94 have you done all the three steps [enabling the inbound connection](https://bitcoin.org/en/full-node#enabling-connections) ?

**Comment by yaz94** [comment]
@odarboe 
yup, i did them all the DHCP,port Forwarding and Firewall steps

**Comment by odarboe** [comment]
@yaz94 Your node does not need to appear on bitnodes.io to be functional. Your node will automatically connect to peers and sync to the blockchain. That is why you can see the latest mined blocks. This means you have already joined the network. To see more details about your peers run:
> bitcoin-cli getpeerinfo.

This information is what matters when it comes to joining the network. But for it to appear on the bitnodes.io is not required. Since your have done all the steps may be try restarting the node and wait for a while to see if your node will appear on the live map.

**Comment by yaz94** [comment]
@odarboe 
I think what you are saying is logical. As the commands applied on the GUI used before are getting back with info about peers, blocks..etc.

The last question, how can I get the all transactions or observe them live through bitcoin core, as I become a full-node?

**Comment by odarboe** [comment]
You can get some stats on[ bitcoincore documentation](https://bitcoincore.org/en/doc/0.19.0/rpc/blockchain/getchaintxstats/). There are many commands you can run to get live details stats from the red section highlighted.
![image](https://user-images.githubusercontent.com/1871493/83353258-88bd3080-a351-11ea-82f2-bfdff69fdce0.png)
You can also see the[ documentation in bitcoin.org ](https://developer.bitcoin.org/reference/rpc/index.html)

**Comment by odarboe** [comment]
You can get the 10 most recent transaction with 
> bitcoin-cli listtransactions

**Comment by yaz94** [comment]
15:23:27 listtransactions

[
]


is empty ??

**Comment by odarboe** [comment]
Check the documentation. Try this 
> bitcoin-cli listtransactions "*" 20 100

**Comment by yaz94** [comment]
yeah, i checked different commands to get info about transactions, it is getting me back with empty brackets !!

**Comment by odarboe** [comment]
Oh right! the transactions correspond to your wallet transactions. Since you have not made any we are getting an empty result.

**Comment by yaz94** [comment]
Ok, So I think there was a misunderstanding, what i meant is, how to see the transactions participated by other nodes (not mine) ?

**Comment by odarboe** [comment]
> bitcoin-cli getrawmempool true
> bitcoin-cli getmempoolinfo

**Comment by yaz94** [comment]
yeah, that what I was looking for, through the command (getrawmempool true).

Many thanks @odarboe for your time and support.
