### ISSUE TITLE
BRD iOS wallet source code is out of sync with App Store

### ISSUE THREAD

**Issue by wbnns** [bitcoin-dot-org/bitcoin.org#3366]
We noted that [BRD wallet](https://bitcoin.org/en/wallets/mobile/ios/brd/?step=5&platform=ios)'s [source code](https://github.com/breadwallet/breadwallet-ios) seems to have fallen out of sync with the release that's currently available in the [App Store](https://apps.apple.com/app/breadwallet/id885251393).

The most recent release in their GitHub repository is 4.0, but in the App Store there have been approximately 9 releases since 4.0, where the current release is now 4.3.1.

Cc: @crwatkins, @samuraisam, @jmacwhyte

**Comment by wbnns** [comment]
We've reached out to BRD for further clarification on this.

**Comment by samuraisam** [comment]
We push our code to the `release/*` branches with every release. You can see 4.3.1 here on our branches list: https://github.com/breadwallet/breadwallet-ios/branches

I will remind the team to remember to push release branches to master as well.

**Comment by wbnns** [comment]
@samuraisam 

Great, thanks for joining the thread to clarify. We'll close the issue. Cheers.
