### ISSUE TITLE
Reconsider listing of Armory wallet

### ISSUE THREAD

**Issue by wbnns** [bitcoin-dot-org/bitcoin.org#3367]
The [Armory wallet](https://bitcoin.org/en/wallets/desktop/linux/armory/?step=5&platform=linux) [source code](https://github.com/goatpig/BitcoinArmory) hasn't been updated in almost 2 1/2 years, and the link to the [Support Portal](https://support.bitcoinarmory.com/) on their website is broken (the support site is down).

Based on this, we feel we should reconsider the listing.

Cc: @crwatkins

**Comment by crwatkins** [comment]
There is quite active development happening on the [development branch](https://github.com/goatpig/BitcoinArmory/tree/dev). Version 0.97 [is expected this summer](https://bitcointalk.org/index.php?topic=5088934.msg54530603#msg54530603).  

@wbnns It is  [highly regretful](https://github.com/bitcoin-dot-org/bitcoin.org/pull/1301#issuecomment-220414875) that the Support Portal you mention is on a confusing unofficial site that has not been used for this project for a few years now (bitcoin.org points to the correct site).

There is a fairly active user community and as far as I can tell the wallet meets all of our current criteria, so  I don't see any reason to reconsider the listing.

**Comment by wbnns** [comment]
@crwatkins 

Ok, thanks for the info.

**Comment by wbnns** [comment]
Closing, and have made a note to revisit this later in the year.
