### ISSUE TITLE
I am notr computer sayy and need phone helop to send money

### ISSUE THREAD

**Issue by ralphmorgan** [bitcoin-dot-org/Bitcoin.org#3380]

**Comment by ralphmorgan** [comment]
Why aren't my coins showing up in my account?  They were taken by moonpay as instructed. I need then in my account immediately.

THIS IS AN EMERGENCY 🚨



Sent by iPhone X AT&T

________________________________

**Comment by wbnns** [comment]
@ralphmorgan 

If you're having an issue with a particular wallet and/or service provider, we'd recommend you reach out to their support team(s) for assistance. We most likely wouldn't have any special/proprietary insight into their platform(s) to be able to assist.
