### ISSUE TITLE
Regarding Will Binns

### ISSUE THREAD

**Issue by Cobra-Bitcoin** [bitcoin-dot-org/bitcoin.org#3397]
I have removed Will Binns as the site's maintainer, during a conversation on Twitter he had claimed that his work contributing to bitcoin.org conferred on him more authority than what I had agreed with him. I won't engage with him beyond attempting to retrieve the community's donations from wallets he has control over. The exchange with him is recorded below. If you have ongoing discussions with him, please reach out to me and I will take care of it.

This may seem harsh, but any further communication with him risks putting this project in an unfortunate situation. So I had to be brisk and terminate his relationship with us. I'll be taking over the day-to-day activities on the site more actively from now on; if any contributors or translators are in any group chats with him, please make alternative groups so you can continue work on the site.

<img width="523" alt="Screenshot 2020-06-24 at 16 04 01" src="https://user-images.githubusercontent.com/12899428/85584513-7fb53b80-b63f-11ea-8b20-09f96a90cd21.png">
<img width="506" alt="Screenshot 2020-06-24 at 16 04 16" src="https://user-images.githubusercontent.com/12899428/85584535-83e15900-b63f-11ea-9b8d-a6f754170afa.png">
<img width="570" alt="Screenshot 2020-06-24 at 16 04 38" src="https://user-images.githubusercontent.com/12899428/85584551-893ea380-b63f-11ea-84bd-669e7cff8994.png">
<img width="555" alt="Screenshot 2020-06-24 at 16 04 55" src="https://user-images.githubusercontent.com/12899428/85584565-8d6ac100-b63f-11ea-8e5d-68060baaef5e.png">
<img width="567" alt="Screenshot 2020-06-24 at 16 05 07" src="https://user-images.githubusercontent.com/12899428/85584581-8fcd1b00-b63f-11ea-884c-66983aae3ee7.png">
<img width="565" alt="Screenshot 2020-06-24 at 16 05 25" src="https://user-images.githubusercontent.com/12899428/85584599-93f93880-b63f-11ea-8a76-8c7c189b7ccf.png">
<img width="561" alt="Screenshot 2020-06-24 at 16 05 39" src="https://user-images.githubusercontent.com/12899428/85584626-98bdec80-b63f-11ea-9994-c79775c13569.png">
<img width="566" alt="Screenshot 2020-06-24 at 16 05 52" src="https://user-images.githubusercontent.com/12899428/85584649-9bb8dd00-b63f-11ea-9fbb-97fc614a3ce9.png">
<img width="566" alt="Screenshot 2020-06-24 at 16 06 02" src="https://user-images.githubusercontent.com/12899428/85584657-9f4c6400-b63f-11ea-9ea8-450473769dce.png">

**Comment by matthewlilley** [comment]
Sherlock holmes, you saw this one coming from a mile off, even with the camouflage speak, clarity is everything.

**Comment by Cobra-Bitcoin** [comment]
The nerve of this guy is hilarious; to propose I set up a vehicle so I can have "potential return on any success". He would have presumably given me minority control in his company, and then go on to claim his company owned the site outright. When people attempt to muddy the waters in this way, it's important to be clear, and since he wasn't backing down, he had to go. I don't know what he'll do, but I imagine he'll go down the path of court proceedings, and waste hundreds of thousands of dollars suing to take something from someone who he doesn't even know, nor have any contractual agreements with. Beyond ridiculous the lengths some people will go too to make a buck.

**Comment by achow101** [comment]
The end of the message in the 2nd screenshot is cut off. Can you please post what occurred in between the 2nd and 3rd screenshots?

**Comment by Cobra-Bitcoin** [comment]
@achow101 
<img width="494" alt="Screenshot 2020-06-24 at 21 04 34" src="https://user-images.githubusercontent.com/12899428/85622177-bf434e00-b666-11ea-8a36-49487a6d7713.png">

**Comment by harding** [comment]
> Beyond ridiculous the lengths some people will go too to make a buck.

I've been interacting with Will Binns for over six years now, first on Bitcoin.org and later as coworkers.  We haven't always gotten along, but I've never seen him try to scam anyone.  Quite the reverse---I've seen him selflessly contribute to this project and others for no tangible return. I don't know what's happening in that conversation and I understand the need to be clear about who has what rights, but I don't think a single confused conversation warrants the character assassination of a long-time contributor to multiple open source documentation projects.

**Comment by Cobra-Bitcoin** [comment]
@harding I interpret attempting to muddy the waters of ownership over the site as a scam, just like you would feel you got scammed if a company managing property on your behalf tried to insinuate they have some ownership stake in said property when none had ever been agreed. Now imagine such a company goes and claims rightful use of your property is "illegal" and you have "compromised" the property. The facts are clear: I never got into any deals with Will Binns regarding ownership of bitcoin.org, and you can clearly see from his exchanges with me and his subsequent attempts to characterise my actions as "illegal" that he is insinuating I did, which is a **lie**, and **a scam**.

**Comment by harding** [comment]
@Cobra-Bitcoin I regret that I didn't see the issue @wbnns created before making my own post here.  It would still surprise me if Binns is trying to gain control of Bitcoin.org for his own financial benefit (rather than out of some belief that he'd be better at managing it than you or others).  That said, if he was indeed planning to use legal trickery to gain control of the site for whatever reason, I'd agree that's a scam.

**Comment by wbinns** [comment]
@harding 

I wasn't.

**Comment by junderw** [comment]
No one asking for my two cents, I know.

But in regards to the conversation screenshots posted: Cobra is in the right.

In regards to the Github actions, issues, comments and whatnot: Cobra is overreacting. Will is reacting poorly to Cobra's overreacting.

So in summary, my thoughts on what is going on and should be done:

1. bitcoin org site is not a monolith of truth. Anything downloaded from the site should be verified through PGP.
2. Cobra owns the site. That's a fact, regardless on how much work someone else puts into the site, Cobra owns the domain and gets final say on who can update it. If Cobra says "you do not have partial ownership in the site" arguing the opposite is not productive. If you are upset about it, leave the project and let Cobra pick up the slack.
3. "People who live in glass houses shall not cast stones." While I agree that Will's words in the chat were borderline iffy, there was a time when Cobra made some statements on twitter that had a large number of people in the community thinking Cobra was going to do something unsavory with the domain. While being vigilant is good, distrusting people whose work has directly benefited you without concrete evidence (not just "feelings") of misconduct is not good. Though, the exception to this is reminding everyone of number 1 (don't trust bitcoin org as a beacon of truth to begin with) should not be taken personally by anyone involved.
4. Complete ban of Will from even commenting on issues is overkill. He should at the very least be able to access the repo as any other random new account.
5. If Will shows that he will be abusive and make tons of childish issues and comments etc. then and only then should he be actively banned. Pre-emptively banning him only serves to create more bad blood.
6. If Cobra has lost trust in Will, remove some privileges, but let him continue contributing. (Surely tensions are high rn and both of you are probably thinking the last thing you want to do is work with / near each other)
7. Will should take mental note of the kind of statements that trigger Cobra's "shady scam" detector and try not to move forward with things or push ideas in a way that will push those buttons.

Surely I've just angered both parties, so I'll take my leave here... but I personally think that even in the most Cobra-centric view of this whole issue, the amount of work Will has done at the very least merits a benefit of a doubt on whether he's trying to "hostile take over". And no, Cobra banning Will does not make the site "compromised."

Perhaps everyone should take a breather for a day, calm down a bit, then recollect tomorrow and discuss how to move forward. (And no, I don't think partial ownership of bitcoin org should be on the table)

**Comment by nopara73** [comment]
Sorry for jumping right to the solution part, but how about locking this issue, giving triage rights, keep no contact for one month and have a conversation after the waters settled and everyone had the time and chance to meditate and evolve his views on the matter?

P.S.: Mandatory Comic Relief:

![b50](https://user-images.githubusercontent.com/9156103/85678796-1a0d9180-b6c9-11ea-976d-305abae1407a.png)

**Comment by wbinns** [comment]
I've [followed up and replied](https://github.com/bitcoin-dot-org/bitcoin.org/issues/3398#issuecomment-649419797) in relation to this issue on #3398.
