### ISSUE TITLE
Using Bitcoin Core on a Macmini and QNAP NAS Error

### ISSUE THREAD

**Issue by NckyDC** [bitcoin-dot-org/bitcoin.org#3401]
Hello,

I would like some help, please.
I decided to run a full bitcoin node. I have a Mac mini server 10.15.5 and a QNAP NAS with 80TB as well as a very fast line.

I installed Bitcoin Core on the Mac Mini and experiencing a few issues.

1 - Why this application is not signed with an Apple certificate? Apple does not recognize. I think it would be beneficial if it did. However, it can still be run by bypassing the security layer of Apple.

2 - When i launch it the first time it asks me to select a directory. I created a BTC volume on the NAS so I can save the ledger in its own dedicated space and it's here that I experience issues.

As soon as I select the directory i get a dialog error.

Error: Cannot obtain a lock on data directory /Volumes/BTC/Bitcoin Core. Bitcoin Core is probably already running.

The folder "blocks" gets created but also is unable to proceed and will quite the application once acknowledged

<img width="410" alt="Screenshot 2020-06-28 at 20 49 57" src="https://user-images.githubusercontent.com/63108238/85956961-291e6900-b981-11ea-9dbe-bf0d2ff45602.png">
.

**Comment by Cobra-Bitcoin** [comment]
You should take this issue to the the Bitcoin Core repository itself: https://github.com/bitcoin/bitcoin.

Closed.
