### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by fulmoblitz** [bitcoin-dot-org/bitcoin.org#3406]
- date: 2020-08-28
  title: "Unchain Convention"
  venue: "Hotel Nizza"
  address: "Elbestraße 10, 60329 Frankfurt am Main"
  city: "Frankfurt"
  country: "Germany"
  link: "https://www.unchain-convention.com/"

**Comment by fulmofulmo** [comment]
The event is a two-day event, August 28th and 29th, 2020.

**Comment by Daniel-Leedan** [comment]
Resolved in #3410

**Comment by Daniel-Leedan** [comment]
Closed by #3410
