### ISSUE TITLE
https://www.blockchain.com/btc/tx/13290114c5e1fe381c707e5f67b246cd0260f5bd24c9a1fc1aed0eab08dd2521

### ISSUE THREAD

**Issue by w3bst3r67** [bitcoin-dot-org/bitcoin.org#3415]
I have sent 0.0126 BTC after fee to my bitcoin.org wallet, but funds have not been received in to the wallet.
the transaction is sitting on the blockchain unspent (hash above in Title}.
I sent the BTC from Crypto.com wallet on the 07/07/2020 to an address (https://www.blockchain.com/btc/address/1AKWvdsoAQC43sBANr9pCnk74nHCdrAvB6), which was saved on Crypto from my last transaction ( which was succesful).

Can someone please help me as I can not afford to lose the money.

**Comment by Cobra-Bitcoin** [comment]
There's no such thing as a bitcoin.org wallet. Maybe you are getting mixed up with something else.

**Comment by w3bst3r67** [comment]
Yeah sorry bitcoincore.org it is




Sent from Samsung Mobile on O2


Get Outlook for Android







On Sun, Jul 12, 2020 at 12:36 PM +0100, "Cøbra" <notifications@github.com> wrote:















Closed #3415.
