### ISSUE TITLE
Add Bitvo to Canadian Exchanges

### ISSUE THREAD

**Issue by 7thsecret** [bitcoin-dot-org/bitcoin.org#3417]
Hello, 

Can you add the Bitvo Exchange [https://bitvo.com/](url) to the Canadian listings? 

I am aware of your review process, and will take care of any issues or questions that may come up. 

Do you require any additional information in the meantime? 

Thank you.

tw

**Comment by Cobra-Bitcoin** [comment]
You can just create a pull request with the change, and it'll get reviewed and possibly merged.
