### ISSUE TITLE
New event (German Bitcoin Week)

### ISSUE THREAD

**Issue by fulmoblitz** [bitcoin-dot-org/Bitcoin.org#3418]
- date: 2020-08-27
  title: "German Bitcoin Week"
  venue: "decentralized"
  address: "various"
  city: "Frankfurt"
  country: "Germany"
  link: "https://bitcoinweek.de/"

**Comment by fulmoblitz** [comment]
The whole event serious is happening over the course of several days from August 27th to September 6th, 2020.

**Comment by Tigerix** [comment]
How is the handling regarding Covid19. Will everyone be wearing a mask?

**Comment by fulmoblitz** [comment]
> How is the handling regarding Covid19. Will everyone be wearing a mask?

The German Bitcoin Week is a collection of events. Each event is organized by a different entity which is solely responsible for the event itself.

All event organizers are asked to adhere to the official Covid-19 rules that will be in effect during the time of the event, e.g. on a municipal, state and national level.

Regarding your question about masks: Some of the events are outdoors. It is currently not mandatory to wear a mask if you're outside. For the events inside, wearing a mask might be mandatory depending on the size of the group and the location.

Please check the event page itself closer to the date for updates regarding Covid-19. When in doubt, contact the organizer of the specific event you're interested in.

Hope this helps a bit.
