### ISSUE TITLE
Contact Bitcoin.org for listing exchange in  https://bitcoin.org/en/exchanges#south-america

### ISSUE THREAD

**Issue by guilleescudero** [bitcoin-dot-org/bitcoin.org#3419]
Hello

I would like a contact to listing a cryptoexchange called cryptomarket who operate in Latinamerica.

I hope not bother with my contact.

Thank you for all work that put in bitcoin.org

Waiting for news.

Guillermo.-

**Comment by Cobra-Bitcoin** [comment]
You can just make a pull request with the change, and if it's appropriate, it will get merged.
