### ISSUE TITLE
Improve UX around removed release binaries

### ISSUE THREAD

**Issue by l33d4n** [bitcoin-dot-org/Bitcoin.org#3467]
The issue also exists on Bitcoin.org,  first published here: https://github.com/bitcoin-core/bitcoincore.org/issues/672  a year ago by @jimpo 

>I needed to run some old versions of Core for backwards compatibility testing with a project and noticed that a number of the Release Announcement pages have broken links. For example, https://bitcoincore.org/en/releases/0.16.0/ links to https://bitcoincore.org/bin/bitcoin-core-0.16.0/
>
>Clearly they have been removed for security reasons https://github.com/bitcoin-core/bitcoincore.org/issues/605
>
>However, this is not obvious or user friendly. I'd suggest changing the release announcement pages to be more clear and to link to the secure minor version of the corresponding release.

Broken links to Bitcoin.org domain:

- https://bitcoin.org/en/release/v0.10.0
- https://bitcoin.org/en/release/v0.9.0
- https://bitcoin.org/en/release/v0.9.1
- https://bitcoin.org/en/release/v0.9.2.1
- https://bitcoin.org/en/release/v0.9.2
- https://bitcoin.org/en/release/v0.9.3
- https://bitcoin.org/en/release/v0.14.0
- https://bitcoin.org/en/release/v0.14.1
- https://bitcoin.org/en/release/v0.14.2
- https://bitcoin.org/en/release/v0.15.0.1
- https://bitcoin.org/en/release/v0.15.0
- https://bitcoin.org/en/release/v0.15.1

Broken links to BitcoinCore domain:

- https://bitcoin.org/en/release/v0.15.0.1
- https://bitcoin.org/en/release/v0.15.0
- https://bitcoin.org/en/release/v0.15.1
- https://bitcoin.org/en/release/v0.16.0
- https://bitcoin.org/en/release/v0.16.1
- https://bitcoin.org/en/release/v0.16.2

As I suggested, I think the solution is to add an explanation before the broken links and cancel them for now.

Anyone have another suggestion how to solve this issue?
What do you think about this kind of change?
![image](https://user-images.githubusercontent.com/8020386/92343891-92e08f00-f0f7-11ea-897f-a749ea74faa1.png)

**Comment by RandyMcMillan** [comment]
Taking a look at this...

**Comment by RandyMcMillan** [comment]
Looks like there are some other issues with this...

![Screen Shot 2021-01-19 at 10 25 37 PM](https://user-images.githubusercontent.com/152159/105123089-768d2f80-5aa5-11eb-9b13-ad5df536cf49.png)

**Comment by l33d4n** [comment]
Thanks! I probably missed it, can you attach a link to this page?

**Comment by RandyMcMillan** [comment]
The error is present on 
https://bitcoin.org/en/release/v0.15.0.1 
https://bitcoin.org/en/release/v0.15.0
etc..

in the left side navigation..

**Comment by l33d4n** [comment]
I'm ready to work on this Issue, it has been open for a long time.

Before I start, is the solution I mentioned above is good enough or maybe you had another idea? @Cobra-Bitcoin

**Comment by Cobra-Bitcoin** [comment]
@l33d4n Good catch on this. I agree that's a good way to fix the issue, with the links crossed out, an explanation, and link to the secure minor version.

Sometimes there are specific reasons for someone to download old versions of Core, but hopefully this will give some clarity to people looking for old versions.

**Comment by l33d4n** [comment]
Thanks for the quick response! I pushed PR with the links crossed out and explanation but I'm not sure how to find the right links to the secure minor versions.
