### ISSUE TITLE
Mac OS X node software update

### ISSUE THREAD

**Issue by michaelptapia** [bitcoin-dot-org/Bitcoin.org#3511]
Hello BTC,

I tried to down load the MacOS X software and I got this? 

Please take a look!

Thanks,

Michael

<img width="802" alt="Screen Shot 2020-10-02 at 9 23 48 AM" src="https://user-images.githubusercontent.com/72271062/94946652-518e9580-0491-11eb-8c41-7a409bf102cd.png">

**Comment by Cobra-Bitcoin** [comment]
Hey, you should take this issue to the Bitcoin Core repo: https://github.com/bitcoin/bitcoin/issues. This repository is just for the bitcoin.org website, not the Bitcoin Core software.
