### ISSUE TITLE
Full Node installation not working for Catalina

### ISSUE THREAD

**Issue by hhdwong** [bitcoin-dot-org/Bitcoin.org#3515]
Mac OS Catalina complains "Bitcoin Core" can't be opened because Apple cannot check it for malicious software. This software needs to be updated.

May I ask you to help me?

Thanks

**Comment by pavlenex** [comment]
Hey @hhdwong, [check out this issue](https://github.com/bitcoin/bitcoin/issues/15774), this is not a Bitcoin Core repository, so please forward your request there :)

**Comment by Cobra-Bitcoin** [comment]
Unfortunately Bitcoin Core has made the choice to let this happen, hopefully they'll fix the issue soon.
