### ISSUE TITLE
I can't open my wallet 

### ISSUE THREAD

**Issue by blackdream1234** [bitcoin-dot-org/Bitcoin.org#3519]
why i can't open my wallet
when i try to open it get this message
**Error: Prune: last wallet synchronisation goes beyond pruned data. You need to -reindex (download the whole blockchain again in case of pruned node)**
please help me

**Comment by Cobra-Bitcoin** [comment]
Take this to the Bitcoin Core repo instead https://github.com/bitcoin/bitcoin.
