### ISSUE TITLE
BANKING CRYPTO

### ISSUE THREAD

**Issue by SyuzannaAvanesyan** [bitcoin-dot-org/Bitcoin.org#3523]
[Join us](https://www.eventbrite.com/e/banking-crypto-tickets-125868254337) for BOTB webinar on Thur, Nov 5th to learn more about the role of banks and financial institutions in shaping the future of crypto!

Free Eventbrite Link: https://www.eventbrite.com/e/banking-crypto-tickets-125868254337

**About this Event**

Cryptocurrencies threaten to disrupt and reinvent the world’s financial system!

Are banks now catching up with the Blockchain technology? Has the traditional banking system been left behind? How is blockchain technology affecting the nature of money and role of central banks? In this webinar, we'll talk about the evolution and market overview of Crypto Banking, key regulatory challenges financial institutions face, the pros and cons of CBDCs and more!

Iconic Holding brings blockchain entrepreneurs, industry experts, and innovators together to discuss the latest market developments and trends, share their expertise and insides about the latest important topics, and explore synergies together!

**TOPIC: BANKING CRYPTO**

**SPEAKER PROFILES**

• Johannes Schmitt - Director of Banking and Payments, Kraken Digital Asset Exchange
• Alexis Hamel - MD solaris Digital Assets
• Oliver von Landsberg-Sadie - Founder and CEO of BCB Group

**MODERATOR**

- Patrick Lowry, CEO, Iconic Holding

AGENDA:

ET 12:00-12:40 Introduction and Panel Discussion
ET 12:40-13:00 Q&A

CET 18:00-18:40 Introduction and Panel Discussion
CET 18:40- 19:00 Q&A

Register today and you will receive a confirmation email containing information about joining the webinar!

We’ve created the Iconic Bar On The Block Webinar series to help people stay up-to-date on the latest market trends! We hope you will be able to join us in our webinar sessions and we look forward to meeting you at our local networking events at a later stage!

**Comment by odarboe** [comment]
Hi @SyuzannaAvanesyan ,
FYI, events are normally submitted in the following format. 
Example [event here](https://github.com/bitcoin-dot-org/Bitcoin.org/issues/3281)
