### ISSUE TITLE
Add White paper translated into Albanian to https://bitcoin.org/en/bitcoin-paper

### ISSUE THREAD

**Issue by TonyXhufi** [bitcoin-dot-org/Bitcoin.org#3548]
Hi there, I recently translated the bitcoin WP into Albanian.
Can you please add it into https://bitcoin.org/en/bitcoin-paper
I am having issues creating a Pull- Request in order to attach the files.
Can you please help
Thanks
Tony

**Comment by jdabs** [comment]
Thanks. What is the issue with creating the PR? 

Are you trying to upload directly on the main repo here?

 https://github.com/bitcoin-dot-org/Bitcoin.org/tree/master/files/bitcoin-paper

**Comment by TonyXhufi** [comment]
thanks for getting back...my understanding is that I need to create a PR in order to upload the WP on the main website, PR is greyed out from my end when I try to create a pull request directly on the master. Let me upload the PDF on the above link see if that works.

**Comment by TonyXhufi** [comment]
upload is disabled on the above link too...

**Comment by TonyXhufi** [comment]
[bitcoin_al.pdf](https://github.com/bitcoin-dot-org/Bitcoin.org/files/5726900/bitcoin_al.pdf)
here is the file that need to be uploaded

**Comment by jdabs** [comment]
Thanks, maybe the maintainers / @wbnns  can speak to the lockdown of the PR on your side.

I saw that the link I sent was disabled for uploads and I thought you were stuck there, but it sounds like you tried a PR from your own fork too. 

The translation looks nice.

**Comment by TonyXhufi** [comment]
Thanks...@wbnns advised to raise an issue here, please let me know how to progress

**Comment by jdabs** [comment]
@Cobra-Bitcoin

**Comment by TonyXhufi** [comment]
@Cobra-Bitcoin can you please assist with adding the recent translated WP on the website. I'm having issues creating a pull request.
@jdabs what is the process of becoming a contributor and helping the community...happy to explore further

**Comment by Cobra-Bitcoin** [comment]
@TonyXhufi Don't worry, I'll create the PR for you with the new translated file in it. Just keep your fork up on your Github.

**Comment by TonyXhufi** [comment]
@Cobra-Bitcoin ok cool many thanks for your help and assistance T

**Comment by TonyXhufi** [comment]
@Cobra-Bitcoin any update on this...let me know if you need anything from me

**Comment by Cobra-Bitcoin** [comment]
OK, I merged it for you https://github.com/bitcoin-dot-org/Bitcoin.org/pull/3592.

Thanks a lot for working on this.
