### ISSUE TITLE
Add Crypto.com into Exchanges

### ISSUE THREAD

**Issue by jack-cryptocom** [bitcoin-dot-org/Bitcoin.org#3550]
Hi Bitcoin.org, I would like to propose adding the Crypto.com website (https://crypto.com/) on https://bitcoin.org/en/exchanges#international to provide users with one more choice

**Comment by jack-cryptocom** [comment]
PR created under #3551

**Comment by Cobra-Bitcoin** [comment]
Has been merged now. Thanks.
