### ISSUE TITLE
Add BitPreço

### ISSUE THREAD

**Issue by HamadaAndre** [bitcoin-dot-org/Bitcoin.org#3557]
Please add BitPreço at Brazil Exchange

Website: https://bitpreco.com

**BitPreço compares and allows you to buy/sell BTC,ETH and USDT there with the best price because we are connected at several exchanges**

It's already at many websites and our CEO was interviewed at **forbes** (https://www.forbes.com.br/forbes-money/2020/11/bitcoin-atinge-maxima-de-2018-e-encosta-nos-r-85-mil-no-brasil-entenda-o-porque/)

https://www.cointradermonitor.com/preco-bitcoin-brasil

https://biscoint.io/buy/btc/brl?amount=1000&isQuote=true

and others.

our social media
https://tecle.me/bitpreco

Thank you

**Comment by Cobra-Bitcoin** [comment]
Thank you. We will consider it.
