### ISSUE TITLE
BLW wallet not maintained

### ISSUE THREAD

**Issue by JijoBose** [bitcoin-dot-org/Bitcoin.org#3558]
Looks like BLW wallet has stopped development and their repository is archived.
https://github.com/btcontract/lnwallet

https://bitcoin.org/en/wallets/mobile/android/blw/

**Comment by crwatkins** [comment]
@JijoBose Thanks for bring this to our attention!   

I've been in contact with @btcontract and he informs me the wallet is back on track, he has removed the repository from archive and a new version release is pending.  We can leave this issue open until we see the new release or feel free to close it when you like.

**Comment by JijoBose** [comment]
I find that their playstore "whats new" changelog says,

"Wallet is deprecated. Please withdraw any funds from hosted channel until Jan 21, 2022."

https://play.google.com/store/apps/details?id=com.lightning.walletapp
