### ISSUE TITLE
Criteria for inclusion of web wallets.

### ISSUE THREAD

**Issue by ghost** [bitcoin-dot-org/Bitcoin.org#356]
I'm seeing requests to add wallets, especially some of the newer M of N style wallets, but I'm concerned that both bitgo and greenaddress are deploying compressed javascript from their own servers. This means that we have to trust the wallet operator regardless of claims of M of N security. 

I think we should assume that a wallet operator will be hacked (from inside or out) and then we asses the impact of this on the user base. For example...
1. Coinbase, They have access to all funds, and therefore the impact is 100%.
2. Blockchain.info, Doesn't have access to all funds. They could steal funds from users as they login, this would be discovered fairly quickly by the community and the likely impact would be less than 1% of users impacted.

The new M of N style wallets are claiming higher security than blockchain.info, however this is not the case. All the wallets I looked at are deploying compressed javascript from their own servers. This makes it difficult to detect if they are working honestly (I am sure they are with the wallets mentioned above but why take the risk.)

So perhaps we should outline the criteria for wallet inclusion and then implementers can meet or exceed that criteria.

Something like...
1. At least 1 Year in operation.
2. All javascript in plain text and easy to read.
3. Javascript deployed from source control i.e. github. Not from private servers.
4. An integrity checker tool. Similar to the one blockchain already has.
5. No private keys stored on the server. 
6. Disallow users from using email/password as login. Users will use the same email password combination with other services and will have there coins stolen that way.
7. A way for users to recover their wallet if the operator goes away. Recovery procedure should be quick and simple.

I'd be interested in hearing other peoples thoughts.

**Comment by syaifudin857** [comment]
Join
