### ISSUE TITLE
Certain strings aren't localized on Choose your wallet page

### ISSUE THREAD

**Issue by pavlenex** [bitcoin-dot-org/Bitcoin.org#3562]
The following strings on the choose-your-wallet need to be localized. I've read through the [FAQ Translation document 
](https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/docs/assisting-with-translations.md#) but couldn't find instructions on how these should be handled. 
```
Legacy Addresses

Most wallets have the ability to send and receive with legacy bitcoin addresses. Legacy addresses start with 1 or 3 (as opposed to starting with bc1). Without legacy address support, you may not be able to receive bitcoin from older wallets or exchanges.
```

```
Experienced user
```
```
control, transparency
```

```
Optional
```

If GitHub is wrong place for reporting this type of problem, let me know.

**Comment by pavlenex** [comment]
cc @Komodorpudel perhaps you know how to handle this?
Unfortunately I stopped using Telegram due to impersonators.

**Comment by Komodorpudel** [comment]
Hey @pavlenex 

I quickly had a look and at least for German it is alright: https://bitcoin.org/de/waehlen-sie-ihre-wallet?step=5
So I guess those strings are available for translation on Transifex.

Which language are we talking about? It could be that (a) those strings are not translated in the specific language yet or (b) the translation content from Transifex wasn't merged via a PR yet.

**Comment by pavlenex** [comment]
@Komodorpudel You're right, the `Legacy Address paragraph` has been translated but not pushed yet, so that's fine.
However 2 strings seem to be missing in DE as well.
![Screenshot from 2021-01-17 16-13-12](https://user-images.githubusercontent.com/36959754/104847196-ebfad380-58de-11eb-880c-2fa16bef6ed7.png)
Here's a [link](https://bitcoin.org/de/waehlen-sie-ihre-wallet?step=3&platform=linux&user=experienced&important=) that shows they're not yet added to German either.

**Comment by Komodorpudel** [comment]
@pavlenex you are right.

However, I cannot even find e.g. the string "experienced user" here:
https://github.com/bitcoin-dot-org/Bitcoin.org/blob/master/_translations/en.yml

Maybe @Cobra-Bitcoin  knows more?

**Comment by Cobra-Bitcoin** [comment]
It seems the string "experienced user" is hardcoded into the layout: https://github.com/bitcoin-dot-org/Bitcoin.org/blob/977c2734c73fe77d4ef1fcd9f4ce3e1aa69b4485/_includes/layout/base/helper-step-2.html.

**Comment by jdabs** [comment]
I believe that switching that hardcoded text to a liquid translate tag would allow access to it. It appears to be working like an alt tag and shouldn't break the js.

**Comment by jdabs** [comment]
It works with the liquid translate tags. I re-used the translate value, so it dropped the "user" word. Logically, it makes more sense to re-use the `wizard-user-experienced` or `wizard-user-new` values here since they are acting as header/titles, but a new tag can also be added on https://github.com/bitcoin-dot-org/Bitcoin.org/blob/master/_translations/en.yml

https://gist.github.com/jdabs/a28d5b8b74c59a7829f2dc503f34247d#file-helper-step-2-html-L33

Pic shows "user" dropped:
![image](https://user-images.githubusercontent.com/6774432/108630552-50a3d380-7433-11eb-991e-4116595f8955.png)

**Comment by Komodorpudel** [comment]
@Cobra-Bitcoin This can be closed as well.
