### ISSUE TITLE
Potential Scammer claiming to work for Bitcoin.org

### ISSUE THREAD

**Issue by benbrooks315** [bitcoin-dot-org/Bitcoin.org#3564]
Hi I have been contacted by a potential Scammer claiming to be working for Bitcoin.org. He said that he is returning money that was converted into Bitcoin that I was stolen from me in a binary options scam.

Do you have such an employee? He wants me to put 2.5% of the money owed to me into a Bitcoin wallet then he will process an API synchronisation.
So bitcoin.org manage any 3rd party wallets?  Also to make a transfer would I need to do a API synchronisation?

Thanks
Ben

**Comment by Cobra-Bitcoin** [comment]
Your suspicion is correct, that's someone trying to scam you, don't trust. 

All the best.
