### ISSUE TITLE
Estonian translation full

### ISSUE THREAD

**Issue by ekukxs** [bitcoin-dot-org/Bitcoin.org#3576]
Hi!

I have translated the Bitcoin whitepaper into Estonian language completely and was wondering if you'd like to publish it.

[Bitcoin_Valge_Paber.pdf](https://github.com/bitcoin-dot-org/Bitcoin.org/files/5890254/Bitcoin_Valge_Paber.pdf)

Take care!

**Comment by ekukxs** [comment]
Sorry for posting it under 'issues' but I couldn't find any other place to contact someone.

**Comment by liigalihtnebtc** [comment]
Ha, I was working on the exact same thing lately and just today completed it. My version: http://liigalihtne.ee/bitcoin_et.pdf.
Haven't understood either, how to add it here.

Hah, ma töötasin täpselt sama asja kallal ja täna sai valmis. http://liigalihtne.ee/bitcoin_et.pdf minu versioon. 
Ei ole ka täpselt aru saanud, kuidas seda lehele võiks saada lisada.

**Comment by ekukxs** [comment]
Korralik huumor, kõik need aastad pole tehtud ja nüüd järsku teeme samal ajal sama asja :D 

Hea töö igatahes!

Ma ei tea, kumb see nüüd "ametlikum" on siis :D

**Comment by liigalihtnebtc** [comment]
Saatsin sulle meili, et äkki kombineerime kahepeale korraliku asja kokku, sinu oma jätaks põhjaks. Käiksin lihstalt natuke üle teksti ja kujunduse.

**Comment by Cobra-Bitcoin** [comment]
Seems we have an Estonia translation pull request already open. Just need somebody to verify the translation is correct, and it will get merged.
