### ISSUE TITLE
Listing on Bitcoin.org

### ISSUE THREAD

**Issue by KatherineWalnut** [bitcoin-dot-org/Bitcoin.org#3579]
Good afternoon!
We are interested in the possibility of adding our service to your listing (https://bitcoin.org/ru/exchanges). Our service https://buycoin.cash/ provides cryptocurrency exchange services.

We have studied all the requirements at https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/docs/adding-exchanges.md
 and are ready to start the procedure.

We started talking to Will Binns, but we know he doesn't work there anymore.

If you need more information about the service, please let us know. Thanks in advance for your reply.

Sincerely, administration of Buycoin.cash. 
buycoin@crpt.trading

**Comment by Cobra-Bitcoin** [comment]
What is your daily volume?

**Comment by KatherineWalnut** [comment]
Thank you for your response. We cannot measure the trading volume because we are not a marketplace. Users cannot place orders. We have a tariff (commission) and rates at which we can buy or sell cryptocurrency from users. We are a cryptocurrency reseller.

**Comment by Lazaroms** [comment]
Very cool

**Comment by Cobra-Bitcoin** [comment]
You are not a large enough or well known exchange to be listed yet. I think some time needs to pass for you to be listed on bitcoin.org. Sorry about that.

**Comment by KatherineWalnut** [comment]
> You are not a large enough or well known exchange to be listed yet. I think some time needs to pass for you to be listed on bitcoin.org. Sorry about that.

Thank you.

**Comment by Lazaroms** [comment]
I'm satoshi Nakamoto, who started this bitcoin story

________________________________
De: KatherineWalnut ***@***.***>
Enviado: segunda-feira, 12 de abril de 2021 08:10
Para: bitcoin-dot-org/Bitcoin.org ***@***.***>
Cc: Lazaroms ***@***.***>; Comment ***@***.***>
Assunto: Re: [bitcoin-dot-org/Bitcoin.org] Listing on Bitcoin.org (#3579)


You are not a large enough or well known exchange to be listed yet. I think some time needs to pass for you to be listed on bitcoin.org. Sorry about that.

Thank you.

**Comment by Lazaroms** [comment]
You are not a large enough or well known exchange to be listed yet. I think some time needs to pass for you to be listed on bitcoin.org. Sorry about that
________________________________
De: Cøbra ***@***.***>
Enviado: sexta-feira, 9 de abril de 2021 14:06
Para: bitcoin-dot-org/Bitcoin.org ***@***.***>
Cc: Lazaroms ***@***.***>; Comment ***@***.***>
Assunto: Re: [bitcoin-dot-org/Bitcoin.org] Listing on Bitcoin.org (#3579)


You are not a large enough or well known exchange to be listed yet. I think some time needs to pass for you to be listed on bitcoin.org. Sorry about that.
