### ISSUE TITLE
BlockchainWave - 2021

### ISSUE THREAD

**Issue by Blockchainwave** [bitcoin-dot-org/Bitcoin.org#3587]
08.04.2021
      title: "Blockchain Wave 2021"
      venue: "Rixos Downtown Antalya"
      address: "Meltem, Sakıp Sabancı Blv. No:3, 07050 Konyaaltı/Antalya"
      city: "Antalya"
      country: "Turkey"
      link: "https://blockchainwave.org/en"

**Comment by Blockchainwave** [comment]
Hi, can you tell me the reason for the closure11.02.2021, 17:21, "Cøbra" <notifications@github.com>:
Closed #3587.

**Comment by Cobra-Bitcoin** [comment]
It was closed because we're removing the events page soon.
