### ISSUE TITLE
Travis CI builds not being run

### ISSUE THREAD

**Issue by Cobra-Bitcoin** [bitcoin-dot-org/Bitcoin.org#3601]
There seems to be an issue with Travis; currently we're using travis-ci.org but apparently that's being phased out in favour of travis-ci.com in the next few weeks. Whatever is going on, it's causing issues with our test builds not running.

I'm going to wait until they complete whatever migration they're running on their end, because I can't seem to get it working no matter what I do. Pain in the ass to not have testing :/

Sorry about this. It's making it even harder to merge things quickly.

**Comment by k9ert** [comment]
Did you try to ask support@travis-ci.com ? They usually answer quite quickly and most likely this has nothing to do with the transitioning to travis-ci.com.

**Comment by Cobra-Bitcoin** [comment]
@k9ert Finally managed to get this resolved just now. Tests are running again, which can be seen in the latest PR: https://github.com/bitcoin-dot-org/Bitcoin.org/pull/3637.

Thankfully I didn't have to reach out to their support. I just had to migrate to their new beta, and it wasn't quite clear on their site how to do that at first but managed to eventually find it.

**Comment by CrazyPython** [comment]
Hey, just notifying, I heard Travis CI will be permanently shutting down, for real this time, its free builds for open-source projects.

Some alternatives that exist are Jenkins, Semaphore CI, and GitHub Actions.

**Comment by k9ert** [comment]
Also consider to use https://cirrus-ci.org/ .
Bitcoin is using it, I recently switched from Travis to this service with
the specter-project and I'm quite happy with it.

Cheers

Kim
