### ISSUE TITLE
Kannada (ಕನ್ನಡ)  Translation

### ISSUE THREAD

**Issue by ravish0007** [bitcoin-dot-org/Bitcoin.org#3606]
Can I do a PR for Kannada Translation ?

**Comment by heisenberg-hunter** [comment]
Hello and welcome to translating bitcoin.org. The translations for bitcoin.org aren't done that way. They are being carried out through [Transifex](https://www.transifex.com/bitcoinorg/bitcoinorg/dashboard/) website. Currently Hindi and Tamil are being worked on an active level and as of now there is no Kannada translation in progress. If you are willing to request Kannada and thereby translate the whole website, join Transifex and Request the language over here : [Request Language](https://www.transifex.com/bitcoinorg/bitcoinorg/languages/). 
I think @Komodorpudel should accept the language request. Please join the [Telegram group](https://t.me/bitcoinaroundtheworld) of the translators as well to receive regular updates.

**Comment by Komodorpudel** [comment]
Hey Rav, welcome :)

We usually use Transifex to organzie translations, just like @heisenberg-hunter mentioned.
Did you already translate everything outside of Transifex? If yes, just go ahead and follow this guideline:
https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/docs/assisting-with-translations.md#handling-translations-on-github

But if you want to start translating into Kannada; @heisenberg-hunter described everything :) Further information can be found here: https://github.com/bitcoin-dot-org/Bitcoin.org/blob/master/docs/assisting-with-translations.md

**Comment by ravish0007** [comment]
Haha, Should have seen the docs.
I'll checkout the guideline in short while.
Thanks
