### ISSUE TITLE
Romanian translation for the whitepaper

### ISSUE THREAD

**Issue by neuro-fishy** [bitcoin-dot-org/Bitcoin.org#3629]
Hi.

We have noticed some months ago that the current Romanian translation for the whitepaper is.. bad.
And after a while GazetaBitcoin made a new translation for whitepaper from scratch and I've helped him with images, corrections and now I try to send this new version hoping that you'll consider replacing the old translation with this new one.

I will post here also what GazetaBitcoin has to say:

> The actual proposed new translation improves dramatically the existing one from the following points of view:
> 
> - current translation contains crucial translation flows, including, but not limited to: (1) overall correction of the translated text, (2) the translated sentences do not make sense in Romanian, (3) the translated sentences are not coherent, (3) the translated sentences contain very severe grammar issues. The new proposed translation is correct from the translation process point of view, it is coherent, it is typo-free, it contains no grammar / spelling issues and it fully reflects Satoshi's ideas from the original document as they sound in Romanian language
> 
> - current translation does not contain the diagrams translated in Romanian, while the new proposed one contains diagrams fully translated in Romanian
> 
> - current translation does not respect even by far the original document's font, font size, font color, alignment, pagination (number of pages) and text framing inside the document. The new proposed translation fully respects the visual aspect of the original document: each page starts and ends with the same text as the original document; the translated text and its color / font / alignment / size / pagination also respect the source document
> 
> - current translation does not contain mathematics formulas translated in Romanian, while the new proposed translation contains also the formulas translated in Romanian
> 
> - current translation does not have inserted the page number, while the new proposed document contains also the page number
> 
> - aesthetically, the new proposed translation mirrors completely the original document, while the current translation was created in a deep not professional manner.
> 
> This topic from BitcoinTalk (and its posts) also reflects all the issues of the actual translation and, as a plus, there are several images reflecting the serious problems of the current translation: https://bitcointalk.org/index.php?topic=5285986.0.
> 
> Please be so kind and revise this new translation proposal, taking into account all the improvements mentioned above and also the topic from BitcoinTalk.org. Thank you.

.

I will try to make the pull request. I am not that much experienced with Git, so if anything is missing or I've done it wrong, please let me know.
Thank you.

Best regards,
NeuroticFish

**Comment by icopress** [comment]
I do not speak Romanian to confirm the accuracy of the translation, but I am well acquainted with  GazetaBitcoin and judging by the heated discussion of this topic in the forum, I have no doubt about the decency of NeuroFishy and GazetaBitcoin and their good intentions to help with Romanian localization.

Read: https://bitcointalk.org/index.php?topic=5285986.0

**Comment by neuro-fishy** [comment]
Big thanks to everybody for the feedback,whether it was here, or in the pull request or on Bitcointalk.
And also big thanks to @Cobra-Bitcoin for the merge
