### ISSUE TITLE
This app has been blocked for your protection.(Windows 10-64bit)

### ISSUE THREAD

**Issue by cboylesthebest** [bitcoin-dot-org/Bitcoin.org#3632]
After working up the nerve to configure Bitcoin core, I attempted to run bitcoin-0.21.0-win64-setup as administrator.
I received error "This app has been blocked for your protection."
My reaction? Turned off firewalls and in regeditt> Enable LUA changed UAC
value to 0 "zero".  No success. Out of options and solutions.
Thanks in advance for any help.

~Calvin Boyles

**Comment by Cobra-Bitcoin** [comment]
The more appropriate repo for these types of issues is https://github.com/bitcoin/bitcoin.

**Comment by cboylesthebest** [comment]
Thanks!
