### ISSUE TITLE
bitcoind RAM usage

### ISSUE THREAD

**Issue by dzmitrykliapkou** [bitcoin-dot-org/Bitcoin.org#3636]
Hi there!
We are trying to run full-node on AWS EC2 r5.large instance with 16GB RAM but we are facing a strange issue. Despite any options listed [here](https://github.com/bitcoin/bitcoin/blob/master/doc/reduce-memory.md) `bitcoind` memory usage constantly grows, so ~6min after start it uses 100% of RAM. 

Here is the command we use to run `bitcoind`:
```
usr/local/bin/bitcoind -daemon \
-pid=/run/bitcoind/bitcoind.pid \
-conf=/etc/bitcoin/bitcoin.conf \
-datadir=/data/bitcoind \
-txindex=1 \
-sysperms=true \
-dbcache=5000 \
-maxmempool=100
```

How can we limit `bitcoind` memory usage? Thanks in advance

**Comment by Cobra-Bitcoin** [comment]
The more appropriate repo for these types of issues is https://github.com/bitcoin/bitcoin.
