### ISSUE TITLE
Invalid Certificate

### ISSUE THREAD

**Issue by takana-v** [bitcoin-dot-org/Bitcoin.org#3639]
URL:https://bitcoin.org/bin/bitcoin-core-0.21.0/bitcoin-0.21.0-win64-setup.exe

![Untitled](https://user-images.githubusercontent.com/44311840/114295507-b2ea8d80-9ae0-11eb-95ff-98b23f106d34.png)

**Comment by Cobra-Bitcoin** [comment]
This belongs in https://github.com/bitcoin/bitcoin.
