### ISSUE TITLE
Make /bin a redirect to https://bitcoincore.org/bin?

### ISSUE THREAD

**Issue by laanwj** [bitcoin-dot-org/Bitcoin.org#3641]
As I am no longer going to upload new bitcoin core releases to bitcoin.org, and some people may still use the old URL, it might make sense to redirect `/bin` to `bitcoincore.org/bin` site as the canonical download location.

Same for the [bitcoin core](https://bitcoin.org/en/bitcoin-core/) section of the site (at least the download link).

An alternative would be to remove those parts of the site. In any case, keeping it as it is now might confuse people.

**Comment by Cobra-Bitcoin** [comment]
Strange to see you advocating centralization here. IMO having multiple download locations is a good thing. One "canonical location" is a bad thing and makes that location a target for attackers. Also, sometimes sites go down, get DDoS'd, blocked in certain countries, etc, so having more than one reputable site to get the software is essential. The current situation where some users download from bitcoin.org, and some from bitcoincore.org doesn't seem so bad, or at least not bad enough to redirect parts of the site, and remove content.

Unfortunately, we've also recently seen that bitcoincore.org cannot be considered a reliable location for hosting content. If there should be a "canonical location" for the software, it should be someplace that doesn't bend the knee to spurious legal threats.

**Comment by laanwj** [comment]
I do not intend to turn this into an argument. Basically I wanted to communicate I will not be uploading bitcoin core binaries anymore to this site. What you do is up to you.

**Comment by Cobra-Bitcoin** [comment]
@laanwj I don't want to argue either, I was just disagreeing strongly about your suggestion for there to be a canonical location to download the software.

Anyway, it's trivial to mirror the binaries and release notes, so I'll take up that role instead from now on. Thanks for letting me know.

**Comment by laanwj** [comment]
Fair enough, thanks.

**Comment by danger89** [comment]
I also want to sync the `bin` directory on my mirror: bitcoin.melroy.org. Are you using any script to sync the data? Or was and is this still done Manually?!

**Comment by danger89** [comment]
I created a Web scraper that does exactly this. My app will scrawl the [bitcoincore.org/bin](https://bitcoincore.org/bin) folder, and will download all the bitcoin core files and put them locally within a bin directory:

Check it out: https://gitlab.melroy.org/bitcoin-dot-org/bitcoin-core-web-scraper

See also Docker image: https://hub.docker.com/r/danger89/bitcoinscraper

This is ideal for creating your own mirror! The Docker image starts a cronjob, check the website once a week for any changes. So you don't need to do anything anymore.
