### ISSUE TITLE
dev IRC logs not available

### ISSUE THREAD

**Issue by jsarenik** [bitcoin-dot-org/Bitcoin.org#3648]
At https://bitcoin.org/en/development there is http://bitcoinstats.com/irc/bitcoin-core-dev/logs mentioned as source of IRC logs. That link and even parent directories show me a `Server Error (500)`.

**Comment by jsarenik** [comment]
Should rather point to http://gnusha.org/bitcoin-core-dev/

**Comment by kanzure** [comment]
ACK.

**Comment by jsarenik** [comment]
@Cobra-Bitcoin any comment, please? Is bitcoinstats.com expected to start working?

**Comment by jsarenik** [comment]
@Cobra-Bitcoin Mind me, sorry, I misunderstood and forgot this was just the issue and the PR was merged.

Thanks!
