### ISSUE TITLE
Old Wallet of 2003

### ISSUE THREAD

**Issue by Pmartos** [bitcoin-dot-org/Bitcoin.org#3662]
Good Morning.

My name is Paco Martos and I am writing to you because of a problem I have and to ask if your help is possible. In April 2013 I created a bitcoin wallet through bitcoin.org and I was depositing small amounts of satoshis that I was getting, at that time Bitcoin was not like it is now and it was a game for me. A few months later I had a problem with the pc and my hard drive with all the information and the program that I used as a wallet got erased. It was not something very important to me and I forgot about it. Now I have had bitcoins again and I remembered that wallet, searching through my emails I have been able to rescue the wallet address and the site where I created it (bitcoing.org) 😊. Not that he has a lot of money but it has already become a kind of personal challenge and treasure hunt. Is your help possible? Would you know how to tell me what kind of wallet could be made in bitcoin.org and try to track my old wallet.

Thank you!!.

**Comment by mrsteve0924** [comment]
i would try asking in this forum
[https://bitcointalk.org/](url)

**Comment by Pmartos** [comment]
Ok thanks, I will try in that forum. I wrote here since the wallet was created in 2013 from bitcoin.org and I wanted to know if there was something in the bitcoin.org database that could help me in that difficult task to try in a wallet to put the address and test any of my passwords usual. I know that it is difficult since I only have the address of the wallet, from where I create the wallet and the email that can be associated with it 8 years ago. :)

If anyone has any more ideas, it is welcome!
Thank you!! 
Muchas gracias!!
