### ISSUE TITLE
Error Opening Block Database

### ISSUE THREAD

**Issue by lloydrough** [bitcoin-dot-org/Bitcoin.org#3723]
<img width="599" alt="Screen Shot 2021-08-06 at 12 19 01 am" src="https://user-images.githubusercontent.com/31798948/128366255-07ec4588-ecc2-4f43-a5c8-6501654f3146.png">

It says I must rebuild the database, but then I get the error "Error opening Block Database"

**Comment by Cobra-Bitcoin** [comment]
This is more suitable for https://github.com/bitcoin/bitcoin.
