### ISSUE TITLE
Please revoke the BLW listing since their playstore listing points to an invalid website.

### ISSUE THREAD

**Issue by brianddk** [bitcoin-dot-org/Bitcoin.org#3725]
BLW failed to renew their SSL certificate and their site is now invalid.  It is important to never acclimatize bitcoin users to SSL errors.  All SSL errors should be treated as critical and sites that host them should be purged from recommendation.

* Broken site: http://lightning-wallet.com/
* Play Store (referencing site): https://play.google.com/store/apps/details?id=com.lightning.walletapp
* F-Droid (referencing site): https://f-droid.org/en/packages/com.lightning.walletapp/

**Comment by crwatkins** [comment]
@btcontract Hey Anton, your certificated expired yesterday.  Can you look into that?

**Comment by btcontract** [comment]
Thanks for the heads up, have just updated it. Really need to automate this somehow.

**Comment by crwatkins** [comment]
@btcontract Thanks!
