### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by Farzin3** [bitcoin-dot-org/Bitcoin.org#3732]
- date: YYYY-MM-DD
      title: ""
      venue: ""
      address: ""
      city: ""
      country: ""
      link: ""3E8ociqZa9mZUSwGdSmAEMAoAxBK3FNDcd

**Comment by Farzin3** [comment]
> ```
> - date: YYYY-MM-DD
>   title: ""کمک به مردم
>   venue: ""
>   address: ""
>   city: ""
>   country: ""
>   link: ""3E8ociqZa9mZUSwGdSmAEMAoAxBK3FNDcd
> ```

**Comment by Ashworth78** [comment]
??
