### ISSUE TITLE
Bitcoin v22.0 released

### ISSUE THREAD

**Issue by danger89** [bitcoin-dot-org/Bitcoin.org#3737]
I just want to inform that a new version is released: https://bitcoincore.org/en/2021/09/13/release-22.0/

**Comment by danger89** [comment]
Ps. also notice that they went from 0.21 to 22.0, removing the leading zero.

**Comment by danger89** [comment]
https://bitcoin.org/en/download is still showing the old version

**Comment by Ashworth78** [comment]
Thankyou👍

**Comment by danger89** [comment]
It's still not updated.

**Comment by Cobra-Bitcoin** [comment]
It'll be up soon. I just merged the PR, and uploaded the binaries.

**Comment by danger89** [comment]
Thanks! It's live! Good job.
