### ISSUE TITLE
Bitcoin.org currently shows a scam modal

### ISSUE THREAD

**Issue by achow101** [bitcoin-dot-org/Bitcoin.org#3743]
There is currently a scam modal appearing on Bitcoin.org telling people to send Bitcoin to the scammer's address. I would guess that the server hosting the website has been compromised as the modal does not appear in this repo.

This is what I currently see:

<img src="https://user-images.githubusercontent.com/3782274/134451557-6909d7cc-8432-4705-aa81-3f94cdf7aa82.png" width="500">

**Comment by junderw** [comment]
pointing to cloudflare, so maybe cf acct hacked?

**Comment by achow101** [comment]
Namecheap has disabled the domain: https://twitter.com/Namecheap/status/1440896036487245832

**Comment by AmishNick** [comment]
Damn they got almost half a btc in those few hours

**Comment by Cobra-Bitcoin** [comment]
Nothing on my end was compromised (accounts, server, etc). A team of people at Cloudflare and Namecheap are currently investigating what exactly happened. The DNS was completely hijacked, and the hackers were able to point the site to servers under their control.

Not much I could have done to protect the site from this.

**Comment by danger89** [comment]
@Cobra-Bitcoin Nice right.. First DDoS, now you trust Cloudflare to avoid down-time. You get this kind of non-sense with DNS hijacking. 

I think it's time to change how the WWW works, like with IPFS...

**Comment by prayank23** [comment]
> Anyway, I think it's time to change how the WWW works, like with IPFS...! Who is with me!?

IPFS won't solve anything if the domain is pointing to another website.

**Comment by achow101** [comment]
Closing this as the website appears to be back to normal, although I am still interested in hearing what caused this the occur.

***

Here are a few observations that may help out with figuring out what happened:
* A couple of months ago, the domain was switched to using Cloudflare's DNS and proxying service in order to get DDoS protection.
* The site uses a Let's Encrypt certificate. Apparently Cloudflare's business accounts allow for proxying while also setting a custom SSL certificate.
* When the site was hacked, DNS records did not change and continued to point to Cloudflare
  * This indicates a compromise of the Cloudflare account or within Cloudflare itself
* The attack appears to have coincided with changes to whois records, as well as the issuance of a certificate by Cloudflare, and a different certificate issued by Let's Encrypt.
  * A whois lookup [performed](https://www.reddit.com/r/Bitcoin/comments/ptmf3v/comment/hdx7six/?context=3) shortly after the compromise was noticed indicates an updated time of 2021-09-23T02:10:17Z
  * The cloudflare SSL certificate was issued at 2021-09-23 02:21:13 UTC according to [Certificate Transparency logs](https://crt.sh/?id=5270356635). This was the certificate most (all?) visitors saw.
  * The [Let's Encrypt certificate](https://crt.sh/?id=5270352134) was issued a few minutes prior at 2021-09-23 02:18:47 UTC.

**Comment by danger89** [comment]
Did he forget to renew the domain name? Indicating the Whois change....

**Comment by achow101** [comment]
> Did he forget to renew the domain name? Indicating the Whois change....

I don't think so. The whois data from a few months ago says the expiry is in 2029. It has not expired recently.

It's not clear to me what actually changed in the whois data. Each whois query I've looked at has had the exact same data except for the updated time.

**Comment by ralyodio** [comment]
its because of crapflare
