### ISSUE TITLE
Remove White Paper Spanish (Latam) Translation

### ISSUE THREAD

**Issue by dubdam** [bitcoin-dot-org/Bitcoin.org#3767]
The Spanish (Latam) translation of the white paper hosted at bitcoin.org is poorly translated and includes an advertisement to a shitcoin news webiste called diariobitcoin.com (affinity scam).

The Spanish translation by breathingdog is way better and I don't think that two Spanish versions are necessary. It's like having an English (UK) and English (USA) translations.

**Comment by danger89** [comment]
Indeed, this version should be removed: https://bitcoin.org/files/bitcoin-paper/bitcoin_es_latam.pdf

**Comment by Cobra-Bitcoin** [comment]
Good point about having two Spanish versions being redundant. I'll remove it. Thanks for pointing this out!
