### ISSUE TITLE
Bitcoin Core installer downloads are broken

### ISSUE THREAD

**Issue by haakonn** [bitcoin-dot-org/Bitcoin.org#3782]
On https://bitcoin.org/en/download, the Windows and Mac downloads are dead links.

They point to https://bitcoin.org/bin/bitcoin-core-22.0/bitcoin-22.0-win64-setup-unsigned.exe and https://bitcoin.org/bin/bitcoin-core-22.0/bitcoin-22.0-osx.dmg respectively.

I've checked on my local connection, as well as a Swiss VPN. There was also a complaint about it [on Reddit](https://www.reddit.com/r/Bitcoin/comments/quavy0/getting_404_when_trying_to_download_core/).

**Comment by Cobra-Bitcoin** [comment]
This will be fixed shortly.

**Comment by Cobra-Bitcoin** [comment]
Resolved in https://github.com/bitcoin-dot-org/Bitcoin.org/commit/7d7e11e0215f204acebbc950092ea1973132697e.
