### ISSUE TITLE
Wrong link for mac os dmg on homepage

### ISSUE THREAD

**Issue by surak** [bitcoin-dot-org/Bitcoin.org#3783]
The page https://bitcoin.org/en/download

points to 
https://bitcoin.org/bin/bitcoin-core-22.0/bitcoin-22.0-osx.dmg

which does not exist. The file is called
https://bitcoin.org/bin/bitcoin-core-22.0/bitcoin-22.0-osx-signed.dmg

**Comment by Cobra-Bitcoin** [comment]
Resolved in https://github.com/bitcoin-dot-org/Bitcoin.org/commit/7d7e11e0215f204acebbc950092ea1973132697e.
