### ISSUE TITLE
Bitcoin 2022 Conference April 6-9 2022

### ISSUE THREAD

**Issue by kstanwood** [bitcoin-dot-org/Bitcoin.org#3806]
![twitter](https://user-images.githubusercontent.com/22876626/147778961-911bf0cf-f76f-44ed-a6a2-1051a4642f20.jpg)
    - date: 2022-04-06 through 2022-04-09
      title: "Bitcoin 2022 Conference"
      venue: "Miami Beach Conference Center"
      address: "1901 Convention Center Dr. Miami Beach, FL 33139, USA"
      city: "Miami Beach"
      country: "USA"
      link: "https://www.b.tc/conference/registration"

**Comment by aioromo** [comment]
Is this event going to be published on Bitcoin.org website? 

It's rare to find Bitcoin-only events and this is the largest of them all. 

Can't wait for Bitcoin 2022!
