### ISSUE TITLE
Satoshi candidate

### ISSUE THREAD

**Issue by sahil5d** [bitcoin-dot-org/Bitcoin.org#3846]
https://medium.com/p/4120f36da702

**Comment by bullsandbears** [comment]
Ha ha 🤣🤣

**Comment by Ashworth78** [comment]
If this is true plz tell me my email on your early mailing list as I was anonymous at this point in time to EVERYONE apart from satoshi himself??

**Comment by bullsandbears** [comment]
Mein Tiefster Dank geht an meine drei Team Leiter Die Menschheit wird immer in eurer schuld bleiben Dankeschön Hal Finney Teamleiter Code  Dankeschön Len Sassaman Teamleiter Mining  Dankeschön Nick Szabo Abteilung Whitepaper in Englischer Sprache Zusammenfassung nach meiner Vorgabe. Abhelfen bei Mining und Code. Ich weiss noch wie Nick sagte Ich habe schon mal digitales Geld gemacht dass wird nicht funktionieren. Ich antwortete ihm Egal wir machen es trotzdem.  Dankeschön an die 9 anderen die Bei der Code Überprüfung mitgeholfen haben. Wie Gott die Welt an 7 Tagen erschaffen hat. Ich wollte es dem Herrn gleich tun 6 Tage anbeteten wir wie die Verrückten und ruhten am 7 Tag Und Die neue Welt war geboren Willkommen im Blockchain Zeitalter. Ich danke euch allen für euren Einsatz Jeder der 12 mitwirkender wurde mit 50 BTC Bezahlt damals war das nicht viel aber jeder war bereit Trotzdem Sein bestes zu geben.
