### ISSUE TITLE
Max number of outgoing connections is now 10, instead of 8

### ISSUE THREAD

**Issue by nodet** [bitcoin-dot-org/Bitcoin.org#3852]
Running `Bitcoin Core version v22.0.0 (release build)`, I can see that the max number of outgoing connections is 10.

```
$ cat ~/.bitcoin/bitcoin.conf
datadir=/mnt/disk/blockchain
blocksonly=1
$ bitcoin-cli -getinfo
{
  "version": 220000,
  "blocks": 728655,
  "headers": 728655,
  "verificationprogress": 0.9999964627698886,
  "timeoffset": 0,
  "connections": {
    "in": 5,
    "out": 10,
    "total": 15
  },
  "proxy": "",
  "difficulty": 27452707696466.39,
  "chain": "main",
  "relayfee": 0.00001000,
  "warnings": ""
}
```

The full node page at https://bitcoin.org/en/full-node has a number of references to this number being 8. I'll submit a PR shortly.

**Comment by tadeubas** [comment]
Hi @nodet , have you realized that this project is about the bitcoin dot org site and not about the bitcoin core software?

**Comment by Saedx01x01iiiio** [comment]
"{+''

**Comment by amimahd** [comment]
Very good
