### ISSUE TITLE
Please update CoinJar's existing AU listing + add to the UK Exchange list (FCA registered)

### ISSUE THREAD

**Issue by cryptomoniq** [bitcoin-dot-org/Bitcoin.org#3905]
Hi Team,

1. Can you please update the CoinJar existing listing on:
https://bitcoin.org/en/exchanges#australia

from https://www.coinjar.com/ to https://www.coinjar.com/au/

2. Can you please add CoinJar to the UK list (we are FCA registered and have over 100k UK customers)
https://bitcoin.org/en/exchanges#united-kingdom

https://www.coinjar.com/uk/

Your help is much appreciated.

**Comment by Cobra-Bitcoin** [comment]
Done (https://github.com/bitcoin-dot-org/Bitcoin.org/commit/34f186de63c15c383fd2699bdeb1b7db5d555535). Thanks.
