### ISSUE TITLE
Delete Eclair Mobile wallet from your wallet recommendation

### ISSUE THREAD

**Issue by AntonBespalov** [bitcoin-dot-org/Bitcoin.org#3906]
https://bitcoin.org/en/wallets/mobile/android/eclairmobile/ - on this page you recommend to use this wallet, but the developer on his github page (https://github.com/ACINQ/eclair-mobile) doesn't recommend to use it for new wallets - "Eclair Mobile is now in End-Of-Life mode. Do not use it for new wallets."

**Comment by crwatkins** [comment]
@AntonBespalov Thanks for opening this issue.  That looks reasonable to me.

@sstone @dpad85 Any recommendations?

**Comment by dpad85** [comment]
Hey, thanks for the notification. Eclair Mobile is indeed not recommended anymore. We should have updated the repo when we deprecated the app back then, sorry about that. I'll make a PR to fix that if that's fine with you.

**Comment by crwatkins** [comment]
@dpad85 Fantastic!   Thanks much for such a quick response!

**Comment by kuowei9207** [comment]
這是被盜竊是嗎？
