### ISSUE TITLE
Orginal version of Bitcoin whitepaper from 31 October 2008

### ISSUE THREAD

**Issue by ducree** [bitcoin-dot-org/Bitcoin.org#3925]
It seems the PDF version of the Bitcoin whitepaper posted on Bitcoin.org was created on 24 March 2009. 

Would you also have the original version of the PDF posted by Satoshi Nakamoto on 31 October 2008?

Would the version you have available for download have been generated by Satoshi Nakamoto?

Best wishes

Jens Ducrée

**Comment by Cobra-Bitcoin** [comment]
Yes, the current version was generated by Nakamoto.
