### ISSUE TITLE
Bitcoin Core v23.0 is latest

### ISSUE THREAD

**Issue by melroy89** [bitcoin-dot-org/Bitcoin.org#3926]
Hi again,

Bitcoin core `v23.0` is the latest release. - [reference](https://bitcoincore.org/en/download/)

I think you need to create a markdown file again ([just like this](https://github.com/bitcoin-dot-org/Bitcoin.org/commit/196e880e024efeb03c308a78ea8165efb930066b)) in the [_releases](https://github.com/bitcoin-dot-org/Bitcoin.org/tree/master/_releases) folder.

This should also reflect eventually here: https://bitcoin.org/en/bitcoin-core/ (currently still showing v22.0).

Thanks in advance.

Regards,
Melroy vd Berg

**Comment by slashbinslashnoname** [comment]
Was going to submit the same issue.

https://bitcoin.org/bin/ doesn't have the right version available

**Comment by danger89** [comment]
> We will add the new version soon, but in general, there doesn't have to be a rush. I think it makes the network more robust if there are multiple versions. I hate this culture of "upgrade asap!".

I actually fully agree here with you.

In that aspect, I would love to see more node software options, next to the Bitcoin Core. Since that is not the only node software for Bitcoin.

**Comment by instagibbs** [comment]
Why not serve each version faithfully, instead of making judgment calls for potential users?

**Comment by instagibbs** [comment]
If your intention is to encourage people to run not only the latest-greatest, might as well be explicit about it and let users know newer binaries may be hosted elsewhere?

**Comment by Cobra-Bitcoin** [comment]
@instagibbs Letting users know the newer version may be elsewhere is a good idea. If someone made a PR that did that, I'm sure it would probably get merged as long as the notice was subtle and well placed.

@danger89 Other node implementations being featured would be interesting, I think we'd have to design it in a good way though and it could take a lot of effort. We'd also have to explain to the user that some software might not come with a wallet built in.

If you Google "download Bitcoin" or "download Bitcoin Core", bitcoin.org is the first result for both (at least for me). That kind of limits how we can design around the download page, the users come looking for Bitcoin Core specifically. In fact there is an entire Bitcoin Core subsite within bitcoin.org that still gets a lot of traffic itself (just google "Bitcoin Core"!). Bitcoin Core didn't used to be called that, it was initially just "Bitcoin" and was downloaded from bitcoin.org, then it was renamed to Core but didn't have its own site, and then it got its own site and subsequently the binaries became available more readily there. It's a mess to decouple all of this, there are hundreds of thousands of links across the internet to some of these pages. Long term it's obvious that Core is now its own separate thing and that's a good thing, and bitcoin.org is more for explaining Bitcoin in general, not a specific node implementation.

**Comment by danger89** [comment]
> bitcoin.org is more for explaining Bitcoin in general, not a specific node implementation.

That is great mindset, let's try do it.

**Comment by moneyball** [comment]
At the very least it shouldn't say "Latest version: 22.0" as that is factually wrong. It could say "Latest recommended version" instead and provide an explanation as to why (as there is a good explanation). This is orthogonal to whether or not it should also link to https://bitcoincore.org/ as well (IMO it should). Since it seems like @Cobra-Bitcoin is open to having a look at a PR, I'll try to find someone to propose one if not myself.

**Comment by fanquake** [comment]
@moneyball see #4010.

**Comment by GBKS** [comment]
I agree with this change. The webpage states that it provides the latest version, yet it does not actually do that. That is a specific, factual change that should not really be controversial.

The other points about network health and alternatives are separate topics, IMHO, and I do not understand how this is being pushy towards users (it’s not like anyone gets a notification to update when links here change). Maybe those are better as separate issues/PRs?

**Comment by darosior** [comment]
If you don't want to let users access the latest version and the new features that come with it, at least please let them access bug fixes from point releases? The current version available for download (released almost 2 years ago) doesn't even get backports anymore..

**Comment by Cobra-Bitcoin** [comment]
This has been fixed now and the site supports the latest version.
