### ISSUE TITLE
Add first Bitcoin-only Conference in Brazil

### ISSUE THREAD

**Issue by lucasdcf** [bitcoin-dot-org/Bitcoin.org#3935]
date: 2022-11-08
title: "Satsconf"
venue: "Audio"
address: "Av. Francisco Matarazzo, 694 - Água Branca, São Paulo - SP, 05001-100"
city: "São Paulo"
country: "Brazil"
link: "http://satsconf.com.br/"

**Comment by Cobra-Bitcoin** [comment]
It's been added, it should go live on the site in a few hours. Thanks.
