### ISSUE TITLE
Restarting bitcoin.org as i left it. Back in 2010 April  last update to main page of bitcoin.org

### ISSUE THREAD

**Issue by SatoshiNakamoto-MAM** [bitcoin-dot-org/Bitcoin.org#3944]
- date: YYYY-MM-DD
      title: ""  bitcoin.org  /  bitcoincore 
      venue: ""
      address: ""
      city: ""
      country: ""
      link: ""
 I  am  satoshi  nakamoto  and  remember  i   am  the  only  one  that  can  make  changes.

**Comment by andrew66626** [comment]
>     - date: YYYY-MM-DD
>       title: ""  bitcoin.org  /  bitcoincore 
>       venue: ""
>       address: ""
>       city: ""
>       country: ""
>       link: ""
>  I  am  satoshi  nakamoto  and  remember  i   am  the  only  one  that  can  make  changes. 

Iam Satoshi nakamoto an iam steel around like I allwas have been now it's time that iam to use a wallet that has everything I need steel no one will no me but the stachu ofe is Dame close.
