### ISSUE TITLE
Bitcoin core GUI closes on Ubuntu

### ISSUE THREAD

**Issue by reddrums4u** [bitcoin-dot-org/Bitcoin.org#4009]
I am running Ubuntu 22.04.2 LTS
I am running Bitcoin Core 24.0.1

The GUI stays open for an varied amount of time and then closes abruptly. I can open it back up, but then it closes again abruptly. Sometimes 30 seconds, sometimes 10 seconds, sometimes minutes.

**Comment by Mirage1348** [comment]
Bu konuda ne yapabilirim?

**Comment by cbergqvist** [comment]
Please file the issue with Bitcoin Core under this repo instead: https://github.com/bitcoin/bitcoin

Issues filed here should be about the bitcoin.org website.
