### ISSUE TITLE
سلام چرا با اینکه منرمعلول کل کارهایم را طبق دستور انجام داده ام با دارید من را اذیت میکنید  وهیچ کدام از ارزهایم را نشان نمیدهید اگر واقعا خوشحالید که یک معلول را اینقدر ازار دهید تا من گذارشم را با مدارکم تقدیم سازمان ملل وحقوق بشر کنم تا دست از اذار بردارید اخه چقدر من معلود طبق دستوورات شما را انجام داده ام ولی باز هم همان کد  خودتان را انجام میدهید ویا فیلتر یا نیست وهمچیز را روت میکنید خواهشن اگر اقدام نمیکنید من گذارشاتم را کامد با سازمان ملل ارجاع دهم چون حق ومال خودم را اجازه ندارم با اینکه غیر متمرکز کردم بخدا سخت برای انسانی که معلول است شمل ا دم معلول 

### ISSUE THREAD

**Issue by Asman3316** [bitcoin-dot-org/Bitcoin.org#4013]

**Comment by Asman3316** [comment]
من فقط میخواهم به اندازه یک بیت تا دوبیت کوین برداشت کنم خواهشن کمکم کنید

**Comment by w1ldworm** [comment]
@Asman3316 سلام 
لطفا برای حل مشکل خود در تلگرام به آیدی زیر پیام بدید خیلی هم سریع جواب میدن:

@BTC_Supp_persian

**Comment by Asman3316** [comment]
بخدا با این معلولیتم همه دستورات را درست انجام دادم ولی باز من مریض معلول را مثل خودشان که سالنم هسید میبینید

**Comment by Asman3316** [comment]
هر چه قدر من میگویم طبق خواسته ام که کل مجموعه مطعلق هست به خودم باز همان کار خودتان را با فیلتر وهیپ مقداری ویا روت است انجام میدهید واله اگر نمیتوانید بمن بگویید تا با ارجا به سازمان حقوق بشر ومعلولیتم جواب خواهن داد نه هر لحظه طرح وکاری پیشنهاد کنید وبه من معلول مثل خودتان که سالم هستید بخندید

**Comment by Asman3316** [comment]
سلام چشم حتما
