### ISSUE TITLE
 Incorrect Language Name for Slovak Version of Bitcoin Whitepaper

### ISSUE THREAD

**Issue by StellarStoic** [bitcoin-dot-org/Bitcoin.org#4038]
**Issue Description:**
The language name for the Slovak version of the Bitcoin whitepaper on Bitcoin.org is currently labeled as "Slovenščina," which is incorrect. The correct term for the Slovak language is "Slovenčina." This discrepancy can lead to confusion among users looking for the Slovak version of the whitepaper.

**Steps to Reproduce:**

- Visit the Bitcoin.org website.
- Navigate to the Slovak version of the Bitcoin whitepaper.
- Observe that the language is labeled as "Slovenščina."

**Expected Behavior:**
The language name for the Slovak version of the Bitcoin whitepaper should be correctly labeled as "Slovenčina," representing the Slovak language.

**Proposed Solution:**
I have created a pull request[ (PR #4028](https://github.com/bitcoin-dot-org/Bitcoin.org/pull/4028)) to update the language name from "Slovenščina" to "Slovenčina" for the Slovak version of the whitepaper. This change will ensure that the language versions are accurately labeled and avoid any confusion for users seeking the correct language version.

**Additional Information:**
This issue is particularly important as we plan to upload the Slovenian whitepaper version, and having the Slovak version mislabeled as "Slovenščina" can cause confusion and inaccuracies.

**Environment:**

Website: [Bitcoin.org](https://bitcoin.org/en/bitcoin-paper)
Language: Slovak
I kindly request the project maintainers to review and merge the pull request to rectify this language name discrepancy. Thank you for your attention to this matter.

![Screenshot (417)](https://user-images.githubusercontent.com/34000272/236630068-f4632d52-0145-4284-8579-7fd553cb2397.png)

**Comment by Cobra-Bitcoin** [comment]
Fixed. Thanks for the heads up!
