### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by ShortieScobey** [bitcoin-dot-org/Bitcoin.org#4072]
On June 2, 2023, I purchased Bitcoin thru cash app with a lady that says she works for Classic FX Trading. I started with $100. A few days later I received an email from them stating that I need to pay $2999 withdrawal fee. I pd that and then she told me I had to pay a $500 commission fee to her company. So I pd that. Now she is stating that I have to pay a $1200 late fee on my own money to get it. Plz help

**Comment by ShortieScobey** [comment]
Plz help. I've purchased Bitcoin thru cash app and can't get my money off Classic FX Trading

**Comment by HenryEnrique** [comment]
> Plz help. I've purchased Bitcoin thru cash app and can't get my money off Classic FX Trading

Same thing happened to me but thanks to Blackhathacker111 who helped me get recovered my lost funds,message him on telegram his telegram username is https://t.me/Blackhathacker110

**Comment by ShortieScobey** [comment]
I did leave that comment. Someone else did.

**Comment by ShortieScobey** [comment]
I DID NOT LEAVE THAT COMMENT
