### ISSUE TITLE
Hacked

### ISSUE THREAD

**Issue by doperiddle** [bitcoin-dot-org/Bitcoin.org#4102]
1HZwkjkeaoZfTSaJxDw6aKkxp45agDiEzN  This is my old  Bitcoin address period it got hacked years ago and the private keys are all over the internet  . Is there any way I can recover funds and how do I get the funds to stop going to this address

**Comment by Doncharless** [comment]
> 1HZwkjkeaoZfTSaJxDw6aKkxp45agDiEzN This is my old Bitcoin address period it got hacked years ago and the private keys are all over the internet . Is there any way I can recover funds and how do I get the funds to stop going to this address

Same thing happened to me but thanks to Blackhathacker111 who helped me get recovered my lost funds,message him on telegram his telegram username is https://t.me/Blackhathacker110

**Comment by AugustoResende** [comment]
This is the repository to Bitcoin.org website. You cannot "recover" an address or prevent anyone to transferring to a specific address.

**Comment by Gavehenry12** [comment]
> 1HZwkjkeaoZfTSaJxDw6aKkxp45agDiEzN This is my old Bitcoin address period it got hacked years ago and the private keys are all over the internet . Is there any way I can recover funds and how do I get the funds to stop going to this address

Same thing happened to me but thanks to Blackhathacker111 who helped me get recovered my lost funds,message him on telegram his telegram username is https://t.me/Blackhathacker110

**Comment by AugustoResende** [comment]
This is scam.

**Comment by Gavehenry12** [comment]
> This is scam.
> […](#)

Lol what I’m trying to scam here?? He really helped me don’t say what you don’t know

**Comment by AugustoResende** [comment]
> > This is scam.
> > […](#)
> 
> Lol what I’m trying to scam here?? He really helped me don’t say what you don’t know

You has registered last week, with a fake username, and is trying to get an innocent user to Telegram, the scammer's paradise, to talk with a completely unknown person. Surely it's not a scam, of course, you are saying that is because you say that is not a scam.
