### ISSUE TITLE
The transparency score misuses the term "open source"

### ISSUE THREAD

**Issue by ai-oleynikov** [bitcoin-dot-org/Bitcoin.org#4110]
https://github.com/bitcoin-dot-org/Bitcoin.org/blob/fbc8db1a32b63042f9a723c9a74bd8f54606ef11/_translations/en.yml#L340

The source code being readable and the build process being deterministic do not necessarily mean that the software is open source as per the [official OSI definition](https://opensource.org/osd/). For example, both Coldcard's and Passport's firmware can be built reproducibly, but they aren't open source. I suggest we correct this description to say that the code is just publicly available, e.g.:

```diff
- This wallet is open-source and built deterministically.
+ The source code for this wallet is public, and the build process is deterministic.
```

**Comment by crwatkins** [comment]
I agree (although I would leave out the comma).  I recommend a PR.

**Comment by Mandog1120** [comment]
> https://github.com/bitcoin-dot-org/Bitcoin.org/blob/fbc8db1a32b63042f9a723c9a74bd8f54606ef11/_translations/en.yml#L340
> 
> The source code being readable and the build process being deterministic do not necessarily mean that the software is open source as per the [official OSI definition](https://opensource.org/osd/). For example, both Coldcard's and Passport's firmware can be built reproducibly, but they aren't open source. I suggest we correct this description to say that the code is just publicly available, e.g.:
> 
> ```diff
> - This wallet is open-source and built deterministically.
> + The source code for this wallet is public, and the build process is deterministic.
> ```
