### ISSUE TITLE
Slovenian translation of whitepaper

### ISSUE THREAD

**Issue by Demc976** [bitcoin-dot-org/Bitcoin.org#4113]
Hi

We would like to post translation of whitepaper in Slovenian language? Who can we contact?

**Comment by AugustoResende** [comment]
Just do it and open a Pull Request.

**Comment by Demc976** [comment]
Thank you, but with whom or how do i open Pull Request? Do you know who is website admin? I'd love to get the person email or any other contact. The Telegram translation group has no answers. We had been trying to get translation on the .org site since july!
