### ISSUE TITLE
Web Site's discrimination

### ISSUE THREAD

**Issue by LemaBelay** [bitcoin-dot-org/Bitcoin.org#4164]
Dear Bitcoin.org, 

Greetings, I hope this find you well. I have an issue that needs an explanation.

When I tried to download the Bitcoin White Paper from your website [Bitcoin.org]. I noticed a blockage. I did not get the PDF paper, even from Google search link. How is it Google can get the paper and I can't? Could you please amend your ways and give me an explanation? (Read the Images attached).

By the way, if you are unable to change. It could be read as payload and harassment for sick gains!!! If that is so, I guess, is that why you are in hiding! lol

Thank you,
PS: Where is the blue paper? lol

The Images and content are the copy right of the owners.

![google](https://github.com/bitcoin-dot-org/Bitcoin.org/assets/161141195/fc590268-223b-4564-834c-1c057da407f9)
![NotGoogle](https://github.com/bitcoin-dot-org/Bitcoin.org/assets/161141195/0cb2d1c0-77b4-4bd6-ae77-790e556a92b8)

**Comment by Mandog1120** [comment]
> เรียน Bitcoin.org 
> 
> สวัสดี ฉันหวังว่าสิ่งนี้จะพบคุณโดยดี ฉันมีปัญหาที่ต้องการคำอธิบาย
> 
> เมื่อฉันพยายามดาวน์โหลด Bitcoin White Paper จากเว็บไซต์ของคุณ [Bitcoin.org] ฉันสังเกตเห็นการอุดตัน ฉันไม่ได้รับเอกสาร PDF แม้จะมาจากลิงก์ค้นหาของ Google ก็ตาม เป็นไปได้อย่างไรที่ Google สามารถรับกระดาษแต่ฉันทำไม่ได้ คุณช่วยกรุณาแก้ไขวิธีการของคุณและให้คำอธิบายแก่ฉันได้ไหม? (อ่านภาพที่แนบมา)
> 
> อย่างไรก็ตามหากคุณไม่สามารถเปลี่ยนแปลงได้ อาจอ่านได้ว่าเป็นเพย์โหลดและการคุกคามเพื่อผลประโยชน์ที่ป่วย!!! ถ้าเป็นเช่นนั้น ฉันเดาว่านั่นคือเหตุผลว่าทำไมคุณถึงซ่อนตัว! ฮ่าๆ
> 
> ขอบคุณ PS: กระดาษสีฟ้าอยู่ที่ไหน? ฮ่าๆ
> 
> รูปภาพและเนื้อหาเป็นลิขสิทธิ์ของเจ้าของ
> 
> ![Google](https://private-user-images.githubusercontent.com/161141195/307529423-fc590268-223b-4564-834c-1c057da407f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyOTU3ODYsIm5iZiI6MTcwOTI5NTQ4NiwicGF0aCI6Ii8xNjExNDExOTUvMzA3NTI5NDIzLWZjNTkwMjY4LTIyM2ItNDU2NC04MzRjLTFjMDU3ZGE0MDdmOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMVQxMjE4MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNjg3NjcyYWRhZjBiOWZjZGQ0YzhkM2Q2MmFiYmVkZWMxNWQ4MGZiZDhiZWNhYzZlNzA2NTc0MzFjZTBmM2VmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._6bG1ikbZOXpb0t-5jIJvY5dKwzanLU6fU5mzI1cv4U) ![ไม่ใช่Google](https://private-user-images.githubusercontent.com/161141195/307529424-0cb2d1c0-77b4-4bd6-ae77-790e556a92b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyOTU3ODYsIm5iZiI6MTcwOTI5NTQ4NiwicGF0aCI6Ii8xNjExNDExOTUvMzA3NTI5NDI0LTBjYjJkMWMwLTc3YjQtNGJkNi1hZTc3LTc5MGU1NTZhOTJiOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMVQxMjE4MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYzNiOTRjOWIzN2ViZjg3NjA0Y2JhMmIzOGQzYjU2ZjNlYzQ0NjM1YjE5YTMyODgyMDU1N2JmY2ZjYzZlNDlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0LVVToMNaAoxydpYnW6SVggxM6kgCQBQHs5v-aUccRU)

**Comment by Cobra-Bitcoin** [comment]
Bitcoin.org got sued in the UK by someone claiming to own the copyright in the whitepaper. That person won the case by default because we didn't participate. As a result the court ordered to block access to the whitepaper to visitors from the UK. You can get the whitepaper from many other places though. This only impacts a small percentage of users.
