### ISSUE TITLE
Travis CI - No Longer Running On PRs

### ISSUE THREAD

**Issue by JoePotentier** [bitcoin-dot-org/Bitcoin.org#4174]
Travis CI is not running for all pull requests made to master. This blocks new contributors from being able to make contributions.

Please, someone with Travis CI access, would you mind looking into this?

![Screenshot 2024-03-25 at 11 00 14 AM](https://github.com/bitcoin-dot-org/Bitcoin.org/assets/9673684/5b912d8e-c17a-4364-9edb-e3ae7b7b9fd5)

**Comment by Cobra-Bitcoin** [comment]
It should be fixed now.

**Comment by Cobra-Bitcoin** [comment]
Any new PRs and commits to existing PRs should get automatically tested.
