### ISSUE TITLE
why is this happening

### ISSUE THREAD

**Issue by Tifferz4u** [bitcoin-dot-org/Bitcoin.org#4262]
where did all my stuff go I cant see my Bitcoin or withdrawall help me please

**Comment by laalauren1** [comment]
> where did all my stuff go I cant see my Bitcoin or withdrawall help me please

@Tifferz4u It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID BTC07638
Please see the link below to our dedicated support line:
[Bitcoin Network DApps Support Ticket Requests](https://thedappsupport.com/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.
