### ISSUE TITLE
Mr

### ISSUE THREAD

**Issue by Naeemlabib123** [bitcoin-dot-org/Bitcoin.org#4295]
To whom it may concern 

I have lost my phone I had my Bitcoin wallet in there I had thousands of my coins in there I have forgotten my password and username  does anyone know how to get my money back. 
Kind regards
 M.Naeem

**Comment by Naeemlabib123** [comment]
I'm super stressed

**Comment by Annawoody** [comment]
It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID BIT07638
Please see the link below to our dedicated support line:
[Bitcoin Network DApps Support Ticket Requests.](https://thedappsupport.com/)
 Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.
@Naeemlabib123

**Comment by Angiepeck22** [comment]
Hello @Naeemlabib123 
 has your issues been resolved?

**Comment by Naeemlabib123** [comment]
How has it been resolved what can do to get my money back?

Yahoo Mail: Search, organise, conquer 
 
  On Thu, 21 Nov 2024 at 23:23, ***@***.***> wrote:   


Hello @Naeemlabib123
has your issues been resolved?

**Comment by Angiepeck22** [comment]
@Naeemlabib123 reach out to the support team now for immediate assistance they should be able to figure it out

**Comment by Naeemlabib123** [comment]
To whom it may concern 
I have sent you emails regarding losing my phone on one of my flight from dubai everything was there sent quite a number of emails to fly dubai Airline dubai lost and found department they didn't have it but I have not had any response from fly dubai now I am very stressed how can I get my bitcoins back I don't know any of my password or anything I'm fifty years old and I forget things. 
Kind regards M.Naeem 

Yahoo Mail: Search, organise, conquer 
 
  On Sun, 24 Nov 2024 at 19:18, ***@***.***> wrote:   


Closed #4295 as completed.
