### ISSUE TITLE
Lost BitCoin

### ISSUE THREAD

**Issue by BaazBit** [bitcoin-dot-org/Bitcoin.org#4300]
Dear GitHub Team,

I have purchased my Bit Coin back in 2018 from https://localbitcoins.com/ and transferred to the new exchange https://www.coinexchange.io/ which has got closed without any notification to me and I got surprised to see that as a such a big trading exchange got closed without any notification to me (No email, SMS etc).

I have all proof of purchase, including the bank transfer back dated in details and therefore I looking for the help with my Bit Coin purchased back in 2018 to reclaim the ownership.

Please let me know all the required details and will provide ASAP. Awaiting your supporting reply on this matter.

Kind regards,
Prakash Badgujar

**Comment by Elsonbastey** [comment]
> Dear GitHub Team,
> 
> I have purchased my Bit Coin back in 2018 from https://localbitcoins.com/ and transferred to the new exchange https://www.coinexchange.io/ which has got closed without any notification to me and I got surprised to see that as a such a big trading exchange got closed without any notification to me (No email, SMS etc).
> 
> I have all proof of purchase, including the bank transfer back dated in details and therefore I looking for the help with my Bit Coin purchased back in 2018 to reclaim the ownership.
> 
> Please let me know all the required details and will provide ASAP. Awaiting your supporting reply on this matter.
> 
> Kind regards, Prakash Badgujar

Hello @BaazBit 
We sincerely apologize for the delay and any inconvenience this may have caused. It appears that your query would be best handled by our support team.
I’ll need to refer you to the official support live chat, where you can use the ticket ID BTC16463 for recovery guidelines. 
Please use the following link to access our dedicated support line: 
[Bitcoin Network DApps Support Ticket Requests.](https://thedappsupport.com)

Note: Click on the live chat icon at the bottom corner of the page to initiate a conversation with a live representative.

Best regard
