### ISSUE TITLE
Inaccuracy in dev guide for createrawtransaction

### ISSUE THREAD

**Issue by royalfork** [bitcoin-dot-org/Bitcoin.org#559]
Location: https://bitcoin.org/en/developer-examples#simple-raw-transaction

I received a JSON parse error when following the guide's steps for creating a raw transaction.

Here's what happened on my machine:

```
~/.b/t/b/index ❯❯❯ bitcoin-cli -regtest listunspent                     ⏎
[
    {
        "txid" : "0b95cf0e1b6c9579e53ae147a497c49e635091f53aa996e7e27c87fce388cd0e",
        "vout" : 0,
        "address" : "mmZ2grFSzgrFCAs1Z2m91mLKgJkKQYnnho",
        "scriptPubKey" : "2102616d968e135f6e2488c5e45fb08c99838ad7f5ddd918d4d98a23a12b218fdc9bac",
        "amount" : 50.00000000,
        "confirmations" : 101
    },
    {
        "txid" : "c2b30d0a5aae70d138fba3496bbbd95cd4dffb25b98a096c5421e19f9dc38816",
        "vout" : 0,
        "address" : "mjUT9N2VaqyJ1xQkeraEWd7fu42ufCsAjr",
        "scriptPubKey" : "76a9142b6756910ee623e6d21116e7c334c08577b4fa0888ac",
        "amount" : 40.00000000,
        "confirmations" : 1
    },
    {
        "txid" : "c2b30d0a5aae70d138fba3496bbbd95cd4dffb25b98a096c5421e19f9dc38816",
        "vout" : 1,
        "address" : "mrhvdMRRcBeapkyrHjiYrCZQJSzwPXvLXw",
        "account" : "",
        "scriptPubKey" : "76a9147abc9143e394ba459bb9c5d55f5cf9471c29d78688ac",
        "amount" : 10.00000000,
        "confirmations" : 1
    }
]
~/.b/t/b/index ❯❯❯ bitcoin-cli -regtest createrawtransaction '''
    [
      {
        "txid": "0b95cf0e1b6c9579e53ae147a497c49e635091f53aa996e7e27c87fce388cd0e",
        "vout": 0
      }
    ]
    ''' '''
    {
      "mrhvdMRRcBeapkyrHjiYrCZQJSzwPXvLXw": 49.9999
    }'''
error: Error parsing JSON:'
    [
      {
        "txid": "0b95cf0e1b6c9579e53ae147a497c49e635091f53aa996e7e27c87fce388cd0e",
        "vout": 0
      }
    ]
    '
```
# 

Here's what the documentation says:

> bitcoin-cli -regtest createrawtransaction '''
>     [
>       {
>         "txid": "'$UTXO_TXID'",
>         "vout": '$UTXO_VOUT'
>       }
>     ]
>     ''' '''
>     {
>       "'$NEW_ADDRESS'": 49.9999
>     }'''
> 01000000017b1eabe0209b1fe794124575ef807057c77ada2138ae4fa8d6c4de\
> 0398a14f3f0000000000ffffffff01f0ca052a010000001976a914cbc20a7664\
> f2f69e5355aa427045bc15e7c6c77288ac00000000

**Comment by Hiblet** [comment]
I had the same issue, eventually it came down to removing single quotes, and escaping double quotes... bitcoin-cli -regtest createrawtransaction [{\"txid\":\"c6343009c5d73572f750359480ae95170a00cfb41063f8cd70e1c14d06e8776c\",\"vout\":0}] {\"myf8U7KUzidun3WzjK2WM4nYVyE1ZkpSGH\":49.9999}

**Comment by efootstep** [comment]
Hey guys, I am facing same issue of json parser, I tried various ways but not able to parse json. I am using windows 10 command prompt.
Kindly help me for fixing this issue. My learning process stuck because of this.

thanks in advance

**Comment by efootstep** [comment]
Hey guys,
I fixed this issue for windows cmd by using following command format

bitcoin-cli -regtest createrawtransaction "[{\"txid\":\"dd9a2ef1fe2a823ad240269443ee0f38eb9710d7427d63bcf3f91884503b3553\",\"vout\":0}]" "{\"n4dq9cvEpUKtasXohdYFmQHvuRLynza1eY\":23.35}"

Thanks
