### ISSUE TITLE
Document configuration parameters for running Bitcoin Core

### ISSUE THREAD

**Issue by jlopp** [bitcoin-dot-org/bitcoin.org#806]
I think this would be really useful to add as a section to the "Running a Full Node" guide. Basically an in-depth guide to each configuration parameter that you can pass as a command line argument or add as a line to bitcoin.conf

Basically, a better version of this document: https://en.bitcoin.it/wiki/Running_Bitcoin

**Comment by harding** [comment]
@jlopp you're not the first person to request that, and I think it's increasingly needed as the config parameters seem to be both increasing in number and becoming more complex (including the complexity of interaction between params).

When I re-wrote the RPC section last year, I [had the idea](https://github.com/bitcoin/bitcoin.org/pull/693#issuecomment-68318385) that we might move them into a separate document dedicated to just Bitcoin Core API-like stuff, and I think that'd be an obvious place for documentation of the config params.

However, I'd be interested in hearing what other people think about merging the moderately-technical full node docs with a highly-technical API doc.  On first thought, I think I'd like to work on making the full node docs less complex and less detailed (as much as possible), so maybe we'd just link from the full node docs to the Bitcoin Core docs config params section for anyone geeky enough to use non-defaults.

**Comment by jlopp** [comment]
It makes sense to me for the configuration guide to exist in the technical developer docs; a link from the Full Node guide should suffice for node operators who want to look under the hood.

**Comment by luke-jr** [comment]
Configuration is more end-user than technical IMO. Why not improve the existing wiki page?

**Comment by jlopp** [comment]
I think the average user doesn't configure their node much; the defaults work fine for most people. But there are 90+ configuration options that can come in handy for developers. Improving the wiki page would be nice, but I'd like to see the config options added as part of the comprehensive technical docs on bitcoin.org.

**Comment by luke-jr** [comment]
That the average user fails to configure their own node is a problem for Bitcoin because it centralises node policy on a set of defaults.

**Comment by harding** [comment]
@luke-jr centralized policy decisions are indeed a problem, but asking average users to spend at least several hours learning enough about Bitcoin so that they can make well-informed decisions about how to configure their own policy seems like a massively suboptimal solution.  Surely there is way to encourage useful non-conformity without expecting network node operators to be experts.

Regarding Wiki versus GitHub, I haven't made up my mind.  With Saïvann busy on other projects, my largish PRs to the dev docs are going unreviewed for a month or more at a time, so maybe it's time to consider doing more work on the Wiki where content can be posted without prior review.

**Comment by jlopp** [comment]
If you're being blocked because there is no one around to review your PRs, it sounds like we need to find some new people to review them. I'd be happy to help out if that's an option.

**Comment by saivann** [comment]
@jlopp Yes please, it's always very useful to have more reviewers!

@harding Please feel free to merge without waiting for too long for my reviews. I'll happily come back later and submit late pull requests if I find any issue. Thanks for your patience and I don't want to be blocking your nice work!

**Comment by harding** [comment]
@jlopp indeed, more reviewers are always massively appreciated.  If there's anything we can do to make it easier for you to find and review just the stuff you're interested in, please let me know.

@saivann sorry, I didn't mean at all to imply that you were blocking my work!  I was thinking more about the Wiki as an alternative source of reviewers.  Posting new content to the Wiki, especially when there's already a Wiki page for the subject, could be a great way to attract reviewers---and some months later, I could always copy it back here.
