### ISSUE TITLE
CoinAgenda at CE Week

### ISSUE THREAD

**Issue by mollywaldron** [bitcoin-dot-org/bitcoin.org#851]
- date: 2015-6-24-25
      title: CoinAgenda at CE Week
      venue: "Metropolitan Pavilion"
      address: "125 West 18th Street"
      city: "New York City" 
      country: "USA"
      link: "http://www.coinagenda.com/ceweek/CoinAgenda_at_CEWeek.pdf"

**Comment by harding** [comment]
@mollywaldron thanks for submitting.  This looks like an advertisement for companies to buy a table in your pavilion, but what we're looking for on the events page is information for people who want to attend the event.

Maybe you can add a page to your site describing how to find the CoinAgenda pavilion on the show floor?

**Comment by mollywaldron** [comment]
Hi @harding - does this work? http://www.businesswire.com/news/home/20150514005973/en/CE-Week-York-Explores-Future-Money-Retail#.VVu6cvlVhBd

and/or www.CoinAgenda.com 

Thanks!

**Comment by mollywaldron** [comment]
@harding The event is also listed on CE Week's website: http://www.ceweekny.com/updates/ce-week-new-york-explores-future-of-money-and-retail/

Anything else you need from us to get this posted? Thanks!
