### ISSUE TITLE
CoinAgenda

### ISSUE THREAD

**Issue by mollywaldron** [bitcoin-dot-org/bitcoin.org#852]
- date: 2015-10-28-30
      title: "CoinAgenda"
      venue: "TBD"
      address: "TBD"
      city: Las Vegas
      country: USA
      link: "http://www.coinagenda.com/"

**Comment by harding** [comment]
@mollywaldron thanks for submitting your event.  We need the address in order to list the event.  I'll leave this issue open and you can comment here once you have the address.
