### ISSUE TITLE
Making a tutorial for installing a node on Mac

### ISSUE THREAD

**Issue by jabo38** [bitcoin-dot-org/bitcoin.org#862]
This link told me to make an issue if I am willing to help make a tutorial for Mac.  I am. :-) 
https://bitcoin.org/en/full-node#mac-os-x-instructions

**Comment by harding** [comment]
@jabo38 awesome!  I wrote up some instructions here https://github.com/bitcoin/bitcoin.org/issues/763#issuecomment-75582514 when we were looking for help for Windows 8; and here https://github.com/bitcoin/bitcoin.org/issues/825 is the conversation that resulted in us adding those instructions.  Mac OS X should be basically the same, except that the installation instructions will obviously be different.

If you have any questions, please let me know.  Thanks again!

**Comment by jabo38** [comment]
@harding I will work on it this week in my off time.

**Comment by harding** [comment]
Fixed in 02243f6d2a0a526b40bede9736fb6b49fc464137
