### ISSUE TITLE
mSIGNA full node?

### ISSUE THREAD

**Issue by luke-jr** [bitcoin-dot-org/bitcoin.org#878]
According to https://github.com/bitcoin/bitcoin.org/pull/390#issuecomment-59951638, mSIGNA can use any remote bitcoin node, so I'm not sure why it's classified as a full node itself...?

**Comment by gurnec** [comment]
There is a distinction, however it's a bit subtle (see #645).

I think there's a general "grade wallets based on their default and most common configuration" rule, which is why e.g. GreenAddress desktop gets a checkFailTransparencyRemote score. (It has a Google Chrome App available for install which would earn it a checkPassTransparencyOpenSource score, however because it's also available via a website, it's likely desktop users will just use the website therefore it's graded based on that.)

Perhaps the distinction should be made more clear? Unbold and/or change the "Full Validation" text?

**Comment by harding** [comment]
I think the concerning part of the comment @luke-jr linked to is, "mSigna a highly-secure lightweight wallet that is not dependant on a complete local copy of the blockchain (like Armory)"

Their [getting started guide](https://ciphrex.com/docs/Bitcoin_Vault-Getting_Started.pdf) says, "By  default,  mSIGNA will  attempt  to  connect  to  a  bitcoin  node  running  on  localhost  (i.e.  a  local  running  instance  of  BitcoinQt). [...]  If you  would  prefer  to  connect  to  a  remote  bitcoin  node,  you  can  change  the  IP  address  and  port  under  Network -­‐>Settings [...] mSigma only  connects  via  the  peer-to-peer  protocol  and  does  not  require  any  special  RPC  access to  other  nodes." 

That means our text---"This wallet requires you to install full node software that validates [...] transactions"---certainly needs to be changed.  Maybe we should create a new category of "Full Validation Compatible"?

@CodeShark, @saivann, @crwatkins --- comments appreciated.

**Comment by crwatkins** [comment]
We are running into more wallets with many different modes (e.g. some wallets can function in both plain HD and multisig with a server) such that a single scoring cannot apply to all modes of a single wallet.  The same issue occurs when wallets can work both with and without a dedicated hardware component.  I predict that in the near future we will be establishing multiple scoring for the same wallet working in different modes.  Until then, I think we will have some scoring that is not totally accurate in all modes.  As long as the wallet will actually operate with the scoring we list, I'm OK with that for now.  
In general, I'm hesitant to create new scoring or we are likely to approach as many scores as wallets.

**Comment by saivann** [comment]
Personally, I'd be fine if the text was adjusted to "This wallet *uses* a full node software that validates [...] transactions by default". I think this would also reflect Armory correctly.

But sure, the increasing diversity of wallets are making them harder to categorize and compare. I agree with @crwatkins that it's acceptable if scores do not cover everything in the short run. Like @gurnec mentioned, thus far I thought the most appropriate and simplest solution was to reflect what the user gets by default.
