### ISSUE TITLE
Mycelium is not an open source wallet.

### ISSUE THREAD

**Issue by GandalfBitcoin** [bitcoin-dot-org/bitcoin.org#896]
The following description on bitcoin.org is not true: "Mycelium Bitcoin Wallet is an open source wallet".

Actually, the Microsoft Reference Source License ( [MS-RSL](https://en.wikipedia.org/wiki/Shared_source) ) used by Mycelium is the most restrictive of the Microsoft Shared Source licenses. We should not consider MS-RSL as an [open souce](http://www.quora.com/Why-is-MS-RSL-Microsoft-reference-source-license-not-considered-an-open-source-license) license.

So the description open source is totally wrong, and we should correct this. Otherwise it may cause misunderstanding.

**Comment by saivann** [comment]
Agreed that "open source", while technically true, commonly also refer to a free license and is misleading (that's why one associated score was previously rewritten to "developers of this wallet publish the source code"). No one apparently catched this one. How about we just drop this part and say instead "Mycelium is a wallet for Android designed for security, speed, and ease of use."

ping @apetersson

**Comment by saivann** [comment]
@GandalfBitcoin I'd appreciate you avoid using bold or uppercase in pull request (equivalent to screaming) and avoid an aggressive tone as much as possible. There is no Wikipedia-like code of conduct on this repository, but if there would be one, I guess this would be a fairly common guideline :) . We all try to be collaborative, thanks in advance.

**Comment by GandalfBitcoin** [comment]
@saivann ok. sorry for the bold and uppercase.

**Comment by theymos** [comment]
Maybe replace "open source" with "source-available" where appropriate.

**Comment by saivann** [comment]
@theymos That would become "Mycelium Bitcoin Wallet is a source-available
wallet".

Are you sure it's understandable? If so, I'm also fine with it.

@GandalfBitcoin Thanks!

**Comment by theymos** [comment]
@saivann That sentence is entirely understandable, though it's kind of clunky as an opening sentence. (I didn't previously look into where that sentence appeared.) Your suggestion is probably better.

**Comment by schildbach** [comment]
You could also write "…is open source, but not free software" to make it clearer.

**Comment by jandreske** [comment]
I saw "The source code is available for inspection" somewhere, which also includes hints at why this question is important to many.

**Comment by GandalfBitcoin** [comment]
MS-PL and MS-RL are considered as open source by the Open Source Initiative and free by the Free Software Foundation.

The other Microsoft Shared Source Licenses have various limitations that make them non-Open Source according to the Open Source Initiative and non-Free to the Free Software Foundation.

MS-RSL is the most restrictive of the Microsoft Shared Source licenses.

https://en.wikipedia.org/wiki/Shared_source

**Comment by gurnec** [comment]
@schildbach Calling it "not free" software may be confusing to those unfamiliar with the beer/freedom distinction, and could cause many people to think that Mycelium charges a fee.

I think saivann's version sounds best so far, but any version that doesn't imply open source is better than what's there now.

**Comment by harding** [comment]
Agreed with @saivann's proposal being the best so far.  Let's see what Mycellium developers @apetersson or @DanielWeigl have to say.

**Comment by apetersson** [comment]
Hi. personally, i would love to see an open source Mycelium, to avoid confusing discussions like this one. i have made sure that any additional component beyond the UI core was licensed as apache2.0, that might open the door for a license change in the future.

i'm A-OK with "Mycelium Bitcoin Wallet is a source-available wallet" on bitcoin.org.

i think most users and bitcoin experts are generally ok with the MS-RSL license. My proposal would be to leave out the licensing from the description on bitcoin.org, that opens up the description length to include other features.

For example:

"Mycelium Bitcoin Wallet for Android is designed for security, speed, and ease of use. It has unique features to manage your keys and for cold storage and offers compatibilty with Trezor, MultibitHD and others."

**Comment by saivann** [comment]
Thanks all for your comments!

I've just opened  pull request #902 with text from @apetersson (since the description is going to be re-translated anyway, I see no issue with including the other changes).

**Comment by saivann** [comment]
Closing the issue as the pull request is now merged.
