### ISSUE TITLE
New event: Bitcoin Wednesday 2-Year Anniversary Conference

### ISSUE THREAD

**Issue by generalseven** [bitcoin-dot-org/bitcoin.org#906]
- date: 2015-07-01
      title: "Bitcoin Wednesday 2-Year Anniversary Conference"
      venue: VondelCS: The media, culture and broadcasting center in Amsterdam for national broadcaster AVROTROS.
      address: Vondelpark 3
      city: "Amsterdam"
      country: "The Netherlands"
      link: "http://www.bitcoinwednesday.com/event/bitcoin-wednesday-25/"

**Comment by harding** [comment]
@generalseven hi, could you let us know when you have an address for the event?  Thanks.

**Comment by generalseven** [comment]
@harding Location is officially announced.  Please post!

**Comment by generalseven** [comment]
@harding This is a recurring event on the first Wednesday of every month -- already 2 years running.

Should I make a separate issue for each event or can you handle it like this?

**Comment by harding** [comment]
@generalseven thanks for getting back to me with the location.  The event should be listed on the website within the next 15 minutes.

We don't currently do recurring monthly events---we pull data from Meetup.com to list those.  You may open an issue for subsequent events if you want.
