### ISSUE TITLE
Blockchain Incredible Party

### ISSUE THREAD

**Issue by jrh11** [bitcoin-dot-org/bitcoin.org#909]
- date: 2015-07-02
      title: "Blockchain Incredible Party"
![560x292](https://cloud.githubusercontent.com/assets/13006006/8290896/75573bc4-192e-11e5-971f-dfe68cba4ec5.png)

      address: "Grecheskaya str., 1a — HUB Odessa, 2-rd floor"
      city: "Odessa "
      country: "Ukraine"
      link: "http://bip001.com "

**Comment by harding** [comment]
@jrh11 thanks for submitting the event---I love the name!  It should be listed on the site within the next 15 minutes.

**Comment by jrh11** [comment]
Thanks a lot! Would you like to visit this event?

2015-06-23 20:07 GMT+03:00 David A. Harding <notifications@github.com>:

> @jrh11 <https://github.com/jrh11> thanks for submitting the event---I
> love the name! It should be listed on the site within the next 15 minutes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitcoin-dot-org/bitcoin.org/issues/909#issuecomment-114574254>
> .
>



-- 
С уважением,
Евгения Брошеван

**Comment by harding** [comment]
Alas, I'm in New Jersey, USA---rather far from Ukraine.  :-)  I do see that @greenadress is attending, so I hope you all have a blast!

**Comment by jrh11** [comment]
If you have changed your mind, we will be happy to see you!


2015-06-23 21:04 GMT+03:00 David A. Harding <notifications@github.com>:

> Alas, I'm in New Jersey, USA---rather far from Ukraine. :-) I do see that
> @greenadress is attending, so I hope you all have a blast!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitcoin-dot-org/bitcoin.org/issues/909#issuecomment-114592339>
> .
>



-- 
С уважением,
Евгения Брошеван
