### ISSUE TITLE
III Brazilian Bitcoin Conference

### ISSUE THREAD

**Issue by wladcrippa** [bitcoin-dot-org/bitcoin.org#911]
- date: 2015-07-18and19
      title: "III Brazilian Bitcoin Conference"
      venue: "Centro de Inovação ACATE Primavera"
      address: "Rodovia SC 401, Km 4 | Bairro Saco Grande"
      city: "Florianopolis"
      country: "Brazil"
      link: "http://www.bitconf.com.br"

**Comment by harding** [comment]
@wladcrippa thanks for submitting your event!  It  should appear on the website within 15 minutes.

**Comment by rasrenato** [comment]
Boa noite 
 Gostaria de saber como faço pra fazer mineração
