### ISSUE TITLE
Blockchain Incredible Party (BIP001)

### ISSUE THREAD

**Issue by kravchenkopo** [bitcoin-dot-org/bitcoin.org#913]
- date: 2015-07-02
      title: "Blockchain Incredible Party"
      venue: "Hub Odessa"
      address: "Grecheskaya str. 1a"
      city: "Odessa"
      country: "Ukraine"
      link: "http://bip001.com"

**Comment by harding** [comment]
@kravchenkopo thanks for submitting the event---I love the name!  It should be listed on the site within the next 15 minutes.
