### ISSUE TITLE
Mobile Payments Exchange

### ISSUE THREAD

**Issue by gabrielasantosiqpc** [bitcoin-dot-org/bitcoin.org#926]
- date: 2015/11/08
      title: Mobile Payments Exchange
      country: United States
      link: www.mobilepaymentsexchange.com
![25655 001_mobile payments exchange logo](https://cloud.githubusercontent.com/assets/13103883/8410006/8b84ae02-1e49-11e5-8c4f-86097d242a7c.jpg)

**Comment by coderwill** [comment]
@gabrielasantosiqpc hello, we need a venue to list this on bitcoin.org - could you please provide that information? i noticed it appears it isn't yet available on the website:
http://www.mobilepaymentsexchange.com/venue

**Comment by gabrielasantosiqpc** [comment]
We not have a venue confirmed yet. But it will be on the West Coast, United States. Could you use that for the Venue, for now?

**Comment by harding** [comment]
@gabrielasantosiqpc I think we'd really prefer at least a city and state.  You can get back to us whenever you have this information available.  Thanks,
