### ISSUE TITLE
bitcoin.com duplicating bitcoin.org

### ISSUE THREAD

**Issue by saivann** [bitcoin-dot-org/bitcoin.org#928]
@jonwaller @jmaurice It seems like your team intends to make a marketing website of bitcoin.com, at the moment, more or less as a copycat of bitcoin.org.

Since the website is going to host completely different content, could it be possible for your team to use a distinctive visual identity (e.g. logo, font, layout), much like what weusecoins and bitcoins.com did in the past? This way people could at least pick the website they find the most useful or trustworthy, and this can avoid quite a lot of confusion and issues.

Otherwise I think this makes both sites look sketchy and can be misleading to people. I'm also concerned about other issues. For instance, I remember WeUseCoins served outdated Bitcoin Core links for quite a while in the past. That kind of issue would be much more problematic if the website can be confused for bitcoin.org on a nearly identical domain name, like now. (Edit: [already happening](https://www.reddit.com/r/Bitcoin/comments/3bri4j/only_1684_nodes_282_run_0102_fixing_serious/csoxjr4)...)

The advertizing-focused nature of the website also increases the risk of promoting risky links, even if you are very careful (this is something I was also worried about when considering that option for bitcoin.org). At the very least, taking this risk on your shoulders only would be appreciated.

**Comment by coderwill** [comment]
It also seems the "Choose Your Wallet" section has been revised to only show the mobile and web wallets that Roger Ver is invested in (Luxstack and Blockchain.info).

**Comment by coderwill** [comment]
Upon further review, I believe this is no different than a phishing attempt. Bitcoin.com has duplicated Bitcoin.org to mislead users into products and services specifically omitted in the past due to gaping security issues and lost BTC (e.g. Blockchain.info). I would recommend that we all report Bitcoin.com as a phishing site at the following places:

* email [abuse@namecheap.com](mailto:abuse@namecheap.com) and Cc [abuse@enom.com](mailto:abuse@enom.com) (namecheap is an enom reseller), let them know a *phishing* site has been placed on bitcoin.com, and send them the link to bitcoin.org as the reference.
* spend 30 seconds to [fill out this form](https://www.google.com/safebrowsing/report_phish/) on google.com, which will help to get bitcoin.com removed bitcoin.com from the google search index.
* spend another 30 seconds to [fill out this form](http://toolbar.netcraft.com/report_url) on netcraft, which works with various third parties block websites at the dns level.

Here is a reference letter, to use on the above links. Please feel free to copy and paste or modify it to your liking. It is important that the 3 actions above be taken so that we can ensure that Bitcoin.com is blocked at the registrar level and also removed from the Google Index - as Bitcoin.org is the number one search result for Bitcoin, each day that Bitcoin.com continues to run in this way is another day of extremely misleading information and potential security risks to new and existing users:

>To Whom It May Concern:

>[Bitcoin.com](http://Bitcoin.com), a domain with [Enom](http://enom.com/) through [NameCheap](http://namecheap.com) has recently been redesigned to look almost identical to [Bitcoin.org](http://bitcoin.org) the original Bitcoin domain and top resource for new users in an attempt to mislead users.

>Many people have heard in the past about Bitcoins being hacked or stolen. By allowing Bitcoin.com to continue to operate in this way it puts users at risk of exactly that, as Bitcoin.com is attempting to route users into unauthorized products and services (e.g. [Bitcoin.com Wallet Page](https://www.bitcoin.com/en/choose-your-wallet) vs [Bitcoin.org Wallet Page](https://bitcoin.org/en/choose-your-wallet)) with known security issues. Any wallet on Bitcoin.org goes through a rigorous audit to ensure that only those that meet the utmost standard are included. 

>Bitcoin.com is intentionally duplicating virtually all of Bitcoin.org content and misleading users into other products and services - the very definition of phishing.

>As a service provider who prevents these types of occurrences from happening to protect users from being mislead to put them at risk, your prompt assistance is requested at your earliest convenience in handling this matter.

Copied: @Cobra-Bitcoin @theymos

**Comment by harding** [comment]
@coderwill although I agree that the visual similarity between the sites is inappropriate, I'd prefer to see if we can work this out professionally.

@jonwaller @jmaurice if you don't have time to make changes to you site's cloned style, I'd be happy to donate an hour or two of my time (at no charge) to provide you with a basic patch that makes your site look somewhat different.  Please let me know if you think this is a reasonable way forward.

**Comment by harding** [comment]
@jonwaller @jmaurice please fix this page immediately: https://www.bitcoin.com/en/download

People are trying to download the Bitcoin Core binaries from your site: https://www.reddit.com/r/Bitcoin/comments/3bri4j/only_1684_nodes_282_run_0102_fixing_serious/csoxjr4

**Comment by magmahindenburg** [comment]
Hi, I'm Magma Hindenburg, one of the people who has been working on bitcoin.com. I have read your concerns and I will address them asap. I will start with the download link.

**Comment by harding** [comment]
@magmahindenburg thank you!

**Comment by magmahindenburg** [comment]
I have changed to the download page links to bitcoin.org, and currently the front page is redirected to our news page with original content.

**Comment by ABISprotocol** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

I just saw for the first time what bitcoin.com was doing (in terms of
its duplication of bitcoin.org - which would make it easy for people
who come upon bitcoin.com to mistake it for bitcoin.org - and in terms
of bitcoin.com's promotion of very specific wallets)

To me, bitcoin.com has all the characteristics of a scam site.  It
doesn't matter to me who is behind it and how they are "addressing"
this issue if this is how they do business.

As such, I fully agree with moving forward with @saivann's and
@coderwill's suggestions above.

On 07/01/2015 06:24 PM, Magma Hindenburg wrote:
> Hi, I'm Magma Hindenburg, one of the people who has been working
> on bitcoin.com. I have read your concerns and I will address them
> asap. I will start with the download link.
> 
> — Reply to this email directly or view it on GitHub 
> <https://github.com/bitcoin-dot-org/bitcoin.org/issues/928#issuecommen
t-117868596>.
>
> 
- -- 
http://abis.io ~
"a protocol concept to enable decentralization
and expansion of a giving economy, and a new social good"
https://keybase.io/odinn
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQEcBAEBAgAGBQJVlLr1AAoJEGxwq/inSG8C2OIH/09GHt22l0W5PnIPT1qjVBpt
GSFhDYgMT9AvqAladhGUmCHKRCfIOZkfbeWrm3pAhiOJvAxjGvQ3kjU9GWDlEmbe
xOuNeNwdRp4rcFuOJZKUQX3SA23pI7/8/8XZ4nAQJ2y+pFvq2iqGr36PcDK+kfMx
aHZUpUlZ2IQqcO0w12QmArDidzLhM0KIzhYC/z3gOf1MUgw2rWiQ1Q4XnmcMXj2d
jzlH0/eWomkNcihY7ZXc5ThTmy5Zxre3uEEWrVkFyi0/Hp6fzkyBNwzEVFoMnzNE
6CNimNoeCO4FTEI+8QmEb71w0CVSekn4MQiBV8WEpNXY5nX22/nSYSOlhheO6bg=
=SdRw
-----END PGP SIGNATURE-----

**Comment by jmaurice** [comment]
@saivann @harding 

Hi Guys,

After the very public OKCoin breach of contract to manage bitcoin.com, we had to get a new site up and running on bitcoin.com ASAP. This is why we forked bitcoin.org, to get some content up right away.

However, we now have several people working full-time to make the site into something totally new. To address @saivann 's concerns, we are working on a "distinctive visual identity", and it will be coming together in the next few days - weeks.

I believe we have addressed your immediate concerns of the download links now pointing to bitcoin.org - if there is anything else please don't hesitate to contact us directly by email on IRC.

Best Regards,
J. Maurice (@wiz)

**Comment by harding** [comment]
@jmaurice thanks for addressing our immediate concerns!  I just submitted https://github.com/bitcoin-portal/bitcoin-portal-content/pull/1 fixing some less urgent concerns I had about people confusing the two sites and two sets of contributors.  It's a fairly large patchset (part was automatically generated with `sed`), so feel free to take your time to review it.

If I can think of anything else specific that needs to be changed, I'll open an issue or a PR on your repository.

Thank you and your team again for working with us on this.

**Comment by ABISprotocol** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Nothing much has changed... see
https://www.bitcoin.com/en/getting-started
and
https://www.bitcoin.com/en/choose-your-wallet
as of July 2, 2015, still basically "same-as" bitcoin.org
Same concerns as before.  I don't see any effort here to make the page
different.  Again, I support @coderwill's suggestion as described
earlier in this thread (redundant, I know, but there you have it).

On 07/02/2015 06:17 AM, David A. Harding wrote:
> @jmaurice <https://github.com/jmaurice> thanks for addressing our 
> immediate concerns! I just submitted bitcoin-portal#1 
> <https://github.com/bitcoin-portal/bitcoin-portal-content/pull/1>
> fixing some less urgent concerns I had about people confusing the
> two sites and two sets of contributors. It's a fairly large
> patchset (part was automatically generated with |sed|), so feel
> free to take your time to review it.
> 
> If I can think of anything else specific that needs to be changed,
> I'll open an issue or a PR on your repository.
> 
> Thank you and your team again for working with us on this.
> 
> — Reply to this email directly or view it on GitHub 
> <https://github.com/bitcoin-dot-org/bitcoin.org/issues/928#issuecommen
t-118029418>.
>
> 
- -- 
http://abis.io ~
"a protocol concept to enable decentralization
and expansion of a giving economy, and a new social good"
https://keybase.io/odinn
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQEcBAEBAgAGBQJVlckwAAoJEGxwq/inSG8CxS8H/jPYNk4eaflYyq2WZtq+GTuR
1rMjVSWnpQ7W6Dr5PVBzlhSQvNXBGzwss6bnwH82rxYx/f/VYHdX33mxqHrqyzTz
oEtLbNpnYyYLS7U8SbBEvFw/G6dNg6UbK7gHOEdKvISjgQ9xQ28p9nVLQGmn/g+O
n3GLQa2cCfwgFLaSZpaOdOyv6YBKCIn5zqimCyrQ3Yeo5M14Jts+kL69n7DQnAgi
wPivQyPIKkmKolym8gRsoCoQzGbHXhyjOhBEXJErq+r6U/3Fz3hkETtYkY+4gr6J
tHlnCcE4FXEsII452Bal37qspQrzaWhhvMyIiXiCfOv7W9/USB4L4hClQ+w1AqU=
=PA91
-----END PGP SIGNATURE-----

**Comment by harding** [comment]
@ABISprotocol I see significant progress towards making the .com site different, and we've received what I consider to be assurances in good faith that they have other differentiating changes planned.

I can't speak for the other .org contributors, but I knew from the start that my MIT-licensed contributions could be used this way, and I accepted it.  As long as they aren't deliberately trying to confuse .com visitors into thinking they're on the .org site, I don't think it's appropriate to report them as a phishing site.

I do think it's regretful that some peoples' first impression of Bitcoin will be so heavily commercialized, but I also think having such stark contrast between .com and .org has always served us well in the past.  I've never actually seen anyone link to the .com site, but the .org site has so many backlinks that we [accidentally rank well](https://www.google.com/?gws_rd=ssl#q=pdf) for things that have nothing to do with Bitcoin.

I think our best bet is for .org to continue focusing on providing high-quality, peer-reviewed, and dispassionate information about Bitcoin, and let .com see how far they get on this nth attempt to monetize the .com domain.

If nobody has any major issues left, we should probably close this issue.  We can reopen it if new major problems are discovered.

**Comment by saivann** [comment]
@harding Agreed, maybe we could just wait for the updated layout to go live and then close the issue?

Additionally, if someone dislikes something and wish to suggest improvements, the bitcoin.com team seems happy to receive and consider feedback.

@jmaurice I don't know if that is intentional, but GitHub issues are disabled on your repository. Enabling that feature can allow people to report bugs and issues. This is especially useful for non-developer contributers, and helped us quite often in our case.

**Comment by ABISprotocol** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

My recommendation would be to keep this issue open well beyond when
their updated layout goes live.  I'm willing to bet there will be
further issues for us to comment on at that time.  The fact that
Github issues aren't enabled in their repository is not encouraging,
but that could be changed easily enough...

On 07/02/2015 07:32 PM, saivann wrote:
> @harding <https://github.com/harding> Agreed, maybe we could just
> wait for the updated layout to go live and then close the issue?
> 
> Additionally, if someone dislikes something and wish to suggest 
> improvements, the bitcoin.com team seems happy to receive and
> consider feedback.
> 
> @jmaurice <https://github.com/jmaurice> I don't know if that is 
> intentional, but GitHub issues are disabled on your repository.
> Enabling that feature can allow people to report bugs and issues.
> This is especially useful for non-developer contributers, and
> helped us quite often in our case.
> 
> — Reply to this email directly or view it on GitHub 
> <https://github.com/bitcoin-dot-org/bitcoin.org/issues/928#issuecommen
t-118214127>.
>
> 
- -- 
http://abis.io ~
"a protocol concept to enable decentralization
and expansion of a giving economy, and a new social good"
https://keybase.io/odinn
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQEcBAEBAgAGBQJVlfrKAAoJEGxwq/inSG8C21cH/jtPHP3DXtAdYnwCAkGU3PPh
muWsycnIPwh6UOk5N4TP18TPaYUBksb5+Rl2tkM9BVggYCP/cRd/uiJLaiAL4hdM
wjCnGwYe+FF/gjzQflNIuapjjyEzo7AwRRamkkh3Vvw4G/M4fhB4stx9o8bQpPnV
tKIbPGsLpcWXbbFj+R55A4ULnq3dMeHEhau4xr692yRx3oLOJ6D5PaLqQgFzWDlh
yZlQDIyJvrZR/yd8S6Bl5vvMIqbbMyohXiLQCvi88o13Vq89Ef4LDHTK3Pw5elsL
w5AnAgmtuGzjUB3niQQZzje5Fnf2xcxCWJ10jcqJfxM11PI0XW0MAnCv5qR4EWg=
=fEWD
-----END PGP SIGNATURE-----

**Comment by jmaurice** [comment]
@saivann Not sure why it was disabled, but I've enabled issues for our repo now. Thanks for pointing that out!

**Comment by harding** [comment]
.Com have significantly updated their layout, so per @saivann's comment above and a quick consultation with @coderwill on IRC, I'm closing this issue.

@jmaurice thanks again to you and your team for working with us on this.

**Comment by coderwill** [comment]
@jmaurice thanks.

**Comment by theymos** [comment]
FYI: I removed the ban of bitcoin.com from /r/Bitcoin and bitcointalk.org, since it now seems to be sufficiently distinct from bitcoin.org.

**Comment by pobri19** [comment]
@coderwill I don't think bitcoin.org is trustworthy either given their resistance to a hard fork even if it has full public support (Bitcoin-XT) https://bitcoin.org/en/posts/hard-fork-policy -- so I won't be reporting bitcoin.com, and I advise others not to do so as well.

**Comment by magmahindenburg** [comment]
FYI: Bitcoin.com has discontinued the fork
