### ISSUE TITLE
New Event: Bitcoin Wednesday

### ISSUE THREAD

**Issue by generalseven** [bitcoin-dot-org/bitcoin.org#930]
date: 2015-08-05
  title: "Bitcoin Wednesday #26"
  venue: VondelCS: The media, culture and broadcasting center in Amsterdam for national broadcaster AVROTROS.
  address: Vondelpark 3
  city: "Amsterdam"
  country: "The Netherlands"
  link: "http://www.bitcoinwednesday.com/event/bitcoin-wednesday-26/"

**Comment by coderwill** [comment]
@generalseven Thanks for submitting this - I've added it to PR #945.

**Comment by saivann** [comment]
Thanks for submitting your event. It should display on bitcoin.org in the next 15 minutes.

**Comment by generalseven** [comment]
@coderwill @saivann Note location change.

**Comment by saivann** [comment]
@generalseven Thanks for notifying us. Both events should be up to date in the next minutes.
