### ISSUE TITLE
Minor issues relating to the alerts system

### ISSUE THREAD

**Issue by harding** [bitcoin-dot-org/bitcoin.org#934]
Issue for tracking minor issues relating to the alerts system.

- @luke-jr suggested making the whole alerts bar clickable, not just the text
- @luke-jr says 901-1189 pixels wide browsers have a horizontal scrollbar
- @harding thinks we should probably setup a collaborative google doc in advance for future alerts
- @harding thinks it might be nice if the YAML header can specify a color for the alert like red, yellow, or green (for resolved alerts)

More issues/feedback welcome.

**Comment by harding** [comment]
Oh, if it doesn't interfere with the google docs thing, it might be nice to have future alerts writable in markdown rather than html

**Comment by saivann** [comment]
**Horizontal scrollbar bug**: I can't reproduce the bug, it may have been fixed previously?

**Google docs**: That may be helpful indeed, although I think we've been pretty efficient. The main point is someone has to coordinate and make decisions within a short time frame and you did it well!

**YAML banner**: I can implement this if you need. Although I thought about this idea previously and concluded that just dropping the alert banner was a clear enough indication that the issue was fixed and much simplier (adding features can sometime play against us in the future as it adds risk for screwing up somewhere). Interested people can read the updated alert post to know the exact status.

**Markdown**: Alerts currently support markdown, I just tested to be sure. I just happens that previous alerts were written in HTML. I think markdown would be more appropriate in the future (faster, fewer risk of syntax mistakes).

**Comment by harding** [comment]
@btcdrak just sent me an email asking for an RSS feed.  I'm pointing him to the [main alerts page]( https://bitcoin.org/en/alerts) that has the link to the existing feed, but I think we could probably do better promotion of the feed on the individual alerts.  (Like how we promote the feed on individual blog posts.)

Also, we should probably test the alerts feed with RSS readers to see how they handle revisions.  My usual feed reader is rather dumb, but I don't know if more advanced feed readers have some way of telling the user that a post has been updated without us having to create what looks like a new post for every update.

More also: just brainstorming, but it might be worthwhile to look into one of those free/cheap rss-to-email services for people who want alerts but don't use feed readers.

**Comment by btcdrak** [comment]
@harding How about something prominent like you have on the blog homepage?

**Comment by harding** [comment]
I don't know if this is practical, but /u/scotty321 on reddit [suggested](https://www.reddit.com/r/Bitcoin/comments/3c305f/if_you_are_using_any_wallet_other_than_bitcoin/csrwzl4) having some way to display what wallets are affected by an alert on the Choose Your Wallet page.

I think maybe a separate page (or `include`-able template) that has access to the YAML from the Choose Your Wallet page might be better.

**Comment by harding** [comment]
@btcdrak yeah, next week, I'll go over all of these suggestions to see specifically how we can improve things.  Right now I just want to capture ideas as they come to us.  (This is the first time we've used a site alert in 15 months, so we don't get a lot of experience with them (which is good for the network at least!).)

**Comment by harding** [comment]
@luke-jr regarding the scrollbar issue, I also can't reproduce it.  I think you previously reported a similar issue on the dev docs.  Could you tell us what browser/version you use?

@saivann regarding google docs, thanks for the complement.  I do think that using docs could be annoying because of formatting issues, but I also hate creating lots of tiny commits to keep everyone updated.  Still, that may be the best way.  I'll think on it.

Regarding coloring the banner, it would be nice to have a yellow banner as well as a red.  (I think this current issue qualifies better as "yellow alert" than "red alert".)  Regarding simply not displaying the alert once the problem is fixed/not critical, I dunno.  How many regular site visitors do you think know about the Network Alerts link in the footer?  I'm thinking that once the alert disappears from the top of the page, most people don't know how to access it again.  I was thinking that displaying a green "problem solved" banner for ~3 days could reassure people---but I'm open to further discussion. (I'll code up a quick idea for color coding and open a PR; we can discuss more there.)

Regarding markdown, great!  I'll update the site docs with that detail plus some tips for creating a good alert based on your suggestions.

**Comment by luke-jr** [comment]
Chromium Version 41.0.2272.118

**Comment by saivann** [comment]
@luke-jr Maybe if you could attach a screenshot and give details as to what pages present that issue, that could be helpful. At this point, I am neither able to reproduce the issue with Chrome or Chromium (43.0.2357.81) on any page I tested.

**Comment by luke-jr** [comment]
http://luke.dashjr.org/tmp/screenshots/snapshot136.png
http://luke.dashjr.org/tmp/screenshots/snapshot137.png

**Comment by harding** [comment]
@luke-jr I was also unable to reproduce the scrollbar problem on Chromium 40.0.2214.91 (Debian version).  I see you have the Stylish installed---is there any chance you're overriding the Bitcoin.org CSS is some way?
