### ISSUE TITLE
New Event

### ISSUE THREAD

**Issue by gonxi** [bitcoin-dot-org/bitcoin.org#942]
- date: 2015-07-18
      title: "avalBit: Pay Paella with bitcoin "
      venue: "Polígono Industrial Plá dels Olivars"
      address: "Av espinoca"
      city: "Valencia"
      country: "Spain"
      link: "http://avalbit.org/actividades/evento-pagar-paella-birras-y-bitcoins/"

**Comment by coderwill** [comment]
@gonxi Thanks for submitting your event - I've added this in PR #945. Saludos!

**Comment by saivann** [comment]
Thanks for submitting your event. It should display on bitcoin.org in the next 15 minutes.
