### ISSUE TITLE
Replace links to outdated BitcoinMining.com

### ISSUE THREAD

**Issue by DotSauce** [bitcoin-dot-org/bitcoin.org#949]
Hello, I would like to suggest replacing the links to BitcoinMining.com (now owned by Butterfly Labs) because it has very outdated and misleading information about Bitcoin mining.

https://bitcoin.org/en/support-bitcoin  ---->  "bitcoin mining"
https://bitcoin.org/en/faq ----> "mining"
https://bitcoin.org/en/resources ----> "BitcoinMining.com"

Here is a great updated guide to start Bitcoin mining:
http://www.coindesk.com/information/how-to-set-up-a-miner/

**Comment by saivann** [comment]
Actually bitcoinmining.com is now owned by Trace Mayer AFAIK.

In general I agree that this website has for long been disappointing. Upon more review of it's content, I am positively surprised to see that there is more mining hardware listed than only ButterflyLabs now. Although I am still very disappointed by ads interfering with the content everywhere and I would be happy to support linking to a better resource.

I can think of two regressions if we start linking to Coindesk. They don't seem to be linking to any list of Bitcoin mining pool and they don't promote p2pool. Do you think they are open to suggestions?

**Comment by DotSauce** [comment]
Ok, I did not realize the site was updated too. It must have been recently done. Sorry for assuming it was still the same, it was like that for a long time. At least it is attempting to be better, but surely it's not the best resource. 

I am sure Coindesk would be open to suggestions, especially if you mentioned wanting to link.

**Comment by saivann** [comment]
@DotSauce Would you have time to ask them, per chance? I don't know if other contributors have any opinion, but I think it wouldn't hurt to consider it. It seems unfortunately rare to find good resources not filled with advertizing to the point where it hurts the content... Coindesk isn't perfect on that front either, but at the very least ads are generally separated from the content.

**Comment by sunnankar** [comment]
@DotSauce The Github repo is available here (https://github.com/sunnankar/bm) and some pull request contributions to help it become a better resource would be greatly appreciated.
