### ISSUE TITLE
BitCoin Core Installation on OS X 10.8+

### ISSUE THREAD

**Issue by joestrusz** [bitcoin-dot-org/bitcoin.org#954]
I noticed there's no instructions for the OS X branch and it told me to create an issue. I can provide screenshots and etc to complete this portion of the FAQ. 

The install is trivial, and works out of the box on 10.8-10.11 from what I have tested on my OS X Server (1,2) and my Mid 2013 Macbook Air.

**Comment by harding** [comment]
@joestrusz that would be great!  Someone else volunteered, but they haven't followed up in almost two months---so I suggest you go for it.  Here were my suggestions to them: https://github.com/bitcoin-dot-org/bitcoin.org/issues/862#issuecomment-105056829

If you have any questions, please don't hesitate to ask!

**Comment by harding** [comment]
Fixed in 02243f6d2a0a526b40bede9736fb6b49fc464137
