### ISSUE TITLE
Update protocol section of docs to reflect v70003

### ISSUE THREAD

**Issue by drazisil** [bitcoin-dot-org/bitcoin.org#958]
https://bitcoin.org/en/developer-reference#protocol-versions

Does not list protocol version 70003 as latest, appears to have not been updated from core v0.9.0

Unsure what changes have taken place.

**Comment by harding** [comment]
@drazisil  My 0.11.0-pre node is still at 70002, and I think master is too.  Where do you see 70003?

**Comment by luke-jr** [comment]
It's a design flaw in [BIP 64 / getutxos](https://github.com/bitcoin/bips/blob/master/bip-0064.mediawiki).

**Comment by drazisil** [comment]
Bitcoin XT 0.10.2

{u'localservices': u'0000000000000003', u'connections': 33, u'subversion': u'/Bitcoin XT:0.10.2/', u'version': 100200, u'relayfee': 0.00011, u'protocolversion': 70003, u'timeoffset': -1, u'localaddresses': [{u'score': 1, u'port': 8333, u'address': u'2002:6cb7:7be6:1:76d4:35ff:fe1d:45b'}], u'networks': [{u'limited': False, u'reachable': True, u'name': u'ipv4', u'proxy': u''}, {u'limited': False, u'reachable': True, u'name': u'ipv6', u'proxy': u''}, {u'limited': False, u'reachable': False, u'name': u'onion', u'proxy': u''}]}

**Comment by harding** [comment]
Oh.  The first paragraph of the [P2P Network section](https://bitcoin.org/en/developer-reference#p2p-network) says:

> This section describes the Bitcoin P2P network protocol (but it is not a specification). It does not describe [...] any network protocol never implemented in an official version of Bitcoin Core.

For the sake of pedantry, I know getutxos/70003 was briefly implemented in Bitcoin Core master before being reverted a few hours later, but I don't feel that really qualifies as being implemented in an official version.  So I don't think this part of the docs is the appropriate place to describe 70003.

**Comment by luke-jr** [comment]
I don't think it's appropriate for the dev docs to focus on a single p2p protocol implementation. OTOH, if XT is going to altcoinfork off in a few days/weeks anyway, maybe not worth the trouble to add it here.

**Comment by harding** [comment]
@luke-jr I don't have any problem with someone adding alternative protocols (there are several I'd like to describe myself, given enough time).  I do think that for simplicity the section that @drazisil linked to should be dedicated to the protocol that Bitcoin Core implements for as long as Bitcoin Core is the reference client.

**Comment by drazisil** [comment]
Understood. I was not aware that 70003 was just XT, I thought it was for all .10.x clients, since it listed Bitcoin Core 0.9.0 as the implementation.

I rephrase my suggestion to update the docs to reflect the current version. Then again, I'm not sure how far away 0.11x is, so may want to hold off.

**Comment by harding** [comment]
@drazisil oh, I think there's some confusion.  I meant "implementation" to mean "first implemented in".  What if I change the header of the table to "Initial Release"?  E.g.:

![screenshot-btcorg localhost 2015-07-11 11-46-07](https://cloud.githubusercontent.com/assets/61096/8634319/cad6d76a-27c2-11e5-8f0c-d5ab9345e312.png)

**Comment by drazisil** [comment]
@harding it would. The confusion mainly stemmed from it looks like each version of core, recently at least, has an updated protocol version to match. So i assumed 0.10 would be 70003 and it just wasn't current.

**Comment by harding** [comment]
@drazisil added in ee554df51923b254c865b750813508e42b3a55bf plus an extra sentence to help make it even more clear.  It should appear on the website within 15 minutes.  Thanks!

**Comment by drazisil** [comment]
@harding looks perfect in the commit. Thank you!
