### ISSUE TITLE
Bitcoin fullnode on my mac

### ISSUE THREAD

**Issue by rameshmanian** [bitcoin-dot-org/bitcoin.org#959]
I would like to run a full node on my mac. If you can provide instructions on how to achieve that, it will be much appreciated.

Thanks
Ramesh

**Comment by harding** [comment]
@rameshmanian it looks like @joestrusz is working on that in issue #954 right now.

I'm going to close this issue since we already have issue #954 open; you can monitor that issue to see when the instructions are ready.
