### ISSUE TITLE
Bitcoin Thrill Day 2015

### ISSUE THREAD

**Issue by martijnw** [bitcoin-dot-org/bitcoin.org#960]
- date: 2015-09-18
      title: "Bitcoin Thrill Day 2015"
      venue: "Walibi Holland"
      address: "SPIJKWEG 30"
      city: "BIDDINGHUIZEN"
      country: "The Netherlands"
      link: "https://thrilldays.bitcoinembassy.nl/"

**Comment by martijnw** [comment]
Thank you!

**Comment by coderwill** [comment]
:+1:
