### ISSUE TITLE
Bitcoin Core 11 Frequent Freezing.  Too Much Freezing both 64 and 32

### ISSUE THREAD

**Issue by Jbitcoinman** [bitcoin-dot-org/bitcoin.org#965]
Is anyone else experienceing the same issue with the latest release.  If so, and you have figured out the kinks can you share your methodology with me so that I can correct it also?

Thanks,

Coinman

**Comment by harding** [comment]
@Jbitcoinman this repository is only for issues related to the Bitcoin.org website.  If you'd like to discuss your problem, the best places in my opinion are the [Bitcoin Talk tech support forum](https://bitcointalk.org/index.php?board=4.0) and the [#bitcoin IRC channel](https://en.bitcoin.it/wiki/IRC_channels).

You can also search for similar problems on the [Bitcoin Core issue tracker](https://github.com/bitcoin/bitcoin/issues) or report a new problem there.  For what it's worth, I never had any problems with the Bitcoin Core 0.11 pre-releases on 64-bit Linux.
