### ISSUE TITLE
Armory/Bitcoin Core/Mac problem

### ISSUE THREAD

**Issue by tommy546** [bitcoin-dot-org/bitcoin.org#970]
Each time I try to run Armory with Bitcoin Core running, Armory closes unexpectedly.

**Comment by harding** [comment]
@tommy546 I'm sorry to hear that.  You can ask for help in the [BitcoinTalk Armory sub-forum](https://bitcointalk.org/index.php?board=97.0) or in the [#bitcoin chatroom](https://webchat.freenode.net/?channels=bitcoin&uio=d4).  If you need to file an issue, you can do that on [their issue tracker](https://github.com/etotheipi/BitcoinArmory/issues/new).

This issue tracker is only for the Bitcoin.org website, so I'm going to close this issue.
