### ISSUE TITLE
End users exposed to low-level detail of change addresses

### ISSUE THREAD

**Issue by luke-jr** [bitcoin-dot-org/bitcoin.org#985]
https://bitcoin.org/en/protect-your-privacy#send

Change addresses are something low-level used by wallet software, and any software that reuses addresses is broken by design. There is no reason users should be exposed to technical details like this...

**Comment by saivann** [comment]
FWIW, address reuse was common when I wrote that text. I'd be fine with dropping it nowadays.

Note; I also considered the following texts about HD wallets to be worth deleting once they're deployed everywhere. I think Bitcoin Core is the only wallet that is holding up keeping these technical details on the website.

https://bitcoin.org/en/secure-your-wallet#backupregular
https://bitcoin.org/en/secure-your-wallet#backupwhole

**Comment by harding** [comment]
ACK on deleting the section at https://bitcoin.org/en/protect-your-privacy#send

The backup text should stay even if Bitcoin Core starts using HD because the wallet's payment details (e.g. label, memo, etc.) still need to be backed up.

**Comment by saivann** [comment]
@luke-jr I just opened PR #986.

@harding Makes sense, although these texts will need to be updated (and perhaps merged together wouldn't be a bad idea), but that's another topic.
