### ISSUE TITLE
I can provide daemon instructions for Win7

### ISSUE THREAD

**Issue by Gyomu** [bitcoin-dot-org/bitcoin.org#988]
As said in title, please feel free to ask if you need screenshots and instructions for Windows 7.

**Comment by harding** [comment]
@Gyomu awesome!  You can just paste or link to them here when done.  I'd prefer they be as close to the [instructions for the Win8 daemon](https://bitcoin.org/en/full-node#win8-daemon) as possible to minimize future changes, but please feel free to write whatever you think is appropriate.  Thanks!

**Comment by Gyomu** [comment]
Made the pull request. I'll let you review and close if everything is satisfactory
