### ISSUE TITLE
allow incoming connections

### ISSUE THREAD

**Issue by ptschip** [bitcoin-dot-org/bitcoin.org#995]
I didn't see in your documentation about running a full node that you stated check the "allow incoming connections" box.  Without that , users won't be running a full node.

**Comment by harding** [comment]
@ptschip that box is checked by default so we don't have any instructions about it, and I think its meaning is clear for anyone who chooses to uncheck it.  (Also, even if you don't accept incoming connections, you're still running a full node if you use Bitcoin Core.)

I don't plan to add any instruction about that box, but I'll leave this issue open for a few days in case anyone disagrees.

**Comment by ABISprotocol** [comment]
I feel this issue should be re-opened to allow for more time to consider the language issues.

**Comment by saivann** [comment]
@ABISprotocol Please let users who have opened the issue comment by themselves if they want to ask for anything for any reason. Asking this repeatedly on various issues is obstrusive and not very helpful in the workflow.

**Comment by ABISprotocol** [comment]
@saivann Repeatedly I have come to issues such as this and found them closed before I even would have a chance to comment on them.  It's an ongoing observation I make in this repository.
