### ISSUE TITLE
Google Chrome reports bitcoin.org site as insecure on Debian

### ISSUE THREAD

**Issue by drazisil** [bitcoin-dot-org/bitcoin.org#998]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=774195

There is a bug in Debian (jessie) that causes NSS-based browsers such as Chrome to prefer SHA-1 certs over SHA-2. In Chrome this leads to reporting the site as insecure.

![screenshot from 2015-08-04 11 49 26](https://cloud.githubusercontent.com/assets/190986/9065378/16798476-3a9f-11e5-9d16-ea0c8787d602.png)

**Comment by drazisil** [comment]
Sorry for the delay in responding to this. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=774195 was closed Wed, 19 Aug 2015, I have updated nss and tested that bitcoin.org shows as secure, closing issue.

**Comment by harding** [comment]
@drazisil thanks a ton for updating this!  I subscribed to the bug, but I must've confused the close email for something else because I don't recall seeing it.  Thanks again!
